// Activity categories — client-safe constants shared by the seed and the UI.

export const CATEGORIES = [
  { key: "wytrzymalosciowe", label: "Wytrzymałościowe", icon: "🏃" },
  { key: "outdoor", label: "Górskie i outdoor", icon: "🏔️" },
  { key: "wodne", label: "Wodne", icon: "🌊" },
  { key: "zimowe", label: "Zimowe", icon: "❄️" },
  { key: "sila", label: "Siła i ciało", icon: "💪" },
  { key: "fitness", label: "Fitness i cardio", icon: "🔥" },
  { key: "druzynowe", label: "Drużynowe", icon: "⚽" },
  { key: "rakietowe", label: "Rakietowe", icon: "🎾" },
  { key: "precyzyjne", label: "Precyzyjne", icon: "🎯" },
  { key: "taniec-walki", label: "Taniec i sztuki walki", icon: "🥋" },
  { key: "motorowe", label: "Motorowe", icon: "🏍️" },
  { key: "umyslowe", label: "Umysłowe", icon: "♟️" },
  { key: "wizualne", label: "Sztuki wizualne", icon: "🎨" },
  { key: "rekodzielo", label: "Rękodzieło", icon: "🧶" },
  { key: "cyfrowe", label: "Sztuki cyfrowe", icon: "🖥️" },
  { key: "artyzm", label: "Artyzm", icon: "🎭" },
  { key: "instrumenty", label: "Instrumenty", icon: "🎸" },
  { key: "kuchnie", label: "Kuchnie świata", icon: "🍳" },
] as const;

export type CategoryKey = (typeof CATEGORIES)[number]["key"];

export const CATEGORY_LABELS: Record<string, string> = Object.fromEntries(
  CATEGORIES.map((c) => [c.key, c.label])
);

// Slug → category. Single source of truth; the seed writes Activity.category from here.
export const CATEGORY_BY_SLUG: Record<string, CategoryKey> = {
  bieganie: "wytrzymalosciowe",
  chodzenie: "wytrzymalosciowe",
  "jazda-na-rowerze": "wytrzymalosciowe",
  plywanie: "wytrzymalosciowe",
  wioslarstwo: "wytrzymalosciowe",
  "rolki-lyzwy": "wytrzymalosciowe",
  "turystyka-gorska": "outdoor",
  wspinaczka: "outdoor",
  narciarstwo: "outdoor",
  golf: "outdoor",
  "trening-silowy": "sila",
  joga: "sila",
  "pilka-nozna": "druzynowe",
  koszykowka: "druzynowe",
  siatkowka: "druzynowe",
  tenis: "rakietowe",
  "tenis-stolowy": "rakietowe",
  badminton: "rakietowe",
  taniec: "taniec-walki",
  "sztuki-walki": "taniec-walki",
  // --- batch 2 ---
  kajakarstwo: "wodne",
  zeglarstwo: "wodne",
  surfing: "wodne",
  nurkowanie: "wodne",
  snowboard: "zimowe",
  "lyzwiarstwo-figurowe": "zimowe",
  biathlon: "zimowe",
  lucznictwo: "precyzyjne",
  bilard: "precyzyjne",
  kregle: "precyzyjne",
  dart: "precyzyjne",
  "pilka-reczna": "druzynowe",
  rugby: "druzynowe",
  hokej: "druzynowe",
  krykiet: "druzynowe",
  squash: "rakietowe",
  padel: "rakietowe",
  kalistenika: "sila",
  pilates: "sila",
  gimnastyka: "sila",
  // --- batch 3 ---
  triathlon: "wytrzymalosciowe",
  sprint: "wytrzymalosciowe",
  "narciarstwo-biegowe": "zimowe",
  "lyzwiarstwo-szybkie": "zimowe",
  "skoki-narciarskie": "zimowe",
  curling: "zimowe",
  windsurfing: "wodne",
  kitesurfing: "wodne",
  sup: "wodne",
  "pilka-wodna": "wodne",
  baseball: "druzynowe",
  "futbol-amerykanski": "druzynowe",
  "hokej-na-trawie": "druzynowe",
  lacrosse: "druzynowe",
  "ultimate-frisbee": "druzynowe",
  pickleball: "rakietowe",
  snooker: "precyzyjne",
  petanka: "precyzyjne",
  "strzelectwo-sportowe": "precyzyjne",
  "podnoszenie-ciezarow": "sila",
  "trojboj-silowy": "sila",
  strongman: "sila",
  crossfit: "fitness",
  spinning: "fitness",
  skakanka: "fitness",
  aerobik: "fitness",
  boks: "taniec-walki",
  judo: "taniec-walki",
  zapasy: "taniec-walki",
  "taniec-towarzyski": "taniec-walki",
  jezdziectwo: "outdoor",
  paralotniarstwo: "outdoor",
  "bieg-na-orientacje": "outdoor",
  parkour: "outdoor",
  karting: "motorowe",
  motocross: "motorowe",
  zuzel: "motorowe",
  szachy: "umyslowe",
  "e-sport": "umyslowe",
  poker: "umyslowe",
  // --- batch 4: branża kreatywna ---
  rysowanie: "wizualne",
  malarstwo: "wizualne",
  akwarela: "wizualne",
  kaligrafia: "wizualne",
  garncarstwo: "rekodzielo",
  dzianie: "rekodzielo",
  szydelkowanie: "rekodzielo",
  szycie: "rekodzielo",
  stolarstwo: "rekodzielo",
  bizuteria: "rekodzielo",
  origami: "rekodzielo",
  "grafika-cyfrowa": "cyfrowe",
  fotografia: "cyfrowe",
  "montaz-wideo": "cyfrowe",
  animacja: "cyfrowe",
  "modelowanie-3d": "cyfrowe",
  pisanie: "artyzm",
  "produkcja-muzyczna": "artyzm",
  "gra-na-gitarze": "instrumenty",
  spiew: "instrumenty",
  // --- batch 6: instrumenty (18 nowych) ---
  pianino: "instrumenty",
  skrzypce: "instrumenty",
  perkusja: "instrumenty",
  "gitara-basowa": "instrumenty",
  ukulele: "instrumenty",
  saksofon: "instrumenty",
  flet: "instrumenty",
  trabka: "instrumenty",
  klarnet: "instrumenty",
  wiolonczela: "instrumenty",
  "harmonijka-ustna": "instrumenty",
  akordeon: "instrumenty",
  banjo: "instrumenty",
  mandolina: "instrumenty",
  keyboard: "instrumenty",
  puzon: "instrumenty",
  harfa: "instrumenty",
  organy: "instrumenty",
  // --- batch 5: kuchnie świata ---
  "kuchnia-wloska": "kuchnie",
  "kuchnia-francuska": "kuchnie",
  "kuchnia-japonska": "kuchnie",
  "kuchnia-chinska": "kuchnie",
  "kuchnia-meksykanska": "kuchnie",
  "kuchnia-indyjska": "kuchnie",
  "kuchnia-tajska": "kuchnie",
  "kuchnia-hiszpanska": "kuchnie",
  "kuchnia-grecka": "kuchnie",
  "kuchnia-polska": "kuchnie",
  "kuchnia-turecka": "kuchnie",
  "kuchnia-wietnamska": "kuchnie",
  "kuchnia-koreanska": "kuchnie",
  "kuchnia-amerykanska": "kuchnie",
  "kuchnia-libanska": "kuchnie",
  "kuchnia-marokanska": "kuchnie",
  "kuchnia-brazylijska": "kuchnie",
  "kuchnia-niemiecka": "kuchnie",
  "kuchnia-wegierska": "kuchnie",
  "kuchnia-peruwianska": "kuchnie",
};
