// Curated quote library for the "Cytat na dziś" panel. Bundled (offline, free,
// reliable attribution). Each quote is in its ORIGINAL language with a Polish
// translation (null when the original is already Polish), an author and a
// domain. Client-safe (pure data — no server deps), so both the panel and the
// server actions can import it. Extend freely; ids must stay stable (favourites
// reference them).

export type QuoteLang = "pl" | "en" | "la" | "fr" | "de" | "es" | "it";

export type Quote = {
  id: string;
  lang: QuoteLang;
  text: string; // original language
  author: string;
  translation: string | null; // Polish; null when original is Polish
  category: string; // domain, PL label
};

export const LANG_LABELS: Record<QuoteLang, string> = {
  pl: "polski",
  en: "angielski",
  la: "łacina",
  fr: "francuski",
  de: "niemiecki",
  es: "hiszpański",
  it: "włoski",
};

export const QUOTES: Quote[] = [
  // Łacina
  { id: "amor-vincit-omnia", lang: "la", text: "Amor vincit omnia.", author: "Wergiliusz", translation: "Miłość zwycięża wszystko.", category: "miłość" },
  { id: "carpe-diem", lang: "la", text: "Carpe diem.", author: "Horacy", translation: "Chwytaj dzień.", category: "czas" },
  { id: "dum-spiro-spero", lang: "la", text: "Dum spiro, spero.", author: "przysłowie łacińskie", translation: "Póki oddycham, mam nadzieję.", category: "wytrwałość" },
  { id: "per-aspera-ad-astra", lang: "la", text: "Per aspera ad astra.", author: "przysłowie łacińskie", translation: "Przez ciernie do gwiazd.", category: "wytrwałość" },
  { id: "festina-lente", lang: "la", text: "Festina lente.", author: "Oktawian August", translation: "Spiesz się powoli.", category: "mądrość" },
  { id: "errare-humanum-est", lang: "la", text: "Errare humanum est.", author: "Seneka", translation: "Błądzić jest rzeczą ludzką.", category: "mądrość" },
  { id: "verba-volant", lang: "la", text: "Verba volant, scripta manent.", author: "przysłowie łacińskie", translation: "Słowa ulatują, pismo zostaje.", category: "mądrość" },
  { id: "non-omnis-moriar", lang: "la", text: "Non omnis moriar.", author: "Horacy", translation: "Nie wszystek umrę.", category: "czas" },
  { id: "fortes-fortuna", lang: "la", text: "Fortes fortuna adiuvat.", author: "Terencjusz", translation: "Odważnym los sprzyja.", category: "odwaga" },
  { id: "dilige-quod-vis-fac", lang: "la", text: "Dilige, et quod vis fac.", author: "Święty Augustyn", translation: "Kochaj i czyń, co chcesz.", category: "miłość" },
  { id: "qui-dat-beneficia", lang: "la", text: "Qui dat beneficia, deos imitatur.", author: "Seneka", translation: "Kto czyni dobro, naśladuje bogów.", category: "dobroć" },
  { id: "bis-dat-qui-cito-dat", lang: "la", text: "Bis dat qui cito dat.", author: "Publiliusz Syrus", translation: "Dwakroć daje, kto szybko daje.", category: "dobroć" },

  // Angielski
  { id: "well-done-said", lang: "en", text: "Well done is better than well said.", author: "Benjamin Franklin", translation: "Lepiej dobrze zrobić niż dobrze powiedzieć.", category: "produktywność" },
  { id: "be-a-good-one", lang: "en", text: "Whatever you are, be a good one.", author: "Abraham Lincoln", translation: "Kimkolwiek jesteś, bądź w tym dobry.", category: "rozwój" },
  { id: "kindness-language", lang: "en", text: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain", translation: "Dobroć to język, który głusi słyszą, a niewidomi widzą.", category: "dobroć" },
  { id: "love-what-you-do", lang: "en", text: "The only way to do great work is to love what you do.", author: "Steve Jobs", translation: "Jedyny sposób, by robić wielkie rzeczy, to kochać to, co się robi.", category: "produktywność" },
  { id: "impossible-until-done", lang: "en", text: "It always seems impossible until it's done.", author: "Nelson Mandela", translation: "Zawsze wydaje się to niemożliwe, dopóki nie zostanie zrobione.", category: "wytrwałość" },
  { id: "do-what-you-can", lang: "en", text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", translation: "Rób, co możesz, tym, co masz, tam, gdzie jesteś.", category: "produktywność" },
  { id: "predict-invent-future", lang: "en", text: "The best way to predict the future is to invent it.", author: "Alan Kay", translation: "Najlepszy sposób przewidzieć przyszłość to ją wymyślić.", category: "produktywność" },
  { id: "courage-grace", lang: "en", text: "Courage is grace under pressure.", author: "Ernest Hemingway", translation: "Odwaga to wdzięk pod presją.", category: "odwaga" },
  { id: "only-way-friend", lang: "en", text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson", translation: "Jedyny sposób, by mieć przyjaciela, to samemu nim być.", category: "przyjaźń" },
  { id: "peace-but-yourself", lang: "en", text: "Nothing can bring you peace but yourself.", author: "Ralph Waldo Emerson", translation: "Nic nie da ci spokoju prócz ciebie samego.", category: "spokój" },
  { id: "be-kind-possible", lang: "en", text: "Be kind whenever possible. It is always possible.", author: "Dalajlama", translation: "Bądź dobry, kiedy tylko możesz. Zawsze możesz.", category: "dobroć" },
  { id: "cheer-someone-else", lang: "en", text: "The best way to cheer yourself is to try to cheer somebody else up.", author: "Mark Twain", translation: "Najlepszy sposób, by się pocieszyć, to pocieszyć kogoś innego.", category: "dobroć" },
  { id: "peace-begins-smile", lang: "en", text: "Peace begins with a smile.", author: "Matka Teresa", translation: "Pokój zaczyna się od uśmiechu.", category: "spokój" },
  { id: "turn-wounds-wisdom", lang: "en", text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", translation: "Zamień swoje rany w mądrość.", category: "rozwój" },
  { id: "we-rise-lifting", lang: "en", text: "We rise by lifting others.", author: "Robert Ingersoll", translation: "Wznosimy się, podnosząc innych.", category: "dobroć" },
  { id: "gratitude-enough", lang: "en", text: "Gratitude turns what we have into enough.", author: "Anonim", translation: "Wdzięczność sprawia, że to, co mamy, wystarcza.", category: "wdzięczność" },

  // Francuski
  { id: "voir-avec-coeur", lang: "fr", text: "On ne voit bien qu'avec le cœur.", author: "Antoine de Saint-Exupéry", translation: "Dobrze widzi się tylko sercem.", category: "miłość" },
  { id: "je-pense-je-suis", lang: "fr", text: "Je pense, donc je suis.", author: "René Descartes", translation: "Myślę, więc jestem.", category: "mądrość" },
  { id: "ete-invincible", lang: "fr", text: "Au milieu de l'hiver, j'apprenais enfin qu'il y avait en moi un été invincible.", author: "Albert Camus", translation: "W środku zimy odkryłem w sobie niezwyciężone lato.", category: "wytrwałość" },
  { id: "coeur-raisons", lang: "fr", text: "Le cœur a ses raisons que la raison ne connaît point.", author: "Blaise Pascal", translation: "Serce ma swoje racje, których rozum nie zna.", category: "miłość" },
  { id: "aimer-etre-aime", lang: "fr", text: "Il n'y a qu'un bonheur dans la vie, c'est d'aimer et d'être aimé.", author: "George Sand", translation: "Jest tylko jedno szczęście w życiu: kochać i być kochanym.", category: "miłość" },
  { id: "reconnaissance-coeur", lang: "fr", text: "La reconnaissance est la mémoire du cœur.", author: "Jean-Baptiste Massieu", translation: "Wdzięczność to pamięć serca.", category: "wdzięczność" },
  { id: "vivre-agir", lang: "fr", text: "Vivre, ce n'est pas respirer, c'est agir.", author: "Jean-Jacques Rousseau", translation: "Żyć to nie oddychać — to działać.", category: "produktywność" },

  // Niemiecki
  { id: "wollen-tun", lang: "de", text: "Es ist nicht genug zu wollen, man muss auch tun.", author: "Johann Wolfgang von Goethe", translation: "Nie wystarczy chcieć — trzeba też działać.", category: "produktywność" },
  { id: "nicht-umbringt", lang: "de", text: "Was mich nicht umbringt, macht mich stärker.", author: "Friedrich Nietzsche", translation: "Co mnie nie zabije, to mnie wzmocni.", category: "wytrwałość" },
  { id: "licht-schatten", lang: "de", text: "Wo viel Licht ist, ist starker Schatten.", author: "Johann Wolfgang von Goethe", translation: "Gdzie dużo światła, tam mocny cień.", category: "mądrość" },
  { id: "mensch-spielt", lang: "de", text: "Der Mensch ist nur da ganz Mensch, wo er spielt.", author: "Friedrich Schiller", translation: "Człowiek jest w pełni sobą tylko wtedy, gdy się bawi.", category: "szczęście" },
  { id: "wer-a-sagt", lang: "de", text: "Wer A sagt, muss auch B sagen.", author: "przysłowie niemieckie", translation: "Kto powiedział A, musi powiedzieć i B.", category: "wytrwałość" },

  // Hiszpański
  { id: "caminante-camino", lang: "es", text: "Caminante, no hay camino, se hace camino al andar.", author: "Antonio Machado", translation: "Wędrowcze, nie ma drogi — drogę tworzy się idąc.", category: "rozwój" },
  { id: "lee-anda-ve", lang: "es", text: "Quien lee mucho y anda mucho, ve mucho y sabe mucho.", author: "Miguel de Cervantes", translation: "Kto dużo czyta i wędruje, dużo widzi i wie.", category: "mądrość" },
  { id: "poco-a-poco", lang: "es", text: "Poco a poco se anda lejos.", author: "przysłowie hiszpańskie", translation: "Krok po kroku dochodzi się daleko.", category: "wytrwałość" },

  // Włoski
  { id: "chi-va-piano", lang: "it", text: "Chi va piano, va sano e va lontano.", author: "przysłowie włoskie", translation: "Kto idzie powoli, idzie zdrowo i daleko.", category: "wytrwałość" },
  { id: "amor-move-stelle", lang: "it", text: "L'amor che move il sole e l'altre stelle.", author: "Dante Alighieri", translation: "Miłość, co porusza słońce i inne gwiazdy.", category: "miłość" },
  { id: "semplicita", lang: "it", text: "La semplicità è l'ultima sofisticazione.", author: "Leonardo da Vinci", translation: "Prostota to najwyższe wyrafinowanie.", category: "mądrość" },

  // Polski (bez tłumaczenia)
  { id: "miej-serce", lang: "pl", text: "Miej serce i patrzaj w serce.", author: "Adam Mickiewicz", translation: null, category: "mądrość" },
  { id: "przeszlosc-dzis", lang: "pl", text: "Przeszłość jest to dziś, tylko cokolwiek dalej.", author: "Cyprian Kamil Norwid", translation: null, category: "czas" },
  { id: "ojczyzna-obowiazek", lang: "pl", text: "Ojczyzna to wielki zbiorowy obowiązek.", author: "Cyprian Kamil Norwid", translation: null, category: "dobroć" },
  { id: "kto-rano-wstaje", lang: "pl", text: "Kto rano wstaje, temu Pan Bóg daje.", author: "przysłowie polskie", translation: null, category: "produktywność" },
  { id: "przyjaciol-biedzie", lang: "pl", text: "Prawdziwych przyjaciół poznaje się w biedzie.", author: "przysłowie polskie", translation: null, category: "przyjaźń" },
  { id: "odwaznych-swiat", lang: "pl", text: "Do odważnych świat należy.", author: "przysłowie polskie", translation: null, category: "odwaga" },
  { id: "skorupka-mlodu", lang: "pl", text: "Czym skorupka za młodu nasiąknie, tym na starość trąci.", author: "przysłowie polskie", translation: null, category: "rozwój" },
  { id: "nie-ten-szczesliwy", lang: "pl", text: "Nie ten szczęśliwy, kto ma wiele, lecz ten, kto mało potrzebuje.", author: "przysłowie polskie", translation: null, category: "szczęście" },

  // ─────────── Łacina (rozszerzenie) ───────────
  { id: "veni-vidi-vici", lang: "la", text: "Veni, vidi, vici.", author: "Juliusz Cezar", translation: "Przybyłem, zobaczyłem, zwyciężyłem.", category: "odwaga" },
  { id: "alea-iacta-est", lang: "la", text: "Alea iacta est.", author: "Juliusz Cezar", translation: "Kości zostały rzucone.", category: "odwaga" },
  { id: "cogito-ergo-sum", lang: "la", text: "Cogito ergo sum.", author: "Kartezjusz", translation: "Myślę, więc jestem.", category: "mądrość" },
  { id: "sapere-aude", lang: "la", text: "Sapere aude.", author: "Horacy", translation: "Odważ się być mądrym.", category: "mądrość" },
  { id: "labor-omnia-vincit", lang: "la", text: "Labor omnia vincit.", author: "Wergiliusz", translation: "Praca wszystko zwycięża.", category: "praca" },
  { id: "mens-sana", lang: "la", text: "Mens sana in corpore sano.", author: "Juwenalis", translation: "W zdrowym ciele zdrowy duch.", category: "rozwój" },
  { id: "gutta-cavat-lapidem", lang: "la", text: "Gutta cavat lapidem.", author: "Owidiusz", translation: "Kropla drąży skałę.", category: "wytrwałość" },
  { id: "fugit-tempus", lang: "la", text: "Fugit irreparabile tempus.", author: "Wergiliusz", translation: "Ucieka niepowrotny czas.", category: "czas" },
  { id: "memento-mori", lang: "la", text: "Memento mori.", author: "sentencja łacińska", translation: "Pamiętaj o śmierci.", category: "czas" },
  { id: "tempus-fugit", lang: "la", text: "Tempus fugit, aeternitas manet.", author: "sentencja łacińska", translation: "Czas ucieka, wieczność trwa.", category: "czas" },
  { id: "ars-longa", lang: "la", text: "Ars longa, vita brevis.", author: "sentencja łacińska", translation: "Sztuka długa, życie krótkie.", category: "czas" },
  { id: "docendo-discimus", lang: "la", text: "Docendo discimus.", author: "Seneka", translation: "Ucząc innych, uczymy się sami.", category: "rozwój" },
  { id: "otium-sine-litteris", lang: "la", text: "Otium sine litteris mors est.", author: "Seneka", translation: "Wolny czas bez nauki jest śmiercią.", category: "rozwój" },
  { id: "repetitio-mater", lang: "la", text: "Repetitio est mater studiorum.", author: "sentencja łacińska", translation: "Powtarzanie jest matką nauki.", category: "rozwój" },
  { id: "historia-magistra", lang: "la", text: "Historia magistra vitae.", author: "Cyceron", translation: "Historia nauczycielką życia.", category: "mądrość" },
  { id: "faber-fortunae", lang: "la", text: "Faber est suae quisque fortunae.", author: "Appiusz Klaudiusz", translation: "Każdy jest kowalem swego losu.", category: "wytrwałość" },
  { id: "audentes-fortuna", lang: "la", text: "Audentes fortuna iuvat.", author: "Wergiliusz", translation: "Śmiałym sprzyja los.", category: "odwaga" },
  { id: "vincit-qui-se-vincit", lang: "la", text: "Vincit qui se vincit.", author: "sentencja łacińska", translation: "Zwycięża, kto zwycięża samego siebie.", category: "wytrwałość" },
  { id: "nosce-te-ipsum", lang: "la", text: "Nosce te ipsum.", author: "sentencja łacińska", translation: "Poznaj samego siebie.", category: "mądrość" },
  { id: "vitiis-nemo", lang: "la", text: "Vitiis nemo sine nascitur.", author: "Horacy", translation: "Nikt nie rodzi się bez wad.", category: "pokora" },
  { id: "concordia-crescunt", lang: "la", text: "Concordia parvae res crescunt.", author: "Salustiusz", translation: "Zgodą małe rzeczy rosną.", category: "przyjaźń" },
  { id: "ubi-concordia", lang: "la", text: "Ubi concordia, ibi victoria.", author: "Publiliusz Syrus", translation: "Gdzie zgoda, tam zwycięstwo.", category: "przyjaźń" },
  { id: "amicus-certus", lang: "la", text: "Amicus certus in re incerta cernitur.", author: "Enniusz", translation: "Pewnego przyjaciela poznaje się w niepewnej chwili.", category: "przyjaźń" },
  { id: "veritas-odium", lang: "la", text: "Veritas odium parit.", author: "Terencjusz", translation: "Prawda rodzi nienawiść.", category: "prawda" },
  { id: "veritas-liberabit", lang: "la", text: "Veritas vos liberabit.", author: "Ewangelia św. Jana", translation: "Prawda was wyzwoli.", category: "prawda" },
  { id: "spes-ultima", lang: "la", text: "Spes ultima dea.", author: "sentencja łacińska", translation: "Nadzieja umiera ostatnia.", category: "nadzieja" },
  { id: "post-nubila-sol", lang: "la", text: "Post nubila sol.", author: "sentencja łacińska", translation: "Po chmurach [wychodzi] słońce.", category: "nadzieja" },
  { id: "dum-vivimus-vivamus", lang: "la", text: "Dum vivimus, vivamus.", author: "sentencja łacińska", translation: "Póki żyjemy, żyjmy [pełnią].", category: "szczęście" },
  { id: "non-progredi", lang: "la", text: "Non progredi est regredi.", author: "sentencja łacińska", translation: "Nie iść naprzód to się cofać.", category: "rozwój" },
  { id: "qui-tacet-consentire", lang: "la", text: "Qui tacet, consentire videtur.", author: "sentencja łacińska", translation: "Kto milczy, zdaje się zgadzać.", category: "mądrość" },
  { id: "silentium-aurum", lang: "la", text: "Silentium est aurum.", author: "sentencja łacińska", translation: "Milczenie jest złotem.", category: "spokój" },
  { id: "nihil-novi", lang: "la", text: "Nihil novi sub sole.", author: "sentencja łacińska", translation: "Nic nowego pod słońcem.", category: "mądrość" },
  { id: "fide-sed-vide", lang: "la", text: "Fide, sed cui, vide.", author: "sentencja łacińska", translation: "Ufaj, ale patrz komu.", category: "mądrość" },
  { id: "suum-cuique", lang: "la", text: "Suum cuique.", author: "Cyceron", translation: "Każdemu, co mu się należy.", category: "mądrość" },
  { id: "beatus-qui-prodest", lang: "la", text: "Beatus qui prodest quibus potest.", author: "sentencja łacińska", translation: "Szczęśliwy, kto pomaga, komu może.", category: "dobroć" },
  { id: "manus-manum-lavat", lang: "la", text: "Manus manum lavat.", author: "przysłowie łacińskie", translation: "Ręka rękę myje.", category: "mądrość" },
  { id: "homo-homini", lang: "la", text: "Homo homini lupus.", author: "Plaut", translation: "Człowiek człowiekowi wilkiem.", category: "mądrość" },
  { id: "omnia-mea", lang: "la", text: "Omnia mea mecum porto.", author: "sentencja łacińska", translation: "Wszystko, co moje, noszę ze sobą.", category: "mądrość" },

  // ─────────── Angielski (rozszerzenie) ───────────
  { id: "invest-knowledge", lang: "en", text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin", translation: "Inwestycja w wiedzę daje najlepsze odsetki.", category: "rozwój" },
  { id: "failing-to-prepare", lang: "en", text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin", translation: "Nie przygotowując się, przygotowujesz się do porażki.", category: "produktywność" },
  { id: "lost-time", lang: "en", text: "Lost time is never found again.", author: "Benjamin Franklin", translation: "Straconego czasu nigdy się nie odnajdzie.", category: "czas" },
  { id: "believe-halfway", lang: "en", text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", translation: "Uwierz, że potrafisz, a jesteś w połowie drogi.", category: "odwaga" },
  { id: "future-dreams", lang: "en", text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", translation: "Przyszłość należy do tych, którzy wierzą w piękno swoich marzeń.", category: "marzenia" },
  { id: "no-inferior-consent", lang: "en", text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt", translation: "Nikt nie sprawi, byś poczuł się gorszy, bez twojej zgody.", category: "odwaga" },
  { id: "alone-together", lang: "en", text: "Alone we can do so little; together we can do so much.", author: "Helen Keller", translation: "Sami możemy tak mało; razem tak wiele.", category: "przyjaźń" },
  { id: "felt-with-heart", lang: "en", text: "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.", author: "Helen Keller", translation: "Najlepszych i najpiękniejszych rzeczy nie można zobaczyć ani dotknąć — trzeba je czuć sercem.", category: "miłość" },
  { id: "face-to-sunshine", lang: "en", text: "Keep your face to the sunshine and you cannot see a shadow.", author: "Helen Keller", translation: "Zwróć twarz ku słońcu, a nie zobaczysz cienia.", category: "nadzieja" },
  { id: "never-give-in", lang: "en", text: "Never give in — never, never, never.", author: "Winston Churchill", translation: "Nigdy się nie poddawaj — przenigdy.", category: "wytrwałość" },
  { id: "success-not-final", lang: "en", text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", translation: "Sukces nie jest ostateczny, porażka nie jest zgubna — liczy się odwaga, by iść dalej.", category: "wytrwałość" },
  { id: "gutter-stars", lang: "en", text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde", translation: "Wszyscy jesteśmy w rynsztoku, ale niektórzy patrzą w gwiazdy.", category: "nadzieja" },
  { id: "truth-rarely-pure", lang: "en", text: "The truth is rarely pure and never simple.", author: "Oscar Wilde", translation: "Prawda rzadko bywa czysta i nigdy prosta.", category: "prawda" },
  { id: "to-live-rarest", lang: "en", text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde", translation: "Żyć to najrzadsza rzecz na świecie. Większość ludzi tylko istnieje.", category: "życie" },
  { id: "confidently-dreams", lang: "en", text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau", translation: "Idź śmiało w kierunku swoich marzeń. Żyj życiem, które sobie wymarzyłeś.", category: "marzenia" },
  { id: "richest-cheapest", lang: "en", text: "That man is richest whose pleasures are cheapest.", author: "Henry David Thoreau", translation: "Najbogatszy jest ten, czyje przyjemności są najtańsze.", category: "szczęście" },
  { id: "enthusiasm-great", lang: "en", text: "Nothing great was ever achieved without enthusiasm.", author: "Ralph Waldo Emerson", translation: "Niczego wielkiego nie osiągnięto bez entuzjazmu.", category: "produktywność" },
  { id: "best-day-year", lang: "en", text: "Write it on your heart that every day is the best day in the year.", author: "Ralph Waldo Emerson", translation: "Zapisz w sercu, że każdy dzień jest najlepszym w roku.", category: "szczęście" },
  { id: "darkness-light", lang: "en", text: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", author: "Martin Luther King Jr.", translation: "Ciemności nie wypędzi ciemność — tylko światło. Nienawiści nie wypędzi nienawiść — tylko miłość.", category: "miłość" },
  { id: "time-right-to-do-right", lang: "en", text: "The time is always right to do what is right.", author: "Martin Luther King Jr.", translation: "Zawsze jest właściwy czas, by zrobić to, co słuszne.", category: "dobroć" },
  { id: "good-head-heart", lang: "en", text: "A good head and a good heart are always a formidable combination.", author: "Nelson Mandela", translation: "Dobra głowa i dobre serce to zawsze potężne połączenie.", category: "dobroć" },
  { id: "education-weapon", lang: "en", text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", translation: "Edukacja to najpotężniejsza broń, którą możesz zmienić świat.", category: "rozwój" },
  { id: "find-yourself-service", lang: "en", text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi", translation: "Najlepszy sposób, by odnaleźć siebie, to zatracić się w służbie innym.", category: "dobroć" },
  { id: "live-learn-forever", lang: "en", text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", translation: "Żyj tak, jakbyś miał jutro umrzeć. Ucz się tak, jakbyś miał żyć wiecznie.", category: "rozwój" },
  { id: "imagination-knowledge", lang: "en", text: "Imagination is more important than knowledge.", author: "Albert Einstein", translation: "Wyobraźnia jest ważniejsza od wiedzy.", category: "marzenia" },
  { id: "never-mistake-new", lang: "en", text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", translation: "Kto nigdy nie popełnił błędu, nigdy nie próbował niczego nowego.", category: "rozwój" },
  { id: "stay-hungry", lang: "en", text: "Stay hungry, stay foolish.", author: "Steve Jobs", translation: "Bądź głodny, bądź szalony.", category: "rozwój" },
  { id: "time-limited", lang: "en", text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs", translation: "Twój czas jest ograniczony, więc nie marnuj go, żyjąc cudzym życiem.", category: "czas" },
  { id: "thine-own-self", lang: "en", text: "To thine own self be true.", author: "William Shakespeare", translation: "Bądź wierny samemu sobie.", category: "mądrość" },
  { id: "know-what-we-may-be", lang: "en", text: "We know what we are, but know not what we may be.", author: "William Shakespeare", translation: "Wiemy, czym jesteśmy, lecz nie wiemy, czym możemy się stać.", category: "rozwój" },
  { id: "world-a-stage", lang: "en", text: "All the world's a stage.", author: "William Shakespeare", translation: "Cały świat to scena.", category: "życie" },
  { id: "true-love-smooth", lang: "en", text: "The course of true love never did run smooth.", author: "William Shakespeare", translation: "Bieg prawdziwej miłości nigdy nie był gładki.", category: "miłość" },
  { id: "tenderness-of-heart", lang: "en", text: "There is no charm equal to tenderness of heart.", author: "Jane Austen", translation: "Nie ma uroku równego czułości serca.", category: "miłość" },
  { id: "no-one-useless", lang: "en", text: "No one is useless in this world who lightens the burdens of another.", author: "Charles Dickens", translation: "Nikt nie jest bezużyteczny, kto ulży ciężarowi innego.", category: "dobroć" },
  { id: "happy-make-others", lang: "en", text: "Whoever is happy will make others happy too.", author: "Anne Frank", translation: "Kto jest szczęśliwy, uszczęśliwi też innych.", category: "szczęście" },
  { id: "poor-by-giving", lang: "en", text: "No one has ever become poor by giving.", author: "Anne Frank", translation: "Nikt nie zbiedniał przez to, że dawał.", category: "dobroć" },
  { id: "lift-up-someone", lang: "en", text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", translation: "Jeśli chcesz się podnieść, podnieś kogoś innego.", category: "dobroć" },
  { id: "small-things-great-love", lang: "en", text: "Not all of us can do great things. But we can do small things with great love.", author: "Matka Teresa", translation: "Nie wszyscy możemy robić wielkie rzeczy. Ale możemy robić małe rzeczy z wielką miłością.", category: "dobroć" },
  { id: "genius-perspiration", lang: "en", text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison", translation: "Geniusz to jeden procent natchnienia i dziewięćdziesiąt dziewięć procent potu.", category: "praca" },
  { id: "one-more-time", lang: "en", text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison", translation: "Naszą największą słabością jest rezygnacja. Najpewniejszy sposób na sukces to spróbować jeszcze raz.", category: "wytrwałość" },
  { id: "think-you-can", lang: "en", text: "Whether you think you can, or you think you can't — you're right.", author: "Henry Ford", translation: "Czy myślisz, że dasz radę, czy że nie — masz rację.", category: "odwaga" },
  { id: "coming-together", lang: "en", text: "Coming together is a beginning; keeping together is progress; working together is success.", author: "Henry Ford", translation: "Zejść się to początek; trzymać się razem to postęp; pracować razem to sukces.", category: "przyjaźń" },
  { id: "quit-talking", lang: "en", text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", translation: "Aby zacząć, trzeba przestać gadać i zacząć działać.", category: "produktywność" },
  { id: "courage-pursue-dreams", lang: "en", text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney", translation: "Wszystkie marzenia mogą się spełnić, jeśli mamy odwagę je realizować.", category: "marzenia" },
  { id: "act-makes-difference", lang: "en", text: "Act as if what you do makes a difference. It does.", author: "William James", translation: "Działaj tak, jakby to, co robisz, miało znaczenie. Bo ma.", category: "produktywność" },
  { id: "start-to-be-great", lang: "en", text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar", translation: "Nie musisz być wielki, by zacząć, ale musisz zacząć, by być wielkim.", category: "produktywność" },
  { id: "cannot-do-can-do", lang: "en", text: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden", translation: "Nie pozwól, by to, czego nie możesz zrobić, przeszkadzało w tym, co możesz.", category: "produktywność" },
  { id: "work-love-visible", lang: "en", text: "Work is love made visible.", author: "Kahlil Gibran", translation: "Praca to miłość uczyniona widzialną.", category: "praca" },
  { id: "happiness-own-actions", lang: "en", text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalajlama", translation: "Szczęście nie jest gotowe — pochodzi z twoich własnych czynów.", category: "szczęście" },
  { id: "where-will-way", lang: "en", text: "Where there's a will, there's a way.", author: "przysłowie angielskie", translation: "Gdzie jest chęć, tam jest sposób.", category: "wytrwałość" },
  { id: "actions-louder", lang: "en", text: "Actions speak louder than words.", author: "przysłowie angielskie", translation: "Czyny mówią głośniej niż słowa.", category: "produktywność" },
  { id: "practice-perfect", lang: "en", text: "Practice makes perfect.", author: "przysłowie angielskie", translation: "Trening czyni mistrza.", category: "rozwój" },
  { id: "rome-not-in-a-day", lang: "en", text: "Rome wasn't built in a day.", author: "przysłowie angielskie", translation: "Nie od razu Rzym zbudowano.", category: "cierpliwość" },
  { id: "silver-lining", lang: "en", text: "Every cloud has a silver lining.", author: "przysłowie angielskie", translation: "Każda chmura ma srebrzystą podszewkę.", category: "nadzieja" },
  { id: "honesty-best-policy", lang: "en", text: "Honesty is the best policy.", author: "przysłowie angielskie", translation: "Uczciwość to najlepsza polityka.", category: "prawda" },

  // ─────────── Francuski (rozszerzenie) ───────────
  { id: "mieux-ennemi-bien", lang: "fr", text: "Le mieux est l'ennemi du bien.", author: "Voltaire", translation: "Lepsze jest wrogiem dobrego.", category: "mądrość" },
  { id: "cultiver-jardin", lang: "fr", text: "Il faut cultiver notre jardin.", author: "Voltaire", translation: "Trzeba uprawiać własny ogród.", category: "praca" },
  { id: "decide-heureux", lang: "fr", text: "J'ai décidé d'être heureux parce que c'est bon pour la santé.", author: "Voltaire", translation: "Postanowiłem być szczęśliwy, bo to dobre dla zdrowia.", category: "szczęście" },
  { id: "aimer-cest-agir", lang: "fr", text: "Aimer, c'est agir.", author: "Victor Hugo", translation: "Kochać to działać.", category: "miłość" },
  { id: "nuit-vers-lumiere", lang: "fr", text: "Chaque homme dans sa nuit s'en va vers sa lumière.", author: "Victor Hugo", translation: "Każdy człowiek w swej nocy idzie ku swojemu światłu.", category: "nadzieja" },
  { id: "vie-fleur-amour-miel", lang: "fr", text: "La vie est une fleur dont l'amour est le miel.", author: "Victor Hugo", translation: "Życie to kwiat, którego miodem jest miłość.", category: "miłość" },
  { id: "rien-ne-sert-courir", lang: "fr", text: "Rien ne sert de courir; il faut partir à point.", author: "Jean de La Fontaine", translation: "Nie warto biec; trzeba wyruszyć w porę.", category: "cierpliwość" },
  { id: "patience-longueur", lang: "fr", text: "Patience et longueur de temps font plus que force ni que rage.", author: "Jean de La Fontaine", translation: "Cierpliwość i czas zdziałają więcej niż siła i złość.", category: "cierpliwość" },
  { id: "roseau-pensant", lang: "fr", text: "L'homme n'est qu'un roseau, le plus faible de la nature, mais c'est un roseau pensant.", author: "Blaise Pascal", translation: "Człowiek to trzcina, najsłabsza w naturze, ale trzcina myśląca.", category: "mądrość" },
  { id: "se-croire-plus-fin", lang: "fr", text: "Le vrai moyen d'être trompé, c'est de se croire plus fin que les autres.", author: "François de La Rochefoucauld", translation: "Najlepszy sposób, by dać się oszukać, to uważać się za sprytniejszego od innych.", category: "pokora" },
  { id: "que-sais-je", lang: "fr", text: "Que sais-je?", author: "Michel de Montaigne", translation: "Cóż ja wiem?", category: "pokora" },
  { id: "etre-a-soi", lang: "fr", text: "La plus grande chose du monde, c'est de savoir être à soi.", author: "Michel de Montaigne", translation: "Największą rzeczą na świecie jest umieć być sobą.", category: "mądrość" },
  { id: "reve-realite", lang: "fr", text: "Fais de ta vie un rêve, et d'un rêve, une réalité.", author: "Antoine de Saint-Exupéry", translation: "Uczyń z życia marzenie, a z marzenia rzeczywistość.", category: "marzenia" },
  { id: "meme-direction", lang: "fr", text: "Aimer, ce n'est pas se regarder l'un l'autre, c'est regarder ensemble dans la même direction.", author: "Antoine de Saint-Exupéry", translation: "Kochać to nie patrzeć na siebie nawzajem, lecz patrzeć razem w tym samym kierunku.", category: "miłość" },
  { id: "desert-puits", lang: "fr", text: "Ce qui embellit le désert, c'est qu'il cache un puits quelque part.", author: "Antoine de Saint-Exupéry", translation: "Pustynię upiększa to, że gdzieś kryje studnię.", category: "nadzieja" },
  { id: "automne-printemps", lang: "fr", text: "L'automne est un deuxième printemps où chaque feuille est une fleur.", author: "Albert Camus", translation: "Jesień to druga wiosna, gdy każdy liść jest kwiatem.", category: "piękno" },
  { id: "generosite-present", lang: "fr", text: "La vraie générosité envers l'avenir consiste à tout donner au présent.", author: "Albert Camus", translation: "Prawdziwa hojność wobec przyszłości to oddać wszystko teraźniejszości.", category: "czas" },
  { id: "meurt-quune-fois", lang: "fr", text: "On ne meurt qu'une fois, et c'est pour si longtemps.", author: "Molière", translation: "Umiera się tylko raz, i to na tak długo.", category: "życie" },
  { id: "ne-libre-fers", lang: "fr", text: "L'homme est né libre, et partout il est dans les fers.", author: "Jean-Jacques Rousseau", translation: "Człowiek rodzi się wolny, a wszędzie jest w okowach.", category: "wolność" },
  { id: "patience-amere", lang: "fr", text: "La patience est amère, mais son fruit est doux.", author: "Jean-Jacques Rousseau", translation: "Cierpliwość jest gorzka, lecz jej owoc słodki.", category: "cierpliwość" },
  { id: "oiseau-nid", lang: "fr", text: "Petit à petit, l'oiseau fait son nid.", author: "przysłowie francuskie", translation: "Powoli ptak buduje gniazdo.", category: "cierpliwość" },
  { id: "vouloir-pouvoir", lang: "fr", text: "Vouloir, c'est pouvoir.", author: "przysłowie francuskie", translation: "Chcieć to móc.", category: "wytrwałość" },
  { id: "habit-moine", lang: "fr", text: "L'habit ne fait pas le moine.", author: "przysłowie francuskie", translation: "Nie szata zdobi człowieka.", category: "mądrość" },
  { id: "apres-pluie", lang: "fr", text: "Après la pluie, le beau temps.", author: "przysłowie francuskie", translation: "Po deszczu przychodzi pogoda.", category: "nadzieja" },
  { id: "qui-vivra-verra", lang: "fr", text: "Qui vivra verra.", author: "przysłowie francuskie", translation: "Kto dożyje, zobaczy.", category: "cierpliwość" },

  // ─────────── Niemiecki (rozszerzenie) ───────────
  { id: "strebend-bemueht", lang: "de", text: "Wer immer strebend sich bemüht, den können wir erlösen.", author: "Johann Wolfgang von Goethe", translation: "Kto wciąż dążąc się trudzi, tego możemy zbawić.", category: "wytrwałość" },
  { id: "wissen-anwenden", lang: "de", text: "Es ist nicht genug zu wissen, man muss auch anwenden.", author: "Johann Wolfgang von Goethe", translation: "Nie wystarczy wiedzieć, trzeba też stosować.", category: "rozwój" },
  { id: "ganze-im-kleinsten", lang: "de", text: "Willst du dich am Ganzen erquicken, so musst du das Ganze im Kleinsten erblicken.", author: "Johann Wolfgang von Goethe", translation: "Chcesz radować się całością — musisz dostrzec ją w tym, co najmniejsze.", category: "mądrość" },
  { id: "warum-leben", lang: "de", text: "Wer ein Warum zu leben hat, erträgt fast jedes Wie.", author: "Friedrich Nietzsche", translation: "Kto ma po co żyć, zniesie niemal każde jak.", category: "wytrwałość" },
  { id: "ohne-musik-irrtum", lang: "de", text: "Ohne Musik wäre das Leben ein Irrtum.", author: "Friedrich Nietzsche", translation: "Bez muzyki życie byłoby pomyłką.", category: "piękno" },
  { id: "chaos-tanzender-stern", lang: "de", text: "Man muss noch Chaos in sich haben, um einen tanzenden Stern gebären zu können.", author: "Friedrich Nietzsche", translation: "Trzeba mieć w sobie chaos, by móc urodzić tańczącą gwiazdę.", category: "marzenia" },
  { id: "brave-mann-zuletzt", lang: "de", text: "Der brave Mann denkt an sich selbst zuletzt.", author: "Friedrich Schiller", translation: "Prawy człowiek myśli o sobie na końcu.", category: "dobroć" },
  { id: "mensch-waechst-zwecken", lang: "de", text: "Es wächst der Mensch mit seinen größeren Zwecken.", author: "Friedrich Schiller", translation: "Człowiek rośnie wraz z większymi celami.", category: "rozwój" },
  { id: "habe-mut-verstand", lang: "de", text: "Habe Mut, dich deines eigenen Verstandes zu bedienen.", author: "Immanuel Kant", translation: "Miej odwagę posługiwać się własnym rozumem.", category: "mądrość" },
  { id: "leben-fahrrad", lang: "de", text: "Das Leben ist wie Fahrrad fahren. Um die Balance zu halten, musst du in Bewegung bleiben.", author: "Albert Einstein", translation: "Życie jest jak jazda na rowerze. Aby utrzymać równowagę, musisz być w ruchu.", category: "rozwój" },
  { id: "uebung-meister", lang: "de", text: "Übung macht den Meister.", author: "przysłowie niemieckie", translation: "Trening czyni mistrza.", category: "rozwój" },
  { id: "morgenstund-gold", lang: "de", text: "Morgenstund hat Gold im Mund.", author: "przysłowie niemieckie", translation: "Kto rano wstaje, temu Pan Bóg daje.", category: "produktywność" },
  { id: "wille-weg", lang: "de", text: "Wo ein Wille ist, ist auch ein Weg.", author: "przysłowie niemieckie", translation: "Gdzie jest wola, tam jest droga.", category: "wytrwałość" },
  { id: "anfang-schwer", lang: "de", text: "Aller Anfang ist schwer.", author: "przysłowie niemieckie", translation: "Każdy początek jest trudny.", category: "wytrwałość" },
  { id: "geteiltes-leid", lang: "de", text: "Geteiltes Leid ist halbes Leid.", author: "przysłowie niemieckie", translation: "Podzielony smutek to połowa smutku.", category: "przyjaźń" },
  { id: "luegen-kurze-beine", lang: "de", text: "Lügen haben kurze Beine.", author: "przysłowie niemieckie", translation: "Kłamstwo ma krótkie nogi.", category: "prawda" },
  { id: "kluegere-gibt-nach", lang: "de", text: "Der Klügere gibt nach.", author: "przysłowie niemieckie", translation: "Mądrzejszy ustępuje.", category: "mądrość" },

  // ─────────── Hiszpański (rozszerzenie) ───────────
  { id: "libertad-don", lang: "es", text: "La libertad es uno de los más preciosos dones que a los hombres dieron los cielos.", author: "Miguel de Cervantes", translation: "Wolność to jeden z najcenniejszych darów, jakie niebo dało ludziom.", category: "wolność" },
  { id: "gozar-ventura", lang: "es", text: "El que no sabe gozar de la ventura cuando le viene, no debe quejarse si se pasa.", author: "Miguel de Cervantes", translation: "Kto nie umie cieszyć się szczęściem, gdy nadchodzi, niech nie narzeka, gdy mija.", category: "szczęście" },
  { id: "hoy-siempre-todavia", lang: "es", text: "Hoy es siempre todavía.", author: "Antonio Machado", translation: "Dziś to zawsze jeszcze [wciąż trwa].", category: "czas" },
  { id: "solo-se-gana-da", lang: "es", text: "Sólo se pierde lo que se guarda; sólo se gana lo que se da.", author: "Antonio Machado", translation: "Traci się tylko to, co się chowa; zyskuje tylko to, co się daje.", category: "dobroć" },
  { id: "despacito-buena-letra", lang: "es", text: "Despacito y buena letra: el hacer las cosas bien importa más que el hacerlas.", author: "Antonio Machado", translation: "Powoli i starannie: robić rzeczy dobrze ważniejsze niż je robić.", category: "produktywność" },
  { id: "bueno-breve", lang: "es", text: "Lo bueno, si breve, dos veces bueno.", author: "Baltasar Gracián", translation: "Co dobre, jeśli krótkie, dwa razy dobre.", category: "mądrość" },
  { id: "saber-haber", lang: "es", text: "Más vale saber que haber.", author: "Baltasar Gracián", translation: "Lepiej wiedzieć niż mieć.", category: "rozwój" },
  { id: "hacer-decir", lang: "es", text: "Hacer es la mejor manera de decir.", author: "José Martí", translation: "Działać to najlepszy sposób, by mówić.", category: "produktywność" },
  { id: "mas-vale-tarde", lang: "es", text: "Más vale tarde que nunca.", author: "przysłowie hiszpańskie", translation: "Lepiej późno niż wcale.", category: "czas" },
  { id: "no-dejes-manana", lang: "es", text: "No dejes para mañana lo que puedas hacer hoy.", author: "przysłowie hiszpańskie", translation: "Nie odkładaj na jutro tego, co możesz zrobić dziś.", category: "produktywność" },
  { id: "querer-es-poder", lang: "es", text: "Querer es poder.", author: "przysłowie hiszpańskie", translation: "Chcieć to móc.", category: "wytrwałość" },
  { id: "mal-tiempo-buena-cara", lang: "es", text: "A mal tiempo, buena cara.", author: "przysłowie hiszpańskie", translation: "Złej pogodzie — dobra mina.", category: "nadzieja" },
  { id: "siembra-vientos", lang: "es", text: "Quien siembra vientos recoge tempestades.", author: "przysłowie hiszpańskie", translation: "Kto sieje wiatr, zbiera burzę.", category: "mądrość" },
  { id: "la-sigue-consigue", lang: "es", text: "El que la sigue la consigue.", author: "przysłowie hiszpańskie", translation: "Kto wytrwa, ten osiągnie.", category: "wytrwałość" },

  // ─────────── Włoski (rozszerzenie) ───────────
  { id: "fatti-non-bruti", lang: "it", text: "Fatti non foste a viver come bruti, ma per seguir virtute e canoscenza.", author: "Dante Alighieri", translation: "Nie stworzono was, by żyć jak zwierzęta, lecz by iść za cnotą i wiedzą.", category: "rozwój" },
  { id: "chi-poco-pensa", lang: "it", text: "Chi poco pensa, molto erra.", author: "Leonardo da Vinci", translation: "Kto mało myśli, wiele błądzi.", category: "mądrość" },
  { id: "fortuna-meta", lang: "it", text: "La fortuna è arbitra della metà delle nostre azioni, ma ci lascia governare l'altra metà.", author: "Niccolò Machiavelli", translation: "Fortuna rządzi połową naszych czynów, lecz drugą połowę zostawia nam.", category: "mądrość" },
  { id: "buon-senso-nascosto", lang: "it", text: "Il buon senso c'era, ma se ne stava nascosto per paura del senso comune.", author: "Alessandro Manzoni", translation: "Zdrowy rozsądek istniał, lecz krył się ze strachu przed opinią ogółu.", category: "mądrość" },
  { id: "trova-amico-tesoro", lang: "it", text: "Chi trova un amico trova un tesoro.", author: "przysłowie włoskie", translation: "Kto znajduje przyjaciela, znajduje skarb.", category: "przyjaźń" },
  { id: "unione-forza", lang: "it", text: "L'unione fa la forza.", author: "przysłowie włoskie", translation: "W jedności siła.", category: "przyjaźń" },
  { id: "dorme-non-piglia", lang: "it", text: "Chi dorme non piglia pesci.", author: "przysłowie włoskie", translation: "Kto śpi, nie łowi ryb.", category: "produktywność" },
  { id: "roma-non-un-giorno", lang: "it", text: "Roma non fu fatta in un giorno.", author: "przysłowie włoskie", translation: "Nie od razu Rzym zbudowano.", category: "cierpliwość" },
  { id: "meglio-tardi", lang: "it", text: "Meglio tardi che mai.", author: "przysłowie włoskie", translation: "Lepiej późno niż wcale.", category: "czas" },
  { id: "pratica-grammatica", lang: "it", text: "Val più la pratica che la grammatica.", author: "przysłowie włoskie", translation: "Więcej warta praktyka niż gramatyka.", category: "rozwój" },
  { id: "ride-ultimo", lang: "it", text: "Ride bene chi ride ultimo.", author: "przysłowie włoskie", translation: "Ten się śmieje, kto się śmieje ostatni.", category: "mądrość" },

  // ─────────── Polski (rozszerzenie) ───────────
  { id: "mierz-sily-zamiary", lang: "pl", text: "Mierz siły na zamiary, nie zamiar podług sił.", author: "Adam Mickiewicz", translation: null, category: "odwaga" },
  { id: "zywi-nie-traca-nadziei", lang: "pl", text: "Lecz zaklinam — niech żywi nie tracą nadziei.", author: "Juliusz Słowacki", translation: null, category: "nadzieja" },
  { id: "piekno-praca", lang: "pl", text: "Piękno na to jest, by zachwycało do pracy — praca, by się zmartwychwstało.", author: "Cyprian Kamil Norwid", translation: null, category: "praca" },
  { id: "nie-porzucaj-nadzieje", lang: "pl", text: "Nie porzucaj nadzieje, jakoć się kolwiek dzieje.", author: "Jan Kochanowski", translation: null, category: "nadzieja" },
  { id: "cnota-skarb", lang: "pl", text: "Cnota skarb wieczny, cnota klejnot drogi.", author: "Jan Kochanowski", translation: null, category: "dobroć" },
  { id: "serce-roscie", lang: "pl", text: "Serce roście, patrząc na te czasy.", author: "Jan Kochanowski", translation: null, category: "szczęście" },
  { id: "cnota-krytyk", lang: "pl", text: "Prawdziwa cnota krytyk się nie boi.", author: "Ignacy Krasicki", translation: null, category: "mądrość" },
  { id: "serdecznych-przyjaciol", lang: "pl", text: "Wśród serdecznych przyjaciół psy zająca zjadły.", author: "Ignacy Krasicki", translation: null, category: "przyjaźń" },
  { id: "byc-uzytecznym", lang: "pl", text: "Być narodowi użytecznym.", author: "Stanisław Staszic", translation: null, category: "dobroć" },
  { id: "bez-pracy-kolaczy", lang: "pl", text: "Bez pracy nie ma kołaczy.", author: "przysłowie polskie", translation: null, category: "praca" },
  { id: "ziarnko-do-ziarnka", lang: "pl", text: "Ziarnko do ziarnka, a zbierze się miarka.", author: "przysłowie polskie", translation: null, category: "wytrwałość" },
  { id: "kto-pyta-nie-bladzi", lang: "pl", text: "Kto pyta, nie błądzi.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "nie-chwal-dnia", lang: "pl", text: "Nie chwal dnia przed zachodem słońca.", author: "przysłowie polskie", translation: null, category: "cierpliwość" },
  { id: "co-nagle-po-diable", lang: "pl", text: "Co nagle, to po diable.", author: "przysłowie polskie", translation: null, category: "cierpliwość" },
  { id: "zgoda-buduje", lang: "pl", text: "Zgoda buduje, niezgoda rujnuje.", author: "przysłowie polskie", translation: null, category: "przyjaźń" },
  { id: "pod-kim-dolki-kopie", lang: "pl", text: "Kto pod kim dołki kopie, ten sam w nie wpada.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "jak-poscielesz", lang: "pl", text: "Jak sobie pościelesz, tak się wyśpisz.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "prawda-w-oczy-kole", lang: "pl", text: "Prawda w oczy kole.", author: "przysłowie polskie", translation: null, category: "prawda" },
  { id: "madrej-glowie", lang: "pl", text: "Mądrej głowie dość dwie słowie.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "pokora-niebo", lang: "pl", text: "Pokora niebo otwiera.", author: "przysłowie polskie", translation: null, category: "pokora" },
  { id: "praca-uszlachetnia", lang: "pl", text: "Praca uszlachetnia.", author: "przysłowie polskie", translation: null, category: "praca" },
  { id: "nie-taki-diabel", lang: "pl", text: "Nie taki diabeł straszny, jak go malują.", author: "przysłowie polskie", translation: null, category: "odwaga" },
  { id: "kto-nie-ryzykuje", lang: "pl", text: "Kto nie ryzykuje, ten nie pije szampana.", author: "przysłowie polskie", translation: null, category: "odwaga" },
  { id: "fortuna-kolem", lang: "pl", text: "Fortuna kołem się toczy.", author: "przysłowie polskie", translation: null, category: "życie" },
  { id: "gdzie-dwoch-sie-bije", lang: "pl", text: "Gdzie dwóch się bije, tam trzeci korzysta.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "apetyt-rosnie", lang: "pl", text: "Apetyt rośnie w miarę jedzenia.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "czlowiek-strzela", lang: "pl", text: "Człowiek strzela, Pan Bóg kule nosi.", author: "przysłowie polskie", translation: null, category: "życie" },
  { id: "cierpliwosc-owoce", lang: "pl", text: "Cierpliwość jest gorzka, ale jej owoce są słodkie.", author: "przysłowie polskie", translation: null, category: "cierpliwość" },

  // ─────────── Uzupełnienie (różne języki) ───────────
  // Łacina
  { id: "vivere-militare", lang: "la", text: "Vivere militare est.", author: "Seneka", translation: "Żyć to walczyć.", category: "wytrwałość" },
  { id: "dies-diem-docet", lang: "la", text: "Dies diem docet.", author: "sentencja łacińska", translation: "Dzień uczy dzień.", category: "rozwój" },
  { id: "verbum-nobile", lang: "la", text: "Verbum nobile debet esse stabile.", author: "sentencja łacińska", translation: "Szlachetne słowo ma być trwałe.", category: "mądrość" },
  { id: "aquila-non-muscas", lang: "la", text: "Aquila non captat muscas.", author: "przysłowie łacińskie", translation: "Orzeł nie chwyta much.", category: "mądrość" },
  { id: "cave-ne-cadas", lang: "la", text: "Cave ne cadas.", author: "sentencja łacińska", translation: "Uważaj, byś nie upadł.", category: "pokora" },
  { id: "amantes-amentes", lang: "la", text: "Amantes amentes.", author: "Terencjusz", translation: "Zakochani — szaleni.", category: "miłość" },
  { id: "amor-tussis", lang: "la", text: "Amor et tussis non celatur.", author: "przysłowie łacińskie", translation: "Miłości i kaszlu nie da się ukryć.", category: "miłość" },

  // Angielski
  { id: "injustice-anywhere", lang: "en", text: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr.", translation: "Niesprawiedliwość gdziekolwiek jest zagrożeniem dla sprawiedliwości wszędzie.", category: "dobroć" },
  { id: "silence-of-friends", lang: "en", text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr.", translation: "W końcu zapamiętamy nie słowa wrogów, lecz milczenie przyjaciół.", category: "przyjaźń" },
  { id: "faith-first-step", lang: "en", text: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King Jr.", translation: "Wiara to pierwszy krok, nawet gdy nie widzisz całych schodów.", category: "odwaga" },
  { id: "think-critically", lang: "en", text: "The function of education is to teach one to think intensively and to think critically.", author: "Martin Luther King Jr.", translation: "Zadaniem edukacji jest nauczyć intensywnego i krytycznego myślenia.", category: "rozwój" },
  { id: "10000-ways", lang: "en", text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison", translation: "Nie poniosłem porażki. Znalazłem 10 000 sposobów, które nie działają.", category: "wytrwałość" },
  { id: "mind-conceive-achieve", lang: "en", text: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill", translation: "Cokolwiek umysł potrafi pojąć i w co uwierzy, może osiągnąć.", category: "marzenia" },
  { id: "ship-in-harbor", lang: "en", text: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd", translation: "Statek w porcie jest bezpieczny, ale nie po to buduje się statki.", category: "odwaga" },
  { id: "knowledge-is-power", lang: "en", text: "Knowledge is power.", author: "Francis Bacon", translation: "Wiedza to potęga.", category: "mądrość" },
  { id: "well-begun-half-done", lang: "en", text: "Well begun is half done.", author: "przysłowie angielskie", translation: "Dobry początek to połowa dzieła.", category: "produktywność" },
  { id: "slow-steady", lang: "en", text: "Slow and steady wins the race.", author: "przysłowie angielskie", translation: "Powoli, lecz pewnie wygrywa się wyścig.", category: "wytrwałość" },
  { id: "early-bird", lang: "en", text: "The early bird catches the worm.", author: "przysłowie angielskie", translation: "Kto rano wstaje, temu chleb się dostaje.", category: "produktywność" },
  { id: "friend-in-need", lang: "en", text: "A friend in need is a friend indeed.", author: "przysłowie angielskie", translation: "Prawdziwych przyjaciół poznaje się w biedzie.", category: "przyjaźń" },
  { id: "hope-best-prepare-worst", lang: "en", text: "Hope for the best, prepare for the worst.", author: "przysłowie angielskie", translation: "Miej nadzieję na najlepsze, przygotuj się na najgorsze.", category: "nadzieja" },
  { id: "count-chickens", lang: "en", text: "Don't count your chickens before they hatch.", author: "przysłowie angielskie", translation: "Nie chwal dnia przed zachodem słońca.", category: "cierpliwość" },

  // Francuski
  { id: "temps-grand-maitre", lang: "fr", text: "Le temps est un grand maître.", author: "Pierre Corneille", translation: "Czas jest wielkim mistrzem.", category: "czas" },
  { id: "bien-faire-laisser-dire", lang: "fr", text: "Bien faire et laisser dire.", author: "przysłowie francuskie", translation: "Rób dobrze i pozwól mówić.", category: "mądrość" },
  { id: "tout-vient-a-point", lang: "fr", text: "Tout vient à point à qui sait attendre.", author: "przysłowie francuskie", translation: "Wszystko przychodzi w porę do tego, kto umie czekać.", category: "cierpliwość" },

  // Niemiecki
  { id: "kleider-machen-leute", lang: "de", text: "Kleider machen Leute.", author: "przysłowie niemieckie", translation: "Jak cię widzą, tak cię piszą.", category: "mądrość" },
  { id: "ende-gut-alles-gut", lang: "de", text: "Ende gut, alles gut.", author: "przysłowie niemieckie", translation: "Wszystko dobre, co się dobrze kończy.", category: "nadzieja" },
  { id: "wer-nicht-wagt", lang: "de", text: "Wer nicht wagt, der nicht gewinnt.", author: "przysłowie niemieckie", translation: "Kto nie ryzykuje, ten nie wygrywa.", category: "odwaga" },

  // Hiszpański
  { id: "ojos-que-no-ven", lang: "es", text: "Ojos que no ven, corazón que no siente.", author: "przysłowie hiszpańskie", translation: "Czego oczy nie widzą, tego sercu nie żal.", category: "mądrość" },
  { id: "camaron-duerme", lang: "es", text: "Camarón que se duerme se lo lleva la corriente.", author: "przysłowie hiszpańskie", translation: "Krewetkę, która zaśnie, porywa prąd.", category: "produktywność" },

  // Włoski
  { id: "chi-ha-tempo", lang: "it", text: "Chi ha tempo non aspetti tempo.", author: "przysłowie włoskie", translation: "Kto ma czas, niech nie czeka.", category: "czas" },
  { id: "caval-donato", lang: "it", text: "A caval donato non si guarda in bocca.", author: "przysłowie włoskie", translation: "Darowanemu koniowi nie zagląda się w zęby.", category: "wdzięczność" },
  { id: "dire-fare-mare", lang: "it", text: "Tra il dire e il fare c'è di mezzo il mare.", author: "przysłowie włoskie", translation: "Między słowem a czynem jest całe morze.", category: "produktywność" },

  // Polski
  { id: "kucharek-szesc", lang: "pl", text: "Gdzie kucharek sześć, tam nie ma co jeść.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "czas-leczy-rany", lang: "pl", text: "Czas leczy rany.", author: "przysłowie polskie", translation: null, category: "czas" },
  { id: "kto-sie-lubi", lang: "pl", text: "Kto się lubi, ten się czubi.", author: "przysłowie polskie", translation: null, category: "miłość" },
  { id: "uderz-w-stol", lang: "pl", text: "Uderz w stół, a nożyce się odezwą.", author: "przysłowie polskie", translation: null, category: "prawda" },
  { id: "grunt-to-zdrowie", lang: "pl", text: "Grunt to zdrowie.", author: "przysłowie polskie", translation: null, category: "życie" },
  { id: "cicha-woda", lang: "pl", text: "Cicha woda brzegi rwie.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "klamstwo-krotkie-nogi", lang: "pl", text: "Kłamstwo ma krótkie nogi.", author: "przysłowie polskie", translation: null, category: "prawda" },
  { id: "baba-z-wozu", lang: "pl", text: "Baba z wozu, koniom lżej.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "nosil-wilk", lang: "pl", text: "Nosił wilk razy kilka, ponieśli i wilka.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "gdzie-kuma-nie-moze", lang: "pl", text: "Gdzie diabeł nie może, tam babę pośle.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "co-dwie-glowy", lang: "pl", text: "Co dwie głowy, to nie jedna.", author: "przysłowie polskie", translation: null, category: "przyjaźń" },
  { id: "bez-ochoty-roboty", lang: "pl", text: "Bez ochoty niespore roboty.", author: "przysłowie polskie", translation: null, category: "produktywność" },

  // ─────────── Uzupełnienie do ~300 ───────────
  { id: "nulla-dies-sine-linea", lang: "la", text: "Nulla dies sine linea.", author: "Pliniusz Starszy", translation: "Ani dnia bez kreski.", category: "praca" },
  { id: "colamus-humanitatem", lang: "la", text: "Dum inter homines sumus, colamus humanitatem.", author: "Seneka", translation: "Póki jesteśmy wśród ludzi, pielęgnujmy człowieczeństwo.", category: "dobroć" },
  { id: "amicitia-prodest", lang: "la", text: "Amicitia semper prodest.", author: "Seneka", translation: "Przyjaźń zawsze przynosi korzyść.", category: "przyjaźń" },
  { id: "qui-scribit-bis-legit", lang: "la", text: "Qui scribit, bis legit.", author: "sentencja łacińska", translation: "Kto pisze, dwa razy czyta.", category: "rozwój" },
  { id: "courage-triumph-fear", lang: "en", text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela", translation: "Odwaga to nie brak strachu, lecz zwycięstwo nad nim.", category: "odwaga" },
  { id: "reading-mind-exercise", lang: "en", text: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison", translation: "Czytanie jest dla umysłu tym, czym ćwiczenie dla ciała.", category: "rozwój" },
  { id: "measure-who-we-are", lang: "en", text: "The measure of who we are is what we do with what we have.", author: "Vince Lombardi", translation: "Miarą tego, kim jesteśmy, jest to, co robimy z tym, co mamy.", category: "rozwój" },
  { id: "change-thoughts-world", lang: "en", text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale", translation: "Zmień myśli, a zmienisz swój świat.", category: "rozwój" },
  { id: "purpose-be-happy", lang: "en", text: "The purpose of our lives is to be happy.", author: "Dalajlama", translation: "Celem naszego życia jest być szczęśliwym.", category: "szczęście" },
  { id: "impossible-journey", lang: "en", text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", translation: "Jedyna niemożliwa podróż to ta, której nigdy nie zaczniesz.", category: "odwaga" },
  { id: "vivre-sans-aimer", lang: "fr", text: "Vivre sans aimer n'est pas proprement vivre.", author: "Molière", translation: "Żyć bez miłości to właściwie nie żyć.", category: "miłość" },
  { id: "weg-ist-ziel", lang: "de", text: "Der Weg ist das Ziel.", author: "przysłowie niemieckie", translation: "Droga jest celem.", category: "życie" },
  { id: "nie-od-razu-krakow", lang: "pl", text: "Nie od razu Kraków zbudowano.", author: "przysłowie polskie", translation: null, category: "cierpliwość" },
  { id: "wrobel-w-garsci", lang: "pl", text: "Lepszy wróbel w garści niż gołąb na dachu.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "kropla-drazy", lang: "pl", text: "Kropla drąży skałę.", author: "przysłowie polskie", translation: null, category: "wytrwałość" },

  // ═══════════ Partia +150 ═══════════
  // Łacina
  { id: "nil-desperandum", lang: "la", text: "Nil desperandum.", author: "Horacy", translation: "Nie należy rozpaczać.", category: "nadzieja" },
  { id: "acta-non-verba", lang: "la", text: "Acta non verba.", author: "sentencja łacińska", translation: "Czyny, nie słowa.", category: "produktywność" },
  { id: "age-quod-agis", lang: "la", text: "Age quod agis.", author: "sentencja łacińska", translation: "Rób [dobrze] to, co robisz.", category: "produktywność" },
  { id: "non-ducor-duco", lang: "la", text: "Non ducor, duco.", author: "sentencja łacińska", translation: "Nie daję się prowadzić — [sam] prowadzę.", category: "odwaga" },
  { id: "aut-viam-inveniam", lang: "la", text: "Aut viam inveniam aut faciam.", author: "Hannibal", translation: "Albo znajdę drogę, albo ją zbuduję.", category: "wytrwałość" },
  { id: "dulcius-ex-asperis", lang: "la", text: "Dulcius ex asperis.", author: "sentencja łacińska", translation: "Słodycz po trudach.", category: "wytrwałość" },
  { id: "virtus-in-medio", lang: "la", text: "Virtus in medio stat.", author: "sentencja łacińska", translation: "Cnota leży pośrodku.", category: "mądrość" },
  { id: "qui-non-laborat", lang: "la", text: "Qui non laborat, non manducet.", author: "św. Paweł", translation: "Kto nie chce pracować, niech też nie je.", category: "praca" },
  { id: "radix-malorum", lang: "la", text: "Radix omnium malorum est cupiditas.", author: "sentencja łacińska", translation: "Chciwość jest korzeniem wszelkiego zła.", category: "mądrość" },
  { id: "cedamus-amori", lang: "la", text: "Omnia vincit amor; et nos cedamus amori.", author: "Wergiliusz", translation: "Miłość wszystko zwycięża; ustąpmy i my miłości.", category: "miłość" },
  { id: "bene-qui-latuit", lang: "la", text: "Bene qui latuit, bene vixit.", author: "Owidiusz", translation: "Dobrze żył, kto dobrze [w spokoju] się ukrył.", category: "spokój" },
  { id: "nemo-propheta", lang: "la", text: "Nemo propheta in patria sua.", author: "Ewangelia św. Łukasza", translation: "Nikt nie jest prorokiem we własnym kraju.", category: "mądrość" },
  { id: "nemo-dat-quod-non-habet", lang: "la", text: "Nemo dat quod non habet.", author: "sentencja łacińska", translation: "Nikt nie daje tego, czego nie ma.", category: "mądrość" },
  { id: "verba-docent-exempla", lang: "la", text: "Verba docent, exempla trahunt.", author: "sentencja łacińska", translation: "Słowa uczą, przykłady pociągają.", category: "rozwój" },
  { id: "aut-disce-aut-discede", lang: "la", text: "Aut disce aut discede.", author: "sentencja łacińska", translation: "Albo się ucz, albo odejdź.", category: "rozwój" },
  { id: "deliberando-perit", lang: "la", text: "Deliberando saepe perit occasio.", author: "Publiliusz Syrus", translation: "Rozważając, często traci się okazję.", category: "czas" },
  { id: "vulnerant-omnes", lang: "la", text: "Vulnerant omnes, ultima necat.", author: "sentencja łacińska", translation: "Wszystkie [godziny] ranią, ostatnia zabija.", category: "czas" },
  { id: "melius-tarde", lang: "la", text: "Melius tarde, quam numquam.", author: "sentencja łacińska", translation: "Lepiej późno niż wcale.", category: "czas" },
  { id: "non-nova-sed-nove", lang: "la", text: "Non nova, sed nove.", author: "sentencja łacińska", translation: "Nie nowe rzeczy, lecz w nowy sposób.", category: "rozwój" },
  { id: "dux-vitae-ratio", lang: "la", text: "Dux vitae ratio.", author: "sentencja łacińska", translation: "Rozum przewodnikiem życia.", category: "mądrość" },
  { id: "ubi-bene-ibi-patria", lang: "la", text: "Ubi bene, ibi patria.", author: "sentencja łacińska", translation: "Gdzie dobrze, tam ojczyzna.", category: "życie" },
  { id: "ad-meliora", lang: "la", text: "Ad meliora.", author: "sentencja łacińska", translation: "Ku lepszemu.", category: "nadzieja" },
  { id: "cato-rem-tene", lang: "la", text: "Rem tene, verba sequentur.", author: "Katon Starszy", translation: "Trzymaj się rzeczy, słowa [same] przyjdą.", category: "mądrość" },
  { id: "vestis-virum-facit", lang: "la", text: "Vestis virum facit.", author: "sentencja łacińska", translation: "Szata czyni człowieka.", category: "mądrość" },
  { id: "dum-inter-homines", lang: "la", text: "Aegroto dum anima est, spes est.", author: "Cyceron", translation: "Póki chory oddycha, jest nadzieja.", category: "nadzieja" },

  // Angielski
  { id: "shallow-luck", lang: "en", text: "Shallow men believe in luck. Strong men believe in cause and effect.", author: "Ralph Waldo Emerson", translation: "Płytcy ludzie wierzą w szczęście. Silni — w przyczynę i skutek.", category: "mądrość" },
  { id: "years-teach", lang: "en", text: "The years teach much which the days never know.", author: "Ralph Waldo Emerson", translation: "Lata uczą wiele, czego dni nigdy nie znają.", category: "czas" },
  { id: "what-you-see", lang: "en", text: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau", translation: "Nie liczy się, na co patrzysz, lecz co widzisz.", category: "mądrość" },
  { id: "courage-mastery-fear", lang: "en", text: "Courage is resistance to fear, mastery of fear — not absence of fear.", author: "Mark Twain", translation: "Odwaga to opór wobec strachu, panowanie nad nim — nie jego brak.", category: "odwaga" },
  { id: "three-hours-too-soon", lang: "en", text: "Better three hours too soon than a minute too late.", author: "William Shakespeare", translation: "Lepiej trzy godziny za wcześnie niż minutę za późno.", category: "czas" },
  { id: "little-candle", lang: "en", text: "How far that little candle throws his beams! So shines a good deed in a weary world.", author: "William Shakespeare", translation: "Jak daleko sięga blask tej małej świecy! Tak jaśnieje dobry uczynek w znużonym świecie.", category: "dobroć" },
  { id: "love-all-trust-few", lang: "en", text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare", translation: "Kochaj wszystkich, ufaj nielicznym, nie krzywdź nikogo.", category: "dobroć" },
  { id: "forgive-enemies", lang: "en", text: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde", translation: "Zawsze wybaczaj wrogom; nic ich tak nie irytuje.", category: "mądrość" },
  { id: "experience-mistakes", lang: "en", text: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde", translation: "Doświadczenie to po prostu nazwa, którą nadajemy swoim błędom.", category: "rozwój" },
  { id: "to-err-forgive", lang: "en", text: "To err is human, to forgive divine.", author: "Alexander Pope", translation: "Błądzić jest rzeczą ludzką, przebaczać — boską.", category: "dobroć" },
  { id: "hope-springs-eternal", lang: "en", text: "Hope springs eternal in the human breast.", author: "Alexander Pope", translation: "Nadzieja wiecznie kiełkuje w ludzkiej piersi.", category: "nadzieja" },
  { id: "great-works-perseverance", lang: "en", text: "Great works are performed not by strength but by perseverance.", author: "Samuel Johnson", translation: "Wielkie dzieła powstają nie siłą, lecz wytrwałością.", category: "wytrwałość" },
  { id: "great-deal-good", lang: "en", text: "He who waits to do a great deal of good at once will never do anything.", author: "Samuel Johnson", translation: "Kto czeka, by naraz uczynić wiele dobra, nie zrobi nic.", category: "dobroć" },
  { id: "either-write-or-do", lang: "en", text: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin", translation: "Albo napisz coś wartego czytania, albo zrób coś wartego opisania.", category: "produktywność" },
  { id: "energy-persistence", lang: "en", text: "Energy and persistence conquer all things.", author: "Benjamin Franklin", translation: "Energia i wytrwałość pokonują wszystko.", category: "wytrwałość" },
  { id: "patience-have-will", lang: "en", text: "He that can have patience can have what he will.", author: "Benjamin Franklin", translation: "Kto ma cierpliwość, może mieć, co zechce.", category: "cierpliwość" },
  { id: "seeds-you-plant", lang: "en", text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson", translation: "Nie oceniaj dnia po zebranych plonach, lecz po zasianych ziarnach.", category: "cierpliwość" },
  { id: "share-your-courage", lang: "en", text: "Keep your fears to yourself, but share your courage with others.", author: "Robert Louis Stevenson", translation: "Zatrzymaj lęki dla siebie, lecz dziel się odwagą z innymi.", category: "odwaga" },
  { id: "words-powerful-drug", lang: "en", text: "Words are, of course, the most powerful drug used by mankind.", author: "Rudyard Kipling", translation: "Słowa to oczywiście najsilniejszy narkotyk, jakiego używa ludzkość.", category: "mądrość" },
  { id: "never-too-late-to-be", lang: "en", text: "It is never too late to be what you might have been.", author: "George Eliot", translation: "Nigdy nie jest za późno, by stać się tym, kim mogłeś być.", category: "rozwój" },
  { id: "exist-as-i-am", lang: "en", text: "I exist as I am, that is enough.", author: "Walt Whitman", translation: "Istnieję taki, jaki jestem, i to wystarcza.", category: "spokój" },
  { id: "hope-thing-feathers", lang: "en", text: "Hope is the thing with feathers that perches in the soul.", author: "Emily Dickinson", translation: "Nadzieja to pierzaste stworzenie, co siada w duszy.", category: "nadzieja" },
  { id: "never-come-again", lang: "en", text: "That it will never come again is what makes life so sweet.", author: "Emily Dickinson", translation: "To, że już nigdy nie wróci, czyni życie tak słodkim.", category: "czas" },
  { id: "rising-every-time", lang: "en", text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", translation: "Największa chwała życia nie w tym, by nigdy nie upaść, lecz by wstawać za każdym razem.", category: "wytrwałość" },
  { id: "winner-dreamer", lang: "en", text: "A winner is a dreamer who never gives up.", author: "Nelson Mandela", translation: "Zwycięzca to marzyciel, który nigdy się nie poddaje.", category: "marzenia" },
  { id: "use-creativity", lang: "en", text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou", translation: "Kreatywności nie da się zużyć. Im więcej jej używasz, tym więcej masz.", category: "rozwój" },
  { id: "rainbow-in-cloud", lang: "en", text: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou", translation: "Staraj się być tęczą w czyjejś chmurze.", category: "dobroć" },
  { id: "best-preparation", lang: "en", text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr.", translation: "Najlepsze przygotowanie na jutro to dać z siebie wszystko dziś.", category: "produktywność" },
  { id: "life-goes-on", lang: "en", text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost", translation: "W trzech słowach streszczę wszystko, czego nauczyłem się o życiu: toczy się dalej.", category: "życie" },
  { id: "daring-adventure", lang: "en", text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller", translation: "Życie to albo śmiała przygoda, albo nic.", category: "odwaga" },
  { id: "optimism-faith", lang: "en", text: "Optimism is the faith that leads to achievement.", author: "Helen Keller", translation: "Optymizm to wiara prowadząca do osiągnięć.", category: "nadzieja" },
  { id: "gentle-shake-world", lang: "en", text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi", translation: "W łagodny sposób możesz wstrząsnąć światem.", category: "dobroć" },
  { id: "indomitable-will", lang: "en", text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi", translation: "Siła nie bierze się z ciała, lecz z niezłomnej woli.", category: "wytrwałość" },
  { id: "living-by-giving", lang: "en", text: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill", translation: "Zarabiamy na życie tym, co bierzemy, ale tworzymy życie tym, co dajemy.", category: "dobroć" },
  { id: "attitude-big-difference", lang: "en", text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill", translation: "Nastawienie to drobiazg, który robi wielką różnicę.", category: "rozwój" },
  { id: "man-of-value", lang: "en", text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein", translation: "Nie staraj się być człowiekiem sukcesu, lecz człowiekiem wartości.", category: "mądrość" },
  { id: "never-stop-questioning", lang: "en", text: "The important thing is not to stop questioning.", author: "Albert Einstein", translation: "Ważne, by nigdy nie przestać pytać.", category: "rozwój" },
  { id: "purpose-of-purpose", lang: "en", text: "The purpose of life is a life of purpose.", author: "Robert Byrne", translation: "Celem życia jest życie pełne celu.", category: "życie" },
  { id: "eggs-one-basket", lang: "en", text: "Don't put all your eggs in one basket.", author: "przysłowie angielskie", translation: "Nie wkładaj wszystkich jajek do jednego koszyka.", category: "mądrość" },
  { id: "picture-thousand-words", lang: "en", text: "A picture is worth a thousand words.", author: "przysłowie angielskie", translation: "Obraz wart tysiąca słów.", category: "mądrość" },
  { id: "necessity-invention", lang: "en", text: "Necessity is the mother of invention.", author: "przysłowie angielskie", translation: "Potrzeba matką wynalazku.", category: "rozwój" },
  { id: "strike-iron-hot", lang: "en", text: "Strike while the iron is hot.", author: "przysłowie angielskie", translation: "Kuj żelazo, póki gorące.", category: "produktywność" },
  { id: "barking-dogs", lang: "en", text: "Barking dogs seldom bite.", author: "przysłowie angielskie", translation: "Pies, który dużo szczeka, rzadko gryzie.", category: "mądrość" },
  { id: "look-before-leap", lang: "en", text: "Look before you leap.", author: "przysłowie angielskie", translation: "Patrz, zanim skoczysz.", category: "mądrość" },

  // Francuski
  { id: "secret-ennuyer", lang: "fr", text: "Le secret d'ennuyer est celui de tout dire.", author: "Voltaire", translation: "Sekret nudzenia to powiedzieć wszystko.", category: "mądrość" },
  { id: "travail-trois-maux", lang: "fr", text: "Le travail éloigne de nous trois grands maux: l'ennui, le vice et le besoin.", author: "Voltaire", translation: "Praca oddala trzy wielkie nieszczęścia: nudę, występek i niedostatek.", category: "praca" },
  { id: "ceux-qui-luttent", lang: "fr", text: "Ceux qui vivent, ce sont ceux qui luttent.", author: "Victor Hugo", translation: "Ci, którzy żyją, to ci, którzy walczą.", category: "wytrwałość" },
  { id: "idee-heure-venue", lang: "fr", text: "Rien n'est plus fort qu'une idée dont l'heure est venue.", author: "Victor Hugo", translation: "Nic nie jest silniejsze od idei, której czas nadszedł.", category: "mądrość" },
  { id: "hypocrisie-hommage", lang: "fr", text: "L'hypocrisie est un hommage que le vice rend à la vertu.", author: "François de La Rochefoucauld", translation: "Hipokryzja to hołd, jaki występek składa cnocie.", category: "mądrość" },
  { id: "plus-petit-que-soi", lang: "fr", text: "On a souvent besoin d'un plus petit que soi.", author: "Jean de La Fontaine", translation: "Często potrzebujemy kogoś mniejszego od siebie.", category: "dobroć" },
  { id: "aide-toi-ciel", lang: "fr", text: "Aide-toi, le Ciel t'aidera.", author: "Jean de La Fontaine", translation: "Pomóż sobie, a niebo ci pomoże.", category: "wytrwałość" },
  { id: "faire-bien-homme", lang: "fr", text: "Il n'est rien de si beau et légitime que de faire bien l'homme.", author: "Michel de Montaigne", translation: "Nie ma nic piękniejszego i słuszniejszego niż być dobrze człowiekiem.", category: "mądrość" },
  { id: "tous-heureux", lang: "fr", text: "Tous les hommes recherchent d'être heureux.", author: "Blaise Pascal", translation: "Wszyscy ludzie pragną być szczęśliwi.", category: "szczęście" },
  { id: "reconnaissance-devoir", lang: "fr", text: "La reconnaissance est un devoir qu'il faut rendre, mais que nul n'a le droit d'exiger.", author: "Jean-Jacques Rousseau", translation: "Wdzięczność to obowiązek, który trzeba spełnić, lecz nikt nie ma prawa go żądać.", category: "wdzięczność" },
  { id: "vaincre-sans-peril", lang: "fr", text: "À vaincre sans péril, on triomphe sans gloire.", author: "Pierre Corneille", translation: "Zwyciężać bez ryzyka to triumfować bez chwały.", category: "odwaga" },
  { id: "liberte-blamer", lang: "fr", text: "Sans la liberté de blâmer, il n'est point d'éloge flatteur.", author: "Beaumarchais", translation: "Bez wolności krytyki nie ma pochwały, która cieszy.", category: "wolność" },
  { id: "resignation-suicide", lang: "fr", text: "La résignation est un suicide quotidien.", author: "Honoré de Balzac", translation: "Rezygnacja to codzienne samobójstwo.", category: "wytrwałość" },
  { id: "solitude-caractere", lang: "fr", text: "On peut tout acquérir dans la solitude, hormis du caractère.", author: "Stendhal", translation: "W samotności można zdobyć wszystko prócz charakteru.", category: "rozwój" },
  { id: "journee-sans-rire", lang: "fr", text: "La plus perdue de toutes les journées est celle où l'on n'a pas ri.", author: "Nicolas de Chamfort", translation: "Najbardziej stracony jest dzień, w którym się nie śmiano.", category: "szczęście" },
  { id: "grandeur-metier-unir", lang: "fr", text: "La grandeur d'un métier est peut-être, avant tout, d'unir les hommes.", author: "Antoine de Saint-Exupéry", translation: "Wielkość zawodu polega może przede wszystkim na tym, że łączy ludzi.", category: "praca" },
  { id: "union-fait-force", lang: "fr", text: "L'union fait la force.", author: "przysłowie francuskie", translation: "W jedności siła.", category: "przyjaźń" },
  { id: "qui-ne-risque", lang: "fr", text: "Qui ne risque rien n'a rien.", author: "przysłowie francuskie", translation: "Kto nie ryzykuje, nic nie ma.", category: "odwaga" },
  { id: "petite-pluie", lang: "fr", text: "Petite pluie abat grand vent.", author: "przysłowie francuskie", translation: "Mały deszcz zbija wielki wiatr.", category: "spokój" },
  { id: "coeur-vaillant", lang: "fr", text: "À cœur vaillant rien d'impossible.", author: "przysłowie francuskie", translation: "Dla dzielnego serca nie ma rzeczy niemożliwych.", category: "odwaga" },
  { id: "premier-pas-coute", lang: "fr", text: "Il n'y a que le premier pas qui coûte.", author: "przysłowie francuskie", translation: "Tylko pierwszy krok kosztuje.", category: "odwaga" },
  { id: "prevenir-guerir", lang: "fr", text: "Mieux vaut prévenir que guérir.", author: "przysłowie francuskie", translation: "Lepiej zapobiegać niż leczyć.", category: "mądrość" },

  // Niemiecki
  { id: "sieht-nur-was-man-weiss", lang: "de", text: "Man sieht nur das, was man weiß.", author: "Johann Wolfgang von Goethe", translation: "Widzimy tylko to, co wiemy.", category: "mądrość" },
  { id: "worte-genug-taten", lang: "de", text: "Der Worte sind genug gewechselt, lasst mich auch endlich Taten sehn!", author: "Johann Wolfgang von Goethe", translation: "Dość już wymieniono słów — pozwólcie mi wreszcie ujrzeć czyny!", category: "produktywność" },
  { id: "wahre-wiederholen", lang: "de", text: "Man muss das Wahre immer wiederholen, weil auch der Irrtum um uns her immer wieder gepredigt wird.", author: "Johann Wolfgang von Goethe", translation: "Prawdę trzeba wciąż powtarzać, bo i błąd wokół nas wciąż jest głoszony.", category: "prawda" },
  { id: "nichts-wagt-hoffen", lang: "de", text: "Wer nichts wagt, der darf nichts hoffen.", author: "Friedrich Schiller", translation: "Kto nic nie ryzykuje, nie może na nic liczyć.", category: "odwaga" },
  { id: "ernst-leben-heiter-kunst", lang: "de", text: "Ernst ist das Leben, heiter ist die Kunst.", author: "Friedrich Schiller", translation: "Poważne jest życie, pogodna jest sztuka.", category: "piękno" },
  { id: "langsamste-ziel", lang: "de", text: "Der langsamste, der sein Ziel nicht aus den Augen verliert, geht noch immer geschwinder als jener, der ohne Ziel umherirrt.", author: "Gotthold Ephraim Lessing", translation: "Najwolniejszy, kto nie traci celu z oczu, idzie szybciej niż ten, kto błądzi bez celu.", category: "wytrwałość" },
  { id: "aus-schmerzen-lieder", lang: "de", text: "Aus meinen großen Schmerzen mach ich die kleinen Lieder.", author: "Heinrich Heine", translation: "Z moich wielkich cierpień tworzę małe pieśni.", category: "piękno" },
  { id: "schlange-haeuten", lang: "de", text: "Die Schlange, welche sich nicht häuten kann, geht zugrunde.", author: "Friedrich Nietzsche", translation: "Wąż, który nie potrafi zrzucić skóry, ginie.", category: "rozwój" },
  { id: "bestirnte-himmel", lang: "de", text: "Der bestirnte Himmel über mir und das moralische Gesetz in mir.", author: "Immanuel Kant", translation: "Niebo gwiaździste nade mną i prawo moralne we mnie.", category: "mądrość" },
  { id: "wer-nichts-weiss", lang: "de", text: "Wer nichts weiß, muss alles glauben.", author: "Marie von Ebner-Eschenbach", translation: "Kto nic nie wie, musi we wszystko wierzyć.", category: "mądrość" },
  { id: "kluger-bemerkt", lang: "de", text: "Ein kluger Mensch bemerkt alles, ein dummer macht über alles eine Bemerkung.", author: "Marie von Ebner-Eschenbach", translation: "Mądry wszystko zauważa, głupi o wszystkim się wypowiada.", category: "mądrość" },
  { id: "wunsch-junge", lang: "de", text: "Ein jeder Wunsch, wenn er erfüllt, kriegt augenblicklich Junge.", author: "Wilhelm Busch", translation: "Każde życzenie, gdy spełnione, natychmiast rodzi młode.", category: "mądrość" },
  { id: "reden-silber", lang: "de", text: "Reden ist Silber, Schweigen ist Gold.", author: "przysłowie niemieckie", translation: "Mowa jest srebrem, milczenie złotem.", category: "spokój" },
  { id: "koeche-brei", lang: "de", text: "Viele Köche verderben den Brei.", author: "przysłowie niemieckie", translation: "Gdzie kucharek sześć, tam nie ma co jeść.", category: "mądrość" },
  { id: "nicht-alles-gold", lang: "de", text: "Es ist nicht alles Gold, was glänzt.", author: "przysłowie niemieckie", translation: "Nie wszystko złoto, co się świeci.", category: "prawda" },
  { id: "apfel-stamm", lang: "de", text: "Der Apfel fällt nicht weit vom Stamm.", author: "przysłowie niemieckie", translation: "Niedaleko pada jabłko od jabłoni.", category: "rozwój" },
  { id: "zuletzt-lacht", lang: "de", text: "Wer zuletzt lacht, lacht am besten.", author: "przysłowie niemieckie", translation: "Ten się śmieje, kto się śmieje ostatni.", category: "mądrość" },
  { id: "gut-ding-weile", lang: "de", text: "Gut Ding will Weile haben.", author: "przysłowie niemieckie", translation: "Dobra rzecz wymaga czasu.", category: "cierpliwość" },

  // Hiszpański
  { id: "pluma-lengua-alma", lang: "es", text: "La pluma es la lengua del alma.", author: "Miguel de Cervantes", translation: "Pióro to język duszy.", category: "mądrość" },
  { id: "madruga-disfruta", lang: "es", text: "El que no madruga con el sol no disfruta de la jornada.", author: "Miguel de Cervantes", translation: "Kto nie wstaje ze słońcem, nie cieszy się dniem.", category: "produktywność" },
  { id: "vida-es-sueno", lang: "es", text: "Toda la vida es sueño, y los sueños, sueños son.", author: "Pedro Calderón de la Barca", translation: "Całe życie jest snem, a sny — snami są.", category: "życie" },
  { id: "tiempo-testigo", lang: "es", text: "No hay mejor testigo que el tiempo.", author: "przysłowie hiszpańskie", translation: "Nie ma lepszego świadka niż czas.", category: "czas" },
  { id: "nada-te-turbe", lang: "es", text: "Nada te turbe, nada te espante; quien a Dios tiene, nada le falta.", author: "Teresa z Ávili", translation: "Niech nic cię nie trwoży; kto ma Boga, temu niczego nie brak.", category: "spokój" },
  { id: "saber-libre", lang: "es", text: "Sólo el que sabe es libre, y más libre el que más sabe.", author: "Miguel de Unamuno", translation: "Tylko ten, kto wie, jest wolny; a bardziej wolny, kto więcej wie.", category: "wolność" },
  { id: "dime-con-quien", lang: "es", text: "Dime con quién andas y te diré quién eres.", author: "przysłowie hiszpańskie", translation: "Powiedz mi, z kim się zadajesz, a powiem ci, kim jesteś.", category: "mądrość" },
  { id: "no-hay-mal-bien", lang: "es", text: "No hay mal que por bien no venga.", author: "przysłowie hiszpańskie", translation: "Nie ma tego złego, co by na dobre nie wyszło.", category: "nadzieja" },
  { id: "perro-ladra", lang: "es", text: "Perro que ladra no muerde.", author: "przysłowie hiszpańskie", translation: "Pies, który szczeka, nie gryzie.", category: "mądrość" },
  { id: "prevenir-curar", lang: "es", text: "Más vale prevenir que curar.", author: "przysłowie hiszpańskie", translation: "Lepiej zapobiegać niż leczyć.", category: "mądrość" },
  { id: "madruga-dios", lang: "es", text: "A quien madruga, Dios le ayuda.", author: "przysłowie hiszpańskie", translation: "Kto rano wstaje, temu Pan Bóg daje.", category: "produktywność" },
  { id: "saber-no-ocupa", lang: "es", text: "El saber no ocupa lugar.", author: "przysłowie hiszpańskie", translation: "Wiedza nie zajmuje miejsca.", category: "rozwój" },

  // Włoski
  { id: "petrarca-arde", lang: "it", text: "Chi può dir com'egli arde è in picciol foco.", author: "Francesco Petrarca", translation: "Kto potrafi opisać, jak płonie, płonie słabym ogniem.", category: "miłość" },
  { id: "nel-mezzo-cammin", lang: "it", text: "Nel mezzo del cammin di nostra vita.", author: "Dante Alighieri", translation: "W połowie drogi naszego życia.", category: "życie" },
  { id: "riveder-stelle", lang: "it", text: "E quindi uscimmo a riveder le stelle.", author: "Dante Alighieri", translation: "I stamtąd wyszliśmy, by znów ujrzeć gwiazdy.", category: "nadzieja" },
  { id: "machiavelli-patrimonio", lang: "it", text: "Gli uomini dimenticano più presto la morte del padre che la perdita del patrimonio.", author: "Niccolò Machiavelli", translation: "Ludzie prędzej zapominają śmierć ojca niż utratę majątku.", category: "mądrość" },
  { id: "leonardo-vita-merita", lang: "it", text: "Chi non stima la vita, non la merita.", author: "Leonardo da Vinci", translation: "Kto nie ceni życia, nie zasługuje na nie.", category: "życie" },
  { id: "eppur-si-muove", lang: "it", text: "Eppur si muove.", author: "Galileo Galilei", translation: "A jednak się kręci.", category: "prawda" },
  { id: "chi-va-zoppo", lang: "it", text: "Chi va con lo zoppo impara a zoppicare.", author: "przysłowie włoskie", translation: "Kto z kulawym chodzi, uczy się kuleć.", category: "mądrość" },
  { id: "male-non-nuocere", lang: "it", text: "Non tutto il male viene per nuocere.", author: "przysłowie włoskie", translation: "Nie każde zło przynosi szkodę.", category: "nadzieja" },
  { id: "mattino-oro", lang: "it", text: "Il mattino ha l'oro in bocca.", author: "przysłowie włoskie", translation: "Kto rano wstaje, temu Pan Bóg daje.", category: "produktywność" },
  { id: "chi-la-dura", lang: "it", text: "Chi la dura la vince.", author: "przysłowie włoskie", translation: "Kto wytrwa, ten zwycięża.", category: "wytrwałość" },
  { id: "sbagliando-impara", lang: "it", text: "Sbagliando s'impara.", author: "przysłowie włoskie", translation: "Na błędach się uczymy.", category: "rozwój" },
  { id: "can-abbaia", lang: "it", text: "Can che abbaia non morde.", author: "przysłowie włoskie", translation: "Pies, który szczeka, nie gryzie.", category: "mądrość" },

  // Polski
  { id: "fraszki-mysli", lang: "pl", text: "Fraszki to wszystko, cokolwiek myślemy.", author: "Jan Kochanowski", translation: null, category: "życie" },
  { id: "fredro-uczy-glupim", lang: "pl", text: "Człowiek uczy się przez całe życie, a i tak głupim umiera.", author: "Aleksander Fredro", translation: null, category: "rozwój" },
  { id: "norwid-skad-wyszlo", lang: "pl", text: "Aby mierzyć drogę przyszłą, trzeba wiedzieć, skąd się wyszło.", author: "Cyprian Kamil Norwid", translation: null, category: "mądrość" },
  { id: "prus-grzebien", lang: "pl", text: "Doświadczenie jest to grzebień, który los daje człowiekowi, gdy ten już wyłysieje.", author: "Bolesław Prus", translation: null, category: "mądrość" },
  { id: "nie-ma-dymu", lang: "pl", text: "Nie ma dymu bez ognia.", author: "przysłowie polskie", translation: null, category: "prawda" },
  { id: "w-domu-najlepiej", lang: "pl", text: "Wszędzie dobrze, ale w domu najlepiej.", author: "przysłowie polskie", translation: null, category: "życie" },
  { id: "drwa-rabia", lang: "pl", text: "Gdzie drwa rąbią, tam wióry lecą.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "jaka-praca-placa", lang: "pl", text: "Jaka praca, taka płaca.", author: "przysłowie polskie", translation: null, category: "praca" },
  { id: "co-ma-wisiec", lang: "pl", text: "Co ma wisieć, nie utonie.", author: "przysłowie polskie", translation: null, category: "życie" },
  { id: "dobrymi-chieciami", lang: "pl", text: "Dobrymi chęciami piekło jest wybrukowane.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "mieczem-wojuje", lang: "pl", text: "Kto mieczem wojuje, od miecza ginie.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "prawda-wyplynie", lang: "pl", text: "Prawda zawsze na wierzch wypłynie.", author: "przysłowie polskie", translation: null, category: "prawda" },
  { id: "wolnosc-tomku", lang: "pl", text: "Wolnoć Tomku w swoim domku.", author: "przysłowie polskie", translation: null, category: "wolność" },
  { id: "cel-srodki", lang: "pl", text: "Cel uświęca środki.", author: "przysłowie polskie", translation: null, category: "mądrość" },
  { id: "milosc-ukryc", lang: "pl", text: "Miłości, kaszlu i ubóstwa ukryć nie można.", author: "przysłowie polskie", translation: null, category: "miłość" },
  { id: "swieci-garnki", lang: "pl", text: "Nie święci garnki lepią.", author: "przysłowie polskie", translation: null, category: "rozwój" },
  { id: "amor-omnibus-idem", lang: "la", text: "Amor omnibus idem.", author: "Wergiliusz", translation: "Miłość u wszystkich jednaka.", category: "miłość" },
];

export const QUOTE_BY_ID: Record<string, Quote> = Object.fromEntries(
  QUOTES.map((q) => [q.id, q])
);

// Stable per-day pick: same quote for a given date. Simple string hash so the
// choice is deterministic without storing anything.
export function dailyQuoteId(dayKey: string): string {
  let hash = 0;
  for (let i = 0; i < dayKey.length; i++) {
    hash = (hash * 31 + dayKey.charCodeAt(i)) | 0;
  }
  const index = Math.abs(hash) % QUOTES.length;
  return QUOTES[index].id;
}

/** A random quote id, optionally different from `excludeId`. */
export function randomQuoteId(excludeId?: string): string {
  if (QUOTES.length <= 1) return QUOTES[0].id;
  let q = QUOTES[Math.floor(Math.random() * QUOTES.length)];
  while (q.id === excludeId) q = QUOTES[Math.floor(Math.random() * QUOTES.length)];
  return q.id;
}

export function isKnownQuoteId(id: string): boolean {
  return id in QUOTE_BY_ID;
}
