// Aerobics / fitness ladder 1-99. Manual — progression tracks: sessions,
// choreography/technique, sport aerobics elements, and competition level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "aerobik",
  name: "Aerobik",
  icon: "🤸",
  description:
    "Fitness grupowy i aerobik sportowy — od podstawowych kroków po elementy trudności i zawody. Progresja: sesje, choreografia, elementy i poziom rywalizacji.",
  sortOrder: 66,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj podstawowe kroki (march, step-touch, grapevine)", undefined, prog("technika", 1)],
  ["Ukończ pierwsze zajęcia aerobiku (45 min)", undefined, prog("sesje", 1)],
  ["Utrzymaj rytm z muzyką przez całą piosenkę", undefined, prog("technika", 2)],
  ["Opanuj kroki high/low impact", undefined, prog("technika", 3)],
  ["Zaliczy 5 zajęć", undefined, prog("sesje", 5)],
  ["Wykonaj prostą kombinację 4 kroków z pamięci", undefined, prog("technika", 4)],
  ["Utrzymaj intensywność przez pełne zajęcia bez przerwy", undefined, prog("technika", 5)],
  ["Wykonaj podstawowe ruchy ramion zsynchronizowane z nogami", undefined, prog("technika", 6)],
  ["Zaliczy 10 zajęć", undefined, prog("sesje", 10)],
  ["Zapamiętaj i wykonaj krótką choreografię (32 takty)", undefined, prog("choreo", 1)],
  // 11-25 · Regularny
  ["Ćwicz 3 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Opanuj kroki step aerobiku (na stepie)", undefined, prog("technika", 7)],
  ["Zaliczy 20 zajęć", undefined, prog("sesje", 20)],
  ["Wykonaj choreografię 64 takty bez błędu", undefined, prog("choreo", 2)],
  ["Opanuj pivot i turn w choreografii", undefined, prog("technika", 8)],
  ["Wykonaj pierwsze pompki i przysiady w tempie aerobiku sportowego", undefined, prog("elementy", 1)],
  ["Zaliczy 40 zajęć", undefined, prog("sesje", 40)],
  ["Wykonaj jumping jacks i power moves w rytmie", undefined, prog("technika", 9)],
  ["Wykonaj szpagat (podstawowy element gibkości)", undefined, prog("elementy", 2)],
  ["Wykonaj choreografię z lustrzanym odbiciem (obie strony)", undefined, prog("choreo", 3)],
  ["Zaliczy 60 zajęć", undefined, prog("sesje", 60)],
  ["Prowadź fragment rozgrzewki dla grupy", undefined, prog("technika", 10)],
  ["Wykonaj element skoku z obrotem (podstawowy)", undefined, prog("elementy", 3)],
  ["Wykonaj pełną choreografię zajęć (kilka bloków) z pamięci", undefined, prog("choreo", 4)],
  ["Zaliczy 80 zajęć", undefined, prog("sesje", 80)],
  // 26-45 · Średniozaawansowany
  ["Ćwicz 4 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(4, 12)],
  ["Wykonaj push-up do pozycji rozkroku (element aerobiku sportowego)", undefined, prog("elementy", 4)],
  ["Zaliczy 100 zajęć", undefined, prog("sesje", 100)],
  ["Wykonaj skok w rozkroku (split leap)", undefined, prog("elementy", 5)],
  ["Opanuj złożoną choreografię z power i flexibility", undefined, prog("choreo", 5)],
  ["Wykonaj pompki jednorącz (element siłowy grupy A)", undefined, prog("elementy", 6)],
  ["Zajmij miejsce w pierwszej połowie zawodów amatorskich aerobiku sportowego"],
  ["Zaliczy 150 zajęć", undefined, prog("sesje", 150)],
  ["Wykonaj L-sit / V-sit w choreografii", undefined, prog("elementy", 7)],
  ["Wykonaj skok z obrotem 360° z lądowaniem", undefined, prog("elementy", 8)],
  ["Poprowadź całe zajęcia jako instruktor", undefined, prog("technika", 11)],
  ["Zaliczy 200 zajęć", undefined, prog("sesje", 200)],
  ["Wykonaj free fall push-up (element grupy A)", undefined, prog("elementy", 9)],
  ["Wykonaj układ zawodniczy (1:20) z elementami wszystkich grup", undefined, prog("choreo", 6)],
  ["Zajmij miejsce na podium zawodów amatorskich"],
  ["Wykonaj wysoki skok w szpagacie (switch leap)", undefined, prog("elementy", 10)],
  ["Zaliczy 250 zajęć", undefined, prog("sesje", 250)],
  ["Wykonaj element równowagi (illusion / needle)", undefined, prog("elementy", 11)],
  ["Utrzymaj pełną intensywność przez cały układ zawodniczy", undefined, prog("technika", 12)],
  ["Wykonaj capoeira / helikopter (element grupy C)", undefined, prog("elementy", 12)],
  // 46-65 · Zaawansowany
  ["Trenuj jak zawodnik aerobiku sportowego przez sezon"],
  ["Wykonaj pompkę Wenson (element grupy A)", undefined, prog("elementy", 13)],
  ["Zaliczy 300 zajęć", undefined, prog("sesje", 300)],
  ["Wykonaj skok z podwójnym obrotem (720°)", undefined, prog("elementy", 14)],
  ["Zajmij miejsce w czołówce mistrzostw kraju (kategoria)"],
  ["Wykonaj plansza push-up (planche element)", undefined, prog("elementy", 15)],
  ["Wykonaj układ zawodniczy z elementami trudności C i D", undefined, prog("choreo", 7)],
  ["Zaliczy 400 zajęć", undefined, prog("sesje", 400)],
  ["Wykonaj hinge / air turn (element skokowy zaawansowany)", undefined, prog("elementy", 16)],
  ["Wykonaj gainer lub salto w układzie (jeśli dozwolone w kategorii)", undefined, prog("elementy", 17)],
  ["Zdobądź minimum na mistrzostwa kraju seniorów"],
  ["Wykonaj element o wartości trudności 0,7+ (skala FIG)", undefined, prog("elementy", 18)],
  ["Zaliczy 500 zajęć", undefined, prog("sesje", 500)],
  ["Wykonaj perfekcyjnie zsynchronizowany układ pary/trójki", undefined, prog("choreo", 8)],
  ["Zdobądź medal mistrzostw kraju juniorów"],
  ["Wykonaj element o wartości trudności 0,8+", undefined, prog("elementy", 19)],
  ["Zaliczy 600 zajęć", undefined, prog("sesje", 600)],
  ["Utrzymaj czystość techniczną w całym układzie pod presją", undefined, prog("technika", 13)],
  ["Wykonaj element o wartości trudności 0,9+", undefined, prog("elementy", 20)],
  ["Uzyskaj notę kwalifikującą do zawodów międzynarodowych"],
  // 66-85 · Wyczynowy
  ["Wystartuj w zawodach międzynarodowych aerobiku sportowego"],
  ["Wykonaj element o wartości trudności 1,0", undefined, prog("elementy", 21)],
  ["Zaliczy 700 zajęć", undefined, prog("sesje", 700)],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Wykonaj układ z minimum 10 elementami trudności bez błędu", undefined, prog("choreo", 9)],
  ["Zdobądź punkty w Pucharze Świata FIG"],
  ["Wykonaj element o wartości trudności 1,1", undefined, prog("elementy", 22)],
  ["Zaliczy 800 zajęć", undefined, prog("sesje", 800)],
  ["Zajmij miejsce w pierwszej ósemce zawodów o zasięgu ogólnokrajowym"],
  ["Wykonaj element o wartości trudności 1,2", undefined, prog("elementy", 23)],
  ["Utrzymaj wysoką intensywność i ekspresję sceniczną", undefined, prog("technika", 14)],
  ["Zaliczy 1000 zajęć", undefined, prog("sesje", 1000)],
  ["Zdobądź medal zawodów o zasięgu ogólnokrajowym"],
  ["Wykonaj element o wartości trudności 1,3", undefined, prog("elementy", 24)],
  ["Weź udział w mistrzostwach regionu"],
  ["Wykonaj układ na bardzo wysokim, wieloletnio wypracowanym poziomie", undefined, prog("choreo", 10)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw regionu"],
  ["Wykonaj element o wartości trudności 1,4", undefined, prog("elementy", 25)],
  ["Zdobądź medal mistrzostw regionu"],
  ["Zostań mistrzem kraju amatorów"],
  // 86-99 · Elita
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Wykonaj element o wartości trudności 1,5", undefined, prog("elementy", 26)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju amatorów"],
  ["Wykonaj perfekcyjny układ z najwyższą notą wykonania", undefined, prog("technika", 15)],
  ["Wykonaj element o wartości trudności 1,6", undefined, prog("elementy", 27)],
  ["Awansuj do finału mistrzostw kraju amatorów"],
  ["Wykonaj element o wartości trudności 1,7", undefined, prog("elementy", 28)],
  ["Zdobądź medal mistrzostw kraju amatorów"],
  ["Wykonaj autorski element lub kombinację o najwyższej trudności", undefined, prog("elementy", 29)],
  ["Zdobądź złoto mistrzostw kraju amatorów w konkurencji"],
  ["Zdobądź medal w kilku konkurencjach mistrzostw kraju amatorów"],
  ["Utrzymaj czołową pozycję w kraju przez cały sezon"],
  ["Zostań wielokrotnym mistrzem kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): wielokrotny mistrz kraju amatorów w aerobiku sportowym", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata FIG) potwierdzają osobne certyfikaty."],
]);
