// Watercolour ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, counts scaled; top tiers reframed as attainable
// mastery, real feats left to future certificates).
// Tracks: umiejetnosci, prace (finished watercolours), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "akwarela",
  name: "Akwarela",
  icon: "🖌️",
  description:
    "Malarstwo akwarelowe — kontrola wody, lawowanie, planowanie świateł. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → wystawy → dojrzały, autorski warsztat.",
  sortOrder: 83,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Poznaj sprzęt: papier, farby, pędzle, woda", undefined, prog("umiejetnosci", 1)],
  ["Połóż równą lawę (płaski wash) na całej płaszczyźnie", undefined, prog("umiejetnosci", 2)],
  ["Wykonaj lawę gradientową (od ciemnej do jasnej)", undefined, prog("umiejetnosci", 3)],
  ["Maluj mokrym w mokre (wet-on-wet) i kontroluj rozlanie", undefined, prog("umiejetnosci", 4)],
  ["Zaplanuj i zachowaj biele papieru (światła)", undefined, prog("umiejetnosci", 5)],
  ["Namaluj prostą pracę (owoc, liść) od jasnych do ciemnych", undefined, prog("prace", 3)],
  ["Zmieszaj czyste barwy bez zabłocenia koloru", undefined, prog("umiejetnosci", 6)],
  ["Buduj warstwy (glazing) po wyschnięciu", undefined, prog("umiejetnosci", 7)],
  ["Ukończ 10 akwarel", undefined, prog("prace", 10)],
  ["Maluj akwarelą łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Maluj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Kontroluj wilgotność papieru i pędzla (timing)", undefined, prog("umiejetnosci", 8)],
  ["Namaluj prosty pejzaż akwarelowy z planami", undefined, prog("prace", 15)],
  ["Opanuj miękkie i twarde krawędzie", undefined, prog("umiejetnosci", 9)],
  ["Zbuduj przestrzeń przez perspektywę powietrzną", undefined, prog("umiejetnosci", 10)],
  ["Maluj akwarelą łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Namaluj martwą naturę z pełnym zakresem walorów", undefined, prog("umiejetnosci", 11)],
  ["Ukończ 30 akwarel", undefined, prog("prace", 30)],
  ["Opanuj technikę na sucho (dry brush) i fakturę", undefined, prog("umiejetnosci", 12)],
  ["Maluj szybkie szkice akwarelowe w plenerze", undefined, prog("umiejetnosci", 13)],
  ["Prowadź szkicownik akwarelowy przez 2 tygodnie", undefined, prog("prace", 45)],
  ["Opanuj świadomy dobór palety (ograniczona gama)", undefined, prog("umiejetnosci", 14)],
  ["Maluj akwarelą łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Namaluj portret lub postać akwarelą", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 60 akwarel", undefined, prog("prace", 60)],
  // 26-45 · Średniozaawansowany
  ["Maluj regularnie przez 8 kolejnych tygodni", undefined, freq(3, 8)],
  ["Opanuj światło i nastrój (mgła, deszcz, słońce)", undefined, prog("umiejetnosci", 16)],
  ["Namaluj złożony pejzaż z bogatą przestrzenią", undefined, prog("umiejetnosci", 17)],
  ["Ukończ 90 akwarel", undefined, prog("prace", 90)],
  ["Maluj pewnie „za jednym razem” bez poprawek", undefined, prog("umiejetnosci", 18)],
  ["Maluj akwarelą łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Opanuj architekturę / miasto w akwareli", undefined, prog("umiejetnosci", 19)],
  ["Zbuduj spójną kolorystykę i harmonię pracy", undefined, prog("umiejetnosci", 20)],
  ["Ukończ 130 akwarel", undefined, prog("prace", 130)],
  ["Maluj z wyobraźni / z uproszczeniem formy", undefined, prog("umiejetnosci", 21)],
  ["Opanuj kompozycję i prowadzenie wzroku", undefined, prog("umiejetnosci", 22)],
  ["Maluj akwarelą łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Namaluj serię prac o wspólnym motywie", undefined, prog("prace", 170)],
  ["Opanuj różne techniki (granulacja, sól, maskowanie)", undefined, prog("umiejetnosci", 23)],
  ["Zbuduj dopracowaną, „wystawową” akwarelę", undefined, prog("umiejetnosci", 24)],
  ["Ukończ 200 akwarel", undefined, prog("prace", 200)],
  ["Opanuj wodę i refleksy (pejzaż nadmorski/rzeczny)", undefined, prog("umiejetnosci", 25)],
  ["Maluj akwarelą łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Namaluj duży format z pełną kontrolą lawowania", undefined, prog("umiejetnosci", 26)],
  ["Maluj w plenerze przez cały sezon", undefined, prog("prace", 250)],
  // 46-65 · Zaawansowany (amator)
  ["Maluj regularnie przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Wypracuj rozpoznawalny, osobisty język akwareli", undefined, prog("umiejetnosci", 27)],
  ["Zbuduj spójną serię tematyczną (5-10 prac)", undefined, prog("umiejetnosci", 28)],
  ["Ukończ 300 akwarel", undefined, prog("prace", 300)],
  ["Maluj akwarelą łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Pokaż prace publicznie i zbierz opinie odbiorców"],
  ["Namaluj ambitną, dopracowaną kompozycję", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 380 akwarel", undefined, prog("prace", 380)],
  ["Opanuj świadomą stylizację (realizm ↔ ekspresja)", undefined, prog("umiejetnosci", 30)],
  ["Maluj akwarelą łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj portfolio najlepszych prac"],
  ["Weź udział w wystawie zbiorowej lub konkursie"],
  ["Opanuj złożone oświetlenie i atmosferę", undefined, prog("umiejetnosci", 31)],
  ["Ukończ 450 akwarel", undefined, prog("prace", 450)],
  ["Sprzedaj pracę / zrealizuj zamówienie", undefined, prog("umiejetnosci", 32)],
  ["Maluj akwarelą łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy akwareli", undefined, prog("umiejetnosci", 33)],
  ["Zrealizuj spójny cykl prac wokół jednego pomysłu"],
  ["Namaluj „galeryjną” akwarelę na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 550 akwarel", undefined, prog("prace", 550)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Maluj regularnie przez pełny sezon (6 miesięcy)"],
  ["Maluj swobodnie z wyobraźni złożone sceny", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 650 akwarel", undefined, prog("prace", 650)],
  ["Maluj akwarelą łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zorganizuj małą wystawę indywidualną (lokalnie / online)"],
  ["Rozwiń warsztat na tyle, by uczyć akwareli", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie sprzedajesz prace lub realizujesz zlecenia"],
  ["Opanuj wybraną specjalizację (pejzaż / botanika / miasto)", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 800 akwarel", undefined, prog("prace", 800)],
  ["Zdobądź wyróżnienie w konkursie lub uznanie w społeczności"],
  ["Maluj akwarelą łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny, wieloczęściowy cykl autorski", undefined, prog("umiejetnosci", 38)],
  ["Twoje akwarele są dojrzałe i rozpoznawalne bez podpisu"],
  ["Ukończ 1000 akwarel", undefined, prog("prace", 1000)],
  ["Zbuduj grono odbiorców swoich prac"],
  ["Poprowadź warsztaty lub mentoring dla malujących"],
  ["Łącz kontrolę i spontaniczność w dojrzały sposób", undefined, prog("umiejetnosci", 39)],
  ["Zrealizuj wystawę prezentującą Twój dorobek"],
  ["Ukończ 1200 akwarel", undefined, prog("prace", 1200)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Maluj akwarelą łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdej pracy"],
  ["Ukończ 1400 akwarel", undefined, prog("prace", 1400)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych malujących w Twoim otoczeniu"],
  ["Namaluj osobisty „opus” — dużą, dopracowaną pracę lub cykl", undefined, prog("umiejetnosci", 40)],
  ["Regularnie wystawiasz swoje akwarele"],
  ["Maluj akwarelą łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje prace zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 1600 akwarel", undefined, prog("prace", 1600)],
  ["Uczysz i kształtujesz kolejnych akwarelistów"],
  ["Masz dorobek, z którego można ułożyć wystawę retrospektywną"],
  ["Malujesz swobodnie wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski warsztat", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones. Videos from Louise De Masi, Jenna Rainey, Kirsty Partridge i in.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  // — Rozszerzenie zasobów Tier 1 (wszystkie linki zweryfikowane jako aktywne) —
  6: [{ kind: "video", title: "Pierwsza akwarela: wskazówki na start", url: yt("tP8Z-n0ppBM") }],
  9: [{ kind: "article", title: "Papier akwarelowy: przewodnik po rodzajach", url: "https://www.jacksonsart.com/blog/2021/04/15/a-guide-to-watercolour-paper/" }],
  10: [{ kind: "video", title: "Jak dobrać kolory do palety", url: yt("6TZgxDrIY18") }],
  11: [{ kind: "video", title: "Codzienna rutyna ćwiczeń akwarelowych", url: yt("Q2m4A6q98ZU") }],
  12: [{ kind: "video", title: "Panowanie nad techniką mokrym w mokre", url: yt("Vg19sNs48xU") }],
  13: [{ kind: "video", title: "Realistyczny liść — botanika w akwareli", url: yt("XpSP5icbVGs") }],
  16: [{ kind: "video", title: "Pejzaż górski: mokre w mokre i sucha technika", url: yt("yOjuKlo7Sxo") }],
  17: [{ kind: "article", title: "Perspektywa i głębia w pejzażu", url: "https://www.solvingwatercolour.com/watercolor-landscapes-depth-perspective/" }],
  18: [{ kind: "video", title: "Jak zbudować profesjonalne portfolio", url: yt("9BI13bpf8FU") }],
  20: [{ kind: "video", title: "Portret akwarelą: pełne demo i karnacja", url: yt("EoAC9iF4Rp4") }],
  25: [{ kind: "video", title: "Plener: porady i techniki malowania", url: yt("fp5wtsLc-8s") }],
  1: [{ kind: "video", title: "Materiały: papier, farby, pędzle", url: yt("qyJs4VhDoBs") }],
  2: [{ kind: "video", title: "Lawa płaska (flat wash)", url: yt("efSp9VWnft8") }],
  3: [{ kind: "video", title: "Lawa gradientowa", url: yt("Xo7k51lZLV0") }],
  4: [{ kind: "video", title: "Mokrym w mokre (wet-on-wet)", url: yt("mxGxSISbpjk") }],
  5: [{ kind: "video", title: "Zachowywanie bieli papieru", url: yt("iZ6Fqz1GCFU") }],
  7: [{ kind: "video", title: "Mieszanie barw bez zabłocenia", url: yt("FiKYmVfpOcw") }],
  8: [{ kind: "video", title: "Lawowanie warstwami (glazing)", url: yt("2kF4mys5F40") }],
  14: [{ kind: "video", title: "Miękkie i twarde krawędzie", url: yt("mpdnd30G6CA") }],
  15: [{ kind: "video", title: "Perspektywa powietrzna (głębia)", url: yt("I9fLyTaJEhY") }],
  19: [{ kind: "video", title: "Technika na sucho (dry brush)", url: yt("U1aJi-afiTU") }],
  22: [{ kind: "video", title: "Ograniczona paleta", url: yt("gbOvOVPvV6Y") }],
  32: [{ kind: "video", title: "Architektura / miasto w akwareli", url: yt("tAwobwnwxiA") }],
  39: [{ kind: "video", title: "Granulacja, sól, maskowanie", url: yt("SY97DyAXWBw") }],
};
