// Animation ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, shot counts scaled; top tiers reframed as
// attainable mastery, real feats left to future certificates).
// Tracks: umiejetnosci, ujecia (finished shots), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "animacja",
  name: "Animacja",
  icon: "🎞️",
  description:
    "Wprawianie rysunków i postaci w ruch — od bouncing ball po animację aktorską. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → showreel i projekty → dojrzały, autorski styl.",
  sortOrder: 95,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Poznaj klatki kluczowe (keyframes) i międzyfazy (inbetweens)", undefined, prog("umiejetnosci", 1)],
  ["Zanimuj odbijającą się piłkę (bouncing ball)", "Pierwsze ćwiczenie każdego animatora.", prog("umiejetnosci", 2)],
  ["Zastosuj timing i spacing (rozstaw klatek)", undefined, prog("umiejetnosci", 3)],
  ["Dodaj squash & stretch (ściśnięcie i rozciągnięcie)", undefined, prog("umiejetnosci", 4)],
  ["Zanimuj wahadło / ciężki i lekki obiekt", undefined, prog("umiejetnosci", 5)],
  ["Zastosuj anticipation i follow-through", undefined, prog("umiejetnosci", 6)],
  ["Zanimuj prosty ruch z easing (ease in/out)", undefined, prog("umiejetnosci", 7)],
  ["Ukończ pierwsze 3 krótkie ujęcia animacji", undefined, prog("ujecia", 3)],
  ["Ukończ 8 ujęć", undefined, prog("ujecia", 8)],
  ["Animuj łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Animuj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Opanuj wszystkie 12 zasad animacji", undefined, prog("umiejetnosci", 8)],
  ["Zanimuj flour sack (worek mąki — pierwsza postać z emocją)", undefined, prog("umiejetnosci", 9)],
  ["Zanimuj cykl chodu (walk cycle)", undefined, prog("umiejetnosci", 10)],
  ["Ukończ 16 ujęć", undefined, prog("ujecia", 16)],
  ["Animuj łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Zanimuj cykl biegu i skok", undefined, prog("umiejetnosci", 11)],
  ["Ukończ 28 ujęć", undefined, prog("ujecia", 28)],
  ["Zbuduj mocne pozy kluczowe (posing, sylwetka)", undefined, prog("umiejetnosci", 12)],
  ["Zanimuj podnoszenie ciężkiego obiektu (waga i wysiłek)", undefined, prog("umiejetnosci", 13)],
  ["Zanimuj prostą pantomimę (akcja bez dialogu)", undefined, prog("umiejetnosci", 14)],
  ["Animuj łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Opanuj overlapping action i drugorzędny ruch", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 45 ujęć", undefined, prog("ujecia", 45)],
  ["Zanimuj wyraz twarzy i lip sync (synchronizacja ust)", undefined, prog("umiejetnosci", 16)],
  // 26-45 · Średniozaawansowany
  ["Animuj regularnie przez 8 kolejnych tygodni", undefined, freq(3, 8)],
  ["Zanimuj scenę aktorską z emocją (acting shot)", undefined, prog("umiejetnosci", 17)],
  ["Zanimuj dialog z pełnym lip sync i gestem", undefined, prog("umiejetnosci", 18)],
  ["Ukończ 65 ujęć", undefined, prog("ujecia", 65)],
  ["Opanuj interakcję dwóch postaci (kontakt, ciężar wspólny)", undefined, prog("umiejetnosci", 19)],
  ["Animuj łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Zbuduj czytelną narrację ruchu (readability, staging)", undefined, prog("umiejetnosci", 20)],
  ["Zanimuj czworonoga lub stworzenie fantastyczne", undefined, prog("umiejetnosci", 21)],
  ["Opanuj animację kamery / ruch inscenizacji", undefined, prog("umiejetnosci", 22)],
  ["Zanimuj złożoną akcję (walka, taniec, akrobacja)", undefined, prog("umiejetnosci", 23)],
  ["Ukończ 90 ujęć", undefined, prog("ujecia", 90)],
  ["Zbuduj postać z osobowością wyrażoną ruchem", undefined, prog("umiejetnosci", 24)],
  ["Animuj łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Ukończ krótki film animowany od storyboardu po finał", undefined, prog("umiejetnosci", 25)],
  ["Ukończ 120 ujęć", undefined, prog("ujecia", 120)],
  ["Zbuduj rozpoznawalny styl animacji", undefined, prog("umiejetnosci", 26)],
  ["Animuj łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Zanimuj scenę na poziomie portfolio (dopracowaną)", undefined, prog("umiejetnosci", 27)],
  ["Ukończ 150 ujęć", undefined, prog("ujecia", 150)],
  ["Animuj regularnie przez 3 miesiące", undefined, prog("ujecia", 175)],
  // 46-65 · Zaawansowany (amator)
  ["Animuj regularnie przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Zrealizuj złożoną sekwencję z wieloma postaciami", undefined, prog("umiejetnosci", 28)],
  ["Opanuj subtelną animację aktorską (mikroekspresje)", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 210 ujęć", undefined, prog("ujecia", 210)],
  ["Animuj łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Publikuj prace i buduj widownię / portfolio"],
  ["Zbuduj profesjonalny showreel", undefined, prog("umiejetnosci", 30)],
  ["Ukończ 270 ujęć", undefined, prog("ujecia", 270)],
  ["Zrealizuj samodzielny krótki film animowany", undefined, prog("umiejetnosci", 31)],
  ["Animuj łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Wygraj lub wyróżnij się w konkursie / na festiwalu"],
  ["Sprzedaj pierwsze zlecenie / zdobądź płatną pracę"],
  ["Opanuj reżyserię animacji (timing sceny, rytm)", undefined, prog("umiejetnosci", 32)],
  ["Ukończ 340 ujęć", undefined, prog("ujecia", 340)],
  ["Realizuj płatne zlecenia animacyjne regularnie", undefined, prog("umiejetnosci", 33)],
  ["Animuj łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy animacji"],
  ["Zrealizuj spójny cykl / serię animacji"],
  ["Zanimuj sekwencję na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 420 ujęć", undefined, prog("ujecia", 420)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Animuj regularnie przez pełny sezon (6 miesięcy)"],
  ["Animuj swobodnie złożone sceny aktorskie i akcji", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 500 ujęć", undefined, prog("ujecia", 500)],
  ["Animuj łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zbuduj społeczność / grono odbiorców swojej animacji"],
  ["Rozwiń warsztat na tyle, by uczyć animacji", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie realizujesz płatne zlecenia animacyjne"],
  ["Opanuj każdy typ animacji na wysokim poziomie", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 600 ujęć", undefined, prog("ujecia", 600)],
  ["Zdobądź wyróżnienie na festiwalu lub uznanie w społeczności"],
  ["Animuj łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny film autorski (dłuższy metraż)", undefined, prog("umiejetnosci", 38)],
  ["Twoja animacja jest dojrzała i rozpoznawalna", undefined, prog("umiejetnosci", 39)],
  ["Ukończ 720 ujęć", undefined, prog("ujecia", 720)],
  ["Zbuduj markę o zasięgu ponadlokalnym"],
  ["Poprowadź warsztaty lub mentoring dla animatorów"],
  ["Publikuj kursy lub tutoriale animacji"],
  ["Zrealizuj pokaz lub publikację prezentującą dorobek"],
  ["Ukończ 850 ujęć", undefined, prog("ujecia", 850)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Animuj łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdym ujęciu"],
  ["Ukończ 1000 ujęć", undefined, prog("ujecia", 1000)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych animatorów w Twoim otoczeniu"],
  ["Zrealizuj osobisty „opus” — samodzielny film animowany", undefined, prog("umiejetnosci", 40)],
  ["Regularnie publikujesz animacje lub realizujesz duże projekty"],
  ["Animuj łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje animacje zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 1200 ujęć", undefined, prog("ujecia", 1200)],
  ["Uczysz i kształtujesz kolejnych animatorów"],
  ["Masz dorobek, z którego można ułożyć retrospektywę"],
  ["Zanimujesz niemal wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski styl", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (12 zasad animacji + ćwiczenia bazowe: Alan Becker i in.).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Straight ahead vs pose-to-pose (klatki)", url: yt("v8quCbt4C-c") }],
  2: [{ kind: "video", title: "Odbijająca się piłka (bouncing ball)", url: yt("y43LS6PHJGg") }],
  3: [{ kind: "video", title: "Timing i spacing (rozstaw klatek)", url: yt("BarOk2p38LQ") }],
  4: [{ kind: "video", title: "Squash & stretch (ściśnięcie/rozciągnięcie)", url: yt("haa7n3UGyDc") }],
  6: [{ kind: "video", title: "Follow-through i overlapping action", url: yt("4OxphYV8W3E") }],
  12: [{ kind: "video", title: "12 zasad animacji — pełna seria", url: yt("uDqjIdI4bF4") }],
  13: [{ kind: "video", title: "Flour sack — worek mąki z emocją", url: yt("Qsgt8DVh558") }],
  14: [{ kind: "video", title: "Cykl chodu (walk cycle)", url: yt("tpZfDPEz68M") }],
  17: [{ kind: "video", title: "Cykl biegu (run cycle)", url: yt("7NkvAP3aqeo") }],
  25: [{ kind: "video", title: "Lip sync i kształty ust", url: yt("h7U2YvmIMOo") }],
  27: [{ kind: "video", title: "Scena aktorska — blocking", url: yt("6cihU6C_ksk") }],
};
