// Badminton ladder 1-99. Tracks: rally length, serve accuracy, matches;
// stroke technique and tournament milestones manual.
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "badminton",
  name: "Badminton",
  icon: "🏸",
  description:
    "Najszybszy sport rakietowy świata — od pierwszej wymiany po turnieje. Lotka potrafi lecieć 400 km/h.",
  sortOrder: 12,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Odbij lotkę rakietą 10 razy w górę"],
  ["Wymień z partnerem 5 uderzeń bez upadku lotki"],
  ["Wykonaj prawidłowy serwis krótki (bekhendowy)"],
  ["Wymień 10 uderzeń"],
  ["Wykonaj serwis wysoki (forhendowy) do końca pola"],
  ["Wymień 20 uderzeń"],
  ["Zagraj clear — wysoko i głęboko na tył kortu"],
  ["Traf serwisem w pole 8/10", "Serwis w badmintonie musi być pewny."],
  ["Wymień 30 uderzeń"],
  ["Rozegraj pierwszego seta do 21"],
  // 11-25 · Regularny
  ["Graj raz w tygodniu przez 4 kolejne tygodnie"],
  ["Zagraj drop — krótką lotkę tuż za siatkę"],
  ["Rozegraj pierwszy mecz (2 z 3 setów)"],
  ["Wymień 50 uderzeń"],
  ["Zagraj pierwszy smecz"],
  ["Rozegraj 5 meczów"],
  ["Opanuj poruszanie krokiem dostawnym do 4 rogów kortu"],
  ["Zagraj netdrop (krótka przy siatce po krótkiej)"],
  ["Wygraj pierwszego seta"],
  ["Rozegraj 10 meczów"],
  ["Wymień 75 uderzeń"],
  ["Wygraj pierwszy mecz"],
  ["Graj 2 razy w tygodniu przez 8 kolejnych tygodni"],
  ["Zagraj lob obronny spod siatki na tył kortu"],
  ["Traf serwisem krótkim tuż za linię 8/10"],
  // 26-45 · Średniozaawansowany
  ["Rozegraj 20 meczów"],
  ["Zagraj smecz punktowy 3 razy w jednym meczu"],
  ["Wymień 100 uderzeń", "Setka wymiany — kondycja i kontrola."],
  ["Wygraj 5 meczów"],
  ["Zagraj bekhendowy clear z tyłu kortu", "Jedno z najtrudniejszych uderzeń amatora."],
  ["Rozegraj 35 meczów"],
  ["Zagraj mecz deblowy ze świadomą rotacją ustawień"],
  ["Wygraj 10 meczów"],
  ["Zagraj zwodzony drop (deception) wygrywający punkt"],
  ["Rozegraj 50 meczów"],
  ["Wygraj seta do 10 lub niżej"],
  ["Zagraj smecz z wyskoku (jump smash)"],
  ["Wygraj 20 meczów"],
  ["Weź udział w turnieju amatorskim"],
  ["Obron 3 smecze z rzędu w jednej wymianie"],
  ["Wygraj mecz w turnieju amatorskim"],
  ["Rozegraj 75 meczów"],
  ["Wygraj 30 meczów"],
  ["Zagraj pełny mecz singla bez błędów serwisowych"],
  ["Rozegraj 100 meczów", "Setka na korcie."],
  // 46-65 · Zaawansowany
  ["Wygraj 50 meczów"],
  ["Osiągnij ćwierćfinał turnieju amatorskiego"],
  ["Zagraj mecz taktyczny na wytrzymałość rywala (długie wymiany celowo)"],
  ["Rozegraj 150 meczów"],
  ["Wygraj 3 mecze w jednym turnieju"],
  ["Wygraj 75 meczów"],
  ["Osiągnij półfinał turnieju amatorskiego"],
  ["Zagraj miksta w turnieju"],
  ["Rozegraj 200 meczów"],
  ["Wygraj 100 meczów"],
  ["Wygraj turniej amatorski", "Pierwsze złoto."],
  ["Dołącz do klubu z sekcją badmintona"],
  ["Rozegraj 250 meczów"],
  ["Pokonaj zawodnika z licencją PZBad"],
  ["Wygraj 150 meczów"],
  ["Zagraj sezon w lidze amatorskiej"],
  ["Rozegraj 300 meczów"],
  ["Wygraj drugi turniej amatorski"],
  ["Wygraj 200 meczów"],
  ["Zdobądź licencję zawodniczą PZBad"],
  // 66-85 · Wyczynowy
  ["Rozegraj 400 meczów"],
  ["Zagraj mecz ligowy"],
  ["Wygraj 250 meczów"],
  ["Wygraj mecz ligowy"],
  ["Rozegraj 500 meczów"],
  ["Wygraj 5 turniejów łącznie"],
  ["Rozegraj pełny sezon ligowy jako podstawowy zawodnik"],
  ["Wygraj 300 meczów"],
  ["Osiągnij dodatni bilans sezonu ligowego"],
  ["Awansuj z drużyną do wyższej klasy"],
  ["Rozegraj 600 meczów"],
  ["Wygraj turniej rangi wojewódzkiej"],
  ["Wygraj 400 meczów"],
  ["Zagraj 50 meczów ligowych"],
  ["Zdobądź punkty w rankingu krajowym"],
  ["Rozegraj 750 meczów"],
  ["Zdobądź medal mistrzostw województwa"],
  ["Wygraj 500 meczów"],
  ["Zagraj w turnieju ogólnopolskim (cykl Krajowych Turniejów)"],
  ["Wygraj mistrzostwa województwa"],
  // 86-99 · Elita
  ["Rozegraj 900 meczów"],
  ["Wygraj 600 meczów"],
  ["Osiągnij czołową 50 rankingu krajowego w swojej kategorii"],
  ["Rozegraj 1000 meczów", "Tysiąc meczów z lotką."],
  ["Wygraj mecz w turnieju ogólnopolskim"],
  ["Wygraj 750 meczów"],
  ["Zagraj 100 meczów ligowych"],
  ["Osiągnij czołową dziesiątkę rankingu regionalnego"],
  ["Zdobądź podium regionalnego turnieju"],
  ["Zagraj na poziomie silnej ligi regionalnej"],
  ["Wygraj 900 meczów"],
  ["Zdobądź podium mistrzostw regionu (dowolna kategoria)"],
  ["Wygraj turniej regionalny rankingowy"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, czołowy zawodnik regionu", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  2: prog("wymiana", 5), 4: prog("wymiana", 10), 6: prog("wymiana", 20), 9: prog("wymiana", 30),
  14: prog("wymiana", 50), 21: prog("wymiana", 75), 28: prog("wymiana", 100),
  8: prog("serwis", 8), 25: prog("serwis-krotki", 8),
  13: prog("mecze", 1), 16: prog("mecze", 5), 20: prog("mecze", 10), 26: prog("mecze", 20),
  31: prog("mecze", 35), 35: prog("mecze", 50), 42: prog("mecze", 75), 45: prog("mecze", 100),
  49: prog("mecze", 150), 54: prog("mecze", 200), 58: prog("mecze", 250), 62: prog("mecze", 300),
  66: prog("mecze", 400), 70: prog("mecze", 500), 76: prog("mecze", 600), 81: prog("mecze", 750),
  86: prog("mecze", 900), 89: prog("mecze", 1000),
  22: prog("wygrane", 1), 29: prog("wygrane", 5), 33: prog("wygrane", 10), 38: prog("wygrane", 20),
  43: prog("wygrane", 30), 46: prog("wygrane", 50), 51: prog("wygrane", 75), 55: prog("wygrane", 100),
  60: prog("wygrane", 150), 64: prog("wygrane", 200), 68: prog("wygrane", 250), 73: prog("wygrane", 300),
  78: prog("wygrane", 400), 83: prog("wygrane", 500), 87: prog("wygrane", 600), 91: prog("wygrane", 750),
  96: prog("wygrane", 900),
  11: freq(1, 4), 23: freq(2, 8),
  // pozostałe: technika i osiągnięcia — manualne.
};
