// Baseball ladder 1-99. Manual — progression tracks: matches played, hits
// (total), and competition level. Includes batting/pitching skill milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "baseball",
  name: "Baseball",
  icon: "⚾",
  description:
    "Amerykańska klasyka — pałkarstwo, miotanie i gra polowa. Progresja: rozegrane mecze, uderzenia (hits) i poziom rozgrywek.",
  sortOrder: 51,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Złap piłkę do rękawicy z bliska", undefined, prog("technika", 1)],
  ["Rzuć piłkę celnie na 15 m", undefined, prog("technika", 2)],
  ["Uderz piłkę z tee (podstawki) kijem", undefined, prog("technika", 3)],
  ["Uderz piłkę rzuconą wprost (soft toss)", undefined, prog("technika", 4)],
  ["Przebiegnij bazy we właściwej kolejności", undefined, prog("technika", 5)],
  ["Złap piłkę lecącą górą (fly ball)", undefined, prog("technika", 6)],
  ["Rzuć poprawnie zza głowy na dystans (overhand)", undefined, prog("technika", 7)],
  ["Zagraj pierwszy mecz treningowy", undefined, prog("mecze", 1)],
  ["Zalicz pierwsze uderzenie w grze (base hit)", undefined, prog("hity", 1)],
  ["Rozegraj pełny mecz (9 zmian lub skrócony)", undefined, prog("mecze", 2)],
  // 11-25 · Regularny
  ["Trenuj lub graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Uderz piłkę rzuconą przez miotacza (live pitching)", undefined, prog("technika", 8)],
  ["Zagraj 5 meczów", undefined, prog("mecze", 5)],
  ["Zalicz 10 uderzeń łącznie", undefined, prog("hity", 10)],
  ["Wykonaj skuteczny out w polu (fielding play)", undefined, prog("technika", 9)],
  ["Zagraj na stałej pozycji polowej przez cały mecz"],
  ["Zagraj 10 meczów", undefined, prog("mecze", 10)],
  ["Zalicz 20 uderzeń łącznie", undefined, prog("hity", 20)],
  ["Rzucaj jako miotacz (pitcher) całą zmianę", undefined, prog("technika", 10)],
  ["Rozegraj mecz w lidze amatorskiej", undefined, prog("liga", 1)],
  ["Zagraj 20 meczów", undefined, prog("mecze", 20)],
  ["Zalicz 40 uderzeń łącznie", undefined, prog("hity", 40)],
  ["Zdobądź pierwszy home run", undefined, prog("technika", 11)],
  ["Zalicz 2 uderzenia w jednym meczu", undefined, prog("hity-mecz", 2)],
  ["Zagraj 30 meczów", undefined, prog("mecze", 30)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zalicz 60 uderzeń łącznie", undefined, prog("hity", 60)],
  ["Rzucaj drugą piłkę (curveball lub changeup)", undefined, prog("technika", 12)],
  ["Zagraj 50 meczów", undefined, prog("mecze", 50)],
  ["Zalicz 90 uderzeń łącznie", undefined, prog("hity", 90)],
  ["Rozegraj pełny sezon w regularnej lidze", undefined, prog("liga", 2)],
  ["Zalicz 3 uderzenia w jednym meczu", undefined, prog("hity-mecz", 3)],
  ["Wykonaj double play jako część obrony", undefined, prog("technika", 13)],
  ["Zagraj 75 meczów", undefined, prog("mecze", 75)],
  ["Zalicz 130 uderzeń łącznie", undefined, prog("hity", 130)],
  ["Zajmij miejsce w pierwszej połowie tabeli ligowej"],
  ["Utrzymaj średnią uderzeń (AVG) powyżej .300 w sezonie", undefined, prog("technika", 14)],
  ["Zagraj 100 meczów", undefined, prog("mecze", 100)],
  ["Zalicz 180 uderzeń łącznie", undefined, prog("hity", 180)],
  ["Rozegraj mecz w II lidze lub odpowiedniku", undefined, prog("liga", 3)],
  ["Zostań liderem drużyny w uderzeniach lub RBI w rundzie"],
  ["Zalicz 250 uderzeń łącznie", undefined, prog("hity", 250)],
  ["Zagraj 150 meczów", undefined, prog("mecze", 150)],
  ["Rzucaj shutout jako miotacz (mecz bez straconego punktu)", undefined, prog("technika", 15)],
  ["Zalicz 4 uderzenia w jednym meczu", undefined, prog("hity-mecz", 4)],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Zalicz 350 uderzeń łącznie", undefined, prog("hity", 350)],
  ["Rozegraj mecz w I lidze", undefined, prog("liga", 4)],
  ["Zagraj 200 meczów", undefined, prog("mecze", 200)],
  ["Zalicz 450 uderzeń łącznie", undefined, prog("hity", 450)],
  ["Zostań podstawowym zawodnikiem zespołu I-ligowego"],
  ["Zalicz 5 uderzeń w jednym meczu", undefined, prog("hity-mecz", 5)],
  ["Zagraj 250 meczów", undefined, prog("mecze", 250)],
  ["Zalicz 600 uderzeń łącznie", undefined, prog("hity", 600)],
  ["Zajmij miejsce w czołówce I ligi"],
  ["Rozegraj mecz w najwyższej lidze krajowej", undefined, prog("liga", 5)],
  ["Zalicz 750 uderzeń łącznie", undefined, prog("hity", 750)],
  ["Zagraj 300 meczów", undefined, prog("mecze", 300)],
  ["Zalicz uderzenie w meczu najwyższej ligi"],
  ["Zalicz 900 uderzeń łącznie", undefined, prog("hity", 900)],
  ["Zostań podstawowym zawodnikiem najwyższej ligi"],
  ["Zagraj 400 meczów", undefined, prog("mecze", 400)],
  ["Zalicz 1100 uderzeń łącznie", undefined, prog("hity", 1100)],
  ["Zostań najlepszym pałkarzem rundy w lidze"],
  ["Zostań rozpoznawalnym zawodnikiem w swoim regionie"],
  // 66-85 · Wyczynowy
  ["Zalicz 1300 uderzeń łącznie", undefined, prog("hity", 1300)],
  ["Zagraj 500 meczów", undefined, prog("mecze", 500)],
  ["Zostań filarem drużyny najwyższej ligi"],
  ["Zalicz 1500 uderzeń łącznie", undefined, prog("hity", 1500)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Zagraj 600 meczów", undefined, prog("mecze", 600)],
  ["Zalicz 1700 uderzeń łącznie", undefined, prog("hity", 1700)],
  ["Zostań uznanym zawodnikiem swojej ligi regionalnej"],
  ["Zalicz 1900 uderzeń łącznie", undefined, prog("hity", 1900)],
  ["Zagraj 700 meczów", undefined, prog("mecze", 700)],
  ["Zalicz uderzenie w ważnym meczu ligowym"],
  ["Zalicz 2100 uderzeń łącznie", undefined, prog("hity", 2100)],
  ["Zagraj w rozgrywkach o zasięgu ogólnokrajowym"],
  ["Zalicz 2300 uderzeń łącznie", undefined, prog("hity", 2300)],
  ["Zagraj 800 meczów", undefined, prog("mecze", 800)],
  ["Zdobądź podium mistrzostw regionu z klubem"],
  ["Weź udział w turnieju o zasięgu ogólnokrajowym"],
  ["Zalicz 2500 uderzeń łącznie", undefined, prog("hity", 2500)],
  ["Zagraj 900 meczów", undefined, prog("mecze", 900)],
  ["Zostań kapitanem swojej drużyny klubowej"],
  // 86-99 · Elita
  ["Zalicz 2700 uderzeń łącznie", undefined, prog("hity", 2700)],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zagraj 1000 meczów", undefined, prog("mecze", 1000)],
  ["Zalicz 3000 uderzeń łącznie", "Magiczna granica 3000 hitów.", prog("hity", 3000)],
  ["Zalicz uderzenie w ważnym meczu ligowym"],
  ["Zagraj w turnieju o zasięgu ogólnokrajowym"],
  ["Zostań czołowym pałkarzem swojej ligi"],
  ["Zdobądź tytuł mistrzowski swojej ligi klubowej"],
  ["Znajdź się w składzie gwiazd sezonu (all-star team)"],
  ["Zdobądź nagrodę MVP swojej ligi lub turnieju"],
  ["Poprowadź drużynę jako lider przez cały sezon"],
  ["Zagraj w finale rozgrywek ligowych"],
  ["Wygraj mistrzostwo swojej ligi klubowej"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej drużyny klubowej", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);
