// Orienteering ladder 1-99. Manual — progression tracks: navigation skill,
// course difficulty, and competition level. Combines running and map-reading.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "bieg-na-orientacje",
  name: "Bieg na orientację",
  icon: "🧭",
  description:
    "Bieg z mapą i kompasem przez nieznany teren — od pierwszej trasy po zawody rangi światowej. Progresja: nawigacja, trudność trasy i poziom zawodów.",
  sortOrder: 73,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Zorientuj mapę względem terenu i północy", undefined, prog("nawigacja", 1)],
  ["Odczytaj podstawowe znaki mapy sportowej (OŚ)", undefined, prog("nawigacja", 2)],
  ["Ukończ prostą trasę wzdłuż ścieżek (żółta/biała)", undefined, prog("trasa", 1)],
  ["Użyj kompasu do wyznaczenia kierunku (azymut)", undefined, prog("nawigacja", 3)],
  ["Potwierdź punkty kontrolne w prawidłowej kolejności", undefined, prog("nawigacja", 4)],
  ["Ukończ trasę z punktami poza ścieżkami (pomarańczowa)", undefined, prog("trasa", 2)],
  ["Zliczaj odległość krokami (pomiar dystansu)", undefined, prog("nawigacja", 5)],
  ["Ukończ pierwsze zawody amatorskie", undefined, prog("liga", 1)],
  ["Ukończ trasę bez pomyłki (błędu nawigacyjnego)", undefined, prog("nawigacja", 6)],
  ["Ukończ 5 tras/zawodów łącznie", undefined, prog("trasa", 3)],
  // 11-25 · Regularny
  ["Trenuj/startuj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Opanuj bieg po azymucie na dłuższym odcinku", undefined, prog("nawigacja", 7)],
  ["Ukończ trasę o średniej trudności (czerwona/technika lasu)", undefined, prog("trasa", 4)],
  ["Wybierz optymalny wariant trasy między punktami (route choice)", undefined, prog("nawigacja", 8)],
  ["Ukończ 15 startów łącznie", undefined, prog("trasa", 5)],
  ["Utrzymaj tempo biegu bez utraty orientacji", undefined, prog("nawigacja", 9)],
  ["Ukończ zawody sprint (miejskie, szybka nawigacja)", undefined, prog("trasa", 6)],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  ["Opanuj czytanie rzeźby terenu (warstwice, formy)", undefined, prog("nawigacja", 10)],
  ["Ukończ trudną trasę leśną (czarna/elita amatorska)", undefined, prog("trasa", 7)],
  ["Ukończ 30 startów łącznie", undefined, prog("trasa", 8)],
  ["Nawiguj precyzyjnie do małego punktu (mikrorelief)", undefined, prog("nawigacja", 11)],
  ["Ukończ zawody na dystansie długim (classic/long)", undefined, prog("trasa", 9)],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Ukończ 50 startów łącznie", undefined, prog("trasa", 10)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 3 razy w tygodniu (bieg + technika) przez 12 tyg.", undefined, freq(3, 12)],
  ["Utrzymaj czystą nawigację przy wysokim tempie", undefined, prog("nawigacja", 12)],
  ["Ukończ zawody nocne (nawigacja po ciemku)", undefined, prog("trasa", 11)],
  ["Wybieraj warianty pod presją czasu bezbłędnie", undefined, prog("nawigacja", 13)],
  ["Ukończ 75 startów łącznie", undefined, prog("trasa", 12)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw okręgu"],
  ["Ukończ zawody sztafetowe jako część zespołu", undefined, prog("trasa", 13)],
  ["Opanuj „simplifikację” mapy (upraszczanie w biegu)", undefined, prog("nawigacja", 14)],
  ["Ukończ 100 startów łącznie", undefined, prog("trasa", 14)],
  ["Zdobądź minimum na mistrzostwa kraju (kategoria)", undefined, prog("liga", 2)],
  ["Nawiguj bezbłędnie w skomplikowanym terenie (kamienie/bagna)", undefined, prog("nawigacja", 15)],
  ["Ukończ zawody typu middle na wysokim poziomie", undefined, prog("trasa", 15)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju"],
  ["Ukończ 150 startów łącznie", undefined, prog("trasa", 16)],
  ["Utrzymaj koncentrację nawigacyjną przez cały długi dystans", undefined, prog("nawigacja", 16)],
  ["Zdobądź medal mistrzostw kraju juniorów/masters"],
  ["Ukończ 200 startów łącznie", undefined, prog("trasa", 17)],
  ["Opanuj bieg na przełaj z minimalnym patrzeniem na mapę", undefined, prog("nawigacja", 17)],
  ["Zajmij miejsce w pierwszej czwórce mistrzostw kraju"],
  ["Ukończ zawody wieloetapowe (multiday) w czołówce"],
  // 46-65 · Zaawansowany
  ["Trenuj jak zawodnik (bieg + mapa) przez cały sezon"],
  ["Osiągnij poziom nawigacji „bez błędu” w każdej dyscyplinie", undefined, prog("nawigacja", 18)],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Ukończ 250 startów łącznie", undefined, prog("trasa", 18)],
  ["Wygraj zawody rangi ogólnokrajowej"],
  ["Utrzymaj tempo bliskie biegowemu przy pełnej nawigacji", undefined, prog("nawigacja", 19)],
  ["Zostań mistrzem kraju w jednej z konkurencji"],
  ["Zdobądź czołową pozycję w rankingu regionalnym", undefined, prog("liga", 3)],
  ["Ukończ 300 startów łącznie", undefined, prog("trasa", 19)],
  ["Wystartuj w zawodach międzynarodowych (World Ranking Event)"],
  ["Zajmij miejsce w pierwszej połowie zawodów międzynarodowych"],
  ["Opanuj nawigację w nieznanych typach terenu (skandynawskie lasy, skały)", undefined, prog("nawigacja", 20)],
  ["Ukończ 400 startów łącznie", undefined, prog("trasa", 20)],
  ["Zdobądź punkty w rankingu krajowym", undefined, prog("liga", 4)],
  ["Zajmij miejsce w pierwszej dwudziestce zawodów o zasięgu ogólnokrajowym"],
  ["Wygraj zawody o zasięgu ogólnokrajowym niższej rangi"],
  ["Ukończ 500 startów łącznie", undefined, prog("trasa", 21)],
  ["Weź udział w mistrzostwach regionu"],
  ["Zajmij miejsce w pierwszej połowie mistrzostw regionu"],
  ["Utrzymaj perfekcyjną nawigację pod presją zawodów", undefined, prog("nawigacja", 21)],
  // 66-85 · Wyczynowy
  ["Zajmij miejsce w pierwszej dwudziestce mistrzostw regionu"],
  ["Osiągnij czołową 50 rankingu krajowego"],
  ["Ukończ 600 startów łącznie", undefined, prog("trasa", 22)],
  ["Zajmij miejsce w finale A mistrzostw regionu"],
  ["Wygraj etap zawodów o zasięgu ogólnokrajowym niższej rangi"],
  ["Osiągnij mistrzowską precyzję nawigacyjną na maksymalnym tempie", undefined, prog("nawigacja", 22)],
  ["Osiągnij czołową 30 rankingu krajowego"],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Ukończ 700 startów łącznie", undefined, prog("trasa", 23)],
  ["Zajmij miejsce w finale A mistrzostw kraju amatorów"],
  ["Zdobądź punkty w klasyfikacji zawodów o zasięgu ogólnokrajowym"],
  ["Zajmij miejsce w pierwszej piętnastce mistrzostw kraju amatorów"],
  ["Osiągnij czołową 20 rankingu krajowego"],
  ["Zdobądź medal mistrzostw regionu"],
  ["Ukończ 800 startów łącznie", undefined, prog("trasa", 24)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju amatorów"],
  ["Osiągnij czołową dziesiątkę rankingu krajowego"],
  ["Zajmij miejsce na podium etapu zawodów o zasięgu ogólnokrajowym"],
  ["Zdobądź medal mistrzostw kraju amatorów w sztafecie"],
  ["Osiągnij status uznanego zawodnika w krajowym środowisku", undefined, prog("nawigacja", 23)],
  // 86-99 · Elita
  ["Zdobądź indywidualny medal mistrzostw kraju amatorów"],
  ["Osiągnij czołową piątkę rankingu krajowego"],
  ["Wygraj etap zawodów o zasięgu ogólnokrajowym"],
  ["Zdobądź złoto mistrzostw regionu"],
  ["Ukończ 1000 startów łącznie", undefined, prog("trasa", 25)],
  ["Zostań numerem 1 rankingu krajowego"],
  ["Zdobądź złoto mistrzostw kraju amatorów w jednej z konkurencji"],
  ["Wygraj klasyfikację generalną sezonu krajowego"],
  ["Zdobądź złoto mistrzostw kraju amatorów w kilku konkurencjach"],
  ["Obroń tytuł mistrza kraju amatorów"],
  ["Zdobądź wielokrotne złoto mistrzostw kraju amatorów"],
  ["Poprowadź kogoś przez zaawansowaną nawigację terenową"],
  ["Zdobądź uznanie w krajowym środowisku biegu na orientację", undefined, prog("nawigacja", 24)],
  ["Poziom mistrzowski (amatorski szczyt): wielokrotny mistrz kraju amatorów", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, Puchar Świata) potwierdzają osobne certyfikaty."],
]);
