// Billiards/pool ladder 1-99. Manual — progression tracks: "run" (consecutive
// balls potted / break-and-run), technique, and competition levels.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "bilard",
  name: "Bilard",
  icon: "🎱",
  description:
    "Od pierwszej wbitej bili po serie break-and-run i turnieje. Progresja: długość serii, technika i poziom rozgrywek.",
  sortOrder: 29,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Ustaw poprawny most dłoni i uderz bilę bez pudła", undefined, prog("technika", 1)],
  ["Wbij bilę do łuzy z bliska", undefined, prog("wbicia", 1)],
  ["Wbij bilę do wskazanej łuzy (zapowiedziana)", undefined, prog("technika", 2)],
  ["Wbij 2 bile pod rząd", undefined, prog("wbicia", 2)],
  ["Kontroluj bilę białą — zatrzymaj ją po uderzeniu (stun)", undefined, prog("technika", 3)],
  ["Wbij 3 bile pod rząd", undefined, prog("wbicia", 3)],
  ["Zagraj z odbiciem od bandy do łuzy", undefined, prog("technika", 4)],
  ["Wbij do łuz 4 bile pod rząd", undefined, prog("wbicia", 4)],
  ["Rozegraj pełną partię 8-ball do końca", undefined, prog("technika", 5)],
  ["Wbij 5 bil pod rząd", undefined, prog("wbicia", 5)],
  // 11-25 · Regularny
  ["Graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Zagraj bilę z podkręceniem (efekt boczny)", undefined, prog("technika", 6)],
  ["Wbij 6 bil pod rząd", undefined, prog("wbicia", 6)],
  ["Wyjdź białą na kolejną bilę (pozycjonowanie)", undefined, prog("technika", 7)],
  ["Wbij 7 bil pod rząd", undefined, prog("wbicia", 7)],
  ["Zagraj skuteczne zagranie obronne (safety)", undefined, prog("technika", 8)],
  ["Wbij 8 bil pod rząd", undefined, prog("wbicia", 8)],
  ["Wygraj pierwszą partię z realnym przeciwnikiem"],
  ["Wbij 9 bil pod rząd", undefined, prog("wbicia", 9)],
  ["Zagraj bilę z zagraniem z przełożeniem (draw/follow) z kontrolą", undefined, prog("technika", 9)],
  ["Wbij 10 bil pod rząd", undefined, prog("wbicia", 10)],
  ["Weź udział w pierwszym turnieju"],
  ["Rozbij i wbij bilę z rozbicia (breakowa łuza)", undefined, prog("technika", 10)],
  ["Wbij do łuz 12 bil pod rząd", undefined, prog("wbicia", 12)],
  ["Wygraj partię 8-ball „z krzesła” (rozbicie do końca)"],
  // 26-45 · Średniozaawansowany
  ["Graj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Wbij 14 bil pod rząd", undefined, prog("wbicia", 14)],
  ["Wykonaj break-and-run w 8-ball (rozbicie i cała partia bez oddania stołu)", undefined, prog("technika", 11)],
  ["Wbij 15 bil pod rząd", undefined, prog("wbicia", 15)],
  ["Zajmij miejsce w pierwszej połowie turnieju amatorskiego"],
  ["Wbij 16 bil pod rząd (pełen zestaw 9-ball ×2)", undefined, prog("wbicia", 16)],
  ["Wykonaj zagranie od bandy (cushion) z dokładnym pozycjonowaniem", undefined, prog("technika", 12)],
  ["Wbij 18 bil pod rząd", undefined, prog("wbicia", 18)],
  ["Wykonaj break-and-run w 9-ball", undefined, prog("technika", 13)],
  ["Wbij 20 bil pod rząd", undefined, prog("wbicia", 20)],
  ["Zagraj skuteczny kombinację (bila-bila-łuza)", undefined, prog("technika", 14)],
  ["Wbij 22 bile pod rząd", undefined, prog("wbicia", 22)],
  ["Zajmij miejsce na podium turnieju amatorskiego"],
  ["Wbij 25 bil pod rząd", undefined, prog("wbicia", 25)],
  ["Wykonaj dwa break-and-runy pod rząd", undefined, prog("technika", 15)],
  ["Wbij 28 bil pod rząd", undefined, prog("wbicia", 28)],
  ["Opanuj zagranie masse (łuk białą) w podstawowej formie", undefined, prog("technika", 16)],
  ["Wbij 30 bil pod rząd", undefined, prog("wbicia", 30)],
  ["Wygraj mecz do 5 partii z zaawansowanym graczem"],
  ["Wbij 35 bil pod rząd", undefined, prog("wbicia", 35)],
  // 46-65 · Zaawansowany
  ["Graj lub trenuj 4+ razy w tygodniu przez sezon"],
  ["Wbij 40 bil pod rząd", undefined, prog("wbicia", 40)],
  ["Wykonaj trzy break-and-runy pod rząd", undefined, prog("technika", 17)],
  ["Wbij 45 bil pod rząd", undefined, prog("wbicia", 45)],
  ["Zajmij miejsce w czołówce turnieju regionalnego"],
  ["Wbij 50 bil pod rząd (serie mistrzowskie)", undefined, prog("wbicia", 50)],
  ["Utrzymaj serię 60 bil w partii prostej (14.1)", undefined, prog("wbicia", 60)],
  ["Wygraj mecz z zawodnikiem ligowym"],
  ["Utrzymaj serię 70 bil (14.1)", undefined, prog("wbicia", 70)],
  ["Wykonaj cztery break-and-runy pod rząd", undefined, prog("technika", 18)],
  ["Utrzymaj serię 80 bil (14.1)", undefined, prog("wbicia", 80)],
  ["Zajmij miejsce na podium turnieju regionalnego"],
  ["Utrzymaj serię 100 bil (14.1)", "Setka w partii prostej — poziom zawodniczy.", prog("wbicia", 100)],
  ["Wygraj turniej regionalny"],
  ["Utrzymaj serię 120 bil (14.1)", undefined, prog("wbicia", 120)],
  ["Wykonaj pięć break-and-runów pod rząd", undefined, prog("technika", 19)],
  ["Utrzymaj serię 140 bil (14.1)", undefined, prog("wbicia", 140)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju"],
  ["Utrzymaj serię 150 bil (14.1)", undefined, prog("wbicia", 150)],
  ["Uzyskaj wynik kwalifikujący do rozgrywek krajowych rangi mistrzowskiej"],
  // 66-85 · Wyczynowy
  ["Utrzymaj serię 175 bil (14.1)", undefined, prog("wbicia", 175)],
  ["Wygraj mecz z czoÅowym zawodnikiem regionu"],
  ["Utrzymaj serię 200 bil (14.1)", undefined, prog("wbicia", 200)],
  ["Wykonaj sześć break-and-runów pod rząd", undefined, prog("technika", 20)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Utrzymaj serię 225 bil (14.1)", undefined, prog("wbicia", 225)],
  ["Wygraj turniej rangi ogólnokrajowej"],
  ["Utrzymaj serię 250 bil (14.1)", undefined, prog("wbicia", 250)],
  ["Zdobądź punkty w rankingu międzynarodowym"],
  ["Utrzymaj serię 275 bil (14.1)", undefined, prog("wbicia", 275)],
  ["Wykonaj osiem break-and-runów pod rząd", undefined, prog("technika", 21)],
  ["Utrzymaj serię 300 bil (14.1)", undefined, prog("wbicia", 300)],
  ["Zajmij miejsce w pierwszej ósemce turnieju międzynarodowego"],
  ["Utrzymaj serię 350 bil (14.1)", undefined, prog("wbicia", 350)],
  ["Wygraj mecz z zawodnikiem światowego rankingu"],
  ["Utrzymaj serię 400 bil (14.1)", undefined, prog("wbicia", 400)],
  ["Wykonaj dziesięć break-and-runów pod rząd", undefined, prog("technika", 22)],
  ["Utrzymaj serię 450 bil (14.1)", undefined, prog("wbicia", 450)],
  ["Zdobądź podium mistrzostw regionu"],
  ["Utrzymaj serię 500 bil (14.1)", undefined, prog("wbicia", 500)],
  // 86-99 · Elita
  ["Weź udział w turnieju o zasięgu ogólnokrajowym"],
  ["Utrzymaj serię 526 bil (14.1)", "Poziom rekordów turniejowych.", prog("wbicia", 526)],
  ["Zajmij miejsce w czołówce turnieju ogólnokrajowego"],
  ["Wykonaj dwanaście break-and-runów pod rząd", undefined, prog("technika", 23)],
  ["Zdobądź podium turnieju o zasięgu ogólnokrajowym"],
  ["Utrzymaj serię 600 bil (14.1)", undefined, prog("wbicia", 600)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju amatorów"],
  ["Wygraj turniej rangi ogólnokrajowej"],
  ["Utrzymaj serię 700 bil (14.1)", undefined, prog("wbicia", 700)],
  ["Zdobądź podium mistrzostw kraju amatorów"],
  ["Utrzymaj serię 526+ w warunkach turniejowych", "Poziom Mosconiego z jego słynnej serii z 1954 roku.", prog("wbicia", 714)],
  ["Poprowadź kogoś przez zaawansowane techniki bilardowe"],
  ["Wygraj mistrzostwa kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat bilardowy", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);
