// Jewellery making ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, piece counts scaled; top tiers reframed as
// attainable mastery, real feats left to future certificates).
// Tracks: umiejetnosci, prace (finished pieces), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "bizuteria",
  name: "Wyrób biżuterii",
  icon: "💍",
  description:
    "Od koralików i drutu po lutowanie metalu i oprawianie kamieni. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → własne kolekcje → dojrzały, autorski warsztat.",
  sortOrder: 90,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Nawlecz i zapnij prosty naszyjnik / bransoletkę", undefined, prog("umiejetnosci", 1)],
  ["Zamontuj zapięcia i bigle (findings)", undefined, prog("umiejetnosci", 2)],
  ["Zrób oczko z drutu (prosta pętelka)", undefined, prog("umiejetnosci", 3)],
  ["Zrób zawinięte oczko (wrapped loop)", undefined, prog("umiejetnosci", 4)],
  ["Zrób kolczyki z koralików i bigli", undefined, prog("prace", 3)],
  ["Dobierz kolory i proporcje kompozycji", undefined, prog("umiejetnosci", 5)],
  ["Zrób bransoletkę z elementami z drutu", undefined, prog("umiejetnosci", 6)],
  ["Pracuj czysto i bezpiecznie przy stole", undefined, prog("umiejetnosci", 7)],
  ["Ukończ 8 wyrobów", undefined, prog("prace", 8)],
  ["Pracuj przy stole jubilerskim łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Twórz biżuterię kilka razy w tygodniu przez 4 tygodnie", undefined, freq(2, 4)],
  ["Opanuj wire wrapping (owijanie drutem)", undefined, prog("umiejetnosci", 8)],
  ["Oprawy kamieni w drut (bez lutowania)", undefined, prog("umiejetnosci", 9)],
  ["Zrób komplet (naszyjnik + kolczyki)", undefined, prog("prace", 18)],
  ["Piłuj i szlifuj blachę metalu", undefined, prog("umiejetnosci", 10)],
  ["Pracuj łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Wiercenie, gięcie i teksturowanie metalu", undefined, prog("umiejetnosci", 11)],
  ["Zrób wisior z blachy (cięcie + wykończenie)", undefined, prog("umiejetnosci", 12)],
  ["Ukończ 30 wyrobów", undefined, prog("prace", 30)],
  ["Polerowanie i wykończenie metalu", undefined, prog("umiejetnosci", 13)],
  ["Zaprojektuj wyrób na papierze przed wykonaniem", undefined, prog("umiejetnosci", 14)],
  ["Pracuj łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Zrób wyrób z kilku łączonych elementów", undefined, prog("prace", 45)],
  ["Opanuj podstawy lutowania (proste złącze)", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 60 wyrobów", undefined, prog("prace", 60)],
  // 26-45 · Średniozaawansowany
  ["Twórz biżuterię regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Lutuj pierścionek (obrączka z łączeniem)", undefined, prog("umiejetnosci", 16)],
  ["Zrób oprawę kamienia (bezel setting)", undefined, prog("umiejetnosci", 17)],
  ["Ukończ 90 wyrobów", undefined, prog("prace", 90)],
  ["Opanuj lutowanie wieloetapowe (kilka złączy)", undefined, prog("umiejetnosci", 18)],
  ["Pracuj łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Zrób pierścionek z oczkiem na kamień", undefined, prog("umiejetnosci", 19)],
  ["Wykonaj łańcuszek z ogniw (ręcznie)", undefined, prog("umiejetnosci", 20)],
  ["Ukończ 130 wyrobów", undefined, prog("prace", 130)],
  ["Wykończ wyrób na poziomie sklepowym (poler, patyna)", undefined, prog("umiejetnosci", 21)],
  ["Zrób złożony wyrób łączący metal i kamienie", undefined, prog("umiejetnosci", 22)],
  ["Pracuj łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Zaprojektuj i wykonaj spójny komplet", undefined, prog("prace", 170)],
  ["Opanuj osadzanie kamieni w łapki (prong setting)", undefined, prog("umiejetnosci", 23)],
  ["Zaprojektuj własny wzór od zera", undefined, prog("umiejetnosci", 24)],
  ["Ukończ 200 wyrobów", undefined, prog("prace", 200)],
  ["Opanuj teksturę i fakturę metalu (walcowanie, młotkowanie)", undefined, prog("umiejetnosci", 25)],
  ["Pracuj łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Zrób wyrób na najwyższym własnym poziomie wykonania", undefined, prog("umiejetnosci", 26)],
  ["Twórz biżuterię regularnie przez 3 miesiące", undefined, prog("prace", 250)],
  // 46-65 · Zaawansowany (amator)
  ["Twórz biżuterię regularnie przez 12 tygodni", undefined, freq(2, 12)],
  ["Zaprojektuj i wykonaj własną kolekcję", undefined, prog("umiejetnosci", 27)],
  ["Zrób spójny zestaw (naszyjnik + kolczyki + pierścionek)", undefined, prog("umiejetnosci", 28)],
  ["Ukończ 300 wyrobów", undefined, prog("prace", 300)],
  ["Pracuj łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Pokaż prace publicznie i zbierz opinie odbiorców"],
  ["Wykonaj ambitny, złożony wyrób", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 380 wyrobów", undefined, prog("prace", 380)],
  ["Opanuj wybraną specjalizację (srebro / kamienie / wire)", undefined, prog("umiejetnosci", 30)],
  ["Pracuj łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj portfolio najlepszych prac"],
  ["Weź udział w wystawie / jarmarku lub sprzedaj wyrób"],
  ["Wykonaj oprawę wymagającego kamienia na wysokim poziomie", undefined, prog("umiejetnosci", 31)],
  ["Ukończ 450 wyrobów", undefined, prog("prace", 450)],
  ["Realizuj wyroby na zamówienie", undefined, prog("umiejetnosci", 32)],
  ["Pracuj łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy wyrobu biżuterii", undefined, prog("umiejetnosci", 33)],
  ["Zrealizuj spójny cykl / kolekcję tematyczną"],
  ["Wykonaj wyrób couture na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 550 wyrobów", undefined, prog("prace", 550)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Twórz biżuterię regularnie przez pełny sezon (6 miesięcy)"],
  ["Projektuj i wykonuj własne wzory swobodnie", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 650 wyrobów", undefined, prog("prace", 650)],
  ["Pracuj łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zrealizuj kolekcję i pokaż ją (lokalnie / online)"],
  ["Rozwiń warsztat na tyle, by uczyć wyrobu biżuterii", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie sprzedajesz wyroby lub realizujesz zamówienia"],
  ["Opanuj każdą podstawową technikę jubilerską na wysokim poziomie", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 800 wyrobów", undefined, prog("prace", 800)],
  ["Zdobądź wyróżnienie lub uznanie w społeczności rękodzieła"],
  ["Pracuj łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny projekt autorski (kolekcja / statement piece)", undefined, prog("umiejetnosci", 38)],
  ["Twoje wyroby są dopracowane w każdym detalu", undefined, prog("umiejetnosci", 39)],
  ["Ukończ 950 wyrobów", undefined, prog("prace", 950)],
  ["Zbuduj grono klientów / odbiorców swojej biżuterii"],
  ["Poprowadź warsztaty lub mentoring dla twórców biżuterii"],
  ["Zaprojektuj spójną, autorską kolekcję"],
  ["Zrealizuj wystawę prezentującą Twój dorobek"],
  ["Ukończ 1100 wyrobów", undefined, prog("prace", 1100)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Pracuj łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdym wyrobie"],
  ["Ukończ 1300 wyrobów", undefined, prog("prace", 1300)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych twórców w Twoim otoczeniu"],
  ["Wykonaj osobisty „opus” — statement piece lub kolekcję życia", undefined, prog("umiejetnosci", 40)],
  ["Regularnie wystawiasz lub sprzedajesz swoją biżuterię"],
  ["Pracuj łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje wyroby zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 1500 wyrobów", undefined, prog("prace", 1500)],
  ["Uczysz i kształtujesz kolejnych twórców biżuterii"],
  ["Masz dorobek, z którego można ułożyć wystawę retrospektywną"],
  ["Wykonasz z metalu i kamieni niemal wszystko, co zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski warsztat", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (wyrób biżuterii: Beadaholique, Jewel School i in.).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Nawlekanie i montaż zapięcia", url: yt("HskY5RUhQAo") }],
  3: [{ kind: "video", title: "Proste oczko z drutu (simple loop)", url: yt("X4p3nD8zyKY") }],
  4: [{ kind: "video", title: "Zawinięte oczko (wrapped loop)", url: yt("ETL-dbncs68") }],
  12: [{ kind: "video", title: "Wire wrapping — podstawy", url: yt("qbQiwEbqvxM") }],
  13: [{ kind: "video", title: "Oprawa kamienia w drut (bez lutu)", url: yt("KacRlVxcKFM") }],
  15: [{ kind: "video", title: "Piłowanie blachy (jubilerska piłka)", url: yt("8kBpYOSRtos") }],
  20: [{ kind: "video", title: "Polerowanie i wykończenie metalu", url: yt("Bg7ry6etrPs") }],
  24: [{ kind: "video", title: "Lutowanie — podstawy", url: yt("Q_gejiVEClE") }],
  27: [{ kind: "video", title: "Lutowanie obrączki (ring band)", url: yt("qZw-feh7T-E") }],
  28: [{ kind: "video", title: "Oprawa kamienia (bezel setting)", url: yt("quE9WlldEMw") }],
};
