// Boxing ladder 1-99. Manual — progression tracks: technique, sparring/bouts,
// and competition level (amateur → national → international → pro/Olympic).
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "boks",
  name: "Boks",
  icon: "🥊",
  description:
    "Szlachetna sztuka samoobrony — cios, praca nóg i obrona. Progresja: technika, walki i poziom rywalizacji (amator → zawodowiec).",
  sortOrder: 67,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj postawę bokserską i gardę", undefined, prog("technika", 1)],
  ["Wyprowadź poprawny jab i prosty (cross)", undefined, prog("technika", 2)],
  ["Wykonaj podstawową pracę nóg (footwork)", undefined, prog("technika", 3)],
  ["Wyprowadź hak (hook) i podbródkowy (uppercut)", undefined, prog("technika", 4)],
  ["Wykonaj uniki (slip) i zbicia ciosów", undefined, prog("technika", 5)],
  ["Ćwicz na worku 3 rundy z techniką", undefined, prog("technika", 6)],
  ["Wykonaj serię kombinacji na łapach", undefined, prog("technika", 7)],
  ["Odbądź pierwszy lekki sparing", undefined, prog("walki", 1)],
  ["Ćwicz na tarczach zachowując gardę i oddech", undefined, prog("technika", 8)],
  ["Odbądź 3 sparingi", undefined, prog("walki", 3)],
  // 11-25 · Regularny
  ["Trenuj 3 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Opanuj kontrę po uniku (counter-punching)", undefined, prog("technika", 9)],
  ["Odbądź 6 sparingów", undefined, prog("walki", 6)],
  ["Wykonaj skuteczny clinch i wyjście z niego", undefined, prog("technika", 10)],
  ["Odbądź pierwszą walkę amatorską (licencja)", undefined, prog("liga", 1)],
  ["Odbądź 10 sparingów", undefined, prog("walki", 10)],
  ["Kontroluj dystans (in-and-out) przez rundę", undefined, prog("technika", 11)],
  ["Wygraj pierwszą walkę amatorską"],
  ["Odbądź 15 walk/sparingów", undefined, prog("walki", 15)],
  ["Opanuj pracę na dwóch dystansach (long i infighting)", undefined, prog("technika", 12)],
  ["Stocz 5 walk amatorskich", undefined, prog("walki", 20)],
  ["Zajmij miejsce w pierwszej połowie turnieju amatorskiego"],
  ["Wygraj walkę przed czasem (RSC/KO)", undefined, prog("technika", 13)],
  ["Stocz 10 walk amatorskich", undefined, prog("walki", 30)],
  ["Odczytuj styl przeciwnika i dostosuj taktykę", undefined, prog("technika", 14)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 4-5 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(4, 12)],
  ["Stocz 15 walk amatorskich", undefined, prog("walki", 45)],
  ["Opanuj feinty i pułapki (setting traps)", undefined, prog("technika", 15)],
  ["Zajmij miejsce na podium turnieju amatorskiego"],
  ["Stocz 20 walk amatorskich", undefined, prog("walki", 60)],
  ["Wygraj mecz międzyklubowy jako reprezentant klubu", undefined, prog("liga", 2)],
  ["Utrzymaj wysokie tempo i technikę przez pełne 3 rundy", undefined, prog("technika", 16)],
  ["Stocz 30 walk amatorskich", undefined, prog("walki", 80)],
  ["Zajmij miejsce w czołówce mistrzostw okręgu"],
  ["Opanuj obronę na linach i counter z narożnika", undefined, prog("technika", 17)],
  ["Stocz 40 walk amatorskich", undefined, prog("walki", 100)],
  ["Zdobądź minimum na mistrzostwa kraju amatorów", undefined, prog("liga", 3)],
  ["Wygraj walkę z zawodnikiem z rankingu okręgowego"],
  ["Stocz 50 walk amatorskich", undefined, prog("walki", 130)],
  ["Utrzymaj skuteczność w walce z leworęcznym (southpaw)", undefined, prog("technika", 18)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju"],
  ["Stocz 60 walk amatorskich", undefined, prog("walki", 160)],
  ["Zdobądź medal mistrzostw kraju juniorów/młodzieżowców"],
  ["Wygraj walkę z mocnym zawodnikiem okręgowym"],
  ["Stocz 75 walk amatorskich", undefined, prog("walki", 200)],
  // 46-65 · Zaawansowany
  ["Trenuj na wysokim poziomie klubowym przez cały sezon"],
  ["Opanuj pełen repertuar ciosów i kombinacji na mistrzowskim poziomie", undefined, prog("technika", 19)],
  ["Zajmij miejsce w czołówce mistrzostw kraju seniorów"],
  ["Stocz 90 walk amatorskich", undefined, prog("walki", 250)],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Wygraj walkę z czołowym zawodnikiem regionu"],
  ["Stocz 110 walk amatorskich", undefined, prog("walki", 300)],
  ["Zdobądź czołową pozycję w rankingu regionalnym", undefined, prog("liga", 4)],
  ["Utrzymaj psychiczną odporność w walce mistrzowskiej", undefined, prog("technika", 20)],
  ["Stocz 130 walk amatorskich", undefined, prog("walki", 350)],
  ["Wystartuj w międzynarodowym turnieju amatorskim"],
  ["Zdobądź medal na turnieju międzynarodowym"],
  ["Stocz 150 walk amatorskich", undefined, prog("walki", 400)],
  ["Zostań mistrzem kraju amatorów seniorów"],
  ["Wygraj walkę z uznanym zawodnikiem krajowym"],
  ["Stocz 170 walk amatorskich", undefined, prog("walki", 450)],
  ["Weź udział w mistrzostwach kraju amatorów wyższej rangi"],
  ["Zostań uznanym, doświadczonym zawodnikiem klubowym", undefined, prog("liga", 5)],
  ["Wygraj walkę na prestiżowym turnieju amatorskim", undefined, prog("walki", 470)],
  ["Stocz 5 kolejnych walk amatorskich bez porażki", undefined, prog("walki", 490)],
  // 66-85 · Wyczynowy
  ["Zdobądź medal mistrzostw regionu amatorów"],
  ["Stocz 10 walk klubowych/turniejowych", undefined, prog("walki", 520)],
  ["Wygraj walkę przed czasem na zawodach amatorskich", undefined, prog("technika", 21)],
  ["Zbuduj solidny bilans zwycięstw na zawodach amatorskich"],
  ["Stocz 15 walk klubowych/turniejowych", undefined, prog("walki", 560)],
  ["Zdobądź tytuł mistrzostw regionu w swojej kategorii wagowej"],
  ["Wygraj walkę z uznanym zawodnikiem regionalnym"],
  ["Stocz 20 walk klubowych/turniejowych", undefined, prog("walki", 600)],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Osiągnij czołową 15 rankingu krajowego amatorów", undefined, prog("liga", 6)],
  ["Stocz 25 walk klubowych/turniejowych", undefined, prog("walki", 650)],
  ["Zdobądź tytuł mistrzostw kraju amatorów w swojej kategorii"],
  ["Utrzymaj dobrą formę na pełnym dystansie walki amatorskiej", undefined, prog("technika", 22)],
  ["Wygraj walkę z doświadczonym zawodnikiem klubowym"],
  ["Stocz 30 walk klubowych/turniejowych", undefined, prog("walki", 700)],
  ["Osiągnij czołową piątkę rankingu krajowego amatorów"],
  ["Zdobądź podium mistrzostw kraju amatorów"],
  ["Poprowadź kogoś przez podstawy boksu"],
  ["Zdobądź uznanie w krajowym środowisku bokserskim"],
  ["Stocz 35 walk klubowych/turniejowych bez poważnej porażki", undefined, prog("walki", 750)],
  // 86-99 · Elita
  ["Zdobądź tytuł mistrza kraju amatorów", "Pas/tytuł mistrzowski amatorski."],
  ["Obroń tytuł mistrza kraju amatorów"],
  ["Utrzymaj uznaną pozycję w kilku sezonach z rzędu"],
  ["Stocz 40 walk klubowych/turniejowych", undefined, prog("walki", 800)],
  ["Wygraj walkę z uznanym, doświadczonym rywalem krajowym"],
  ["Zdobądź status najlepszego zawodnika swojej kategorii wagowej w kraju"],
  ["Obroń tytuł wielokrotnie (3+ obrony tytułu)"],
  ["Zdobądź tytuł w drugiej kategorii wagowej"],
  ["Stocz 45 walk klubowych/turniejowych", undefined, prog("walki", 850)],
  ["Poprowadź własny klub / grupę treningową przez dłuższy czas"],
  ["Weź udział w prestiżowym turnieju amatorskim o szerokim zasięgu"],
  ["Zakończ karierę amatorską z wybitnym bilansem", undefined, prog("technika", 23)],
  ["Zdobądź najwyższe krajowe uznanie w swojej kategorii wagowej"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat bokserski", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, igrzyska) potwierdzają osobne certyfikaty."],
]);
