// CrossFit ladder 1-99. Manual — progression tracks: benchmark lifts, gymnastic
// skills (pull-ups → muscle-up → handstand walk), Fran time, and competition.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "crossfit",
  name: "CrossFit",
  icon: "🏋️",
  description:
    "Wszechstronny trening: podnoszenie, gimnastyka i cardio. Progresja: siła, umiejętności gimnastyczne, benchmarki (Fran) i poziom zawodów.",
  sortOrder: 63,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj air squat i technikę przysiadu", undefined, prog("technika", 1)],
  ["Wykonaj 10 pompek pod rząd", undefined, prog("gimnastyka", 10)],
  ["Ukończ pierwsze WOD skalowane (scaled)", undefined, prog("wod", 1)],
  ["Opanuj kettlebell swing i wallball", undefined, prog("technika", 2)],
  ["Wykonaj 5 podciągnięć z gumą lub 1 bez", undefined, prog("gimnastyka", 15)],
  ["Martwy ciąg 60 kg z techniką", undefined, prog("sila", 60)],
  ["Ukończ benchmark WOD (np. Cindy skalowane)", undefined, prog("wod", 2)],
  ["Opanuj podstawy olympic lifts (power clean, push press)", undefined, prog("technika", 3)],
  ["Wykonaj 3 podciągnięcia bez gumy", undefined, prog("gimnastyka", 20)],
  ["Ukończ Fran (skalowane) w dowolnym czasie", undefined, prog("wod", 3)],
  // 11-25 · Regularny
  ["Trenuj 3 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Wykonaj 10 podciągnięć pod rząd (strict lub kipping)", undefined, prog("gimnastyka", 30)],
  ["Martwy ciąg 100 kg", undefined, prog("sila", 100)],
  ["Wykonaj pierwszego double-under (podwójny skok skakanki)", undefined, prog("technika", 4)],
  ["Ukończ Fran RX poniżej 8:00", undefined, prog("fran", 480)],
  ["Wykonaj 20 double-unders pod rząd", undefined, prog("technika", 5)],
  ["Back squat 100 kg", undefined, prog("sila", 110)],
  ["Wykonaj pierwszy ring muscle-up lub bar muscle-up", "Kamień milowy gimnastyki CrossFit.", prog("gimnastyka", 40)],
  ["Ukończ „Murph” (skalowane lub RX z kamizelką lub bez)", undefined, prog("wod", 4)],
  ["Clean & jerk 60 kg z techniką", undefined, prog("sila", 120)],
  ["Wykonaj handstand push-up (przy ścianie)", undefined, prog("gimnastyka", 50)],
  ["Ukończ Fran RX poniżej 6:00", undefined, prog("fran", 360)],
  ["Wykonaj 50 double-unders pod rząd", undefined, prog("technika", 6)],
  ["Deadlift 140 kg", undefined, prog("sila", 140)],
  ["Wykonaj 5 muscle-upów pod rząd", undefined, prog("gimnastyka", 60)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 4-5 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(4, 12)],
  ["Back squat 130 kg", undefined, prog("sila", 150)],
  ["Wykonaj handstand walk 5 m", undefined, prog("gimnastyka", 70)],
  ["Ukończ Fran RX poniżej 5:00", undefined, prog("fran", 300)],
  ["Snatch 60 kg z techniką", undefined, prog("sila", 160)],
  ["Wykonaj 10 muscle-upów pod rząd", undefined, prog("gimnastyka", 80)],
  ["Zajmij miejsce w pierwszej połowie lokalnych zawodów (scaled/RX)"],
  ["Clean & jerk 90 kg", undefined, prog("sila", 170)],
  ["Wykonaj 100 double-unders pod rząd", undefined, prog("technika", 7)],
  ["Ukończ „Grace” (30 C&J 60 kg) poniżej 3:00", undefined, prog("wod", 5)],
  ["Deadlift 180 kg", undefined, prog("sila", 180)],
  ["Wykonaj handstand walk 15 m", undefined, prog("gimnastyka", 90)],
  ["Ukończ Fran RX poniżej 4:00", undefined, prog("fran", 240)],
  ["Snatch 80 kg", undefined, prog("sila", 190)],
  ["Wykonaj strict muscle-up (bez zamachu)", undefined, prog("gimnastyka", 100)],
  ["Back squat 160 kg", undefined, prog("sila", 200)],
  ["Zajmij miejsce na podium lokalnych zawodów RX"],
  ["Clean & jerk 110 kg", undefined, prog("sila", 210)],
  ["Wykonaj 20 muscle-upów pod rząd", undefined, prog("gimnastyka", 120)],
  ["Ukończ Fran RX poniżej 3:30", undefined, prog("fran", 210)],
  // 46-65 · Zaawansowany
  ["Trenuj jak zawodnik (2 sesje dziennie) przez sezon"],
  ["Snatch 100 kg", "Setka w rwaniu.", prog("sila", 220)],
  ["Deadlift 220 kg", undefined, prog("sila", 230)],
  ["Wykonaj handstand walk 30 m", undefined, prog("gimnastyka", 140)],
  ["Ukończ Fran RX poniżej 3:00", "Sub-3 Fran — poziom zawodniczy.", prog("fran", 180)],
  ["Clean & jerk 130 kg", undefined, prog("sila", 240)],
  ["Wykonaj 30 muscle-upów pod rząd", undefined, prog("gimnastyka", 160)],
  ["Back squat 180 kg", undefined, prog("sila", 250)],
  ["Zajmij miejsce w czołówce regionalnych zawodów RX"],
  ["Snatch 110 kg", undefined, prog("sila", 260)],
  ["Wykonaj legless rope climb lub inny zaawansowany element", undefined, prog("gimnastyka", 180)],
  ["Ukończ Fran RX poniżej 2:45", undefined, prog("fran", 165)],
  ["Deadlift 250 kg", undefined, prog("sila", 270)],
  ["Wykonaj pistolet + handstand + muscle-up w jednym WOD bez przerw", undefined, prog("gimnastyka", 200)],
  ["Zakwalifikuj się do Quarterfinals CrossFit (top % Open)"],
  ["Clean & jerk 150 kg", undefined, prog("sila", 280)],
  ["Ukończ Fran RX poniżej 2:30", undefined, prog("fran", 150)],
  ["Snatch 120 kg", undefined, prog("sila", 290)],
  ["Wykonaj strict handstand push-up ×10", undefined, prog("gimnastyka", 220)],
  ["Back squat 200 kg", "Dwieście w przysiadzie.", prog("sila", 300)],
  // 66-85 · Wyczynowy
  ["Ukończ Fran RX poniżej 2:20", undefined, prog("fran", 140)],
  ["Clean & jerk 160 kg", undefined, prog("sila", 320)],
  ["Zajmij wysokie miejsce w CrossFit Open (top 5% świata)"],
  ["Snatch 130 kg", undefined, prog("sila", 340)],
  ["Wykonaj 50 muscle-upów pod rząd", undefined, prog("gimnastyka", 250)],
  ["Ukończ Fran RX poniżej 2:10", undefined, prog("fran", 130)],
  ["Deadlift 280 kg", undefined, prog("sila", 360)],
  ["Awansuj do Quarterfinals i utrzymaj miejsce w top 1000 świata"],
  ["Clean & jerk 170 kg", undefined, prog("sila", 380)],
  ["Wykonaj handstand walk 50 m bez przerwy", undefined, prog("gimnastyka", 280)],
  ["Ukończ Fran RX poniżej 2:00", "Sub-2 Fran — elita.", prog("fran", 120)],
  ["Snatch 140 kg", undefined, prog("sila", 400)],
  ["Weź udział w zawodach o zasięgu ogólnokrajowym"],
  ["Deadlift 300 kg", undefined, prog("sila", 420)],
  ["Wykonaj każdy standardowy element gimnastyczny na bardzo wysokim poziomie", undefined, prog("gimnastyka", 320)],
  ["Clean & jerk 180 kg", undefined, prog("sila", 440)],
  ["Zajmij miejsce w pierwszej połowie zawodów o zasięgu ogólnokrajowym"],
  ["Ukończ Fran RX poniżej 1:55", undefined, prog("fran", 115)],
  ["Snatch 150 kg", undefined, prog("sila", 460)],
  ["Weź udział w mistrzostwach kraju amatorów (indywidualnie lub drużynowo)"],
  // 86-99 · Elita
  ["Ukończ WOD zawodów o zasięgu ogólnokrajowym w regulaminowym limicie"],
  ["Clean & jerk 190 kg", undefined, prog("sila", 480)],
  ["Ukończ Fran RX poniżej 1:50", undefined, prog("fran", 110)],
  ["Snatch 160 kg", undefined, prog("sila", 500)],
  ["Zajmij miejsce w pierwszej połowie mistrzostw kraju amatorów"],
  ["Wygraj event na zawodach o zasięgu ogólnokrajowym"],
  ["Ukończ Fran RX poniżej 1:45", undefined, prog("fran", 105)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju amatorów"],
  ["Wykonaj rekordowy dla siebie wynik w kluczowym benchmarku", undefined, prog("gimnastyka", 360)],
  ["Zajmij miejsce na podium eventu mistrzostw kraju amatorów"],
  ["Zajmij miejsce w pierwszej piątce klasyfikacji generalnej kraju amatorów"],
  ["Ukończ Fran RX poniżej 1:40", "Bardzo rzadki, wieloletnio wypracowany wynik.", prog("fran", 100)],
  ["Stań na podium mistrzostw kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat crossfitowy", "Dalsze, zawodowe osiągnięcia (CrossFit Games) potwierdzają osobne certyfikaty."],
]);

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  // — Rozszerzenie zasobów Tier 1 (wszystkie linki zweryfikowane jako aktywne) —
  2: [{ kind: "video", title: "Standard air squat na zawodach — kiedy powtórzenie się liczy", url: yt("8Cj6is9gEx0") }],
  4: [{ kind: "video", title: "Push press i push jerk — technika wyciskania nad głowę", url: yt("WGPcHNICvAQ") }],
  7: [{ kind: "article", title: "Jak zbudowany jest typowy trening CrossFit (WOD) — rozbiór krok po kroku", url: "https://fitbod.me/blog/typical-crossfit-workout/" }],
  8: [{ kind: "article", title: "Słownik CrossFit: AMRAP, EMOM, WOD, RX — oficjalne wyjaśnienie pojęć", url: "https://www.crossfit.com/essentials/crossfit-terms-explained" }],
  12: [{ kind: "video", title: "Zarzut (clean) dla początkujących — przewodnik po technice", url: yt("8sTXxyK501Q") }],
  15: [{ kind: "article", title: "Rwanie (snatch) od zera — progresja dla początkujących", url: "https://wodprep.com/blog/ultimate-snatch-beginner-progressions/" }],
  25: [{ kind: "video", title: "Butterfly pull-up — progresja krok po kroku", url: yt("6ji4A5WCuBo") }],
  30: [{ kind: "video", title: "Ring muscle-up — szybki poradnik techniki", url: yt("kcOrpyWW77A") }],
  40: [{ kind: "article", title: "Przewodnik po CrossFit Open 2026 — zasady, terminy, kwalifikacje", url: "https://www.theprogrm.com/blog/2026-crossfit-open-all-you-need-to-know" }],
  55: [{ kind: "article", title: "Jak układać program pod zawody CrossFit", url: "https://www.conquerathlete.com/blog/best-way-to-program-for-crossfit-competitions" }],
  65: [{ kind: "article", title: "Periodyzacja sezonu w CrossFit — makrocykl, mezocykl, mikrocykl", url: "https://wodprep.com/blog/plan-crossfit-season-periodization/" }],
  1: [
    { kind: "video", title: "The Air Squat — CrossFit", url: yt("C_VtOYc6j5c") },
    { kind: "article", title: "CrossFit beginner guide", url: "https://www.verywellfit.com/crossfit-training-guide-3498289" },
  ],
  3: [
    { kind: "video", title: "Your First WOD: How to Scale — WODprep", url: yt("VLlvx2RaDSo") },
  ],
  5: [
    { kind: "video", title: "Kipping Pull-Up Progression — WODprep", url: yt("GwMnpxJxIG0") },
  ],
  10: [
    { kind: "video", title: "Fran — Tips & Strategy — WODprep", url: yt("9Z9e1VfFkvA") },
  ],
  14: [
    { kind: "video", title: "Learn Double-Unders — WODprep", url: yt("hCuXYrTORxo") },
  ],
  18: [
    { kind: "video", title: "Your First Bar Muscle-Up — WODprep", url: yt("1eeE_auIPBg") },
    { kind: "article", title: "Muscle-up progression guide", url: "https://www.barbend.com/muscle-up-progression/" },
  ],
  28: [
    { kind: "video", title: "Handstand Walk Progressions — CrossFit", url: yt("oBSandHijDc") },
  ],
  35: [
    { kind: "video", title: "Grace WOD Strategy — WODprep", url: yt("_vqHHnDjMmQ") },
  ],
  49: [
    { kind: "article", title: "Sub-3 Fran: how to get there", url: "https://www.barbend.com/crossfit-fran-workout/" },
  ],
  79: [
    { kind: "reference", title: "CrossFit Open Leaderboard", url: "https://games.crossfit.com/leaderboard" },
  ],
};
