// Curling ladder 1-99. Manual — progression tracks: technique/shot skill,
// matches played, and competition level.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";
const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "curling",
  name: "Curling",
  icon: "🥌",
  description:
    "Szachy na lodzie — od pierwszego wyrzutu kamienia po turnieje. Progresja: technika zagrań, rozegrane mecze i poziom rozgrywek.",
  sortOrder: 46,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Utrzymaj równowagę podczas ślizgu z kamieniem curlingowym (podstawowa pozycja)", undefined, prog("technika", 1)],
  ["Wypuść kamień tak, by dojechał do domu (house)", undefined, prog("technika", 2)],
  ["Opanuj poprawne szczotkowanie (sweeping)", undefined, prog("technika", 3)],
  ["Nadaj kamieniowi rotację (in-turn / out-turn)", undefined, prog("technika", 4)],
  ["Ustaw kamień w domu (draw) choć raz", undefined, prog("technika", 5)],
  ["Wykonaj wybicie kamienia przeciwnika (takeout)", undefined, prog("technika", 6)],
  ["Zrozum liczenie punktów i ustawienie końcowe (end)", undefined, prog("technika", 7)],
  ["Zagraj pierwszy mecz treningowy", undefined, prog("mecze", 1)],
  ["Zdobądź pierwszy punkt w meczu"],
  ["Rozegraj pełny mecz (6-8 endów)", undefined, prog("mecze", 2)],
  // 11-25 · Regularny
  ["Graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Ustaw draw dokładnie na button (środek domu)", undefined, prog("technika", 8)],
  ["Zagraj 5 meczów", undefined, prog("mecze", 5)],
  ["Wykonaj guard (kamień blokujący) w wyznaczonym miejscu", undefined, prog("technika", 9)],
  ["Skomunikuj się jako zespół przy szczotkowaniu (kontrola tempa)", undefined, prog("technika", 10)],
  ["Zagraj 10 meczów", undefined, prog("mecze", 10)],
  ["Wykonaj double takeout (wybicie dwóch kamieni)", undefined, prog("technika", 11)],
  ["Zagraj na pozycji skipa przez cały mecz"],
  ["Rozegraj mecz w lidze klubowej", undefined, prog("liga", 1)],
  ["Zagraj 20 meczów", undefined, prog("mecze", 20)],
  ["Wykonaj freeze (dostawienie kamienia idealnie do innego)", undefined, prog("technika", 12)],
  ["Utrzymaj celność zagrań 60%+ w meczu", undefined, prog("celnosc", 60)],
  ["Zagraj come-around (obejście guarda draw'em)", undefined, prog("technika", 13)],
  ["Zagraj 30 meczów", undefined, prog("mecze", 30)],
  ["Wygraj pierwszy end z kradzieżą (steal — punkt bez młota)"],
  // 26-45 · Średniozaawansowany
  ["Graj 2 razy w tygodniu przez cały sezon (12 tyg.)", undefined, freq(2, 12)],
  ["Utrzymaj celność zagrań 65%+ w meczu", undefined, prog("celnosc", 65)],
  ["Zagraj 50 meczów", undefined, prog("mecze", 50)],
  ["Wykonaj hit and roll (wybicie z odbiciem w pozycję)", undefined, prog("technika", 14)],
  ["Rozegraj pełny sezon w lidze klubowej", undefined, prog("liga", 2)],
  ["Wykonaj raise (podbicie własnego kamienia do domu)", undefined, prog("technika", 15)],
  ["Zajmij miejsce w pierwszej połowie turnieju (bonspiel)"],
  ["Zagraj 75 meczów", undefined, prog("mecze", 75)],
  ["Utrzymaj celność zagrań 70%+", undefined, prog("celnosc", 70)],
  ["Opanuj strategię ustawiania końcówki (ostatni kamień)", undefined, prog("technika", 16)],
  ["Zagraj 100 meczów", undefined, prog("mecze", 100)],
  ["Weź udział w turnieju rangi regionalnej", undefined, prog("liga", 3)],
  ["Wygraj mecz turniejowy"],
  ["Wykonaj tick shot (delikatne przesunięcie guarda)", undefined, prog("technika", 17)],
  ["Zagraj 150 meczów", undefined, prog("mecze", 150)],
  ["Utrzymaj celność zagrań 75%+", undefined, prog("celnosc", 75)],
  ["Zajmij miejsce na podium turnieju amatorskiego"],
  ["Poprowadź zespół jako skip w turnieju", undefined, prog("technika", 18)],
  ["Zagraj 200 meczów", undefined, prog("mecze", 200)],
  ["Utrzymaj celność zagrań 78%+", undefined, prog("celnosc", 78)],
  // 46-65 · Zaawansowany
  ["Graj lub trenuj 3+ razy w tygodniu przez sezon"],
  ["Zagraj 250 meczów", undefined, prog("mecze", 250)],
  ["Zajmij miejsce w czołówce turnieju regionalnego"],
  ["Wykonaj precyzyjny double takeout pod presją", undefined, prog("technika", 19)],
  ["Utrzymaj celność zagrań 80%+", undefined, prog("celnosc", 80)],
  ["Wygraj turniej regionalny"],
  ["Zagraj w rozgrywkach ligi krajowej", undefined, prog("liga", 4)],
  ["Zagraj 300 meczów", undefined, prog("mecze", 300)],
  ["Utrzymaj celność zagrań 82%+", undefined, prog("celnosc", 82)],
  ["Wykonaj triple takeout w meczu", undefined, prog("technika", 20)],
  ["Zagraj 350 meczów", undefined, prog("mecze", 350)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju"],
  ["Utrzymaj celność zagrań 84%+", undefined, prog("celnosc", 84)],
  ["Poprowadź zespół do finału turnieju krajowego"],
  ["Zagraj 400 meczów", undefined, prog("mecze", 400)],
  ["Utrzymaj celność zagrań 85%+", undefined, prog("celnosc", 85)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Opanuj pełen repertuar zagrań strategicznych jako skip", undefined, prog("technika", 21)],
  ["Zagraj 500 meczów", undefined, prog("mecze", 500)],
  ["Uzyskaj wynik kwalifikujący do rozgrywek międzynarodowych"],
  // 66-85 · Wyczynowy
  ["Utrzymaj celność zagrań 86%+", undefined, prog("celnosc", 86)],
  ["Zagraj 600 meczów", undefined, prog("mecze", 600)],
  ["Zostań mistrzem kraju"],
  ["Utrzymaj celność zagrań 87%+", undefined, prog("celnosc", 87)],
  ["Wystartuj w turnieju rangi międzynarodowej (WCT)"],
  ["Zagraj 700 meczów", undefined, prog("mecze", 700)],
  ["Utrzymaj celność zagrań 88%+", undefined, prog("celnosc", 88)],
  ["Wygraj mecz z drużyną z rankingu światowego"],
  ["Zagraj 800 meczów", undefined, prog("mecze", 800)],
  ["Zdobądź punkty w rankingu World Curling Tour"],
  ["Utrzymaj celność zagrań 89%+", undefined, prog("celnosc", 89)],
  ["Zajmij miejsce w pierwszej ósemce turnieju międzynarodowego"],
  ["Zagraj 900 meczów", undefined, prog("mecze", 900)],
  ["Reprezentuj kraj w mistrzostwach Europy"],
  ["Utrzymaj celność zagrań 90%+", "Poziom światowej czołówki.", prog("celnosc", 90)],
  ["Wygraj turniej World Curling Tour niższej rangi"],
  ["Zagraj 1000 meczów", undefined, prog("mecze", 1000)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw regionu"],
  ["Utrzymaj celność zagrań 91%+", undefined, prog("celnosc", 91)],
  ["Zdobądź medal mistrzostw regionu"],
  // 86-99 · Elita
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Utrzymaj celność zagrań 92%+", undefined, prog("celnosc", 92)],
  ["Wygraj duży turniej klubowy rangi krajowej"],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju amatorów"],
  ["Utrzymaj celność zagrań 93%+", undefined, prog("celnosc", 93)],
  ["Zdobądź medal mistrzostw kraju amatorów"],
  ["Wygraj prestiżowy turniej klubowy o szerokim zasięgu"],
  ["Utrzymaj celność zagrań 94%+", undefined, prog("celnosc", 94)],
  ["Poprowadź kogoś przez zaawansowaną strategię curlingu"],
  ["Zajmij miejsce w finale mistrzostw kraju amatorów"],
  ["Zdobądź złoto mistrzostw kraju amatorów"],
  ["Utrzymaj celność zagrań 95%+", "Mistrzowska precyzja.", prog("celnosc", 95)],
  ["Zdobądź wielokrotne medale mistrzostw kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat curlingowy", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, igrzyska) potwierdzają osobne certyfikaty."],
]);

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [
    { kind: "video", title: "Learn to Curl — Curling Canada", url: yt("AH0yGUpz5aY") },
    { kind: "article", title: "How to Curl: beginner guide", url: "https://www.wikihow.com/Curl-(Sport)" },
  ],
  3: [
    { kind: "video", title: "How to Sweep in Curling — Curling Canada", url: yt("YRJWGXKYQOI") },
  ],
  5: [
    { kind: "video", title: "Delivery Technique & Slide — Curling Canada", url: yt("Mj_o6Y9RF3A") },
    { kind: "article", title: "Curling rules & scoring explained", url: "https://www.worldcurling.org/about/rules/" },
  ],
  8: [
    { kind: "video", title: "Takeout Shot Tutorial — Curling Canada", url: yt("bPpiqJrn7WQ") },
  ],
  14: [
    { kind: "video", title: "Guard Strategy in Curling — Curling Canada", url: yt("R5yE2I-Y-F0") },
  ],
  22: [
    { kind: "video", title: "The Freeze Shot Explained — Curling Canada", url: yt("aPm0qGzQapw") },
    { kind: "article", title: "Curling Strategy Guide for Intermediate Players", url: "https://www.topendsports.com/sport/curling/strategy.htm" },
  ],
  35: [
    { kind: "video", title: "Skip Strategy & Communication — Curling Canada", url: yt("N2c5Vi8yQfk") },
  ],
  50: [
    { kind: "video", title: "Advanced Shot Making — Hit & Roll", url: yt("T__3TFfkF0w") },
    { kind: "article", title: "Curling shot accuracy & percentage tracking", url: "https://www.curling.ca/about-curling/getting-started-in-curling/" },
  ],
  70: [
    { kind: "video", title: "World Curling Championship Highlights", url: yt("5z1FhGYRves") },
  ],
  85: [
    { kind: "video", title: "Olympic Curling Gold Medal Moments", url: yt("UkB5bwUpbsE") },
  ],
};
