// Darts ladder 1-99. Manual — progression tracks: 3-dart average, highest
// checkout (finish, max 170), and competition levels. Benchmarks: casual avg
// ~40-50; club 60-70; strong amateur 80+; pro 95-100+; elite 105+.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "dart",
  name: "Dart",
  icon: "🎯",
  description:
    "Rzutki (501) — od pierwszej punktacji po średnie zawodowe 100+ i finisze z wysokich checkoutów. Progresja: średnia z 3 lotek, checkout i poziom rozgrywek.",
  sortOrder: 31,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Trafij w tarczę (dartboard) wszystkimi trzema rzutkami", undefined, prog("technika", 1)],
  ["Trafij w wybrany sektor (np. 20) choć raz na 3 rzutki", undefined, prog("technika", 2)],
  ["Zbij pełną partię 501 do zera (dowolna liczba rund)", undefined, prog("technika", 3)],
  ["Uzyskaj średnią 30 na 3 rzutki", undefined, prog("srednia", 30)],
  ["Trafij pierwsze pole podwójne (double)", undefined, prog("technika", 4)],
  ["Uzyskaj średnią 40 na 3 rzutki", undefined, prog("srednia", 40)],
  ["Zbij checkout (zakończ 501 rzutem w double)", undefined, prog("checkout", 2)],
  ["Trafij pierwszy triple (potrójne pole)", undefined, prog("technika", 5)],
  ["Uzyskaj średnią 45 na 3 rzutki", undefined, prog("srednia", 45)],
  ["Zbij 100 punktów w jednej rundzie (3 lotki)", undefined, prog("technika", 6)],
  // 11-25 · Regularny
  ["Graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Uzyskaj średnią 50 na 3 rzutki", undefined, prog("srednia", 50)],
  ["Zbij checkout z 40 punktów (podwójne 20)", undefined, prog("checkout", 40)],
  ["Zbij 120 punktów w jednej rundzie", undefined, prog("technika", 7)],
  ["Uzyskaj średnią 55 na 3 rzutki", undefined, prog("srednia", 55)],
  ["Trafij trzy razy w to samo pole podwójne z rzędu", undefined, prog("technika", 8)],
  ["Uzyskaj średnią 60 na 3 rzutki", "Poziom pewnego gracza pubowego.", prog("srednia", 60)],
  ["Zbij checkout z 60 punktów", undefined, prog("checkout", 60)],
  ["Weź udział w pierwszym turnieju lub lidze"],
  ["Zbij 140 punktów w jednej rundzie", undefined, prog("technika", 9)],
  ["Uzyskaj średnią 65 na 3 rzutki", undefined, prog("srednia", 65)],
  ["Zbij checkout z 80 punktów", undefined, prog("checkout", 80)],
  ["Trafij pierwsze 180 (trzy triple 20 — maksimum!)", "Święty Graal początkującego.", prog("technika", 10)],
  ["Uzyskaj średnią 70 na 3 rzutki", undefined, prog("srednia", 70)],
  ["Zbij checkout z 100 punktów", undefined, prog("checkout", 100)],
  // 26-45 · Średniozaawansowany
  ["Graj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Uzyskaj średnią 72 na 3 rzutki", undefined, prog("srednia", 72)],
  ["Zbij checkout z 110 punktów", undefined, prog("checkout", 110)],
  ["Uzyskaj średnią 74 na 3 rzutki", undefined, prog("srednia", 74)],
  ["Zbij dwa razy 180 w jednym meczu", undefined, prog("technika", 11)],
  ["Uzyskaj średnią 76 na 3 rzutki", undefined, prog("srednia", 76)],
  ["Zajmij miejsce w pierwszej połowie turnieju"],
  ["Uzyskaj średnią 78 na 3 rzutki", undefined, prog("srednia", 78)],
  ["Zbij checkout z 120 punktów", undefined, prog("checkout", 120)],
  ["Uzyskaj średnią 80 na 3 rzutki", "Poziom silnego amatora.", prog("srednia", 80)],
  ["Wygraj mecz w formacie legów (najlepszy z 5)", undefined, prog("technika", 12)],
  ["Uzyskaj średnią 82 na 3 rzutki", undefined, prog("srednia", 82)],
  ["Zbij checkout z 130 punktów", undefined, prog("checkout", 130)],
  ["Uzyskaj średnią 84 na 3 rzutki", undefined, prog("srednia", 84)],
  ["Zajmij miejsce na podium turnieju amatorskiego"],
  ["Uzyskaj średnią 85 na 3 rzutki", undefined, prog("srednia", 85)],
  ["Zbij checkout z 140 punktów", undefined, prog("checkout", 140)],
  ["Zbij 9-strzałowego lega na treningu (najkrótsze możliwe 501)", undefined, prog("technika", 13)],
  ["Uzyskaj średnią 86 na 3 rzutki", undefined, prog("srednia", 86)],
  // 46-65 · Zaawansowany
  ["Graj lub trenuj 4+ razy w tygodniu przez sezon"],
  ["Uzyskaj średnią 88 na 3 rzutki", undefined, prog("srednia", 88)],
  ["Zbij checkout z 150 punktów", undefined, prog("checkout", 150)],
  ["Uzyskaj średnią 89 na 3 rzutki", undefined, prog("srednia", 89)],
  ["Zajmij miejsce w czołówce turnieju regionalnego"],
  ["Uzyskaj średnią 90 na 3 rzutki", "Poziom półprofesjonalny.", prog("srednia", 90)],
  ["Zbij checkout z 160 punktów", undefined, prog("checkout", 160)],
  ["Uzyskaj średnią 91 na 3 rzutki", undefined, prog("srednia", 91)],
  ["Zbij checkout z 161 punktów (T20-T17-D25)", undefined, prog("checkout", 161)],
  ["Uzyskaj średnią 92 na 3 rzutki", undefined, prog("srednia", 92)],
  ["Zbij największy możliwy checkout — 170 (T20-T20-D25)", "Big Fish!", prog("checkout", 170)],
  ["Uzyskaj średnią 93 na 3 rzutki", undefined, prog("srednia", 93)],
  ["Wygraj turniej regionalny"],
  ["Uzyskaj średnią 94 na 3 rzutki", undefined, prog("srednia", 94)],
  ["Zbij trzy 180 w jednym meczu", undefined, prog("technika", 14)],
  ["Uzyskaj średnią 95 na 3 rzutki", "Poziom rankingowego zawodnika.", prog("srednia", 95)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju"],
  ["Uzyskaj średnią 96 na 3 rzutki", undefined, prog("srednia", 96)],
  ["Zbij lega w 12 lotkach lub mniej w meczu", undefined, prog("technika", 15)],
  ["Uzyskaj średnią 97 na 3 rzutki", undefined, prog("srednia", 97)],
  // 66-85 · Wyczynowy
  ["Zdobądź kartę turniejową (Tour Card) lub odpowiednik krajowy"],
  ["Wygraj mecz w formacie „best of 11 legów” w turnieju rangi krajowej"],
  ["Uzyskaj średnią 98 na 3 rzutki", undefined, prog("srednia", 98)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Uzyskaj średnią 99 na 3 rzutki", undefined, prog("srednia", 99)],
  ["Zbij pięć 180 w jednym meczu", undefined, prog("technika", 16)],
  ["Uzyskaj średnią 100 na 3 rzutki", "Setka średniej — bardzo wysoki, wieloletnio wypracowany poziom.", prog("srednia", 100)],
  ["Wygraj turniej rangi ogólnokrajowej"],
  ["Uzyskaj średnią 101 na 3 rzutki", undefined, prog("srednia", 101)],
  ["Zdobądź punkty w rankingu międzynarodowym (PDC Order of Merit)"],
  ["Uzyskaj średnią 102 na 3 rzutki", undefined, prog("srednia", 102)],
  ["Zbij lega dziewięciolotkowego w meczu turniejowym", "Perfekcyjny leg.", prog("technika", 17)],
  ["Uzyskaj średnią 103 na 3 rzutki", undefined, prog("srednia", 103)],
  ["Zajmij miejsce w pierwszej ósemce turnieju międzynarodowego"],
  ["Uzyskaj średnią 104 na 3 rzutki", undefined, prog("srednia", 104)],
  ["Zbij siedem 180 w jednym meczu", undefined, prog("technika", 18)],
  ["Uzyskaj średnią 105 na 3 rzutki", "Poziom światowej czołówki.", prog("srednia", 105)],
  ["Wygraj mecz z mocnym zawodnikiem regionalnym"],
  ["Uzyskaj średnią 106 na 3 rzutki", undefined, prog("srednia", 106)],
  ["Awansuj do finału turnieju o zasięgu ogólnokrajowym"],
  ["Uzyskaj średnią 107 na 3 rzutki", undefined, prog("srednia", 107)],
  // 86-99 · Elita
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Uzyskaj średnią 108 na 3 rzutki", undefined, prog("srednia", 108)],
  ["Zajmij miejsce w czołówce mistrzostw kraju amatorów"],
  ["Uzyskaj średnią 109 na 3 rzutki", undefined, prog("srednia", 109)],
  ["Zdobądź tytuł turnieju rangi ogólnokrajowej"],
  ["Uzyskaj średnią 110 na 3 rzutki", undefined, prog("srednia", 110)],
  ["Awansuj do ćwierćfinału mistrzostw kraju amatorów"],
  ["Uzyskaj średnią 111 na 3 rzutki", undefined, prog("srednia", 111)],
  ["Zbij dziesięć 180 w jednym meczu", undefined, prog("technika", 19)],
  ["Uzyskaj średnią 112 na 3 rzutki", "Wynik z rekordowych meczów amatorskich.", prog("srednia", 112)],
  ["Awansuj do finału mistrzostw kraju amatorów"],
  ["Zdobądź uznanie w krajowym środowisku darta"],
  ["Wygraj mistrzostwa kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): średnia meczowa 112+ i wieloletni, dojrzały warsztat", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

import type { MilestoneResource } from "../../src/lib/milestone-resources";
const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "How to throw darts — grip and stance", url: yt("WUaYClVqEEk") }],
  5: [{ kind: "video", title: "How to hit doubles", url: yt("yTXaGIKOcfg") }],
  8: [{ kind: "article", title: "Understanding the dartboard scoring", url: "https://www.wikihow.com/Play-Darts" }],
  13: [{ kind: "article", title: "Checkout charts explained", url: "https://www.dartsnutz.net/checkouts" }],
  23: [{ kind: "video", title: "How to throw 180", url: yt("7aRiAMpq6mM") }],
  30: [{ kind: "video", title: "Two 180s technique", url: yt("4UlAS_KRWWE") }],
  35: [{ kind: "video", title: "Improving your average", url: yt("fKmxvJ9FRME") }],
  42: [{ kind: "video", title: "9-dart finish explained", url: yt("Q39_D8SGRA4") }],
  55: [{ kind: "video", title: "Mental game in darts", url: yt("dOsVoXvJpms") }],
  75: [{ kind: "video", title: "170 checkout tutorial", url: yt("JUjMMVe2kMo") }],
};
