// Knitting ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, project counts scaled for a slow craft; top
// tiers reframed as attainable mastery, real feats left to future certificates).
// Tracks: umiejetnosci, projekty (finished pieces), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "dzianie",
  name: "Dzianie na drutach",
  icon: "🧶",
  description:
    "Od pierwszych oczek po swetry, warkocze i koronki. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → własne projekty → dojrzały, autorski warsztat.",
  sortOrder: 86,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Nabierz oczka na drut (cast on)", undefined, prog("umiejetnosci", 1)],
  ["Zrób ścieg prawy (garter stitch)", undefined, prog("umiejetnosci", 2)],
  ["Zrób ścieg lewy i gładki (stockinette)", undefined, prog("umiejetnosci", 3)],
  ["Zamknij oczka (bind off) równo", undefined, prog("umiejetnosci", 4)],
  ["Zrób ściągacz (rib 1x1 / 2x2)", undefined, prog("umiejetnosci", 5)],
  ["Utrzymaj równe napięcie nici", undefined, prog("umiejetnosci", 6)],
  ["Zrób prosty projekt (szalik / opaska)", undefined, prog("projekty", 2)],
  ["Rozczytaj prosty wzór / schemat", undefined, prog("umiejetnosci", 7)],
  ["Ukończ 4 projekty", undefined, prog("projekty", 4)],
  ["Dziergaj łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Dziergaj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(2, 4)],
  ["Naucz się przybierać i ubierać oczka (kształtowanie)", undefined, prog("umiejetnosci", 8)],
  ["Zrób czapkę na drutach okrągłych / DPN", undefined, prog("umiejetnosci", 9)],
  ["Zrób dzierganie w okręgu (magic loop)", undefined, prog("umiejetnosci", 10)],
  ["Ukończ 8 projektów", undefined, prog("projekty", 8)],
  ["Dziergaj łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Naprawiaj błędy (spuszczone oczko, pruć i podnosić)", undefined, prog("umiejetnosci", 11)],
  ["Zrób rękawiczki / skarpety (pięta)", undefined, prog("umiejetnosci", 12)],
  ["Ukończ 14 projektów", undefined, prog("projekty", 14)],
  ["Zrób prosty warkocz (cable)", undefined, prog("umiejetnosci", 13)],
  ["Dobierz włóczkę i druty do próbki (gauge swatch)", undefined, prog("umiejetnosci", 14)],
  ["Dziergaj łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Zrób projekt z kilku części i zszyj go", undefined, prog("projekty", 22)],
  ["Zrób prosty żakard / colourwork (2 kolory)", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 30 projektów", undefined, prog("projekty", 30)],
  // 26-45 · Średniozaawansowany
  ["Dziergaj regularnie przez 8 kolejnych tygodni", undefined, freq(2, 8)],
  ["Zrób sweter od podstaw (top-down lub od dołu)", undefined, prog("umiejetnosci", 16)],
  ["Opanuj warkocze złożone (cable panels)", undefined, prog("umiejetnosci", 17)],
  ["Ukończ 40 projektów", undefined, prog("projekty", 40)],
  ["Opanuj ażury / koronki (lace, yarn overs)", undefined, prog("umiejetnosci", 18)],
  ["Dziergaj łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Zrób żakard wielokolorowy (fair isle)", undefined, prog("umiejetnosci", 19)],
  ["Dopasuj rozmiar wzoru do własnych wymiarów", undefined, prog("umiejetnosci", 20)],
  ["Ukończ 55 projektów", undefined, prog("projekty", 55)],
  ["Wykończ pracę profesjonalnie (blokowanie, zszywanie)", undefined, prog("umiejetnosci", 21)],
  ["Zrób skomplikowany sweter z warkoczami", undefined, prog("umiejetnosci", 22)],
  ["Dziergaj łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Zrób dużą pracę (koc / duży sweter)", undefined, prog("projekty", 70)],
  ["Opanuj brioche lub intarsję", undefined, prog("umiejetnosci", 23)],
  ["Zaprojektuj drobną modyfikację wzoru", undefined, prog("umiejetnosci", 24)],
  ["Ukończ 85 projektów", undefined, prog("projekty", 85)],
  ["Opanuj steek (przecinanie dzianiny)", undefined, prog("umiejetnosci", 25)],
  ["Dziergaj łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Zrób pracę łączącą kilka technik (warkocze + ażur + kolor)", undefined, prog("umiejetnosci", 26)],
  ["Prowadź projekty regularnie przez 3 miesiące", undefined, prog("projekty", 100)],
  // 46-65 · Zaawansowany (amator)
  ["Dziergaj regularnie przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zaprojektuj własny prosty wzór od zera", undefined, prog("umiejetnosci", 27)],
  ["Zrób spójny zestaw (np. sweter + czapka + rękawice)", undefined, prog("umiejetnosci", 28)],
  ["Ukończ 120 projektów", undefined, prog("projekty", 120)],
  ["Dziergaj łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Pokaż prace publicznie i zbierz opinie odbiorców"],
  ["Zaprojektuj sweter z pełnym rozpisaniem rozmiarów", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 150 projektów", undefined, prog("projekty", 150)],
  ["Opanuj wybraną specjalizację (koronki / żakard / skarpety)", undefined, prog("umiejetnosci", 30)],
  ["Dziergaj łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj portfolio najlepszych prac"],
  ["Weź udział w wystawie / konkursie robótek lub sprzedaj pracę"],
  ["Zaprojektuj skomplikowany wzór ażurowy", undefined, prog("umiejetnosci", 31)],
  ["Ukończ 180 projektów", undefined, prog("projekty", 180)],
  ["Sprzedaj pracę / zrealizuj zamówienie", undefined, prog("umiejetnosci", 32)],
  ["Dziergaj łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy dziergania", undefined, prog("umiejetnosci", 33)],
  ["Zrealizuj spójny cykl prac wokół jednego pomysłu"],
  ["Zrób wymagający projekt na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 220 projektów", undefined, prog("projekty", 220)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Dziergaj regularnie przez pełny sezon (6 miesięcy)"],
  ["Projektuj swobodnie własne wzory (sweter, akcesoria)", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 270 projektów", undefined, prog("projekty", 270)],
  ["Dziergaj łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Opublikuj własny wzór (za darmo lub na sprzedaż)"],
  ["Rozwiń warsztat na tyle, by uczyć dziergania", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie sprzedajesz prace lub wzory"],
  ["Opanuj każdą technikę dziewiarską na wysokim poziomie", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 330 projektów", undefined, prog("projekty", 330)],
  ["Zdobądź wyróżnienie lub uznanie w społeczności rękodzieła"],
  ["Dziergaj łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny, wieloczęściowy projekt autorski", undefined, prog("umiejetnosci", 38)],
  ["Twoje prace są dojrzałe i dopracowane w każdym detalu", undefined, prog("umiejetnosci", 39)],
  ["Ukończ 400 projektów", undefined, prog("projekty", 400)],
  ["Zbuduj grono odbiorców swoich prac / wzorów"],
  ["Poprowadź warsztaty lub mentoring dla dziergających"],
  ["Zaprojektuj kolekcję spójnych wzorów"],
  ["Zrealizuj wystawę lub publikację prezentującą dorobek"],
  ["Ukończ 480 projektów", undefined, prog("projekty", 480)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Dziergaj łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdej pracy"],
  ["Ukończ 560 projektów", undefined, prog("projekty", 560)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych dziergających w Twoim otoczeniu"],
  ["Zrealizuj osobisty „opus” — dużą, dopracowaną pracę lub kolekcję", undefined, prog("umiejetnosci", 40)],
  ["Regularnie publikujesz wzory lub wystawiasz prace"],
  ["Dziergaj łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje prace zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 650 projektów", undefined, prog("projekty", 650)],
  ["Uczysz i kształtujesz kolejnych dziergających"],
  ["Masz dorobek, z którego można ułożyć wystawę retrospektywną"],
  ["Zrobisz na drutach niemal wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski warsztat", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (dzianie na drutach: Sheep & Stitch, Nimble Needles i in.).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Nabieranie oczek (long tail cast on)", url: yt("ZjmNuqqfFx0") }],
  2: [{ kind: "video", title: "Ścieg prawy (garter stitch)", url: yt("u9yuXROish0") }],
  3: [{ kind: "video", title: "Ścieg lewy i gładki (stockinette)", url: yt("0uUZMB7oFvg") }],
  4: [{ kind: "video", title: "Zamykanie oczek (bind off)", url: yt("VSwjIUiQZlM") }],
  5: [{ kind: "video", title: "Ściągacz 1x1 i 2x2 (rib)", url: yt("dCJj3pW2nRY") }],
  12: [{ kind: "video", title: "Przybieranie i ubieranie oczek", url: yt("lWuNtu-hvX0") }],
  13: [{ kind: "video", title: "Czapka na drutach DPN", url: yt("mKIyi0WJaXc") }],
  14: [{ kind: "video", title: "Dzierganie w okręgu (magic loop)", url: yt("MLMCgtufyFE") }],
  17: [{ kind: "video", title: "Naprawa spuszczonego oczka", url: yt("qoRnZ-18hgs") }],
  18: [{ kind: "video", title: "Pięta skarpety (turning the heel)", url: yt("MnkhAeOREho") }],
  20: [{ kind: "video", title: "Warkocz (cable) dla początkujących", url: yt("4XEvjxvbZxo") }],
  24: [{ kind: "video", title: "Żakard / colourwork (2 kolory)", url: yt("P19RAfu-Cs4") }],
};
