// Photography ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, keeper counts scaled for a high-volume craft;
// top tiers reframed as attainable mastery, real feats left to future certs).
// Tracks: umiejetnosci, zdjecia (keeper/portfolio shots), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "fotografia",
  name: "Fotografia",
  icon: "📷",
  description:
    "Od trybu auto po pełną kontrolę światła i kompozycji. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → portfolio i wystawy → dojrzały, autorski styl.",
  sortOrder: 93,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Zrozum trójkąt ekspozycji (przysłona, czas, ISO)", undefined, prog("umiejetnosci", 1)],
  ["Ustaw ostrość ręcznie i przez punkty AF", undefined, prog("umiejetnosci", 2)],
  ["Zrób poprawnie naświetlone zdjęcie w trybie manualnym", undefined, prog("umiejetnosci", 3)],
  ["Steruj głębią ostrości (rozmyte tło / wszystko ostre)", undefined, prog("umiejetnosci", 4)],
  ["Zamroź ruch i pokaż ruch (czas migawki)", undefined, prog("umiejetnosci", 5)],
  ["Zastosuj regułę trójpodziału w kadrze", undefined, prog("umiejetnosci", 6)],
  ["Ustaw balans bieli i fotografuj w RAW", undefined, prog("umiejetnosci", 7)],
  ["Zbierz 10 udanych, przemyślanych zdjęć", undefined, prog("zdjecia", 10)],
  ["Zbierz 25 udanych zdjęć", undefined, prog("zdjecia", 25)],
  ["Fotografuj łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Fotografuj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Opanuj kompozycję: linie prowadzące, kadrowanie, symetria", undefined, prog("umiejetnosci", 8)],
  ["Zrób portret z ładnym tłem i światłem", undefined, prog("zdjecia", 50)],
  ["Fotografuj w złotej godzinie i wykorzystaj miękkie światło", undefined, prog("umiejetnosci", 9)],
  ["Opanuj podstawy obróbki (ekspozycja, kontrast, kadr, kolor)", undefined, prog("umiejetnosci", 10)],
  ["Fotografuj łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Zrób zdjęcie krajobrazu z pierwszym planem i głębią", undefined, prog("umiejetnosci", 11)],
  ["Zbierz 100 udanych zdjęć", undefined, prog("zdjecia", 100)],
  ["Fotografuj w trudnym świetle (kontra, noc, wnętrze)", undefined, prog("umiejetnosci", 12)],
  ["Opanuj panoramowanie i długi czas naświetlania", undefined, prog("umiejetnosci", 13)],
  ["Wywołaj zdjęcie w spójnym, autorskim tonie", undefined, prog("umiejetnosci", 14)],
  ["Fotografuj łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Zrób reportaż / serię z wydarzenia (fotografia uliczna/eventowa)", undefined, prog("umiejetnosci", 15)],
  ["Zbierz 200 udanych zdjęć", undefined, prog("zdjecia", 200)],
  ["Opanuj światło sztuczne (lampa błyskowa / softbox — podstawy)", undefined, prog("umiejetnosci", 16)],
  // 26-45 · Średniozaawansowany
  ["Fotografuj regularnie przez 8 kolejnych tygodni", undefined, freq(3, 8)],
  ["Opanuj studio i modelowanie światła (schematy oświetlenia)", undefined, prog("umiejetnosci", 17)],
  ["Zrób sesję portretową z reżyserią modela", undefined, prog("umiejetnosci", 18)],
  ["Zbierz 300 udanych zdjęć", undefined, prog("zdjecia", 300)],
  ["Opanuj zaawansowaną obróbkę (dodge & burn, retusz, color grading)", undefined, prog("umiejetnosci", 19)],
  ["Fotografuj łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Zbuduj spójną serię tematyczną (projekt fotograficzny)", undefined, prog("umiejetnosci", 20)],
  ["Opanuj wybrany gatunek na wysokim poziomie (makro, sport, moda)", undefined, prog("umiejetnosci", 21)],
  ["Zrób zdjęcie produktowe / martwą naturę z kontrolą światła", undefined, prog("umiejetnosci", 22)],
  ["Fotografuj z technikami HDR / focus stacking", undefined, prog("umiejetnosci", 23)],
  ["Zbierz 450 udanych zdjęć", undefined, prog("zdjecia", 450)],
  ["Zbuduj spójny, rozpoznawalny styl fotograficzny", undefined, prog("umiejetnosci", 24)],
  ["Fotografuj łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Wydrukuj i skalibruj zdjęcia (workflow do druku)", undefined, prog("umiejetnosci", 25)],
  ["Zbierz 600 udanych zdjęć", undefined, prog("zdjecia", 600)],
  ["Opanuj storytelling w serii zdjęć (fotoesej)", undefined, prog("umiejetnosci", 26)],
  ["Fotografuj łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Zrealizuj pełną sesję (produkt / portret / event) na poziomie portfolio", undefined, prog("umiejetnosci", 27)],
  ["Zbierz 800 udanych zdjęć portfolio", undefined, prog("zdjecia", 800)],
  ["Fotografuj regularnie przez 3 miesiące", undefined, prog("zdjecia", 1000)],
  // 46-65 · Zaawansowany (amator)
  ["Fotografuj regularnie przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Opanuj drugi wymagający gatunek na wysokim poziomie", undefined, prog("umiejetnosci", 28)],
  ["Zbuduj profesjonalne portfolio (kilkanaście najlepszych prac)", undefined, prog("umiejetnosci", 29)],
  ["Zbierz 1300 udanych zdjęć", undefined, prog("zdjecia", 1300)],
  ["Fotografuj łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Publikuj i buduj obserwujących / portfolio online"],
  ["Opanuj oświetlenie w każdych warunkach (natura + studio + mieszane)", undefined, prog("umiejetnosci", 30)],
  ["Zbierz 1700 udanych zdjęć", undefined, prog("zdjecia", 1700)],
  ["Opanuj mistrzowski color grading i retusz", undefined, prog("umiejetnosci", 31)],
  ["Fotografuj łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj portfolio pod klienta / na wystawę"],
  ["Wygraj lub wyróżnij się w konkursie fotograficznym"],
  ["Opublikuj zdjęcia w magazynie / na wystawie zbiorowej", undefined, prog("umiejetnosci", 32)],
  ["Zbierz 2200 udanych zdjęć", undefined, prog("zdjecia", 2200)],
  ["Sprzedaj pierwsze zdjęcie lub zdobądź płatne zlecenie", undefined, prog("umiejetnosci", 33)],
  ["Fotografuj łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy fotografii"],
  ["Zrealizuj sesję na zamówienie na wysokim poziomie"],
  ["Zrób zdjęcie / serię na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Zbierz 2800 udanych zdjęć", undefined, prog("zdjecia", 2800)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Fotografuj regularnie przez pełny sezon (6 miesięcy)"],
  ["Fotografuj swobodnie w każdym świetle i gatunku", undefined, prog("umiejetnosci", 35)],
  ["Zbierz 3400 udanych zdjęć", undefined, prog("zdjecia", 3400)],
  ["Fotografuj łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zorganizuj małą wystawę indywidualną (lokalnie / online)"],
  ["Rozwiń warsztat na tyle, by uczyć fotografii", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie realizujesz płatne zlecenia fotograficzne"],
  ["Opanuj każdy gatunek na wysokim, publikowalnym poziomie", undefined, prog("umiejetnosci", 37)],
  ["Zbierz 4000 udanych zdjęć", undefined, prog("zdjecia", 4000)],
  ["Zdobądź wyróżnienie w konkursie lub uznanie w społeczności"],
  ["Fotografuj łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny projekt autorski (album / cykl)", undefined, prog("umiejetnosci", 38)],
  ["Twoje zdjęcia są dojrzałe i rozpoznawalne", undefined, prog("umiejetnosci", 39)],
  ["Zbierz 4800 udanych zdjęć", undefined, prog("zdjecia", 4800)],
  ["Zbuduj grono odbiorców swojej twórczości"],
  ["Poprowadź warsztaty lub mentoring dla fotografów"],
  ["Wydaj album lub zrób dużą wystawę"],
  ["Zrealizuj publikację prezentującą dorobek"],
  ["Zbierz 5600 udanych zdjęć", undefined, prog("zdjecia", 5600)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Fotografuj łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdej sesji"],
  ["Zbierz 6500 udanych zdjęć", undefined, prog("zdjecia", 6500)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych fotografów w Twoim otoczeniu"],
  ["Zrealizuj osobisty „opus” — album lub duży cykl fotograficzny", undefined, prog("umiejetnosci", 40)],
  ["Regularnie wystawiasz lub publikujesz swoje zdjęcia"],
  ["Fotografuj łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje zdjęcia zdobywają uznanie poza lokalną społecznością"],
  ["Zbierz 7500 udanych zdjęć", undefined, prog("zdjecia", 7500)],
  ["Uczysz i kształtujesz kolejnych fotografów"],
  ["Masz dorobek, z którego można ułożyć wystawę retrospektywną"],
  ["Sfotografujesz niemal wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski styl", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones. Filmy z Adobe, Adorama, NatureTTL i in.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  // — Rozszerzenie zasobów Tier 1 (wszystkie linki zweryfikowane jako aktywne) —
  5: [{ kind: "article", title: "Jak zamrozić ruch — czas migawki w praktyce", url: "https://expertphotography.com/freeze-motion-photography" }],
  8: [{ kind: "video", title: "Ćwicz oko — jak nauczyć się widzieć jak fotograf", url: yt("gGngRlWHmZw") }],
  10: [{ kind: "video", title: "Pierwszy sprzęt fotograficzny dla początkujących", url: yt("St9MidwHc9I") }],
  11: [{ kind: "video", title: "5 nawyków, które zmieniły moją fotografię", url: yt("-Vhg1mSA1jU") }],
  12: [{ kind: "article", title: "Zaawansowana kompozycja — 28 technik kadrowania", url: "https://petapixel.com/photography-composition-techniques/" }],
  13: [{ kind: "video", title: "Portret z jedną lampą — podstawy dla początkujących", url: yt("vgXbYeiHhH4") }],
  16: [{ kind: "video", title: "Lightroom — pełny workflow obróbki od początku do końca", url: yt("mPvJkhnB4xg") }],
  18: [{ kind: "video", title: "Jak wybrać najlepsze zdjęcia — sztuka selekcji", url: yt("YlSa8VfljsM") }],
  19: [{ kind: "video", title: "Fotografia nocna — ustawienia i wskazówki", url: yt("X5vogaSCmuk") }],
  20: [{ kind: "video", title: "Długa ekspozycja z filtrami ND — prosto wyjaśnione", url: yt("YTVJeAukxG0") }],
  22: [{ kind: "video", title: "Teoria koloru, którą powinien znać każdy fotograf", url: yt("muXeSghtLwE") }],
  23: [{ kind: "article", title: "Reportaż i fotografia dokumentalna — poradnik", url: "https://www.diyphotography.net/documentary-wedding-photography-101-a-guide-for-photographers/" }],
  24: [{ kind: "video", title: "Jak wypracować i rozwinąć własny styl fotograficzny", url: yt("85MgVZH2pGI") }],
  26: [{ kind: "video", title: "Lampa poza aparatem — praktyczny poradnik", url: yt("RZwYSaWoW3Y") }],
  1: [{ kind: "video", title: "Trójkąt ekspozycji", url: yt("eNohTJh-ugI") }],
  2: [{ kind: "video", title: "Tryby autofokusa", url: yt("WMuoFK5elmc") }],
  3: [{ kind: "video", title: "Tryb manualny — jak zacząć", url: yt("uyXiWF3mI2s") }],
  4: [{ kind: "video", title: "Przysłona i głębia ostrości", url: yt("EdxKl5np9KE") }],
  6: [{ kind: "video", title: "Reguła trójpodziału", url: yt("I1OK3yeuO_s") }],
  7: [{ kind: "video", title: "Balans bieli i RAW", url: yt("6NAYm-VegZ0") }],
  14: [{ kind: "video", title: "Złota godzina — portrety", url: yt("2ykY4mDDCVQ") }],
  15: [{ kind: "video", title: "Lightroom — podstawy obróbki", url: yt("bN2jqsJgbBs") }],
  17: [{ kind: "video", title: "Pejzaż — pierwszy plan i głębia", url: yt("2W7FSJQyNZ0") }],
  25: [{ kind: "video", title: "Lampa reporterska — podstawy", url: yt("cGtyrBoDpsc") }],
  27: [{ kind: "video", title: "Studio: 1 lampa, 5 ustawień", url: yt("bWy5uHLuQDk") }],
  30: [{ kind: "video", title: "Dodge & burn + color grading", url: yt("_3oQSeXO-9w") }],
};
