// American football ladder 1-99. Manual — progression tracks: matches played,
// touchdowns/big plays (total), and competition level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "futbol-amerykanski",
  name: "Futbol amerykański",
  icon: "🏈",
  description:
    "Kontakt, taktyka i eksplozywność — od pierwszego podania po ligowe boiska. Progresja: rozegrane mecze, przyłożenia/akcje i poziom rozgrywek.",
  sortOrder: 52,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Złap podanie w biegu (catch)", undefined, prog("technika", 1)],
  ["Rzuć spiralę na 10 m", undefined, prog("technika", 2)],
  ["Przyjmij poprawną postawę i ruszaj z linii (stance & start)", undefined, prog("technika", 3)],
  ["Wykonaj poprawny blok", undefined, prog("technika", 4)],
  ["Wykonaj tackle na tarczy (technika obalenia)", undefined, prog("technika", 5)],
  ["Biegnij wyznaczoną trasę (route) i złap piłkę", undefined, prog("technika", 6)],
  ["Zrozum formacje i podstawowe zagrania (playbook basics)", undefined, prog("technika", 7)],
  ["Zagraj pierwszy mecz treningowy (flag lub kontakt)", undefined, prog("mecze", 1)],
  ["Zalicz pierwszą znaczącą akcję (przyłożenie, przechwyt, worek)", undefined, prog("akcje", 1)],
  ["Rozegraj pełny mecz (4 kwarty lub skrócony)", undefined, prog("mecze", 2)],
  // 11-25 · Regularny
  ["Trenuj lub graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Wykonaj skuteczny tackle w meczu", undefined, prog("technika", 8)],
  ["Zagraj 5 meczów", undefined, prog("mecze", 5)],
  ["Zalicz 3 znaczące akcje łącznie", undefined, prog("akcje", 3)],
  ["Opanuj grę na wyznaczonej pozycji (atak lub obrona)", undefined, prog("technika", 9)],
  ["Zagraj cały mecz na jednej pozycji"],
  ["Zagraj 10 meczów", undefined, prog("mecze", 10)],
  ["Zalicz 6 znaczących akcji łącznie", undefined, prog("akcje", 6)],
  ["Wykonaj kluczowy blok otwierający bieg", undefined, prog("technika", 10)],
  ["Rozegraj mecz w lidze amatorskiej", undefined, prog("liga", 1)],
  ["Zagraj 20 meczów", undefined, prog("mecze", 20)],
  ["Zalicz 12 znaczących akcji łącznie", undefined, prog("akcje", 12)],
  ["Zalicz przyłożenie w meczu", undefined, prog("technika", 11)],
  ["Zalicz 2 znaczące akcje w jednym meczu", undefined, prog("akcje-mecz", 2)],
  ["Zagraj 30 meczów", undefined, prog("mecze", 30)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zalicz 20 znaczących akcji łącznie", undefined, prog("akcje", 20)],
  ["Czytaj grę przeciwnika i reaguj (pre-snap read)", undefined, prog("technika", 12)],
  ["Zagraj 50 meczów", undefined, prog("mecze", 50)],
  ["Zalicz 30 znaczących akcji łącznie", undefined, prog("akcje", 30)],
  ["Rozegraj pełny sezon w regularnej lidze", undefined, prog("liga", 2)],
  ["Zalicz 3 znaczące akcje w jednym meczu", undefined, prog("akcje-mecz", 3)],
  ["Opanuj zaawansowaną technikę pozycji (release, coverage lub pass rush)", undefined, prog("technika", 13)],
  ["Zagraj 75 meczów", undefined, prog("mecze", 75)],
  ["Zalicz 45 znaczących akcji łącznie", undefined, prog("akcje", 45)],
  ["Zajmij miejsce w pierwszej połowie tabeli ligowej"],
  ["Zostań liderem statystyk zespołu na swojej pozycji", undefined, prog("technika", 14)],
  ["Zagraj 100 meczów", undefined, prog("mecze", 100)],
  ["Zalicz 65 znaczących akcji łącznie", undefined, prog("akcje", 65)],
  ["Rozegraj mecz w II lidze lub odpowiedniku", undefined, prog("liga", 3)],
  ["Wygraj mecz play-off"],
  ["Zalicz 90 znaczących akcji łącznie", undefined, prog("akcje", 90)],
  ["Zagraj 150 meczów", undefined, prog("mecze", 150)],
  ["Poprowadź zespół jako kapitan formacji", undefined, prog("technika", 15)],
  ["Zalicz 4 znaczące akcje w jednym meczu", undefined, prog("akcje-mecz", 4)],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Zalicz 120 znaczących akcji łącznie", undefined, prog("akcje", 120)],
  ["Rozegraj mecz w I lidze", undefined, prog("liga", 4)],
  ["Zagraj 200 meczów", undefined, prog("mecze", 200)],
  ["Zalicz 150 znaczących akcji łącznie", undefined, prog("akcje", 150)],
  ["Zostań podstawowym zawodnikiem zespołu I-ligowego"],
  ["Zalicz 5 znaczących akcji w jednym meczu", undefined, prog("akcje-mecz", 5)],
  ["Zagraj 250 meczów", undefined, prog("mecze", 250)],
  ["Zalicz 190 znaczących akcji łącznie", undefined, prog("akcje", 190)],
  ["Zajmij miejsce w czołówce I ligi"],
  ["Rozegraj mecz w najwyższej lidze krajowej (Topliga)", undefined, prog("liga", 5)],
  ["Zalicz 230 znaczących akcji łącznie", undefined, prog("akcje", 230)],
  ["Zagraj 300 meczów", undefined, prog("mecze", 300)],
  ["Zalicz znaczącą akcję w meczu najwyższej ligi"],
  ["Zalicz 270 znaczących akcji łącznie", undefined, prog("akcje", 270)],
  ["Zostań podstawowym zawodnikiem najwyższej ligi"],
  ["Zagraj 400 meczów", undefined, prog("mecze", 400)],
  ["Zalicz 310 znaczących akcji łącznie", undefined, prog("akcje", 310)],
  ["Zostań najlepszym zawodnikiem rundy na swojej pozycji"],
  ["Zostań uznanym zawodnikiem swojej ligi regionalnej"],
  // 66-85 · Wyczynowy
  ["Zalicz 350 znaczących akcji łącznie", undefined, prog("akcje", 350)],
  ["Zagraj 500 meczów", undefined, prog("mecze", 500)],
  ["Zostań filarem drużyny najwyższej ligi"],
  ["Zalicz 390 znaczących akcji łącznie", undefined, prog("akcje", 390)],
  ["Zdobądź mistrzostwo kraju (finał — Superfinał/Polbowl)"],
  ["Zagraj 600 meczów", undefined, prog("mecze", 600)],
  ["Zalicz 430 znaczących akcji łącznie", undefined, prog("akcje", 430)],
  ["Zagraj w rozgrywkach o zasięgu ogólnokrajowym"],
  ["Zalicz 470 znaczących akcji łącznie", undefined, prog("akcje", 470)],
  ["Zagraj 700 meczów", undefined, prog("mecze", 700)],
  ["Zalicz znaczącą akcję w ważnym meczu ligowym"],
  ["Zalicz 510 znaczących akcji łącznie", undefined, prog("akcje", 510)],
  ["Zagraj w europejskiej lidze klubowej (ELF)"],
  ["Zalicz 550 znaczących akcji łącznie", undefined, prog("akcje", 550)],
  ["Zagraj 800 meczów", undefined, prog("mecze", 800)],
  ["Zdobądź tytuł najlepszego zawodnika swojej ligi (MVP)"],
  ["Zdobądź podium mistrzostw regionu z drużyną"],
  ["Zalicz 600 znaczących akcji łącznie", undefined, prog("akcje", 600)],
  ["Zagraj 900 meczów", undefined, prog("mecze", 900)],
  ["Zostań liderem i kapitanem swojej drużyny klubowej"],
  // 86-99 · Elita
  ["Zalicz 650 znaczących akcji łącznie", undefined, prog("akcje", 650)],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zagraj 1000 meczów", undefined, prog("mecze", 1000)],
  ["Zalicz 700 znaczących akcji łącznie", undefined, prog("akcje", 700)],
  ["Zalicz znaczącą akcję w ważnym meczu ligowym"],
  ["Zdobądź tytuł mistrza swojej ligi klubowej"],
  ["Zostań czołowym zawodnikiem swojej ligi na swojej pozycji"],
  ["Znajdź się w składzie gwiazd sezonu swojej ligi"],
  ["Zdobądź nagrodę MVP swojej ligi"],
  ["Poprowadź drużynę jako lider przez cały sezon"],
  ["Zagraj w finale rozgrywek ligowych"],
  ["Wygraj mistrzostwo swojej ligi klubowej"],
  ["Zdobądź uznanie w krajowym środowisku futbolu amerykańskiego"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej drużyny klubowej", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);
