// Artistic gymnastics ladder 1-99. Manual — progression tracks: floor skills
// (roll → handstand → walkover → back handspring → salto → twisting saltos),
// strength holds, flexibility, and competition levels.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "gimnastyka",
  name: "Gimnastyka",
  icon: "🤸‍♀️",
  description:
    "Gimnastyka sportowa — od przewrotu po salta i przyrządy. Progresja: elementy akrobatyczne, siła, gibkość i poziom zawodniczy.",
  sortOrder: 40,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Wykonaj przewrót w przód", undefined, prog("akro", 1)],
  ["Wykonaj przewrót w tył", undefined, prog("akro", 2)],
  ["Utrzymaj świecę (stanie na łopatkach) przez 10 s", undefined, prog("sila", 1)],
  ["Wykonaj stanie na rękach przy ścianie (20 s)", undefined, prog("handstand", 1)],
  ["Wykonaj mostek z leżenia", undefined, prog("gibkosc", 1)],
  ["Wykonaj gwiazdę (przewrót bokiem)", undefined, prog("akro", 3)],
  ["Utrzymaj deskę i pompki gimnastyczne (10 powt.)", undefined, prog("sila", 2)],
  ["Wykonaj szpagat na jedną stronę (choćby z podparciem)", undefined, prog("gibkosc", 2)],
  ["Wykonaj stanie na rękach bez ściany (3 s)", undefined, prog("handstand", 2)],
  ["Wykonaj rundak (przerzut z półobrotem)", undefined, prog("akro", 4)],
  // 11-25 · Regularny
  ["Trenuj 2 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(2, 4)],
  ["Wykonaj przerzut bokiem bez rąk (gwiazda „na wolno”)", undefined, prog("akro", 5)],
  ["Utrzymaj stanie na rękach przez 15 s bez ściany", undefined, prog("handstand", 4)],
  ["Wykonaj pełny szpagat podłużny na obie strony", undefined, prog("gibkosc", 3)],
  ["Wykonaj przerzut w przód (przewrót przez ręce)", undefined, prog("akro", 6)],
  ["Utrzymaj L-sit przez 10 s", undefined, prog("sila", 4)],
  ["Wykonaj przemyk / most z przejściem (bridge kick-over)", undefined, prog("gibkosc", 4)],
  ["Wykonaj przewrót lotny (dive roll)", undefined, prog("akro", 7)],
  ["Wykonaj stanie na rękach z marszem (kilka kroków)", undefined, prog("handstand", 6)],
  ["Wykonaj przerzut w tył wspomagany (back walkover)", undefined, prog("akro", 8)],
  ["Wykonaj szpagat poprzeczny (pełny)", undefined, prog("gibkosc", 5)],
  ["Utrzymaj L-sit przez 20 s", undefined, prog("sila", 6)],
  ["Wykonaj przerzut w przód swobodny (front walkover)", undefined, prog("akro", 9)],
  ["Zaprezentuj układ na zajęciach lub pokazie"],
  ["Wykonaj flik-flak wspomagany (back handspring z asekuracją)", undefined, prog("akro", 10)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 3 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Wykonaj flik-flak samodzielnie (back handspring)", "Podstawa akrobatyki.", prog("akro", 11)],
  ["Utrzymaj stanie na rękach przez 30 s", undefined, prog("handstand", 8)],
  ["Wykonaj rundak + flik-flak w połączeniu", undefined, prog("akro", 12)],
  ["Wykonaj przeshpagat (oversplit) na jedną stronę", undefined, prog("gibkosc", 6)],
  ["Wykonaj przewrót przez ręce w przód z lotem (front handspring)", undefined, prog("akro", 13)],
  ["Utrzymaj L-sit przez 30 s / wykonaj V-sit", undefined, prog("sila", 8)],
  ["Wykonaj salto w przód z rozbiegu (front tuck)", "Pierwsze salto!", prog("akro", 14)],
  ["Wykonaj serię: rundak + 2 flik-flaki", undefined, prog("akro", 15)],
  ["Utrzymaj stanie na rękach na poręczach/podwyższeniu 20 s", undefined, prog("handstand", 10)],
  ["Wykonaj salto w tył z miejsca (back tuck)", undefined, prog("akro", 16)],
  ["Wykonaj most z opadu do tyłu na stojąco (standing back bend to bridge)", undefined, prog("gibkosc", 7)],
  ["Wykonaj salto w tył w pozycji łamanej (pike back salto)", undefined, prog("akro", 17)],
  ["Wykonaj 3 pompki w staniu na rękach (HSPU)", undefined, prog("sila", 10)],
  ["Wykonaj serię akrobatyczną: rundak + flik + salto w tył", undefined, prog("akro", 18)],
  ["Zajmij miejsce w zawodach na poziomie regionalnym/klubowym"],
  ["Wykonaj salto w przód w pozycji łamanej", undefined, prog("akro", 19)],
  ["Utrzymaj planszę / front lever (10 s)", undefined, prog("sila", 12)],
  ["Wykonaj salto boczne (side salto / aerial)", undefined, prog("akro", 20)],
  ["Wykonaj gwiazdę bez rąk (aerial cartwheel)", undefined, prog("akro", 21)],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Wykonaj salto w tył wyprostowane (layout)", undefined, prog("akro", 22)],
  ["Utrzymaj stanie na rękach przez 60 s", undefined, prog("handstand", 14)],
  ["Wykonaj serię: rundak + flik + layout", undefined, prog("akro", 23)],
  ["Wykonaj salto w tył ze śrubą (full twist / 360°)", "Salto ze śrubą — element zawodniczy.", prog("akro", 24)],
  ["Wykonaj oversplit na obie strony", undefined, prog("gibkosc", 8)],
  ["Wykonaj 8 HSPU pod rząd", undefined, prog("sila", 14)],
  ["Wykonaj salto w przód ze śrubą", undefined, prog("akro", 25)],
  ["Wykonaj podwójny flik-flak w serii", undefined, prog("akro", 26)],
  ["Utrzymaj planche (tuck/straddle) 5 s", undefined, prog("sila", 16)],
  ["Wykonaj whip back + salto w połączeniu", undefined, prog("akro", 27)],
  ["Wykonaj salto w tył z podwójną śrubą (double full)", undefined, prog("akro", 28)],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Wykonaj salto podwójne w pozycji kulistej (double back tuck)", "Podwójne salto — poziom zaawansowany.", prog("akro", 29)],
  ["Utrzymaj krzyż na kółkach / planche pełną (jeśli dostępny sprzęt)", undefined, prog("sila", 18)],
  ["Wykonaj serię akrobatyczną z dwoma saltami", undefined, prog("akro", 30)],
  ["Wykonaj element na przyrządzie (poręcze, drążek, równoważnia)", undefined, prog("przyrzad", 1)],
  ["Wykonaj podwójne salto w pozycji łamanej (double pike)", undefined, prog("akro", 31)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju (kategoria)"],
  ["Wykonaj salto z potrójną śrubą (triple full)", undefined, prog("akro", 32)],
  // 66-85 · Wyczynowy
  ["Wykonaj pełen układ na dwóch przyrządach", undefined, prog("przyrzad", 2)],
  ["Wykonaj podwójne salto wyprostowane (double layout)", undefined, prog("akro", 33)],
  ["Utrzymaj stanie na rękach na kółkach lub jednej ręce (próba)", undefined, prog("handstand", 18)],
  ["Zdobądź medal mistrzostw kraju juniorów"],
  ["Wykonaj podwójne salto ze śrubą (full-in / double back full)", undefined, prog("akro", 34)],
  ["Wykonaj pełne układy na trzech przyrządach", undefined, prog("przyrzad", 3)],
  ["Wykonaj element trudności D lub wyższej w układzie", undefined, prog("akro", 35)],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Wykonaj podwójne salto z dwiema śrubami (full-full)", undefined, prog("akro", 36)],
  ["Opanuj pełne układy na wszystkich przyrządach swojej wieloboju", undefined, prog("przyrzad", 4)],
  ["Utrzymaj elementy siłowe klasy zawodniczej (np. krzyż, planche) w układzie", undefined, prog("sila", 20)],
  ["Wykonaj potrójne salto w pozycji kulistej (triple back — próba)", undefined, prog("akro", 37)],
  ["Uzyskaj notę kwalifikującą do zawodów o zasięgu ogólnokrajowym"],
  ["Wykonaj element trudności E w układzie", undefined, prog("akro", 38)],
  ["Weź udział w zawodach o zasięgu ogólnokrajowym juniorów/seniorów"],
  ["Wykonaj układ wielobojowy bez upadku na wszystkich przyrządach"],
  ["Wykonaj element trudności F w układzie", undefined, prog("akro", 39)],
  ["Zajmij miejsce w pierwszej ósemce zawodów o zasięgu ogólnokrajowym"],
  ["Uzyskaj wysoką notę za trudność (D-score) na wysokim poziomie"],
  ["Zdobądź podium zawodów o zasięgu ogólnokrajowym"],
  // 86-99 · Elita
  ["Wykonaj element trudności G (najwyższa klasa) w układzie", undefined, prog("akro", 40)],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Wykonaj autorski lub nazwany element o najwyższej trudności"],
  ["Zdobądź podium mistrzostw kraju amatorów"],
  ["Uzyskaj notę wieloboju na wysokim, krajowym poziomie"],
  ["Zajmij miejsce w czołówce mistrzostw kraju amatorów"],
  ["Zajmij miejsce w finale przyrządowym mistrzostw kraju"],
  ["Zdobądź medal mistrzostw kraju amatorów na przyrządzie"],
  ["Zdobądź medal wieloboju mistrzostw kraju amatorów"],
  ["Poprowadź kogoś przez zaawansowane elementy techniczne"],
  ["Wykonaj bezbłędny układ na wszystkich przyrządach na zawodach"],
  ["Zdobądź uznanie w krajowym środowisku gimnastycznym"],
  ["Wygraj wielobój mistrzostw kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): element G i wieloletni, dojrzały warsztat", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);
