// Golf ladder 1-99. Tracks: score breaking (value = 200 - score, so lower
// scores imply higher claims), handicap (value = 54 - HCP), drive distance,
// rounds played. Benchmarks: average golfer shoots ~100 and holds HCP ~18-20;
// breaking 90 = top ~25%; breaking 80 = top ~5%; scratch (HCP 0) = ~1%.
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "golf",
  name: "Golf",
  icon: "⛳",
  description:
    "Od pierwszego swingu po grę w okolicach par. Progi wg światowych statystyk handicapów.",
  sortOrder: 18,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Traf piłkę czysto na driving range", "Kontakt z piłką w środku główki — początek wszystkiego."],
  ["Wybij 50 piłek na driving range w jednej sesji"],
  ["Wykonaj putt do dołka z 1 metra"],
  ["Traf 10 kolejnych piłek czysto żelazem"],
  ["Wybij piłkę na odległość 75 m"],
  ["Wykonaj chip na green z okolicy 20 m"],
  ["Traf puttem z 1 m 8/10 prób"],
  ["Wybij piłkę na odległość 100 m"],
  ["Zagraj pierwsze 9 dołków (pole par-3 lub pełne)", "Wynik nieważny — doświadcz rundy."],
  ["Zdaj egzamin Zielonej Karty lub odpowiednik uprawnień pola", "W Polsce przepustka na pełnowymiarowe pola."],
  // 11-25 · Regularny
  ["Trenuj lub graj raz w tygodniu przez 4 kolejne tygodnie"],
  ["Wybij piłkę driverem na 125 m"],
  ["Traf puttem z 2 m 5/10"],
  ["Zagraj pierwszą pełną rundę 18 dołków"],
  ["Ukończ 9 dołków z wynikiem poniżej 60 uderzeń"],
  ["Wykonaj bunker shot (wyjście z piasku) na green"],
  ["Zagraj 5 rund"],
  ["Wybij driverem 150 m"],
  ["Złam 110 na 18 dołkach", "Pierwszy duży próg wyniku."],
  ["Traf green w regulacji (GIR) 3 razy w jednej rundzie"],
  ["Zagraj 10 rund"],
  ["Traf puttem z 3 m 4/10"],
  ["Zrób pierwszego para na dołku", "Wynik zgodny z założeniem pola."],
  ["Wybij driverem 175 m"],
  ["Złam 105 na 18 dołkach"],
  // 26-45 · Średniozaawansowany
  ["Zagraj 20 rund"],
  ["Złam 100", "Magiczna setka — większość golfistów nigdy jej nie łamie."],
  ["Zrób 3 pary w jednej rundzie"],
  ["Uzyskaj oficjalny handicap (HCP 54 lub niższy)"],
  ["Wybij driverem 200 m"],
  ["Zrób pierwszego birdie", "Dołek poniżej par — smak, który uzależnia."],
  ["Obniż HCP do 40"],
  ["Zagraj 35 rund"],
  ["Traf 6 GIR w jednej rundzie"],
  ["Złam 95"],
  ["Obniż HCP do 36", "Pełnoprawny handicap turniejowy."],
  ["Wykonaj up-and-down (chip + putt) 3 razy w rundzie"],
  ["Zagraj rundę bez podwójnego bogeya lub gorzej"],
  ["Zagraj 50 rund", "Pół setki rund."],
  ["Obniż HCP do 30"],
  ["Weź udział w pierwszym turnieju klubowym"],
  ["Traf puttem z 3 m 6/10"],
  ["Złam 90", "Top ~25% golfistów świata."],
  ["Obniż HCP do 26"],
  ["Zrób 2 birdie w jednej rundzie"],
  // 46-65 · Zaawansowany
  ["Zagraj 75 rund"],
  ["Wybij driverem 220 m"],
  ["Obniż HCP do 22"],
  ["Zagraj rundę z 9 GIR"],
  ["Ukończ turniej klubowy w pierwszej połowie stawki"],
  ["Złam 88"],
  ["Obniż HCP do 20", "Okolice średniej światowej golfistów z HCP."],
  ["Zagraj 100 rund", "Setka rund na polach."],
  ["Zrób eagle'a lub hole-in-one na par-3 (albo albatrosa — jeśli los da)", "Dwa poniżej par na dołku."],
  ["Złam 85"],
  ["Obniż HCP do 18"],
  ["Wygraj klasyfikację netto turnieju klubowego"],
  ["Zrób 3 birdie w jednej rundzie"],
  ["Obniż HCP do 15"],
  ["Zagraj 150 rund"],
  ["Złam 82"],
  ["Traf 12 GIR w jednej rundzie"],
  ["Obniż HCP do 13"],
  ["Zagraj rundę bez trzech puttów na żadnym greenie"],
  ["Złam 80", "Top ~5% golfistów. Single digit coraz bliżej."],
  // 66-85 · Wyczynowy
  ["Obniż HCP do 11"],
  ["Zagraj 200 rund"],
  ["Wygraj klasyfikację brutto turnieju klubowego"],
  ["Obniż HCP do 9,9 (single digit)", "Jednocyfrowy handicap — ~10% zrzeszonych graczy."],
  ["Zrób 4 birdie w jednej rundzie"],
  ["Złam 78"],
  ["Zagraj 250 rund"],
  ["Obniż HCP do 8"],
  ["Weź udział w turnieju rangi regionalnej"],
  ["Złam 76"],
  ["Obniż HCP do 6"],
  ["Zagraj 300 rund"],
  ["Traf 14 GIR w jednej rundzie"],
  ["Zdobądź podium turnieju regionalnego"],
  ["Obniż HCP do 5"],
  ["Złam 75"],
  ["Zrób 5 birdie w jednej rundzie"],
  ["Obniż HCP do 4"],
  ["Zagraj 400 rund"],
  ["Złam 74"],
  // 86-99 · Elita
  ["Obniż HCP do 3"],
  ["Wygraj turniej regionalny"],
  ["Złam 73"],
  ["Obniż HCP do 2"],
  ["Zagraj 500 rund", "Pół tysiąca rund."],
  ["Zagraj rundę w par pola (E)"],
  ["Obniż HCP do 1"],
  ["Weź udział w regionalnych mistrzostwach amatorów"],
  ["Zostań scratch golferem (HCP 0)", "~1% wszystkich golfistów z handicapem."],
  ["Złam 70 (runda pod par)"],
  ["Zdobądź plusowy handicap (+1 lub lepszy)"],
  ["Zdobądź podium regionalnych mistrzostw amatorów"],
  ["Wygraj turniej klubowy lub regionalny amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): HCP +2 lub lepszy", "Dojrzały, wieloletni warsztat golfowy zaangażowanego amatora. Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  2: prog("range", 50), 4: prog("range", 60),
  3: prog("putt-1m", 1), 7: prog("putt-1m", 8),
  13: prog("putt-3m", 3), 22: prog("putt-3m", 4), 42: prog("putt-3m", 6),
  5: prog("drive", 75), 8: prog("drive", 100), 12: prog("drive", 125), 18: prog("drive", 150),
  24: prog("drive", 175), 30: prog("drive", 200), 47: prog("drive", 220),
  17: prog("rundy", 5), 21: prog("rundy", 10), 26: prog("rundy", 20), 33: prog("rundy", 35),
  39: prog("rundy", 50), 46: prog("rundy", 75), 53: prog("rundy", 100), 60: prog("rundy", 150),
  67: prog("rundy", 200), 72: prog("rundy", 250), 77: prog("rundy", 300), 84: prog("rundy", 400),
  90: prog("rundy", 500),
  19: prog("score", 90), 25: prog("score", 95), 27: prog("score", 100), 35: prog("score", 105),
  43: prog("score", 110), 51: prog("score", 112), 55: prog("score", 115), 61: prog("score", 118),
  65: prog("score", 120), 71: prog("score", 122), 75: prog("score", 124), 81: prog("score", 125),
  85: prog("score", 126), 88: prog("score", 127), 91: prog("score", 128), 95: prog("score", 130),
  29: prog("hcp", 0), 32: prog("hcp", 14), 36: prog("hcp", 18), 40: prog("hcp", 24),
  44: prog("hcp", 28), 48: prog("hcp", 32), 52: prog("hcp", 34), 56: prog("hcp", 36),
  59: prog("hcp", 39), 63: prog("hcp", 41), 66: prog("hcp", 43), 69: prog("hcp", 44.1),
  73: prog("hcp", 46), 76: prog("hcp", 48), 80: prog("hcp", 49), 83: prog("hcp", 50),
  86: prog("hcp", 51), 89: prog("hcp", 52), 92: prog("hcp", 53), 94: prog("hcp", 54),
  96: prog("hcp", 55),
  11: freq(1, 4),
  // GIR, birdie, turnieje — manualne.
};
