// Digital painting ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, work counts scaled; top tiers reframed as
// attainable mastery, real feats left to future certificates).
// Tracks: umiejetnosci, prace (finished works), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "grafika-cyfrowa",
  name: "Grafika cyfrowa",
  icon: "🖥️",
  description:
    "Malowanie cyfrowe i concept art (tablet + program). Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → portfolio i zlecenia → dojrzały, autorski styl.",
  sortOrder: 92,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj tablet i podstawy programu (warstwy, pędzle, skróty)", undefined, prog("umiejetnosci", 1)],
  ["Prowadź pewną, kontrolowaną kreskę tabletem", undefined, prog("umiejetnosci", 2)],
  ["Używaj warstw i kryjności (opacity) świadomie", undefined, prog("umiejetnosci", 3)],
  ["Namaluj bryły z walorami (kula, sześcian, walec)", undefined, prog("umiejetnosci", 4)],
  ["Zbuduj studium wartości (grayscale) prostego motywu", undefined, prog("umiejetnosci", 5)],
  ["Namaluj prostą ilustrację od szkicu po kolor", undefined, prog("prace", 3)],
  ["Używaj masek i trybów mieszania warstw", undefined, prog("umiejetnosci", 6)],
  ["Dobierz paletę i pokoloruj rysunek (flats + cienie)", undefined, prog("umiejetnosci", 7)],
  ["Ukończ 10 prac cyfrowych", undefined, prog("prace", 10)],
  ["Maluj cyfrowo łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Maluj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Opanuj custom brushes i teksturowanie", undefined, prog("umiejetnosci", 8)],
  ["Namaluj portret cyfrowy z podobieństwem", undefined, prog("prace", 20)],
  ["Opanuj oświetlenie (rim light, ambient, źródła barwne)", undefined, prog("umiejetnosci", 9)],
  ["Namaluj proste środowisko (krajobraz z planami)", undefined, prog("umiejetnosci", 10)],
  ["Maluj cyfrowo łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Opanuj perspektywę cyfrową (siatki, punkty zbiegu)", undefined, prog("umiejetnosci", 11)],
  ["Ukończ 35 prac", undefined, prog("prace", 35)],
  ["Namaluj postać w pełnej figurze z proporcjami", undefined, prog("umiejetnosci", 12)],
  ["Użyj fotobashingu / referencji z zachowaniem spójności", undefined, prog("umiejetnosci", 13)],
  ["Namaluj rendering materiałów (metal, skóra, tkanina)", undefined, prog("umiejetnosci", 14)],
  ["Maluj cyfrowo łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Zaprojektuj prosty projekt postaci (character design)", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 60 prac", undefined, prog("prace", 60)],
  ["Namaluj scenę o spójnym oświetleniu i nastroju", undefined, prog("umiejetnosci", 16)],
  // 26-45 · Średniozaawansowany
  ["Maluj regularnie przez 8 kolejnych tygodni", undefined, freq(3, 8)],
  ["Opanuj koncept środowiska (environment concept art)", undefined, prog("umiejetnosci", 17)],
  ["Namaluj złożoną ilustrację wielopostaciową", undefined, prog("umiejetnosci", 18)],
  ["Ukończ 90 prac", undefined, prog("prace", 90)],
  ["Opanuj malowanie z wyobraźni (bez ciężkiej referencji)", undefined, prog("umiejetnosci", 19)],
  ["Maluj cyfrowo łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Zbuduj kompozycję prowadzącą wzrok (thumbnaile → finał)", undefined, prog("umiejetnosci", 20)],
  ["Zaprojektuj prop / pojazd (industrial design concept)", undefined, prog("umiejetnosci", 21)],
  ["Opanuj kolor i światło w scenach o różnej porze dnia", undefined, prog("umiejetnosci", 22)],
  ["Namaluj key art / okładkę (ilustracja narracyjna)", undefined, prog("umiejetnosci", 23)],
  ["Ukończ 130 prac", undefined, prog("prace", 130)],
  ["Opanuj mood i storytelling w jednym kadrze", undefined, prog("umiejetnosci", 24)],
  ["Maluj cyfrowo łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Zbuduj spójny arkusz projektu (turnaround, warianty)", undefined, prog("umiejetnosci", 25)],
  ["Ukończ 170 prac", undefined, prog("prace", 170)],
  ["Opanuj szybkie szkicowanie koncepcyjne (speed painting)", undefined, prog("umiejetnosci", 26)],
  ["Maluj cyfrowo łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Namaluj pełnowartościowy concept do gry/filmu (poziom portfolio)", undefined, prog("umiejetnosci", 27)],
  ["Ukończ 220 prac", undefined, prog("prace", 220)],
  ["Maluj regularnie przez 3 miesiące", undefined, prog("prace", 260)],
  // 46-65 · Zaawansowany (amator)
  ["Maluj regularnie przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Zaprojektuj kompletny świat / IP (postacie + środowiska)", undefined, prog("umiejetnosci", 28)],
  ["Zbuduj rozpoznawalny, spójny styl cyfrowy", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 300 prac", undefined, prog("prace", 300)],
  ["Maluj cyfrowo łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Opublikuj prace i buduj obserwujących (ArtStation/social)"],
  ["Opanuj mistrzowski rendering i wykończenie ilustracji", undefined, prog("umiejetnosci", 30)],
  ["Ukończ 360 prac", undefined, prog("prace", 360)],
  ["Zbuduj profesjonalne portfolio pod klienta / studio", undefined, prog("umiejetnosci", 31)],
  ["Maluj cyfrowo łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Wygraj lub wyróżnij się w konkursie artystycznym"],
  ["Sprzedaj pierwszą pracę lub zdobądź zlecenie"],
  ["Namaluj concept na poziomie produkcyjnym (studio-ready)", undefined, prog("umiejetnosci", 32)],
  ["Ukończ 430 prac", undefined, prog("prace", 430)],
  ["Realizuj zlecenia (ilustracja / concept) regularnie", undefined, prog("umiejetnosci", 33)],
  ["Maluj cyfrowo łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy malowania cyfrowego"],
  ["Zrealizuj spójny cykl / mini-projekt (art book, IP)"],
  ["Namaluj ilustrację na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 500 prac", undefined, prog("prace", 500)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Maluj regularnie przez pełny sezon (6 miesięcy)"],
  ["Projektuj swobodnie postacie i środowiska z wyobraźni", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 600 prac", undefined, prog("prace", 600)],
  ["Maluj cyfrowo łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zbuduj społeczność / grono odbiorców swojej twórczości"],
  ["Rozwiń warsztat na tyle, by uczyć grafiki cyfrowej", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie realizujesz płatne zlecenia"],
  ["Opanuj każdy temat i styl na wysokim poziomie", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 750 prac", undefined, prog("prace", 750)],
  ["Zdobądź wyróżnienie lub uznanie w społeczności (ArtStation)"],
  ["Maluj cyfrowo łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny projekt autorski (artbook / IP)", undefined, prog("umiejetnosci", 38)],
  ["Twoje prace są dojrzałe i rozpoznawalne bez podpisu", undefined, prog("umiejetnosci", 39)],
  ["Ukończ 900 prac", undefined, prog("prace", 900)],
  ["Zbuduj markę i rozpoznawalne portfolio o zasięgu ponadlokalnym"],
  ["Poprowadź warsztaty lub mentoring dla artystów cyfrowych"],
  ["Publikuj tutoriale lub kursy grafiki cyfrowej"],
  ["Zrealizuj wystawę lub publikację prezentującą dorobek"],
  ["Ukończ 1100 prac", undefined, prog("prace", 1100)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Maluj cyfrowo łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdej pracy"],
  ["Ukończ 1300 prac", undefined, prog("prace", 1300)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych artystów cyfrowych w Twoim otoczeniu"],
  ["Zrealizuj osobisty „opus” — dużą ilustrację lub artbook", undefined, prog("umiejetnosci", 40)],
  ["Regularnie publikujesz prace lub realizujesz duże zlecenia"],
  ["Maluj cyfrowo łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoja twórczość zdobywa uznanie poza lokalną społecznością"],
  ["Ukończ 1500 prac", undefined, prog("prace", 1500)],
  ["Uczysz i kształtujesz kolejnych artystów cyfrowych"],
  ["Masz dorobek, z którego można ułożyć wystawę retrospektywną"],
  ["Namalujesz cyfrowo niemal wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski styl", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones. Filmy + wolna biblioteka Ctrl+Paint.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [
    { kind: "video", title: "Podstawy programu (Krita)", url: yt("UjtzfE609Vs") },
    { kind: "course", title: "Ctrl+Paint — biblioteka lekcji", url: "https://www.ctrlpaint.com/library" },
  ],
  2: [{ kind: "video", title: "Płynna kreska tabletem", url: yt("IAOZXjXDc34") }],
  4: [{ kind: "video", title: "Malowanie kuli (walor, forma)", url: yt("oA2MeD1qyXc") }],
  5: [{ kind: "video", title: "Malowanie w skali szarości", url: yt("wmpzOHVqBQI") }],
  8: [{ kind: "video", title: "Cieniowanie i blendowanie", url: yt("p1mQ4zDBTAA") }],
  12: [{ kind: "video", title: "Własne pędzle (custom brushes)", url: yt("Iq5RAy2rhnU") }],
  14: [{ kind: "video", title: "Rim light — światło konturowe", url: yt("xaqo7y8GUqM") }],
  20: [{ kind: "video", title: "Photobashing — wprowadzenie", url: yt("isIdzpqfa6g") }],
  23: [{ kind: "video", title: "Projektowanie postaci", url: yt("UnWZhBUa46g") }],
  27: [{ kind: "video", title: "Concept art środowiska", url: yt("VW7DpsFgj8o") }],
};
