// Ice hockey ladder 1-99. Manual — progression tracks: matches played, points
// (goals+assists total), competition level. Skating skill early on.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "hokej",
  name: "Hokej na lodzie",
  icon: "🏒",
  description:
    "Od pierwszej jazdy z krążkiem po ligowe tafle. Progresja: rozegrane mecze, punkty (gole + asysty) i poziom rozgrywkowy.",
  sortOrder: 34,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Jedź pewnie na łyżwach do przodu", undefined, prog("technika", 1)],
  ["Zatrzymaj się kontrolowanie (na dwóch łyżwach)", undefined, prog("technika", 2)],
  ["Prowadź krążek kijem w truchcie", undefined, prog("technika", 3)],
  ["Wykonaj poprawne podanie i przyjęcie krążka", undefined, prog("technika", 4)],
  ["Oddaj strzał nadgarstkowy (wrist shot) do bramki", undefined, prog("technika", 5)],
  ["Jedź do tyłu i wykonaj przekładankę", undefined, prog("technika", 6)],
  ["Traf do pustej bramki z bliska", undefined, prog("technika", 7)],
  ["Zagraj pierwszy mecz treningowy", undefined, prog("mecze", 1)],
  ["Zdobądź pierwszy punkt (gol lub asysta)", undefined, prog("punkty", 1)],
  ["Rozegraj pełny mecz (3 tercje lub skrócony)", undefined, prog("mecze", 2)],
  // 11-25 · Regularny
  ["Trenuj lub graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Wykonaj strzał klepnięty (slap shot)", undefined, prog("technika", 8)],
  ["Zagraj 5 meczów", undefined, prog("mecze", 5)],
  ["Zdobądź 5 punktów łącznie", undefined, prog("punkty", 5)],
  ["Zatrzymaj się i ruszaj eksplozywnie w obie strony", undefined, prog("technika", 9)],
  ["Zagraj na stałej pozycji (obrona lub atak) przez cały mecz"],
  ["Zagraj 10 meczów", undefined, prog("mecze", 10)],
  ["Zdobądź 12 punktów łącznie", undefined, prog("punkty", 12)],
  ["Wykonaj skuteczny odbiór krążka (poke check / body check zgodny z przepisami)", undefined, prog("technika", 10)],
  ["Rozegraj mecz w lidze amatorskiej", undefined, prog("liga", 1)],
  ["Zagraj 20 meczów", undefined, prog("mecze", 20)],
  ["Zdobądź 25 punktów łącznie", undefined, prog("punkty", 25)],
  ["Zdobądź 3 punkty w jednym meczu", undefined, prog("punkty-mecz", 3)],
  ["Wykonaj zwód i minij obrońcę w biegu", undefined, prog("technika", 11)],
  ["Zagraj 30 meczów", undefined, prog("mecze", 30)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zdobądź 40 punktów łącznie", undefined, prog("punkty", 40)],
  ["Oddaj strzał w jednym kontakcie (one-timer)", undefined, prog("technika", 12)],
  ["Zagraj 50 meczów", undefined, prog("mecze", 50)],
  ["Zdobądź 60 punktów łącznie", undefined, prog("punkty", 60)],
  ["Rozegraj pełny sezon w regularnej lidze", undefined, prog("liga", 2)],
  ["Graj skutecznie w przewadze (power play) lub osłabieniu (penalty kill) (specjalne zespoły)", undefined, prog("technika", 13)],
  ["Zdobądź 4 punkty w jednym meczu", undefined, prog("punkty-mecz", 4)],
  ["Zagraj 75 meczów", undefined, prog("mecze", 75)],
  ["Zdobądź 90 punktów łącznie", undefined, prog("punkty", 90)],
  ["Zajmij miejsce w pierwszej połowie tabeli ligowej"],
  ["Zdobądź hat-tricka (3 gole w meczu)", undefined, prog("technika", 14)],
  ["Zagraj 100 meczów", undefined, prog("mecze", 100)],
  ["Zdobądź 130 punktów łącznie", undefined, prog("punkty", 130)],
  ["Rozegraj mecz w II lidze lub odpowiedniku", undefined, prog("liga", 3)],
  ["Zostań liderem punktacji swojej drużyny w rundzie"],
  ["Zdobądź 170 punktów łącznie", undefined, prog("punkty", 170)],
  ["Zagraj 150 meczów", undefined, prog("mecze", 150)],
  ["Poprowadź zespół jako kapitan lub asystent"],
  ["Zdobądź 5 punktów w jednym meczu", undefined, prog("punkty-mecz", 5)],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Zdobądź 220 punktów łącznie", undefined, prog("punkty", 220)],
  ["Rozegraj mecz w I lidze", undefined, prog("liga", 4)],
  ["Zagraj 200 meczów", undefined, prog("mecze", 200)],
  ["Zdobądź 280 punktów łącznie", undefined, prog("punkty", 280)],
  ["Zostań kluczowym zawodnikiem zespołu I-ligowego"],
  ["Zajmij miejsce w czołówce I ligi"],
  ["Zagraj 250 meczów", undefined, prog("mecze", 250)],
  ["Zdobądź 350 punktów łącznie", undefined, prog("punkty", 350)],
  ["Zdobądź 6 punktów w jednym meczu", undefined, prog("punkty-mecz", 6)],
  ["Awansuj z drużyną do wyższej klasy rozgrywek"],
  ["Zdobądź 420 punktów łącznie", undefined, prog("punkty", 420)],
  ["Zagraj 300 meczów", undefined, prog("mecze", 300)],
  ["Zostań najlepszym strzelcem rundy w lidze"],
  ["Zdobądź 500 punktów łącznie", undefined, prog("punkty", 500)],
  ["Zagraj w najwyższej lidze krajowej (PHL)", undefined, prog("liga", 5)],
  ["Zdobądź punkt w meczu najwyższej ligi"],
  ["Zdobądź 580 punktów łącznie", undefined, prog("punkty", 580)],
  ["Zagraj 400 meczów", undefined, prog("mecze", 400)],
  ["Zostań rozpoznawalnym zawodnikiem w swoim regionie"],
  // 66-85 · Wyczynowy
  ["Zdobądź 660 punktów łącznie", undefined, prog("punkty", 660)],
  ["Zagraj 500 meczów", undefined, prog("mecze", 500)],
  ["Zostań kluczowym zawodnikiem najwyższej ligi"],
  ["Zdobądź 740 punktów łącznie", undefined, prog("punkty", 740)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Zagraj 600 meczów", undefined, prog("mecze", 600)],
  ["Zdobądź 820 punktów łącznie", undefined, prog("punkty", 820)],
  ["Zostań uznanym zawodnikiem swojej ligi regionalnej"],
  ["Zdobądź 900 punktów łącznie", undefined, prog("punkty", 900)],
  ["Zagraj 700 meczów", undefined, prog("mecze", 700)],
  ["Zdobądź punkt w ważnym meczu ligowym"],
  ["Zdobądź 980 punktów łącznie", undefined, prog("punkty", 980)],
  ["Zagraj w europejskich rozgrywkach klubowych (Champions Hockey League)"],
  ["Zdobądź 1060 punktów łącznie", undefined, prog("punkty", 1060)],
  ["Zagraj 800 meczów", undefined, prog("mecze", 800)],
  ["Zdobądź podium mistrzostw regionu z klubem"],
  ["Zagraj w turnieju o zasięgu ogólnokrajowym"],
  ["Zdobądź 1140 punktów łącznie", undefined, prog("punkty", 1140)],
  ["Zagraj 900 meczów", undefined, prog("mecze", 900)],
  ["Zostań kapitanem swojej drużyny klubowej"],
  // 86-99 · Elita
  ["Zdobądź 1220 punktów łącznie", undefined, prog("punkty", 1220)],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zagraj 1000 meczów", undefined, prog("mecze", 1000)],
  ["Zdobądź 1300 punktów łącznie", undefined, prog("punkty", 1300)],
  ["Zdobądź punkt w ważnym meczu ligowym"],
  ["Zdobądź podium turnieju o zasięgu ogólnokrajowym"],
  ["Zostań czołowym punktującym swojej ligi"],
  ["Zagraj w finale rozgrywek ligowych"],
  ["Zdobądź gola lub asystę w finale rozgrywek ligowych"],
  ["Zdobądź trofeum swojej ligi klubowej"],
  ["Znajdź się w składzie gwiazd sezonu swojej ligi"],
  ["Zostań MVP swojej ligi lub turnieju"],
  ["Wygraj mistrzostwo swojej ligi klubowej"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej drużyny klubowej", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);
