// Field hockey ladder 1-99. Manual — progression tracks: matches played, goals
// (total), and competition level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "hokej-na-trawie",
  name: "Hokej na trawie",
  icon: "🏑",
  description:
    "Olimpijski sport drużynowy z laską i piłką — od pierwszego prowadzenia po ligowe murawy. Progresja: mecze, bramki i poziom rozgrywek.",
  sortOrder: 53,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Prowadź piłkę laską w truchcie (dribbling)", undefined, prog("technika", 1)],
  ["Wykonaj poprawne podanie push", undefined, prog("technika", 2)],
  ["Przyjmij piłkę pod kontrolę w biegu", undefined, prog("technika", 3)],
  ["Wykonaj uderzenie (hit) do bramki", undefined, prog("technika", 4)],
  ["Wykonaj indyjski dribbling (przekładanie piłki)", undefined, prog("technika", 5)],
  ["Odbierz piłkę przeciwnikowi zgodnie z przepisami (tackle)", undefined, prog("technika", 6)],
  ["Zrozum pozycje i ustawienie w grze", undefined, prog("technika", 7)],
  ["Zagraj pierwszy mecz treningowy", undefined, prog("mecze", 1)],
  ["Zdobądź pierwszą bramkę w grze", undefined, prog("bramki", 1)],
  ["Rozegraj pełny mecz (4 kwarty lub 2 połowy)", undefined, prog("mecze", 2)],
  // 11-25 · Regularny
  ["Trenuj lub graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Wykonaj slap shot lub flick", undefined, prog("technika", 8)],
  ["Zagraj 5 meczów", undefined, prog("mecze", 5)],
  ["Zdobądź 5 bramek łącznie", undefined, prog("bramki", 5)],
  ["Zagraj skuteczny rzut karny krótki (short corner) — wejście", undefined, prog("technika", 9)],
  ["Zagraj na stałej pozycji przez cały mecz"],
  ["Zagraj 10 meczów", undefined, prog("mecze", 10)],
  ["Zdobądź 12 bramek łącznie", undefined, prog("bramki", 12)],
  ["Wykonaj skuteczny 3D skill (unoszenie piłki nad laską)", undefined, prog("technika", 10)],
  ["Rozegraj mecz w lidze amatorskiej", undefined, prog("liga", 1)],
  ["Zagraj 20 meczów", undefined, prog("mecze", 20)],
  ["Zdobądź 25 bramek łącznie", undefined, prog("bramki", 25)],
  ["Zdobądź bramkę z rzutu karnego krótkiego (drag flick)", undefined, prog("technika", 11)],
  ["Zdobądź 3 bramki w jednym meczu", undefined, prog("bramki-mecz", 3)],
  ["Zagraj 30 meczów", undefined, prog("mecze", 30)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zdobądź 40 bramek łącznie", undefined, prog("bramki", 40)],
  ["Opanuj drag flick z prędkością (rzut karny krótki)", undefined, prog("technika", 12)],
  ["Zagraj 50 meczów", undefined, prog("mecze", 50)],
  ["Zdobądź 60 bramek łącznie", undefined, prog("bramki", 60)],
  ["Rozegraj pełny sezon w regularnej lidze", undefined, prog("liga", 2)],
  ["Zdobądź 4 bramki w jednym meczu", undefined, prog("bramki-mecz", 4)],
  ["Graj skutecznie w pressingu i obronie strefowej", undefined, prog("technika", 13)],
  ["Zagraj 75 meczów", undefined, prog("mecze", 75)],
  ["Zdobądź 90 bramek łącznie", undefined, prog("bramki", 90)],
  ["Zajmij miejsce w pierwszej połowie tabeli ligowej"],
  ["Zostań liderem strzelców zespołu w rundzie", undefined, prog("technika", 14)],
  ["Zagraj 100 meczów", undefined, prog("mecze", 100)],
  ["Zdobądź 130 bramek łącznie", undefined, prog("bramki", 130)],
  ["Rozegraj mecz w II lidze lub odpowiedniku", undefined, prog("liga", 3)],
  ["Wygraj mecz o awans lub play-off"],
  ["Zdobądź 170 bramek łącznie", undefined, prog("bramki", 170)],
  ["Zagraj 150 meczów", undefined, prog("mecze", 150)],
  ["Poprowadź zespół jako kapitan", undefined, prog("technika", 15)],
  ["Zdobądź 5 bramek w jednym meczu", undefined, prog("bramki-mecz", 5)],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Zdobądź 210 bramek łącznie", undefined, prog("bramki", 210)],
  ["Rozegraj mecz w I lidze", undefined, prog("liga", 4)],
  ["Zagraj 200 meczów", undefined, prog("mecze", 200)],
  ["Zdobądź 260 bramek łącznie", undefined, prog("bramki", 260)],
  ["Zostań kluczowym zawodnikiem zespołu I-ligowego"],
  ["Zajmij miejsce w czołówce I ligi"],
  ["Zagraj 250 meczów", undefined, prog("mecze", 250)],
  ["Zdobądź 320 bramek łącznie", undefined, prog("bramki", 320)],
  ["Zdobądź 6 bramek w jednym meczu", undefined, prog("bramki-mecz", 6)],
  ["Rozegraj mecz na wysokim poziomie ligowym", undefined, prog("liga", 5)],
  ["Zdobądź 380 bramek łącznie", undefined, prog("bramki", 380)],
  ["Zagraj 300 meczów", undefined, prog("mecze", 300)],
  ["Zdobądź bramkę w meczu najwyższej ligi"],
  ["Zdobądź 440 bramek łącznie", undefined, prog("bramki", 440)],
  ["Zostań kluczowym zawodnikiem najwyższej ligi"],
  ["Zagraj 400 meczów", undefined, prog("mecze", 400)],
  ["Zdobądź 500 bramek łącznie", undefined, prog("bramki", 500)],
  ["Zostań najlepszym strzelcem rundy w lidze"],
  ["Zostań rozpoznawalnym zawodnikiem w swoim regionie"],
  // 66-85 · Wyczynowy
  ["Zdobądź 560 bramek łącznie", undefined, prog("bramki", 560)],
  ["Zagraj 500 meczów", undefined, prog("mecze", 500)],
  ["Zostań filarem drużyny najwyższej ligi"],
  ["Zdobądź 620 bramek łącznie", undefined, prog("bramki", 620)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Zagraj 600 meczów", undefined, prog("mecze", 600)],
  ["Zdobądź 680 bramek łącznie", undefined, prog("bramki", 680)],
  ["Zostań uznanym zawodnikiem swojej ligi regionalnej"],
  ["Zdobądź 740 bramek łącznie", undefined, prog("bramki", 740)],
  ["Zagraj 700 meczów", undefined, prog("mecze", 700)],
  ["Zdobądź bramkę w ważnym meczu ligowym"],
  ["Zdobądź 800 bramek łącznie", undefined, prog("bramki", 800)],
  ["Zagraj w europejskich pucharach klubowych (EHL)"],
  ["Zdobądź 860 bramek łącznie", undefined, prog("bramki", 860)],
  ["Zagraj 800 meczów", undefined, prog("mecze", 800)],
  ["Zdobądź podium mistrzostw regionu z klubem"],
  ["Zagraj w turnieju o zasięgu ogólnokrajowym"],
  ["Zdobądź 920 bramek łącznie", undefined, prog("bramki", 920)],
  ["Zagraj 900 meczów", undefined, prog("mecze", 900)],
  ["Zostań kapitanem swojej drużyny klubowej"],
  // 86-99 · Elita
  ["Zdobądź 980 bramek łącznie", undefined, prog("bramki", 980)],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zagraj 1000 meczów", undefined, prog("mecze", 1000)],
  ["Zdobądź 1050 bramek łącznie", undefined, prog("bramki", 1050)],
  ["Zdobądź bramkę w ważnym meczu ligowym"],
  ["Awansuj z klubem do wyższej klasy rozgrywkowej"],
  ["Zostań czołowym strzelcem swojej ligi"],
  ["Weź udział w turnieju o zasięgu ogólnokrajowym"],
  ["Zdobądź podium mistrzostw regionu z klubem"],
  ["Zdobądź trofeum swojej ligi klubowej"],
  ["Znajdź się w składzie gwiazd turnieju"],
  ["Poprowadź drużynę jako lider / kapitan przez sezon"],
  ["Wygraj mistrzostwo swojej ligi klubowej"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej drużyny klubowej", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);
