// Equestrian ladder 1-99. Manual — progression tracks: riding skill, jumping
// height (cm), and competition level (dressage/show jumping/eventing).
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "jezdziectwo",
  name: "Jeździectwo",
  icon: "🐎",
  description:
    "Jazda konna — ujeżdżenie, skoki i WKKW. Progresja: umiejętności jeździeckie, wysokość skoków i poziom zawodów.",
  sortOrder: 71,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Dosiądź konia i utrzymaj prawidłowy dosiad w stępie (walk)", undefined, prog("technika", 1)],
  ["Kieruj koniem w stępie (skręty, zatrzymanie)", undefined, prog("technika", 2)],
  ["Jedź kłusem anglezowanym", undefined, prog("technika", 3)],
  ["Jedź kłusem ćwiczebnym (siedzącym) przez kilka kroków", undefined, prog("technika", 4)],
  ["Zagalopuj i utrzymaj galop przez okrążenie", undefined, prog("technika", 5)],
  ["Wykonaj przejścia stęp-kłus-galop płynnie", undefined, prog("technika", 6)],
  ["Przejedź kawaletki (drążki na ziemi) w kłusie", undefined, prog("skoki", 30)],
  ["Pokonaj pierwszą przeszkodę (krzyż z dwóch skrzyżowanych drągów, ~40 cm)", undefined, prog("skoki", 40)],
  ["Zdobądź odznakę jeździecką (brązową) lub ukończ kurs podstawowy", undefined, prog("technika", 7)],
  ["Pokonaj przeszkodę 50 cm", undefined, prog("skoki", 50)],
  // 11-25 · Regularny
  ["Jeźdź 2 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(2, 4)],
  ["Wykonaj podstawowy program ujeżdżeniowy (koło, serpentyna)", undefined, prog("technika", 8)],
  ["Pokonaj przeszkodę 60 cm", undefined, prog("skoki", 60)],
  ["Przejedź szereg 3 przeszkód (parkur podstawowy)", undefined, prog("technika", 9)],
  ["Wystartuj w pierwszych zawodach towarzyskich", undefined, prog("liga", 1)],
  ["Pokonaj przeszkodę 70 cm", undefined, prog("skoki", 70)],
  ["Wykonaj ustąpienie od łydki (leg yield)", undefined, prog("technika", 10)],
  ["Ukończ parkur bez punktów karnych (klasa LL)"],
  ["Pokonaj przeszkodę 80 cm", undefined, prog("skoki", 80)],
  ["Zdobądź srebrną odznakę jeździecką", undefined, prog("technika", 11)],
  ["Pokonaj przeszkodę 90 cm", undefined, prog("skoki", 90)],
  ["Wykonaj poprawny program ujeżdżeniowy klasy L", undefined, prog("technika", 12)],
  ["Ukończ parkur klasy L czysto", undefined, prog("liga", 2)],
  ["Pokonaj przeszkodę 100 cm", "Metrowa przeszkoda.", prog("skoki", 100)],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  // 26-45 · Średniozaawansowany
  ["Jeźdź 3-4 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(4, 12)],
  ["Pokonaj przeszkodę 110 cm", undefined, prog("skoki", 110)],
  ["Wykonaj wolty i przejścia w programie klasy P", undefined, prog("technika", 13)],
  ["Ukończ parkur klasy P czysto", undefined, prog("liga", 3)],
  ["Pokonaj przeszkodę 115 cm", undefined, prog("skoki", 115)],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Pokonaj przeszkodę 120 cm", undefined, prog("skoki", 120)],
  ["Wykonaj kontrgalop i przejścia w kontrze", undefined, prog("technika", 14)],
  ["Ukończ WKKW (ujeżdżenie + krosowy + parkur) na poziomie podstawowym"],
  ["Pokonaj przeszkodę 125 cm", undefined, prog("skoki", 125)],
  ["Wykonaj program ujeżdżeniowy klasy N", undefined, prog("technika", 15)],
  ["Pokonaj przeszkodę 130 cm", undefined, prog("skoki", 130)],
  ["Ukończ parkur klasy N czysto", undefined, prog("liga", 4)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw okręgu"],
  ["Pokonaj przeszkodę 135 cm", undefined, prog("skoki", 135)],
  ["Wykonaj półprzejścia i wydłużenia chodów", undefined, prog("technika", 16)],
  ["Pokonaj przeszkodę 140 cm", undefined, prog("skoki", 140)],
  ["Ukończ trudny parkur (klasa C) z dobrym czasem"],
  ["Zdobądź minimum na mistrzostwa kraju (kategoria)"],
  ["Pokonaj przeszkodę 145 cm", undefined, prog("skoki", 145)],
  // 46-65 · Zaawansowany
  ["Trenuj na poziomie zawodniczym z trenerem przez sezon"],
  ["Wykonaj program ujeżdżeniowy klasy C (piruety, zmiany nogi)", undefined, prog("technika", 17)],
  ["Zajmij miejsce w czołówce mistrzostw okręgu"],
  ["Pokonaj przeszkodę 150 cm", "Poziom Grand Prix wchodzi w grę.", prog("skoki", 150)],
  ["Zdobądź medal mistrzostw okręgu"],
  ["Ukończ parkur klasy CC czysto", undefined, prog("liga", 5)],
  ["Wykonaj zmiany nogi co 4 tempa (ujeżdżenie)", undefined, prog("technika", 18)],
  ["Pokonaj przeszkodę 155 cm", undefined, prog("skoki", 155)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju"],
  ["Ukończ WKKW na poziomie CCI2*"],
  ["Wykonaj pasaż i piaff (ujeżdżenie klasy CC/Grand Prix)", undefined, prog("technika", 19)],
  ["Pokonaj przeszkodę 160 cm", "Wysokość Pucharu Świata w skokach.", prog("skoki", 160)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Ukończ program ujeżdżeniowy Grand Prix", undefined, prog("technika", 20)],
  ["Zostań mistrzem kraju w swojej konkurencji"],
  ["Ukończ WKKW na poziomie CCI3*"],
  ["Pokonaj przeszkodę 165 cm", undefined, prog("skoki", 165)],
  ["Wystartuj w zawodach międzynarodowych CSI/CDI", undefined, prog("liga", 6)],
  ["Zajmij miejsce w pierwszej połowie konkursu międzynarodowego"],
  ["Uzyskaj wynik kwalifikujący do rankingu międzynarodowego"],
  // 66-85 · Wyczynowy
  ["Zdobądź punkty w rankingu światowym FEI"],
  ["Pokonaj przeszkodę 170 cm", undefined, prog("skoki", 170)],
  ["Wygraj konkurs międzynarodowy CSI1*/2*"],
  ["Zajmij miejsce w pierwszej dziesiątce konkursu CSI/CDI"],
  ["Wykonaj program Grand Prix Special na wysokim poziomie", undefined, prog("technika", 21)],
  ["Ukończ WKKW na wysokim poziomie krajowym"],
  ["Zajmij miejsce na podium konkursu o zasięgu ogólnokrajowym"],
  ["Pokonaj przeszkodę 175 cm", undefined, prog("skoki", 175)],
  ["Weź udział w mistrzostwach regionu"],
  ["Zajmij miejsce w pierwszej połowie mistrzostw regionu"],
  ["Wygraj Grand Prix wysokiej rangi krajowej", undefined, prog("liga", 7)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw regionu"],
  ["Wykonaj freestyle (kür) ujeżdżeniowy na bardzo wysokim poziomie", undefined, prog("technika", 22)],
  ["Ukończ WKKW na wymagającym, znanym poziomie krajowym"],
  ["Zdobądź medal mistrzostw regionu"],
  ["Osiągnij czołową 30 rankingu krajowego"],
  ["Wygraj Grand Prix rangi krajowej"],
  ["Zakwalifikuj się do finału zawodów o zasięgu ogólnokrajowym"],
  ["Zajmij miejsce w pierwszej dziesiątce finału zawodów ogólnokrajowych"],
  ["Pokonaj przeszkodę 180 cm", undefined, prog("skoki", 180)],
  // 86-99 · Elita
  ["Zdobądź medal finału zawodów o zasięgu ogólnokrajowym"],
  ["Osiągnij czołową 15 rankingu krajowego"],
  ["Wygraj Grand Prix najwyższej rangi krajowej"],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju amatorów"],
  ["Osiągnij czołową piątkę rankingu krajowego"],
  ["Zdobądź medal mistrzostw kraju amatorów"],
  ["Wygraj finał zawodów o zasięgu ogólnokrajowym"],
  ["Zdobądź złoto mistrzostw regionu"],
  ["Zostań numerem 1 rankingu krajowego"],
  ["Poprowadź kogoś przez zaawansowaną jazdę i skoki"],
  ["Zdobądź uznanie w krajowym środowisku jeździeckim"],
  ["Zdobądź wielokrotne medale mistrzostw kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat jeździecki", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, igrzyska) potwierdzają osobne certyfikaty."],
]);
