// Judo ladder 1-99. Manual — progression tracks: belt/grade (kyu → dan),
// technique, contests, and competition level.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "judo",
  name: "Judo",
  icon: "🥋",
  description:
    "Japońska „łagodna droga” — rzuty, dźwignie i trzymania. Progresja: stopnie (pas), technika, walki i poziom zawodów.",
  sortOrder: 68,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj upadki (ukemi) w każdą stronę", undefined, prog("technika", 1)],
  ["Wykonaj poprawny chwyt (kumi-kata) i postawę", undefined, prog("technika", 2)],
  ["Wykonaj pierwszy rzut (o-goshi lub o-soto-gari)", undefined, prog("technika", 3)],
  ["Zdobądź pas biały-żółty (6 kyu)", undefined, prog("pas", 1)],
  ["Wykonaj trzymanie (osaekomi) i utrzymaj 20 s", undefined, prog("technika", 4)],
  ["Zdobądź pas żółty (5 kyu)", undefined, prog("pas", 2)],
  ["Wykonaj rzut z pełnym kuzushi (wytrąceniem równowagi)", undefined, prog("technika", 5)],
  ["Odbądź pierwsze randori (walkę treningową)", undefined, prog("walki", 1)],
  ["Zdobądź pas pomarańczowy (4 kyu)", undefined, prog("pas", 3)],
  ["Wykonaj 5 różnych rzutów poprawnie", undefined, prog("technika", 6)],
  // 11-25 · Regularny
  ["Trenuj 2 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(2, 4)],
  ["Wykonaj kombinację rzutów (renraku)", undefined, prog("technika", 7)],
  ["Zdobądź pas zielony (3 kyu)", undefined, prog("pas", 4)],
  ["Odbądź 10 walk randori", undefined, prog("walki", 10)],
  ["Wykonaj dźwignię na ramię (ude-garami) lub duszenie", undefined, prog("technika", 8)],
  ["Wystartuj w pierwszych zawodach", undefined, prog("liga", 1)],
  ["Zdobądź pas niebieski (2 kyu)", undefined, prog("pas", 5)],
  ["Wygraj pierwszą walkę na zawodach"],
  ["Wykonaj ippon (rzut na plecy) w walce", undefined, prog("technika", 9)],
  ["Odbądź 25 walk", undefined, prog("walki", 25)],
  ["Zdobądź pas brązowy (1 kyu)", undefined, prog("pas", 6)],
  ["Opanuj przejście z rzutu do trzymania (ne-waza flow)", undefined, prog("technika", 10)],
  ["Odbądź 40 walk", undefined, prog("walki", 40)],
  ["Zajmij miejsce w pierwszej połowie turnieju"],
  ["Wykonaj kontratak (kaeshi-waza) w walce", undefined, prog("technika", 11)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 3 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Zdobądź pas czarny 1 dan (shodan)", "Kamień milowy każdego judoki.", prog("pas", 7)],
  ["Odbądź 60 walk", undefined, prog("walki", 60)],
  ["Opanuj tokui-waza (swoją technikę specjalną) na wysokim poziomie", undefined, prog("technika", 12)],
  ["Zajmij miejsce na podium turnieju regionalnego"],
  ["Odbądź 80 walk", undefined, prog("walki", 80)],
  ["Wykonaj dźwignię (armlock)/duszenie kończące walkę (ippon submission)", undefined, prog("technika", 13)],
  ["Zdobądź minimum na mistrzostwa okręgu", undefined, prog("liga", 2)],
  ["Odbądź 100 walk", undefined, prog("walki", 100)],
  ["Wygraj walkę z posiadaczem czarnego pasa"],
  ["Opanuj taktykę zdobywania i utrzymywania przewagi (shido management)", undefined, prog("technika", 14)],
  ["Odbądź 130 walk", undefined, prog("walki", 130)],
  ["Zajmij miejsce w czołówce mistrzostw okręgu"],
  ["Zdobądź pas czarny 2 dan (nidan)", undefined, prog("pas", 8)],
  ["Odbądź 160 walk", undefined, prog("walki", 160)],
  ["Wykonaj rzut o wysokiej trudności (uchi-mata, harai-goshi) w walce", undefined, prog("technika", 15)],
  ["Zdobądź minimum na mistrzostwa kraju", undefined, prog("liga", 3)],
  ["Odbądź 200 walk", undefined, prog("walki", 200)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju"],
  ["Zdobądź medal mistrzostw kraju juniorów"],
  // 46-65 · Zaawansowany
  ["Trenuj na wysokim poziomie klubowym przez cały sezon"],
  ["Zdobądź pas czarny 3 dan (sandan)", undefined, prog("pas", 9)],
  ["Odbądź 250 walk", undefined, prog("walki", 250)],
  ["Opanuj pełen arsenał rzutów w tachi-waza i ne-waza", undefined, prog("technika", 16)],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Wygraj walkę z czołowym zawodnikiem regionu"],
  ["Odbądź 300 walk", undefined, prog("walki", 300)],
  ["Zdobądź czołową pozycję w rankingu regionalnym", undefined, prog("liga", 4)],
  ["Utrzymaj wysoką skuteczność (ippon rate) w zawodach", undefined, prog("technika", 17)],
  ["Odbądź 350 walk", undefined, prog("walki", 350)],
  ["Wystartuj w turnieju międzynarodowym (Continental Open)"],
  ["Zdobądź medal na turnieju międzynarodowym"],
  ["Odbądź 400 walk", undefined, prog("walki", 400)],
  ["Zostań mistrzem kraju seniorów"],
  ["Wygraj walkę z zawodnikiem z rankingu światowego"],
  ["Zdobądź pas czarny 4 dan (yodan)", undefined, prog("pas", 10)],
  ["Odbądź 450 walk", undefined, prog("walki", 450)],
  ["Zdobądź punkty w rankingu światowym IJF", undefined, prog("liga", 5)],
  ["Zajmij miejsce w pierwszej ósemce turnieju Grand Prix"],
  ["Odbądź 500 walk", undefined, prog("walki", 500)],
  // 66-85 · Wyczynowy
  ["Zdobądź medal na turnieju o zasięgu ogólnokrajowym"],
  ["Odbądź 550 walk", undefined, prog("walki", 550)],
  ["Wygraj walkę z uznanym zawodnikiem krajowym"],
  ["Zdobądź medal na dużym turnieju o zasięgu ogólnokrajowym"],
  ["Odbądź 600 walk", undefined, prog("walki", 600)],
  ["Osiągnij czołową 30 rankingu krajowego"],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Odbądź 650 walk", undefined, prog("walki", 650)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju amatorów"],
  ["Utrzymaj wysoki poziom techniczny w swojej kategorii", undefined, prog("technika", 18)],
  ["Odbądź 700 walk", undefined, prog("walki", 700)],
  ["Zdobądź medal mistrzostw kraju amatorów"],
  ["Osiągnij czołową 15 rankingu krajowego"],
  ["Odbądź 750 walk", undefined, prog("walki", 750)],
  ["Weź udział w mistrzostwach kraju amatorów seniorów"],
  ["Wygraj duży turniej o zasięgu ogólnokrajowym"],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju amatorów seniorów"],
  ["Odbądź 800 walk", undefined, prog("walki", 800)],
  ["Osiągnij czołową ósemkę rankingu krajowego"],
  ["Zdobądź medal mistrzostw regionu w drugiej kategorii lub open"],
  // 86-99 · Elita
  ["Zdobądź medal mistrzostw kraju amatorów seniorów"],
  ["Osiągnij czołową piątkę rankingu krajowego"],
  ["Wygraj prestiżowy turniej o szerokim zasięgu"],
  ["Odbądź 900 walk", undefined, prog("walki", 900)],
  ["Zdobądź złoto mistrzostw regionu"],
  ["Poprowadź kogoś przez zaawansowaną technikę judo"],
  ["Zostań numerem 1 rankingu krajowego w swojej kategorii"],
  ["Zdobądź złoto mistrzostw kraju amatorów"],
  ["Zdobądź uznanie w krajowym środowisku judo"],
  ["Odbądź 1000 walk", undefined, prog("walki", 1000)],
  ["Poprowadź własny klub / grupę treningową przez dłuższy czas"],
  ["Zdobądź wielokrotne mistrzostwo kraju amatorów"],
  ["Zdobądź pas czarny wysokiego dan (5-6 dan) za dorobek", undefined, prog("pas", 11)],
  ["Poziom mistrzowski (amatorski szczyt): wielokrotny mistrz kraju amatorów w judo", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, igrzyska) potwierdzają osobne certyfikaty."],
]);

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  // — Rozszerzenie zasobów Tier 1 (wszystkie linki zweryfikowane jako aktywne) —
  2: [{ kind: "video", title: "Kumi-kata — walka o chwyt i prawidłowa postawa", url: yt("X0LZjkvdw3U") }],
  4: [{ kind: "article", title: "Pas biały-żółty (6 kyu) — czego wymaga egzamin na stopień", url: "https://www.britishjudo.org.uk/get-started/grading/kyu-grade-scheme/" }],
  5: [{ kind: "video", title: "Kesa-gatame — trzymanie (osaekomi) według Kodokanu", url: yt("NDaQuJOFBYk") }],
  8: [{ kind: "video", title: "Pierwsze randori — jak zacząć walkę treningową", url: yt("6wV7LtomHgE") }],
  10: [{ kind: "video", title: "Podstawowe rzuty judo dla początkujących + kombinacje", url: yt("9Dca30IZRe0") }],
  14: [{ kind: "article", title: "Randori — 8 najczęstszych błędów w sparingu", url: "https://kljudo.com/common-mistakes-in-randori/" }],
  18: [{ kind: "article", title: "Pierwsze zawody — jak wygrać swoją walkę", url: "https://onlyjudo.com/tips-for-your-very-first-judo-competition/" }],
  25: [{ kind: "article", title: "Kaeshi-waza — o-soto-gaeshi, kontra na o-soto-gari", url: "https://judoinfo.com/osoto-gaeshi/" }],
  35: [{ kind: "article", title: "Jak pokonać lepszego rywala — taktyka na macie", url: "https://sports-star.co.uk/tips-and-tricks-on-how-to-beat-an-opponent-in-judo/" }],
  65: [{ kind: "video", title: "Trening siłowy dla judoki — całe ciało", url: yt("9ixcPNodxzo") }],
  80: [{ kind: "article", title: "Zorganizuj randori i wykorzystaj pełny potencjał", url: "https://judotraining.info/organize-your-randori-training-and-reach-your-full-potential/" }],
  1: [
    { kind: "video", title: "Ukemi — How to Fall Safely — Shintaro Higashi", url: yt("KFrdOCp2cHE") },
    { kind: "article", title: "Judo basics for beginners", url: "https://www.wikihow.com/Do-Judo" },
  ],
  3: [
    { kind: "video", title: "O-Goshi (hip throw) Tutorial — Matt D'Aquino", url: yt("g_bh_hPqFrE") },
  ],
  7: [
    { kind: "video", title: "Kuzushi — Breaking Balance — Shintaro Higashi", url: yt("69rFJSaZ4gM") },
  ],
  12: [
    { kind: "video", title: "Renraku-Waza — Combination Throws", url: yt("Xvq1hUxfNBo") },
  ],
  15: [
    { kind: "video", title: "Arm Lock & Choke Fundamentals — Matt D'Aquino", url: yt("VIU_h2JJWlo") },
    { kind: "article", title: "Guide to judo ne-waza ground techniques", url: "https://www.verywellfit.com/judo-techniques-guide-3498361" },
  ],
  22: [
    { kind: "video", title: "Ne-Waza Flow: Throw to Pin — Shintaro Higashi", url: yt("WjKFgpHi1S4") },
  ],
  27: [
    { kind: "article", title: "Shodan: your first black belt in judo", url: "https://www.breakingmuscle.com/judo-black-belt-guide/" },
  ],
  41: [
    { kind: "video", title: "Uchi-Mata & Harai-Goshi Masterclass", url: yt("jVxSBBP82kQ") },
  ],
  55: [
    { kind: "reference", title: "IJF Sport & Organisation Rules", url: "https://www.ijf.org/sor" },
  ],
  92: [
    { kind: "video", title: "Judo Coaching & Teaching Philosophy — Shintaro Higashi", url: yt("Q5R5DQmL4U8") },
  ],
};
