// Calligraphy ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, counts scaled; top tiers reframed as attainable
// mastery, real feats left to future certificates).
// Tracks: umiejetnosci, prace (finished pieces), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "kaligrafia",
  name: "Kaligrafia",
  icon: "🖋️",
  description:
    "Sztuka pięknego pisma — kreski, litery, style, kompozycja. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → zlecenia i wystawy → dojrzały, autorski charakter pisma.",
  sortOrder: 84,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Poznaj narzędzia (stalówka, pędzelek, papier, atrament)", undefined, prog("umiejetnosci", 1)],
  ["Opanuj podstawowe kreski (cienkie w górę, grube w dół)", undefined, prog("umiejetnosci", 2)],
  ["Utrzymaj stały kąt i nacisk narzędzia", undefined, prog("umiejetnosci", 3)],
  ["Napisz drobne litery jednego stylu (minuskuła)", undefined, prog("umiejetnosci", 4)],
  ["Zachowaj równe odstępy i wysokość liter (liniatura)", undefined, prog("umiejetnosci", 5)],
  ["Napisz pierwsze słowo z połączeniami liter", undefined, prog("umiejetnosci", 6)],
  ["Ukończ pierwszą kompozycję (krótki cytat)", undefined, prog("prace", 3)],
  ["Napisz wielkie litery (majuskuła) jednego stylu", undefined, prog("umiejetnosci", 7)],
  ["Ukończ 10 prac", undefined, prog("prace", 10)],
  ["Ćwicz kaligrafię łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Ćwicz kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Opanuj pełny alfabet jednego stylu (np. italika)", undefined, prog("umiejetnosci", 8)],
  ["Zachowaj rytm i spójność w dłuższym tekście", undefined, prog("umiejetnosci", 9)],
  ["Napisz akapit tekstu równo i czytelnie", undefined, prog("prace", 20)],
  ["Opanuj drugi styl pisma (np. foundational / uncjała)", undefined, prog("umiejetnosci", 10)],
  ["Ćwicz kaligrafię łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Zaplanuj układ kartki (marginesy, wyśrodkowanie)", undefined, prog("umiejetnosci", 11)],
  ["Ukończ 35 prac", undefined, prog("prace", 35)],
  ["Napisz kaligrafię pędzelkową (brush lettering)", undefined, prog("umiejetnosci", 12)],
  ["Dobierz atrament i papier do efektu (tusze, kolory)", undefined, prog("umiejetnosci", 13)],
  ["Wykonaj ozdobne zakończenia liter (podstawy flourishy)", undefined, prog("umiejetnosci", 14)],
  ["Ćwicz kaligrafię łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Napisz zaproszenie / adres na kopercie", undefined, prog("prace", 55)],
  ["Opanuj trzeci styl pisma", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 60 prac", undefined, prog("prace", 60)],
  // 26-45 · Średniozaawansowany
  ["Ćwicz regularnie przez 8 kolejnych tygodni", undefined, freq(3, 8)],
  ["Opanuj copperplate / spencerian (pismo pochyłe cienkie-grube)", undefined, prog("umiejetnosci", 16)],
  ["Zbuduj złożoną, spójną kompozycję tekstową", undefined, prog("umiejetnosci", 17)],
  ["Ukończ 90 prac", undefined, prog("prace", 90)],
  ["Opanuj rozbudowane flourishe i ornamenty", undefined, prog("umiejetnosci", 18)],
  ["Ćwicz kaligrafię łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Łącz kaligrafię z ilustracją / dekoracją", undefined, prog("umiejetnosci", 19)],
  ["Opanuj kompozycję plakatu / dużego formatu", undefined, prog("umiejetnosci", 20)],
  ["Ukończ 130 prac", undefined, prog("prace", 130)],
  ["Pisz złocenia / efekty specjalne (gilding, metaliki)", undefined, prog("umiejetnosci", 21)],
  ["Zaprojektuj spójny zestaw (zaproszenie + dodatki)", undefined, prog("umiejetnosci", 22)],
  ["Ćwicz kaligrafię łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Zrealizuj serię prac o wspólnym motywie", undefined, prog("prace", 170)],
  ["Opanuj kaligrafię jako kompozycję artystyczną (nie tylko tekst)", undefined, prog("umiejetnosci", 23)],
  ["Zbuduj dopracowaną, „wystawową” pracę", undefined, prog("umiejetnosci", 24)],
  ["Ukończ 200 prac", undefined, prog("prace", 200)],
  ["Opanuj wybrane pismo historyczne na wysokim poziomie", undefined, prog("umiejetnosci", 25)],
  ["Ćwicz kaligrafię łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Wykonaj dużą, ozdobną kompozycję kaligraficzną", undefined, prog("umiejetnosci", 26)],
  ["Prowadź praktykę regularnie przez 3 miesiące", undefined, prog("prace", 250)],
  // 46-65 · Zaawansowany (amator)
  ["Ćwicz regularnie przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Wypracuj rozpoznawalny, osobisty charakter pisma", undefined, prog("umiejetnosci", 27)],
  ["Zbuduj spójną serię tematyczną prac", undefined, prog("umiejetnosci", 28)],
  ["Ukończ 300 prac", undefined, prog("prace", 300)],
  ["Ćwicz kaligrafię łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Pokaż prace publicznie i zbierz opinie odbiorców"],
  ["Zrealizuj ambitną, złożoną kompozycję kaligraficzną", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 380 prac", undefined, prog("prace", 380)],
  ["Opanuj świadome łamanie zasad (ekspresja, styl własny)", undefined, prog("umiejetnosci", 30)],
  ["Ćwicz kaligrafię łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj portfolio najlepszych prac"],
  ["Weź udział w wystawie zbiorowej lub konkursie"],
  ["Realizuj zlecenia (zaproszenia, dyplomy, logotypy pisane)", undefined, prog("umiejetnosci", 31)],
  ["Ukończ 450 prac", undefined, prog("prace", 450)],
  ["Sprzedaj pracę / zrealizuj większe zamówienie", undefined, prog("umiejetnosci", 32)],
  ["Ćwicz kaligrafię łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy kaligrafii", undefined, prog("umiejetnosci", 33)],
  ["Zrealizuj spójny cykl prac wokół jednego pomysłu"],
  ["Wykonaj „galeryjną” pracę na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 550 prac", undefined, prog("prace", 550)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Ćwicz regularnie przez pełny sezon (6 miesięcy)"],
  ["Pisz swobodnie w wielu stylach na wysokim poziomie", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 650 prac", undefined, prog("prace", 650)],
  ["Ćwicz kaligrafię łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zorganizuj małą wystawę indywidualną (lokalnie / online)"],
  ["Rozwiń warsztat na tyle, by uczyć kaligrafii", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie realizujesz zlecenia kaligraficzne"],
  ["Opanuj wybraną specjalizację (copperplate / brush / gotyk)", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 800 prac", undefined, prog("prace", 800)],
  ["Zdobądź wyróżnienie w konkursie lub uznanie w społeczności"],
  ["Ćwicz kaligrafię łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny, wieloczęściowy projekt autorski", undefined, prog("umiejetnosci", 38)],
  ["Twoje pismo jest dojrzałe i rozpoznawalne", undefined, prog("umiejetnosci", 39)],
  ["Ukończ 1000 prac", undefined, prog("prace", 1000)],
  ["Zbuduj grono odbiorców swojej twórczości"],
  ["Poprowadź warsztaty lub mentoring dla piszących"],
  ["Projektuj własne kroje / litery inspirowane kaligrafią"],
  ["Zrealizuj wystawę prezentującą Twój dorobek"],
  ["Ukończ 1200 prac", undefined, prog("prace", 1200)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Ćwicz kaligrafię łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdej pracy"],
  ["Ukończ 1400 prac", undefined, prog("prace", 1400)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych piszących w Twoim otoczeniu"],
  ["Wykonaj osobisty „opus” — dużą, dopracowaną kompozycję", undefined, prog("umiejetnosci", 40)],
  ["Regularnie wystawiasz swoje prace"],
  ["Ćwicz kaligrafię łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje prace zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 1600 prac", undefined, prog("prace", 1600)],
  ["Uczysz i kształtujesz kolejnych kaligrafów"],
  ["Masz dorobek, z którego można ułożyć wystawę retrospektywną"],
  ["Piszesz pięknie w każdym stylu, jaki sobie wybierzesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski warsztat", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones. Videos from Maria Montes, Loveleigh Loops, Domestika i in.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [
    { kind: "video", title: "Narzędzia: stalówki, atrament, papier", url: yt("GLZp2Os1py4") },
    { kind: "article", title: "Kaligrafia dla początkujących — co kupić na start", url: "https://www.jetpens.com/blog/The-Beginners-Guide-to-Calligraphy/pt/592" },
  ],
  2: [{ kind: "video", title: "Podstawowe kreski (drills)", url: yt("8e9HHz6j3lA") }],
  5: [{ kind: "video", title: "Jak trzymać stalówkę — kąt i nacisk", url: yt("sB4x1HfCkP0") }],
  8: [{ kind: "video", title: "Małe litery — ćwiczenia alfabetyczne", url: yt("MN-WS4a_Gu0") }],
  12: [{ kind: "video", title: "Alfabet italika — wprowadzenie", url: yt("BFW1N4yCTXw") }],
  15: [{ kind: "video", title: "Pismo foundational — podstawy", url: yt("mj1DLCWoEPI") }],
  19: [{ kind: "video", title: "Brush lettering — kreski", url: yt("9fmjCi6Cb_o") }],
  21: [{ kind: "video", title: "Flourishe — jak zacząć", url: yt("xJbklrucYbc") }],
  27: [{ kind: "video", title: "Copperplate dla początkujących", url: yt("uasWncPctnY") }],
  35: [{ kind: "video", title: "Złocenia (gold leaf)", url: yt("69vllqd_iTw") }],
  45: [{ kind: "article", title: "Kompozycja kaligraficzna — layout i marginesy", url: "https://www.calligraphy-skills.com/calligraphy-layout.html" }],
  60: [{ kind: "video", title: "Spencerian script — klasyka amerykańska", url: yt("BFNBiQ3lxVM") }],
};
