// Karting ladder 1-99. Manual — progression tracks: technique, races, and
// competition level (club → national → international → path to single-seaters).
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "karting",
  name: "Karting",
  icon: "🏎️",
  description:
    "Przedsionek sportów wyścigowych — gokarty na torze. Progresja: technika jazdy, wyścigi i poziom rywalizacji (klub → mistrzostwa świata).",
  sortOrder: 75,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Przejedź okrążenie toru kartingowego pewnie", undefined, prog("technika", 1)],
  ["Opanuj prawidłową pozycję za kierownicą i chwyt", undefined, prog("technika", 2)],
  ["Hamuj i przyspieszaj płynnie na prostych", undefined, prog("technika", 3)],
  ["Pokonaj zakręt po prawidłowej linii (apex)", undefined, prog("technika", 4)],
  ["Utrzymaj równe okrążenia (powtarzalność czasów)", undefined, prog("technika", 5)],
  ["Wykonaj wyprzedzanie na torze treningowym", undefined, prog("technika", 6)],
  ["Popraw swój czas okrążenia o 2 sekundy względem pierwszego", undefined, prog("technika", 7)],
  ["Weź udział w pierwszym wyścigu amatorskim (arrive-and-drive)", undefined, prog("wyscigi", 1)],
  ["Opanuj start z pozycji i pierwszy zakręt", undefined, prog("technika", 8)],
  ["Ukończ 3 wyścigi", undefined, prog("wyscigi", 3)],
  // 11-25 · Regularny
  ["Jeźdź lub ścigaj się raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Opanuj trail braking (hamowanie do zakrętu)", undefined, prog("technika", 9)],
  ["Ukończ 6 wyścigów", undefined, prog("wyscigi", 6)],
  ["Zdobądź licencję kartingową (krajowa)", undefined, prog("liga", 1)],
  ["Utrzymaj czoło stawki przez cały wyścig", undefined, prog("technika", 10)],
  ["Ukończ 10 wyścigów", undefined, prog("wyscigi", 10)],
  ["Wygraj pierwszy wyścig amatorski"],
  ["Opanuj jazdę w deszczu (mokra linia)", undefined, prog("technika", 11)],
  ["Ukończ 20 wyścigów", undefined, prog("wyscigi", 20)],
  ["Ustaw kartę (setup) pod tor i warunki", undefined, prog("technika", 12)],
  ["Wystartuj w klubowych mistrzostwach", undefined, prog("liga", 2)],
  ["Ukończ 30 wyścigów", undefined, prog("wyscigi", 30)],
  ["Zajmij miejsce w pierwszej połowie wyścigu rangi klubowej"],
  ["Opanuj obronę pozycji i czystą walkę koło w koło", undefined, prog("technika", 13)],
  ["Ukończ 45 wyścigów", undefined, prog("wyscigi", 45)],
  // 26-45 · Średniozaawansowany
  ["Trenuj i ścigaj się systematycznie przez sezon", undefined, freq(2, 12)],
  ["Zajmij miejsce na podium wyścigu klubowego"],
  ["Ukończ 60 wyścigów", undefined, prog("wyscigi", 60)],
  ["Opanuj optymalizację czasu okrążenia (qualifying pace)", undefined, prog("technika", 14)],
  ["Zdobądź pole position w kwalifikacjach", undefined, prog("technika", 15)],
  ["Ukończ 80 wyścigów", undefined, prog("wyscigi", 80)],
  ["Wygraj wyścig w klubowych mistrzostwach"],
  ["Awansuj do wyższej klasy sprzętowej (np. Rotax/OK)", undefined, prog("liga", 3)],
  ["Ukończ 100 wyścigów", undefined, prog("wyscigi", 100)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw okręgu/strefy"],
  ["Opanuj zarządzanie oponami i tempem w długim wyścigu", undefined, prog("technika", 16)],
  ["Ukończ 130 wyścigów", undefined, prog("wyscigi", 130)],
  ["Zdobądź podium w mistrzostwach strefowych"],
  ["Ustaw rekordowy czas okrążenia na znanym torze", undefined, prog("technika", 17)],
  ["Ukończ 160 wyścigów", undefined, prog("wyscigi", 160)],
  ["Zdobądź minimum na mistrzostwa kraju", undefined, prog("liga", 4)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju"],
  ["Ukończ 200 wyścigów", undefined, prog("wyscigi", 200)],
  ["Wygraj wyścig w mistrzostwach kraju"],
  ["Zdobądź medal mistrzostw kraju"],
  // 46-65 · Zaawansowany
  ["Trenuj z zespołem/inżynierem przez cały sezon"],
  ["Opanuj perfekcyjną powtarzalność na poziomie 0,1 s", undefined, prog("technika", 18)],
  ["Zostań mistrzem kraju w swojej klasie"],
  ["Ukończ 250 wyścigów", undefined, prog("wyscigi", 250)],
  ["Zdobądź pole position w mistrzostwach kraju"],
  ["Wystartuj w zawodach międzynarodowych (WSK / seria europejska)", undefined, prog("liga", 5)],
  ["Zajmij miejsce w pierwszej połowie zawodów międzynarodowych"],
  ["Ukończ 300 wyścigów", undefined, prog("wyscigi", 300)],
  ["Opanuj taktykę slipstreamu i wyścigów pack racing", undefined, prog("technika", 19)],
  ["Zakwalifikuj się do finału zawodów międzynarodowych"],
  ["Zajmij miejsce w pierwszej dziesiątce zawodów międzynarodowych"],
  ["Ukończ 350 wyścigów", undefined, prog("wyscigi", 350)],
  ["Zdobądź punkty w mistrzostwach Europy CIK-FIA"],
  ["Wygraj heat w zawodach o zasięgu ogólnokrajowym"],
  ["Ukończ 400 wyścigów", undefined, prog("wyscigi", 400)],
  ["Zdobądź uznanie w silnym zespole kartingowym", undefined, prog("liga", 6)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw regionu"],
  ["Opanuj jazdę na wysokim poziomie w każdych warunkach", undefined, prog("technika", 20)],
  ["Ukończ 450 wyścigów", undefined, prog("wyscigi", 450)],
  ["Zdobądź podium w rundzie mistrzostw regionu"],
  // 66-85 · Wyczynowy
  ["Zdobądź medal mistrzostw regionu"],
  ["Ukończ 500 wyścigów", undefined, prog("wyscigi", 500)],
  ["Wygraj rundę mistrzostw regionu"],
  ["Zajmij miejsce w pierwszej piętnastce mistrzostw kraju amatorów"],
  ["Ustaw swój rekord życiowy okrążenia w rundzie o zasięgu ogólnokrajowym", undefined, prog("technika", 21)],
  ["Ukończ 600 wyścigów", undefined, prog("wyscigi", 600)],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju amatorów"],
  ["Zdobądź uznanie jako obiecujący kierowca", undefined, prog("liga", 7)],
  ["Ukończ 700 wyścigów", undefined, prog("wyscigi", 700)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju amatorów"],
  ["Wygraj heat na mistrzostwach kraju amatorów"],
  ["Zdobądź pole position na zawodach o zasięgu ogólnokrajowym"],
  ["Ukończ 800 wyścigów", undefined, prog("wyscigi", 800)],
  ["Zajmij miejsce w pierwszej piątce mistrzostw kraju amatorów"],
  ["Weź udział w otwartym naborze / testach dla utalentowanych kierowców"],
  ["Zdobądź podium mistrzostw kraju amatorów"],
  ["Osiągnij status uznanego kartingowca w kraju", undefined, prog("technika", 22)],
  ["Ukończ 900 wyścigów", undefined, prog("wyscigi", 900)],
  ["Zdobądź srebro lub brąz mistrzostw kraju amatorów"],
  // 86-99 · Elita
  ["Awansuj do finału mistrzostw kraju amatorów"],
  ["Ustanów swój rekord toru na lokalnym obiekcie", undefined, prog("technika", 23)],
  ["Wygraj rundę mistrzostw kraju amatorów"],
  ["Zdobądź złoto mistrzostw kraju amatorów w kartingu"],
  ["Ukończ 1000 wyścigów", undefined, prog("wyscigi", 1000)],
  ["Obroń tytuł mistrza kraju amatorów w kartingu"],
  ["Poprowadź kogoś przez zaawansowaną technikę jazdy wyścigowej"],
  ["Zdobądź uznanie w krajowym środowisku kartingowym"],
  ["Zostań instruktorem jazdy wyścigowej / kartingowej"],
  ["Wygraj prestiżowy turniej kartingowy o szerokim zasięgu"],
  ["Utrzymuj wieloletnią, wysoką formę w krajowych zawodach"],
  ["Zdobądź wielokrotne mistrzostwo kraju amatorów"],
  ["Wygraj najbardziej prestiżowy krajowy turniej kartingowy"],
  ["Poziom mistrzowski (amatorski szczyt): wielokrotny mistrz kraju amatorów w kartingu", "Dalsze, zawodowe osiągnięcia (sport formułowy, F1) potwierdzają osobne certyfikaty."],
]);
