// Kitesurfing ladder 1-99. Manual — progression tracks: skill line (kite
// control → bodydrag → waterstart → upwind → jumps → loops → kiteloops → big
// air), airtime/height, and competition level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kitesurfing",
  name: "Kitesurfing",
  icon: "🪁",
  description:
    "Latawiec i deska — od sterowania kite na lądzie po big air i kiteloopy. Progresja: umiejętności, wysokość skoku i poziom zawodów.",
  sortOrder: 48,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Steruj latawcem treningowym na lądzie", undefined, prog("technika", 1)],
  ["Wykonaj relaunch (start latawca z wody)", undefined, prog("technika", 2)],
  ["Opanuj strefę mocy i strefę neutralną kite'a", undefined, prog("technika", 3)],
  ["Wykonaj bodydrag (ciągnięcie w wodzie bez deski)", undefined, prog("technika", 4)],
  ["Wykonaj bodydrag pod wiatr (odzyskiwanie deski)", undefined, prog("technika", 5)],
  ["Wykonaj waterstart — wstań na desce", "Pierwsze płynięcie.", prog("technika", 6)],
  ["Przepłyń kilka metrów na desce w jedną stronę", undefined, prog("technika", 7)],
  ["Płyń w obie strony (obie halsy)", undefined, prog("technika", 8)],
  ["Zatrzymaj się i wystartuj ponownie kontrolowanie", undefined, prog("technika", 9)],
  ["Popływaj łącznie 10 godzin na wodzie", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Pływaj raz w tygodniu przez 4 tygodnie w sezonie", undefined, freq(1, 4)],
  ["Płyń pod wiatr (upwind) — wracaj do punktu startu", "Niezależność na wodzie.", prog("technika", 10)],
  ["Wykonaj podstawowy zwrot (toeside lub przez halsy)", undefined, prog("technika", 11)],
  ["Utrzymaj płynięcie przy wietrze 4-5°B", undefined, prog("technika", 12)],
  ["Popływaj łącznie 30 godzin", undefined, prog("godziny", 30)],
  ["Płyń na krawędzi (edging) budując napęd", undefined, prog("technika", 13)],
  ["Wykonaj pierwszy mały skok (pop) z wody", undefined, prog("wysokosc", 1)],
  ["Wykonaj transition jibe (zwrot ze skokiem/przełożeniem)", undefined, prog("technika", 14)],
  ["Skocz i utrzymaj się w powietrzu 1 sekundę", undefined, prog("wysokosc", 2)],
  ["Popływaj łącznie 60 godzin", undefined, prog("godziny", 60)],
  ["Wykonaj kontrolowany skok z wyciągnięciem kite'a (send)", undefined, prog("technika", 15)],
  ["Skocz na wysokość ~2 m", undefined, prog("wysokosc", 3)],
  ["Płyń toeside pewnie w obie strony", undefined, prog("technika", 16)],
  ["Wystartuj w pierwszych zawodach lub jam session"],
  ["Skocz na wysokość ~3 m", undefined, prog("wysokosc", 4)],
  // 26-45 · Średniozaawansowany
  ["Pływaj regularnie przez cały sezon (2×/tydz.)", undefined, freq(2, 12)],
  ["Wykonaj grab (chwyt deski) w skoku", undefined, prog("technika", 17)],
  ["Skocz na wysokość ~4 m", undefined, prog("wysokosc", 5)],
  ["Popływaj łącznie 100 godzin", undefined, prog("godziny", 100)],
  ["Wykonaj backroll (rotacja w tył)", undefined, prog("technika", 18)],
  ["Skocz na wysokość ~5 m", undefined, prog("wysokosc", 6)],
  ["Wykonaj frontroll (rotacja w przód)", undefined, prog("technika", 19)],
  ["Skocz na wysokość ~6 m", undefined, prog("wysokosc", 7)],
  ["Popływaj łącznie 150 godzin", undefined, prog("godziny", 150)],
  ["Wykonaj backroll z grabem", undefined, prog("technika", 20)],
  ["Skocz na wysokość ~7 m", undefined, prog("wysokosc", 8)],
  ["Wykonaj downloop transition (zwrot z pętlą kite'a)", undefined, prog("technika", 21)],
  ["Skocz na wysokość ~8 m", undefined, prog("wysokosc", 9)],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  ["Wykonaj S-bend lub inny obrót z przechwytem", undefined, prog("technika", 22)],
  ["Skocz na wysokość ~9 m", undefined, prog("wysokosc", 10)],
  ["Popływaj łącznie 250 godzin", undefined, prog("godziny", 250)],
  ["Wykonaj pierwszego kiteloopa (pętla kite'a w skoku) — próba", undefined, prog("technika", 23)],
  ["Skocz na wysokość ~10 m", undefined, prog("wysokosc", 11)],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  // 46-65 · Zaawansowany
  ["Pływaj intensywnie przez cały sezon"],
  ["Wykonaj czystego kiteloopa z lądowaniem", "Pętla latawca — poziom zaawansowany.", prog("technika", 24)],
  ["Skocz na wysokość ~12 m", undefined, prog("wysokosc", 12)],
  ["Popływaj łącznie 400 godzin", undefined, prog("godziny", 400)],
  ["Wykonaj megaloop (kiteloop z dużym wybiciem)", undefined, prog("technika", 25)],
  ["Skocz na wysokość ~14 m", undefined, prog("wysokosc", 13)],
  ["Wykonaj element unhooked (wypięty z trapezu) — raley", undefined, prog("technika", 26)],
  ["Skocz na wysokość ~16 m", undefined, prog("wysokosc", 14)],
  ["Popływaj łącznie 600 godzin", undefined, prog("godziny", 600)],
  ["Wykonaj handle pass (przełożenie drążka za plecami)", undefined, prog("technika", 27)],
  ["Skocz na wysokość ~18 m", undefined, prog("wysokosc", 15)],
  ["Zajmij miejsce w czołówce zawodów krajowych"],
  ["Wykonaj S-bend to blind lub inny trik z handle pass", undefined, prog("technika", 28)],
  ["Skocz na wysokość ~20 m (big air)", undefined, prog("wysokosc", 16)],
  ["Popływaj łącznie 800 godzin", undefined, prog("godziny", 800)],
  ["Zdobądź medal mistrzostw kraju (freestyle/big air)"],
  ["Wykonaj double kiteloop — próba", undefined, prog("technika", 29)],
  ["Skocz na wysokość ~22 m", undefined, prog("wysokosc", 17)],
  ["Popływaj łącznie 1000 godzin", undefined, prog("godziny", 1000)],
  ["Uzyskaj wynik kwalifikujący do zawodów międzynarodowych"],
  // 66-85 · Wyczynowy
  ["Wykonaj czysty double kiteloop", undefined, prog("technika", 30)],
  ["Skocz na wysokość ~24 m", undefined, prog("wysokosc", 18)],
  ["Wystartuj w zawodach międzynarodowych (GKA/King of the Air kwalifikacje)"],
  ["Skocz na wysokość ~26 m", undefined, prog("wysokosc", 19)],
  ["Zdobądź punkty w rankingu międzynarodowym"],
  ["Wykonaj board-off (odpięcie deski w powietrzu)", undefined, prog("technika", 31)],
  ["Skocz na wysokość ~28 m", undefined, prog("wysokosc", 20)],
  ["Zajmij miejsce w pierwszej ósemce zawodów międzynarodowych"],
  ["Wykonaj triple handle pass lub najtrudniejszy element freestyle", undefined, prog("technika", 32)],
  ["Skocz na wysokość ~30 m", "Big air poziomu King of the Air.", prog("wysokosc", 21)],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Wykonaj triple kiteloop — próba", undefined, prog("technika", 33)],
  ["Skocz na wysokość ~32 m", undefined, prog("wysokosc", 22)],
  ["Weź udział w zawodach o zasięgu ogólnokrajowym"],
  ["Wykonaj czysty triple kiteloop", undefined, prog("technika", 34)],
  ["Skocz na wysokość ~34 m", undefined, prog("wysokosc", 23)],
  ["Zajmij miejsce w pierwszej piętnastce zawodów o zasięgu ogólnokrajowym"],
  ["Skocz na wysokość ~36 m", undefined, prog("wysokosc", 24)],
  ["Wykonaj kombinację najtrudniejszych znanych sobie trików w jednym przejeździe", undefined, prog("technika", 35)],
  ["Zdobądź tytuł mistrza regionu"],
  // 86-99 · Elita
  ["Zajmij miejsce w pierwszej dziesiątce zawodów o zasięgu ogólnokrajowym"],
  ["Skocz na wysokość ~38 m", undefined, prog("wysokosc", 25)],
  ["Wygraj heat na zawodach o zasięgu ogólnokrajowym"],
  ["Skocz na wysokość ~40 m", undefined, prog("wysokosc", 26)],
  ["Zajmij miejsce w pierwszej szóstce zawodów o zasięgu ogólnokrajowym"],
  ["Skocz na wysokość ~42 m", undefined, prog("wysokosc", 27)],
  ["Zdobądź podium etapu zawodów o zasięgu ogólnokrajowym"],
  ["Skocz na wysokość ~24 m przy pełnym megaloopie w zawodach", undefined, prog("wysokosc", 28)],
  ["Zajmij miejsce w pierwszej trójce klasyfikacji kraju amatorów"],
  ["Wygraj etap zawodów o zasięgu ogólnokrajowym"],
  ["Skocz na wysokość ponad 28 m w oficjalnym pomiarze na zawodach", undefined, prog("wysokosc", 29)],
  ["Zdobądź tytuł mistrza kraju amatorów"],
  ["Wygraj prestiżowy turniej big air o szerokim zasięgu"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat kitesurfingowy", "Dalsze, zawodowe osiągnięcia (GKA World Tour, King of the Air) potwierdzają osobne certyfikaty."],
]);
