// Basketball ladder 1-99. Tracks: free throws (out of 10), three-pointers,
// dribbling/handles, match experience. Manual check-offs.
import type { Criterion } from "../../src/lib/milestone-criteria";
import type { MilestoneResource } from "../../src/lib/milestone-resources";
import { ladder, freq, prog } from "./helpers";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "koszykowka",
  name: "Koszykówka",
  icon: "🏀",
  description:
    "Rzuty, kozioł i mecze — od pierwszego trafienia po ligowe parkiety. Serie rzutowe licz z 10 prób.",
  sortOrder: 8,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Traf do kosza z dowolnego miejsca", "Pierwszy swish (albo szczęśliwy rzut z tablicy)."],
  ["Kozłuj piłkę 30 sekund prawą ręką bez utraty kontroli"],
  ["Traf rzut osobisty (z linii)"],
  ["Kozłuj piłkę 30 sekund lewą ręką"],
  ["Traf 3/10 rzutów osobistych"],
  ["Wykonaj poprawny dwutakt z prawej strony"],
  ["Kozłuj naprzemiennie (crossover) 10 razy bez utraty piłki"],
  ["Traf 5/10 rzutów osobistych (free throws)", "Połowa — poziom rekreacyjnego początku."],
  ["Wykonaj dwutakt z lewej strony"],
  ["Zagraj pierwszy mecz (streetball 3v3 lub hala)"],
  // 11-25 · Regularny
  ["Graj lub trenuj raz w tygodniu przez 4 kolejne tygodnie"],
  ["Traf pierwszą trójkę"],
  ["Kozłuj między nogami w marszu"],
  ["Traf 6/10 rzutów osobistych"],
  ["Zagraj 5 meczów"],
  ["Traf 5/10 rzutów z półdystansu (z linii rzutów za 2)"],
  ["Wykonaj poprawny rzut z wyskoku (jump shot)"],
  ["Traf 2/10 trójek"],
  ["Zagraj 10 meczów"],
  ["Traf 7/10 rzutów osobistych", "Średnia rzutów osobistych w NBA to ~78%."],
  ["Kozłuj za plecami w biegu"],
  ["Zdobądź 10 punktów w jednym meczu"],
  ["Graj 2 razy w tygodniu przez 8 kolejnych tygodni"],
  ["Traf 4/10 trójek"],
  ["Zagraj 20 meczów"],
  // 26-45 · Średniozaawansowany
  ["Traf 8/10 rzutów osobistych"],
  ["Wykonaj skuteczny zwód rzutowy (pump fake) i minięcie w meczu"],
  ["Traf 10 rzutów osobistych z rzędu"],
  ["Zalicz 5 asyst w jednym meczu"],
  ["Traf 5/10 trójek", "Połowa zza łuku — próg „strzelca”."],
  ["Zagraj 35 meczów"],
  ["Zbierz 10 zbiórek w jednym meczu"],
  ["Traf trójkę w meczu"],
  ["Wykonaj poprawny floater w meczu"],
  ["Zdobądź 20 punktów w jednym meczu"],
  ["Zagraj 50 meczów"],
  ["Traf 6/10 trójek"],
  ["Graj regularnie przez pełny sezon (6+ miesięcy)"],
  ["Wykonaj step-back z trafieniem w meczu"],
  ["Traf 15 rzutów osobistych z rzędu"],
  ["Zalicz double-double w meczu (np. 10 pkt + 10 zbiórek)"],
  ["Zdobądź 100 punktów łącznie w meczach"],
  ["Wygraj lokalny turniej 3v3 ze swoją drużyną"],
  ["Traf 7/10 trójek"],
  ["Zagraj 75 meczów"],
  // 46-65 · Zaawansowany
  ["Traf 9/10 rzutów osobistych", "Poziom najlepszych strzelców z linii."],
  ["Zdobądź 30 punktów w jednym meczu"],
  ["Dołącz do drużyny w zorganizowanej lidze amatorskiej"],
  ["Zagraj 100 meczów", "Setka spotkań na parkiecie."],
  ["Traf 20 rzutów osobistych z rzędu"],
  ["Zalicz 10 asyst w jednym meczu"],
  ["Traf 5 trójek w jednym meczu"],
  ["Zdobądź 250 punktów łącznie"],
  ["Wykonaj blok w meczu przeciwko rzutowi z wyskoku"],
  ["Zagraj pełny mecz ligowy bez zmiany"],
  ["Traf 8/10 trójek"],
  ["Zostań MVP meczu w swojej drużynie"],
  ["Zagraj 150 meczów"],
  ["Zalicz triple-double w meczu", "Punkty + zbiórki + asysty dwucyfrowo."],
  ["Zdobądź 500 punktów łącznie"],
  ["Traf 25 rzutów osobistych z rzędu"],
  ["Wygraj sezon ligi amatorskiej ze swoją drużyną"],
  ["Zagraj 200 meczów"],
  ["Zdobądź 40 punktów w jednym meczu"],
  ["Dotknij obręczy w wyskoku", "Wymierny próg skoczności."],
  // 66-85 · Wyczynowy
  ["Traf 9/10 trójek w serii treningowej"],
  ["Zostań kapitanem drużyny na sezon"],
  ["Zdobądź 1000 punktów łącznie", "Czterocyfrowy licznik."],
  ["Zagraj 300 meczów"],
  ["Zostań królem strzelców swojej ligi"],
  ["Traf 30 rzutów osobistych z rzędu"],
  ["Rozegraj 5 pełnych sezonów"],
  ["Zagraj w rozgrywkach związkowych (PZKosz, dowolna klasa)"],
  ["Traf 50 trójek łącznie w meczach"],
  ["Zalicz 5 meczów z double-double w jednym sezonie"],
  ["Zagraj 400 meczów"],
  ["Awansuj z drużyną do wyższej klasy rozgrywkowej"],
  ["Zdobądź 2000 punktów łącznie"],
  ["Złap piłkę z powietrza i wyłóż ją do kosza (alley-oop lub tip-in) w meczu"],
  ["Zagraj 50 oficjalnych meczów ligowych"],
  ["Wygraj puchar regionu lub równorzędne trofeum"],
  ["Zdobądź 30+ punktów w meczu związkowym"],
  ["Zagraj 500 meczów"],
  ["Wykonaj wsad w meczu lub na treningu", "Powyżej obręczy — poziom, o którym marzy każde podwórko."],
  ["Rozegraj sezon jako podstawowy zawodnik III ligi lub wyżej"],
  // 86-99 · Elita
  ["Traf 10/10 trójek w serii treningowej", "Perfekcyjna seria zza łuku."],
  ["Zdobądź 3000 punktów łącznie"],
  ["Zagraj 600 meczów"],
  ["Zagraj na poziomie II ligi"],
  ["Traf 50 rzutów osobistych z rzędu"],
  ["Zostań MVP sezonu swojej ligi"],
  ["Zagraj 100 oficjalnych meczów ligowych"],
  ["Zagraj na poziomie I ligi"],
  ["Zdobądź 5000 punktów łącznie"],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zagraj 750 meczów"],
  ["Wystąp w rozgrywkach pucharu na szczeblu regionalnym"],
  ["Poprowadź drużynę jako lider / kapitan przez sezon"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej amatorskiej drużyny", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  3: prog("osobiste", 1), 5: prog("osobiste", 3), 8: prog("osobiste", 5), 14: prog("osobiste", 6),
  20: prog("osobiste", 7), 26: prog("osobiste", 8), 46: prog("osobiste", 9),
  28: prog("osobiste-seria", 10), 40: prog("osobiste-seria", 15), 50: prog("osobiste-seria", 20),
  61: prog("osobiste-seria", 25), 71: prog("osobiste-seria", 30), 90: prog("osobiste-seria", 50),
  12: prog("trojki", 1), 18: prog("trojki", 2), 24: prog("trojki", 4), 30: prog("trojki", 5),
  37: prog("trojki", 6), 44: prog("trojki", 7), 56: prog("trojki", 8), 66: prog("trojki", 9),
  86: prog("trojki", 10),
  10: prog("mecze", 1), 15: prog("mecze", 5), 19: prog("mecze", 10), 25: prog("mecze", 20),
  31: prog("mecze", 35), 36: prog("mecze", 50), 45: prog("mecze", 75), 49: prog("mecze", 100),
  58: prog("mecze", 150), 63: prog("mecze", 200), 69: prog("mecze", 300), 76: prog("mecze", 400),
  83: prog("mecze", 500), 88: prog("mecze", 600), 96: prog("mecze", 750),
  22: prog("punkty-mecz", 10), 35: prog("punkty-mecz", 20), 47: prog("punkty-mecz", 30), 64: prog("punkty-mecz", 40),
  42: prog("punkty", 100), 53: prog("punkty", 250), 60: prog("punkty", 500), 68: prog("punkty", 1000),
  78: prog("punkty", 2000), 87: prog("punkty", 3000), 94: prog("punkty", 5000),
  11: freq(1, 4), 23: freq(2, 8),
  // pozostałe: technika, wydarzenia, poziomy rozgrywkowe — manualne.
};

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  // — Rozszerzenie zasobów Tier 1 (wszystkie linki zweryfikowane jako aktywne) —
  1: [{ kind: "video", title: "Jak rzucać do kosza — poradnik dla początkujących", url: yt("dfbIAOXDPFk") }],
  4: [{ kind: "video", title: "Kozłowanie słabszą ręką — trening off-hand", url: yt("TQZoa9p5Mfk") }],
  5: [{ kind: "video", title: "Rzut wolny — jak trafiać z linii", url: yt("iW2VFzBiaQo") }],
  8: [{ kind: "video", title: "Jak trafiać więcej rzutów osobistych", url: yt("0343D3fjPnQ") }],
  10: [{ kind: "video", title: "Zasady koszykówki 3x3 — jak grać w streetball", url: yt("bN6LywHcihI") }],
  14: [{ kind: "video", title: "Rytuał rzutu osobistego — większa regularność", url: yt("d3fdURdzT6k") }],
  20: [{ kind: "video", title: "Rzut osobisty — rutyna dla wysokiej skuteczności", url: yt("8Ul28lp87Xc") }],
  22: [{ kind: "video", title: "Dlaczego nie trafiasz w meczu — rzuty w grze", url: yt("SmspzPf7PPU") }],
  25: [{ kind: "video", title: "Jak podnieść swoje IQ koszykarskie", url: yt("uIgpf1ZKaLs") }],
  30: [{ kind: "video", title: "Jak trafiać więcej trójek — kompletny poradnik", url: yt("lYLv4ux7Pd4") }],
  40: [{ kind: "article", title: "Rzuty osobiste pod presją — trening regularności", url: "https://www.nike.com/a/how-to-shoot-free-throw" }],
  50: [{ kind: "article", title: "Rytuał i psychika przy rzutach osobistych", url: "https://www.sports-psychology.com/free-throw-routine/" }],
  60: [{ kind: "video", title: "Trójki z dystansu — zasięg i regularność", url: yt("PdgeX_3pB0A") }],
  2: [{ kind: "video", title: "Kozioł — podstawy dryblingu", url: yt("VLiOF2jMaJc") }],
  3: [{ kind: "video", title: "Technika rzutu osobistego", url: yt("TUHMJq3O3Rk") }],
  6: [{ kind: "video", title: "Dwutakt — layup krok po kroku", url: yt("S-_PYQyknWI") }],
  7: [{ kind: "video", title: "Crossover — kozioł między rękami", url: yt("d6MKEJKDhbc") }],
  12: [{ kind: "video", title: "Jak trafić pierwszą trójkę", url: yt("t7ci4VRbSl4") }],
  17: [{ kind: "video", title: "Jump shot — technika rzutu z wyskoku", url: yt("WE3_yF4jCiA") }],
  27: [{ kind: "video", title: "Pump fake — zwód rzutowy", url: yt("d4cw0N_I-Aw") }],
  34: [{ kind: "video", title: "Floater — rzut z bliska nad wyższymi", url: yt("4JB3-MUJKUY") }],
  39: [{ kind: "video", title: "Step-back jumper — technika", url: yt("H4T-MiN4xKU") }],
  54: [{ kind: "article", title: "How to block a shot in basketball", url: "https://www.wikihow.com/Block-a-Shot-in-Basketball" }],
  65: [{ kind: "video", title: "How to dunk — vertical jump training", url: yt("BVFY7aLQn2o") }],
};
