// Ten-pin bowling ladder 1-99. Manual — progression tracks: game score
// (out of 300), consecutive strikes, and competition levels. Benchmarks:
// casual ~80-100; league average 150-175; strong amateur 200+; perfect 300.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kregle",
  name: "Kręgle",
  icon: "🎳",
  description:
    "Kręgle klasyczne (ten-pin) — od pierwszego strike'a po grę doskonałą 300. Progresja: wynik gry, serie strike'ów i poziom rozgrywek.",
  sortOrder: 30,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Rzuć kulą prosto i zbij choć jeden kręgiel", undefined, prog("wynik", 20)],
  ["Zbij wszystkie kręgle w dwóch rzutach (spare) choć raz", undefined, prog("technika", 1)],
  ["Uzyskaj wynik 60 w grze", undefined, prog("wynik", 60)],
  ["Rzuć pierwszego strike'a", undefined, prog("seria", 1)],
  ["Uzyskaj wynik 80 w grze", undefined, prog("wynik", 80)],
  ["Opanuj poprawny rozbieg i wypuszczenie kuli", undefined, prog("technika", 2)],
  ["Uzyskaj wynik 90 w grze", undefined, prog("wynik", 90)],
  ["Zbij spare'a typu „dziura” (dwa rozdzielone kręgle)", undefined, prog("technika", 3)],
  ["Uzyskaj wynik 100 w grze", "Setka — pierwszy próg.", prog("wynik", 100)],
  ["Rzuć dwa strike'i pod rząd (double)", undefined, prog("seria", 2)],
  // 11-25 · Regularny
  ["Graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Uzyskaj wynik 110 w grze", undefined, prog("wynik", 110)],
  ["Opanuj rzut z rotacją (hook)", undefined, prog("technika", 4)],
  ["Uzyskaj wynik 120 w grze", undefined, prog("wynik", 120)],
  ["Rzuć trzy strike'i pod rząd (turkey)", undefined, prog("seria", 3)],
  ["Uzyskaj wynik 130 w grze", undefined, prog("wynik", 130)],
  ["Zbij spare narożny (10-pin lub 7-pin)", undefined, prog("technika", 5)],
  ["Uzyskaj wynik 140 w grze", undefined, prog("wynik", 140)],
  ["Weź udział w pierwszym turnieju lub lidze"],
  ["Uzyskaj wynik 150 w grze", "Średnia typowego ligowca.", prog("wynik", 150)],
  ["Rzuć cztery strike'i pod rząd", undefined, prog("seria", 4)],
  ["Uzyskaj wynik 160 w grze", undefined, prog("wynik", 160)],
  ["Kontroluj tor rzutu na naoliwionej pasie", undefined, prog("technika", 6)],
  ["Uzyskaj wynik 170 w grze", undefined, prog("wynik", 170)],
  ["Rzuć pięć strike'ów pod rząd", undefined, prog("seria", 5)],
  // 26-45 · Średniozaawansowany
  ["Graj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Uzyskaj wynik 175 w grze", undefined, prog("wynik", 175)],
  ["Zbij trudnego splita (np. baby split)", undefined, prog("technika", 7)],
  ["Uzyskaj wynik 180 w grze", undefined, prog("wynik", 180)],
  ["Rzuć sześć strike'ów pod rząd", undefined, prog("seria", 6)],
  ["Uzyskaj wynik 185 w grze", undefined, prog("wynik", 185)],
  ["Zajmij miejsce w pierwszej połowie turnieju"],
  ["Uzyskaj wynik 190 w grze", undefined, prog("wynik", 190)],
  ["Rzuć siedem strike'ów pod rząd", undefined, prog("seria", 7)],
  ["Uzyskaj wynik 195 w grze", undefined, prog("wynik", 195)],
  ["Opanuj dwa różne kąty ataku (linia prosta i hook)", undefined, prog("technika", 8)],
  ["Uzyskaj wynik 200 w grze", "Dwieście — poziom zaawansowanego amatora.", prog("wynik", 200)],
  ["Rzuć osiem strike'ów pod rząd", undefined, prog("seria", 8)],
  ["Uzyskaj wynik 210 w grze", undefined, prog("wynik", 210)],
  ["Zajmij miejsce na podium turnieju amatorskiego"],
  ["Uzyskaj wynik 215 w grze", undefined, prog("wynik", 215)],
  ["Zbij splita 7-10 (najtrudniejszy)", undefined, prog("technika", 9)],
  ["Uzyskaj wynik 220 w grze", undefined, prog("wynik", 220)],
  ["Rzuć dziewięć strike'ów pod rząd", undefined, prog("seria", 9)],
  // 46-65 · Zaawansowany
  ["Graj lub trenuj 3+ razy w tygodniu przez sezon"],
  ["Uzyskaj wynik 225 w grze", undefined, prog("wynik", 225)],
  ["Dopasuj kulę i olej — czytaj pas jak zawodnik", undefined, prog("technika", 10)],
  ["Uzyskaj wynik 230 w grze", undefined, prog("wynik", 230)],
  ["Rzuć dziesięć strike'ów pod rząd", undefined, prog("seria", 10)],
  ["Uzyskaj wynik 235 w grze", undefined, prog("wynik", 235)],
  ["Zajmij miejsce w czołówce turnieju regionalnego"],
  ["Uzyskaj wynik 240 w grze", undefined, prog("wynik", 240)],
  ["Rzuć jedenaście strike'ów pod rząd", undefined, prog("seria", 11)],
  ["Uzyskaj wynik 245 w grze", undefined, prog("wynik", 245)],
  ["Uzyskaj serię 3 gier powyżej 600 pkt łącznie", undefined, prog("technika", 11)],
  ["Uzyskaj wynik 250 w grze", "Poziom półprofesjonalny.", prog("wynik", 250)],
  ["Wygraj turniej regionalny"],
  ["Uzyskaj wynik 255 w grze", undefined, prog("wynik", 255)],
  ["Uzyskaj serię 3 gier powyżej 650 pkt", undefined, prog("technika", 12)],
  ["Uzyskaj wynik 260 w grze", undefined, prog("wynik", 260)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju"],
  ["Uzyskaj wynik 265 w grze", undefined, prog("wynik", 265)],
  ["Uzyskaj serię 3 gier powyżej 700 pkt", undefined, prog("technika", 13)],
  ["Uzyskaj wynik 270 w grze", undefined, prog("wynik", 270)],
  // 66-85 · Wyczynowy
  ["Utrzymaj średnią 220+ przez cały sezon ligowy"],
  ["Wygraj mecz play-off w rozgrywkach ligowych"],
  ["Uzyskaj wynik 275 w grze", undefined, prog("wynik", 275)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Uzyskaj wynik 278 w grze", undefined, prog("wynik", 278)],
  ["Uzyskaj serię 3 gier powyżej 750 pkt", undefined, prog("technika", 14)],
  ["Uzyskaj wynik 280 w grze", undefined, prog("wynik", 280)],
  ["Wygraj turniej rangi ogólnokrajowej"],
  ["Uzyskaj wynik 282 w grze", undefined, prog("wynik", 282)],
  ["Zdobądź punkty w rankingu międzynarodowym"],
  ["Uzyskaj wynik 285 w grze", undefined, prog("wynik", 285)],
  ["Uzyskaj serię 3 gier powyżej 800 pkt", "Świetna seria zawodnicza.", prog("technika", 15)],
  ["Uzyskaj wynik 288 w grze", undefined, prog("wynik", 288)],
  ["Zajmij miejsce w pierwszej ósemce turnieju międzynarodowego"],
  ["Uzyskaj wynik 290 w grze", undefined, prog("wynik", 290)],
  ["Utrzymaj średnią 210+ przez cały sezon ligowy"],
  ["Uzyskaj wynik 292 w grze", undefined, prog("wynik", 292)],
  ["Uzyskaj serię 3 gier powyżej 850 pkt", undefined, prog("technika", 16)],
  ["Uzyskaj wynik 295 w grze", undefined, prog("wynik", 295)],
  ["Zdobądź podium mistrzostw regionu"],
  ["Uzyskaj wynik 298 w grze", undefined, prog("wynik", 298)],
  // 86-99 · Elita
  ["Weź udział w turnieju o zasięgu ogólnopolskim"],
  ["Uzyskaj wynik 299 w grze", "O jeden kręgiel od doskonałości.", prog("wynik", 299)],
  ["Zajmij miejsce w czołówce turnieju ogólnopolskiego"],
  ["Rzuć grę doskonałą — 300 punktów", "12 strike'ów pod rząd. Perfekcja.", prog("wynik", 300)],
  ["Rzuć dwanaście strike'ów pod rząd (perfect game)", undefined, prog("seria", 12)],
  ["Uzyskaj serię 3 gier powyżej 850 pkt w turnieju", undefined, prog("technika", 17)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju amatorów"],
  ["Uzyskaj drugą grę doskonałą w karierze", undefined, prog("technika", 18)],
  ["Wygraj turniej rangi ogólnopolskiej"],
  ["Zdobądź podium mistrzostw kraju amatorów"],
  ["Utrzymaj średnią 220+ przez cały sezon ligowy"],
  ["Poprowadź drużynę ligową jako lider przez sezon"],
  ["Wygraj mistrzostwa kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletnia średnia 220+ i kilka gier doskonałych", "Dalsze, zawodowe osiągnięcia (tour PBA, rekordy) potwierdzają osobne certyfikaty."],
]);
