// Cricket ladder 1-99. Manual — progression tracks: matches played, runs
// scored (total, batting), and competition level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "krykiet",
  name: "Krykiet",
  icon: "🏏",
  description:
    "Najpopularniejszy sport, o którym w Polsce mało kto słyszał. Od pierwszego odbicia po ligowe murawy. Progresja: mecze, zdobyte runy i poziom rozgrywek.",
  sortOrder: 35,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Poprawnie chwyć kij i przyjmij postawę (batting stance)", undefined, prog("technika", 1)],
  ["Odbij piłkę rzuconą wprost (front-foot drive)", undefined, prog("technika", 2)],
  ["Rzuć piłkę z prostym ramieniem (legalny bowling)", undefined, prog("technika", 3)],
  ["Złap piłkę w polu (catch) z bliska", undefined, prog("technika", 4)],
  ["Wykonaj poprawny run między bramkami (wicket)", undefined, prog("technika", 5)],
  ["Odbij piłkę do tyłu (back-foot shot)", undefined, prog("technika", 6)],
  ["Rzuć serię (over — 6 legalnych piłek) bez błędu", undefined, prog("technika", 7)],
  ["Zagraj pierwszy mecz treningowy", undefined, prog("mecze", 1)],
  ["Zdobądź pierwsze runy jako batsman", undefined, prog("runy", 1)],
  ["Rozegraj pełny mecz (format skrócony T20 lub podobny)", undefined, prog("mecze", 2)],
  // 11-25 · Regularny
  ["Trenuj lub graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Wykonaj pull shot lub cut shot", undefined, prog("technika", 8)],
  ["Zagraj 5 meczów", undefined, prog("mecze", 5)],
  ["Zdobądź 50 runów łącznie", undefined, prog("runy", 50)],
  ["Zdobądź pierwszy wicket jako bowler (wyautuj batsmana)", undefined, prog("technika", 9)],
  ["Zagraj na stałej roli (batsman, bowler lub all-rounder)"],
  ["Zagraj 10 meczów", undefined, prog("mecze", 10)],
  ["Zdobądź 150 runów łącznie", undefined, prog("runy", 150)],
  ["Wykonaj skuteczny rzut spinowy lub szybki (opanuj jeden typ)", undefined, prog("technika", 10)],
  ["Rozegraj mecz w lidze amatorskiej lub klubowej", undefined, prog("liga", 1)],
  ["Zagraj 20 meczów", undefined, prog("mecze", 20)],
  ["Zdobądź 300 runów łącznie", undefined, prog("runy", 300)],
  ["Zdobądź 20 runów w jednym inningsie", undefined, prog("runy-inn", 20)],
  ["Wykonaj catch w biegu w polu", undefined, prog("technika", 11)],
  ["Zagraj 30 meczów", undefined, prog("mecze", 30)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zdobądź 500 runów łącznie", undefined, prog("runy", 500)],
  ["Opanuj drugi typ zagrania (np. sweep lub lofted drive)", undefined, prog("technika", 12)],
  ["Zagraj 50 meczów", undefined, prog("mecze", 50)],
  ["Zdobądź 800 runów łącznie", undefined, prog("runy", 800)],
  ["Rozegraj pełny sezon w regularnej lidze", undefined, prog("liga", 2)],
  ["Zdobądź pierwsze half-century — 50 runów w inningsie", "Kluczowy próg batsmana.", prog("runy-inn", 50)],
  ["Weź 3 wickety w jednym meczu (jako bowler)", undefined, prog("technika", 13)],
  ["Zagraj 75 meczów", undefined, prog("mecze", 75)],
  ["Zdobądź 1200 runów łącznie", undefined, prog("runy", 1200)],
  ["Zajmij miejsce w pierwszej połowie tabeli ligowej"],
  ["Zdobądź 75 runów w jednym inningsie", undefined, prog("runy-inn", 75)],
  ["Zagraj 100 meczów", undefined, prog("mecze", 100)],
  ["Zdobądź 1800 runów łącznie", undefined, prog("runy", 1800)],
  ["Rozegraj mecz w II lidze lub odpowiedniku", undefined, prog("liga", 3)],
  ["Zdobądź pierwsze century — 100 runów w inningsie", "Setka — marzenie każdego batsmana.", prog("runy-inn", 100)],
  ["Zdobądź 2400 runów łącznie", undefined, prog("runy", 2400)],
  ["Zagraj 150 meczów", undefined, prog("mecze", 150)],
  ["Weź 5 wicketów w jednym inningsie (five-for)", undefined, prog("technika", 14)],
  ["Zostań liderem swojego zespołu w runach lub wicketach w sezonie"],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Zdobądź 3200 runów łącznie", undefined, prog("runy", 3200)],
  ["Rozegraj mecz w I lidze", undefined, prog("liga", 4)],
  ["Zagraj 200 meczów", undefined, prog("mecze", 200)],
  ["Zdobądź 4000 runów łącznie", undefined, prog("runy", 4000)],
  ["Zostań podstawowym zawodnikiem zespołu I-ligowego"],
  ["Zdobądź 125 runów w jednym inningsie", undefined, prog("runy-inn", 125)],
  ["Zagraj 250 meczów", undefined, prog("mecze", 250)],
  ["Zdobądź 5000 runów łącznie", undefined, prog("runy", 5000)],
  ["Zajmij miejsce w czołówce I ligi"],
  ["Awansuj z drużyną do wyższej klasy rozgrywek"],
  ["Zdobądź 6000 runów łącznie", undefined, prog("runy", 6000)],
  ["Zagraj 300 meczów", undefined, prog("mecze", 300)],
  ["Zdobądź 150 runów w jednym inningsie", undefined, prog("runy-inn", 150)],
  ["Zdobądź 7000 runów łącznie", undefined, prog("runy", 7000)],
  ["Zagraj w najwyższej lidze krajowej", undefined, prog("liga", 5)],
  ["Zdobądź runy w meczu najwyższej ligi"],
  ["Zdobądź 8000 runów łącznie", undefined, prog("runy", 8000)],
  ["Zagraj 400 meczów", undefined, prog("mecze", 400)],
  ["Zostań rozpoznawalnym zawodnikiem w swoim regionie"],
  // 66-85 · Wyczynowy
  ["Zdobądź 9000 runów łącznie", undefined, prog("runy", 9000)],
  ["Zagraj 500 meczów", undefined, prog("mecze", 500)],
  ["Zostań podstawowym zawodnikiem najwyższej ligi"],
  ["Zdobądź 10 000 runów łącznie", undefined, prog("runy", 10000)],
  ["Zdobądź 175 runów w jednym inningsie", undefined, prog("runy-inn", 175)],
  ["Zagraj 600 meczów", undefined, prog("mecze", 600)],
  ["Zdobądź medal lub tytuł mistrzostw kraju"],
  ["Zdobądź 12 000 runów łącznie", undefined, prog("runy", 12000)],
  ["Zostań uznanym zawodnikiem swojej ligi regionalnej"],
  ["Zdobądź 200 runów w jednym inningsie (double century)", undefined, prog("runy-inn", 200)],
  ["Zdobądź runy w ważnym meczu ligowym"],
  ["Zdobądź 14 000 runów łącznie", undefined, prog("runy", 14000)],
  ["Zagraj 700 meczów", undefined, prog("mecze", 700)],
  ["Zagraj w międzynarodowym meczu formatu T20I lub ODI"],
  ["Zdobądź 16 000 runów łącznie", undefined, prog("runy", 16000)],
  ["Zagraj 800 meczów", undefined, prog("mecze", 800)],
  ["Zdobądź podium mistrzostw regionu z klubem"],
  ["Zdobądź half-century w ważnym meczu ligowym"],
  ["Zdobądź 18 000 runów łącznie", undefined, prog("runy", 18000)],
  ["Zostań kapitanem swojej drużyny klubowej"],
  // 86-99 · Elita
  ["Zdobądź 20 000 runów łącznie", undefined, prog("runy", 20000)],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zagraj 1000 meczów", undefined, prog("mecze", 1000)],
  ["Zdobądź century w ważnym meczu ligowym"],
  ["Zdobądź 22 000 runów łącznie", undefined, prog("runy", 22000)],
  ["Weź udział w turnieju o zasięgu ogólnokrajowym"],
  ["Zostań czołowym batsmanem lub bowlerem swojej ligi"],
  ["Zdobądź 24 000 runów łącznie", undefined, prog("runy", 24000)],
  ["Zdobądź 250 runów w jednym inningsie", undefined, prog("runy-inn", 250)],
  ["Zdobądź trofeum swojej ligi klubowej"],
  ["Znajdź się w składzie gwiazd sezonu swojej ligi"],
  ["Zostań graczem meczu w ważnym spotkaniu ligowym"],
  ["Wygraj mistrzostwo swojej ligi klubowej"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej drużyny klubowej", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);
