// Peruvian cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "kuchnia-peruwianska",
  name: "Kuchnia peruwiańska",
  icon: "🇵🇪",
  description:
    "Od ceviche po lomo saltado i pachamancę — konkretne dania jako poziomy. Podstawy → klasyki → pasty ají, leche de tigre i grill → uczta. Realna droga kucharza domowego.",
  sortOrder: 120,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Salsa criolla (surówka z cebuli i limonki)", undefined, prog("techniki", 1)],
  ["Papa a la huancaína (ziemniaki w sosie ají)"],
  ["Causa limeña (warstwowe ziemniaki)", undefined, prog("techniki", 2)],
  ["Arroz chaufa (smażony ryż)"],
  ["Pasty ají (amarillo, panca) — baza", undefined, prog("techniki", 3)],
  ["Ceviche proste (ryba w limonce)"],
  ["Ensalada / tallarines verdes"],
  ["Choclo con queso"],
  ["Ugotuj 5 peruwiańskich dań", undefined, prog("dania", 5)],
  ["Anticuchos (szaszłyki) na gotowej marynacie"],
  // 11-25 · Klasyki
  ["Gotuj peruwiańskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Leche de tigre (marynata do ceviche)", undefined, prog("techniki", 4)],
  ["Lomo saltado (wołowina stir-fry)", undefined, prog("techniki", 5)],
  ["Ají de gallina (kurczak w kremowym sosie)"],
  ["Causa rellena (nadziewana)"],
  ["Anticuchos de corazón (marynata od podstaw)"],
  ["Arroz con pollo"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Ceviche z prawdziwym leche de tigre", undefined, prog("techniki", 6)],
  ["Wok / saltado — technika (chifa)", undefined, prog("techniki", 7)],
  ["Papa rellena (nadziewane ziemniaki)"],
  ["Tallarines verdes (peruwiańskie pesto)"],
  ["Picarones (deser)"],
  ["Aji de gallina na wysokim poziomie"],
  ["Sopa a la criolla"],
  ["Escabeche de pollo (kurczak w zalewie)"],
  // 26-45 · Średniozaawansowane
  ["Pasty ají od podstaw (amarillo, panca, rocoto)", undefined, prog("techniki", 8)],
  ["Ceviche w kilku wariantach (mixto, ryby)", undefined, prog("techniki", 9)],
  ["Marynaty do grilla (anticuchos, pollo a la brasa)", undefined, prog("techniki", 10)],
  ["Seco de cordero (jagnięcina z kolendrą)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Rocoto relleno (nadziewana papryka rocoto)"],
  ["Tacu tacu (ryż z fasolą)", undefined, prog("techniki", 11)],
  ["Lomo saltado na wysokim poziomie (wok hei)"],
  ["Pollo a la brasa (kurczak z rożna)", undefined, prog("techniki", 12)],
  ["Aji de gallina / carapulcra na przyjęcie"],
  ["Chupe de camarones (zupa z krewetek)"],
  ["Arroz con mariscos"],
  ["Suspiro a la limeña (deser)"],
  ["Gotuj peruwiańskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Picarones z chancacą (deser)"],
  ["Ceviche na przyjęcie z garniturami"],
  ["Anticuchos na grilla dla gości"],
  ["Ají de gallina / seco na dużą imprezę"],
  ["Mazamorra morada (deser)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Ceviche i tiradito na poziomie cebicherii", undefined, prog("techniki", 13)],
  ["Zestaw dań na peruwiański stół dla gości"],
  ["Pachamanca (mięsa i warzywa pieczone — imitacja domowa)"],
  ["Cau cau / mondongo (flaki po peruwiańsku)"],
  ["Pasty ají i sosy na poziomie mistrzowskim", undefined, prog("techniki", 14)],
  ["Aguadito / chupe na wysokim poziomie"],
  ["Desery peruwiańskie (alfajores, king kong)", undefined, prog("techniki", 15)],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Pollo a la brasa / anticuchos na dużą imprezę"],
  ["Seco / carapulcra na przyjęcie"],
  ["Chleby i wypieki peruwiańskie (pan chapla)", undefined, prog("techniki", 16)],
  ["Ceviche + lomo saltado + deser jako komplet"],
  ["Danie regionalne (Arequipa / Amazonia / Andy)"],
  ["Deser: suspiro / crema volteada"],
  ["Zupy i chupes w kilku wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Konserwy i pasty ají na zapas"],
  ["Zaserwuj spójne 3-daniowe menu peruwiańskie"],
  ["Peruwiański stół: ceviche + główne + desery"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj peruwiańskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Ceviche, tiradito i pasty ají na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Pełny zestaw przystawek i causas"],
  ["Owoce morza premium po peruwiańsku"],
  ["Pachamanca / całe pieczyste dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: ceviche + saltado + seco + desery"],
  ["Danie z Arequipy (picantería, ostre sosy)"],
  ["Wypieki i desery peruwiańskie (alfajores, turrón)", undefined, prog("techniki", 18)],
  ["Ceviche i dania nikkei/chifa w kilku stylach"],
  ["Suszenie/marynowanie w domu (charqui, ají seco)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. Limy lub Andów)"],
  ["Pollo a la brasa / anticuchos na dużą imprezę"],
  ["Pachamanca na przyjęcie"],
  ["Zorganizuj peruwiańską kolację tematyczną"],
  ["Całe pieczyste (lechón / cuy) na okazję"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie ceviche i causas (plating)"],
  ["Desery peruwiańskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania peruwiańskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Ceviche, pasty ají i saltado na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu peruwiańskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Peru"],
  ["Uczta świąteczna (Navidad / Fiestas Patrias) — wielodaniowa"],
  ["Naucz kogoś peruwiańskich technik (leche de tigre, ají, saltado)"],
  ["Ceviche i pasty ají bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar sosów i marynat z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni peruwiańskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde peruwiańskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne peruwiańskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated learning resources for Peruvian cuisine milestones.
// Videos from Peru Delights and others; articles from seriouseats, bonappetit.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  2: [{ kind: "video", title: "Papa a la Huancaína — Potatoes in Ají Sauce", url: yt("Q3Rf3v13qJk") }],
  3: [{ kind: "video", title: "Causa Limeña — Layered Potato Terrine", url: yt("HROWCe1Ynkk") }],
  6: [
    { kind: "video", title: "Ceviche — Classic Peruvian Fish in Lime", url: yt("lJAqnqfzBBU") },
    { kind: "article", title: "How to make real Peruvian ceviche", url: "https://www.seriouseats.com/peruvian-ceviche-recipe" },
  ],
  10: [{ kind: "video", title: "Anticuchos — Peruvian Beef Heart Skewers", url: yt("b7N_zMv0b-U") }],
  13: [
    { kind: "video", title: "Lomo Saltado — Peruvian Beef Stir-Fry", url: yt("3VKoDBrM8Ro") },
    { kind: "article", title: "Lomo saltado recipe and technique", url: "https://www.bonappetit.com/recipe/lomo-saltado" },
  ],
  14: [{ kind: "video", title: "Ají de Gallina — Creamy Chicken in Ají Amarillo", url: yt("xt10_LWRHMw") }],
  20: [{ kind: "video", title: "Papa Rellena — Stuffed Potato Croquettes", url: yt("9P_qcQqRmRg") }],
  22: [{ kind: "video", title: "Picarones — Peruvian Sweet Potato Donuts", url: yt("Bc5nGSCMBu4") }],
  28: [{ kind: "video", title: "Seco de Cordero — Lamb Stew with Cilantro", url: yt("FfCQpDz7L-Y") }],
  31: [{ kind: "video", title: "Rocoto Relleno — Stuffed Hot Peppers", url: yt("1Q2tR_pDYeo") }],
  38: [{ kind: "video", title: "Suspiro a la Limeña — Peruvian Caramel Meringue", url: yt("fAJXH1UvPbI") }],
  4: [{ kind: "video", title: "Arroz Chaufa — Peruvian-Chinese Fried Rice", url: yt("gCN0a-RSd6E") }],
};
