// Turkish cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "kuchnia-turecka",
  name: "Kuchnia turecka",
  icon: "🇹🇷",
  description:
    "Od köfte po baklavę i künefe — konkretne dania jako poziomy. Podstawy → klasyki → kebaby, ciasto yufka i mezze → uczta. Realna droga kucharza domowego.",
  sortOrder: 111,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Çoban salatası (sałatka pasterska)", undefined, prog("techniki", 1)],
  ["Cacık (jogurt z ogórkiem)"],
  ["Mercimek çorbası (zupa z soczewicy)", undefined, prog("techniki", 2)],
  ["Menemen (jajka z pomidorami)"],
  ["Pilav (ryż z makaronem)", undefined, prog("techniki", 3)],
  ["Ezme / haydari (dipy mezze)"],
  ["Sigara böreği (paluszki z ciasta)"],
  ["Piyaz (sałatka z fasoli)"],
  ["Ugotuj 5 tureckich dań", undefined, prog("dania", 5)],
  ["Zapiekany bakłażan / warzywa"],
  // 11-25 · Klasyki
  ["Gotuj tureckie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Marynaty i mieszanki przypraw do mięs", undefined, prog("techniki", 4)],
  ["Köfte (kotleciki mięsne)"],
  ["Lahmacun (turecka pizza)", undefined, prog("techniki", 5)],
  ["Dolma (nadziewane warzywa/liście)"],
  ["İmam bayıldı (bakłażan)"],
  ["Adana / urfa kebab"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Ciasto na pide / lahmacun od podstaw", undefined, prog("techniki", 6)],
  ["Praca z ciastem yufka (börek)", undefined, prog("techniki", 7)],
  ["Pide (łódki z nadzieniem)"],
  ["Karnıyarık (bakłażan z mięsem)"],
  ["Baklava (deser)"],
  ["Mercimek köftesi / mezze zestaw"],
  ["Şakşuka"],
  // 26-45 · Średniozaawansowane
  ["Mantı (drobne pierożki) od podstaw", undefined, prog("techniki", 8)],
  ["Grillowanie kebabów (technika)", undefined, prog("techniki", 9)],
  ["Pilav w kilku wariantach (bulgur, ryż)", undefined, prog("techniki", 10)],
  ["İskender kebab"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Kuzu tandır (jagnięcina pieczona)"],
  ["Börek z ciasta yufka od podstaw", undefined, prog("techniki", 11)],
  ["Manti z sosem jogurtowo-czosnkowym"],
  ["Künefe (deser z serem i kadaif)", undefined, prog("techniki", 12)],
  ["Kısır / mezze na zimno"],
  ["Hünkar beğendi (mięso na puree z bakłażana)"],
  ["Etli nohut / gulasze z ciecierzycą"],
  ["Balık (ryba po turecku)"],
  ["Gotuj tureckie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Sütlaç / kazandibi (deser mleczny)"],
  ["Lahmacun i pide na przyjęcie"],
  ["Dolma w kilku wariantach"],
  ["Mücver (placki z cukinii)"],
  ["Revani / şekerpare (deser z syropem)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Zestaw kebabów na grilla dla gości", undefined, prog("techniki", 13)],
  ["Pełne mezze (8+ przekąsek)"],
  ["Kuzu / całe pieczyste jagnięce"],
  ["Manti na przyjęcie (drobne, ręcznie)"],
  ["Yufka cienka jak profesjonalna", undefined, prog("techniki", 14)],
  ["İçli köfte (kibbeh po turecku)"],
  ["Baklava wielowarstwowa na wysokim poziomie"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Pide/lahmacun z domowym ciastem na imprezę"],
  ["Gulasze i güveç (zapiekanki gliniane)"],
  ["Ciasta i chleby tureckie (simit, pide ekmeği)", undefined, prog("techniki", 15)],
  ["Desery z syropem na poziomie mistrzowskim", undefined, prog("techniki", 16)],
  ["Kebab + pilav + mezze jako komplet"],
  ["Danie regionalne (Gaziantep / Morze Czarne)"],
  ["Künefe / baklava na dużą imprezę"],
  ["Zupy w kilku wariantach (ezogelin, işkembe)"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Turşu (tureckie pikle)"],
  ["Zaserwuj spójne 3-daniowe menu tureckie"],
  ["Wieczór mezze z kilkunastoma przekąskami"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj tureckie dania regularnie przez pełny sezon (6 mies.)"],
  ["Baklava i yufka na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Pełny zestaw mezze z całej Turcji"],
  ["Owoce morza i ryby premium po turecku"],
  ["Kuzu tandır / całe pieczyste dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: kebaby + pilav + mezze + desery"],
  ["Danie z Gaziantep (stolica kuchni tureckiej)"],
  ["Wypieki tureckie (poğaça, açma, simit)", undefined, prog("techniki", 18)],
  ["Kebaby w kilku regionalnych stylach"],
  ["Peklowanie/suszenie w domu (pastırma, sucuk)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. południowo-wschodnie)"],
  ["Zestaw pieczystych i güveç na imprezę"],
  ["Baklava/künefe na dużą imprezę"],
  ["Zorganizuj turecką kolację tematyczną"],
  ["Całe pieczyste jagnię / kuzu çevirme na okazję"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie mezze (plating)"],
  ["Desery tureckie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania tureckiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Baklava, yufka i kebaby na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu tureckie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Turcji"],
  ["Uczta świąteczna (Bayram) — wielodaniowa"],
  ["Naucz kogoś tureckich technik (yufka, kebab, syrop)"],
  ["Ciasta yufka i desery bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar mezze z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni tureckiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde tureckie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne tureckie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated learning resources for Turkish cuisine milestones.
// Videos from Refika's Kitchen, Turkish Foods and others; articles from seriouseats, bonappetit.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Classic Çoban Salatası (Shepherd's Salad)", url: yt("G8RDKR0yhl0") }],
  3: [{ kind: "video", title: "Mercimek Çorbası — Turkish Red Lentil Soup", url: yt("kM2WBlfITDo") }],
  4: [{ kind: "video", title: "Menemen — Turkish Scrambled Eggs with Tomato", url: yt("aKR3peeAAb4") }],
  7: [{ kind: "video", title: "Crispy Sigara Böreği (Cheese Cigar Rolls)", url: yt("PAaBLzq3Dng") }],
  13: [{ kind: "video", title: "Turkish Köfte — Grilled Meatballs", url: yt("B-W_Cq-jg4Y") }],
  14: [
    { kind: "video", title: "Lahmacun — Turkish Flatbread Pizza from Scratch", url: yt("FiNYWJOqZ5M") },
    { kind: "article", title: "Lahmacun recipe guide", url: "https://www.seriouseats.com/lahmacun-turkish-pizza-recipe" },
  ],
  16: [{ kind: "video", title: "İmam Bayıldı — Stuffed Eggplant", url: yt("5oJkSN0xVaE") }],
  17: [{ kind: "video", title: "Adana Kebab at Home — Charcoal Grilled", url: yt("DZye_GM-O_8") }],
  23: [
    { kind: "video", title: "Baklava from Scratch — Layers of Yufka", url: yt("wR0ZP1kHdDk") },
    { kind: "article", title: "How to make Turkish baklava", url: "https://www.bonappetit.com/recipe/turkish-baklava" },
  ],
  26: [{ kind: "video", title: "Mantı — Turkish Dumplings with Yogurt Sauce", url: yt("5AcaGrhm2y0") }],
  29: [{ kind: "video", title: "İskender Kebab with Tomato Butter Sauce", url: yt("rF1EMkQSr-s") }],
  34: [{ kind: "video", title: "Künefe — Crispy Cheese Dessert with Kadaif", url: yt("PYYwPPaikzA") }],
};
