// Chinese cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-chinska",
  name: "Kuchnia chińska",
  icon: "🇨🇳",
  description:
    "Od smażonego ryżu po pekińską kaczkę — konkretne dania jako poziomy. Podstawy → klasyki → pierożki, makarony i wok hei → bankiet. Realna droga kucharza domowego.",
  sortOrder: 104,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Ryż na sypko i smażony ryż z jajkiem", undefined, prog("techniki", 1)],
  ["Jajecznica z pomidorami (xihongshi chao jidan)"],
  ["Bok choy / kapusta z czosnkiem na woku", undefined, prog("techniki", 2)],
  ["Zupa wonton (na gotowych zawijkach)"],
  ["Congee (kleik ryżowy) na śniadanie", undefined, prog("techniki", 3)],
  ["Sałatka z ogórka po syczuańsku"],
  ["Kurczak z orzeszkami / prosty stir-fry"],
  ["Jajko gotowane na parze (zheng shui dan)"],
  ["Ugotuj 5 chińskich dań", undefined, prog("dania", 5)],
  ["Chow mein / smażony makaron warzywny"],
  // 11-25 · Klasyki
  ["Gotuj chińskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Velveting mięsa (aksamitna marynata)", undefined, prog("techniki", 4)],
  ["Kurczak kung pao (gong bao)"],
  ["Mapo tofu", undefined, prog("techniki", 5)],
  ["Wieprzowina w sosie słodko-kwaśnym"],
  ["Zupa pikantno-kwaśna (suan la tang)"],
  ["Sajgonki / spring rolls smażone"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Jiaozi (pierożki na gotowych/prostych zawijkach)", undefined, prog("techniki", 6)],
  ["Wok hei — smażenie na dużym ogniu", undefined, prog("techniki", 7)],
  ["Char siu (wieprzowina bbq)"],
  ["Wołowina z brokułami"],
  ["Kurczak general tso / sezamowy"],
  ["Makaron w sosie sojowym (chow fun)"],
  ["Krewetki w sosie chili"],
  // 26-45 · Średniozaawansowane
  ["Jiaozi od ciasta po zawijanie", undefined, prog("techniki", 8)],
  ["Makaron dan dan", undefined, prog("techniki", 9)],
  ["Zawijanie pierożków (kilka kształtów)", undefined, prog("techniki", 10)],
  ["Wieprzowina dwukrotnie gotowana (hui guo rou)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Bakłażan w sosie rybnym (yu xiang qiezi)"],
  ["Wonton od podstaw (ciasto + farsz)", undefined, prog("techniki", 11)],
  ["Kaczka po syczuańsku / kurczak la zi ji"],
  ["Baozi (bułki na parze z farszem)", undefined, prog("techniki", 12)],
  ["Ma po / ma la — balans pikantno-drętwiący"],
  ["Zupa z kluskami i wołowiną (niu rou mian)"],
  ["Krewetki kung pao / w czosnku"],
  ["Kurczak gong bao na wysokim poziomie"],
  ["Gotuj chińskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Cong you bing (placki z dymką)"],
  ["Hong shao rou (wieprzowina w czerwonym sosie)"],
  ["Ryba na parze z imbirem i dymką"],
  ["Tofu jedwabiste / domashu"],
  ["Deser: tang yuan / mango pudding"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Xiao long bao (pierożki z zupą w środku)", undefined, prog("techniki", 13)],
  ["Ryba w całości gotowana na parze (mistrzowsko)"],
  ["Zestaw dim sum na obiad dla gości"],
  ["Hot pot (huo guo) z bulionem i dodatkami"],
  ["Makaron ciągniony ręcznie (la mian)", undefined, prog("techniki", 14)],
  ["Kaczka po pekińsku — wersja uproszczona"],
  ["Deser: sesame balls (jian dui)"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Char siu i siu yuk (chrupiący boczek)"],
  ["Har gow / shumai (dim sum)"],
  ["Ciasto na baozi i mantou na parze", undefined, prog("techniki", 15)],
  ["Wok hei na poziomie restauracyjnym", undefined, prog("techniki", 16)],
  ["Peking duck z naleśnikami i garniturem"],
  ["Syczuańskie danie z ma la na wysokim poziomie"],
  ["Deser: egg tarts (dan tat)"],
  ["Gong bao / yu xiang w wielu wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Kiszonki i pikle chińskie"],
  ["Zaserwuj spójne 3-daniowe menu chińskie"],
  ["Zestaw 4-5 dań podanych rodzinnie (rozmaitość smaków)"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj chińskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Xiao long bao z cienkim ciastem i galaretką rosołu", undefined, prog("techniki", 17)],
  ["Kaczka po pekińsku z chrupiącą skórą (pełny proces)"],
  ["Dim sum — zestaw kilku rodzajów naraz"],
  ["Makaron biang biang / ciągniony perfekcyjnie"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Bankiet: dania zimne i gorące jako sekwencja"],
  ["Danie kantońskie z owocami morza premium"],
  ["Wypieki dim sum (char siu bao, custard bao)", undefined, prog("techniki", 18)],
  ["Danie hunańskie / syczuańskie ostre na wysokim poziomie"],
  ["Krojenie i przygotowanie ryby na wiele sposobów", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. syczuańskie lub kantońskie)"],
  ["Kluski i makarony w kilku regionalnych stylach"],
  ["Hot pot na przyjęcie z domowymi dodatkami"],
  ["Zorganizuj chińską kolację tematyczną"],
  ["Pieczona / duszona całość mięsa na bankiet"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie i sekwencja dań (plating)"],
  ["Desery i wypieki chińskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania chińskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Pełny bankiet chiński (wielodaniowy, rozmaitość technik)", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu chińskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Chin"],
  ["Kolacja noworoczna (chińskie święto) — wielodaniowa"],
  ["Naucz kogoś chińskich technik (wok, pierożki, makaron)"],
  ["Dim sum i pierożki na perfekcyjnym poziomie domowym", undefined, prog("techniki", 22)],
  ["Makarony ciągnione i wok hei bez przepisu"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni chińskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde chińskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne chińskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);

import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Smażony ryż z jajkiem — technika wok", url: yt("n10xBmqehiQ") }],
  3: [{ kind: "video", title: "Bok choy z czosnkiem — szybki stir-fry", url: yt("4wZs4E9IYVE") }],
  10: [{ kind: "video", title: "Chow mein — smażony makaron chiński", url: yt("UH7bsOGdOGQ") }],
  13: [
    { kind: "video", title: "Kung pao chicken — Chinese Cooking Demystified", url: yt("bS3s_bY7Mco") },
    { kind: "article", title: "Kung pao chicken — autentyczny syczuański przepis", url: "https://www.seriouseats.com/real-deal-kung-pao-chicken-recipe" },
  ],
  14: [{ kind: "video", title: "Mapo tofu — syczuański klasyk", url: yt("ZfsZwwrTFD4") }],
  21: [{ kind: "video", title: "Char siu — kantońska wieprzowina BBQ", url: yt("ITzcSbEwxBw") }],
  26: [{ kind: "video", title: "Jiaozi — pierożki od ciasta po zawijanie", url: yt("GaEd0Bnfv3E") }],
  27: [{ kind: "article", title: "Dan dan noodles — pikantne kluski syczuańskie", url: "https://www.seriouseats.com/dan-dan-noodles-recipe" }],
  34: [{ kind: "video", title: "Baozi — bułki na parze z farszem", url: yt("Izv18uPXjso") }],
  41: [{ kind: "video", title: "Hong shao rou — duszony boczek w sosie sojowym", url: yt("UKz9ANrfg7g") }],
  46: [{ kind: "video", title: "Xiao long bao — pierożki z zupą w środku", url: yt("29IhGLBhZNc") }],
  50: [{ kind: "video", title: "La mian — makaron ciągniony ręcznie", url: yt("mzJm0HvwAMg") }],
};
