// German cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-niemiecka",
  name: "Kuchnia niemiecka",
  icon: "🇩🇪",
  description:
    "Od sznycla po sauerbraten i tort szwarcwaldzki — konkretne dania jako poziomy. Podstawy → klasyki → pieczyste, kluski i wypieki → uczta. Realna droga kucharza domowego.",
  sortOrder: 118,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Bratwurst z musztardą i pieczywem", undefined, prog("techniki", 1)],
  ["Kartoffelsalat (sałatka ziemniaczana)"],
  ["Gurkensalat (mizeria po niemiecku)", undefined, prog("techniki", 2)],
  ["Sauerkraut duszony"],
  ["Frikadellen (kotleciki mielone)", undefined, prog("techniki", 3)],
  ["Kartoffelpuffer (placki ziemniaczane)"],
  ["Brotzeit / kanapki z wędliną i serem"],
  ["Erbsensuppe (zupa grochowa)"],
  ["Ugotuj 5 niemieckich dań", undefined, prog("dania", 5)],
  ["Currywurst z frytkami"],
  // 11-25 · Klasyki
  ["Gotuj niemieckie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Panierka i smażenie sznycla (technika)", undefined, prog("techniki", 4)],
  ["Wiener/Jäger schnitzel"],
  ["Spätzle (kluski) od podstaw", undefined, prog("techniki", 5)],
  ["Rouladen (zrazy wołowe)"],
  ["Kartoffelknödel (kluski ziemniaczane)"],
  ["Gulasch (gulasz)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Ciasto na Brezel (precel z ługiem)", undefined, prog("techniki", 6)],
  ["Sauerbraten (marynowana pieczeń) — proces", undefined, prog("techniki", 7)],
  ["Schweinebraten (pieczeń wieprzowa)"],
  ["Käsespätzle"],
  ["Apfelstrudel (deser)"],
  ["Maultaschen (szwabskie pierogi)"],
  ["Linsen mit Spätzle"],
  // 26-45 · Średniozaawansowane
  ["Sauerbraten pełny z sosem korzennym", undefined, prog("techniki", 8)],
  ["Pieczyste i sosy (Bratensoße, gravy)", undefined, prog("techniki", 9)],
  ["Marynaty i peklowanie (technika)", undefined, prog("techniki", 10)],
  ["Schweinshaxe (golonka pieczona)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Königsberger Klopse (klopsiki w sosie kaparowym)"],
  ["Senfeier (jajka w sosie musztardowym)"],
  ["Maultaschen od podstaw (ciasto + farsz)", undefined, prog("techniki", 11)],
  ["Rouladen na przyjęcie z kluskami i modrą kapustą"],
  ["Brezel od podstaw z ługiem", undefined, prog("techniki", 12)],
  ["Zwiebelkuchen (placek cebulowy)"],
  ["Rinderroulade / Sauerbraten na przyjęcie"],
  ["Kartoffelknödel i Semmelknödel od podstaw"],
  ["Schwarzwälder Kirschtorte (tort szwarcwaldzki)"],
  ["Gotuj niemieckie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Bienenstich / Streuselkuchen (wypiek)"],
  ["Schnitzel w kilku wariantach na przyjęcie"],
  ["Gulasch / Eintopf na dużą imprezę"],
  ["Flammkuchen (placek alzacki)"],
  ["Rote Grütze / Quarkspeise (deser)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Schweinshaxe / Eisbein dla gości", undefined, prog("techniki", 13)],
  ["Zestaw dań na niemiecki stół świąteczny"],
  ["Gänsebraten (pieczona gęś)"],
  ["Sauerbraten reński z rodzynkami i piernikiem"],
  ["Chleby niemieckie (Vollkornbrot, Roggenbrot)", undefined, prog("techniki", 14)],
  ["Leberkäse / domowe wędliny"],
  ["Torty i wypieki warstwowe", undefined, prog("techniki", 15)],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Pieczyste na dużą imprezę"],
  ["Gulasch / Eintopf regionalne"],
  ["Brezel, Brötchen i chleby na zakwasie", undefined, prog("techniki", 16)],
  ["Sznycel + Spätzle + sos jako komplet"],
  ["Danie regionalne (bawarskie / szwabskie / północne)"],
  ["Deser: Berliner / Krapfen / Dampfnudel"],
  ["Zupy i Eintopf w kilku wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Kiszenie kapusty i marynaty niemieckie"],
  ["Zaserwuj spójne 3-daniowe menu niemieckie"],
  ["Niemiecki stół: pieczyste + kluski + wypieki"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj niemieckie dania regularnie przez pełny sezon (6 mies.)"],
  ["Pieczyste i sosy na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Pełny stół z zimnymi i ciepłymi przekąskami"],
  ["Ryby i owoce morza po niemiecku (Matjes, Forelle)"],
  ["Gänsebraten / całe pieczyste dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: pieczyste + kluski + kapusta + torty"],
  ["Danie bawarskie (Weißwurst, Haxe, Brezn) na wysokim poziomie"],
  ["Wypieki niemieckie (Stollen, Lebkuchen, torty)", undefined, prog("techniki", 18)],
  ["Pieczyste w kilku regionalnych stylach"],
  ["Peklowanie/wędzenie w domu (Wurst, Schinken)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. Bawaria lub Szwabia)"],
  ["Zestaw pieczystych na dużą imprezę"],
  ["Gänsebraten świąteczny (całość)"],
  ["Zorganizuj niemiecką kolację tematyczną"],
  ["Spanferkel / całe pieczyste na okazję"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie i plating"],
  ["Torty i wypieki niemieckie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania niemieckiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Pieczyste, kluski i wypieki na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu niemieckie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Niemiec"],
  ["Uczta świąteczna (Weihnachten) — wielodaniowa"],
  ["Naucz kogoś niemieckich technik (sznycel, kluski, chleby)"],
  ["Pieczyste i wypieki bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar sosów i klusek z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni niemieckiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde niemieckie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne niemieckie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);
