// Thai cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-tajska",
  name: "Kuchnia tajska",
  icon: "🇹🇭",
  description:
    "Od som tam po zielone curry od podstaw — konkretne dania jako poziomy. Podstawy → klasyki → pasty curry i balans smaków → uczta. Realna droga kucharza domowego.",
  sortOrder: 107,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Som tam (sałatka z zielonej papai)", undefined, prog("techniki", 1)],
  ["Tajski omlet (khai jiao)"],
  ["Pad krapow (bazylia + mięso mielone)", undefined, prog("techniki", 2)],
  ["Smażony ryż po tajsku (khao pad)"],
  ["Balans smaków: słony-słodki-kwaśny-ostry", undefined, prog("techniki", 3)],
  ["Tom yum (na gotowej paście)"],
  ["Sajgonki tajskie (por pia)"],
  ["Sałatka z ogórka / yam"],
  ["Ugotuj 5 tajskich dań", undefined, prog("dania", 5)],
  ["Ryż jaśminowy i kleisty na parze"],
  // 11-25 · Klasyki
  ["Gotuj tajskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Mleczko kokosowe i praca z nim", undefined, prog("techniki", 4)],
  ["Pad thai"],
  ["Zielone curry (na gotowej paście)", undefined, prog("techniki", 5)],
  ["Czerwone curry"],
  ["Tom kha gai (kokosowa z kurczakiem)"],
  ["Satay z sosem orzechowym"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Sticky rice na parze (mistrzowsko)", undefined, prog("techniki", 6)],
  ["Larb (pikantna sałatka mięsna)", undefined, prog("techniki", 7)],
  ["Massaman curry"],
  ["Pad see ew"],
  ["Mango sticky rice (deser)"],
  ["Panang curry"],
  ["Krewetki w tamaryndzie"],
  // 26-45 · Średniozaawansowane
  ["Pasta curry od podstaw (moździerz)", undefined, prog("techniki", 8)],
  ["Balans smaków w curry (dopracowany)", undefined, prog("techniki", 9)],
  ["Nam prik (dipy chili)", undefined, prog("techniki", 10)],
  ["Khao soi (curry z makaronem)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Tom yum od podstaw (bez gotowej pasty)"],
  ["Zielona pasta curry od zera i curry na niej", undefined, prog("techniki", 11)],
  ["Pad thai na wysokim poziomie (balans, tamaryndowiec)"],
  ["Fish cakes (tod man pla)", undefined, prog("techniki", 12)],
  ["Gaeng som (kwaśne curry)"],
  ["Boat noodles / kluski wołowe"],
  ["Yam talay (sałatka z owoców morza)"],
  ["Moo ping (grillowana wieprzowina)"],
  ["Gotuj tajskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Roti / banana roti (deser)"],
  ["Massaman od podstaw z własną pastą"],
  ["Pla rad prik (smażona ryba z chili)"],
  ["Khao man gai (kurczak z ryżem)"],
  ["Sangkhaya (deser kokosowy)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Wszystkie pasty curry od podstaw (zielona, czerwona, panang)", undefined, prog("techniki", 13)],
  ["Whole fish (cała ryba na parze / smażona)"],
  ["Zestaw dań na wspólny tajski stół dla gości"],
  ["Choo chee (curry z owocami morza)"],
  ["Kokos od orzecha (mleczko/śmietanka od podstaw)", undefined, prog("techniki", 14)],
  ["Gaeng hung lay (północne curry wieprzowe)"],
  ["Desery na bazie kokosa (kanom)"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Khao soi na przyjęcie z pełnym garniturem"],
  ["Massaman/panang na dużą imprezę"],
  ["Rzeźbienie owoców/warzyw (dekoracja)", undefined, prog("techniki", 15)],
  ["Balans i głębia smaku na poziomie mistrzowskim", undefined, prog("techniki", 16)],
  ["Pad thai / khao soi jako komplet dla gości"],
  ["Danie regionalne (Isan / północ)"],
  ["Deser: tab tim krob / bua loi"],
  ["Curry w kilku regionalnych wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Pikle i przetwory tajskie"],
  ["Zaserwuj spójne 3-daniowe menu tajskie"],
  ["Tajski stół: kilka dań o różnym profilu smaku"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj tajskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Pasty curry i nam prik na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Royal Thai — dopracowane, dekoracyjne dania"],
  ["Zestaw sałatek yam i larb naraz"],
  ["Owoce morza premium w tajskim stylu"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: curry + smażone + sałatki + desery"],
  ["Danie z regionu Isan (grill + som tam + kleisty ryż)"],
  ["Zaawansowane desery kokosowe i z ryżu", undefined, prog("techniki", 18)],
  ["Curry z 5 regionów Tajlandii"],
  ["Palenie i mielenie przypraw do past od podstaw", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. północne lub południowe)"],
  ["Makarony w kilku stylach (pad thai, see ew, boat)"],
  ["Curry/khao soi na dużą imprezę"],
  ["Zorganizuj tajską kolację tematyczną"],
  ["Grill i sałatki na przyjęcie w stylu Isan"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie i rzeźbienie (plating)"],
  ["Desery tajskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania tajskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Pasty curry i balans smaków na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu tajskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Tajlandii"],
  ["Uczta świąteczna (np. Songkran) — wielodaniowa"],
  ["Naucz kogoś tajskich technik (pasty, balans, kokos)"],
  ["Curry i makarony bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny zestaw past i sosów z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni tajskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde tajskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne tajskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);
