// Moroccan cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "kuchnia-marokanska",
  name: "Kuchnia marokańska",
  icon: "🇲🇦",
  description:
    "Od hariry po tagine i pastillę — konkretne dania jako poziomy. Podstawy → klasyki → tagine, kuskus i mieszanki przypraw → uczta. Realna droga kucharza domowego.",
  sortOrder: 116,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Marokańska sałatka (pomidor-papryka)", undefined, prog("techniki", 1)],
  ["Zaalouk (pasta z bakłażana i pomidora)"],
  ["Taktouka (sałatka z papryki)", undefined, prog("techniki", 2)],
  ["Harira (zupa z soczewicy i ciecierzycy)"],
  ["Chermoula (marynata ziołowa)", undefined, prog("techniki", 3)],
  ["Kuskus prosty (na parze)"],
  ["Khobz (chleb marokański)"],
  ["Bissara (zupa z bobu)"],
  ["Ugotuj 5 marokańskich dań", undefined, prog("dania", 5)],
  ["Msemen (placki warstwowe) na gotowo"],
  // 11-25 · Klasyki
  ["Gotuj marokańskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Ras el hanout i mieszanki przypraw od podstaw", undefined, prog("techniki", 4)],
  ["Tagine z kurczakiem, cytryną i oliwkami", undefined, prog("techniki", 5)],
  ["Kefta tagine (klopsiki z jajkiem)"],
  ["Kuskus z warzywami i mięsem"],
  ["Briouat (nadziewane trójkąciki)"],
  ["Zaalouk / taktouka na wysokim poziomie"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Ciasto na msemen / batbout od podstaw", undefined, prog("techniki", 6)],
  ["Tagine — długie duszenie w naczyniu (technika)", undefined, prog("techniki", 7)],
  ["Cytryny konserwowane (preserved lemon)"],
  ["Tagine z jagnięciną, śliwką i migdałami"],
  ["Sellou / chebakia (deser)"],
  ["Rfissa (kurczak z soczewicą i chlebem)"],
  ["Harira pełnowartościowa (ramadanowa)"],
  // 26-45 · Średniozaawansowane
  ["Kuskus na parze od podstaw (wielokrotne parowanie)", undefined, prog("techniki", 8)],
  ["Tagine w kilku wariantach (ryba, drób, jagnięcina)", undefined, prog("techniki", 9)],
  ["Chermoula i marynaty dopracowane", undefined, prog("techniki", 10)],
  ["Pastilla z kurczaka (bastilla)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Mrouzia (jagnięcina na słodko)"],
  ["Ciasto warqa / brik od podstaw", undefined, prog("techniki", 11)],
  ["Tagine z rybą i chermoulą"],
  ["Msemen i baghrir od podstaw", undefined, prog("techniki", 12)],
  ["Tanjia marrakszańska (wolno pieczona)"],
  ["Loubia (fasola w sosie)"],
  ["Seffa (słodki kuskus z mięsem)"],
  ["Chebakia / ghriba (deser)"],
  ["Gotuj marokańskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Kaab el ghazal (rogaliki migdałowe)"],
  ["Kuskus na przyjęcie (pełny, z 7 warzywami)"],
  ["Tagine na dużą imprezę"],
  ["Harira + briouat + chebakia jako zestaw iftar"],
  ["Sellou / zamita (deser)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Pastilla na wysokim poziomie (warstwy warqa)", undefined, prog("techniki", 13)],
  ["Pełny stół marokański dla gości (mezze + tagine)"],
  ["Mechoui (pieczona jagnięcina)"],
  ["Kuskus royal (kilka mięs)"],
  ["Warqa cienka jak profesjonalna", undefined, prog("techniki", 14)],
  ["Tanjia / tagine na wolnym ogniu dla gości"],
  ["Wypieki: kaab el ghazal, fekkas", undefined, prog("techniki", 15)],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Kuskus na dużą imprezę (na parze, z parownikiem)"],
  ["Pastilla z owocami morza"],
  ["Chleby marokańskie (khobz, batbout, harcha)", undefined, prog("techniki", 16)],
  ["Tagine w kilku regionalnych stylach"],
  ["Tagine + kuskus + pastilla jako komplet"],
  ["Danie regionalne (Fez / Marrakesz / południe)"],
  ["Deser: msemen z miodem / sfenj"],
  ["Marynaty i konfitury przyprawowe"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Konserwowanie (cytryny, oliwki, smen)"],
  ["Zaserwuj spójne 3-daniowe menu marokańskie"],
  ["Stół marokański: sałatki + tagine + deser"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj marokańskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Pastilla i warqa na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Pełny zestaw sałatek i przystawek marokańskich"],
  ["Owoce morza premium po marokańsku"],
  ["Mechoui / całe pieczyste dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: pastilla + tagine + kuskus + desery"],
  ["Danie z Fezu (kuchnia dworska, dopracowana)"],
  ["Wypieki marokańskie (cornes de gazelle, ghriba)", undefined, prog("techniki", 18)],
  ["Tagine w kilku regionalnych wariantach"],
  ["Suszenie/konserwowanie w domu (khlii, smen)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. Fez lub Marrakesz)"],
  ["Kuskus i tagine na dużą imprezę"],
  ["Mechoui / tanjia na przyjęcie"],
  ["Zorganizuj marokańską kolację tematyczną"],
  ["Całe pieczyste jagnię (mechoui) na okazję"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie i plating"],
  ["Desery marokańskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania marokańskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Pastilla, kuskus i tagine na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu marokańskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Maroka"],
  ["Uczta świąteczna (Eid / ramadanowy iftar) — wielodaniowa"],
  ["Naucz kogoś marokańskich technik (tagine, kuskus, warqa)"],
  ["Pastilla i kuskus bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar przypraw i marynat z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni marokańskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde marokańskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne marokańskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated learning resources for Moroccan cuisine milestones.
// Videos from CookingWithAlia, Zineb's Kitchen and others; articles from seriouseats, food52.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  2: [{ kind: "video", title: "Zaalouk — Moroccan Eggplant and Tomato Salad", url: yt("kMJ0vY_V_NI") }],
  4: [
    { kind: "video", title: "Harira — Moroccan Lentil and Chickpea Soup", url: yt("gGKLB3zIEp8") },
    { kind: "article", title: "Harira: the classic Ramadan soup", url: "https://www.seriouseats.com/harira-moroccan-lentil-soup-recipe" },
  ],
  6: [{ kind: "video", title: "Couscous — How to Steam Properly", url: yt("EbzEJHjPZuY") }],
  7: [{ kind: "video", title: "Khobz — Moroccan Semolina Bread", url: yt("_LDhJeNTm6U") }],
  13: [
    { kind: "video", title: "Chicken Tagine with Preserved Lemons and Olives", url: yt("CsZVPOxlTdI") },
    { kind: "article", title: "Moroccan chicken tagine guide", url: "https://www.bonappetit.com/recipe/chicken-tagine-with-olives-and-lemon" },
  ],
  14: [{ kind: "video", title: "Kefta Tagine — Meatballs with Eggs", url: yt("m4w3UPvf3AY") }],
  21: [{ kind: "video", title: "Preserved Lemons — How to Make at Home", url: yt("W_IRurJgFDA") }],
  22: [{ kind: "video", title: "Lamb Tagine with Prunes and Almonds", url: yt("nPpV_r3UzYg") }],
  27: [{ kind: "video", title: "Pastilla (Bastilla) — Moroccan Chicken Pie", url: yt("pEm3BhQX1Yo") }],
  33: [{ kind: "video", title: "Msemen — Flaky Moroccan Flatbread", url: yt("VBqYmS0B2VU") }],
  36: [{ kind: "article", title: "Seffa medfouna — sweet couscous with chicken", url: "https://www.food52.com/recipes/moroccan-sweet-couscous-seffa" }],
  23: [{ kind: "video", title: "Chebakia — Moroccan Sesame Cookies", url: yt("rAf_oJ83sPE") }],
};
