// Indian cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-indyjska",
  name: "Kuchnia indyjska",
  icon: "🇮🇳",
  description:
    "Od dal po dum biryani — konkretne dania jako poziomy. Podstawy → klasyki → chleby, curry i mieszanki przypraw → thali. Realna droga kucharza domowego.",
  sortOrder: 106,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Dal tadka (soczewica z zaprawą)", undefined, prog("techniki", 1)],
  ["Jeera rice (ryż z kminem)"],
  ["Raita (jogurt z ogórkiem)", undefined, prog("techniki", 2)],
  ["Aloo gobi (ziemniaki z kalafiorem)"],
  ["Tadka — temperowanie przypraw w ghee", undefined, prog("techniki", 3)],
  ["Chana masala (ciecierzyca)"],
  ["Masala chai"],
  ["Sałatka kachumber"],
  ["Ugotuj 5 indyjskich dań", undefined, prog("dania", 5)],
  ["Bhindi / prosta sabzi warzywna"],
  // 11-25 · Klasyki
  ["Gotuj indyjskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Garam masala i mieszanki przypraw od podstaw", undefined, prog("techniki", 4)],
  ["Butter chicken (murgh makhani)"],
  ["Palak paneer", undefined, prog("techniki", 5)],
  ["Chicken tikka (marynowany)"],
  ["Roti / chapati (chleb od podstaw)"],
  ["Samosa (smażone pierożki)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Chapati puchnące na ogniu (phulka)", undefined, prog("techniki", 6)],
  ["Dal makhani (długo duszona)", undefined, prog("techniki", 7)],
  ["Biryani proste (jednogarnkowe)"],
  ["Korma (łagodne curry na orzechach)"],
  ["Paneer domowy (twaróg indyjski)"],
  ["Chicken curry domowe"],
  ["Pakora / bhaji"],
  // 26-45 · Średniozaawansowane
  ["Naan na patelni / pod grillem", undefined, prog("techniki", 8)],
  ["Bazy curry: cebula-imbir-czosnek + pomidory (bhuna)", undefined, prog("techniki", 9)],
  ["Marynaty tandoori (jogurt + przyprawy)", undefined, prog("techniki", 10)],
  ["Rogan josh (jagnięcina)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Chole bhature"],
  ["Biryani dum (warstwowe, na parze)", undefined, prog("techniki", 11)],
  ["Malai kofta"],
  ["Dosa i idli — rozczyn fermentowany", undefined, prog("techniki", 12)],
  ["Sambar i chutney kokosowy"],
  ["Paneer tikka masala"],
  ["Aloo paratha (nadziewany placek)"],
  ["Fish curry (np. z Goa/Kerali)"],
  ["Gotuj indyjskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Gulab jamun (deser)"],
  ["Tandoori chicken (bez tandoora, w piekarniku)"],
  ["Vindaloo (ostre curry)"],
  ["Baingan bharta"],
  ["Kheer / gajar halwa (deser)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Hyderabadi dum biryani (kaczka/koza/kurczak)", undefined, prog("techniki", 13)],
  ["Naan i kulcha na wysokim poziomie"],
  ["Zestaw thali (kilka dań naraz)"],
  ["Butter chicken + dal + naan jako komplet"],
  ["Dosa masala z fermentacją i ghee", undefined, prog("techniki", 14)],
  ["Nihari / haleem (długo duszone)"],
  ["Jalebi (deser smażony)"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Biryani dla gości (pełny dum proces)"],
  ["Chettinad / curry regionalne z południa"],
  ["Chleby tandoori-style i paratha wielowarstwowa", undefined, prog("techniki", 15)],
  ["Mieszanki masala palone i mielone samodzielnie", undefined, prog("techniki", 16)],
  ["Rogan josh / korma na przyjęcie"],
  ["Danie regionalne (bengalskie / pendżabskie)"],
  ["Rasgulla / rasmalai (deser mleczny)"],
  ["Curry w kilku wariantach baz (bhuna, korma, jalfrezi)"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Achar / pikle indyjskie"],
  ["Zaserwuj spójne 3-daniowe menu indyjskie"],
  ["Thali z kilkoma curry, ryżem, chlebem i deserem"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj indyjskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Biryani na poziomie mistrzowskim (aromat, warstwy)", undefined, prog("techniki", 17)],
  ["Pełny thali z 6-8 elementów"],
  ["Dania tandoori z pełnym zestawem marynat"],
  ["Dosa/idli/uttapam z doskonałym rozczynem"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: biryani + curry + chleby + desery"],
  ["Danie z owoców morza (curry z Kerali)"],
  ["Indyjskie słodycze (barfi, ladoo, kaju katli)", undefined, prog("techniki", 18)],
  ["Curry regionalne z kilku stanów naraz"],
  ["Palenie i mieszanie własnych mieszanek masala", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. pendżabskie lub południowe)"],
  ["Chleby: naan, kulcha, bhatura, paratha — zestaw"],
  ["Biryani/nihari na dużą imprezę"],
  ["Zorganizuj indyjską kolację tematyczną"],
  ["Dania świąteczne (Diwali / Eid) — kilka naraz"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie thali (plating)"],
  ["Indyjskie słodycze na poziomie cukierni (mithai)"],
  ["Własna, autorska interpretacja dania indyjskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Dum biryani i mieszanki masala na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu indyjskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Indii"],
  ["Uczta świąteczna (Diwali) — wielodaniowa"],
  ["Naucz kogoś indyjskich technik (tadka, masala, chleby)"],
  ["Chleby i biryani bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny zestaw przypraw i baz curry z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni indyjskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde indyjskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne indyjskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);
