// Brazilian cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "kuchnia-brazylijska",
  name: "Kuchnia brazylijska",
  icon: "🇧🇷",
  description:
    "Od pão de queijo po feijoadę i moquecę — konkretne dania jako poziomy. Podstawy → klasyki → churrasco, gulasze i przekąski → uczta. Realna droga kucharza domowego.",
  sortOrder: 117,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Arroz e feijão (ryż z fasolą)", undefined, prog("techniki", 1)],
  ["Pão de queijo (serowe bułeczki)"],
  ["Vinagrete (brazylijska salsa)", undefined, prog("techniki", 2)],
  ["Farofa (podprażona mąka maniokowa)"],
  ["Feijão temperado (doprawiona fasola)", undefined, prog("techniki", 3)],
  ["Brigadeiro (deser)"],
  ["Salada de maionese"],
  ["Couve refogada (jarmuż)"],
  ["Ugotuj 5 brazylijskich dań", undefined, prog("dania", 5)],
  ["Pastel / coxinha na gotowo"],
  // 11-25 · Klasyki
  ["Gotuj brazylijskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Refogado — baza z cebuli i czosnku", undefined, prog("techniki", 4)],
  ["Feijoada (gulasz z fasoli i mięs)", undefined, prog("techniki", 5)],
  ["Coxinha (krokieciki z kurczakiem)"],
  ["Escondidinho (zapiekanka z maniokiem)"],
  ["Picanha na patelni / grillu"],
  ["Moqueca (gulasz rybny na mleczku kokosowym)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Ciasto na coxinha / pastel od podstaw", undefined, prog("techniki", 6)],
  ["Churrasco — grillowanie mięs (technika)", undefined, prog("techniki", 7)],
  ["Feijão tropeiro"],
  ["Bobó de camarão (krewetki z maniokiem)"],
  ["Pudim de leite (deser)"],
  ["Strogonoff brazylijski"],
  ["Pão de queijo od podstaw (polvilho)"],
  // 26-45 · Średniozaawansowane
  ["Feijoada pełnowartościowa z dodatkami", undefined, prog("techniki", 8)],
  ["Churrasco z kilkoma rodzajami mięs", undefined, prog("techniki", 9)],
  ["Marynaty i chimichurri", undefined, prog("techniki", 10)],
  ["Moqueca baiana z dendę i mleczkiem"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Acarajé (smażone kuleczki z fasoli)"],
  ["Coxinha i salgados w kilku wariantach", undefined, prog("techniki", 11)],
  ["Vatapá / caruru"],
  ["Pastel smażony od podstaw", undefined, prog("techniki", 12)],
  ["Feijoada na przyjęcie z farofą i couve"],
  ["Bacalhau à brasileira"],
  ["Galinhada (ryż z kurczakiem)"],
  ["Beijinho / quindim (deser)"],
  ["Gotuj brazylijskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Bolo de rolo / brigadeiro gourmet"],
  ["Churrasco na przyjęcie (picanha, linguiça)"],
  ["Moqueca na dużą imprezę"],
  ["Baião de dois"],
  ["Cocada / canjica (deser)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Feijoada completa dla gości (pełny zestaw dodatków)", undefined, prog("techniki", 13)],
  ["Pełny churrasco z rodizio (kilka mięs kolejno)"],
  ["Peixe / owoce morza po bahijsku"],
  ["Tutu de feijão / virado"],
  ["Vaca atolada (żeberka z maniokiem)"],
  ["Salgados (coxinha, kibe, esfiha) od podstaw", undefined, prog("techniki", 14)],
  ["Leitão / pieczysta wieprzowina"],
  ["Bolo i desery warstwowe", undefined, prog("techniki", 15)],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Churrasco na dużą imprezę"],
  ["Moqueca / bobó na przyjęcie"],
  ["Chleby i tapioka od podstaw", undefined, prog("techniki", 16)],
  ["Feijoada + farofa + couve + laranja jako komplet"],
  ["Danie regionalne (Bahia / Minas / Amazonia)"],
  ["Deser: brigadeiro gourmet / pavê"],
  ["Gulasze i moquecas w kilku wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Konserwy i marynaty brazylijskie"],
  ["Zaserwuj spójne 3-daniowe menu brazylijskie"],
  ["Stół brazylijski: churrasco + dodatki + desery"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj brazylijskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Feijoada i churrasco na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Pełny zestaw salgados na stół"],
  ["Owoce morza premium po bahijsku"],
  ["Rodizio / churrasco dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: churrasco + feijoada + moqueca + desery"],
  ["Danie z Bahii (dendę, kokos, owoce morza)"],
  ["Wypieki i desery brazylijskie (bolo, brigadeiro)", undefined, prog("techniki", 18)],
  ["Moquecas i gulasze w kilku regionalnych stylach"],
  ["Peklowanie/suszenie w domu (carne seca, linguiça)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. Bahia lub Minas Gerais)"],
  ["Churrasco na dużą imprezę (cała picanha, kostrzewa)"],
  ["Feijoada na dużą imprezę"],
  ["Zorganizuj brazylijską kolację tematyczną"],
  ["Całe pieczyste (leitão / cordeiro) na okazję"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie i plating"],
  ["Desery brazylijskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania brazylijskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Feijoada, churrasco i salgados na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu brazylijskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Brazylii"],
  ["Uczta świąteczna (Ceia de Natal) — wielodaniowa"],
  ["Naucz kogoś brazylijskich technik (feijoada, churrasco, salgados)"],
  ["Feijoada i churrasco bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar salgados i deserów z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni brazylijskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde brazylijskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne brazylijskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated learning resources for Brazilian cuisine milestones.
// Videos from popular Brazilian cooking channels; articles from seriouseats, bonappetit.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Arroz e Feijão — Perfect Brazilian Rice and Beans", url: yt("PA5R-oXxuMU") }],
  2: [
    { kind: "video", title: "Pão de Queijo — Brazilian Cheese Bread", url: yt("W6Tu-xnl2AM") },
    { kind: "article", title: "Pão de queijo recipe with tapioca flour", url: "https://www.seriouseats.com/easy-brazilian-cheese-bread-recipe" },
  ],
  6: [{ kind: "video", title: "Brigadeiro — Brazilian Chocolate Truffles", url: yt("5Mf1Z4rZG3s") }],
  13: [
    { kind: "video", title: "Feijoada — Traditional Brazilian Black Bean Stew", url: yt("RZ8oJlpXBXA") },
    { kind: "article", title: "Feijoada completa — the national dish of Brazil", url: "https://www.bonappetit.com/recipe/feijoada" },
  ],
  14: [{ kind: "video", title: "Coxinha — Brazilian Chicken Croquettes", url: yt("j-5qfVlqLa8") }],
  16: [{ kind: "video", title: "Picanha — How to Grill Brazilian Style", url: yt("_2vFl5oHrik") }],
  17: [{ kind: "video", title: "Moqueca — Brazilian Fish Stew with Coconut Milk", url: yt("mYo0cgz_3Pw") }],
  23: [{ kind: "video", title: "Pudim de Leite — Brazilian Flan", url: yt("rlw0cqsMTjM") }],
  27: [{ kind: "video", title: "Moqueca Baiana with Dendê Oil", url: yt("Cxhbb0QFJJY") }],
  30: [{ kind: "video", title: "Acarajé — Bahian Black-Eyed Pea Fritters", url: yt("s4Q1dLkXzFw") }],
  33: [{ kind: "article", title: "Vatapá — creamy shrimp stew from Bahia", url: "https://www.food52.com/recipes/brazilian-vatapa-shrimp" }],
  40: [{ kind: "video", title: "Brigadeiro Gourmet — Fancy Variations", url: yt("n5-Sxgz-k9o") }],
};
