// Greek cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-grecka",
  name: "Kuchnia grecka",
  icon: "🇬🇷",
  description:
    "Od greckiej sałatki po moussakę i baklavę — konkretne dania jako poziomy. Podstawy → klasyki → ciasto filo, sosy i pieczyste → uczta. Realna droga kucharza domowego.",
  sortOrder: 109,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Horiatiki (grecka sałatka)", undefined, prog("techniki", 1)],
  ["Tzatziki"],
  ["Hummus / fava (pasta z grochu)", undefined, prog("techniki", 2)],
  ["Pita i dipy"],
  ["Souvlaki (szaszłyki, marynata)", undefined, prog("techniki", 3)],
  ["Saganaki (smażony ser)"],
  ["Gigantes (fasola w sosie pomidorowym)"],
  ["Melitzanosalata (pasta z bakłażana)"],
  ["Ugotuj 5 greckich dań", undefined, prog("dania", 5)],
  ["Keftedes (greckie klopsiki)"],
  // 11-25 · Klasyki
  ["Gotuj greckie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Sos béchamel do zapiekanek", undefined, prog("techniki", 4)],
  ["Gyros (mięso + tzatziki + pita)"],
  ["Spanakopita (szpinak w cieście filo)", undefined, prog("techniki", 5)],
  ["Gemista (nadziewane warzywa)"],
  ["Briam (zapiekane warzywa)"],
  ["Moussaka (bakłażan + mięso + beszamel)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Praca z gotowym ciastem filo", undefined, prog("techniki", 6)],
  ["Avgolemono (zupa/sos jajeczno-cytrynowy)", undefined, prog("techniki", 7)],
  ["Dolmades (gołąbki w liściach winogron)"],
  ["Pastitsio (zapiekanka z makaronem)"],
  ["Baklava (deser)"],
  ["Souvlaki na przyjęcie z garniturami"],
  ["Fasolada (zupa fasolowa)"],
  // 26-45 · Średniozaawansowane
  ["Moussaka od podstaw z idealnym beszamelem", undefined, prog("techniki", 8)],
  ["Marynaty do mięs (oregano, cytryna, oliwa)", undefined, prog("techniki", 9)],
  ["Grillowanie mięs i ryb po grecku", undefined, prog("techniki", 10)],
  ["Kleftiko (jagnięcina pieczona)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Stifado (gulasz z cebulą)"],
  ["Dolmades od podstaw (zawijanie)", undefined, prog("techniki", 11)],
  ["Kotosoupa avgolemono"],
  ["Ciasto filo domowe (rozciąganie)", undefined, prog("techniki", 12)],
  ["Galaktoboureko (deser z kremem w filo)"],
  ["Soutzoukakia (klopsiki w sosie)"],
  ["Gemista pełne (ryż + zioła)"],
  ["Oktapodi (ośmiornica grillowana)"],
  ["Gotuj greckie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Loukoumades (pączki w syropie)"],
  ["Pastitsio na przyjęcie"],
  ["Youvetsi (mięso z makaronem orzo)"],
  ["Horta (dzikie zielone warzywa)"],
  ["Ravani / karydopita (deser z syropem)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Moussaka i pastitsio jako komplet dla gości", undefined, prog("techniki", 13)],
  ["Zestaw meze (8+ przekąsek)"],
  ["Kleftiko / jagnięcina na dużą imprezę"],
  ["Psari plaki (ryba zapiekana)"],
  ["Ciasto filo cienkie jak profesjonalne", undefined, prog("techniki", 14)],
  ["Kokoretsi / kontosouvli (grill obrotacyjny)"],
  ["Baklava na wysokim poziomie (warstwy, syrop)"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Gyros z pełnym garniturem i domową pitą"],
  ["Youvetsi / kleftiko na przyjęcie"],
  ["Pita i chleby greckie od podstaw", undefined, prog("techniki", 15)],
  ["Avgolemono opanowane w kilku daniach", undefined, prog("techniki", 16)],
  ["Zestaw pieczystych i zapiekanek dla gości"],
  ["Danie wyspiarskie (kreteńskie / cykladzkie)"],
  ["Deser: kataifi / bougatsa"],
  ["Ryby i owoce morza w kilku wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Kiszonki i marynaty greckie"],
  ["Zaserwuj spójne 3-daniowe menu greckie"],
  ["Wieczór meze z kilkunastoma przekąskami"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj greckie dania regularnie przez pełny sezon (6 mies.)"],
  ["Ciasta filo (spanakopita, galaktoboureko) mistrzowsko", undefined, prog("techniki", 17)],
  ["Pełny zestaw meze z całej Grecji"],
  ["Owoce morza premium (ośmiornica, kalmary, krewetki)"],
  ["Kleftiko/kokoretsi dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: pieczyste + zapiekanki + meze + desery"],
  ["Danie kreteńskie (dieta kreteńska, dzikie zioła)"],
  ["Wypieki greckie (tsoureki, koulourakia)", undefined, prog("techniki", 18)],
  ["Zapiekanki regionalne w kilku wariantach"],
  ["Peklowanie/marynowanie oliwek i serów", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. kreteńskie lub macedońskie)"],
  ["Zestaw grillowanych mięs i ryb na imprezę"],
  ["Baklava/galaktoboureko na dużą imprezę"],
  ["Zorganizuj grecką kolację tematyczną"],
  ["Pieczona jagnięcina wielkanocna (całość)"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie meze (plating)"],
  ["Desery greckie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania greckiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Ciasto filo i zapiekanki na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu greckie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Grecji"],
  ["Uczta wielkanocna (Pascha) — wielodaniowa"],
  ["Naucz kogoś greckich technik (filo, beszamel, grill)"],
  ["Zapiekanki i filo bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar meze z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni greckiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde greckie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne greckie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);

import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  2: [{ kind: "video", title: "Tzatziki — Akis Petretzikis", url: yt("d5wJa5JEeJg") }],
  5: [{ kind: "video", title: "Souvlaki — marynata i grillowanie", url: yt("RWVBPsa7Kp0") }],
  6: [{ kind: "video", title: "Saganaki — smażony ser po grecku", url: yt("SoAL7gIcna4") }],
  10: [{ kind: "video", title: "Keftedes — greckie klopsiki", url: yt("vVRLkCnDezo") }],
  13: [{ kind: "article", title: "Gyros — domowy przepis z marynowanym mięsem", url: "https://www.recipetineats.com/greek-chicken-gyros/" }],
  14: [{ kind: "video", title: "Spanakopita — szpinak w cieście filo", url: yt("MNRbCGQFsSM") }],
  17: [
    { kind: "video", title: "Moussaka — Akis Petretzikis", url: yt("JO8GHhkuMGs") },
    { kind: "article", title: "Moussaka — klasyczny grecki przepis", url: "https://www.seriouseats.com/moussaka-recipe" },
  ],
  21: [{ kind: "video", title: "Dolmades — gołąbki w liściach winogron", url: yt("0m0qaSH3oiI") }],
  23: [{ kind: "video", title: "Baklava — warstwy filo, orzechy i syrop", url: yt("qJjwMCETQnE") }],
  29: [{ kind: "video", title: "Kleftiko — jagnięcina wolno pieczona", url: yt("pJxZ0pv-6WI") }],
  31: [{ kind: "article", title: "Stifado — grecki gulasz z małymi cebulkami", url: "https://www.recipetineats.com/greek-beef-stifado/" }],
  35: [{ kind: "video", title: "Galaktoboureko — krem w cieście filo z syropem", url: yt("nBmR1PKOKX8") }],
};
