// Japanese cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-japonska",
  name: "Kuchnia japońska",
  icon: "🇯🇵",
  description:
    "Od zupy miso po kaiseki — konkretne dania jako poziomy. Podstawy → klasyki → sushi, ramen i tempura → pełne menu. Realna droga kucharza domowego.",
  sortOrder: 103,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Ugotuj ryż do sushi/dań (perfekcyjny gohan)", undefined, prog("techniki", 1)],
  ["Zupa miso (dashi + miso + tofu)"],
  ["Tamagoyaki (japoński omlet)", undefined, prog("techniki", 2)],
  ["Onigiri (ryżowe trójkąty z nadzieniem)"],
  ["Edamame i szybkie przystawki", undefined, prog("techniki", 3)],
  ["Gyudon (ryż z wołowiną)"],
  ["Kurczak teriyaki"],
  ["Sunomono (sałatka z ogórka)"],
  ["Ugotuj 5 japońskich dań", undefined, prog("dania", 5)],
  ["Miso z dodatkami / prosty domburi"],
  // 11-25 · Klasyki
  ["Gotuj japońskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Dashi od podstaw (kombu + katsuobushi)", undefined, prog("techniki", 4)],
  ["Tonkatsu (panierowany kotlet)"],
  ["Ryż curry (karē raisu)", undefined, prog("techniki", 5)],
  ["Yakitori (szaszłyki z kurczaka)"],
  ["Katsudon (kotlet na ryżu z jajkiem)"],
  ["Gyoza (pierożki od podstaw)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Ramen shoyu (na gotowym bulionie + dodatki)", undefined, prog("techniki", 6)],
  ["Udon w bulionie", undefined, prog("techniki", 7)],
  ["Chirashi (ryż z dodatkami)"],
  ["Łosoś teriyaki"],
  ["Agedashi tofu"],
  ["Oyakodon (kurczak + jajko na ryżu)"],
  ["Karaage (japoński smażony kurczak)"],
  // 26-45 · Średniozaawansowane
  ["Sushi maki (rolki) — formowanie ryżu", undefined, prog("techniki", 8)],
  ["Tempura (warzywa i krewetki w cieście)", undefined, prog("techniki", 9)],
  ["Sushi ryż z prawidłowym zalewaniem (shari)", undefined, prog("techniki", 10)],
  ["Okonomiyaki (placek osaka)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Takoyaki (kulki z ośmiornicą)"],
  ["Nigiri sushi (formowanie na dłoni)", undefined, prog("techniki", 11)],
  ["Katsu curry"],
  ["Yakisoba (smażony makaron)"],
  ["Gyoza własne od ciasta po smażenie na parze", undefined, prog("techniki", 12)],
  ["Chawanmushi (jajeczny budyń na parze)"],
  ["Nikujaga (gulasz ziemniaczano-mięsny)"],
  ["Tonjiru (zupa miso z wieprzowiną)"],
  ["Gotuj japońskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Onigirazu / bento zestaw"],
  ["Ramen miso na własnym bulionie"],
  ["Sukiyaki (jednogarnkowe)"],
  ["Tempura z sosem tentsuyu na wysokim poziomie"],
  ["Dorayaki / mochi (deser)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Ramen tonkotsu (długo gotowany bulion wieprzowy)", undefined, prog("techniki", 13)],
  ["Uramaki i futomaki (odwrócone i grube rolki)"],
  ["Sushi na zestaw dla gości (miks nigiri + maki)"],
  ["Shabu-shabu (fondue z dashi)"],
  ["Ręcznie robione soba (mąka gryczana)", undefined, prog("techniki", 14)],
  ["Unagi no kabayaki (węgorz w sosie)"],
  ["Wagashi proste (dorayaki, daifuku)"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Ramen z ajitama, chashu i domowym tare"],
  ["Chashu (marynowana wieprzowina)"],
  ["Ręcznie robione udon", undefined, prog("techniki", 15)],
  ["Tempura moriawase (zestaw) perfekcyjna", undefined, prog("techniki", 16)],
  ["Tonkatsu + garnitury jako komplet"],
  ["Gyudon / donburi na wyższym poziomie"],
  ["Matcha desery (roll cake, tiramisu matcha)"],
  ["Kakuni (duszony boczek)"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Tsukemono (kiszonki japońskie)"],
  ["Zaserwuj spójne 3-daniowe menu japońskie"],
  ["Zestaw sushi + zupa + przystawki jako komplet"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj japońskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Nigiri na poziomie sushi-ya (ryż + krojenie ryby)", undefined, prog("techniki", 17)],
  ["Kaiseki — pojedyncze dania sezonowe"],
  ["Dashi w kilku wariantach (ichiban, niban)"],
  ["Tempura z warzyw sezonowych i owoców morza (mistrzowsko)"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Ramen w 3 stylach (shoyu, miso, tonkotsu)"],
  ["Soba i tsuyu na poziomie profesjonalnym"],
  ["Wagashi zaawansowane (nerikiri)", undefined, prog("techniki", 18)],
  ["Tempura-don / kaisendon premium"],
  ["Krojenie ryby (sashimi) na wysokim poziomie", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. Kansai lub Hokkaido)"],
  ["Okonomiyaki hiroszimskie (warstwowe)"],
  ["Nabe / one-pot na przyjęcie"],
  ["Zorganizuj japońską kolację tematyczną"],
  ["Tonkotsu z pełnym garniturem od zera"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Bento artystyczne / plating japoński"],
  ["Desery matcha i wagashi na poziomie cukierni"],
  ["Własna, autorska interpretacja dania japońskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Kaiseki — wielodaniowe sezonowe menu", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu japońskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Japonii"],
  ["Osechi — świąteczny zestaw noworoczny"],
  ["Naucz kogoś japońskich technik (sushi, dashi, tempura)"],
  ["Sushi i sashimi na perfekcyjnym poziomie domowym", undefined, prog("techniki", 22)],
  ["Ramen od bulionu po tare i makaron bez przepisu"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni japońskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde japońskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne japońskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);
