// Spanish cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-hiszpanska",
  name: "Kuchnia hiszpańska",
  icon: "🇪🇸",
  description:
    "Od tortilli po paellę z socarrat — konkretne dania jako poziomy. Podstawy → tapas i klasyki → paella, sofrito i croquetas → uczta. Realna droga kucharza domowego.",
  sortOrder: 108,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Tortilla española (omlet ziemniaczany)", undefined, prog("techniki", 1)],
  ["Pan con tomate"],
  ["Gazpacho (chłodnik)", undefined, prog("techniki", 2)],
  ["Patatas bravas z sosem"],
  ["Aioli (emulsja czosnkowa)", undefined, prog("techniki", 3)],
  ["Ensalada mixta"],
  ["Gambas al ajillo (krewetki w czosnku)"],
  ["Chorizo al vino"],
  ["Ugotuj 5 hiszpańskich dań", undefined, prog("dania", 5)],
  ["Pincho / prosta tapa"],
  // 11-25 · Tapas i klasyki
  ["Gotuj hiszpańskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Sofrito — baza z cebuli, pomidora i papryki", undefined, prog("techniki", 4)],
  ["Albóndigas (pulpeciki w sosie)"],
  ["Pisto (hiszpańskie ratatouille)", undefined, prog("techniki", 5)],
  ["Tortilla z odwróceniem na patelni (technika)"],
  ["Calamares a la romana (kalmary)"],
  ["Paella prosta (kurczak/warzywa)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Croquetas — beszamel + panierka", undefined, prog("techniki", 6)],
  ["Socarrat — chrupiąca warstwa ryżu w paelli", undefined, prog("techniki", 7)],
  ["Pulpo a la gallega (ośmiornica)"],
  ["Tortilla de patatas idealna (soczysta w środku)"],
  ["Crema catalana (deser)"],
  ["Empanada gallega"],
  ["Pimientos de padrón"],
  // 26-45 · Średniozaawansowane
  ["Paella valenciana (klasyczna)", undefined, prog("techniki", 8)],
  ["Sofrito dopracowany jako baza dań", undefined, prog("techniki", 9)],
  ["Marynaty i adobo do mięs", undefined, prog("techniki", 10)],
  ["Fabada asturiana (fasola z mięsami)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Paella de marisco (owoce morza)"],
  ["Croquetas w kilku wariantach od podstaw", undefined, prog("techniki", 11)],
  ["Rabo de toro (ogon wołowy)"],
  ["Fideuà (paella na makaronie)", undefined, prog("techniki", 12)],
  ["Salmorejo"],
  ["Bacalao al pil pil"],
  ["Migas"],
  ["Churros con chocolate"],
  ["Gotuj hiszpańskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Flan / natillas (deser)"],
  ["Cocido madrileño"],
  ["Pollo al ajillo"],
  ["Escalivada"],
  ["Tarta de Santiago (deser migdałowy)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Paella mixta z idealnym socarrat", undefined, prog("techniki", 13)],
  ["Zestaw tapas (6-8 rodzajów) na przyjęcie"],
  ["Cochinillo / lechazo (pieczyste)"],
  ["Romesco i sosy katalońskie"],
  ["Praca z owocami morza (czyszczenie, przygotowanie)", undefined, prog("techniki", 14)],
  ["Callos (flaki po hiszpańsku)"],
  ["Ensaimada / wypiek drożdżowy"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Paella na dużą patelnię dla gości"],
  ["Fabada / cocido pełnowartościowe"],
  ["Croquetas na poziomie baru tapas", undefined, prog("techniki", 15)],
  ["Suquet / zarzuela (gulasz z owoców morza)", undefined, prog("techniki", 16)],
  ["Zestaw paella + tapas jako komplet"],
  ["Danie regionalne (baskijskie / andaluzyjskie)"],
  ["Deser: torrijas / leche frita"],
  ["Ryż w kilku wariantach (seco, meloso, caldoso)"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Konserwy i marynaty (boquerones, escabeche)"],
  ["Zaserwuj spójne 3-daniowe menu hiszpańskie"],
  ["Wieczór tapas z kilkunastoma przekąskami"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj hiszpańskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Paella i ryże na poziomie mistrzowskim (socarrat, aromat)", undefined, prog("techniki", 17)],
  ["Pełny zestaw pintxos baskijskich"],
  ["Owoce morza premium (percebes, langostinos)"],
  ["Zarzuela / suquet dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: paella + tapas + pieczyste + desery"],
  ["Danie katalońskie z sosami (romesco, allioli)"],
  ["Wypieki hiszpańskie (ensaimada, tarta)", undefined, prog("techniki", 18)],
  ["Ryże i paelle w kilku regionalnych wariantach"],
  ["Peklowanie/wędzenie w domu (jamón-style, chorizo)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. baskijskie lub walenckie)"],
  ["Zestaw pieczystych (cochinillo/cordero) na imprezę"],
  ["Paella dla dużej grupy na wolnym ogniu"],
  ["Zorganizuj hiszpańską kolację tematyczną"],
  ["Cocido / fabada na dużą imprezę"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie tapas (plating)"],
  ["Desery hiszpańskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania hiszpańskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Paella i sofrito na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu hiszpańskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Hiszpanii"],
  ["Uczta świąteczna (Nochebuena) — wielodaniowa"],
  ["Naucz kogoś hiszpańskich technik (sofrito, paella, croquetas)"],
  ["Paella i ryże bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar tapas z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni hiszpańskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde hiszpańskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne hiszpańskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);
