// Korean cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "kuchnia-koreanska",
  name: "Kuchnia koreańska",
  icon: "🇰🇷",
  description:
    "Od bibimbap po własne kimchi — konkretne dania jako poziomy. Podstawy → klasyki → fermentacja, banchan i grill → uczta. Realna droga kucharza domowego.",
  sortOrder: 113,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Ryż koreański i proste banchan", undefined, prog("techniki", 1)],
  ["Gyeran mari (zwijany omlet)"],
  ["Oi muchim (sałatka z ogórka)", undefined, prog("techniki", 2)],
  ["Bibimbap (miska z ryżem i warzywami)"],
  ["Balans gochujang/doenjang (pasty)", undefined, prog("techniki", 3)],
  ["Japchae (szklany makaron)"],
  ["Pajeon (placek z dymką)"],
  ["Kongnamul (kiełki fasoli)"],
  ["Ugotuj 5 koreańskich dań", undefined, prog("dania", 5)],
  ["Tteokbokki (kluski ryżowe w sosie)"],
  // 11-25 · Klasyki
  ["Gotuj koreańskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Marynata bulgogi (baza sosów)", undefined, prog("techniki", 4)],
  ["Bulgogi (marynowana wołowina)"],
  ["Kimchi jjigae (gulasz z kimchi)", undefined, prog("techniki", 5)],
  ["Kimbap (rolki ryżowe)"],
  ["Sundubu jjigae (tofu jjigae)"],
  ["Dak galbi (kurczak na ostro)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Zestaw banchan (kilka dodatków naraz)", undefined, prog("techniki", 6)],
  ["Fermentacja: proste kimchi (mak kimchi)", undefined, prog("techniki", 7)],
  ["Galbi (marynowane żeberka)"],
  ["Koreański smażony kurczak (yangnyeom)"],
  ["Doenjang jjigae"],
  ["Bibimbap dolsot (w gorącym kamieniu)"],
  ["Haemul pajeon (z owocami morza)"],
  // 26-45 · Średniozaawansowane
  ["Baechu kimchi (całe kapusty) od podstaw", undefined, prog("techniki", 8)],
  ["Pasty i sosy (ssamjang, gochujang) dopracowane", undefined, prog("techniki", 9)],
  ["Grillowanie mięs (samgyeopsal, galbi)", undefined, prog("techniki", 10)],
  ["Galbijjim (duszone żeberka)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Bossam (gotowana wieprzowina z kimchi)"],
  ["Kimchi w kilku wariantach (kkakdugi, oi sobagi)", undefined, prog("techniki", 11)],
  ["Budae jjigae (gulasz armijny)"],
  ["Jeon zestaw (placuszki różne)", undefined, prog("techniki", 12)],
  ["Naengmyeon (zimny makaron)"],
  ["Samgyetang (zupa z kurczaka z żeń-szeniem)"],
  ["Tteokguk (zupa z klusek ryżowych)"],
  ["Jjajangmyeon (makaron w czarnym sosie)"],
  ["Gotuj koreańskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Hotteok / bungeoppang (deser uliczny)"],
  ["Bibimbap i banchan na przyjęcie"],
  ["Bulgogi / galbi na grill dla gości"],
  ["Sundubu / doenjang na wysokim poziomie"],
  ["Bingsu / tteok (deser)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Pełny stół z 8+ banchan", undefined, prog("techniki", 13)],
  ["Koreański grill (KBBQ) w domu dla gości"],
  ["Jokbal (marynowane nóżki)"],
  ["Haemul / owoce morza po koreańsku"],
  ["Fermentacja na poziomie mistrzowskim (kimchi dojrzewające)", undefined, prog("techniki", 14)],
  ["Galbijjim / jjim na przyjęcie"],
  ["Desery koreańskie (yakgwa, tteok)"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["KBBQ z pełnym zestawem ssam i sosów"],
  ["Budae / kimchi jjigae na dużą grupę"],
  ["Tteok (kluski ryżowe) od podstaw", undefined, prog("techniki", 15)],
  ["Sosy i pasty fermentowane na wysokim poziomie", undefined, prog("techniki", 16)],
  ["Bibimbap + zupa + banchan jako komplet"],
  ["Danie regionalne (Jeolla / Busan)"],
  ["Deser: patbingsu / hangwa"],
  ["Zupy i gulasze jjigae w kilku wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Kiszonki i fermenty (jangajji, kimchi sezonowe)"],
  ["Zaserwuj spójne 3-daniowe menu koreańskie"],
  ["Koreański stół: kilka dań + zestaw banchan"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj koreańskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Kimchi i fermenty na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Pełny zestaw banchan (12+ dodatków)"],
  ["Owoce morza premium po koreańsku"],
  ["Galbijjim / bossam dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: grill + jjigae + banchan + desery"],
  ["Danie dworskie (hanjeongsik — kuchnia królewska)"],
  ["Wypieki i słodycze koreańskie (tteok, hangwa)", undefined, prog("techniki", 18)],
  ["Jjigae i gulasze w kilku regionalnych stylach"],
  ["Suszenie/marynowanie w domu (jang, jeotgal)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. Jeolla lub Gyeongsang)"],
  ["KBBQ i grill na dużą imprezę"],
  ["Kimchi na cały sezon (kimjang)"],
  ["Zorganizuj koreańską kolację tematyczną"],
  ["Pieczyste i jjim na przyjęcie"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie banchan (plating)"],
  ["Desery koreańskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania koreańskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Kimchi, fermenty i banchan na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu koreańskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Korei"],
  ["Uczta noworoczna (Seollal) — wielodaniowa"],
  ["Naucz kogoś koreańskich technik (kimchi, banchan, grill)"],
  ["Fermenty i banchan bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar sosów i past z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni koreańskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde koreańskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne koreańskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated learning resources for Korean cuisine milestones.
// Videos from Maangchi, Aaron and Claire, Future Neighbor; articles from seriouseats, bonappetit.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  4: [{ kind: "video", title: "Bibimbap — Korean Mixed Rice Bowl", url: yt("6QQ67F8y2b8") }],
  6: [{ kind: "video", title: "Japchae — Glass Noodle Stir-Fry", url: yt("i1djfV9uigc") }],
  7: [{ kind: "video", title: "Pajeon — Crispy Korean Scallion Pancake", url: yt("IfaExW4CgXk") }],
  10: [{ kind: "video", title: "Tteokbokki — Spicy Rice Cakes", url: yt("FLd0Vl5oMak") }],
  13: [
    { kind: "video", title: "Bulgogi — Korean Marinated Beef", url: yt("SOrfKo14bIA") },
    { kind: "article", title: "Bulgogi recipe with tips", url: "https://www.seriouseats.com/korean-bulgogi-recipe" },
  ],
  14: [{ kind: "video", title: "Kimchi Jjigae — Kimchi Stew", url: yt("DmU3JgSba4M") }],
  15: [{ kind: "video", title: "Kimbap — Korean Seaweed Rice Rolls", url: yt("iVFMWPJ13Kk") }],
  22: [{ kind: "video", title: "Yangnyeom Chicken — Korean Fried Chicken", url: yt("Jb_Xq3KBMWE") }],
  26: [
    { kind: "video", title: "Baechu Kimchi — Traditional Napa Cabbage Kimchi", url: yt("eTyyJ36h0mE") },
    { kind: "article", title: "Complete kimchi fermentation guide", url: "https://www.seriouseats.com/homemade-kimchi-recipe" },
  ],
  29: [{ kind: "video", title: "Galbijjim — Braised Short Ribs", url: yt("r7TJ_VToIbw") }],
  35: [{ kind: "video", title: "Naengmyeon — Cold Korean Noodles", url: yt("CVd9saz1uXM") }],
  38: [{ kind: "video", title: "Jjajangmyeon — Noodles in Black Bean Sauce", url: yt("BIRFViCP9mM") }],
};
