// American cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "kuchnia-amerykanska",
  name: "Kuchnia amerykańska",
  icon: "🇺🇸",
  description:
    "Od burgera po smoked brisket i indyka na Święto Dziękczynienia — konkretne dania jako poziomy. Podstawy → klasyki → BBQ, wypieki i soul food → uczta. Realna droga kucharza domowego.",
  sortOrder: 114,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Burger wołowy (soczysty, dobrze doprawiony)", undefined, prog("techniki", 1)],
  ["Pancakes (amerykańskie naleśniki)"],
  ["Coleslaw (surówka)", undefined, prog("techniki", 2)],
  ["Mac and cheese"],
  ["Scrambled eggs / omlet po amerykańsku", undefined, prog("techniki", 3)],
  ["Grilled cheese sandwich"],
  ["Cornbread (chleb kukurydziany)"],
  ["Chili con carne"],
  ["Ugotuj 5 amerykańskich dań", undefined, prog("dania", 5)],
  ["Frytki / pieczone ziemniaki i dipy"],
  // 11-25 · Klasyki
  ["Gotuj amerykańskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Rub i marynaty do mięs BBQ", undefined, prog("techniki", 4)],
  ["Buffalo wings (skrzydełka)"],
  ["Southern fried chicken (smażony kurczak)", undefined, prog("techniki", 5)],
  ["Cheeseburger z dodatkami od podstaw"],
  ["Clam chowder (zupa z małży)"],
  ["Meatloaf (pieczeń rzekoma)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Ciasto na pie (kruchy spód)", undefined, prog("techniki", 6)],
  ["Grillowanie i pieczenie na ruszcie (technika)", undefined, prog("techniki", 7)],
  ["BBQ ribs (żeberka w sosie)"],
  ["Cheesecake (New York)"],
  ["Buttermilk biscuits"],
  ["Pancakes / waffles na śniadanie premium"],
  ["Sloppy joes / burgery w wariantach"],
  // 26-45 · Średniozaawansowane
  ["Smoke / low and slow (technika wędzenia)", undefined, prog("techniki", 8)],
  ["Sosy BBQ w kilku regionalnych stylach", undefined, prog("techniki", 9)],
  ["Sos i roux do gumbo/gravy", undefined, prog("techniki", 10)],
  ["Pulled pork (wędzona łopatka)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Jambalaya"],
  ["Apple pie od podstaw", undefined, prog("techniki", 11)],
  ["Gumbo (kreolski gulasz)"],
  ["Biscuits and gravy", undefined, prog("techniki", 12)],
  ["Buffalo wings z domowym sosem i blue cheese"],
  ["Cornbread / skillet cornbread na wysokim poziomie"],
  ["Clam chowder / lobster roll"],
  ["Brownie / chocolate chip cookies"],
  ["Gotuj amerykańskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Cheesecake w kilku wariantach"],
  ["Ribs na przyjęcie (wędzone)"],
  ["Fried chicken na wysokim poziomie (buttermilk brine)"],
  ["Cajun / creole danie (etouffee)"],
  ["Pecan pie / key lime pie"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Smoked brisket (mostek, wiele godzin)", undefined, prog("techniki", 13)],
  ["Zestaw BBQ na przyjęcie (ribs, brisket, pulled pork)"],
  ["Cała pieczona szynka / prime rib"],
  ["Soul food talerz (fried chicken, greens, cornbread)"],
  ["Wypieki: layer cake od podstaw", undefined, prog("techniki", 14)],
  ["Crab cakes / seafood boil"],
  ["Deser: layered cheesecake / carrot cake"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["BBQ platter dla gości (kilka mięs + dodatki)"],
  ["Gumbo / jambalaya na dużą grupę"],
  ["Chleby i bułki burgerowe od podstaw", undefined, prog("techniki", 15)],
  ["Wędzenie na poziomie mistrzowskim (bark, smoke ring)", undefined, prog("techniki", 16)],
  ["Burger gourmet z domowymi dodatkami jako komplet"],
  ["Danie regionalne (Tex-Mex / New England / Południe)"],
  ["Deser: banana pudding / cobbler"],
  ["Sosy i marynaty BBQ w wielu wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Pikle i przetwory (bread & butter, hot sauce)"],
  ["Zaserwuj spójne 3-daniowe menu amerykańskie"],
  ["Cookout / grill party dla większej grupy"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj amerykańskie dania regularnie przez pełny sezon (6 mies.)"],
  ["BBQ i wędzenie na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Pełen zestaw soul food na stół"],
  ["Owoce morza premium (lobster, oysters)"],
  ["Brisket / whole hog dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: BBQ + sides + wypieki + desery"],
  ["Danie kreolskie/cajun z Luizjany na wysokim poziomie"],
  ["Wypieki amerykańskie (pies, layer cakes, donuts)", undefined, prog("techniki", 18)],
  ["BBQ w kilku regionalnych stylach (Texas, Carolina, KC)"],
  ["Peklowanie/wędzenie w domu (bacon, pastrami)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. Południe lub Nowy Orlean)"],
  ["Grill i smoker na dużą imprezę"],
  ["Seafood boil / clambake na przyjęcie"],
  ["Zorganizuj amerykańską kolację tematyczną"],
  ["Pieczony indyk z nadzieniem (całość)"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie i plating"],
  ["Wypieki i desery amerykańskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania amerykańskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["BBQ, wędzenie i wypieki na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu amerykańskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem USA"],
  ["Thanksgiving — pełna świąteczna uczta"],
  ["Naucz kogoś amerykańskich technik (BBQ, pie, biscuit)"],
  ["Wędzenie i wypieki bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar sosów BBQ i marynat z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni amerykańskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde amerykańskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne amerykańskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated learning resources for American cuisine milestones.
// Videos from Babish, Joshua Weissman, America's Test Kitchen; articles from seriouseats, bonappetit.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [
    { kind: "video", title: "The Perfect Smash Burger", url: yt("A-RfHC91Ewc") },
    { kind: "article", title: "The ultimate smash burger technique", url: "https://www.seriouseats.com/ultra-smashed-cheeseburger-recipe-food-lab" },
  ],
  2: [{ kind: "video", title: "Fluffy American Pancakes from Scratch", url: yt("IY5ykPd3coo") }],
  4: [{ kind: "video", title: "Mac and Cheese — Stovetop Creamy", url: yt("FUeyrEN14Rk") }],
  8: [{ kind: "video", title: "Classic Texas Chili con Carne", url: yt("bcft1Gk4Z7Y") }],
  13: [{ kind: "video", title: "Crispy Buffalo Wings with Blue Cheese", url: yt("DcmCIVJOBxE") }],
  14: [{ kind: "video", title: "Southern Fried Chicken — Buttermilk Brine", url: yt("a-SnxKbn8Jk") }],
  21: [
    { kind: "video", title: "BBQ Ribs — Low and Slow Smoked", url: yt("EBnOxPjB8xI") },
    { kind: "article", title: "Guide to BBQ pork ribs", url: "https://www.seriouseats.com/best-barbecue-ribs-recipe" },
  ],
  22: [{ kind: "video", title: "New York Cheesecake from Scratch", url: yt("tspdJ6hxqnc") }],
  29: [{ kind: "video", title: "Pulled Pork — Smoked Pork Shoulder", url: yt("Nnsg9yJ7-B4") }],
  32: [{ kind: "video", title: "Apple Pie — Flaky Crust from Scratch", url: yt("GxJSxj5p1rA") }],
  46: [{ kind: "video", title: "Smoked Brisket — Texas Style Low and Slow", url: yt("pGZ39yYxeBk") }],
  48: [{ kind: "article", title: "How to host a BBQ party: ribs, brisket, pulled pork", url: "https://www.bonappetit.com/story/backyard-bbq-guide" }],
};
