// Hungarian cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-wegierska",
  name: "Kuchnia węgierska",
  icon: "🇭🇺",
  description:
    "Od gulaszu po halászlé i tort Dobosa — konkretne dania jako poziomy. Podstawy → klasyki → pörkölt, strudel i wypieki → uczta. Realna droga kucharza domowego.",
  sortOrder: 119,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Lecsó (potrawka z papryki i pomidorów)", undefined, prog("techniki", 1)],
  ["Uborkasaláta (sałatka z ogórka)"],
  ["Körözött (pasta z twarogu i papryki)", undefined, prog("techniki", 2)],
  ["Paprikás krumpli (ziemniaki z papryką)"],
  ["Baza paprykowa (cebula + papryka) — technika", undefined, prog("techniki", 3)],
  ["Palacsinta (naleśniki)"],
  ["Rántott sajt (smażony ser)"],
  ["Tojásos nokedli (kluski z jajkiem)"],
  ["Ugotuj 5 węgierskich dań", undefined, prog("dania", 5)],
  ["Zsíroskenyér / przekąski"],
  // 11-25 · Klasyki
  ["Gotuj węgierskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Rántás (zasmażka) i pörkölt baza", undefined, prog("techniki", 4)],
  ["Gulyás (zupa gulaszowa)", undefined, prog("techniki", 5)],
  ["Pörkölt (gulasz duszony)"],
  ["Nokedli / galuska (kluski) od podstaw"],
  ["Paprikás csirke (kurczak w papryce)"],
  ["Töltött káposzta (gołąbki po węgiersku)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Ciasto na lángos od podstaw", undefined, prog("techniki", 6)],
  ["Halászlé (zupa rybacka) — proces", undefined, prog("techniki", 7)],
  ["Lángos (smażone placki)"],
  ["Székelykáposzta (kapusta z wieprzowiną)"],
  ["Somlói galuska (deser)"],
  ["Marhapörkölt z nokedli"],
  ["Rakott krumpli (zapiekanka ziemniaczana)"],
  ["Lecsós tojás (jajka sadzone na lecsó)"],
  // 26-45 · Średniozaawansowane
  ["Halászlé pełnowartościowe (na wywarze rybnym)", undefined, prog("techniki", 8)],
  ["Pörkölt w kilku wariantach (wołowy, z dziczyzny)", undefined, prog("techniki", 9)],
  ["Praca z papryką (świeża, mielona, ostrość)", undefined, prog("techniki", 10)],
  ["Töltött paprika (nadziewana papryka)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Csirkepaprikás z nokedli na przyjęcie"],
  ["Rétes (strudel) od ciągnionego ciasta", undefined, prog("techniki", 11)],
  ["Gulyásleves na ognisku / bogrács"],
  ["Lángos od podstaw z dodatkami", undefined, prog("techniki", 12)],
  ["Töltött káposzta na przyjęcie"],
  ["Halászlé na dużą imprezę"],
  ["Túrós csusza (makaron z twarogiem)"],
  ["Dobos torta (tort Dobosa)"],
  ["Gotuj węgierskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Kürtőskalács (kołacz kominowy)"],
  ["Pörkölt / gulyás na dużą imprezę"],
  ["Halászlé w kilku regionalnych wariantach"],
  ["Vadas (dziczyzna w sosie)"],
  ["Gundel palacsinta (naleśniki flambirowane)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Zestaw dań na węgierski stół dla gości", undefined, prog("techniki", 13)],
  ["Bogrács gulyás na ognisku dla grupy"],
  ["Pieczyste (kacsasült — pieczona kaczka)"],
  ["Halászlé z ciastem i całą rybą"],
  ["Rétes ciągniony cienko jak profesjonalny", undefined, prog("techniki", 14)],
  ["Töltött káposzta wielodniowa"],
  ["Torty i wypieki warstwowe (Dobos, Eszterházy)", undefined, prog("techniki", 15)],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Pieczyste na dużą imprezę"],
  ["Pörkölt / paprikás na przyjęcie"],
  ["Chleby i lángos na zakwasie", undefined, prog("techniki", 16)],
  ["Gulyás + nokedli + deser jako komplet"],
  ["Danie regionalne (Szeged / Debreczyn / Alföld)"],
  ["Deser: krémes / flódni"],
  ["Zupy węgierskie w kilku wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Kiszonki i marynaty węgierskie"],
  ["Zaserwuj spójne 3-daniowe menu węgierskie"],
  ["Węgierski stół: gulasz + pieczyste + wypieki"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj węgierskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Pörkölt, halászlé i strudel na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Pełny stół z przekąskami i pörköltami"],
  ["Ryby słodkowodne po węgiersku (sandacz, karp)"],
  ["Całe pieczyste dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: gulyás + pörkölt + töltött + torty"],
  ["Danie z kuchni puszty (bogrács, dziczyzna)"],
  ["Wypieki węgierskie (Dobos, kürtőskalács, beigli)", undefined, prog("techniki", 18)],
  ["Gulasze i pörkölty w kilku regionalnych stylach"],
  ["Peklowanie/wędzenie w domu (kolbász, szalonna)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. Szeged lub Siedmiogród)"],
  ["Bogrács i pieczyste na dużą imprezę"],
  ["Halászlé na dużą imprezę"],
  ["Zorganizuj węgierską kolację tematyczną"],
  ["Całe pieczyste (prosię / kaczki) na okazję"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie i plating"],
  ["Torty i wypieki węgierskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania węgierskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Pörkölt, strudel i torty na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu węgierskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Węgier"],
  ["Uczta świąteczna (Karácsony) — wielodaniowa"],
  ["Naucz kogoś węgierskich technik (pörkölt, rétes, nokedli)"],
  ["Strudel i wypieki bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar gulaszy i sosów z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni węgierskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde węgierskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne węgierskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);
