// Italian cuisine ladder 1-99 — concrete dishes as levels, ordered easy → hard.
// REALISTIC home-cook scale: top = an accomplished home cook running a full
// multi-course Italian feast, not a Michelin chef. Tracks: dania (dishes cooked),
// techniki (techniques), plus specific-dish milestones (plain manual).
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-wloska",
  name: "Kuchnia włoska",
  icon: "🇮🇹",
  description:
    "Od bruschetty po świąteczny cenone — konkretne dania jako poziomy. Podstawy → klasyki → dania zaawansowane → pełne wielodaniowe menu. Realna droga kucharza domowego.",
  sortOrder: 101,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Bruschetta z pomidorami i bazylią", undefined, prog("techniki", 1)],
  ["Insalata caprese (mozzarella, pomidor, bazylia)"],
  ["Ugotuj makaron perfekcyjnie al dente", undefined, prog("techniki", 2)],
  ["Spaghetti aglio e olio (czosnek, oliwa, chili)"],
  ["Domowy sos pomodoro i spaghetti al pomodoro", undefined, prog("techniki", 3)],
  ["Pesto alla genovese (bazylia, orzeszki, parmezan)"],
  ["Frittata z warzywami"],
  ["Minestrone (zupa jarzynowa)"],
  ["Ugotuj 5 włoskich dań", undefined, prog("dania", 5)],
  ["Panzanella (sałatka chlebowa)"],
  // 11-25 · Klasyki
  ["Gotuj włoskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Spaghetti alla carbonara (bez śmietany, jajko + guanciale)", undefined, prog("techniki", 4)],
  ["Penne all'arrabbiata"],
  ["Cacio e pepe (pecorino + pieprz)", undefined, prog("techniki", 5)],
  ["Pasta all'amatriciana"],
  ["Bruschetta i crostini w 3 wariantach"],
  ["Parmigiana di melanzane (zapiekany bakłażan)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Focaccia (ciasto drożdżowe)", undefined, prog("techniki", 6)],
  ["Risotto alla milanese (technika mantecatura)", undefined, prog("techniki", 7)],
  ["Tiramisu (deser)"],
  ["Panna cotta"],
  ["Zuppa toscana / ribollita"],
  ["Pollo alla cacciatora"],
  ["Insalata di mare (owoce morza)"],
  // 26-45 · Średniozaawansowane
  ["Pizza margherita — ciasto od podstaw", undefined, prog("techniki", 8)],
  ["Gnocchi ziemniaczane od podstaw", undefined, prog("techniki", 9)],
  ["Ragù alla bolognese (długie duszenie)", undefined, prog("techniki", 10)],
  ["Lasagne al forno z beszamelem"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Risotto ai funghi porcini"],
  ["Saltimbocca alla romana"],
  ["Melanzane alla parmigiana perfekcyjna"],
  ["Arancini (smażone kulki ryżowe)"],
  ["Tagliatelle al ragù — makaron jajeczny od podstaw", undefined, prog("techniki", 11)],
  ["Ravioli własnoręcznie (ciasto + farsz)", undefined, prog("techniki", 12)],
  ["Vitello tonnato"],
  ["Caponata siciliana"],
  ["Gotuj włoskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Cannoli siciliani (deser)"],
  ["Zuppa di pesce (zupa rybna)"],
  ["Tortellini w rosole (in brodo)"],
  ["Cotoletta alla milanese"],
  ["Panzerotti / calzone"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Osso buco alla milanese (długie duszenie)", undefined, prog("techniki", 13)],
  ["Risotto al nero di seppia"],
  ["Brasato al Barolo (wołowina w winie)"],
  ["Fritto misto (owoce morza w cieście)"],
  ["Pasta fresca w kilku kształtach ręcznie", undefined, prog("techniki", 14)],
  ["Involtini (roladki wołowe/warzywne)"],
  ["Cassata siciliana (deser)"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Cotechino / bollito misto"],
  ["Focaccia di Recco (z serem)"],
  ["Pane fatto in casa (chleb od podstaw)", undefined, prog("techniki", 15)],
  ["Gelato domowe", undefined, prog("techniki", 16)],
  ["Zabaglione (krem na winie marsala)"],
  ["Pappardelle al cinghiale (z dzikiem/wołowiną)"],
  ["Torta caprese (czekoladowa)"],
  ["Coniglio alla ligure (królik)"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Baccalà alla vicentina (dorsz)"],
  ["Zaserwuj spójne 3-daniowe menu włoskie (antipasto–primo–secondo)"],
  ["Ossobuco z risotto alla milanese jako komplet"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj włoskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Sfogliatelle riccia (bardzo trudne ciasto)", undefined, prog("techniki", 17)],
  ["Cappelletti in brodo (drobny makaron nadziewany)"],
  ["Culurgiones (sardyńskie pierożki)"],
  ["Timballo (zapiekany pasztet z makaronu)"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Ragù napoletano (wielogodzinne)"],
  ["Brodetto / cacciucco (gęsta zupa rybna)"],
  ["Millefoglie (ciasto francuskie + krem)", undefined, prog("techniki", 18)],
  ["Bagna càuda (piemoncki dip)"],
  ["Pasta all'uovo cienka jak profesjonalna", undefined, prog("techniki", 19)],
  ["Parmigiana i lasagne na przyjęcie dla gości"],
  ["Colomba pasquale (drożdżowa)"],
  ["Cassoeula (lombardzki gulasz)"],
  ["Zorganizuj regionalną kolację tematyczną (np. sycylijską)"],
  ["Sformato / soufflé warzywne"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Struccoli / strudel (północne Włochy)"],
  ["Bottarga / dania z owocami morza premium"],
  ["Własna, autorska interpretacja klasyka włoskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Panettone od zera z zakwasem (lievito madre)", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu (antipasto–primo–secondo–dolce)"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Włoch"],
  ["Cenone — świąteczna wielodaniowa uczta włoska"],
  ["Naucz kogoś gotować włoskie klasyki"],
  ["Sfogliatelle na perfekcyjnym poziomie", undefined, prog("techniki", 22)],
  ["Świeży makaron na poziomie profesjonalnym (kilka rodzajów)"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni włoskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde włoskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne włoskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);
