// Polish cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-polska",
  name: "Kuchnia polska",
  icon: "🇵🇱",
  description:
    "Od jajecznicy po wigilijne 12 dań — konkretne potrawy jako poziomy. Podstawy → klasyki → pierogi, zupy i pieczyste → świąteczna uczta. Realna droga kucharza domowego.",
  sortOrder: 110,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Jajecznica na maśle i kanapki", undefined, prog("techniki", 1)],
  ["Mizeria (surówka z ogórka)"],
  ["Surówka z marchewki / z kapusty", undefined, prog("techniki", 2)],
  ["Zupa pomidorowa z makaronem"],
  ["Zupa ogórkowa", undefined, prog("techniki", 3)],
  ["Jajka w sosie majonezowym"],
  ["Naleśniki na słodko"],
  ["Kopytka / kluski śląskie"],
  ["Ugotuj 5 polskich dań", undefined, prog("dania", 5)],
  ["Frytki / ziemniaki puree do obiadu"],
  // 11-25 · Klasyki
  ["Gotuj polskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Rosół — klarowny wywar drobiowy", undefined, prog("techniki", 4)],
  ["Kotlet schabowy (panierka)", undefined, prog("techniki", 5)],
  ["Mielone kotlety z ziemniakami i surówką"],
  ["Placki ziemniaczane"],
  ["Gołąbki w sosie pomidorowym"],
  ["Bigos"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Ciasto na pierogi (zagniatanie i wałkowanie)", undefined, prog("techniki", 6)],
  ["Pierogi ruskie od podstaw", undefined, prog("techniki", 7)],
  ["Żurek na zakwasie"],
  ["Barszcz czerwony (wywar buraczany)"],
  ["Sznycel / de volaille"],
  ["Leczo / fasolka po bretońsku"],
  ["Racuchy / sernik na zimno (deser)"],
  // 26-45 · Średniozaawansowane
  ["Zakwas na żurek od podstaw", undefined, prog("techniki", 8)],
  ["Wywary i zupy klarowne (technika)", undefined, prog("techniki", 9)],
  ["Panierowanie i smażenie (schab, ryba, ser)", undefined, prog("techniki", 10)],
  ["Pierogi z mięsem / z kapustą i grzybami"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Gołąbki na wywarze z domowym sosem"],
  ["Pierogi w kilku wariantach naraz", undefined, prog("techniki", 11)],
  ["Kaczka pieczona z jabłkami"],
  ["Bigos długo gotowany (wielodniowy)", undefined, prog("techniki", 12)],
  ["Barszcz czerwony z uszkami"],
  ["Flaki wołowe"],
  ["Krokiety z barszczem"],
  ["Karp smażony / w galarecie"],
  ["Gotuj polskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Sernik pieczony"],
  ["Schab pieczony / karkówka"],
  ["Zrazy zawijane wołowe"],
  ["Kapusta zasmażana / modra"],
  ["Szarlotka (deser)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Rosół + drugie + deser jako pełny obiad niedzielny", undefined, prog("techniki", 13)],
  ["Pierogi na dużą imprezę (kilka nadzień)"],
  ["Pieczeń rzymska / boczek faszerowany"],
  ["Galareta / nóżki w galarecie"],
  ["Ciasto drożdżowe od podstaw", undefined, prog("techniki", 14)],
  ["Pasztet domowy (zapiekany)"],
  ["Makowiec zawijany"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Kaczka / gęś pieczona na przyjęcie"],
  ["Żurek w chlebie na przyjęcie"],
  ["Chleb na zakwasie od podstaw", undefined, prog("techniki", 15)],
  ["Kluski, kopytka i leniwe na wysokim poziomie", undefined, prog("techniki", 16)],
  ["Rolada wołowa ze śląskimi kluskami i modrą kapustą"],
  ["Danie regionalne (śląskie / góralskie / kresowe)"],
  ["Sernik wiedeński / krówka (deser)"],
  ["Zupy regionalne (czernina, zalewajka, kwaśnica)"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Kiszenie kapusty i ogórków od podstaw"],
  ["Zaserwuj spójny 3-daniowy obiad polski"],
  ["Świąteczny stół: kilka dań naraz"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj polskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Pierogi i kluski na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Wigilijne dania postne (kilka naraz)"],
  ["Ryby świąteczne (karp, śledzie w kilku wariantach)"],
  ["Pieczyste świąteczne (schab, indyk, kaczka)"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: zupy + pieczyste + pierogi + desery"],
  ["Danie kresowe / litewskie (kołduny, chłodnik)"],
  ["Wypieki świąteczne (makowiec, piernik, keks)", undefined, prog("techniki", 18)],
  ["Zupy w kilku regionalnych wariantach"],
  ["Wędzenie/peklowanie w domu (boczek, kiełbasa)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. podhalańskie lub wielkopolskie)"],
  ["Zestaw pieczystych i rolad na dużą imprezę"],
  ["Bigos / gołąbki na dużą imprezę"],
  ["Zorganizuj polską kolację tematyczną"],
  ["Pieczona gęś / prosię na okazję"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie dań polskich (plating)"],
  ["Ciasta i desery polskie na poziomie cukierni"],
  ["Własna, autorska interpretacja polskiego klasyka", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Pierogi, kluski i ciasta na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu polskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Polski"],
  ["Wigilia — 12 tradycyjnych dań"],
  ["Naucz kogoś polskich technik (pierogi, rosół, zakwas)"],
  ["Pieczyste i pierogi bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar zup i sosów z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni polskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde polskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne polskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);

import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  4: [{ kind: "video", title: "Zupa pomidorowa — klasyczny polski przepis", url: yt("jTHQkL9Y3JA") }],
  8: [{ kind: "video", title: "Kopytka — kluski ziemniaczane krok po kroku", url: yt("BZw4zH-1t0c") }],
  12: [{ kind: "video", title: "Rosół — klarowny wywar z kury", url: yt("pLwFkbJyIVA") }],
  13: [
    { kind: "video", title: "Kotlet schabowy — chrupiąca panierka", url: yt("N2BjKY2rOBk") },
    { kind: "article", title: "Kotlet schabowy — tradycyjny przepis", url: "https://www.kwestiasmaku.com/kotlet_schabowy.html" },
  ],
  15: [{ kind: "video", title: "Placki ziemniaczane — chrupiące i złociste", url: yt("S3y2NFWA5EY") }],
  16: [{ kind: "video", title: "Gołąbki w sosie pomidorowym", url: yt("K3PaHyggJCk") }],
  17: [{ kind: "article", title: "Bigos — tradycyjny przepis staropolski", url: "https://www.kwestiasmaku.com/bigos.html" }],
  20: [{ kind: "video", title: "Pierogi ruskie — ciasto i farsz od podstaw", url: yt("JEqFnLY6xbY") }],
  21: [{ kind: "video", title: "Żurek na naturalnym zakwasie", url: yt("VTc5gbYxBCM") }],
  22: [{ kind: "video", title: "Barszcz czerwony — czysty wywar buraczany", url: yt("xS8mxaFunEE") }],
  35: [{ kind: "article", title: "Barszcz z uszkami — wigilijny klasyk", url: "https://www.kwestiasmaku.com/barszcz_z_uszkami.html" }],
  40: [{ kind: "video", title: "Sernik pieczony — kremowy na kruchym spodzie", url: yt("VY5rXBIkwnY") }],
};
