// Vietnamese cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "kuchnia-wietnamska",
  name: "Kuchnia wietnamska",
  icon: "🇻🇳",
  description:
    "Od sajgonek po pho od podstaw — konkretne dania jako poziomy. Podstawy → klasyki → buliony, sosy i papier ryżowy → uczta. Realna droga kucharza domowego.",
  sortOrder: 112,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Gỏi cuốn (świeże sajgonki w papierze ryżowym)", undefined, prog("techniki", 1)],
  ["Nước chấm (sos do maczania)"],
  ["Zwijanie papieru ryżowego (technika)", undefined, prog("techniki", 2)],
  ["Cơm tấm (ryż z grillowaną wieprzowiną)"],
  ["Balans smaków wietnamskich (słodki-kwaśny-słony-umami)", undefined, prog("techniki", 3)],
  ["Gỏi gà (sałatka z kurczaka)"],
  ["Chả giò (smażone sajgonki)"],
  ["Dưa chua (marynowane warzywa)"],
  ["Ugotuj 5 wietnamskich dań", undefined, prog("dania", 5)],
  ["Bánh mì (kanapka — złożenie)"],
  // 11-25 · Klasyki
  ["Gotuj wietnamskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Nước màu (karmel rybny) do potraw kho", undefined, prog("techniki", 4)],
  ["Phở (na gotowym/uproszczonym bulionie)", undefined, prog("techniki", 5)],
  ["Bún chả (grillowana wieprzowina z makaronem)"],
  ["Cá kho tộ (ryba w karmelu)"],
  ["Bún thịt nướng"],
  ["Gỏi đu đủ (sałatka z papai)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Bulion phở od podstaw (długie gotowanie)", undefined, prog("techniki", 6)],
  ["Nước chấm dopracowany w kilku wariantach", undefined, prog("techniki", 7)],
  ["Bò kho (gulasz wołowy)"],
  ["Bánh xèo (chrupiące naleśniki)"],
  ["Chè (deser)"],
  ["Canh chua (kwaśna zupa)"],
  ["Thịt kho tàu (wieprzowina w karmelu z jajkiem)"],
  // 26-45 · Średniozaawansowane
  ["Bulion phở bò na wysokim poziomie (aromaty, klarowność)", undefined, prog("techniki", 8)],
  ["Ciasto na bánh xèo (kokos, kurkuma)", undefined, prog("techniki", 9)],
  ["Grillowanie i marynaty wietnamskie", undefined, prog("techniki", 10)],
  ["Bún bò Huế (pikantna zupa)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Cao lầu (specjał z Hội An)"],
  ["Bánh cuốn (naleśniki na parze)", undefined, prog("techniki", 11)],
  ["Phở gà (drobiowe)"],
  ["Sajgonki od podstaw (papier + farsz) w kilku wariantach", undefined, prog("techniki", 12)],
  ["Bún riêu (zupa z pomidorem i krabem)"],
  ["Gà nướng (grillowany kurczak)"],
  ["Mì Quảng (makaron z Quảng Nam)"],
  ["Bánh khọt (mini placki)"],
  ["Gotuj wietnamskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Chè ba màu / desery warstwowe"],
  ["Phở na przyjęcie z pełnym garniturem"],
  ["Bún chả / bún thịt nướng na imprezę"],
  ["Cà ri gà (wietnamskie curry)"],
  ["Bánh flan (deser)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Phở bò i phở gà obie na własnym bulionie", undefined, prog("techniki", 13)],
  ["Zestaw dań na wspólny wietnamski stół dla gości"],
  ["Cá / owoce morza na parze i grillu"],
  ["Bún bò Huế pełnowartościowe"],
  ["Papier ryżowy i naleśniki na poziomie mistrzowskim", undefined, prog("techniki", 14)],
  ["Nem nướng / chả (własne wyroby mięsne)"],
  ["Chè w kilku wariantach (deser)"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Bánh mì z domowym pasztetem i piklami"],
  ["Bò kho / cà ri na przyjęcie"],
  ["Bagietka bánh mì od podstaw", undefined, prog("techniki", 15)],
  ["Buliony i zupy na poziomie mistrzowskim", undefined, prog("techniki", 16)],
  ["Phở + sajgonki + sałatka jako komplet"],
  ["Danie regionalne (Huế / Hội An / delta Mekongu)"],
  ["Deser: bánh da lợn / warstwowe"],
  ["Marynaty i sosy w kilku wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Kiszonki i pikle wietnamskie"],
  ["Zaserwuj spójne 3-daniowe menu wietnamskie"],
  ["Wietnamski stół: kilka dań o różnym profilu smaku"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj wietnamskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Phở i buliony na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Pełny zestaw przekąsek (bánh) z całego Wietnamu"],
  ["Owoce morza premium po wietnamsku"],
  ["Bún bò Huế / bò kho dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: zupy + grill + sajgonki + desery"],
  ["Danie z Huế (kuchnia cesarska, dopracowana)"],
  ["Wypieki i naleśniki wietnamskie na parze", undefined, prog("techniki", 18)],
  ["Zupy makaronowe w kilku regionalnych stylach"],
  ["Suszenie/marynowanie w domu (chả, nem chua)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. środkowy lub południowy Wietnam)"],
  ["Makarony i sajgonki w wielu stylach"],
  ["Phở/bún bò na dużą imprezę"],
  ["Zorganizuj wietnamską kolację tematyczną"],
  ["Grill i owoce morza na przyjęcie"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie (plating)"],
  ["Desery wietnamskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania wietnamskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Phở, buliony i sajgonki na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu wietnamskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Wietnamu"],
  ["Uczta noworoczna (Tết) — wielodaniowa"],
  ["Naucz kogoś wietnamskich technik (bulion, papier ryżowy, balans)"],
  ["Buliony i sajgonki bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny zestaw sosów i marynat z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni wietnamskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde wietnamskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne wietnamskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated learning resources for Vietnamese cuisine milestones.
// Videos from Helen's Recipes, Pailin's Kitchen and others; articles from seriouseats, bonappetit.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Gỏi Cuốn — Fresh Vietnamese Spring Rolls", url: yt("fE0MsafCHcI") }],
  4: [{ kind: "video", title: "Cơm Tấm — Vietnamese Broken Rice with Pork Chop", url: yt("lMBJivGS6YA") }],
  7: [{ kind: "video", title: "Chả Giò — Crispy Vietnamese Fried Spring Rolls", url: yt("tsOC2b0gSKc") }],
  10: [
    { kind: "video", title: "Bánh Mì — Vietnamese Sandwich from Scratch", url: yt("oY8CsOgEiNw") },
    { kind: "article", title: "The ultimate bánh mì guide", url: "https://www.seriouseats.com/banh-mi-vietnamese-sandwich-recipe" },
  ],
  13: [
    { kind: "video", title: "Phở Bò — Authentic Vietnamese Beef Pho", url: yt("JGmXEApcOBg") },
    { kind: "article", title: "Phở from scratch — the complete guide", url: "https://www.recipetineats.com/vietnamese-pho" },
  ],
  14: [{ kind: "video", title: "Bún Chả — Hanoi Grilled Pork with Noodles", url: yt("YFM0RJKEYXU") }],
  15: [{ kind: "video", title: "Cá Kho Tộ — Caramelized Fish in Clay Pot", url: yt("Gx94kcLjjsY") }],
  22: [{ kind: "video", title: "Bánh Xèo — Crispy Vietnamese Crepes", url: yt("B7MzVTWortk") }],
  29: [{ kind: "video", title: "Bún Bò Huế — Spicy Vietnamese Beef Noodle Soup", url: yt("VE1aWNR0eGY") }],
  44: [{ kind: "video", title: "Bánh Flan — Vietnamese Crème Caramel", url: yt("KGr1zyms4Ek") }],
  47: [{ kind: "article", title: "Vietnamese curry (Cà Ri Gà) recipe", url: "https://www.bonappetit.com/recipe/vietnamese-chicken-curry" }],
};
