// Mexican cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-meksykanska",
  name: "Kuchnia meksykańska",
  icon: "🇲🇽",
  description:
    "Od guacamole po mole poblano — konkretne dania jako poziomy. Podstawy → klasyki → tortille, salsy i mole → uczta. Realna droga kucharza domowego.",
  sortOrder: 105,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Guacamole", undefined, prog("techniki", 1)],
  ["Pico de gallo (salsa fresca)"],
  ["Quesadillas", undefined, prog("techniki", 2)],
  ["Tacos z prostym nadzieniem"],
  ["Frijoles refritos (przecierana fasola)", undefined, prog("techniki", 3)],
  ["Salsa roja / verde na patelni"],
  ["Esquites (kukurydza w kubku)"],
  ["Huevos rancheros"],
  ["Ugotuj 5 meksykańskich dań", undefined, prog("dania", 5)],
  ["Nachos z domową salsą"],
  // 11-25 · Klasyki
  ["Gotuj meksykańskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Prażenie i obieranie chili (technika bazowa)", undefined, prog("techniki", 4)],
  ["Tacos al pastor"],
  ["Enchiladas w sosie", undefined, prog("techniki", 5)],
  ["Chilaquiles"],
  ["Sopa de tortilla"],
  ["Carnitas (duszona wieprzowina)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Tortille kukurydziane od masa harina", undefined, prog("techniki", 6)],
  ["Salsa verde z tomatillo (blanszowanie/prażenie)", undefined, prog("techniki", 7)],
  ["Elote (kukurydza z kolby)"],
  ["Tinga de pollo"],
  ["Ceviche"],
  ["Fajitas"],
  ["Sopes / tostadas"],
  // 26-45 · Średniozaawansowane
  ["Tortille pszenne i kukurydziane od podstaw", undefined, prog("techniki", 8)],
  ["Salsy w kilku wariantach (roja, verde, macha)", undefined, prog("techniki", 9)],
  ["Marynaty adobo do mięs", undefined, prog("techniki", 10)],
  ["Pozole (zupa z hominy)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Cochinita pibil (jukatańska wieprzowina)"],
  ["Tamales (w liściach kukurydzy)", undefined, prog("techniki", 11)],
  ["Chiles rellenos (nadziewane papryki)"],
  ["Birria (duszona wołowina/koza)", undefined, prog("techniki", 12)],
  ["Quesabirria z consommé"],
  ["Enmoladas / entomatadas"],
  ["Sopa azteca / crema de elote"],
  ["Camarones a la diabla (krewetki)"],
  ["Gotuj meksykańskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Flan / arroz con leche (deser)"],
  ["Mole poblano — wersja uproszczona"],
  ["Carne asada z garniturami"],
  ["Rajas con crema"],
  ["Churros z sosem"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Mole poblano od podstaw (wiele składników)", undefined, prog("techniki", 13)],
  ["Tamales w kilku wariantach nadzień"],
  ["Zestaw tacos z 3 rodzajami mięs na przyjęcie"],
  ["Barbacoa (długo pieczone mięso)"],
  ["Nixtamalizacja kukurydzy (masa od ziarna)", undefined, prog("techniki", 14)],
  ["Cochinita pibil pełny proces z achiote"],
  ["Pan de muerto / concha (wypiek)"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Pozole rojo/verde pełnowartościowe"],
  ["Chiles en nogada (sezonowe, wymagające)"],
  ["Masa świeża i tortille na poziomie taquería", undefined, prog("techniki", 15)],
  ["Salsy pieczone na comal (mistrzowsko)", undefined, prog("techniki", 16)],
  ["Birria/consommé na przyjęcie"],
  ["Danie regionalne z Oaxaca lub Jukatanu"],
  ["Deser: pastel tres leches"],
  ["Adobo i marynaty w wielu wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Escabeche / pikle meksykańskie"],
  ["Zaserwuj spójne 3-daniowe menu meksykańskie"],
  ["Zestaw taco party z domowymi tortillami i salsami"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj meksykańskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Mole negro Oaxaca (bardzo złożone)", undefined, prog("techniki", 17)],
  ["Tamales oaxaqueños w liściach bananowca"],
  ["Zestaw antojitos (sopes, tlacoyos, tostadas)"],
  ["Cochinita pibil z pełnym pieczeniem pod ziemią (lub imitacja)"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: mole + arroz + tortille + garnitury"],
  ["Danie z owoców morza (Veracruz / Baja)"],
  ["Wypieki meksykańskie (conchas, polvorones)", undefined, prog("techniki", 18)],
  ["7 rodzajów mole — poznaj i wykonaj kilka"],
  ["Prażenie i mielenie przypraw/chili od podstaw", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. Oaxaca lub Jukatan)"],
  ["Tortille niebieskiej kukurydzy i heirloom masa"],
  ["Pozole/birria na dużą imprezę"],
  ["Zorganizuj meksykańską kolację tematyczną"],
  ["Barbacoa/cochinita na przyjęcie dla gości"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie tacos i antojitos (plating)"],
  ["Desery i wypieki meksykańskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania meksykańskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Mole (negro/poblano) na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu meksykańskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Meksyku"],
  ["Uczta świąteczna (np. Día de Muertos) — wielodaniowa"],
  ["Naucz kogoś meksykańskich technik (masa, salsy, mole)"],
  ["Masa, tortille i mole bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny zestaw sals i marynat z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni meksykańskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde meksykańskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne meksykańskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);
