// French cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-francuska",
  name: "Kuchnia francuska",
  icon: "🇫🇷",
  description:
    "Od omleta po croquembouche — konkretne dania jako poziomy. Podstawy → klasyki bistro → techniki i sosy matczyne → pełne menu. Realna droga kucharza domowego.",
  sortOrder: 102,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Omelette nature (klasyczny francuski omlet)", undefined, prog("techniki", 1)],
  ["Salade niçoise"],
  ["Vinaigrette i dressing od podstaw", undefined, prog("techniki", 2)],
  ["Soupe à l'oignon gratinée (zupa cebulowa)"],
  ["Croque-monsieur", undefined, prog("techniki", 3)],
  ["Ratatouille"],
  ["Crêpes (naleśniki) na słodko i słono"],
  ["Poulet rôti (kurczak pieczony)"],
  ["Ugotuj 5 francuskich dań", undefined, prog("dania", 5)],
  ["Salade de chèvre chaud (z ciepłym kozim serem)"],
  // 11-25 · Klasyki bistro
  ["Gotuj francuskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Quiche lorraine (kruche ciasto + wytrawny krem)", undefined, prog("techniki", 4)],
  ["Gratin dauphinois (zapiekane ziemniaki)"],
  ["Sauce béchamel od podstaw", undefined, prog("techniki", 5)],
  ["Moules marinières (małże w winie)"],
  ["Poireaux vinaigrette / entrée warzywne"],
  ["Boeuf bourguignon (wołowina w czerwonym winie)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Pâte brisée / sablée (kruche ciasto)", undefined, prog("techniki", 6)],
  ["Blanquette de veau (cielęcina w białym sosie)", undefined, prog("techniki", 7)],
  ["Crème brûlée"],
  ["Mousse au chocolat"],
  ["Soupe de poisson (zupa rybna)"],
  ["Coq au vin"],
  ["Tarte aux pommes (tarta jabłkowa)"],
  // 26-45 · Średniozaawansowane
  ["Baguette od podstaw (chleb drożdżowy)", undefined, prog("techniki", 8)],
  ["Sauce hollandaise (emulsja na maśle)", undefined, prog("techniki", 9)],
  ["Sauce béarnaise", undefined, prog("techniki", 10)],
  ["Cassoulet (zapiekanka z fasoli i mięs)"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Tarte Tatin (odwrócona, karmelizowana)"],
  ["Steak au poivre z sosem"],
  ["Ratatouille confite / tian warzywny"],
  ["Gratin de fruits de mer"],
  ["Pâte à choux (ptysie, éclairs)", undefined, prog("techniki", 11)],
  ["Crêpes Suzette (flambirowane)", undefined, prog("techniki", 12)],
  ["Pot-au-feu (rosół z wołowiny i warzyw)"],
  ["Rillettes / pasztet domowy"],
  ["Gotuj francuskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Clafoutis (deser z owocami)"],
  ["Bouillabaisse (marsylska zupa rybna)"],
  ["Duck à l'orange (kaczka)"],
  ["Gougères (ptysie z serem)"],
  ["Financiers / madeleines"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Confit de canard (kaczka konfitowana)", undefined, prog("techniki", 13)],
  ["Soufflé au fromage (wytrawny suflet)"],
  ["Bourguignon i garnitury na obiad dla gości"],
  ["Sauce demi-glace (redukcja bazowa)"],
  ["Pâte feuilletée (ciasto francuskie od podstaw)", undefined, prog("techniki", 14)],
  ["Coquilles Saint-Jacques (przegrzebki)"],
  ["Tarte au citron meringuée"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Cassoulet toulousain pełnowartościowy"],
  ["Pissaladière / tarte fine"],
  ["Croissants od podstaw (ciasto laminowane)", undefined, prog("techniki", 15)],
  ["Macarons (bezowe ciasteczka)", undefined, prog("techniki", 16)],
  ["Île flottante"],
  ["Navarin d'agneau (jagnięcina)"],
  ["Paris-Brest (ptysie + praliné)"],
  ["Lapin à la moutarde (królik)"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Terrine / pâté de campagne"],
  ["Zaserwuj spójne 3-daniowe menu francuskie (entrée–plat–dessert)"],
  ["Boeuf bourguignon + gratin dauphinois jako komplet"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj francuskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Mille-feuille (ciasto francuskie + krem)", undefined, prog("techniki", 17)],
  ["Consommé (klarowany bulion)"],
  ["5 sosów matczynych (béchamel, velouté, espagnole, hollandaise, tomate)"],
  ["Sole meunière / ryba na maśle"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Cuisses de grenouille / escargots"],
  ["Pâté en croûte (pasztet w cieście)"],
  ["Opéra (wielowarstwowe ciasto)", undefined, prog("techniki", 18)],
  ["Foie gras poêlé / terrine"],
  ["Brioche od podstaw", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. prowansalskie lub burgundzkie)"],
  ["Galette des rois (frangipane)"],
  ["Cassoulet / choucroute na przyjęcie"],
  ["Zorganizuj francuską kolację tematyczną"],
  ["Quenelles / gratin lyoński"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Tarte fine i desery talerzowe (plating)"],
  ["Bisque de homard (zupa z homara)"],
  ["Własna, autorska interpretacja klasyka francuskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Croquembouche (wieża ptysiów w karmelu)", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu francuskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Francji"],
  ["Réveillon — świąteczna wielodaniowa uczta francuska"],
  ["Naucz kogoś francuskich technik i klasyków"],
  ["Laminowane ciasta (croissant/feuilletée) na perfekcyjnym poziomie", undefined, prog("techniki", 22)],
  ["Pełen zestaw sosów i garniturów bez przepisu"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni francuskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde francuskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne francuskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);

import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Omlet francuski — Jacques Pépin", url: yt("s10etP1p2bU") }],
  4: [{ kind: "video", title: "Soupe à l'oignon — zupa cebulowa z grzanką", url: yt("zcWbOELqqW4") }],
  7: [{ kind: "video", title: "Crêpes — cienkie naleśniki francuskie", url: yt("tinSjWPnNzg") }],
  12: [{ kind: "article", title: "Quiche lorraine — klasyczny przepis", url: "https://www.seriouseats.com/perfect-quiche-lorraine-recipe" }],
  17: [
    { kind: "video", title: "Boeuf bourguignon — wołowina w burgundzie", url: yt("zA2aDKMSlWc") },
    { kind: "article", title: "Boeuf bourguignon — przepis na duszenie", url: "https://www.seriouseats.com/beef-bourguignon-recipe" },
  ],
  21: [{ kind: "video", title: "Crème brûlée — technika karmelizacji", url: yt("a64_QLq3Liw") }],
  26: [{ kind: "video", title: "Bagietka domowa od podstaw", url: yt("5cjFVTnhNSI") }],
  35: [{ kind: "video", title: "Pâte à choux — eklery i ptysie", url: yt("pn7S1XPjblE") }],
  41: [{ kind: "article", title: "Bouillabaisse — marsylska zupa rybna", url: "https://www.bonappetit.com/recipe/bouillabaisse" }],
  47: [{ kind: "video", title: "Soufflé au fromage — jak uniknąć opadania", url: yt("5g4uzarLBUg") }],
  56: [{ kind: "video", title: "Croissanty od podstaw — ciasto laminowane", url: yt("vpwY3nmLLaA") }],
  57: [{ kind: "article", title: "Macarons — kompletny przewodnik", url: "https://www.seriouseats.com/french-macaron-recipe" }],
};
