// Lebanese cuisine ladder 1-99 — concrete dishes as levels, easy → hard.
// REALISTIC home-cook scale. Tracks: dania, techniki, + specific-dish milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "kuchnia-libanska",
  name: "Kuchnia libańska",
  icon: "🇱🇧",
  description:
    "Od hummusu po kibbeh i knafeh — konkretne dania jako poziomy. Podstawy → mezze i klasyki → falafel, kibbeh i chleby → uczta. Realna droga kucharza domowego.",
  sortOrder: 115,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Podstawy
  ["Hummus (z tahini i cieciorki)", undefined, prog("techniki", 1)],
  ["Tabbouleh (sałatka z natką i bulgurem)"],
  ["Baba ganoush (pasta z bakłażana)", undefined, prog("techniki", 2)],
  ["Fattoush (sałatka z chlebem)"],
  ["Sos tahini i dressingi", undefined, prog("techniki", 3)],
  ["Labneh (serek jogurtowy)"],
  ["Muhammara (pasta z papryki i orzechów)"],
  ["Zaatar manakish (na gotowym cieście)"],
  ["Ugotuj 5 libańskich dań", undefined, prog("dania", 5)],
  ["Pita i dipy mezze"],
  // 11-25 · Mezze i klasyki
  ["Gotuj libańskie dania regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Mieszanki przypraw (baharat, zaatar) od podstaw", undefined, prog("techniki", 4)],
  ["Falafel od podstaw (namoczona cieciorka)", undefined, prog("techniki", 5)],
  ["Shish taouk (marynowany kurczak)"],
  ["Mujadara (soczewica z ryżem i cebulą)"],
  ["Kofta (kotleciki z jagnięciny/wołowiny)"],
  ["Warak enab (nadziewane liście winogron)"],
  ["Ugotuj 15 dań", undefined, prog("dania", 15)],
  ["Ciasto na manakish / saj od podstaw", undefined, prog("techniki", 6)],
  ["Kibbeh — skorupka z bulguru i mięsa", undefined, prog("techniki", 7)],
  ["Shawarma (marynata i podanie)"],
  ["Batata harra (pikantne ziemniaki)"],
  ["Baklava (deser)"],
  ["Sfeeha / lahm bi ajin (mięsne placki)"],
  ["Fatteh (z ciecierzycą i jogurtem)"],
  // 26-45 · Średniozaawansowane
  ["Pełne mezze (8+ przekąsek)", undefined, prog("techniki", 8)],
  ["Marynaty do grilla (shish taouk, kofta)", undefined, prog("techniki", 9)],
  ["Sosy: toum (czosnkowy), tahini, jogurtowy", undefined, prog("techniki", 10)],
  ["Kibbeh nayyeh / kibbeh smażone"],
  ["Ugotuj 30 dań", undefined, prog("dania", 30)],
  ["Kousa mahshi (nadziewana cukinia)"],
  ["Kibbeh w kilku wariantach", undefined, prog("techniki", 11)],
  ["Shawarma z domowym chlebem i garniturami"],
  ["Manakish / saj od podstaw", undefined, prog("techniki", 12)],
  ["Maqluba (odwrócony ryż z mięsem i warzywami)"],
  ["Riz a djej (ryż z kurczakiem i orzechami)"],
  ["Samke harra (ryba z tahini)"],
  ["Knafeh (deser z serem)"],
  ["Gotuj libańskie dania regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Maamoul / atayef (deser)"],
  ["Grill mezze na przyjęcie"],
  ["Warak enab / kousa na dużą imprezę"],
  ["Sayadieh (ryba z ryżem)"],
  ["Halawet el jibn (deser serowy)"],
  ["Ugotuj 50 dań", undefined, prog("dania", 50)],
  // 46-65 · Zaawansowane
  ["Kibbeh w wielu formach (pieczone, smażone, w tacy)", undefined, prog("techniki", 13)],
  ["Pełny stół mezze na przyjęcie (12+ dań)"],
  ["Pieczysta jagnięcina / kharouf mahshi"],
  ["Fatteh w kilku wariantach"],
  ["Chleby saj i markook cienkie jak profesjonalne", undefined, prog("techniki", 14)],
  ["Kibbeh bil sanieh (w blasze)"],
  ["Knafeh / baklava na wysokim poziomie"],
  ["Ugotuj 70 dań", undefined, prog("dania", 70)],
  ["Shawarma/grill na dużą imprezę"],
  ["Maqluba na przyjęcie (odwracanie garnka)"],
  ["Wypieki: kaak, maamoul, atayef", undefined, prog("techniki", 15)],
  ["Syropy i desery na poziomie mistrzowskim", undefined, prog("techniki", 16)],
  ["Mezze + grill + deser jako komplet"],
  ["Danie regionalne (górski Liban / wybrzeże)"],
  ["Deser: mouhalabieh / booza"],
  ["Marynaty i pikle (kabees) w kilku wariantach"],
  ["Ugotuj 90 dań", undefined, prog("dania", 90)],
  ["Kiszonki i marynaty libańskie"],
  ["Zaserwuj spójne 3-daniowe menu libańskie"],
  ["Wieczór mezze z kilkunastoma przekąskami"],
  // 66-85 · Ekspert / regionalne
  ["Gotuj libańskie dania regularnie przez pełny sezon (6 mies.)"],
  ["Kibbeh i chleby na poziomie mistrzowskim", undefined, prog("techniki", 17)],
  ["Pełny zestaw mezze z całego Lewantu"],
  ["Owoce morza premium po libańsku"],
  ["Pieczysta jagnięcina dla gości"],
  ["Ugotuj 120 dań", undefined, prog("dania", 120)],
  ["Uczta: mezze + pieczyste + ryże + desery"],
  ["Danie górskie z Libanu na wysokim poziomie"],
  ["Wypieki libańskie (maamoul, baklava, knafeh)", undefined, prog("techniki", 18)],
  ["Kibbeh w kilku regionalnych stylach"],
  ["Suszenie/kiszenie w domu (kishk, makdous)", undefined, prog("techniki", 19)],
  ["Menu regionalne (np. Bejrut lub dolina Bekaa)"],
  ["Grill i pieczyste na dużą imprezę"],
  ["Maqluba/mansaf na przyjęcie"],
  ["Zorganizuj libańską kolację tematyczną"],
  ["Całe pieczyste jagnię na okazję"],
  ["Ugotuj 140 dań", undefined, prog("dania", 140)],
  ["Estetyczne podanie mezze (plating)"],
  ["Desery libańskie na poziomie cukierni"],
  ["Własna, autorska interpretacja dania libańskiego", undefined, prog("techniki", 20)],
  // 86-99 · Mistrzostwo (kucharz domowy)
  ["Kibbeh, chleby i desery na perfekcyjnym poziomie", undefined, prog("techniki", 21)],
  ["Zaserwuj pełne 4-daniowe menu libańskie"],
  ["Ugotuj 160 dań", undefined, prog("dania", 160)],
  ["Menu degustacyjne inspirowane jednym regionem Lewantu"],
  ["Uczta świąteczna (Eid) — wielodaniowa"],
  ["Naucz kogoś libańskich technik (kibbeh, falafel, chleby)"],
  ["Kibbeh i wypieki bez przepisu", undefined, prog("techniki", 22)],
  ["Pełny repertuar mezze z pamięci"],
  ["Ugotuj 190 dań", undefined, prog("dania", 190)],
  ["Ułóż i wykonaj menu na przyjęcie dla kilkunastu osób"],
  ["Twoje dania są rozpoznawalne i chwalone przez bliskich"],
  ["Stwórz autorskie danie w duchu kuchni libańskiej", undefined, prog("techniki", 23)],
  ["Gotujesz swobodnie niemal każde libańskie danie, jakie zaplanujesz"],
  ["Poziom mistrzowski (kucharz domowy): pełne libańskie menu bez przepisu", "Dalsze, „restauracyjne” osiągnięcia potwierdzają osobne certyfikaty."],
]);
