// Lacrosse ladder 1-99. Manual — progression tracks: matches played, goals
// (total), and competition level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "lacrosse",
  name: "Lacrosse",
  icon: "🥍",
  description:
    "Najszybszy sport na dwóch nogach — kij z siatką, piłka i wysokie tempo. Progresja: mecze, bramki i poziom rozgrywek.",
  sortOrder: 54,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Złap piłkę do kija (catch) z bliska", undefined, prog("technika", 1)],
  ["Wykonaj poprawne podanie kijem", undefined, prog("technika", 2)],
  ["Prowadź piłkę w kiju w biegu (cradling)", undefined, prog("technika", 3)],
  ["Podnieś piłkę z ziemi kijem (ground ball)", undefined, prog("technika", 4)],
  ["Wykonaj rzut do bramki", undefined, prog("technika", 5)],
  ["Wykonaj poprawny check kija (odbiór zgodny z przepisami)", undefined, prog("technika", 6)],
  ["Zrozum pozycje i ustawienie w grze", undefined, prog("technika", 7)],
  ["Zagraj pierwszy mecz treningowy", undefined, prog("mecze", 1)],
  ["Zdobądź pierwszą bramkę w grze", undefined, prog("bramki", 1)],
  ["Rozegraj pełny mecz (4 kwarty)", undefined, prog("mecze", 2)],
  // 11-25 · Regularny
  ["Trenuj lub graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Rzuć celnie zza głowy na dystans", undefined, prog("technika", 8)],
  ["Zagraj 5 meczów", undefined, prog("mecze", 5)],
  ["Zdobądź 5 bramek łącznie", undefined, prog("bramki", 5)],
  ["Wykonaj dodge (zwód minięcia obrońcy)", undefined, prog("technika", 9)],
  ["Zagraj na stałej pozycji przez cały mecz"],
  ["Zagraj 10 meczów", undefined, prog("mecze", 10)],
  ["Zdobądź 12 bramek łącznie", undefined, prog("bramki", 12)],
  ["Wygraj face-off (walkę o piłkę na środku)", undefined, prog("technika", 10)],
  ["Rozegraj mecz w lidze amatorskiej", undefined, prog("liga", 1)],
  ["Zagraj 20 meczów", undefined, prog("mecze", 20)],
  ["Zdobądź 25 bramek łącznie", undefined, prog("bramki", 25)],
  ["Wykonaj rzut z półobrotu lub zza pleców (trick shot)", undefined, prog("technika", 11)],
  ["Zdobądź 3 bramki w jednym meczu", undefined, prog("bramki-mecz", 3)],
  ["Zagraj 30 meczów", undefined, prog("mecze", 30)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zdobądź 40 bramek łącznie", undefined, prog("bramki", 40)],
  ["Opanuj grę słabszą ręką (off-hand)", undefined, prog("technika", 12)],
  ["Zagraj 50 meczów", undefined, prog("mecze", 50)],
  ["Zdobądź 60 bramek łącznie", undefined, prog("bramki", 60)],
  ["Rozegraj pełny sezon w regularnej lidze", undefined, prog("liga", 2)],
  ["Zdobądź 4 bramki w jednym meczu", undefined, prog("bramki-mecz", 4)],
  ["Graj skutecznie w obronie (slide & recover)", undefined, prog("technika", 13)],
  ["Zagraj 75 meczów", undefined, prog("mecze", 75)],
  ["Zdobądź 90 bramek łącznie", undefined, prog("bramki", 90)],
  ["Zajmij miejsce w pierwszej połowie tabeli ligowej"],
  ["Zostań liderem strzelców lub asystentów zespołu", undefined, prog("technika", 14)],
  ["Zagraj 100 meczów", undefined, prog("mecze", 100)],
  ["Zdobądź 130 bramek łącznie", undefined, prog("bramki", 130)],
  ["Rozegraj mecz w II lidze lub odpowiedniku", undefined, prog("liga", 3)],
  ["Wygraj mecz play-off"],
  ["Zdobądź 170 bramek łącznie", undefined, prog("bramki", 170)],
  ["Zagraj 150 meczów", undefined, prog("mecze", 150)],
  ["Poprowadź zespół jako kapitan", undefined, prog("technika", 15)],
  ["Zdobądź 5 bramek w jednym meczu", undefined, prog("bramki-mecz", 5)],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Zdobądź 210 bramek łącznie", undefined, prog("bramki", 210)],
  ["Rozegraj mecz w I lidze", undefined, prog("liga", 4)],
  ["Zagraj 200 meczów", undefined, prog("mecze", 200)],
  ["Zdobądź 260 bramek łącznie", undefined, prog("bramki", 260)],
  ["Zostań podstawowym zawodnikiem zespołu I-ligowego"],
  ["Zajmij miejsce w czołówce I ligi"],
  ["Zagraj 250 meczów", undefined, prog("mecze", 250)],
  ["Zdobądź 320 bramek łącznie", undefined, prog("bramki", 320)],
  ["Zdobądź 6 bramek w jednym meczu", undefined, prog("bramki-mecz", 6)],
  ["Rozegraj mecz w najwyższej lidze krajowej", undefined, prog("liga", 5)],
  ["Zdobądź 380 bramek łącznie", undefined, prog("bramki", 380)],
  ["Zagraj 300 meczów", undefined, prog("mecze", 300)],
  ["Zdobądź bramkę w meczu najwyższej ligi"],
  ["Zdobądź 440 bramek łącznie", undefined, prog("bramki", 440)],
  ["Zostań podstawowym zawodnikiem najwyższej ligi"],
  ["Zagraj 400 meczów", undefined, prog("mecze", 400)],
  ["Zdobądź 500 bramek łącznie", undefined, prog("bramki", 500)],
  ["Zostań najlepszym strzelcem rundy w lidze"],
  ["Zostań uznanym zawodnikiem swojej ligi regionalnej"],
  // 66-85 · Wyczynowy
  ["Zdobądź 560 bramek łącznie", undefined, prog("bramki", 560)],
  ["Zagraj 500 meczów", undefined, prog("mecze", 500)],
  ["Zostań filarem drużyny najwyższej ligi"],
  ["Zdobądź 620 bramek łącznie", undefined, prog("bramki", 620)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Zagraj 600 meczów", undefined, prog("mecze", 600)],
  ["Zdobądź 680 bramek łącznie", undefined, prog("bramki", 680)],
  ["Weź udział w turnieju o zasięgu ogólnokrajowym"],
  ["Zdobądź 740 bramek łącznie", undefined, prog("bramki", 740)],
  ["Zagraj 700 meczów", undefined, prog("mecze", 700)],
  ["Zdobądź bramkę w ważnym meczu ligowym"],
  ["Zdobądź 800 bramek łącznie", undefined, prog("bramki", 800)],
  ["Zagraj w międzynarodowych rozgrywkach klubowych"],
  ["Zdobądź 860 bramek łącznie", undefined, prog("bramki", 860)],
  ["Zagraj 800 meczów", undefined, prog("mecze", 800)],
  ["Zdobądź podium mistrzostw regionu z klubem"],
  ["Weź udział w turnieju o zasięgu ogólnokrajowym"],
  ["Zdobądź 920 bramek łącznie", undefined, prog("bramki", 920)],
  ["Zagraj 900 meczów", undefined, prog("mecze", 900)],
  ["Zostań kapitanem swojej drużyny klubowej"],
  // 86-99 · Elita
  ["Zdobądź 980 bramek łącznie", undefined, prog("bramki", 980)],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zagraj 1000 meczów", undefined, prog("mecze", 1000)],
  ["Zdobądź 1050 bramek łącznie", undefined, prog("bramki", 1050)],
  ["Zdobądź bramkę w ważnym meczu ligowym"],
  ["Awansuj z klubem do czołówki rozgrywek ogólnokrajowych"],
  ["Zostań czołowym strzelcem swojej ligi"],
  ["Zdobądź podium turnieju o zasięgu ogólnokrajowym"],
  ["Znajdź się w składzie gwiazd sezonu swojej ligi"],
  ["Zdobądź nagrodę MVP swojej ligi lub turnieju"],
  ["Zdobądź tytuł mistrzowski swojej ligi klubowej"],
  ["Wygraj turniej o zasięgu ogólnokrajowym"],
  ["Zdobądź uznanie w krajowym środowisku lacrosse"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej drużyny klubowej", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);
