// Archery ladder 1-99. Manual — progression tracks: shooting distance (m),
// round score (WA 720, out of 720), and competition levels. Benchmarks:
// beginner 10 m; indoor 18 m; Olympic recurve 70 m; elite 720-round 680+.
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "lucznictwo",
  name: "Łucznictwo",
  icon: "🏹",
  description:
    "Od pierwszej strzały w matę po olimpijskie 70 m i wyniki mistrzowskie. Progresja: dystans, wynik rundy WA 720 i poziom zawodów.",
  sortOrder: 28,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Poprawnie napnij łuk i przyjmij postawę strzelecką"],
  ["Wypuść pierwszą strzałę bezpiecznie w matę"],
  ["Trafij w tarczę z 5 metrów"],
  ["Opanuj pełną sekwencję strzału (postawa → ściąg → kotwica → luz)"],
  ["Trafij w tarczę z 10 metrów"],
  ["Zbierz wszystkie 3 strzały w tarczy z 10 m"],
  ["Trafij w żółte pole (środek) z 10 m"],
  ["Trafij w tarczę z 15 metrów"],
  ["Zbierz grupę 6 strzał w tarczy z 15 m"],
  ["Trafij w tarczę z 18 metrów", "Dystans halowy — standard zawodów w hali."],
  // 11-25 · Regularny
  ["Trenuj raz w tygodniu przez 4 kolejne tygodnie"],
  ["Utrzymaj stały ściąg i kotwicę w każdej strzale serii"],
  ["Trafij w tarczę z 25 metrów"],
  ["Zdobądź 400/720 w rundzie WA 720", "Runda 72 strzał — podstawowy pomiar formy."],
  ["Trafij w tarczę z 30 metrów"],
  ["Uzyskaj grupę w polu 8-9 z 18 m"],
  ["Weź udział w pierwszych zawodach"],
  ["Zdobądź 450/720 w rundzie WA 720"],
  ["Trafij w tarczę z 40 metrów"],
  ["Ustaw i skoryguj celownik na różne dystanse"],
  ["Zdobądź 500/720 w rundzie WA 720"],
  ["Trafij w tarczę z 50 metrów"],
  ["Uzyskaj powtarzalną grupę w środku z 30 m"],
  ["Trafij w tarczę z 60 metrów"],
  ["Trafij w tarczę z 70 metrów", "Dystans olimpijski (łuk klasyczny)."],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni"],
  ["Zdobądź 530/720 w rundzie WA 720"],
  ["Uzyskaj grupę w polu 9-10 z 18 m"],
  ["Zdobądź 550/720 w rundzie WA 720"],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  ["Zdobądź 560/720 w rundzie WA 720"],
  ["Ustrzelaj czystą serię (wszystkie strzały w tarczy) na 70 m"],
  ["Zdobądź 570/720 w rundzie WA 720"],
  ["Wykonaj pełen dystans zawodów bez strzału poza tarczę"],
  ["Zdobądź 580/720 w rundzie WA 720", "Poziom solidnego zawodnika klubowego."],
  ["Opanuj strzelanie w wietrze i korektę na warunki"],
  ["Zdobądź 590/720 w rundzie WA 720"],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Trafij 10/10 (żółte) w serii 6 strzał z 18 m"],
  ["Zdobądź 600/720 w rundzie WA 720", "Sześćset — próg zawodnika zaawansowanego."],
  ["Wykonaj pojedynek (head-to-head) w formacie zawodów"],
  ["Zdobądź 610/720 w rundzie WA 720"],
  ["Utrzymaj średnią 9+ na strzałę przez pełną rundę"],
  ["Zdobądź 620/720 w rundzie WA 720"],
  ["Zajmij miejsce w czołówce mistrzostw kraju (kategoria)"],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Zdobądź 625/720 w rundzie WA 720"],
  ["Wygraj pojedynek eliminacyjny w zawodach rangi krajowej"],
  ["Zdobądź 630/720 w rundzie WA 720"],
  ["Trafij 30/30 (trzy strzały w 10) z 18 m"],
  ["Zdobądź 635/720 w rundzie WA 720"],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju seniorów"],
  ["Zdobądź 640/720 w rundzie WA 720"],
  ["Utrzymaj wynik 630+ w dwóch różnych zawodach"],
  ["Zdobądź 645/720 w rundzie WA 720"],
  ["Ustrzelaj serię 60/60 (dziesięć strzał w 10) na 18 m"],
  ["Zdobądź 650/720 w rundzie WA 720", "Poziom krajowej czołówki."],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Zdobądź 655/720 w rundzie WA 720"],
  ["Uzyskaj wynik z czołówki rankingu regionalnego"],
  ["Zdobądź 660/720 w rundzie WA 720"],
  ["Wygraj zawody rangi ogólnokrajowej"],
  ["Zdobądź 665/720 w rundzie WA 720"],
  ["Utrzymaj średnią 9,3+ na strzałę w zawodach"],
  ["Uzyskaj wynik kwalifikujący do zawodów międzynarodowych"],
  // 66-85 · Wyczynowy
  ["Wystąp w zawodach międzynarodowych"],
  ["Zdobądź 668/720 w rundzie WA 720"],
  ["Zajmij miejsce w pierwszej połowie zawodów o zasięgu ogólnokrajowym"],
  ["Zdobądź 670/720 w rundzie WA 720"],
  ["Wygraj pojedynek z uznanym zawodnikiem krajowym"],
  ["Zdobądź 672/720 w rundzie WA 720"],
  ["Zdobądź punkty w klasyfikacji zawodów o zasięgu ogólnokrajowym"],
  ["Zdobądź 674/720 w rundzie WA 720"],
  ["Zajmij miejsce w pierwszej ósemce zawodów międzynarodowych"],
  ["Zdobądź 676/720 w rundzie WA 720"],
  ["Utrzymaj średnią 9,4+ na strzałę w zawodach międzynarodowych"],
  ["Zdobądź 678/720 w rundzie WA 720"],
  ["Weź udział w zawodach o zasięgu ogólnokrajowym"],
  ["Zdobądź 680/720 w rundzie WA 720", "Bardzo wysoki, wieloletnio trenowany wynik."],
  ["Zdobądź podium zawodów o zasięgu ogólnokrajowym"],
  ["Zdobądź 682/720 w rundzie WA 720"],
  ["Zajmij miejsce na podium mistrzostw regionu"],
  ["Zdobądź 684/720 w rundzie WA 720"],
  ["Wygraj zawody o zasięgu ogólnokrajowym"],
  ["Zdobądź 686/720 w rundzie WA 720"],
  // 86-99 · Elita
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Zdobądź 688/720 w rundzie WA 720"],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju amatorów"],
  ["Zdobądź 690/720 w rundzie WA 720"],
  ["Zdobądź podium mistrzostw regionu drużynowo"],
  ["Zdobądź 692/720 w rundzie WA 720"],
  ["Zdobądź medal drużynowy mistrzostw kraju amatorów"],
  ["Zdobądź 694/720 w rundzie WA 720"],
  ["Poprowadź kogoś przez podstawy łucznictwa wyczynowego"],
  ["Zdobądź 696/720 w rundzie WA 720"],
  ["Zdobądź indywidualny medal mistrzostw kraju amatorów"],
  ["Zdobądź 698/720 w rundzie WA 720"],
  ["Wygraj mistrzostwa kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): 700+/720 w rundzie WA 720", "Dojrzały, wieloletni warsztat łuczniczy zaangażowanego amatora. Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  1: prog("technika", 1), 2: prog("technika", 2), 4: prog("technika", 3),
  // dystans (m) — value = metry
  3: prog("dystans", 5), 5: prog("dystans", 10), 8: prog("dystans", 15), 10: prog("dystans", 18),
  13: prog("dystans", 25), 15: prog("dystans", 30), 19: prog("dystans", 40), 22: prog("dystans", 50),
  24: prog("dystans", 60), 25: prog("dystans", 70),
  // wynik rundy WA 720 (out of 720) — value = wynik; rośnie z poziomem (monotoniczne).
  14: prog("wynik", 400), 18: prog("wynik", 450), 21: prog("wynik", 500), 28: prog("wynik", 530),
  30: prog("wynik", 550), 32: prog("wynik", 560), 34: prog("wynik", 570), 36: prog("wynik", 580),
  38: prog("wynik", 590), 41: prog("wynik", 600), 43: prog("wynik", 610), 45: prog("wynik", 620),
  47: prog("wynik", 625), 49: prog("wynik", 630), 51: prog("wynik", 635), 53: prog("wynik", 640),
  55: prog("wynik", 645), 57: prog("wynik", 650), 59: prog("wynik", 655), 61: prog("wynik", 660),
  63: prog("wynik", 665), 67: prog("wynik", 668), 69: prog("wynik", 670), 71: prog("wynik", 672),
  73: prog("wynik", 674), 75: prog("wynik", 676), 77: prog("wynik", 678), 79: prog("wynik", 680),
  81: prog("wynik", 682), 83: prog("wynik", 684), 85: prog("wynik", 686), 87: prog("wynik", 688),
  89: prog("wynik", 690), 91: prog("wynik", 692), 93: prog("wynik", 694), 95: prog("wynik", 696),
  97: prog("wynik", 698),
  11: freq(1, 4), 26: freq(2, 12),
  // pozostałe: technika grupowania, zawody, medale — manualne.
};
