// Figure skating ladder 1-99. Manual — progression tracks: jump difficulty
// (single → double → triple → quad), spins, and test/competition levels.
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "lyzwiarstwo-figurowe",
  name: "Łyżwiarstwo figurowe",
  icon: "⛸️",
  description:
    "Od pierwszego kroku na lodzie po skoki wielokrotne i programy zawodnicze. Progresja: skoki, piruety i poziomy testowe.",
  sortOrder: 26,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Ustój na łyżwach i przejdź kilka kroków po lodzie"],
  ["Jedź do przodu odpychając się naprzemiennie"],
  ["Zatrzymaj się kontrolowanie (pługiem)"],
  ["Jedź na jednej nodze przez 3 sekundy"],
  ["Wykonaj jazdę na łukach do przodu (wężyk)"],
  ["Jedź do tyłu"],
  ["Wykonaj przekładankę do przodu w jedną stronę"],
  ["Wykonaj przekładankę do przodu w drugą stronę"],
  ["Zatrzymaj się na krawędziach (hokejowo lub T-stop)"],
  ["Wykonaj płynny obrót z jazdy przodem na tył (three turn)"],
  // 11-25 · Regularny
  ["Trenuj raz w tygodniu przez 4 kolejne tygodnie"],
  ["Wykonaj przekładanki do tyłu w obie strony"],
  ["Wykonaj jaskółkę (spirala) przez 3 sekundy"],
  ["Wykonaj pierwszy skok — waltz jump (pół obrotu)"],
  ["Wykonaj piruet stojący (upright spin) — 3 obroty"],
  ["Wykonaj skok toe loop (pojedynczy)"],
  ["Wykonaj skok salchow (pojedynczy)"],
  ["Wykonaj piruet siedzący (sit spin)"],
  ["Wykonaj skok rittberger/loop (pojedynczy)"],
  ["Wykonaj piruet w jaskółce (camel spin)"],
  ["Wykonaj skok flip (pojedynczy)"],
  ["Wykonaj skok lutz (pojedynczy)"],
  ["Połącz dwa skoki w kombinację (np. toe loop + toe loop)"],
  ["Wykonaj skok axel (1,5 obrotu)", "Kultowy skok — pierwszy z „dodatkową połówką”."],
  ["Zdaj pierwszy test łyżwiarski lub wystąp w zawodach klubowych"],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni"],
  ["Wykonaj piruet z zmianą nogi"],
  ["Wykonaj podwójny salchow"],
  ["Wykonaj podwójny toe loop"],
  ["Wykonaj piruet z pozycji Biellmann lub layback (dot. gibkości)"],
  ["Wykonaj podwójny loop"],
  ["Skomponuj i przejedź krótki program z muzyką"],
  ["Wykonaj podwójny flip"],
  ["Wykonaj kombinację dwóch podwójnych skoków"],
  ["Wykonaj podwójny lutz"],
  ["Wykonaj piruet ze zmianą pozycji (kombinowany)"],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  ["Wykonaj podwójny axel", "Poważny próg — 2,5 obrotu."],
  ["Wykonaj szybki piruet z centrowaniem (bez „wędrowania”)"],
  ["Przejedź pełny program dowolny bez upadku"],
  ["Wykonaj sekwencję kroków na poziomie zawodniczym"],
  ["Zdaj wyższy test łyżwiarski (poziom średni)"],
  ["Wykonaj kombinację z podwójnym axlem"],
  ["Utrzymaj piruet 8+ obrotów w jednej pozycji"],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  // 46-65 · Zaawansowany
  ["Trenuj 3+ razy w tygodniu przez cały sezon"],
  ["Wykonaj potrójny salchow", "Wejście w świat skoków potrójnych."],
  ["Wykonaj potrójny toe loop"],
  ["Wykonaj piruet z trudną pozycją i wysoką punktacją (poziom 4)"],
  ["Wykonaj potrójny loop"],
  ["Przejedź program z dwoma różnymi potrójnymi skokami"],
  ["Wykonaj potrójny flip"],
  ["Zajmij miejsce w czołówce mistrzostw kraju (kategoria wiekowa)"],
  ["Wykonaj potrójny lutz"],
  ["Wykonaj kombinację potrójny + podwójny"],
  ["Przejedź program krótki i dowolny w jednych zawodach bez upadku"],
  ["Wykonaj sekwencję piruetów na poziomie 4"],
  ["Wykonaj kombinację dwóch potrójnych skoków"],
  ["Zdaj najwyższy test łyżwiarski (poziom senior/złoty)"],
  ["Wykonaj potrójny axel", "3,5 obrotu — skok elitarny, mało kto go ląduje."],
  ["Zdobądź komplet potrójnych skoków (5-6 rodzajów)"],
  ["Przejedź program z trzema potrójnymi skokami"],
  ["Zajmij miejsce na podium mistrzostw kraju juniorów/seniorów"],
  ["Wykonaj program z sekwencjami i piruetami wyłącznie na poziomie 4"],
  ["Uzyskaj wynik kwalifikujący do zawodów międzynarodowych"],
  // 66-85 · Wyczynowy
  ["Wystąp w zawodach międzynarodowych juniorów"],
  ["Wykonaj program z 4+ potrójnymi skokami"],
  ["Wykonaj czysty potrójny axel w zawodach"],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Wykonaj kombinację potrójny + potrójny"],
  ["Uzyskaj wynik na poziomie krajowej czołówki seniorów"],
  ["Przejedź program dowolny bez błędów technicznych"],
  ["Zakwalifikuj się do zawodów rangi ISU (Challenger)"],
  ["Wykonaj pierwszy poczwórny skok na treningu (quad)", "Najtrudniejszy element sportu."],
  ["Zdobądź punkty w zawodach międzynarodowych"],
  ["Wykonaj czysty poczwórny toe loop lub salchow w zawodach"],
  ["Uzyskaj notę techniczną na poziomie światowej czołówki"],
  ["Przejedź program z poczwórnym skokiem i potrójnym axlem"],
  ["Zajmij miejsce w pierwszej dziesiątce zawodów międzynarodowych"],
  ["Wykonaj dwa różne poczwórne skoki w jednym programie"],
  ["Uzyskaj rekord życiowy powyżej progu światowej elity"],
  ["Weź udział w zawodach o zasięgu ogólnokrajowym"],
  ["Zdobądź podium zawodów o zasięgu ogólnokrajowym"],
  ["Wykonaj kombinację z poczwórnym skokiem"],
  ["Zdobądź podium mistrzostw kraju amatorów seniorów"],
  // 86-99 · Elita
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Wykonaj trzy poczwórne skoki w jednym programie"],
  ["Zdobądź miejsce w pierwszej dziesiątce mistrzostw kraju amatorów"],
  ["Uzyskaj wynik łączny powyżej 250 pkt (skala ISU)"],
  ["Zajmij miejsce w czołówce silnego turnieju krajowego"],
  ["Wykonaj cztery poczwórne skoki w jednym programie"],
  ["Zdobądź medal mistrzostw kraju amatorów"],
  ["Poprowadź kogoś przez zaawansowane elementy techniczne"],
  ["Zdobądź uznanie w krajowym środowisku łyżwiarskim"],
  ["Uzyskaj wynik łączny powyżej 280 pkt"],
  ["Zdobądź uznanie poza lokalnym środowiskiem łyżwiarskim"],
  ["Wygraj mistrzostwa kraju amatorów"],
  ["Zdobądź uznanie w międzynarodowym środowisku amatorskim"],
  ["Poziom mistrzowski (amatorski szczyt): wynik łączny 280+ pkt i wieloletni, dojrzały warsztat", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  1: prog("technika", 1), 2: prog("technika", 2), 3: prog("technika", 3), 4: prog("technika", 4),
  5: prog("technika", 5), 6: prog("technika", 6), 7: prog("technika", 7), 8: prog("technika", 8),
  9: prog("technika", 9), 10: prog("technika", 10), 12: prog("technika", 11), 13: prog("technika", 12),
  // skoki wg trudności (liczba połówek obrotu): waltz=1, single=2, axel=3, double=4,
  // double axel=5, triple=6, triple axel=7, quad=8.
  14: prog("skok", 1), 16: prog("skok", 2), 24: prog("skok", 3), 28: prog("skok", 4),
  37: prog("skok", 5), 47: prog("skok", 6), 60: prog("skok", 7), 74: prog("skok", 8),
  11: freq(1, 4), 26: freq(2, 12),
  // pozostałe: piruety, programy, testy, zawody — manualne (wymagają oceny/wydarzenia).
};
