// Painting ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, counts scaled for a slower medium; top tiers
// reframed as attainable mastery, real feats left to future certificates).
// Tracks: umiejetnosci, prace (finished paintings), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "malarstwo",
  name: "Malarstwo (olej / akryl)",
  icon: "🖼️",
  description:
    "Malarstwo sztalugowe — walor, kolor, kompozycja, faktura. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → wystawy i sprzedaż → dojrzały, autorski warsztat.",
  sortOrder: 82,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Przygotuj warsztat: farby, pędzle, podłoże, media", undefined, prog("umiejetnosci", 1)],
  ["Rozrób farbę i połóż gładką, równą plamę koloru", undefined, prog("umiejetnosci", 2)],
  ["Zmieszaj kolor z podstawowych barw (koło barw)", undefined, prog("umiejetnosci", 3)],
  ["Namaluj studium walorowe (podmalówka monochromatyczna)", undefined, prog("umiejetnosci", 4)],
  ["Namaluj prostą bryłę ze światłocieniem", undefined, prog("umiejetnosci", 5)],
  ["Ukończ pierwszy obraz (prosta martwa natura)", undefined, prog("prace", 2)],
  ["Opanuj przejścia tonalne (miękkie i twarde krawędzie)", undefined, prog("umiejetnosci", 6)],
  ["Zbuduj proporcje i kompozycję kadru", undefined, prog("umiejetnosci", 7)],
  ["Ukończ 6 obrazów", undefined, prog("prace", 6)],
  ["Maluj łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Maluj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Namaluj martwą naturę z kilku obiektów", undefined, prog("prace", 12)],
  ["Opanuj temperaturę barw (ciepłe/zimne w cieniu i świetle)", undefined, prog("umiejetnosci", 8)],
  ["Namaluj prosty pejzaż z planami i głębią", undefined, prog("umiejetnosci", 9)],
  ["Opanuj technikę alla prima (za jednym razem)", undefined, prog("umiejetnosci", 10)],
  ["Maluj łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Namaluj portret z uchwyceniem podobieństwa", undefined, prog("umiejetnosci", 11)],
  ["Ukończ 20 obrazów", undefined, prog("prace", 20)],
  ["Opanuj laserunki i budowanie warstw", undefined, prog("umiejetnosci", 12)],
  ["Namaluj materiały i faktury (szkło, metal, tkanina)", undefined, prog("umiejetnosci", 13)],
  ["Namaluj w plenerze z natury", undefined, prog("prace", 30)],
  ["Opanuj kompozycję barwną (harmonia, akcent, dominanta)", undefined, prog("umiejetnosci", 14)],
  ["Maluj łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Namaluj postać w otoczeniu (figura + tło)", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 35 obrazów", undefined, prog("prace", 35)],
  // 26-45 · Średniozaawansowany
  ["Maluj regularnie przez 8 kolejnych tygodni", undefined, freq(3, 8)],
  ["Opanuj światło i nastrój (pora dnia, atmosfera)", undefined, prog("umiejetnosci", 16)],
  ["Namaluj złożony pejzaż z bogatą przestrzenią", undefined, prog("umiejetnosci", 17)],
  ["Ukończ 55 obrazów", undefined, prog("prace", 55)],
  ["Namaluj portret z natury (sesja z modelem)", undefined, prog("umiejetnosci", 18)],
  ["Maluj łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Opanuj wybraną technikę na wysokim poziomie (olej / akryl)", undefined, prog("umiejetnosci", 19)],
  ["Zbuduj spójną kolorystykę w całym obrazie", undefined, prog("umiejetnosci", 20)],
  ["Ukończ 80 obrazów", undefined, prog("prace", 80)],
  ["Namaluj z wyobraźni / szkicu koncepcyjnego", undefined, prog("umiejetnosci", 21)],
  ["Opanuj wielopostaciową kompozycję narracyjną", undefined, prog("umiejetnosci", 22)],
  ["Maluj łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Namaluj serię prac o wspólnym motywie", undefined, prog("prace", 110)],
  ["Opanuj impasto i świadomą fakturę pędzla", undefined, prog("umiejetnosci", 23)],
  ["Zbuduj dopracowany obraz „wystawowy”", undefined, prog("umiejetnosci", 24)],
  ["Ukończ 140 obrazów", undefined, prog("prace", 140)],
  ["Opanuj rysunek jako fundament pod malarstwo", undefined, prog("umiejetnosci", 25)],
  ["Maluj łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Namaluj duży format z pełną kontrolą kompozycji", undefined, prog("umiejetnosci", 26)],
  ["Maluj w plenerze przez cały sezon", undefined, prog("prace", 170)],
  // 46-65 · Zaawansowany (amator)
  ["Maluj regularnie przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Wypracuj rozpoznawalny, osobisty język malarski", undefined, prog("umiejetnosci", 27)],
  ["Zbuduj spójną serię tematyczną (5-10 obrazów)", undefined, prog("umiejetnosci", 28)],
  ["Ukończ 200 obrazów", undefined, prog("prace", 200)],
  ["Maluj łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Pokaż prace publicznie i zbierz opinie odbiorców"],
  ["Namaluj ambitną, dopracowaną kompozycję figuralną", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 260 obrazów", undefined, prog("prace", 260)],
  ["Opanuj świadomą stylizację i uproszczenie formy", undefined, prog("umiejetnosci", 30)],
  ["Maluj łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj portfolio najlepszych prac"],
  ["Weź udział w wystawie zbiorowej lub konkursie malarskim"],
  ["Opanuj złożone oświetlenie i głębię atmosferyczną", undefined, prog("umiejetnosci", 31)],
  ["Ukończ 320 obrazów", undefined, prog("prace", 320)],
  ["Sprzedaj obraz / zrealizuj zamówienie", undefined, prog("umiejetnosci", 32)],
  ["Maluj łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy malarstwa", undefined, prog("umiejetnosci", 33)],
  ["Zrealizuj spójny cykl prac wokół jednego pomysłu"],
  ["Namaluj „galeryjny” obraz na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 380 obrazów", undefined, prog("prace", 380)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Maluj regularnie przez pełny sezon (6 miesięcy)"],
  ["Maluj swobodnie z wyobraźni złożone sceny", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 450 obrazów", undefined, prog("prace", 450)],
  ["Maluj łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zorganizuj małą wystawę indywidualną (lokalnie / online)"],
  ["Rozwiń warsztat na tyle, by uczyć malarstwa", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie sprzedajesz prace lub realizujesz zlecenia"],
  ["Opanuj wybraną specjalizację (portret / pejzaż / abstrakcja)", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 550 obrazów", undefined, prog("prace", 550)],
  ["Zdobądź wyróżnienie w konkursie lub uznanie w społeczności"],
  ["Maluj łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny, wieloczęściowy cykl autorski", undefined, prog("umiejetnosci", 38)],
  ["Twoje obrazy są dojrzałe i rozpoznawalne bez podpisu"],
  ["Ukończ 650 obrazów", undefined, prog("prace", 650)],
  ["Zbuduj grono odbiorców / kolekcjonerów swoich prac"],
  ["Poprowadź warsztaty lub mentoring dla malujących"],
  ["Łącz realizm i ekspresję w dojrzały, spójny sposób", undefined, prog("umiejetnosci", 39)],
  ["Zrealizuj wystawę prezentującą Twój dorobek"],
  ["Ukończ 750 obrazów", undefined, prog("prace", 750)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Maluj łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdym obrazie"],
  ["Ukończ 850 obrazów", undefined, prog("prace", 850)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych malujących w Twoim otoczeniu"],
  ["Namaluj osobisty „opus” — dużą, dopracowaną pracę lub cykl", undefined, prog("umiejetnosci", 40)],
  ["Regularnie wystawiasz swoje obrazy"],
  ["Maluj łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje prace zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 1000 obrazów", undefined, prog("prace", 1000)],
  ["Uczysz i kształtujesz kolejnych malarzy"],
  ["Masz dorobek, z którego można ułożyć wystawę retrospektywną"],
  ["Malujesz swobodnie wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski warsztat", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (count/hours/exhibition levels have none). Videos from Proko,
// Marco Bucci, Florent Farges, Sessions College, Andrew Tischler i in.
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  // — Rozszerzenie zasobów Tier 1 (wszystkie linki zweryfikowane jako aktywne) —
  2: [{ kind: "video", title: "Mieszanie koloru — metoda bez talentu (Mark Carder)", url: yt("hGMRrpYmsr8") }],
  6: [{ kind: "video", title: "Pierwsza martwa natura w oleju — pełny tutorial", url: yt("Ab94OeQg7u0") }],
  9: [{ kind: "video", title: "Jak zbudować stały nawyk malowania (daily studies)", url: yt("GCbI4V7OmFQ") }],
  10: [{ kind: "video", title: "Jak urządzić pracownię malarską w domu", url: yt("-Wa8ETg7-sI") }],
  11: [{ kind: "video", title: "Jak malować codziennie, gdy brakuje czasu", url: yt("NX2VFiTfbk4") }],
  12: [{ kind: "video", title: "Opanowanie kompozycji w malarstwie (Ian Roberts)", url: yt("GSSB6LjrKNU") }],
  16: [{ kind: "video", title: "Malowanie szpachlą — technika dla początkujących", url: yt("h0jnUpPXEs8") }],
  18: [{ kind: "video", title: "Malarstwo w plenerze — wprowadzenie krok po kroku", url: yt("qIdMVtHhQQA") }],
  21: [{ kind: "video", title: "Ciepłe i zimne barwy — sekret lepszych obrazów", url: yt("JTVZgbNBBnY") }],
  24: [{ kind: "video", title: "Jak zbudować profesjonalne portfolio artysty", url: yt("Jl-gcqSzyWA") }],
  27: [{ kind: "video", title: "Malarstwo olejne dla początkujących — demo krok po kroku", url: yt("p848X4-_VPQ") }],
  1: [{ kind: "video", title: "Materiały do malarstwa (akryl)", url: yt("2P3dAsa2qvQ") }],
  3: [{ kind: "video", title: "Mieszanie kolorów — podstawy", url: yt("dbkX2uFwFdk") }],
  4: [{ kind: "video", title: "Podmalówka walorowa (grisaille)", url: yt("uFXapKNNoBA") }],
  5: [{ kind: "video", title: "Malowanie kuli — światło i cień", url: yt("_TksazgJkic") }],
  7: [{ kind: "video", title: "Miękkie i twarde krawędzie", url: yt("qkl-Kty0P44") }],
  8: [{ kind: "video", title: "Kompozycja obrazu — poradnik", url: yt("mkzMbm1Rm5s") }],
  13: [{ kind: "video", title: "Temperatura barw (Proko)", url: yt("vdvOGfWYxqk") }],
  14: [{ kind: "video", title: "Pejzaż — perspektywa powietrzna", url: yt("34V7VFOX7ow") }],
  15: [{ kind: "video", title: "Technika alla prima", url: yt("Os9tef7ALoA") }],
  17: [{ kind: "video", title: "Malowanie portretu — 5 kroków", url: yt("Vhie4Gv8Igc") }],
  19: [{ kind: "video", title: "Laserunki w malarstwie olejnym", url: yt("edLPcLNrh1M") }],
  20: [{ kind: "video", title: "Malowanie metalu i szkła", url: yt("RjFzSoXFAO4") }],
  22: [{ kind: "video", title: "Harmonia barw (Marco Bucci)", url: yt("4LhcNbFMkTw") }],
  39: [{ kind: "video", title: "Impasto — malowanie szpachlą", url: yt("iT4NOCH_Umg") }],
};
