// 3D modelling ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, model counts scaled; top tiers reframed as
// attainable mastery, real feats left to future certificates).
// Tracks: umiejetnosci, modele (finished models), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "modelowanie-3d",
  name: "Modelowanie 3D",
  icon: "🧊",
  description:
    "Tworzenie modeli i grafiki 3D — od brył po rzeźbę cyfrową i rendering. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → portfolio i zlecenia → dojrzały warsztat.",
  sortOrder: 96,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Poruszaj się w widoku 3D i twórz prymitywy (bryły)", undefined, prog("umiejetnosci", 1)],
  ["Przekształcaj obiekty (move, rotate, scale, pivot)", undefined, prog("umiejetnosci", 2)],
  ["Edytuj siatkę (wierzchołki, krawędzie, ściany)", undefined, prog("umiejetnosci", 3)],
  ["Użyj extrude, bevel, loop cut do budowy formy", undefined, prog("umiejetnosci", 4)],
  ["Zmodeluj prosty przedmiot (kubek, krzesło, stół)", undefined, prog("modele", 3)],
  ["Zastosuj modyfikatory (subdivision, mirror)", undefined, prog("umiejetnosci", 5)],
  ["Ustaw materiał i podstawowe światło do renderu", undefined, prog("umiejetnosci", 6)],
  ["Wyrenderuj pierwszą scenę do obrazu", undefined, prog("umiejetnosci", 7)],
  ["Ukończ 10 modeli", undefined, prog("modele", 10)],
  ["Modeluj 3D łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Modeluj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Opanuj czystą topologię (quady, edge flow) prostego obiektu", undefined, prog("umiejetnosci", 8)],
  ["Rozłóż UV i nałóż teksturę (unwrapping + mapowanie)", undefined, prog("umiejetnosci", 9)],
  ["Zmodeluj prop hard-surface (broń, sprzęt, mebel z detalem)", undefined, prog("modele", 20)],
  ["Zbuduj materiał PBR (kolor, metaliczność, chropowatość)", undefined, prog("umiejetnosci", 10)],
  ["Modeluj 3D łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Ustaw oświetlenie sceny (3-point / HDRI)", undefined, prog("umiejetnosci", 11)],
  ["Ukończ 35 modeli", undefined, prog("modele", 35)],
  ["Zmodeluj środowisko / dioramę z kilku obiektów", undefined, prog("umiejetnosci", 12)],
  ["Wypiecz mapy (bake — normal, AO) z high do low poly", undefined, prog("umiejetnosci", 13)],
  ["Zbuduj wiarygodny render z kompozycją i głębią", undefined, prog("umiejetnosci", 14)],
  ["Modeluj 3D łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Zacznij rzeźbę cyfrową (sculpting — podstawy)", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 55 modeli", undefined, prog("modele", 55)],
  ["Zmodeluj obiekt organiczny (roślina, skała, stworzenie proste)", undefined, prog("umiejetnosci", 16)],
  // 26-45 · Średniozaawansowany
  ["Modeluj regularnie przez 8 kolejnych tygodni", undefined, freq(3, 8)],
  ["Wyrzeźb postać / głowę z anatomią (sculpting zaawansowany)", undefined, prog("umiejetnosci", 17)],
  ["Wykonaj retopologię rzeźby do czystej siatki", undefined, prog("umiejetnosci", 18)],
  ["Ukończ 80 modeli", undefined, prog("modele", 80)],
  ["Opanuj teksturowanie proceduralne / malowanie tekstur", undefined, prog("umiejetnosci", 19)],
  ["Modeluj 3D łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Przygotuj model game-ready (low poly + mapy + optymalizacja)", undefined, prog("umiejetnosci", 20)],
  ["Zbuduj złożone środowisko z modularnych elementów", undefined, prog("umiejetnosci", 21)],
  ["Opanuj rigging i przygotowanie modelu do animacji", undefined, prog("umiejetnosci", 22)],
  ["Wyrenderuj fotorealistyczną scenę (materiały, GI, głębia)", undefined, prog("umiejetnosci", 23)],
  ["Ukończ 110 modeli", undefined, prog("modele", 110)],
  ["Zbuduj postać zdatną do produkcji (od sculptu po teksturę)", undefined, prog("umiejetnosci", 24)],
  ["Modeluj 3D łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Opanuj symulacje (tkanina, cząsteczki, płyny — podstawy)", undefined, prog("umiejetnosci", 25)],
  ["Ukończ 150 modeli", undefined, prog("modele", 150)],
  ["Zbuduj rozpoznawalny styl / specjalizację 3D", undefined, prog("umiejetnosci", 26)],
  ["Modeluj 3D łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Zmodeluj asseta studio-ready (postać / pojazd / lokacja)", undefined, prog("umiejetnosci", 27)],
  ["Ukończ 190 modeli", undefined, prog("modele", 190)],
  ["Modeluj regularnie przez 3 miesiące", undefined, prog("modele", 220)],
  // 46-65 · Zaawansowany (amator)
  ["Modeluj regularnie przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Zrealizuj pełny asset pipeline (concept → model → tekstura → render)", undefined, prog("umiejetnosci", 28)],
  ["Opanuj mistrzowski rendering / lookdev", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 270 modeli", undefined, prog("modele", 270)],
  ["Modeluj 3D łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Publikuj prace i buduj portfolio (ArtStation / Sketchfab)"],
  ["Zbuduj profesjonalne portfolio pod studio / klienta", undefined, prog("umiejetnosci", 30)],
  ["Ukończ 330 modeli", undefined, prog("modele", 330)],
  ["Opanuj wybraną specjalizację na wysokim poziomie (env/char/hard-surface)", undefined, prog("umiejetnosci", 31)],
  ["Modeluj 3D łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Wygraj lub wyróżnij się w konkursie / challenge 3D"],
  ["Sprzedaj pierwszy model / zdobądź płatne zlecenie"],
  ["Zrealizuj shot / asset na poziomie produkcyjnym", undefined, prog("umiejetnosci", 32)],
  ["Ukończ 400 modeli", undefined, prog("modele", 400)],
  ["Realizuj płatne zlecenia 3D regularnie", undefined, prog("umiejetnosci", 33)],
  ["Modeluj 3D łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy modelowania 3D"],
  ["Zrealizuj pełną, samodzielną scenę / produkcję 3D"],
  ["Zmodeluj asseta na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 480 modeli", undefined, prog("modele", 480)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Modeluj regularnie przez pełny sezon (6 miesięcy)"],
  ["Modeluj swobodnie dowolny asset, jaki zaplanujesz", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 580 modeli", undefined, prog("modele", 580)],
  ["Modeluj 3D łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zbuduj społeczność / grono odbiorców swoich prac"],
  ["Rozwiń warsztat na tyle, by uczyć grafiki 3D", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie realizujesz płatne zlecenia 3D"],
  ["Opanuj każdą podstawową specjalizację 3D na wysokim poziomie", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 700 modeli", undefined, prog("modele", 700)],
  ["Zdobądź wyróżnienie w konkursie lub uznanie w społeczności"],
  ["Modeluj 3D łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny projekt autorski (duża scena / kolekcja)", undefined, prog("umiejetnosci", 38)],
  ["Twoje assety są dojrzałe i rozpoznawalne", undefined, prog("umiejetnosci", 39)],
  ["Ukończ 850 modeli", undefined, prog("modele", 850)],
  ["Zbuduj markę o zasięgu ponadlokalnym"],
  ["Poprowadź warsztaty lub mentoring dla artystów 3D"],
  ["Publikuj kursy lub tutoriale 3D"],
  ["Zrealizuj pokaz lub publikację prezentującą dorobek"],
  ["Ukończ 1000 modeli", undefined, prog("modele", 1000)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Modeluj 3D łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdej pracy"],
  ["Ukończ 1200 modeli", undefined, prog("modele", 1200)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych artystów 3D w Twoim otoczeniu"],
  ["Zrealizuj osobisty „opus” — dużą scenę lub kolekcję", undefined, prog("umiejetnosci", 40)],
  ["Regularnie publikujesz prace lub realizujesz duże zlecenia"],
  ["Modeluj 3D łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje prace zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 1400 modeli", undefined, prog("modele", 1400)],
  ["Uczysz i kształtujesz kolejnych artystów 3D"],
  ["Masz dorobek, z którego można ułożyć retrospektywę"],
  ["Zmodelujesz w 3D niemal wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski warsztat", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (warsztat Blendera: modelowanie, tekstury, render, rzeźba).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Nawigacja w widoku 3D (Blender)", url: yt("sP98s2lPOu0") }],
  4: [{ kind: "video", title: "Extrude, inset, bevel, loop cut", url: yt("Kf0giCUUo7c") }],
  6: [{ kind: "video", title: "Modyfikatory: Subdivision i Mirror", url: yt("09BEJuEbFvE") }],
  7: [{ kind: "video", title: "Materiały i oświetlenie sceny", url: yt("M_GsS8U1nmA") }],
  12: [{ kind: "video", title: "Czysta topologia i edge flow", url: yt("HUjpeqpd53A") }],
  13: [{ kind: "video", title: "Rozkładanie UV (unwrapping)", url: yt("qa_1LjeWsJg") }],
  15: [{ kind: "video", title: "Materiały PBR — konfiguracja", url: yt("Mzk5142ab84") }],
  17: [{ kind: "video", title: "Oświetlenie sceny z HDRI", url: yt("QNr7lwhW0h4") }],
  20: [{ kind: "video", title: "Wypiekanie map normalnych (high→low)", url: yt("8cCk8h9Eotk") }],
  23: [{ kind: "video", title: "Rzeźba cyfrowa dla początkujących", url: yt("Lxem4yMs5Dg") }],
  33: [{ kind: "video", title: "Model game-ready (low poly)", url: yt("1hqT62kEThk") }],
};
