// Video editing / filmmaking ladder 1-99 — REALISTIC personal-progression scale
// (dedicated hobbyist; hours capped ~1200, project counts scaled; top tiers
// reframed as attainable mastery, real feats left to future certificates).
// Tracks: umiejetnosci, projekty (finished edits), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "montaz-wideo",
  name: "Montaż wideo",
  icon: "🎬",
  description:
    "Montaż i produkcja filmowa — od pierwszych cięć po dopracowane produkcje. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → portfolio i zlecenia → dojrzały, autorski styl.",
  sortOrder: 94,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Zaimportuj materiał i ułóż go na osi czasu", undefined, prog("umiejetnosci", 1)],
  ["Wykonaj podstawowe cięcia (trim, ripple, roll)", undefined, prog("umiejetnosci", 2)],
  ["Dodaj proste przejścia i tytuły", undefined, prog("umiejetnosci", 3)],
  ["Zsynchronizuj obraz z dźwiękiem/muzyką", undefined, prog("umiejetnosci", 4)],
  ["Zmontuj wideo do rytmu muzyki (cięcia na beat)", undefined, prog("umiejetnosci", 5)],
  ["Wyeksportuj film w prawidłowych ustawieniach", undefined, prog("umiejetnosci", 6)],
  ["Zbuduj prostą narrację (początek-środek-koniec)", undefined, prog("umiejetnosci", 7)],
  ["Ukończ pierwszy zmontowany film (np. vlog / klip)", undefined, prog("projekty", 2)],
  ["Ukończ 5 projektów", undefined, prog("projekty", 5)],
  ["Montuj łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Montuj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Opanuj J-cut i L-cut (montaż dźwiękowy)", undefined, prog("umiejetnosci", 8)],
  ["Wyczyść i zmiksuj dźwięk (poziomy, szum, muzyka pod dialog)", undefined, prog("umiejetnosci", 9)],
  ["Zmontuj wywiad / dialog dwóch ujęć płynnie", undefined, prog("umiejetnosci", 10)],
  ["Ukończ 10 projektów", undefined, prog("projekty", 10)],
  ["Montuj łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Opanuj podstawową korekcję i color grading", undefined, prog("umiejetnosci", 11)],
  ["Ukończ 18 projektów", undefined, prog("projekty", 18)],
  ["Dodaj proste efekty i grafiki ruchome (motion graphics)", undefined, prog("umiejetnosci", 12)],
  ["Kontroluj rytm i tempo montażu (pacing sceny)", undefined, prog("umiejetnosci", 13)],
  ["Zmontuj krótki film narracyjny (fabuła / reportaż)", undefined, prog("umiejetnosci", 14)],
  ["Montuj łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Opanuj keyframing (animacja parametrów, ruch w poście)", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 28 projektów", undefined, prog("projekty", 28)],
  ["Zmontuj teledysk / dynamiczny montaż z efektami", undefined, prog("umiejetnosci", 16)],
  // 26-45 · Średniozaawansowany
  ["Montuj regularnie przez 8 kolejnych tygodni", undefined, freq(3, 8)],
  ["Opanuj zaawansowany color grading (koła barw, LUT, sceny)", undefined, prog("umiejetnosci", 17)],
  ["Zmontuj film z wieloma liniami narracyjnymi", undefined, prog("umiejetnosci", 18)],
  ["Ukończ 40 projektów", undefined, prog("projekty", 40)],
  ["Opanuj miks dźwięku (dialog + muzyka + efekty spójnie)", undefined, prog("umiejetnosci", 19)],
  ["Montuj łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Wykonaj efekty VFX (maskowanie, keying green screen, tracking)", undefined, prog("umiejetnosci", 20)],
  ["Zbuduj napięcie i emocje montażem (rytm, cisza, muzyka)", undefined, prog("umiejetnosci", 21)],
  ["Zmontuj film dokumentalny lub reportaż o strukturze", undefined, prog("umiejetnosci", 22)],
  ["Zaprojektuj spójną oprawę graficzną (intro, lower thirds, outro)", undefined, prog("umiejetnosci", 23)],
  ["Ukończ 55 projektów", undefined, prog("projekty", 55)],
  ["Zmontuj reklamę / spot z jasnym przekazem", undefined, prog("umiejetnosci", 24)],
  ["Montuj łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Opanuj workflow z materiałem RAW/log i wysokim bitrate", undefined, prog("umiejetnosci", 25)],
  ["Ukończ 75 projektów", undefined, prog("projekty", 75)],
  ["Zbuduj rozpoznawalny styl montażu", undefined, prog("umiejetnosci", 26)],
  ["Montuj łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Zmontuj film o długości 20+ min z utrzymanym rytmem", undefined, prog("umiejetnosci", 27)],
  ["Ukończ 95 projektów", undefined, prog("projekty", 95)],
  ["Montuj regularnie przez 3 miesiące", undefined, prog("projekty", 110)],
  // 46-65 · Zaawansowany (amator)
  ["Montuj regularnie przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Zrealizuj krótki film fabularny (od zdjęć po post)", undefined, prog("umiejetnosci", 28)],
  ["Zbuduj profesjonalne portfolio / showreel", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 140 projektów", undefined, prog("projekty", 140)],
  ["Montuj łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Publikuj i buduj widownię (YouTube / social)"],
  ["Zrealizuj złożony projekt z ekipą (reklama / film)", undefined, prog("umiejetnosci", 30)],
  ["Ukończ 175 projektów", undefined, prog("projekty", 175)],
  ["Opanuj grading kinowy (HDR, spójność scen, look)", undefined, prog("umiejetnosci", 31)],
  ["Montuj łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Wygraj lub wyróżnij się w konkursie / na festiwalu"],
  ["Sprzedaj pierwsze zlecenie montażowe"],
  ["Zmontuj film pokazany publicznie / na festiwalu", undefined, prog("umiejetnosci", 32)],
  ["Ukończ 210 projektów", undefined, prog("projekty", 210)],
  ["Realizuj płatne zlecenia montażowe regularnie", undefined, prog("umiejetnosci", 33)],
  ["Montuj łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy montażu"],
  ["Zrealizuj spójny cykl / serię filmów"],
  ["Zmontuj produkcję na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 250 projektów", undefined, prog("projekty", 250)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Montuj regularnie przez pełny sezon (6 miesięcy)"],
  ["Opanuj reżyserię montażu (storytelling na wysokim poziomie)", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 300 projektów", undefined, prog("projekty", 300)],
  ["Montuj łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zbuduj społeczność / grono odbiorców swoich filmów"],
  ["Rozwiń warsztat na tyle, by uczyć montażu", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie realizujesz płatne produkcje"],
  ["Opanuj każdy gatunek i format na wysokim poziomie", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 380 projektów", undefined, prog("projekty", 380)],
  ["Zdobądź wyróżnienie na festiwalu lub uznanie w społeczności"],
  ["Montuj łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny film autorski (krótki metraż / dokument)", undefined, prog("umiejetnosci", 38)],
  ["Twój montaż jest dojrzały i rozpoznawalny", undefined, prog("umiejetnosci", 39)],
  ["Ukończ 460 projektów", undefined, prog("projekty", 460)],
  ["Zbuduj markę o zasięgu ponadlokalnym"],
  ["Poprowadź warsztaty lub mentoring dla montażystów"],
  ["Publikuj kursy lub tutoriale montażu"],
  ["Zrealizuj pokaz lub publikację prezentującą dorobek"],
  ["Ukończ 540 projektów", undefined, prog("projekty", 540)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Montuj łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdej produkcji"],
  ["Ukończ 620 projektów", undefined, prog("projekty", 620)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych montażystów w Twoim otoczeniu"],
  ["Zrealizuj osobisty „opus” — samodzielny film autorski", undefined, prog("umiejetnosci", 40)],
  ["Regularnie publikujesz filmy lub realizujesz duże produkcje"],
  ["Montuj łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje produkcje zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 720 projektów", undefined, prog("projekty", 720)],
  ["Uczysz i kształtujesz kolejnych montażystów"],
  ["Masz dorobek, z którego można ułożyć retrospektywę"],
  ["Zmontujesz niemal każdą produkcję, jaką sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski styl", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (fundamenty warsztatu montażysty).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Montaż dla początkujących — od zera", url: yt("r_muqG_O2u8") }],
  2: [{ kind: "video", title: "Cięcia: trim, ripple, roll, slip, slide", url: yt("UJ3oZqmZ0tc") }],
  4: [{ kind: "video", title: "Synchronizacja obrazu z dźwiękiem", url: yt("84ZHVsrTvGk") }],
  5: [{ kind: "video", title: "Montaż do rytmu muzyki (cięcia na beat)", url: yt("3ZhrMNIaBLk") }],
  6: [{ kind: "video", title: "Ustawienia eksportu na YouTube", url: yt("7ceGQPt6GG4") }],
  12: [{ kind: "video", title: "J-cut i L-cut — montaż dźwiękowy", url: yt("wIw9CA-M0Ic") }],
  17: [{ kind: "video", title: "Korekcja i color grading od zera", url: yt("QB_GKc6LqIM") }],
  19: [{ kind: "video", title: "Motion graphics dla początkujących", url: yt("5tQ0hf2SCeo") }],
  23: [{ kind: "video", title: "Keyframing — animacja parametrów", url: yt("F34rkILSGrA") }],
  32: [{ kind: "video", title: "Green screen — keying (chroma key)", url: yt("BIhUbLmOf14") }],
};
