// Motocross ladder 1-99. Manual — progression tracks: technique, races, and
// competition level (amateur → national → MXGP world championship).
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "motocross",
  name: "Motocross",
  icon: "🏍️",
  description:
    "Wyścigi motocyklowe po torach terenowych — skoki, hopy i walka koło w koło. Progresja: technika jazdy, wyścigi i poziom rywalizacji.",
  sortOrder: 76,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj kontrolę sprzęgła, gazu i hamulców w terenie", undefined, prog("technika", 1)],
  ["Jedź pewnie w pozycji stojącej na podnóżkach", undefined, prog("technika", 2)],
  ["Pokonaj zakręt w koleinie (rut) z kontrolą", undefined, prog("technika", 3)],
  ["Pokonaj małą hopę z lądowaniem na obu kołach", undefined, prog("technika", 4)],
  ["Przejedź pełne okrążenie toru motocrossowego", undefined, prog("technika", 5)],
  ["Pokonaj sekcję muld (whoops) bez utraty kontroli", undefined, prog("technika", 6)],
  ["Wykonaj skok na średniej hopie (kicker)", undefined, prog("technika", 7)],
  ["Weź udział w pierwszym treningu wyścigowym z innymi", undefined, prog("wyscigi", 1)],
  ["Opanuj start z bramki startowej (holeshot technique)", undefined, prog("technika", 8)],
  ["Ukończ 3 wyścigi amatorskie", undefined, prog("wyscigi", 3)],
  // 11-25 · Regularny
  ["Trenuj/ścigaj się raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Opanuj skok tabletop w pełni (clear the jump)", undefined, prog("technika", 9)],
  ["Ukończ 6 wyścigów", undefined, prog("wyscigi", 6)],
  ["Zdobądź licencję zawodniczą (krajowa)", undefined, prog("liga", 1)],
  ["Utrzymaj pozycję w czołówce wyścigu amatorskiego", undefined, prog("technika", 10)],
  ["Ukończ 10 wyścigów", undefined, prog("wyscigi", 10)],
  ["Wygraj pierwszy wyścig w klasie amatorskiej"],
  ["Opanuj jazdę w błocie i trudnym terenie", undefined, prog("technika", 11)],
  ["Ukończ 20 wyścigów", undefined, prog("wyscigi", 20)],
  ["Pokonaj double jump (podwójny skok)", undefined, prog("technika", 12)],
  ["Wystartuj w mistrzostwach strefowych/okręgowych", undefined, prog("liga", 2)],
  ["Ukończ 30 wyścigów", undefined, prog("wyscigi", 30)],
  ["Zajmij miejsce w pierwszej połowie wyścigu rangi strefowej"],
  ["Opanuj scrub (płaski, szybki skok) — podstawy", undefined, prog("technika", 13)],
  ["Ukończ 45 wyścigów", undefined, prog("wyscigi", 45)],
  // 26-45 · Średniozaawansowany
  ["Trenuj systematycznie (jazda + kondycja) przez sezon", undefined, freq(2, 12)],
  ["Zajmij miejsce na podium wyścigu strefowego"],
  ["Ukończ 60 wyścigów", undefined, prog("wyscigi", 60)],
  ["Pokonaj triple jump (potrójny skok)", undefined, prog("technika", 14)],
  ["Zdobądź holeshot (prowadzenie po starcie) w wyścigu", undefined, prog("technika", 15)],
  ["Ukończ 80 wyścigów", undefined, prog("wyscigi", 80)],
  ["Wygraj wyścig w mistrzostwach strefowych"],
  ["Awansuj do wyższej klasy pojemnościowej (np. MX2 250)", undefined, prog("liga", 3)],
  ["Ukończ 100 wyścigów", undefined, prog("wyscigi", 100)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju"],
  ["Opanuj scrub na dużej prędkości", undefined, prog("technika", 16)],
  ["Ukończ 130 wyścigów", undefined, prog("wyscigi", 130)],
  ["Zdobądź podium w rundzie mistrzostw kraju"],
  ["Utrzymaj tempo lidera przez cały moto (wyścig ~30 min + 2 okr.)", undefined, prog("technika", 17)],
  ["Ukończ 160 wyścigów", undefined, prog("wyscigi", 160)],
  ["Zdobądź minimum/licencję do startów międzynarodowych", undefined, prog("liga", 4)],
  ["Zajmij miejsce w pierwszej piątce mistrzostw kraju"],
  ["Ukończ 200 wyścigów", undefined, prog("wyscigi", 200)],
  ["Wygraj rundę mistrzostw kraju"],
  ["Zdobądź medal mistrzostw kraju"],
  // 46-65 · Zaawansowany
  ["Trenuj z zespołem i przygotowaniem fizycznym przez sezon"],
  ["Opanuj perfekcyjną technikę skoków i szybkich linii", undefined, prog("technika", 18)],
  ["Zostań mistrzem kraju w swojej klasie"],
  ["Ukończ 250 wyścigów", undefined, prog("wyscigi", 250)],
  ["Zdobądź holeshot w wyścigu mistrzostw kraju"],
  ["Wystartuj w zawodach międzynarodowych (EMX / runda MXGP jako wildcard)", undefined, prog("liga", 5)],
  ["Zajmij miejsce w pierwszej połowie zawodów międzynarodowych"],
  ["Ukończ 300 wyścigów", undefined, prog("wyscigi", 300)],
  ["Opanuj walkę o pozycję z zawodnikami międzynarodowymi", undefined, prog("technika", 19)],
  ["Zakwalifikuj się do wyścigu głównego zawodów EMX/MXGP"],
  ["Zajmij miejsce w pierwszej piętnastce zawodów międzynarodowych"],
  ["Ukończ 350 wyścigów", undefined, prog("wyscigi", 350)],
  ["Zdobądź punkty w mistrzostwach Europy EMX"],
  ["Zajmij miejsce w pierwszej dziesiątce rundy o zasięgu regionalnym"],
  ["Ukończ 400 wyścigów", undefined, prog("wyscigi", 400)],
  ["Zdobądź uznanie w silnym zespole motocrossowym", undefined, prog("liga", 6)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw regionu"],
  ["Utrzymaj wysoką formę na dwóch wyścigach w jednym dniu", undefined, prog("technika", 20)],
  ["Ukończ 450 wyścigów", undefined, prog("wyscigi", 450)],
  ["Zdobądź podium w rundzie mistrzostw regionu"],
  // 66-85 · Wyczynowy
  ["Zdobądź medal mistrzostw regionu"],
  ["Ukończ 500 wyścigów", undefined, prog("wyscigi", 500)],
  ["Wygraj rundę mistrzostw regionu"],
  ["Zdobądź punkty w mistrzostwach kraju amatorów"],
  ["Zajmij miejsce w pierwszej dwudziestce rundy o zasięgu ogólnokrajowym", undefined, prog("technika", 21)],
  ["Ukończ 600 wyścigów", undefined, prog("wyscigi", 600)],
  ["Regularnie kwalifikuj się do wyścigu głównego zawodów o zasięgu ogólnokrajowym"],
  ["Zajmij miejsce w pierwszej piętnastce mistrzostw kraju amatorów"],
  ["Zdobądź uznanie w silnym zespole zawodów o zasięgu ogólnokrajowym", undefined, prog("liga", 7)],
  ["Ukończ 700 wyścigów", undefined, prog("wyscigi", 700)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju amatorów"],
  ["Zdobądź najlepszy start w wyścigu o zasięgu ogólnokrajowym"],
  ["Zajmij miejsce w pierwszej ósemce klasyfikacji generalnej kraju amatorów"],
  ["Ukończ 800 wyścigów", undefined, prog("wyscigi", 800)],
  ["Zajmij miejsce w pierwszej piątce rundy mistrzostw kraju amatorów"],
  ["Weź udział w prestiżowym turnieju drużynowym o szerokim zasięgu"],
  ["Zdobądź podium rundy mistrzostw kraju amatorów"],
  ["Osiągnij status uznanego zawodnika w krajowym środowisku motocrossowym", undefined, prog("technika", 22)],
  ["Ukończ 900 wyścigów", undefined, prog("wyscigi", 900)],
  ["Wygraj bieg w rundzie mistrzostw kraju amatorów"],
  // 86-99 · Elita
  ["Wygraj rundę mistrzostw kraju amatorów"],
  ["Zajmij miejsce na podium klasyfikacji generalnej kraju amatorów"],
  ["Ustanów swój rekord okrążenia na lokalnym torze", undefined, prog("technika", 23)],
  ["Wygraj kilka rund mistrzostw kraju amatorów w sezonie"],
  ["Ukończ 1000 wyścigów", undefined, prog("wyscigi", 1000)],
  ["Zajmij miejsce w pierwszej trójce klasyfikacji generalnej kraju amatorów"],
  ["Weź udział w prestiżowym turnieju drużynowym reprezentując klub"],
  ["Zostań wicemistrzem kraju amatorów"],
  ["Zdobądź tytuł mistrza kraju amatorów w niższej klasie"],
  ["Zdobądź tytuł mistrza kraju amatorów", "Krajowa korona motocrossu amatorskiego."],
  ["Obroń tytuł mistrza kraju amatorów"],
  ["Zdobądź wielokrotne mistrzostwo kraju amatorów"],
  ["Poprowadź kogoś przez zaawansowaną technikę jazdy motocrossowej", undefined, prog("technika", 24)],
  ["Poziom mistrzowski (amatorski szczyt): wielokrotny mistrz kraju amatorów w motocrossie", "Dalsze, zawodowe osiągnięcia (MXGP, mistrzostwa świata) potwierdzają osobne certyfikaty."],
]);
