// Cross-country skiing ladder 1-99. Distance-logged (km/min). Benchmarks:
// recreational touring; loppet marathons (Bieg Piastów 50 km, Vasaloppet 90 km);
// racing pace 20+ km/h skate. Long marathons are the amateur pinnacle.
import type { Criterion } from "../../src/lib/milestone-criteria";
import type { MilestoneResource } from "../../src/lib/milestone-resources";
import { ladder, d, tfd, weekly, monthly, total, freq, anyOf, prog } from "./helpers";

export const activity = {
  slug: "narciarstwo-biegowe",
  name: "Narciarstwo biegowe",
  icon: "⛷️",
  description:
    "Biegówki klasykiem i łyżwą — od pierwszych kroków po maratony narciarskie typu Bieg Piastów. Przejazdy loguj w km.",
  sortOrder: 43,
  logKind: "distance" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Ustój na biegówkach i pokonaj kilka metrów klasykiem"],
  ["Opanuj krok podstawowy (diagonal) na płaskim"],
  ["Pokonaj łagodne zejście w pozycji zjazdowej"],
  ["Podejdź pod górkę jodełką"],
  ["Pokonaj 2 km klasykiem bez upadku"],
  ["Opanuj podstawy stylu łyżwowego (skating)"],
  ["Pokonaj 5 km bez przerwy", "Podstawowa trasa rekreacyjna."],
  ["Hamuj i skręcaj pługiem kontrolowanie"],
  ["Pokonaj 8 km bez przerwy"],
  ["Pokonaj 10 km bez przerwy", "Dyszka na biegówkach."],
  // 11-25 · Regularny
  ["Trenuj raz w tygodniu przez 4 kolejne tygodnie w sezonie"],
  ["Pokonaj 12 km bez przerwy"],
  ["Pokonaj 10 km poniżej 75 minut"],
  ["Opanuj podjazd łyżwą (skate uphill)"],
  ["Pokonaj 15 km bez przerwy"],
  ["Pokonaj 25 km łącznie w jednym tygodniu"],
  ["Pokonaj 18 km bez przerwy"],
  ["Pokonaj 10 km poniżej 65 minut"],
  ["Weź udział w pierwszym biegu/loppecie"],
  ["Pokonaj 20 km bez przerwy"],
  ["Pokonaj łącznie 100 km"],
  ["Pokonaj 10 km poniżej 58 minut"],
  ["Pokonaj 40 km łącznie w jednym tygodniu"],
  ["Pokonaj 25 km bez przerwy"],
  ["Pokonaj 100 km łącznie w jednym miesiącu"],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez cały sezon (12 tyg.)"],
  ["Pokonaj 30 km bez przerwy"],
  ["Pokonaj 10 km poniżej 52 minut"],
  ["Pokonaj 60 km łącznie w jednym tygodniu"],
  ["Pokonaj 35 km bez przerwy"],
  ["Ukończ Bieg Piastów lub inny loppet 25-30 km", "Kultowy polski maraton narciarski."],
  ["Pokonaj łącznie 300 km"],
  ["Pokonaj 10 km poniżej 48 minut"],
  ["Pokonaj 40 km bez przerwy"],
  ["Pokonaj 200 km łącznie w jednym miesiącu"],
  ["Pokonaj 15 km poniżej 70 minut"],
  ["Pokonaj 45 km bez przerwy"],
  ["Ukończ maraton narciarski 42 km", "Dystans maratonu na nartach."],
  ["Pokonaj 80 km łącznie w jednym tygodniu"],
  ["Pokonaj 10 km poniżej 45 minut"],
  ["Pokonaj łącznie 500 km"],
  ["Pokonaj 50 km bez przerwy", "Dystans Biegu Piastów (klasyk 50 km)."],
  ["Pokonaj 30 km poniżej 2:15"],
  ["Pokonaj 300 km łącznie w jednym miesiącu"],
  ["Pokonaj 10 km poniżej 42 minut"],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Pokonaj 55 km bez przerwy"],
  ["Pokonaj 15 km poniżej 60 minut"],
  ["Ukończ loppet 70 km (np. Marcialonga)"],
  ["Pokonaj 100 km łącznie w jednym tygodniu"],
  ["Pokonaj 10 km poniżej 40 minut", "Tempo 15 km/h — poziom zaawansowany."],
  ["Pokonaj 60 km bez przerwy"],
  ["Pokonaj łącznie 1000 km"],
  ["Pokonaj 30 km poniżej 2:00"],
  ["Ukończ Vasaloppet 90 km", "Najsłynniejszy maraton narciarski świata."],
  ["Pokonaj 400 km łącznie w jednym miesiącu"],
  ["Pokonaj 15 km poniżej 55 minut"],
  ["Pokonaj 70 km bez przerwy"],
  ["Pokonaj 10 km poniżej 38 minut"],
  ["Zajmij miejsce w pierwszej połowie stawki loppetu"],
  ["Pokonaj 80 km bez przerwy"],
  ["Pokonaj 30 km poniżej 1:50"],
  ["Pokonaj łącznie 2000 km"],
  ["Pokonaj 10 km poniżej 36 minut"],
  ["Pokonaj 90 km bez przerwy"],
  // 66-85 · Wyczynowy
  ["Pokonaj 15 km poniżej 50 minut"],
  ["Pokonaj 120 km łącznie w jednym tygodniu"],
  ["Pokonaj 10 km poniżej 34 minut"],
  ["Ukończ całą serię Ski Classics lub Worldloppet (kilka maratonów)"],
  ["Pokonaj 100 km bez przerwy", "Setka na biegówkach."],
  ["Pokonaj 30 km poniżej 1:40"],
  ["Pokonaj 10 km poniżej 32 minut"],
  ["Zajmij miejsce w czołówce dużego loppetu"],
  ["Pokonaj łącznie 3000 km"],
  ["Pokonaj 15 km poniżej 45 minut"],
  ["Pokonaj 10 km poniżej 30 minut", "Tempo 20 km/h — poziom wyczynowy."],
  ["Pokonaj 600 km łącznie w jednym miesiącu"],
  ["Ukończ ultra-maraton narciarski 100 km+ w zawodach"],
  ["Pokonaj 30 km poniżej 1:32"],
  ["Pokonaj 10 km poniżej 29 minut"],
  ["Pokonaj łącznie 5000 km"],
  ["Zajmij miejsce na podium loppetu rangi międzynarodowej"],
  ["Pokonaj 15 km poniżej 42 minut"],
  ["Pokonaj 10 km poniżej 28 minut"],
  ["Uzyskaj wynik kwalifikujący do zawodów o zasięgu ogólnokrajowym"],
  // 86-99 · Elita
  ["Pokonaj 10 km poniżej 27 minut"],
  ["Weź udział w zawodach o zasięgu ogólnokrajowym"],
  ["Pokonaj 30 km poniżej 1:25"],
  ["Pokonaj 10 km poniżej 26 minut"],
  ["Zdobądź punkty w zawodach o zasięgu ogólnokrajowym"],
  ["Pokonaj 15 km poniżej 40 minut"],
  ["Pokonaj 10 km poniżej 25 minut", "Tempo 24 km/h — bardzo wysoki, wieloletnio wypracowany poziom."],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Ukończ bieg mistrzostw kraju amatorów w regulaminowym limicie"],
  ["Pokonaj 10 km poniżej 24 minut"],
  ["Zdobądź dobry wynik w klasyfikacji zawodów krajowych"],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju amatorów"],
  ["Stań na podium zawodów o zasięgu ogólnokrajowym"],
  ["Poziom mistrzowski (amatorski szczyt): 10 km poniżej 23 minut i wieloletni, dojrzały warsztat", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, igrzyska) potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  1: prog("technika", 1), 2: prog("technika", 2), 4: prog("technika", 3), 6: prog("technika", 4), 8: prog("technika", 5),
  3: d(1), 5: d(2), 7: d(5), 9: d(8), 10: d(10),
  11: freq(1, 4), 12: d(12), 13: tfd(10, 75), 15: d(15), 16: weekly(25),
  17: d(18), 18: tfd(10, 65), 20: d(20), 21: total(100), 22: tfd(10, 58),
  23: weekly(40), 24: d(25), 25: monthly(100),
  26: freq(2, 12), 27: d(30), 28: tfd(10, 52), 29: weekly(60), 30: d(35),
  32: total(300), 33: tfd(10, 48), 34: d(40), 35: monthly(200), 36: tfd(15, 70),
  37: d(45), 39: weekly(80), 40: tfd(10, 45), 41: total(500), 42: d(50),
  43: tfd(30, 135), 44: monthly(300), 45: tfd(10, 42),
  46: freq(4, 12), 47: d(55), 48: tfd(15, 60), 50: weekly(100), 51: tfd(10, 40),
  52: d(60), 53: total(1000), 54: tfd(30, 120), 56: monthly(400), 57: tfd(15, 55),
  58: d(70), 59: tfd(10, 38), 61: d(80), 62: tfd(30, 110), 63: total(2000),
  64: tfd(10, 36), 65: d(90),
  66: tfd(15, 50), 67: weekly(120), 68: tfd(10, 34), 70: d(100), 71: tfd(30, 100),
  72: tfd(10, 32), 74: total(3000), 75: tfd(15, 45), 76: tfd(10, 30), 77: monthly(600),
  79: tfd(30, 92), 80: tfd(10, 29), 81: total(5000), 83: tfd(15, 42), 84: tfd(10, 28),
  86: tfd(10, 27), 88: tfd(30, 85), 89: tfd(10, 26), 91: tfd(15, 40), 92: tfd(10, 25),
  96: tfd(10, 24),
  99: anyOf(tfd(10, 23), prog("mistrzostwa", 1)),
  // pozostałe (14, 19, 31, 38, 49, 55, 60, 69, 73, 78, 82, 85, 87, 90, 93, 94, 95, 97, 98) — technika/loppety/zawody: manualne.
};

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Cross-country skiing basics — diagonal stride", url: yt("BPK9JGWnlD0") }],
  6: [{ kind: "video", title: "Skate skiing basics — first steps", url: yt("bDMi3yL8fFw") }],
  10: [{ kind: "article", title: "Beginner cross-country ski technique guide", url: "https://www.rei.com/learn/expert-advice/cross-country-skiing-for-beginners.html" }],
  15: [{ kind: "video", title: "How to go uphill on skate skis", url: yt("e0sTZJCfxIQ") }],
  25: [{ kind: "video", title: "Double pole technique — efficiency tips", url: yt("sJVS0ZXYsCw") }],
  31: [{ kind: "article", title: "Bieg Piastów — informacje o maratonie", url: "https://www.biegpiastow.pl/" }],
  42: [{ kind: "video", title: "Cross-country ski marathon training plan", url: yt("HUE_Xg2NfWM") }],
  55: [{ kind: "article", title: "Vasaloppet — the world's oldest cross-country ski race", url: "https://www.vasaloppet.se/en/" }],
  65: [{ kind: "video", title: "XC ski racing — V2 skate technique", url: yt("M-e_MrN-k0k") }],
  76: [{ kind: "article", title: "Ski Classics — long-distance ski race series", url: "https://www.skiclassics.com/" }],
};
