// Skiing ladder 1-99 (alpine focus, touring at the top). Tracks: slope
// difficulty progression, ski days count, vertical meters (touring).
// Manual check-offs — skill assessment is inherently subjective.
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

export const activity = {
  slug: "narciarstwo",
  name: "Narciarstwo",
  icon: "⛷️",
  description:
    "Od pługu na oślej łączce po freeride i skitury. Progresja tras: zielona → niebieska → czerwona → czarna.",
  sortOrder: 16,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Załóż sprzęt i przejdź kilka kroków na nartach", "Brzmi banalnie — nie jest."],
  ["Zjedź pługiem po oślej łączce z kontrolą prędkości"],
  ["Zatrzymaj się pługiem na komendę"],
  ["Wjedź wyciągiem talerzykowym/orczykiem bez upadku"],
  ["Skręcaj pługiem w obie strony po łagodnym stoku"],
  ["Ukończ pierwszy dzień na nartach (3+ godziny jazdy)"],
  ["Zjedź całą zieloną/łatwą niebieską trasę pługiem"],
  ["Wjedź wyciągiem krzesełkowym i zjedź samodzielnie bez asysty"],
  ["Ukończ 3 dni na nartach"],
  ["Wykonaj pierwszy skręt równoległy (narty razem w fazie skrętu)"],
  // 11-25 · Regularny
  ["Zjedź niebieską trasę skrętem zbliżonym do równoległego"],
  ["Ukończ 5 dni na nartach"],
  ["Jeźdź na nartach z kijkami z poprawnym wbiciem (timing)"],
  ["Zjedź niebieską trasę płynnie bez zatrzymania"],
  ["Kontroluj prędkość promieniem skrętu, nie pługiem", "Przełom techniczny numer jeden."],
  ["Ukończ 8 dni na nartach"],
  ["Zjedź pierwszą czerwoną trasę (dowolnie, byle bezpiecznie)"],
  ["Jeźdź na nartach poprawnym skrętem równoległym na niebieskich"],
  ["Ukończ 12 dni na nartach"],
  ["Zjedź czerwoną trasę skrętem równoległym z kontrolą"],
  ["Przejedź na nartach muldy początkujących (nierówny teren) bez upadku"],
  ["Ukończ 16 dni na nartach"],
  ["Zjedź 5 różnych czerwonych tras"],
  ["Jeźdź na nartach w lekkim śniegu/rozjeżdżonym bez utraty rytmu"],
  ["Ukończ 20 dni na nartach", "Około 3-4 tygodni wyjazdów."],
  // 26-45 · Średniozaawansowany
  ["Wykonaj pierwsze cięte skręty (carving) na łagodnym stoku", "Narta prowadzi na krawędzi, bez ślizgu."],
  ["Zjedź pierwszą czarną trasę (dowolną techniką, bezpiecznie)"],
  ["Ukończ 25 dni na nartach"],
  ["Jeźdź na nartach carvingiem na niebieskich trasach"],
  ["Zjedź czarną trasę skrętem równoległym z kontrolą"],
  ["Ukończ 30 dni na nartach"],
  ["Przejedź na nartach 20 000 m przewyższenia zjazdów w jeden dzień (licznik aplikacji)"],
  ["Jeźdź na nartach krótkim skrętem (śmig) na niebieskiej"],
  ["Zjedź czerwoną trasę carvingiem"],
  ["Ukończ 40 dni na nartach"],
  ["Zjedź w każdym typie śniegu dnia: sztywny rano, kaszana po południu"],
  ["Przejedź na nartach pierwszy odcinek poza trasą (przy stoku, bezpiecznie)"],
  ["Jeźdź na nartach śmigiem na czerwonej"],
  ["Ukończ 50 dni na nartach", "Pół setki dni — solidny narciarz rekreacyjny."],
  ["Zjedź 5 różnych czarnych tras"],
  ["Weź udział w lekcji z instruktorem doskonalącej technikę"],
  ["Zjedź długą trasę (1000+ m przewyższenia) bez zatrzymania"],
  ["Ukończ 60 dni na nartach"],
  ["Przejedź na nartach slalom gigant wyznaczony tyczkami (amatorsko)"],
  ["Jeźdź na nartach pewnie ze średnią prędkością 40+ km/h na czerwonych (licznik)"],
  // 46-65 · Zaawansowany
  ["Ukończ 75 dni na nartach"],
  ["Zjedź czarną trasę śmigiem"],
  ["Ukończ kurs lawinowy podstawowy (teoria + detektor)", "Wstęp do freeride'u i skitur."],
  ["Przejedź na nartach 30 cm świeżego puchu obok trasy"],
  ["Ukończ 90 dni na nartach"],
  ["Zjedź najtrudniejszą czarną trasę swojego ośrodka"],
  ["Wykonaj pierwszy skok z górki terenowej z kontrolowanym lądowaniem"],
  ["Ukończ pierwszy mini-skitur (500 m przewyższenia podejścia)"],
  ["Ukończ 100 dni na nartach", "Setka dni na śniegu."],
  ["Jeźdź na nartach carvingiem z wyraźnym złożeniem (kolano/biodro nisko)"],
  ["Przejedź na nartach muldy średnie rytmicznie"],
  ["Ukończ skitur 1000 m przewyższenia"],
  ["Zjedź nartostradę/trasę FIS z pełną kontrolą"],
  ["Ukończ 120 dni na nartach"],
  ["Przejedź na nartach głęboki puch (50 cm+) z pływającym rytmem", "Uczucie, dla którego ludzie rzucają pracę."],
  ["Weź udział w amatorskich zawodach (gigant/slalom)"],
  ["Ukończ skitur 1500 m przewyższenia"],
  ["Ukończ 150 dni na nartach"],
  ["Zjedź stromy żleb/ścianę 35°+ poza trasą (z asekuracją wiedzy lawinowej)"],
  ["Ukończ pełny sezon z 20+ dniami na śniegu"],
  // 66-85 · Wyczynowy
  ["Ukończ 175 dni na nartach"],
  ["Zdobądź miejsce w pierwszej połowie stawki zawodów amatorskich"],
  ["Ukończ skitur 2000 m przewyższenia w jeden dzień"],
  ["Przejedź na nartach couloir (wąski żleb) w wysokich górach"],
  ["Ukończ 200 dni na nartach"],
  ["Jeźdź na nartach switch (tyłem) na niebieskiej", "Element freestyle'u."],
  ["Wykonaj skok 360 na śniegu lub przejedź park z przeszkodami"],
  ["Ukończ wielodniowy trawers skiturowy (2+ dni)"],
  ["Ukończ 250 dni na nartach"],
  ["Zjedź z wierzchołka 3000+ m n.p.m. na nartach"],
  ["Zdobądź podium zawodów amatorskich"],
  ["Ukończ skitur 3000 m przewyższenia w jeden dzień"],
  ["Ukończ 300 dni na nartach"],
  ["Ukończ kurs lawinowy zaawansowany"],
  ["Przejedź na nartach legendarną trasę freeride (np. Vallée Blanche)"],
  ["Jeźdź na nartach w każdych warunkach: lód, muldy, puch, kaszana — jeden dzień"],
  ["Ukończ 350 dni na nartach"],
  ["Wygraj amatorskie zawody w swojej kategorii"],
  ["Zjedź ścianę 40°+ w wysokich górach"],
  ["Ukończ 400 dni na nartach", "Ponad rok czystego czasu na śniegu."],
  // 86-99 · Elita
  ["Zdobądź uprawnienia pomocnika instruktora (asystent PZN/SITN)"],
  ["Ukończ 450 dni na nartach"],
  ["Ukończ zawody skiturowe (skimo)"],
  ["Zjedź z wierzchołka 4000+ m n.p.m."],
  ["Ukończ 500 dni na nartach"],
  ["Zdobądź uprawnienia instruktora narciarstwa", "Formalny poziom nauczania."],
  ["Weź udział w lokalnych zawodach amatorskich"],
  ["Zjedź kilka znanych, wymagających tras freeride w swoim regionie"],
  ["Ukończ 600 dni na nartach"],
  ["Ukończ ekstremalny zjazd dokumentowany (45°+)"],
  ["Zostań trenerem/instruktorem prowadzącym własne grupy"],
  ["Ukończ 750 dni na nartach"],
  ["Zdobądź podium lokalnych/regionalnych zawodów amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): pewne zjazdy eksploracyjne i wieloletni warsztat", "Dojrzała, samodzielna jazda w trudnym terenie. Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  6: prog("dni", 1), 9: prog("dni", 3), 12: prog("dni", 5), 16: prog("dni", 8),
  19: prog("dni", 12), 22: prog("dni", 16), 25: prog("dni", 20), 28: prog("dni", 25),
  31: prog("dni", 30), 35: prog("dni", 40), 39: prog("dni", 50), 43: prog("dni", 60),
  46: prog("dni", 75), 50: prog("dni", 90), 54: prog("dni", 100), 59: prog("dni", 120),
  63: prog("dni", 150), 66: prog("dni", 175), 70: prog("dni", 200), 74: prog("dni", 250),
  78: prog("dni", 300), 82: prog("dni", 350), 85: prog("dni", 400), 87: prog("dni", 450),
  90: prog("dni", 500), 94: prog("dni", 600), 97: prog("dni", 750),
  7: prog("trasa", 1), 11: prog("trasa", 2), 17: prog("trasa", 3), 20: prog("trasa", 4),
  27: prog("trasa", 5), 30: prog("trasa", 6),
  53: prog("skitur", 500), 57: prog("skitur", 1000), 62: prog("skitur", 1500),
  68: prog("skitur", 2000), 77: prog("skitur", 3000),
  // technika, kursy, zawody — manualne.
};

void freq;

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Beginner pizza/wedge technique", url: yt("20VUbQ2qJbU") }],
  5: [{ kind: "video", title: "Turning basics for beginners", url: yt("5s0-yz_k3wc") }],
  10: [{ kind: "video", title: "How to parallel turn", url: yt("dNZRq-mVuaU") }],
  15: [{ kind: "video", title: "Skiing with speed control", url: yt("FnXySb4-3zM") }],
  26: [{ kind: "video", title: "Introduction to carving", url: yt("hQmEamxOobw") }],
  33: [{ kind: "video", title: "Short turns technique", url: yt("1Wnr3Kh-EXs") }],
  41: [{ kind: "article", title: "Intro to backcountry skiing", url: "https://www.rei.com/learn/expert-advice/intro-to-backcountry-skiing.html" }],
  48: [{ kind: "article", title: "Avalanche education courses", url: "https://avalanche.org/avalanche-education/" }],
  55: [{ kind: "video", title: "Advanced carving drills", url: yt("L6rYLwdZeIg") }],
  80: [{ kind: "article", title: "Vallée Blanche descent guide", url: "https://www.chamonix.com/vallee-blanche,82,en.html" }],
};
