// Scuba diving ladder 1-99. Manual — progression tracks: depth (m),
// certification level (OWD → AOWD → Rescue → Divemaster → Instructor →
// technical), and logged dive count.
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "nurkowanie",
  name: "Nurkowanie",
  icon: "🤿",
  description:
    "Od basenu po głębiny i stopnie instruktorskie. Progresja: głębokość, certyfikaty (OWD → instruktor) i liczba zalogowanych nurkowań.",
  sortOrder: 24,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Oddychaj z automatu pod wodą na basenie"],
  ["Wyrównaj ciśnienie w uszach podczas zejścia"],
  ["Wyczyść maskę z wody pod wodą"],
  ["Odzyskaj automat spod wody"],
  ["Kontroluj pływalność (zawiśnij w toni) przez 30 sekund"],
  ["Odbądź pierwsze nurkowanie w wodach otwartych"],
  ["Zejdź na 5 metrów"],
  ["Zejdź na 10 metrów"],
  ["Zaliczy 4 nurkowania w wodach otwartych"],
  ["Zdobądź certyfikat nurka podstawowego (OWD)", "Open Water Diver — przepustka do samodzielnego nurkowania do 18 m."],
  // 11-25 · Regularny
  ["Zejdź na 15 metrów"],
  ["Zaliczy 10 nurkowań"],
  ["Odbądź nurkowanie z partnerem bez instruktora (buddy system)"],
  ["Opanuj nawigację podwodną z kompasem"],
  ["Zejdź na 18 metrów", "Granica podstawowego certyfikatu."],
  ["Odbądź pierwsze nurkowanie nocne"],
  ["Zaliczy 20 nurkowań"],
  ["Zejdź na 24 metry"],
  ["Odbądź nurkowanie na wraku (z zewnątrz)"],
  ["Zdobądź certyfikat nurka zaawansowanego (AOWD)", "Advanced Open Water — do 30 m."],
  ["Zejdź na 30 metrów"],
  ["Zaliczy 30 nurkowań"],
  ["Odbądź nurkowanie w prądzie (drift dive)"],
  ["Kontroluj zużycie powietrza — wydłuż nurkowanie do 50 minut"],
  ["Odbądź nurkowanie w zimnej wodzie (poniżej 10°C) w skafandrze"],
  // 26-45 · Średniozaawansowany
  ["Nurkuj regularnie (2+ nurkowania/mies. przez sezon)"],
  ["Zaliczy 40 nurkowań"],
  ["Zdobądź specjalizację (nawigacja, wrak, głębokość lub nitrox)"],
  ["Zejdź na 35 metrów"],
  ["Odbądź nurkowanie z obowiązkowym przystankiem dekompresyjnym (planowanym)"],
  ["Zaliczy 50 nurkowań"],
  ["Zdobądź certyfikat nurka ratownika (Rescue Diver)", "Ratowanie partnera i samoratownictwo."],
  ["Zejdź na 40 metrów", "Granica nurkowania rekreacyjnego."],
  ["Wejdź do wnętrza wraku (przeszkolony)"],
  ["Zaliczy 75 nurkowań"],
  ["Odbądź nurkowanie pod lodem lub w jaskini (przeszkolony)"],
  ["Opanuj nurkowanie na nitroksie i planowanie na komputerze"],
  ["Zaliczy 100 nurkowań", "Setka w logbooku — poważny nurek."],
  ["Odbądź nurkowanie na dużym prądzie i głębokości jednocześnie"],
  ["Poprowadź nurkowanie dla mniej doświadczonego partnera"],
  ["Zdobądź certyfikat Divemastera", "Pierwszy stopień zawodowy — możesz prowadzić nurków."],
  ["Zaliczy 150 nurkowań"],
  ["Odbądź nurkowanie z rekinami lub dużymi zwierzętami pelagicznymi"],
  ["Zejdź na 42 metry"],
  ["Odbądź wyprawę nurkową za granicę (rafa tropikalna)"],
  // 46-65 · Zaawansowany
  ["Zaliczy 200 nurkowań"],
  ["Rozpocznij szkolenie techniczne (Tec 40 lub odpowiednik)"],
  ["Zejdź na 45 metrów na sprzęcie technicznym"],
  ["Opanuj nurkowanie na dwóch butlach (twinset)"],
  ["Zaliczy 250 nurkowań"],
  ["Wykonaj planowaną dekompresję z butlą stage"],
  ["Zdobądź certyfikat instruktora nurkowania", "Możesz szkolić nowych nurków."],
  ["Zejdź na 50 metrów"],
  ["Zaliczy 300 nurkowań"],
  ["Poprowadź kurs OWD jako instruktor"],
  ["Odbądź nurkowanie wrakowe z penetracją korytarzy"],
  ["Zejdź na 55 metrów"],
  ["Zaliczy 400 nurkowań"],
  ["Opanuj nurkowanie na trimiksie", "Mieszanka na duże głębokości."],
  ["Odbądź nurkowanie jaskiniowe z liną poręczową"],
  ["Zejdź na 60 metrów"],
  ["Zaliczy 500 nurkowań"],
  ["Poprowadź szkolenie specjalizacyjne jako instruktor"],
  ["Odbądź nurkowanie ekspedycyjne w odległej lokalizacji"],
  ["Zejdź na 70 metrów"],
  // 66-85 · Wyczynowy
  ["Zaliczy 750 nurkowań"],
  ["Zejdź na 80 metrów na trimiksie"],
  ["Opanuj nurkowanie w obiegu zamkniętym (rebreather)"],
  ["Wykonaj długą dekompresję (60+ min przystanków)"],
  ["Zaliczy 1000 nurkowań", "Tysiąc nurkowań — elita doświadczenia."],
  ["Zejdź na 90 metrów"],
  ["Poprowadź ekspedycję nurkową jako lider"],
  ["Odbądź nurkowanie jaskiniowe na dużym zasięgu"],
  ["Zaliczy 1250 nurkowań"],
  ["Zejdź na 100 metrów"],
  ["Zostań instruktorem techniczym (Tec Instructor)"],
  ["Wykonaj nurkowanie eksploracyjne w nieznanym miejscu"],
  ["Zaliczy 1500 nurkowań"],
  ["Zejdź na 110 metrów"],
  ["Opanuj zaawansowane procedury awaryjne na dużej głębokości"],
  ["Poprowadź badawcze nurkowanie naukowe lub dokumentacyjne"],
  ["Zaliczy 2000 nurkowań"],
  ["Zejdź na 120 metrów"],
  ["Zostań instruktorem instruktorów (Course Director/Trainer)"],
  ["Weź udział w eksploracji wraku lub jaskini o randze odkrycia"],
  // 86-99 · Elita
  ["Zaliczy 2500 nurkowań"],
  ["Zejdź na 120 metrów"],
  ["Poprowadź projekt eksploracyjny z lokalnym zespołem nurków"],
  ["Zaliczy 3000 nurkowań"],
  ["Zejdź na 130 metrów"],
  ["Ustanów swój rekord życiowy głębokości lub zasięgu jaskini"],
  ["Zaliczy 4000 nurkowań"],
  ["Zejdź na 140 metrów"],
  ["Poprowadź ekspedycję z zespołem nurków technicznych"],
  ["Zaliczy 5000 nurkowań"],
  ["Zejdź na 150 metrów"],
  ["Wnieś udokumentowany wkład w lokalną eksplorację nurkową"],
  ["Zaliczy 6000 nurkowań"],
  ["Poziom mistrzowski (amatorski szczyt): głębokość 150 m i wieloletni, dojrzały warsztat", "Dalsze, rekordowe osiągnięcia (250 m+) potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  1: prog("technika", 1), 2: prog("technika", 2), 3: prog("technika", 3),
  4: prog("technika", 4), 5: prog("technika", 5),
  7: prog("glebokosc", 5), 8: prog("glebokosc", 10), 11: prog("glebokosc", 15), 15: prog("glebokosc", 18),
  18: prog("glebokosc", 24), 21: prog("glebokosc", 30), 29: prog("glebokosc", 35), 33: prog("glebokosc", 40),
  43: prog("glebokosc", 42), 48: prog("glebokosc", 45), 53: prog("glebokosc", 50), 57: prog("glebokosc", 55),
  61: prog("glebokosc", 60), 65: prog("glebokosc", 70), 67: prog("glebokosc", 80), 71: prog("glebokosc", 90),
  75: prog("glebokosc", 100), 79: prog("glebokosc", 110), 83: prog("glebokosc", 120),
  87: prog("glebokosc", 130), 90: prog("glebokosc", 150), 93: prog("glebokosc", 170), 96: prog("glebokosc", 200),
  10: prog("certyfikat", 1), 20: prog("certyfikat", 2), 32: prog("certyfikat", 3),
  42: prog("certyfikat", 4), 52: prog("certyfikat", 5),
  9: prog("nurkowania", 4), 12: prog("nurkowania", 10), 17: prog("nurkowania", 20), 22: prog("nurkowania", 30),
  27: prog("nurkowania", 40), 31: prog("nurkowania", 50), 36: prog("nurkowania", 75), 38: prog("nurkowania", 100),
  44: prog("nurkowania", 150), 46: prog("nurkowania", 200), 50: prog("nurkowania", 250), 54: prog("nurkowania", 300),
  58: prog("nurkowania", 400), 62: prog("nurkowania", 500), 66: prog("nurkowania", 750), 70: prog("nurkowania", 1000),
  74: prog("nurkowania", 1250), 78: prog("nurkowania", 1500), 82: prog("nurkowania", 2000),
  86: prog("nurkowania", 2500), 89: prog("nurkowania", 3000), 92: prog("nurkowania", 4000), 95: prog("nurkowania", 5000),
  98: prog("nurkowania", 6000),
  26: freq(2, 12),
  // pozostałe: techniki, wyprawy, szkolenia — manualne.
};
