// Origami ladder 1-99 — REALISTIC personal-progression scale (dedicated hobbyist;
// hours capped ~1200, model counts scaled for a fast craft; top tiers reframed as
// attainable mastery, real feats left to future certificates).
// Tracks: umiejetnosci, modele (models folded), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "origami",
  name: "Origami",
  icon: "📄",
  description:
    "Sztuka składania papieru — od żurawia po złożone modele i własne projekty. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → własne projekty → dojrzały warsztat.",
  sortOrder: 91,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Zrób zagięcia dolinowe i górskie precyzyjnie", undefined, prog("umiejetnosci", 1)],
  ["Złóż podstawowe figury (łódka, czapka, pies)", undefined, prog("umiejetnosci", 2)],
  ["Złóż żurawia (tsuru)", undefined, prog("umiejetnosci", 3)],
  ["Opanuj bazę kwadratową i ptasią", undefined, prog("umiejetnosci", 4)],
  ["Złóż żabę i skaczącą żabę (baza żabia)", undefined, prog("umiejetnosci", 5)],
  ["Utrzymaj równe, ostre zagięcia", undefined, prog("umiejetnosci", 6)],
  ["Złóż 5 różnych modeli", undefined, prog("modele", 5)],
  ["Rozczytaj prosty diagram origami", undefined, prog("umiejetnosci", 7)],
  ["Złóż 15 modeli", undefined, prog("modele", 15)],
  ["Składaj origami łącznie przez 8 godzin", undefined, prog("godziny", 8)],
  // 11-25 · Regularny
  ["Składaj origami kilka razy w tygodniu przez 4 tygodnie", undefined, freq(2, 4)],
  ["Opanuj odwrócone zagięcia (inside/outside reverse)", undefined, prog("umiejetnosci", 8)],
  ["Złóż zwierzę o kilkunastu krokach", undefined, prog("umiejetnosci", 9)],
  ["Złóż model z bazy bomby wodnej / preliminary", undefined, prog("umiejetnosci", 10)],
  ["Złóż 30 modeli", undefined, prog("modele", 30)],
  ["Składaj origami łącznie przez 20 godzin", undefined, prog("godziny", 20)],
  ["Zrób pierwszy moduł origami modułowego (np. sonobe)", undefined, prog("umiejetnosci", 11)],
  ["Złóż kusudamę z modułów", undefined, prog("umiejetnosci", 12)],
  ["Złóż 50 modeli", undefined, prog("modele", 50)],
  ["Opanuj bazę żabią i płatkowe zagięcia (petal fold)", undefined, prog("umiejetnosci", 13)],
  ["Złóż model średnio złożony (kilkadziesiąt kroków)", undefined, prog("umiejetnosci", 14)],
  ["Składaj origami łącznie przez 40 godzin", undefined, prog("godziny", 40)],
  ["Złóż 80 modeli", undefined, prog("modele", 80)],
  ["Dobierz i przygotuj papier do modelu (rozmiar, rodzaj)", undefined, prog("umiejetnosci", 15)],
  ["Złóż 120 modeli", undefined, prog("modele", 120)],
  // 26-45 · Średniozaawansowany
  ["Składaj origami regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Złóż złożony model (setki kroków, np. owad)", undefined, prog("umiejetnosci", 16)],
  ["Opanuj składanie z siatki (crease pattern — podstawy)", undefined, prog("umiejetnosci", 17)],
  ["Złóż 180 modeli", undefined, prog("modele", 180)],
  ["Zrób wet-folding (składanie na wilgotno)", undefined, prog("umiejetnosci", 18)],
  ["Składaj origami łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Złóż model figuratywny z detalami (smok, ptak)", undefined, prog("umiejetnosci", 19)],
  ["Opanuj proste tesselacje", undefined, prog("umiejetnosci", 20)],
  ["Złóż 250 modeli", undefined, prog("modele", 250)],
  ["Złóż dużą kusudamę / model modułowy z wielu części", undefined, prog("umiejetnosci", 21)],
  ["Złóż bardzo złożony model (500+ kroków)", undefined, prog("umiejetnosci", 22)],
  ["Składaj origami łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Złóż 330 modeli", undefined, prog("modele", 330)],
  ["Opanuj box-pleating (składanie pudełkowe)", undefined, prog("umiejetnosci", 23)],
  ["Zaprojektuj drobną modyfikację modelu", undefined, prog("umiejetnosci", 24)],
  ["Złóż 420 modeli", undefined, prog("modele", 420)],
  ["Opanuj złożone tesselacje i wzory geometryczne", undefined, prog("umiejetnosci", 25)],
  ["Składaj origami łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Złóż model na najwyższym własnym poziomie precyzji", undefined, prog("umiejetnosci", 26)],
  ["Składaj origami regularnie przez 3 miesiące", undefined, prog("modele", 520)],
  // 46-65 · Zaawansowany (amator)
  ["Składaj origami regularnie przez 12 tygodni", undefined, freq(2, 12)],
  ["Zaprojektuj własny prosty model od zera (crease pattern)", undefined, prog("umiejetnosci", 27)],
  ["Złóż spójną serię modeli (kolekcja)", undefined, prog("umiejetnosci", 28)],
  ["Złóż 620 modeli", undefined, prog("modele", 620)],
  ["Składaj origami łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Pokaż prace publicznie i zbierz opinie odbiorców"],
  ["Zaprojektuj model figuratywny z własną siatką", undefined, prog("umiejetnosci", 29)],
  ["Złóż 750 modeli", undefined, prog("modele", 750)],
  ["Opanuj wybraną specjalizację (owady / tesselacje / modułowe)", undefined, prog("umiejetnosci", 30)],
  ["Składaj origami łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj portfolio najlepszych modeli"],
  ["Weź udział w wystawie / konwencie origami"],
  ["Zaprojektuj skomplikowany model z detalami", undefined, prog("umiejetnosci", 31)],
  ["Złóż 900 modeli", undefined, prog("modele", 900)],
  ["Złóż model na zamówienie / sprzedaj pracę", undefined, prog("umiejetnosci", 32)],
  ["Składaj origami łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy origami", undefined, prog("umiejetnosci", 33)],
  ["Zrealizuj spójny cykl / instalację z papieru"],
  ["Złóż arcytrudny model na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Złóż 1100 modeli", undefined, prog("modele", 1100)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Składaj origami regularnie przez pełny sezon (6 miesięcy)"],
  ["Projektuj własne modele swobodnie (od siatki po finał)", undefined, prog("umiejetnosci", 35)],
  ["Złóż 1300 modeli", undefined, prog("modele", 1300)],
  ["Składaj origami łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Opublikuj własny diagram / crease pattern"],
  ["Rozwiń warsztat na tyle, by uczyć origami", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie publikujesz modele lub sprzedajesz prace"],
  ["Opanuj każdą technikę składania na wysokim poziomie", undefined, prog("umiejetnosci", 37)],
  ["Złóż 1500 modeli", undefined, prog("modele", 1500)],
  ["Zdobądź wyróżnienie lub uznanie w społeczności origami"],
  ["Składaj origami łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zaprojektuj ambitny, autorski model / serię", undefined, prog("umiejetnosci", 38)],
  ["Twoje modele są dojrzałe i rozpoznawalne", undefined, prog("umiejetnosci", 39)],
  ["Złóż 1750 modeli", undefined, prog("modele", 1750)],
  ["Zbuduj grono odbiorców swojej twórczości"],
  ["Poprowadź warsztaty lub mentoring dla składających"],
  ["Zaprojektuj kolekcję autorskich modeli"],
  ["Zrealizuj wystawę prezentującą Twój dorobek"],
  ["Złóż 2000 modeli", undefined, prog("modele", 2000)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Składaj origami łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdym modelu"],
  ["Złóż 2300 modeli", undefined, prog("modele", 2300)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych składających w Twoim otoczeniu"],
  ["Zaprojektuj i złóż osobisty „opus” — arcytrudny model", undefined, prog("umiejetnosci", 40)],
  ["Regularnie publikujesz modele lub wystawiasz prace"],
  ["Składaj origami łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje modele zdobywają uznanie poza lokalną społecznością"],
  ["Złóż 2600 modeli", undefined, prog("modele", 2600)],
  ["Uczysz i kształtujesz kolejnych składających"],
  ["Masz dorobek, z którego można ułożyć wystawę retrospektywną"],
  ["Złożysz z papieru niemal wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski warsztat", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (origami: Art of Fold, Jo Nakashima, EzOrigami i in.).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Zagięcia dolinowe i górskie", url: yt("gLNHKyjXngk") }],
  3: [{ kind: "video", title: "Żuraw (tsuru) krok po kroku", url: yt("MydJjz8CUGc") }],
  4: [{ kind: "video", title: "Baza ptasia i kwadratowa", url: yt("htPzc58jPtY") }],
  5: [{ kind: "video", title: "Skacząca żaba (baza żabia)", url: yt("Vlb2udqPx-M") }],
  12: [{ kind: "video", title: "Odwrócone zagięcia (reverse folds)", url: yt("O-7w2Byevzc") }],
  17: [{ kind: "video", title: "Moduł Sonobe (origami modułowe)", url: yt("in9wVuB33Dk") }],
  18: [{ kind: "video", title: "Kusudama z modułów", url: yt("FfgDPoGcoTo") }],
  20: [{ kind: "video", title: "Zagięcie płatkowe (petal fold)", url: yt("JrqvQBGsAl4") }],
  27: [{ kind: "video", title: "Złożony model — owad (Jo Nakashima)", url: yt("SmL_-Ik5fDI") }],
  28: [{ kind: "video", title: "Czytanie siatki (crease pattern)", url: yt("lz-hoLC73yc") }],
  30: [{ kind: "video", title: "Składanie na wilgotno (wet-folding)", url: yt("9BF2vWmqr2I") }],
};
