// Paragliding ladder 1-99. Manual — progression tracks: skill/licence, XC
// distance flown (km), and competition level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "paralotniarstwo",
  name: "Paralotniarstwo",
  icon: "🪂",
  description:
    "Swobodny lot pod skrzydłem — od pierwszego startu po przeloty XC i zawody. Progresja: umiejętności/licencja, dystans przelotu i poziom rywalizacji.",
  sortOrder: 72,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Rozłóż skrzydło i wykonaj napełnienie na ziemi (ground handling)", undefined, prog("technika", 1)],
  ["Wykonaj kontrolowany rozbieg z napełnionym skrzydłem", undefined, prog("technika", 2)],
  ["Wykonaj pierwszy lot ze zboczem (mały przewyższenie)", undefined, prog("loty", 1)],
  ["Ląduj kontrolowanie w wyznaczonym miejscu", undefined, prog("technika", 3)],
  ["Opanuj skręty i kontrolę prędkości w locie", undefined, prog("technika", 4)],
  ["Wykonaj lot z przewyższeniem 100 m+", undefined, prog("loty", 2)],
  ["Opanuj procedury startowe i czytanie warunków wiatru", undefined, prog("technika", 5)],
  ["Zdobądź świadectwo kwalifikacji pilota paralotni (licencja PL)", "Podstawowe uprawnienia.", prog("licencja", 1)],
  ["Wykonaj lot trwający 15+ minut", undefined, prog("loty", 3)],
  ["Wykonaj 10 lotów łącznie", undefined, prog("loty", 4)],
  // 11-25 · Regularny
  ["Lataj regularnie w sezonie (kilka wylotów w miesiącu)", undefined, freq(1, 4)],
  ["Wykorzystaj pierwszy komin termiczny (utrzymaj wysokość)", "Termika — klucz do latania.", prog("technika", 6)],
  ["Wykonaj lot trwający 30+ minut", undefined, prog("loty", 5)],
  ["Wykręć komin i zyskaj 300 m przewyższenia", undefined, prog("technika", 7)],
  ["Wykonaj 30 lotów łącznie", undefined, prog("loty", 6)],
  ["Wykonaj pierwszy mały przelot XC (5 km)", undefined, prog("xc", 5)],
  ["Opanuj lądowanie poza lądowiskiem (out-landing) bezpiecznie", undefined, prog("technika", 8)],
  ["Wykonaj przelot 10 km", undefined, prog("xc", 10)],
  ["Wykonaj lot trwający 1 godzinę", undefined, prog("loty", 7)],
  ["Zdobądź licencję rozszerzoną / uprawnienia do lotów termicznych", undefined, prog("licencja", 2)],
  ["Wykonaj przelot 20 km", undefined, prog("xc", 20)],
  ["Wykonaj 60 lotów łącznie", undefined, prog("loty", 8)],
  ["Opanuj centrowanie komina i optymalizację wznoszenia", undefined, prog("technika", 9)],
  ["Wykonaj przelot 30 km", undefined, prog("xc", 30)],
  ["Weź udział w pierwszych zawodach lub XC lidze", undefined, prog("liga", 1)],
  // 26-45 · Średniozaawansowany
  ["Lataj intensywnie przez cały sezon"],
  ["Wykonaj przelot 40 km", undefined, prog("xc", 40)],
  ["Opanuj przechodzenie między kominami (glide optimization)", undefined, prog("technika", 10)],
  ["Wykonaj przelot 50 km", undefined, prog("xc", 50)],
  ["Wykonaj 100 lotów łącznie", undefined, prog("loty", 9)],
  ["Wykonaj przelot powrotny (out-and-return) 30 km+", undefined, prog("technika", 11)],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  ["Wykonaj przelot 60 km", undefined, prog("xc", 60)],
  ["Opanuj lot na skrzydle klasy B/C (wyższa wydajność)", undefined, prog("technika", 12)],
  ["Wykonaj przelot 75 km", undefined, prog("xc", 75)],
  ["Wykonaj 150 lotów łącznie", undefined, prog("loty", 10)],
  ["Wykonaj trójkąt FAI 25 km+", undefined, prog("technika", 13)],
  ["Wykonaj przelot 90 km", undefined, prog("xc", 90)],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Wykonaj przelot 100 km", "Setka w powietrzu.", prog("xc", 100)],
  ["Opanuj lot w silnej termice i turbulencji z kontrolą", undefined, prog("technika", 14)],
  ["Wykonaj 200 lotów łącznie", undefined, prog("loty", 11)],
  ["Wykonaj trójkąt FAI 50 km+", undefined, prog("technika", 15)],
  ["Wykonaj przelot 120 km", undefined, prog("xc", 120)],
  ["Zdobądź uprawnienia do lotów w górach wysokich / wysoka klasa skrzydła", undefined, prog("licencja", 3)],
  // 46-65 · Zaawansowany
  ["Lataj na poziomie zawodniczym przez sezon"],
  ["Wykonaj przelot 140 km", undefined, prog("xc", 140)],
  ["Zajmij miejsce w czołówce ligi XC regionu"],
  ["Opanuj lot na skrzydle klasy D/CCC (zawodnicze)", undefined, prog("technika", 16)],
  ["Wykonaj przelot 160 km", undefined, prog("xc", 160)],
  ["Wykonaj trójkąt FAI 100 km+", undefined, prog("technika", 17)],
  ["Wykonaj 300 lotów łącznie", undefined, prog("loty", 12)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju"],
  ["Wykonaj przelot 180 km", undefined, prog("xc", 180)],
  ["Opanuj strategię przelotu na maksymalny dystans (task strategy)", undefined, prog("technika", 18)],
  ["Wykonaj przelot 200 km", "Dwieście kilometrów przelotu.", prog("xc", 200)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Wykonaj trójkąt FAI 150 km+", undefined, prog("technika", 19)],
  ["Wykonaj 400 lotów łącznie", undefined, prog("loty", 13)],
  ["Zostań mistrzem kraju w klasyfikacji XC lub zawodach"],
  ["Wykonaj przelot 230 km", undefined, prog("xc", 230)],
  ["Wystartuj w zawodach międzynarodowych (FAI Cat 2)", undefined, prog("liga", 2)],
  ["Zajmij miejsce w pierwszej połowie zawodów międzynarodowych"],
  ["Wykonaj przelot 260 km", undefined, prog("xc", 260)],
  ["Uzyskaj wynik kwalifikujący do rankingu WPRS", undefined, prog("liga", 3)],
  // 66-85 · Wyczynowy
  ["Zdobądź punkty w rankingu światowym WPRS"],
  ["Wykonaj przelot 290 km", undefined, prog("xc", 290)],
  ["Zajmij miejsce w pierwszej dziesiątce zawodów o zasięgu regionalnym"],
  ["Wykonaj trójkąt FAI 200 km+", undefined, prog("technika", 20)],
  ["Wykonaj przelot 320 km", undefined, prog("xc", 320)],
  ["Wykonaj 600 lotów łącznie", undefined, prog("loty", 14)],
  ["Weź udział w mistrzostwach regionu / zawodach o zasięgu ogólnokrajowym"],
  ["Wykonaj przelot 350 km", undefined, prog("xc", 350)],
  ["Zajmij miejsce w pierwszej połowie mistrzostw regionu"],
  ["Opanuj lot w ekstremalnych warunkach wysokogórskich", undefined, prog("technika", 21)],
  ["Wykonaj przelot 380 km", undefined, prog("xc", 380)],
  ["Osiągnij czołową 50 rankingu krajowego"],
  ["Zdobądź podium mistrzostw regionu"],
  ["Wykonaj przelot 400 km", "Bardzo długi, wieloletnio wypracowany dystans.", prog("xc", 400)],
  ["Wykonaj trójkąt FAI 250 km+", undefined, prog("technika", 22)],
  ["Wykonaj 800 lotów łącznie", undefined, prog("loty", 15)],
  ["Zajmij miejsce w pierwszej dziesiątce zawodów o zasięgu ogólnokrajowym"],
  ["Wykonaj przelot 450 km", undefined, prog("xc", 450)],
  ["Osiągnij czołową 20 rankingu krajowego"],
  ["Wygraj etap zawodów o zasięgu ogólnokrajowym"],
  // 86-99 · Elita
  ["Zdobądź medal mistrzostw kraju amatorów"],
  ["Osiągnij czołową dziesiątkę rankingu krajowego"],
  ["Wykonaj przelot 500 km", "Bardzo rzadki, elitarny dystans.", prog("xc", 500)],
  ["Zakwalifikuj się do finału zawodów o zasięgu ogólnokrajowym"],
  ["Zajmij miejsce w pierwszej piątce mistrzostw kraju amatorów"],
  ["Osiągnij czołową piątkę rankingu krajowego"],
  ["Wygraj zawody o zasięgu ogólnokrajowym"],
  ["Zdobądź złoto mistrzostw regionu"],
  ["Wykonaj przelot ponad 550 km", undefined, prog("xc", 550)],
  ["Zostań numerem 1 rankingu krajowego"],
  ["Poprowadź kogoś przez zaawansowaną technikę przelotów"],
  ["Zdobądź złoto mistrzostw kraju amatorów"],
  ["Ustanów swój rekord życiowy w przelocie", undefined, prog("technika", 23)],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat przelotowy", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, rekordy) potwierdzają osobne certyfikaty."],
]);
