// Pickleball ladder 1-99. Manual — progression tracks: technique, matches
// played, and DUPR-style player rating (2.0-8.0, value ×10) + competition.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "pickleball",
  name: "Pickleball",
  icon: "🥒",
  description:
    "Najszybciej rosnący sport rakietkowy w USA — mieszanka tenisa, badmintona i ping-ponga. Progresja: technika, mecze i rating gracza (DUPR).",
  sortOrder: 56,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Wykonaj poprawny serwis od dołu do właściwego pola", undefined, prog("technika", 1)],
  ["Odbij piłkę forehandem po odbiciu", undefined, prog("technika", 2)],
  ["Odbij piłkę backhandem", undefined, prog("technika", 3)],
  ["Utrzymaj wymianę 4 odbić z partnerem", undefined, prog("technika", 4)],
  ["Zrozum zasadę podwójnego odbicia i strefy kitchen (non-volley zone)", undefined, prog("technika", 5)],
  ["Zagraj dinka (miękka piłka w kuchnię)", undefined, prog("technika", 6)],
  ["Zagraj wolej przy siatce (poza kuchnią)", undefined, prog("technika", 7)],
  ["Rozegraj pierwszego gema do 11 punktów", undefined, prog("mecze", 1)],
  ["Wygraj wymianę atakiem przy siatce"],
  ["Rozegraj pełny mecz (do 2 wygranych setów)", undefined, prog("mecze", 2)],
  // 11-25 · Regularny
  ["Graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Zagraj third shot drop (opad po serwisie do kuchni)", undefined, prog("technika", 8)],
  ["Zagraj 5 meczów", undefined, prog("mecze", 5)],
  ["Osiągnij rating 2.5 (DUPR/skala klubowa)", undefined, prog("rating", 25)],
  ["Utrzymaj wymianę dinków 6+ odbić", undefined, prog("technika", 9)],
  ["Wygraj pierwszy mecz z realnymi przeciwnikami"],
  ["Zagraj 10 meczów", undefined, prog("mecze", 10)],
  ["Osiągnij rating 3.0", undefined, prog("rating", 30)],
  ["Zagraj skuteczny lob ponad przeciwnikami przy siatce", undefined, prog("technika", 10)],
  ["Rozegraj mecz w lidze amatorskiej lub drabince", undefined, prog("liga", 1)],
  ["Zagraj 20 meczów", undefined, prog("mecze", 20)],
  ["Osiągnij rating 3.5", undefined, prog("rating", 35)],
  ["Zagraj skuteczny ATP (around the post) lub trudny return", undefined, prog("technika", 11)],
  ["Wygraj 5 meczów łącznie"],
  ["Zagraj 30 meczów", undefined, prog("mecze", 30)],
  // 26-45 · Średniozaawansowany
  ["Graj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Osiągnij rating 3.75", undefined, prog("rating", 37)],
  ["Opanuj grę w kuchni (dink battles) z cierpliwością", undefined, prog("technika", 12)],
  ["Zagraj 50 meczów", undefined, prog("mecze", 50)],
  ["Osiągnij rating 4.0", "Solidny gracz klubowy.", prog("rating", 40)],
  ["Rozegraj pełny sezon w lidze", undefined, prog("liga", 2)],
  ["Zagraj skuteczny reset (zbicie ataku do kuchni)", undefined, prog("technika", 13)],
  ["Zajmij miejsce w pierwszej połowie turnieju amatorskiego"],
  ["Zagraj 75 meczów", undefined, prog("mecze", 75)],
  ["Osiągnij rating 4.25", undefined, prog("rating", 42)],
  ["Opanuj stacking i komunikację w deblu", undefined, prog("technika", 14)],
  ["Zagraj 100 meczów", undefined, prog("mecze", 100)],
  ["Weź udział w turnieju rangi regionalnej", undefined, prog("liga", 3)],
  ["Wygraj mecz turniejowy"],
  ["Osiągnij rating 4.5", "Zaawansowany zawodnik.", prog("rating", 45)],
  ["Zagraj 150 meczów", undefined, prog("mecze", 150)],
  ["Zajmij miejsce na podium turnieju amatorskiego"],
  ["Opanuj speed-up i grę w wysokim tempie przy siatce", undefined, prog("technika", 15)],
  ["Osiągnij rating 4.75", undefined, prog("rating", 47)],
  ["Zagraj 200 meczów", undefined, prog("mecze", 200)],
  // 46-65 · Zaawansowany
  ["Graj lub trenuj 4+ razy w tygodniu przez sezon"],
  ["Osiągnij rating 5.0", "Poziom półprofesjonalny.", prog("rating", 50)],
  ["Zajmij miejsce w czołówce turnieju regionalnego"],
  ["Opanuj pełny repertuar zagrań (drop, drive, roll, reset)", undefined, prog("technika", 16)],
  ["Zagraj 250 meczów", undefined, prog("mecze", 250)],
  ["Wygraj turniej regionalny"],
  ["Osiągnij rating 5.25", undefined, prog("rating", 52)],
  ["Wejdź do rankingu krajowego", undefined, prog("liga", 4)],
  ["Zagraj 300 meczów", undefined, prog("mecze", 300)],
  ["Wygraj mecz z parą z rankingu krajowego"],
  ["Osiągnij rating 5.5", undefined, prog("rating", 55)],
  ["Utrzymaj poziom gry w meczu trzysetowym pod presją", undefined, prog("technika", 17)],
  ["Zagraj 400 meczów", undefined, prog("mecze", 400)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju (kategoria)"],
  ["Osiągnij rating 5.75", undefined, prog("rating", 57)],
  ["Zagraj 450 meczów", undefined, prog("mecze", 450)],
  ["Wygraj mecz z parą z Top 50 kraju"],
  ["Zdobądź medal mistrzostw kraju w swojej kategorii"],
  ["Osiągnij rating 6.0", undefined, prog("rating", 60)],
  ["Wygraj turniej rangi ogólnokrajowej"],
  // 66-85 · Wyczynowy
  ["Zagraj 500 meczów", undefined, prog("mecze", 500)],
  ["Wystąp w turnieju międzynarodowym"],
  ["Osiągnij rating 6.2", undefined, prog("rating", 62)],
  ["Wygraj mecz z parą z rankingu międzynarodowego"],
  ["Zagraj 600 meczów", undefined, prog("mecze", 600)],
  ["Wejdź do Top 10 rankingu krajowego", undefined, prog("liga", 5)],
  ["Zdobądź punkty w rankingu międzynarodowym (DUPR/PPA)"],
  ["Osiągnij rating 6.4", undefined, prog("rating", 64)],
  ["Zajmij miejsce w pierwszej ósemce turnieju międzynarodowego"],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Osiągnij rating 6.6", undefined, prog("rating", 66)],
  ["Zagraj 700 meczów", undefined, prog("mecze", 700)],
  ["Wygraj turniej regionalny niższej rangi"],
  ["Osiągnij rating 6.8", undefined, prog("rating", 68)],
  ["Zagraj 800 meczów", undefined, prog("mecze", 800)],
  ["Wygraj mecz z mocną parą regionalną"],
  ["Zdobądź podium mistrzostw regionu seniorów"],
  ["Osiągnij rating 7.0", "Bardzo wysoki, wieloletnio trenowany poziom.", prog("rating", 70)],
  ["Weź udział w turnieju o zasięgu ogólnokrajowym"],
  ["Zagraj 900 meczów", undefined, prog("mecze", 900)],
  // 86-99 · Elita
  ["Osiągnij czołową 20 rankingu krajowego"],
  ["Osiągnij rating 7.2", undefined, prog("rating", 72)],
  ["Wygraj mecz z mocną parą z czołówki kraju"],
  ["Awansuj do ćwierćfinału turnieju o zasięgu ogólnokrajowym"],
  ["Osiągnij rating 7.4", undefined, prog("rating", 74)],
  ["Osiągnij czołową dziesiątkę rankingu krajowego"],
  ["Zdobądź tytuł turnieju o zasięgu ogólnokrajowym niższej rangi"],
  ["Osiągnij rating 7.6", undefined, prog("rating", 76)],
  ["Osiągnij czołową piątkę rankingu krajowego"],
  ["Zajmij miejsce w finale mistrzostw kraju amatorów"],
  ["Osiągnij rating 7.8", undefined, prog("rating", 78)],
  ["Wejdź do czołówki rankingu krajowego"],
  ["Zdobądź tytuł mistrzostw kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): rating 8.0 i wieloletni, dojrzały warsztat", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty.", prog("rating", 80)],
]);
