// Pilates ladder 1-99. Manual — progression tracks: control/technique, core
// endurance (holds), flexibility, and repertoire level (mat → reformer →
// advanced/instructor). Mostly skill-based, few auto criteria.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "pilates",
  name: "Pilates",
  icon: "🧎",
  description:
    "Kontrola, oddech i siła głębokich mięśni — od podstaw maty po zaawansowany repertuar i reformer. Progresja: technika, wytrzymałość core i zakres ruchu.",
  sortOrder: 39,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj oddech pilatesowy (żebrowo-boczny)", undefined, prog("technika", 1)],
  ["Znajdź i aktywuj centrum (powerhouse / mięśnie głębokie)", undefined, prog("technika", 2)],
  ["Wykonaj poprawny pelvic curl (mostek kręg po kręgu)", undefined, prog("technika", 3)],
  ["Utrzymaj neutralne ustawienie miednicy w leżeniu", undefined, prog("core", 1)],
  ["Wykonaj serię The Hundred w wersji podstawowej", undefined, prog("technika", 4)],
  ["Utrzymaj deskę (plank) przez 20 sekund", undefined, prog("core", 2)],
  ["Wykonaj Roll Up z kontrolą (choćby z ugięciem)", undefined, prog("technika", 5)],
  ["Dotknij palców stóp w siadzie prostym (elastyczność)", undefined, prog("gibkosc", 1)],
  ["Wykonaj Single Leg Stretch z prawidłową techniką", undefined, prog("technika", 6)],
  ["Zaliczy 5 sesji pilates", undefined, prog("sesje", 5)],
  // 11-25 · Regularny
  ["Ćwicz 2 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(2, 4)],
  ["Wykonaj pełny Roll Up bez pomocy rąk", undefined, prog("technika", 7)],
  ["Utrzymaj deskę przez 45 sekund", undefined, prog("core", 4)],
  ["Wykonaj Double Leg Stretch z koordynacją oddechu", undefined, prog("technika", 8)],
  ["Zaliczy 15 sesji pilates", undefined, prog("sesje", 15)],
  ["Wykonaj Roll Over z kontrolą kręgosłupa", undefined, prog("technika", 9)],
  ["Połóż dłonie płasko na podłodze w skłonie w staniu", undefined, prog("gibkosc", 2)],
  ["Utrzymaj Side Plank przez 20 sekund na każdą stronę", undefined, prog("core", 6)],
  ["Wykonaj Single Straight Leg Stretch (Scissors)", undefined, prog("technika", 10)],
  ["Zaliczy 25 sesji pilates", undefined, prog("sesje", 25)],
  ["Wykonaj Spine Stretch Forward z pełnym wydłużeniem", undefined, prog("technika", 11)],
  ["Utrzymaj deskę przez 60 sekund", undefined, prog("core", 8)],
  ["Wykonaj Open Leg Rocker z równowagą", undefined, prog("technika", 12)],
  ["Weź udział w zajęciach na reformerze", undefined, prog("repertuar", 1)],
  ["Zaliczy 40 sesji pilates", undefined, prog("sesje", 40)],
  // 26-45 · Średniozaawansowany
  ["Ćwicz 3 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Wykonaj The Saw z rotacją i wydłużeniem", undefined, prog("technika", 13)],
  ["Utrzymaj Side Plank przez 45 sekund na każdą stronę", undefined, prog("core", 10)],
  ["Wykonaj Teaser I (do jednej nogi) z kontrolą", "Kultowe ćwiczenie pilates.", prog("technika", 14)],
  ["Zaliczy 60 sesji pilates", undefined, prog("sesje", 60)],
  ["Wykonaj Swan Dive w wersji podstawowej", undefined, prog("technika", 15)],
  ["Wykonaj pełny szpagat podłużny na jedną stronę", undefined, prog("gibkosc", 3)],
  ["Wykonaj Neck Pull z kontrolą kręgosłupa", undefined, prog("technika", 16)],
  ["Zaliczy 80 sesji pilates", undefined, prog("sesje", 80)],
  ["Wykonaj Teaser II (obie nogi) z równowagą", undefined, prog("technika", 17)],
  ["Utrzymaj deskę przez 90 sekund", undefined, prog("core", 12)],
  ["Wykonaj Jackknife z kontrolą", undefined, prog("technika", 18)],
  ["Opanuj serię średniozaawansowaną na reformerze", undefined, prog("repertuar", 2)],
  ["Zaliczy 100 sesji pilates", undefined, prog("sesje", 100)],
  ["Wykonaj Teaser III (pełny) z płynną kontrolą", undefined, prog("technika", 19)],
  ["Wykonaj Bridge z uniesieniem jednej nogi (stabilność)", undefined, prog("core", 14)],
  ["Wykonaj Corkscrew z kontrolą rotacji", undefined, prog("technika", 20)],
  ["Wykonaj mostek gimnastyczny (bridge) z rąk i stóp", undefined, prog("gibkosc", 4)],
  ["Zaliczy 130 sesji pilates", undefined, prog("sesje", 130)],
  ["Wykonaj Boomerang z płynnym przejściem", undefined, prog("technika", 21)],
  // 46-65 · Zaawansowany
  ["Ćwicz 4+ razy w tygodniu przez cały sezon"],
  ["Wykonaj Control Balance z kontrolą", undefined, prog("technika", 22)],
  ["Utrzymaj Side Plank przez 90 sekund na każdą stronę", undefined, prog("core", 16)],
  ["Wykonaj Snake / Twist na macie", undefined, prog("technika", 23)],
  ["Zaliczy 160 sesji pilates", undefined, prog("sesje", 160)],
  ["Wykonaj Rocking z pełnym wygięciem", undefined, prog("technika", 24)],
  ["Wykonaj szpagat podłużny na obie strony", undefined, prog("gibkosc", 5)],
  ["Wykonaj High Scissors / Bicycle w powietrzu", undefined, prog("technika", 25)],
  ["Zaliczy 200 sesji pilates", undefined, prog("sesje", 200)],
  ["Wykonaj Hip Circles z pełną kontrolą", undefined, prog("technika", 26)],
  ["Utrzymaj kontrolowany Teaser przez 30 sekund", undefined, prog("core", 18)],
  ["Wykonaj Swimming z długim wydłużeniem i tempem", undefined, prog("technika", 27)],
  ["Opanuj pełny repertuar zaawansowany na reformerze", undefined, prog("repertuar", 3)],
  ["Zaliczy 250 sesji pilates", undefined, prog("sesje", 250)],
  ["Wykonaj Leg Pull Front z idealną linią ciała", undefined, prog("technika", 28)],
  ["Wykonaj szpagat poprzeczny (pełny)", undefined, prog("gibkosc", 6)],
  ["Wykonaj Star (Side Plank z uniesieniem nogi i ręki)", undefined, prog("core", 20)],
  ["Wykonaj Crab z płynnym przejściem", undefined, prog("technika", 29)],
  ["Zaliczy 300 sesji pilates", undefined, prog("sesje", 300)],
  ["Wykonaj pełną sekwencję maty klasycznej (34 ćwiczenia) bez przerwy", undefined, prog("technika", 30)],
  // 66-85 · Wyczynowy
  ["Ćwicz konsekwentnie — 350 sesji łącznie", undefined, prog("sesje", 350)],
  ["Wykonaj Control Balance z pełnym wyprostem i równowagą", undefined, prog("technika", 31)],
  ["Wykonaj most z chwytem za kostki (pełne wygięcie)", undefined, prog("gibkosc", 7)],
  ["Utrzymaj wolnostojący Teaser przez 60 sekund", undefined, prog("core", 22)],
  ["Zaliczy 400 sesji pilates", undefined, prog("sesje", 400)],
  ["Opanuj repertuar Cadillac / Wunda Chair", undefined, prog("repertuar", 4)],
  ["Wykonaj pełną sekwencję zaawansowaną maty płynnie w tempie", undefined, prog("technika", 32)],
  ["Wykonaj szpagat w podwieszeniu (oversplit)", undefined, prog("gibkosc", 8)],
  ["Zaliczy 500 sesji pilates", undefined, prog("sesje", 500)],
  ["Poprowadź pełną sesję dla innej osoby (znajomość repertuaru)", undefined, prog("technika", 33)],
  ["Utrzymaj zaawansowane pozycje kontrolne (np. Boomerang) w spowolnieniu", undefined, prog("core", 24)],
  ["Zaliczy 600 sesji pilates", undefined, prog("sesje", 600)],
  ["Rozpocznij kurs instruktorski pilates (mata)", undefined, prog("repertuar", 5)],
  ["Wykonaj pełny repertuar na wszystkich przyrządach (reformer, cadillac, chair)", undefined, prog("technika", 34)],
  ["Zaliczy 750 sesji pilates", undefined, prog("sesje", 750)],
  ["Zdobądź certyfikat instruktora pilates (mata)", undefined, prog("repertuar", 6)],
  ["Wykonaj zaawansowane elementy siłowo-gibkościowe łączone (np. Teaser → most)"],
  ["Zaliczy 900 sesji pilates", undefined, prog("sesje", 900)],
  ["Poprowadź regularne zajęcia grupowe jako instruktor"],
  ["Zdobądź certyfikat instruktora na przyrządy (reformer)", undefined, prog("repertuar", 7)],
  // 86-99 · Elita
  ["Zaliczy 1000 sesji pilates", undefined, prog("sesje", 1000)],
  ["Opanuj pełen klasyczny system Josepha Pilatesa (wszystkie poziomy)", undefined, prog("technika", 35)],
  ["Utrzymaj perfekcyjną kontrolę w najtrudniejszych elementach maty", undefined, prog("core", 26)],
  ["Zaliczy 1200 sesji pilates", undefined, prog("sesje", 1200)],
  ["Zdobądź certyfikat comprehensive (wszystkie przyrządy)", undefined, prog("repertuar", 8)],
  ["Prowadź szkolenia lub warsztaty dla instruktorów"],
  ["Zaliczy 1500 sesji pilates", undefined, prog("sesje", 1500)],
  ["Osiągnij mistrzowską gibkość (pełne oversplity we wszystkich kierunkach)", undefined, prog("gibkosc", 9)],
  ["Opracuj i prowadź autorski program treningowy"],
  ["Zaliczy 2000 sesji pilates", undefined, prog("sesje", 2000)],
  ["Zostań trenerem / mentorem instruktorów (master trainer)", undefined, prog("repertuar", 9)],
  ["Wykonaj cały klasyczny repertuar bezbłędnie w jednej sesji pokazowej"],
  ["Wnieś wkład w rozwój metody (publikacja, szkoła, autorska metodyka)"],
  ["Poziom mistrzowski: master trainer z pełnym opanowaniem systemu", "Dziesięciolecia praktyki i nauczania — szczyt metody Pilates."],
]);
