// Handball ladder 1-99. Manual — progression tracks: matches played, goals
// scored (total), league level. Pattern follows koszykowka.
import type { MilestoneResource } from "../../src/lib/milestone-resources";
import { ladderC, freq, prog } from "./helpers";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "pilka-reczna",
  name: "Piłka ręczna",
  icon: "🤾",
  description:
    "Od pierwszego rzutu po ligowe parkiety. Progresja: rozegrane mecze, zdobyte bramki i poziom rozgrywkowy.",
  sortOrder: 32,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Złap i podaj piłkę w biegu", undefined, prog("technika", 1)],
  ["Kozłuj piłkę w truchcie bez utraty kontroli", undefined, prog("technika", 2)],
  ["Wykonaj poprawny rzut do bramki", undefined, prog("technika", 3)],
  ["Traf do pustej bramki z 6 metrów", undefined, prog("technika", 4)],
  ["Wykonaj rzut w wyskoku", undefined, prog("technika", 5)],
  ["Obroń pozycję w obronie 6-0", undefined, prog("technika", 6)],
  ["Wykonaj poprawny rzut z przeskoku (rzut karny 7 m)", undefined, prog("technika", 7)],
  ["Zagraj pierwszy mecz treningowy", undefined, prog("mecze", 1)],
  ["Zdobądź pierwszą bramkę w grze", undefined, prog("bramki", 1)],
  ["Rozegraj pełny mecz (2×30 min lub skrócony)", undefined, prog("mecze", 2)],
  // 11-25 · Regularny
  ["Trenuj lub graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Wykonaj skuteczny zwód (fintę) i minij obrońcę", undefined, prog("technika", 8)],
  ["Zagraj 5 meczów", undefined, prog("mecze", 5)],
  ["Zdobądź 10 bramek łącznie", undefined, prog("bramki", 10)],
  ["Wykonaj rzut z przewrotem (kiwnięcie bramkarza)", undefined, prog("technika", 9)],
  ["Zagraj na pozycji rozgrywającego (playmaker) przez cały mecz"],
  ["Zagraj 10 meczów", undefined, prog("mecze", 10)],
  ["Zdobądź 25 bramek łącznie", undefined, prog("bramki", 25)],
  ["Wykonaj skuteczny blok w obronie", undefined, prog("technika", 10)],
  ["Rozegraj mecz w lidze amatorskiej lub szkolnej", undefined, prog("liga", 1)],
  ["Zagraj 20 meczów", undefined, prog("mecze", 20)],
  ["Zdobądź 50 bramek łącznie", undefined, prog("bramki", 50)],
  ["Zdobądź 5 bramek w jednym meczu", undefined, prog("bramki-mecz", 5)],
  ["Wykonaj asystę kończącą akcję zespołu", undefined, prog("technika", 11)],
  ["Zagraj 30 meczów", undefined, prog("mecze", 30)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zdobądź 75 bramek łącznie", undefined, prog("bramki", 75)],
  ["Wykonaj rzut z pierwszej linii z odległości 9 m", undefined, prog("technika", 12)],
  ["Zagraj 50 meczów", undefined, prog("mecze", 50)],
  ["Zdobądź 8 bramek w jednym meczu", undefined, prog("bramki-mecz", 8)],
  ["Rozegraj sezon w regularnej lidze", undefined, prog("liga", 2)],
  ["Zdobądź 100 bramek łącznie", undefined, prog("bramki", 100)],
  ["Opanuj grę w kontrataku (szybki środek)", undefined, prog("technika", 13)],
  ["Zagraj 75 meczów", undefined, prog("mecze", 75)],
  ["Zdobądź 150 bramek łącznie", undefined, prog("bramki", 150)],
  ["Zajmij miejsce w pierwszej połowie tabeli ligowej"],
  ["Zdobądź 10 bramek w jednym meczu", undefined, prog("bramki-mecz", 10)],
  ["Zagraj 100 meczów", undefined, prog("mecze", 100)],
  ["Zdobądź 200 bramek łącznie", undefined, prog("bramki", 200)],
  ["Wykonaj skuteczną obronę 3-2-1 jako lider defensywy", undefined, prog("technika", 14)],
  ["Rozegraj mecz w III lidze lub odpowiedniku", undefined, prog("liga", 3)],
  ["Zdobądź 300 bramek łącznie", undefined, prog("bramki", 300)],
  ["Zostań najlepszym strzelcem meczu kilkukrotnie w sezonie"],
  ["Zagraj 150 meczów", undefined, prog("mecze", 150)],
  ["Zdobądź 12 bramek w jednym meczu", undefined, prog("bramki-mecz", 12)],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Zdobądź 400 bramek łącznie", undefined, prog("bramki", 400)],
  ["Rozegraj mecz w II lidze", undefined, prog("liga", 4)],
  ["Zagraj 200 meczów", undefined, prog("mecze", 200)],
  ["Zdobądź 500 bramek łącznie", undefined, prog("bramki", 500)],
  ["Zostań kluczowym zawodnikiem rotacji zespołu ligowego"],
  ["Zdobądź 15 bramek w jednym meczu", undefined, prog("bramki-mecz", 15)],
  ["Zagraj 250 meczów", undefined, prog("mecze", 250)],
  ["Zdobądź 700 bramek łącznie", undefined, prog("bramki", 700)],
  ["Zajmij miejsce w czołówce II ligi"],
  ["Rozegraj mecz w I lidze", undefined, prog("liga", 5)],
  ["Zdobądź 900 bramek łącznie", undefined, prog("bramki", 900)],
  ["Zagraj 300 meczów", undefined, prog("mecze", 300)],
  ["Zostań najlepszym strzelcem rundy w swojej lidze"],
  ["Zdobądź 1100 bramek łącznie", undefined, prog("bramki", 1100)],
  ["Zdobądź 18 bramek w jednym meczu", undefined, prog("bramki-mecz", 18)],
  ["Zagraj 400 meczów", undefined, prog("mecze", 400)],
  ["Zdobądź 1300 bramek łącznie", undefined, prog("bramki", 1300)],
  ["Awansuj z drużyną do wyższej ligi"],
  ["Zostań rozpoznawalnym zawodnikiem w swoim regionie"],
  // 66-85 · Wyczynowy
  ["Zdobądź 1500 bramek łącznie", undefined, prog("bramki", 1500)],
  ["Zagraj 500 meczów", undefined, prog("mecze", 500)],
  ["Zadebiutuj na wysokim poziomie ligowym", undefined, prog("liga", 6)],
  ["Zdobądź 1800 bramek łącznie", undefined, prog("bramki", 1800)],
  ["Zdobądź bramkę w meczu najwyższej ligi"],
  ["Zagraj 600 meczów", undefined, prog("mecze", 600)],
  ["Zdobądź 2100 bramek łącznie", undefined, prog("bramki", 2100)],
  ["Zostań kluczowym zawodnikiem zespołu z najwyższego poziomu regionalnego"],
  ["Zdobądź 2400 bramek łącznie", undefined, prog("bramki", 2400)],
  ["Zagraj 700 meczów", undefined, prog("mecze", 700)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Zdobądź 2700 bramek łącznie", undefined, prog("bramki", 2700)],
  ["Zagraj w europejskich pucharach klubowych"],
  ["Zdobądź 3000 bramek łącznie", undefined, prog("bramki", 3000)],
  ["Zagraj 800 meczów", undefined, prog("mecze", 800)],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zdobądź 3300 bramek łącznie", undefined, prog("bramki", 3300)],
  ["Zdobądź bramkę w ważnym meczu ligowym"],
  ["Zagraj 900 meczów", undefined, prog("mecze", 900)],
  ["Zdobądź podium mistrzostw regionu z klubem"],
  // 86-99 · Elita
  ["Zdobądź 3600 bramek łącznie", undefined, prog("bramki", 3600)],
  ["Weź udział w rozgrywkach pucharowych o zasięgu ogólnokrajowym"],
  ["Zagraj 1000 meczów", undefined, prog("mecze", 1000)],
  ["Zdobądź 4000 bramek łącznie", undefined, prog("bramki", 4000)],
  ["Zostań najlepszym strzelcem sezonu swojej ligi"],
  ["Zagraj w finale rozgrywek ligowych"],
  ["Zdobądź 4500 bramek łącznie", undefined, prog("bramki", 4500)],
  ["Awansuj z klubem do wyższej klasy rozgrywkowej"],
  ["Zdobądź podium turnieju o zasięgu ogólnokrajowym"],
  ["Zdobądź 5000 bramek łącznie", undefined, prog("bramki", 5000)],
  ["Zdobądź trofeum swojej ligi klubowej"],
  ["Znajdź się w składzie gwiazd sezonu swojej ligi"],
  ["Wygraj mistrzostwo swojej ligi klubowej"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej drużyny klubowej", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Podanie i złapanie piłki ręcznej", url: yt("b9gqwuY3GCU") }],
  3: [{ kind: "video", title: "Rzut do bramki — technika podstawowa", url: yt("UrEqiwV4lhA") }],
  5: [{ kind: "video", title: "Rzut w wyskoku — jump shot", url: yt("h7NlXkWGo18") }],
  7: [{ kind: "video", title: "Rzut karny 7 m — technika", url: yt("0mcK4k7f3bQ") }],
  12: [{ kind: "video", title: "Finta — zwód w piłce ręcznej", url: yt("jQvEXdYkZgM") }],
  15: [{ kind: "video", title: "Rzut z przewrotem", url: yt("R3mJ6p3u1vM") }],
  19: [{ kind: "video", title: "Blok w obronie — technika i timing", url: yt("52IjuNjy6X0") }],
  28: [{ kind: "video", title: "Rzut z 9 metrów — first line shot", url: yt("DhWCcvQbPe8") }],
  33: [{ kind: "video", title: "Kontratak — szybki środek", url: yt("sQ-9X1JVcHs") }],
  40: [{ kind: "article", title: "Handball positions explained", url: "https://www.topendsports.com/sport/handball/positions.htm" }],
};
