// Water polo ladder 1-99. Manual — progression tracks: matches played, goals
// scored (total), and competition level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "pilka-wodna",
  name: "Piłka wodna",
  icon: "🤽",
  description:
    "Jeden z najbardziej wymagających sportów drużynowych — pływanie, siła i taktyka w basenie. Progresja: mecze, bramki i poziom rozgrywek.",
  sortOrder: 50,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj pracę nóg „śrubą” (eggbeater) i utrzymaj się wysoko nad wodą", undefined, prog("technika", 1)],
  ["Złap i podaj piłkę jedną ręką w wodzie", undefined, prog("technika", 2)],
  ["Przepłyń 100 m kraulem z głową nad wodą (styl waterpolo)", undefined, prog("technika", 3)],
  ["Wykonaj rzut do bramki z miejsca", undefined, prog("technika", 4)],
  ["Utrzymaj piłkę pod presją obrońcy", undefined, prog("technika", 5)],
  ["Wykonaj podanie w wyskoku (eggbeater lift)", undefined, prog("technika", 6)],
  ["Zrozum zasady i pozycje w grze (obrona/atak)", undefined, prog("technika", 7)],
  ["Zagraj pierwszy mecz treningowy", undefined, prog("mecze", 1)],
  ["Zdobądź pierwszą bramkę w grze", undefined, prog("bramki", 1)],
  ["Rozegraj pełny mecz (4 kwarty)", undefined, prog("mecze", 2)],
  // 11-25 · Regularny
  ["Trenuj lub graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Wykonaj rzut w przewrocie / zza głowy", undefined, prog("technika", 8)],
  ["Zagraj 5 meczów", undefined, prog("mecze", 5)],
  ["Zdobądź 10 bramek łącznie", undefined, prog("bramki", 10)],
  ["Graj skutecznie w obronie (blok i pressing)", undefined, prog("technika", 9)],
  ["Zagraj na pozycji centra lub skrzydłowego przez cały mecz"],
  ["Zagraj 10 meczów", undefined, prog("mecze", 10)],
  ["Zdobądź 25 bramek łącznie", undefined, prog("bramki", 25)],
  ["Wykonaj skuteczny sprint na środku (swim-off)", undefined, prog("technika", 10)],
  ["Rozegraj mecz w lidze amatorskiej lub szkolnej", undefined, prog("liga", 1)],
  ["Zagraj 20 meczów", undefined, prog("mecze", 20)],
  ["Zdobądź 50 bramek łącznie", undefined, prog("bramki", 50)],
  ["Zdobądź 3 bramki w jednym meczu", undefined, prog("bramki-mecz", 3)],
  ["Graj skutecznie w przewadze (man-up)", undefined, prog("technika", 11)],
  ["Zagraj 30 meczów", undefined, prog("mecze", 30)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zdobądź 75 bramek łącznie", undefined, prog("bramki", 75)],
  ["Wykonaj rzut podkręcony (screw shot) z obrotu", undefined, prog("technika", 12)],
  ["Zagraj 50 meczów", undefined, prog("mecze", 50)],
  ["Zdobądź 100 bramek łącznie", undefined, prog("bramki", 100)],
  ["Rozegraj pełny sezon w regularnej lidze", undefined, prog("liga", 2)],
  ["Zdobądź 5 bramek w jednym meczu", undefined, prog("bramki-mecz", 5)],
  ["Opanuj grę centra pod bramką (pozycja siłowa)", undefined, prog("technika", 13)],
  ["Zagraj 75 meczów", undefined, prog("mecze", 75)],
  ["Zdobądź 150 bramek łącznie", undefined, prog("bramki", 150)],
  ["Zajmij miejsce w pierwszej połowie tabeli ligowej"],
  ["Zdobądź 200 bramek łącznie", undefined, prog("bramki", 200)],
  ["Zagraj 100 meczów", undefined, prog("mecze", 100)],
  ["Graj skutecznie w obronie strefowej i pressingu (drop/press)", undefined, prog("technika", 14)],
  ["Rozegraj mecz w II lidze lub odpowiedniku", undefined, prog("liga", 3)],
  ["Zdobądź 300 bramek łącznie", undefined, prog("bramki", 300)],
  ["Zdobądź 7 bramek w jednym meczu", undefined, prog("bramki-mecz", 7)],
  ["Zagraj 150 meczów", undefined, prog("mecze", 150)],
  ["Zostań najlepszym strzelcem meczu kilkukrotnie w sezonie"],
  ["Zdobądź 400 bramek łącznie", undefined, prog("bramki", 400)],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Zdobądź 500 bramek łącznie", undefined, prog("bramki", 500)],
  ["Rozegraj mecz w I lidze", undefined, prog("liga", 4)],
  ["Zagraj 200 meczów", undefined, prog("mecze", 200)],
  ["Zdobądź 650 bramek łącznie", undefined, prog("bramki", 650)],
  ["Zostań kluczowym zawodnikiem zespołu I-ligowego"],
  ["Zdobądź 10 bramek w jednym meczu", undefined, prog("bramki-mecz", 10)],
  ["Zagraj 250 meczów", undefined, prog("mecze", 250)],
  ["Zdobądź 800 bramek łącznie", undefined, prog("bramki", 800)],
  ["Zajmij miejsce w czołówce I ligi"],
  ["Rozegraj mecz w najwyższej lidze krajowej (Ekstraliga)", undefined, prog("liga", 5)],
  ["Zdobądź 950 bramek łącznie", undefined, prog("bramki", 950)],
  ["Zagraj 300 meczów", undefined, prog("mecze", 300)],
  ["Zdobądź bramkę w meczu najwyższej ligi"],
  ["Zdobądź 1100 bramek łącznie", undefined, prog("bramki", 1100)],
  ["Zostań kluczowym zawodnikiem zespołu Ekstraligi"],
  ["Zagraj 400 meczów", undefined, prog("mecze", 400)],
  ["Zdobądź 1300 bramek łącznie", undefined, prog("bramki", 1300)],
  ["Zostań najlepszym strzelcem rundy w swojej lidze"],
  ["Zostań rozpoznawalnym zawodnikiem w swoim regionie"],
  // 66-85 · Wyczynowy
  ["Zdobądź 1500 bramek łącznie", undefined, prog("bramki", 1500)],
  ["Zagraj 500 meczów", undefined, prog("mecze", 500)],
  ["Zostań kluczowym zawodnikiem najwyższej ligi"],
  ["Zdobądź 1750 bramek łącznie", undefined, prog("bramki", 1750)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Zagraj 600 meczów", undefined, prog("mecze", 600)],
  ["Zdobądź 2000 bramek łącznie", undefined, prog("bramki", 2000)],
  ["Zostań uznanym zawodnikiem swojej ligi regionalnej"],
  ["Zdobądź 2250 bramek łącznie", undefined, prog("bramki", 2250)],
  ["Zagraj 700 meczów", undefined, prog("mecze", 700)],
  ["Zdobądź bramkę w ważnym meczu ligowym"],
  ["Zdobądź 2500 bramek łącznie", undefined, prog("bramki", 2500)],
  ["Zagraj w europejskich pucharach klubowych (Champions League)"],
  ["Zdobądź 2750 bramek łącznie", undefined, prog("bramki", 2750)],
  ["Zagraj 800 meczów", undefined, prog("mecze", 800)],
  ["Zdobądź podium mistrzostw regionu z klubem"],
  ["Weź udział w turnieju o zasięgu ogólnokrajowym"],
  ["Zdobądź 3000 bramek łącznie", undefined, prog("bramki", 3000)],
  ["Zagraj 900 meczów", undefined, prog("mecze", 900)],
  ["Zostań kapitanem swojej drużyny klubowej"],
  // 86-99 · Elita
  ["Zdobądź 3300 bramek łącznie", undefined, prog("bramki", 3300)],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zagraj 1000 meczów", undefined, prog("mecze", 1000)],
  ["Zdobądź 3600 bramek łącznie", undefined, prog("bramki", 3600)],
  ["Zostań najlepszym strzelcem sezonu swojej ligi"],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Zdobądź 4000 bramek łącznie", undefined, prog("bramki", 4000)],
  ["Awansuj do fazy medalowej turnieju o zasięgu ogólnokrajowym"],
  ["Zdobądź medal mistrzostw regionu"],
  ["Zdobądź trofeum swojej ligi klubowej"],
  ["Znajdź się w składzie gwiazd sezonu swojej ligi"],
  ["Wygraj mistrzostwo swojej ligi klubowej"],
  ["Zdobądź uznanie w krajowym środowisku piłki wodnej"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej drużyny klubowej", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, igrzyska) potwierdzają osobne certyfikaty."],
]);
