// Football (soccer) ladder 1-99. Tracks: juggling (the universal skill meter),
// passing/shooting accuracy drills, match experience. Manual check-offs.
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "pilka-nozna",
  name: "Piłka nożna",
  icon: "⚽",
  description:
    "Żonglerka, technika, mecze — mierzalne kroki od pierwszego podbicia po poziom ligowy.",
  sortOrder: 7,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Podbij piłkę 3 razy z rzędu (żonglerka)", "Uniwersalny miernik czucia piłki."],
  ["Prowadź piłkę 20 m bez utraty kontroli"],
  ["Podbij piłkę 5 razy z rzędu"],
  ["Wykonaj 10 celnych podań do partnera z 10 m"],
  ["Podbij piłkę 10 razy z rzędu"],
  ["Trafializuj bramkę 5 razy z rzędu z 11 m (pusta bramka)"],
  ["Prowadź piłkę slalomem między 5 pachołkami"],
  ["Podbij piłkę 15 razy z rzędu"],
  ["Zagraj pierwszy mecz (małe boisko lub hala)", "Dowolny format — 5v5 się liczy."],
  ["Podbij piłkę 20 razy z rzędu"],
  // 11-25 · Regularny
  ["Graj lub trenuj raz w tygodniu przez 4 kolejne tygodnie"],
  ["Podbij piłkę 30 razy z rzędu"],
  ["Wykonaj 10 celnych podań słabszą nogą z 10 m"],
  ["Zagraj 5 meczów"],
  ["Przyjmij piłkę z powietrza w jednym kontakcie 5 razy z rzędu"],
  ["Żongluj piłką 50 razy z rzędu", "Symboliczna „pięćdziesiątka” każdego podwórka."],
  ["Trafializuj z 16 m w światło bramki 7/10 strzałów"],
  ["Zagraj 10 meczów"],
  ["Wykonaj zwód (np. przełożenie) skutecznie w meczu"],
  ["Podbij piłkę 75 razy z rzędu"],
  ["Prowadź piłkę slalomem wyłącznie słabszą nogą"],
  ["Graj lub trenuj 2 razy w tygodniu przez 8 kolejnych tygodni"],
  ["Podbij piłkę 100 razy z rzędu", "Trzycyfrowa żonglerka — czucie piłki jest już trwałe."],
  ["Strzel gola w meczu"],
  ["Zagraj 20 meczów"],
  // 26-45 · Średniozaawansowany
  ["Żongluj naprzemiennie: noga-noga-udo-głowa (pełny cykl 3 razy)"],
  ["Wykonaj 10 celnych długich podań (25 m+) 7/10"],
  ["Podbij piłkę 150 razy z rzędu"],
  ["Zaliczaj asystę w meczu"],
  ["Trafializuj rzut wolny nad murem do bramki (trening) 3/10"],
  ["Zagraj 35 meczów"],
  ["Podbij piłkę wyłącznie słabszą nogą 20 razy"],
  ["Utrzymaj piłkę w powietrzu w parze (bez ziemi) 20 podbić"],
  ["Strzel gola słabszą nogą w meczu"],
  ["Podbij piłkę 200 razy z rzędu"],
  ["Graj regularnie przez pełny sezon (min. 6 miesięcy)"],
  ["Zagraj 50 meczów", "Pół setki spotkań w nogach."],
  ["Wykonaj skuteczny drybling 1v1 trzykrotnie w jednym meczu"],
  ["Strzel gola z woleja lub półwoleja w meczu"],
  ["Trafializuj z rzutu rożnego w pole karne 8/10 dośrodkowań"],
  ["Podbij piłkę 300 razy z rzędu"],
  ["Strzel 10 goli łącznie"],
  ["Zagraj mecz na pełnowymiarowym boisku (11v11)"],
  ["Wygraj lokalny turniej amatorski (małe boisko lub hala) ze swoją drużyną"],
  ["Zagraj 75 meczów"],
  // 46-65 · Zaawansowany
  ["Żongluj w chodzie 50 m bez upuszczenia piłki"],
  ["Strzel gola bezpośrednio z rzutu wolnego w meczu", "Marzenie każdego piłkarza."],
  ["Podbij piłkę 500 razy z rzędu"],
  ["Zagraj 100 meczów", "Setka rozegranych spotkań."],
  ["Strzel 3 gole w jednym meczu (hat-trick)"],
  ["Dołącz do drużyny grającej w zorganizowanych rozgrywkach ligowych"],
  ["Strzel 25 goli łącznie"],
  ["Wykonaj rabonę lub strzał z przewrotki na treningu"],
  ["Zaliczaj 3 asysty w jednym meczu"],
  ["Zagraj pełne 90 minut meczu ligowego"],
  ["Podbij piłkę 750 razy z rzędu"],
  ["Zagraj 150 meczów"],
  ["Strzel gola głową w meczu"],
  ["Zostań wybrany zawodnikiem meczu (MVP) w swojej drużynie"],
  ["Strzel 50 goli łącznie"],
  ["Rozegraj pełny sezon ligowy bez opuszczenia meczu z własnej winy"],
  ["Żongluj 1000 razy z rzędu", "Poziom trików ulicznych."],
  ["Zagraj 200 meczów"],
  ["Wykonaj skuteczną przewrotkę w meczu"],
  ["Strzel gola z ponad 25 metrów w meczu"],
  // 66-85 · Wyczynowy
  ["Zostań kapitanem drużyny na sezon"],
  ["Strzel 100 goli łącznie", "Trzycyfrowy licznik trafień."],
  ["Zagraj 300 meczów"],
  ["Wygraj ligę amatorską ze swoją drużyną"],
  ["Zostań królem strzelców swojej ligi/turnieju"],
  ["Rozegraj 5 pełnych sezonów ligowych"],
  ["Zagraj w rozgrywkach okręgowych (B-klasa lub wyżej)"],
  ["Strzel gola w oficjalnym meczu związkowym (PZPN)"],
  ["Zagraj 400 meczów"],
  ["Zaliczaj 25 asyst łącznie w rozgrywkach ligowych"],
  ["Awansuj z drużyną do wyższej klasy rozgrywkowej"],
  ["Strzel 150 goli łącznie"],
  ["Zagraj 50 meczów w rozgrywkach związkowych"],
  ["Zostań powołany do kadry turnieju/reprezentacji regionu amatorskiego"],
  ["Zagraj 500 meczów", "Pół tysiąca spotkań."],
  ["Wygraj puchar okręgu lub równorzędne trofeum"],
  ["Rozegraj sezon na poziomie A-klasy lub wyższym jako podstawowy zawodnik"],
  ["Strzel 200 goli łącznie"],
  ["Zagraj na poziomie ligi okręgowej"],
  ["Rozegraj 100 oficjalnych meczów ligowych"],
  // 86-99 · Elita
  ["Zagraj na poziomie IV ligi"],
  ["Strzel gola na poziomie IV ligi lub wyższym"],
  ["Zagraj 600 meczów łącznie"],
  ["Rozegraj pełny sezon IV ligi jako podstawowy zawodnik"],
  ["Zagraj na poziomie III ligi", "Próg piłki półprofesjonalnej w Polsce."],
  ["Strzel 250 goli łącznie"],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zagraj 50 meczów na poziomie III ligi lub wyższym"],
  ["Rozegraj pełny sezon III ligi jako podstawowy zawodnik"],
  ["Zagraj 750 meczów łącznie"],
  ["Wystąp w rozgrywkach Pucharu Polski na szczeblu regionalnym"],
  ["Poprowadź drużynę jako lider / kapitan przez sezon"],
  ["Zdobądź uznanie w lokalnej społeczności piłkarskiej", "Rozpoznawalny, wieloletni zawodnik lokalnej ligi."],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej amatorskiej drużyny", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  1: prog("zonglerka", 3), 3: prog("zonglerka", 5), 5: prog("zonglerka", 10), 8: prog("zonglerka", 15),
  10: prog("zonglerka", 20), 12: prog("zonglerka", 30), 16: prog("zonglerka", 50), 20: prog("zonglerka", 75),
  23: prog("zonglerka", 100), 28: prog("zonglerka", 150), 35: prog("zonglerka", 200), 41: prog("zonglerka", 300),
  48: prog("zonglerka", 500), 56: prog("zonglerka", 750), 62: prog("zonglerka", 1000),
  9: prog("mecze", 1), 14: prog("mecze", 5), 18: prog("mecze", 10), 25: prog("mecze", 20),
  31: prog("mecze", 35), 37: prog("mecze", 50), 45: prog("mecze", 75), 49: prog("mecze", 100),
  57: prog("mecze", 150), 63: prog("mecze", 200), 68: prog("mecze", 300), 74: prog("mecze", 400),
  80: prog("mecze", 500), 88: prog("mecze", 600), 95: prog("mecze", 750),
  11: freq(1, 4), 22: freq(2, 8),
  24: prog("gole", 1), 42: prog("gole", 10), 52: prog("gole", 25), 60: prog("gole", 50),
  67: prog("gole", 100), 77: prog("gole", 150), 83: prog("gole", 200), 91: prog("gole", 250),
  // pozostałe: umiejętności, wydarzenia i poziomy rozgrywkowe — manualne.
};
