// Creative writing ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, word count capped ~500k (a few books' worth),
// top tiers reframed as attainable mastery, real feats left to future certs).
// Tracks: umiejetnosci, teksty (finished pieces), slowa (words), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "pisanie",
  name: "Pisanie",
  icon: "✍️",
  description:
    "Twórcze pisanie — od pierwszych scen po dopracowaną prozę. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i słowa → ukończone dzieła → dojrzały, autorski głos.",
  sortOrder: 97,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Napisz codziennie kilka zdań przez tydzień", undefined, prog("umiejetnosci", 1)],
  ["Napisz pełną, spójną scenę (pół strony)", undefined, prog("umiejetnosci", 2)],
  ["Opisz miejsce tak, by czytelnik je zobaczył", undefined, prog("umiejetnosci", 3)],
  ["Napisz dialog dwóch postaci brzmiący naturalnie", undefined, prog("umiejetnosci", 4)],
  ["Zamień „mówienie” na „pokazywanie” (show, don't tell)", undefined, prog("umiejetnosci", 5)],
  ["Napisz mikroopowiadanie z początkiem, środkiem i końcem", undefined, prog("teksty", 3)],
  ["Zredaguj własny tekst (skróć, popraw, wygładź)", undefined, prog("umiejetnosci", 6)],
  ["Napisz łącznie 5 000 słów", undefined, prog("slowa", 5000)],
  ["Ukończ 5 krótkich tekstów", undefined, prog("teksty", 5)],
  ["Pisz łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Pisz kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Zbuduj postać z celem, wadą i pragnieniem", undefined, prog("umiejetnosci", 7)],
  ["Napisz łącznie 12 000 słów", undefined, prog("slowa", 12000)],
  ["Napisz opowiadanie o wyraźnej strukturze (zawiązanie–punkt–finał)", undefined, prog("umiejetnosci", 8)],
  ["Pisz łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Opanuj punkt widzenia (POV) i trzymaj go konsekwentnie", undefined, prog("umiejetnosci", 9)],
  ["Ukończ 12 tekstów", undefined, prog("teksty", 12)],
  ["Zbuduj napięcie i konflikt w scenie", undefined, prog("umiejetnosci", 10)],
  ["Napisz zakończenie, które płynie z historii", undefined, prog("umiejetnosci", 11)],
  ["Napisz łącznie 25 000 słów", undefined, prog("slowa", 25000)],
  ["Zredaguj tekst w kilku przejściach (revision passes)", undefined, prog("umiejetnosci", 12)],
  ["Znajdź i wzmocnij własny głos / styl", undefined, prog("umiejetnosci", 13)],
  ["Napisz opowiadanie na konkurs lub do publikacji", undefined, prog("umiejetnosci", 14)],
  ["Ukończ 20 tekstów", undefined, prog("teksty", 20)],
  ["Pisz łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  // 26-45 · Średniozaawansowany
  ["Pisz regularnie przez 8 kolejnych tygodni", undefined, freq(3, 8)],
  ["Przyjmij krytykę i przepisz tekst po feedbacku", undefined, prog("umiejetnosci", 15)],
  ["Napisz łącznie 45 000 słów", undefined, prog("slowa", 45000)],
  ["Zbuduj wielowątkową fabułę (subploty, spięcia)", undefined, prog("umiejetnosci", 16)],
  ["Napisz zbiór opowiadań o wspólnym motywie", undefined, prog("umiejetnosci", 17)],
  ["Napisz łącznie 70 000 słów", undefined, prog("slowa", 70000)],
  ["Opanuj rytm i tempo prozy (pacing rozdziału)", undefined, prog("umiejetnosci", 18)],
  ["Ukończ 30 tekstów / rozdziałów", undefined, prog("teksty", 30)],
  ["Zbuduj świat przedstawiony (spójny world-building)", undefined, prog("umiejetnosci", 19)],
  ["Napisz łącznie 100 000 słów", undefined, prog("slowa", 100000)],
  ["Napisz pierwszą wersję powieści (pierwszy szkic)", undefined, prog("umiejetnosci", 20)],
  ["Zredaguj dłuższy tekst od struktury po zdanie", undefined, prog("umiejetnosci", 21)],
  ["Pisz łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Zbuduj rozpoznawalny, spójny styl narracji", undefined, prog("umiejetnosci", 22)],
  ["Napisz łącznie 140 000 słów", undefined, prog("slowa", 140000)],
  ["Opanuj podtekst i wieloznaczność (głębia sceny)", undefined, prog("umiejetnosci", 23)],
  ["Ukończ 40 tekstów / rozdziałów", undefined, prog("teksty", 40)],
  ["Ukończ dopracowaną, gotową powieść lub większą całość", undefined, prog("umiejetnosci", 24)],
  ["Pisz łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Napisz łącznie 180 000 słów", undefined, prog("slowa", 180000)],
  // 46-65 · Zaawansowany (amator)
  ["Pisz regularnie przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Publikuj teksty i buduj czytelników (blog / portal / social)"],
  ["Opanuj wybrany gatunek na wysokim poziomie", undefined, prog("umiejetnosci", 25)],
  ["Napisz łącznie 220 000 słów", undefined, prog("slowa", 220000)],
  ["Pisz łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Zbierz i zredaguj gotowy do wysyłki maszynopis"],
  ["Opublikuj tekst w magazynie / antologii lub sprzedaj tekst", undefined, prog("umiejetnosci", 26)],
  ["Ukończ 55 tekstów / rozdziałów", undefined, prog("teksty", 55)],
  ["Napisz drugą powieść / większe dzieło", undefined, prog("umiejetnosci", 27)],
  ["Napisz łącznie 280 000 słów", undefined, prog("slowa", 280000)],
  ["Zbuduj stałe grono czytelników"],
  ["Wygraj lub wyróżnij się w konkursie literackim"],
  ["Opanuj mistrzowską redakcję (self-editing na wysokim poziomie)", undefined, prog("umiejetnosci", 28)],
  ["Napisz łącznie 330 000 słów", undefined, prog("slowa", 330000)],
  ["Wydaj książkę (własnym nakładem lub w wydawnictwie)", undefined, prog("umiejetnosci", 29)],
  ["Pisz łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Poprowadź kogoś przez podstawy pisania"],
  ["Zrealizuj spójny cykl / serię tekstów"],
  ["Napisz dzieło o dojrzałej, dopracowanej strukturze", undefined, prog("umiejetnosci", 30)],
  ["Ukończ 70 tekstów / rozdziałów", undefined, prog("teksty", 70)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Pisz regularnie przez pełny sezon (6 miesięcy)"],
  ["Pisz swobodnie w różnych formach (proza, esej, scenariusz)", undefined, prog("umiejetnosci", 31)],
  ["Napisz łącznie 380 000 słów", undefined, prog("slowa", 380000)],
  ["Pisz łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj społeczność / grono odbiorców swojej twórczości"],
  ["Rozwiń warsztat na tyle, by uczyć pisania", undefined, prog("umiejetnosci", 32)],
  ["Zbuduj rozpoznawalny dorobek o spójnym stylu"],
  ["Wydaj kolejną książkę / zbuduj dorobek"],
  ["Opanuj każdą formę i rejestr na wysokim poziomie", undefined, prog("umiejetnosci", 33)],
  ["Ukończ 85 tekstów / rozdziałów", undefined, prog("teksty", 85)],
  ["Zdobądź wyróżnienie w konkursie lub uznanie czytelników"],
  ["Napisz łącznie 430 000 słów", undefined, prog("slowa", 430000)],
  ["Zrealizuj ambitne, autorskie dzieło", undefined, prog("umiejetnosci", 34)],
  ["Twój styl jest dojrzały i rozpoznawalny", undefined, prog("umiejetnosci", 35)],
  ["Pisz łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Zbuduj nazwisko o zasięgu ponadlokalnym"],
  ["Poprowadź warsztaty lub mentoring dla piszących"],
  ["Publikuj kursy lub materiały o pisaniu"],
  ["Zrealizuj publikację prezentującą dorobek"],
  ["Ukończ 100 tekstów / rozdziałów", undefined, prog("teksty", 100)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Napisz łącznie 470 000 słów", undefined, prog("slowa", 470000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdym tekście"],
  ["Pisz łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zbuduj bogaty, spójny dorobek o autorskim charakterze"],
  ["Twój styl inspiruje innych piszących w Twoim otoczeniu"],
  ["Zrealizuj osobisty „opus” — powieść lub cykl życia", undefined, prog("umiejetnosci", 36)],
  ["Regularnie publikujesz książki lub teksty"],
  ["Napisz łącznie 500 000 słów", undefined, prog("slowa", 500000)],
  ["Twoja twórczość zdobywa uznanie poza lokalną społecznością", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 120 tekstów / rozdziałów", undefined, prog("teksty", 120)],
  ["Uczysz i kształtujesz kolejnych autorów", undefined, prog("umiejetnosci", 38)],
  ["Pisz łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Masz dorobek, z którego można ułożyć retrospektywę", undefined, prog("umiejetnosci", 39)],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski głos", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty.", prog("umiejetnosci", 40)],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (twórcze pisanie: Reedsy, Abbie Emmons, Alexa Donne i in.).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  // — Rozszerzenie zasobów Tier 1 (wszystkie linki zweryfikowane jako aktywne) —
  1: [{ kind: "article", title: "Jak zbudować codzienny nawyk pisania", url: "https://thewritepractice.com/writing-habit/" }],
  6: [{ kind: "article", title: "Flash fiction: sztuka najkrótszych opowiadań", url: "https://thewritepractice.com/flash-fiction/" }],
  7: [{ kind: "article", title: "Jak samodzielnie zredagować własny tekst (z szablonem)", url: "https://reedsy.com/blog/how-to-edit-a-book/" }],
  8: [{ kind: "article", title: "Najlepsze programy i narzędzia do pisania", url: "https://reedsy.com/blog/book-writing-software/" }],
  9: [{ kind: "article", title: "Jak opublikować opowiadanie: 3 drogi do czytelników", url: "https://reedsy.com/blog/how-to-publish-a-short-story/" }],
  11: [{ kind: "article", title: "Jak zbudować rutynę pisania, której nie porzucisz", url: "https://jerryjenkins.com/writing-routine/" }],
  13: [{ kind: "article", title: "Ile słów ma powieść? Cele i liczba słów", url: "https://reedsy.com/blog/how-many-words-in-a-novel/" }],
  15: [{ kind: "article", title: "Punkt widzenia (POV): kompletny przewodnik z przykładami", url: "https://reedsy.com/blog/point-of-view/" }],
  17: [{ kind: "article", title: "Podróż bohatera: 12 kroków klasycznej struktury fabuły", url: "https://reedsy.com/blog/heros-journey/" }],
  20: [{ kind: "article", title: "Przygotowanie do NaNoWriMo: 8 wskazówek na listopad", url: "https://reedsy.com/blog/how-to-prepare-for-nanowrimo/" }],
  25: [{ kind: "article", title: "Kompletny przewodnik po query letter", url: "https://www.janefriedman.com/query-letters/" }],
  2: [{ kind: "video", title: "Jak napisać scenę", url: yt("XLDo02UhOIo") }],
  3: [{ kind: "video", title: "Opis miejsca (setting description)", url: yt("PH_NoXKO9Ec") }],
  4: [{ kind: "video", title: "Naturalny dialog", url: yt("tCZSndWrZZM") }],
  5: [{ kind: "video", title: "Pokazuj, nie mów (show, don't tell)", url: yt("R8waH6F-ifI") }],
  12: [{ kind: "video", title: "Postać: cel, wada, pragnienie", url: yt("kGoGkGUbWJU") }],
  14: [{ kind: "video", title: "Struktura trzyaktowa opowieści", url: yt("_ugwPlaZasY") }],
  16: [{ kind: "video", title: "Punkt widzenia (POV) w prozie", url: yt("17yV5yRVXec") }],
  18: [{ kind: "video", title: "Napięcie i konflikt w scenie", url: yt("VRWFvW-D7V8") }],
  21: [{ kind: "video", title: "Redakcja i poprawki (self-editing)", url: yt("vLMwtObYZrs") }],
  22: [{ kind: "video", title: "Znajdź własny głos pisarski", url: yt("Mk-tNDIwl2U") }],
  29: [{ kind: "video", title: "Wielowątkowość i subploty", url: yt("6yReK8vCrTc") }],
  34: [{ kind: "video", title: "Budowanie świata (world-building)", url: yt("XGNdT3Adg20") }],
};
