// Olympic weightlifting ladder 1-99. Manual — progression tracks: snatch (kg),
// clean & jerk (kg), technique, and competition level. Values = kg (male
// reference; women adjust with age/weight tables — noted at top levels).
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "podnoszenie-ciezarow",
  name: "Podnoszenie ciężarów",
  icon: "🏋️",
  description:
    "Dwubój olimpijski — rwanie (snatch) i podrzut (clean & jerk). Progresja: ciężary w obu bojach, technika i poziom zawodów. Kilogramy w odniesieniu open.",
  sortOrder: 60,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj pozycję overhead squat z gryfem", undefined, prog("technika", 1)],
  ["Wykonaj poprawny snatch z pozycji hang (z wiszenia)", undefined, prog("technika", 2)],
  ["Wykonaj poprawny clean & jerk techniczny z lekkim ciężarem", undefined, prog("technika", 3)],
  ["Zerwij (snatch) 30 kg z podłogi", undefined, prog("snatch", 30)],
  ["Podrzuć (C&J) 40 kg", undefined, prog("cj", 40)],
  ["Opanuj przejście pod gryf (turnaround w jerku)", undefined, prog("technika", 4)],
  ["Zerwij 40 kg", undefined, prog("snatch", 40)],
  ["Podrzuć 50 kg", undefined, prog("cj", 50)],
  ["Wykonaj snatch z pełnym siadem (squat snatch)", undefined, prog("technika", 5)],
  ["Zerwij 50 kg", undefined, prog("snatch", 50)],
  // 11-25 · Regularny
  ["Trenuj 2 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(2, 4)],
  ["Podrzuć 60 kg", undefined, prog("cj", 60)],
  ["Zerwij 55 kg", undefined, prog("snatch", 55)],
  ["Opanuj split jerk (nożyce)", undefined, prog("technika", 6)],
  ["Podrzuć 70 kg", undefined, prog("cj", 70)],
  ["Zerwij 60 kg", undefined, prog("snatch", 60)],
  ["Wystartuj w pierwszych zawodach", undefined, prog("liga", 1)],
  ["Podrzuć 80 kg", undefined, prog("cj", 80)],
  ["Zerwij 65 kg", undefined, prog("snatch", 65)],
  ["Utrzymaj technikę przy submaksymalnych ciężarach", undefined, prog("technika", 7)],
  ["Podrzuć 90 kg", undefined, prog("cj", 90)],
  ["Zerwij 70 kg", undefined, prog("snatch", 70)],
  ["Zaliczy dwubój 160 kg łącznie (total)", undefined, prog("total", 160)],
  ["Podrzuć 100 kg", "Setka w podrzucie.", prog("cj", 100)],
  ["Zerwij 75 kg", undefined, prog("snatch", 75)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 3 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Podrzuć 105 kg", undefined, prog("cj", 105)],
  ["Zerwij 80 kg", undefined, prog("snatch", 80)],
  ["Zaliczy total 190 kg", undefined, prog("total", 190)],
  ["Opanuj timing drugiego pociągnięcia (triple extension)", undefined, prog("technika", 8)],
  ["Podrzuć 110 kg", undefined, prog("cj", 110)],
  ["Zerwij 85 kg", undefined, prog("snatch", 85)],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  ["Podrzuć 120 kg", undefined, prog("cj", 120)],
  ["Zerwij 90 kg", undefined, prog("snatch", 90)],
  ["Zaliczy total 210 kg", undefined, prog("total", 210)],
  ["Utrzymaj powtarzalność techniki na 90% maksa", undefined, prog("technika", 9)],
  ["Podrzuć 130 kg", undefined, prog("cj", 130)],
  ["Zerwij 95 kg", undefined, prog("snatch", 95)],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Podrzuć 135 kg", undefined, prog("cj", 135)],
  ["Zerwij 100 kg", "Setka w rwaniu.", prog("snatch", 100)],
  ["Zaliczy total 235 kg", undefined, prog("total", 235)],
  ["Podrzuć 140 kg", undefined, prog("cj", 140)],
  ["Zerwij 105 kg", undefined, prog("snatch", 105)],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu z periodyzacją przez sezon"],
  ["Podrzuć 145 kg", undefined, prog("cj", 145)],
  ["Zerwij 110 kg", undefined, prog("snatch", 110)],
  ["Zaliczy total 255 kg", undefined, prog("total", 255)],
  ["Zajmij miejsce w czołówce mistrzostw okręgu"],
  ["Podrzuć 150 kg", undefined, prog("cj", 150)],
  ["Zerwij 115 kg", undefined, prog("snatch", 115)],
  ["Utrzymaj perfekcyjną technikę na 95% maksa", undefined, prog("technika", 10)],
  ["Podrzuć 155 kg", undefined, prog("cj", 155)],
  ["Zerwij 120 kg", undefined, prog("snatch", 120)],
  ["Zaliczy total 275 kg", undefined, prog("total", 275)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju (kategoria)"],
  ["Podrzuć 160 kg", undefined, prog("cj", 160)],
  ["Zerwij 125 kg", undefined, prog("snatch", 125)],
  ["Zdobądź minimum na mistrzostwa kraju seniorów"],
  ["Podrzuć 165 kg", undefined, prog("cj", 165)],
  ["Zerwij 130 kg", undefined, prog("snatch", 130)],
  ["Zaliczy total 295 kg", undefined, prog("total", 295)],
  ["Zdobądź medal mistrzostw kraju juniorów"],
  ["Podrzuć 170 kg", undefined, prog("cj", 170)],
  // 66-85 · Wyczynowy
  ["Zerwij 135 kg", undefined, prog("snatch", 135)],
  ["Zaliczy total 310 kg", undefined, prog("total", 310)],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Podrzuć 175 kg", undefined, prog("cj", 175)],
  ["Zerwij 140 kg", undefined, prog("snatch", 140)],
  ["Utrzymaj technikę mistrzowską pod presją zawodów", undefined, prog("technika", 11)],
  ["Zaliczy total 325 kg", undefined, prog("total", 325)],
  ["Wystartuj w zawodach międzynarodowych"],
  ["Podrzuć 180 kg", undefined, prog("cj", 180)],
  ["Zerwij 145 kg", undefined, prog("snatch", 145)],
  ["Zaliczy total 340 kg", undefined, prog("total", 340)],
  ["Zdobądź minimum na mistrzostwa kraju amatorów"],
  ["Podrzuć 190 kg", undefined, prog("cj", 190)],
  ["Zerwij 150 kg", undefined, prog("snatch", 150)],
  ["Zaliczy total 355 kg", undefined, prog("total", 355)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw regionu"],
  ["Podrzuć 200 kg", "Dwieście w podrzucie.", prog("cj", 200)],
  ["Zerwij 160 kg", undefined, prog("snatch", 160)],
  ["Zaliczy total 375 kg", undefined, prog("total", 375)],
  ["Zdobądź medal mistrzostw regionu"],
  // 86-99 · Elita
  ["Podrzuć 210 kg", undefined, prog("cj", 210)],
  ["Zerwij 170 kg", undefined, prog("snatch", 170)],
  ["Zaliczy total 390 kg", undefined, prog("total", 390)],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Podrzuć 220 kg", undefined, prog("cj", 220)],
  ["Zerwij 180 kg", undefined, prog("snatch", 180)],
  ["Zaliczy total 400 kg", "Bardzo wysoki, wieloletnio wypracowany total.", prog("total", 400)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju amatorów"],
  ["Zdobądź medal mistrzostw kraju amatorów"],
  ["Poprowadź kogoś przez zaawansowaną technikę dwuboju"],
  ["Ustanów swój rekord życiowy w boju lub dwuboju", undefined, prog("technika", 12)],
  ["Zaliczy total 420 kg", undefined, prog("total", 420)],
  ["Zdobądź wielokrotne medale mistrzostw kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat w dwuboju", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, igrzyska) potwierdzają osobne certyfikaty."],
]);
