// Poker ladder 1-99. Manual — progression tracks: strategy skill, stakes level,
// bankroll/results, and tournament results. A mind sport of skill over the long run.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "poker",
  name: "Poker",
  icon: "🃏",
  description:
    "Gra umysłowa łącząca matematykę, psychologię i zarządzanie ryzykiem (Texas Hold'em). Progresja: strategia, poziom stawek i wyniki turniejowe.",
  sortOrder: 80,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Poznaj układy kart i przebieg rozdania (Texas Hold'em)", undefined, prog("strategia", 1)],
  ["Zrozum pozycję przy stole i jej znaczenie", undefined, prog("strategia", 2)],
  ["Zagraj tight-aggressive preflop (dobór rąk startowych)", undefined, prog("strategia", 3)],
  ["Rozegraj pierwszą sesję cash game (mikrostawki)", undefined, prog("stawki", 1)],
  ["Oblicz podstawowe pot odds i outs", undefined, prog("strategia", 4)],
  ["Rozegraj pierwszy turniej (freeroll lub niski buy-in)", undefined, prog("turnieje", 1)],
  ["Unikaj gry zbyt wielu rąk (dyscyplina zakresu)", undefined, prog("strategia", 5)],
  ["Zakończ miesiąc gry na plusie na mikrostawkach", undefined, prog("wyniki", 1)],
  ["Zrozum bankroll management (zasady stawki do banku)", undefined, prog("strategia", 6)],
  ["Rozegraj 5000 rozdań łącznie", undefined, prog("rozdania", 5000)],
  // 11-25 · Regularny
  ["Graj i studiuj strategię regularnie przez 4 tygodnie", undefined, freq(3, 4)],
  ["Opanuj continuation bet i podstawy gry na flopie", undefined, prog("strategia", 7)],
  ["Osiągnij zysk na stawkach NL10 (cash) lub odpowiedniku", undefined, prog("stawki", 2)],
  ["Rozegraj 20 000 rozdań łącznie", undefined, prog("rozdania", 20000)],
  ["Zbuduj i utrzymaj bankroll przez 3 miesiące bez bankructwa", undefined, prog("wyniki", 2)],
  ["Opanuj czytanie zakresów przeciwnika (range reading)", undefined, prog("strategia", 8)],
  ["Wejdź do płatnych miejsc (ITM) w turnieju", undefined, prog("turnieje", 2)],
  ["Osiągnij zysk na stawkach NL25", undefined, prog("stawki", 3)],
  ["Rozegraj 50 000 rozdań łącznie", undefined, prog("rozdania", 50000)],
  ["Opanuj grę na turnie i riverze (value bet / bluff)", undefined, prog("strategia", 9)],
  ["Osiągnij zysk na stawkach NL50", undefined, prog("stawki", 4)],
  ["Zajmij miejsce przy stole finałowym małego turnieju", undefined, prog("turnieje", 3)],
  ["Rozegraj 100 000 rozdań łącznie", undefined, prog("rozdania", 100000)],
  ["Opanuj podstawy GTO vs. exploit (kiedy odchodzić od równowagi)", undefined, prog("strategia", 10)],
  ["Osiągnij zysk na stawkach NL100 (1$/2$ lub odpowiednik)", "Poziom kompetentnego regularnego gracza.", prog("stawki", 5)],
  // 26-45 · Średniozaawansowany
  ["Studiuj solvery i teorię gry systematycznie przez 12 tygodni", undefined, freq(4, 12)],
  ["Opanuj sizing zakładów i konstrukcję zakresu betów", undefined, prog("strategia", 11)],
  ["Wygraj mały turniej (kilkaset uczestników)", undefined, prog("turnieje", 4)],
  ["Rozegraj 250 000 rozdań łącznie", undefined, prog("rozdania", 250000)],
  ["Osiągnij zysk na stawkach NL200", undefined, prog("stawki", 6)],
  ["Utrzymaj dodatni winrate (bb/100) przez 6 miesięcy", undefined, prog("wyniki", 3)],
  ["Opanuj grę 3-bet/4-bet i dynamikę preflop", undefined, prog("strategia", 12)],
  ["Osiągnij zysk na stawkach NL500", undefined, prog("stawki", 7)],
  ["Wejdź do ITM turnieju z pulą 100k+", undefined, prog("turnieje", 5)],
  ["Rozegraj 500 000 rozdań łącznie", undefined, prog("rozdania", 500000)],
  ["Opanuj zaawansowane czytanie mety i dostosowanie do stołu", undefined, prog("strategia", 13)],
  ["Osiągnij zysk na stawkach NL1000 (5$/10$)", undefined, prog("stawki", 8)],
  ["Zajmij miejsce przy stole finałowym dużego turnieju online", undefined, prog("turnieje", 6)],
  ["Rozegraj 750 000 rozdań łącznie", undefined, prog("rozdania", 750000)],
  ["Utrzymaj dyscyplinę mentalną (tilt control) w długiej sesji", undefined, prog("strategia", 14)],
  ["Osiągnij zysk na stawkach NL2000", undefined, prog("stawki", 9)],
  ["Wygraj duży turniej online (pula 100k+)", undefined, prog("turnieje", 7)],
  ["Rozegraj 1 000 000 rozdań łącznie", "Milion rozdań doświadczenia.", prog("rozdania", 1000000)],
  ["Opanuj multi-tabling na wysokim poziomie bez spadku EV", undefined, prog("strategia", 15)],
  ["Osiągnij roczny zysk pozwalający grać zawodowo", undefined, prog("wyniki", 4)],
  // 46-65 · Zaawansowany
  ["Traktuj poker jak zawód — pełny grind i studia przez sezon"],
  ["Osiągnij zysk na stawkach NL5000 (25$/50$)", undefined, prog("stawki", 10)],
  ["Zbuduj repertuar strategii pod różne formaty (cash/MTT/SNG)", undefined, prog("strategia", 16)],
  ["Zagraj na żywo w turnieju z buy-in 1000$+", undefined, prog("turnieje", 8)],
  ["Rozegraj 1 500 000 rozdań łącznie", undefined, prog("rozdania", 1500000)],
  ["Osiągnij zysk na stawkach NL10000", undefined, prog("stawki", 11)],
  ["Wejdź do ITM turnieju na żywo rangi major (WSOP/EPT)", undefined, prog("turnieje", 9)],
  ["Utrzymaj status wygrywającego regulara na high stakes", undefined, prog("wyniki", 5)],
  ["Opanuj analizę EV i wariancji na poziomie eksperckim", undefined, prog("strategia", 17)],
  ["Zajmij miejsce przy stole finałowym turnieju rangi major", undefined, prog("turnieje", 10)],
  ["Rozegraj 2 000 000 rozdań łącznie", undefined, prog("rozdania", 2000000)],
  ["Osiągnij zysk na stawkach nosebleed (NL25000+)", undefined, prog("stawki", 12)],
  ["Wygraj turniej na żywo z pulą 500k+", undefined, prog("turnieje", 11)],
  ["Zdobądź sześciocyfrowy wynik w jednym turnieju", undefined, prog("wyniki", 6)],
  ["Opanuj grę heads-up na najwyższym poziomie", undefined, prog("strategia", 18)],
  ["Zajmij miejsce przy stole finałowym eventu WSOP/EPT/WPT", undefined, prog("turnieje", 12)],
  ["Rozegraj 2 500 000 rozdań łącznie", undefined, prog("rozdania", 2500000)],
  ["Osiągnij zysk na najwyższych stawkach cash dostępnych online", undefined, prog("stawki", 13)],
  ["Zdobądź nagrodę 250k+ w pojedynczym turnieju", undefined, prog("wyniki", 7)],
  ["Utrzymaj status jednego z najlepszych regularów swojej stawki", undefined, prog("strategia", 19)],
  // 66-85 · Wyczynowy
  ["Wygraj event rangi major (WSOP Circuit / EPT side)", undefined, prog("turnieje", 13)],
  ["Rozegraj 3 000 000 rozdań łącznie", undefined, prog("rozdania", 3000000)],
  ["Zdobądź milion dolarów łącznych wygranych turniejowych", undefined, prog("wyniki", 8)],
  ["Zajmij miejsce przy stole finałowym WSOP Main Event day", undefined, prog("turnieje", 14)],
  ["Osiągnij zysk grając w prywatnych high-stakes cash games", undefined, prog("stawki", 14)],
  ["Zdobądź bransoletkę WSOP lub tytuł EPT/WPT", "Kamień milowy pokera na żywo.", prog("turnieje", 15)],
  ["Rozegraj 3 500 000 rozdań łącznie", undefined, prog("rozdania", 3500000)],
  ["Osiągnij status winning player w grach nosebleed", undefined, prog("strategia", 20)],
  ["Zdobądź drugą bransoletkę WSOP lub duży tytuł", undefined, prog("turnieje", 16)],
  ["Zdobądź 3 mln dolarów łącznych wygranych", undefined, prog("wyniki", 9)],
  ["Wejdź do rankingu Global Poker Index (Top 100)"],
  ["Osiągnij zysk w Super High Roller (buy-in 25k$+)", undefined, prog("turnieje", 17)],
  ["Rozegraj 4 000 000 rozdań łącznie", undefined, prog("rozdania", 4000000)],
  ["Zajmij miejsce przy stole finałowym dużego turnieju", undefined, prog("turnieje", 18)],
  ["Zdobądź 5 mln dolarów łącznych wygranych", undefined, prog("wyniki", 10)],
  ["Osiągnij czołową 50 rankingu krajowego"],
  ["Zdobądź kolejny tytuł turniejowy rangi krajowej", undefined, prog("turnieje", 19)],
  ["Osiągnij mistrzowski poziom w każdym formacie (cash, MTT, HU)", undefined, prog("strategia", 21)],
  ["Wygraj duży turniej z wysoką pulą nagród", undefined, prog("turnieje", 20)],
  ["Zdobądź 8 mln dolarów łącznych wygranych", undefined, prog("wyniki", 11)],
  // 86-99 · Elita
  ["Osiągnij czołową 20 rankingu krajowego"],
  ["Zdobądź 10 mln dolarów łącznych wygranych", undefined, prog("wyniki", 12)],
  ["Wygraj duży turniej rangi krajowej lub międzynarodowej", undefined, prog("turnieje", 21)],
  ["Zdobądź nagrodę gracza roku swojego regionu"],
  ["Rozegraj 5 000 000 rozdań łącznie", undefined, prog("rozdania", 5000000)],
  ["Osiągnij czołową dziesiątkę rankingu krajowego"],
  ["Wygraj jeden z największych turniejów, w jakich grałeś", undefined, prog("turnieje", 22)],
  ["Zdobądź 20 mln dolarów łącznych wygranych", undefined, prog("wyniki", 13)],
  ["Zdobądź wiele tytułów turniejowych rangi krajowej", undefined, prog("turnieje", 23)],
  ["Zostań numerem 1 rankingu krajowego"],
  ["Zdobądź 30 mln dolarów łącznych wygranych", undefined, prog("wyniki", 14)],
  ["Zbuduj solidny, wieloletni dorobek turniejowy"],
  ["Zdobądź uznanie w krajowym środowisku pokerowym"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat turniejowy", "Dalsze, zawodowe osiągnięcia (WSOP, Hall of Fame) potwierdzają osobne certyfikaty."],
]);
