// Music production ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, track counts scaled; top tiers reframed as
// attainable mastery, real feats left to future certificates).
// Tracks: umiejetnosci, utwory (finished tracks), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "produkcja-muzyczna",
  name: "Produkcja muzyczna",
  icon: "🎹",
  description:
    "Tworzenie muzyki w komputerze (DAW) — od pierwszego beatu po zmasterowany utwór. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → wydania i miks → dojrzały, autorski styl.",
  sortOrder: 100,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Poznaj DAW: ścieżki, transport, siatka, nagrywanie", undefined, prog("umiejetnosci", 1)],
  ["Zaprogramuj prosty beat perkusyjny", undefined, prog("umiejetnosci", 2)],
  ["Dodaj linię basu i akordy (pierwsza pętla)", undefined, prog("umiejetnosci", 3)],
  ["Ułóż melodię na wirtualnym instrumencie", undefined, prog("umiejetnosci", 4)],
  ["Zbuduj 8-taktową pętlę, która „gra”", undefined, prog("umiejetnosci", 5)],
  ["Rozbuduj pętlę w krótki utwór (intro–zwrotka–refren)", undefined, prog("umiejetnosci", 6)],
  ["Wyeksportuj (bounce) utwór do pliku audio", undefined, prog("umiejetnosci", 7)],
  ["Ukończ pierwszy utwór od początku do końca", undefined, prog("utwory", 1)],
  ["Ukończ 3 utwory", undefined, prog("utwory", 3)],
  ["Produkuj łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Produkuj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Opanuj podstawy aranżacji (budowanie napięcia, drop)", undefined, prog("umiejetnosci", 8)],
  ["Używaj EQ i kompresji świadomie na ścieżkach", undefined, prog("umiejetnosci", 9)],
  ["Ukończ 8 utworów", undefined, prog("utwory", 8)],
  ["Opanuj sound design syntezatora (od podstaw zbuduj brzmienie)", undefined, prog("umiejetnosci", 10)],
  ["Produkuj łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Zbuduj czytelny miks (każdy element słychać, balans)", undefined, prog("umiejetnosci", 11)],
  ["Ukończ 14 utworów", undefined, prog("utwory", 14)],
  ["Użyj automatyzacji (zmiany parametrów w czasie)", undefined, prog("umiejetnosci", 12)],
  ["Opanuj przestrzeń miksu (pogłos, delay, panorama)", undefined, prog("umiejetnosci", 13)],
  ["Nagraj i wyedytuj wokal / instrument akustyczny", undefined, prog("umiejetnosci", 14)],
  ["Produkuj łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Opanuj sidechain i groove (spójny, „oddychający” miks)", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 22 utwory", undefined, prog("utwory", 22)],
  ["Zrób prosty mastering (głośność, ton, limiter)", undefined, prog("umiejetnosci", 16)],
  // 26-45 · Średniozaawansowany
  ["Produkuj regularnie przez 8 kolejnych tygodni", undefined, freq(3, 8)],
  ["Opanuj zaawansowaną aranżację (pełny utwór)", undefined, prog("umiejetnosci", 17)],
  ["Zbuduj profesjonalnie brzmiący miks (klarowność, głębia)", undefined, prog("umiejetnosci", 18)],
  ["Ukończ 32 utwory", undefined, prog("utwory", 32)],
  ["Opanuj zaawansowany sound design (warstwy, modulacja, tekstura)", undefined, prog("umiejetnosci", 19)],
  ["Produkuj łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Zmasteruj utwór do poziomu komercyjnego (głośność + ton)", undefined, prog("umiejetnosci", 20)],
  ["Wyprodukuj utwór dla wokalisty / z gościem", undefined, prog("umiejetnosci", 21)],
  ["Opanuj wybrany gatunek na wysokim poziomie", undefined, prog("umiejetnosci", 22)],
  ["Ukończ 45 utworów", undefined, prog("utwory", 45)],
  ["Zbuduj rozpoznawalny, autorski styl brzmieniowy", undefined, prog("umiejetnosci", 23)],
  ["Produkuj łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Wyprodukuj utwór na poziomie wydawniczym (release-ready)", undefined, prog("umiejetnosci", 24)],
  ["Ukończ 60 utworów", undefined, prog("utwory", 60)],
  ["Zremiksuj lub wyprodukuj cover na wysokim poziomie", undefined, prog("umiejetnosci", 25)],
  ["Produkuj łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Wyprodukuj spójne EP / mini-album", undefined, prog("umiejetnosci", 26)],
  ["Ukończ 80 utworów", undefined, prog("utwory", 80)],
  ["Produkuj regularnie przez 3 miesiące", undefined, prog("utwory", 95)],
  // 46-65 · Zaawansowany (amator)
  ["Produkuj regularnie przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Opublikuj utwór na platformach (Spotify / SoundCloud)"],
  ["Zbuduj słuchaczy / grono odbiorców (streaming, social)"],
  ["Ukończ 110 utworów", undefined, prog("utwory", 110)],
  ["Produkuj łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Wyprodukuj utwór w kilku gatunkach na wysokim poziomie", undefined, prog("umiejetnosci", 27)],
  ["Opanuj mistrzowski miks (poziom radiowy / klubowy)", undefined, prog("umiejetnosci", 28)],
  ["Ukończ 140 utworów", undefined, prog("utwory", 140)],
  ["Wydaj muzykę z realnym zasięgiem (wytwórnia lub własny nakład)", undefined, prog("umiejetnosci", 29)],
  ["Produkuj łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Wygraj lub wyróżnij się w konkursie / na wydawnictwie"],
  ["Sprzedaj beat / zdobądź pierwsze płatne zlecenie"],
  ["Opanuj mastering na poziomie profesjonalnym", undefined, prog("umiejetnosci", 30)],
  ["Ukończ 175 utworów", undefined, prog("utwory", 175)],
  ["Realizuj płatne produkcje / zlecenia regularnie", undefined, prog("umiejetnosci", 31)],
  ["Produkuj łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy produkcji"],
  ["Wyprodukuj album dla artysty lub własny", undefined, prog("umiejetnosci", 32)],
  ["Wydaj pełny album o wyraźnej koncepcji"],
  ["Ukończ 210 utworów", undefined, prog("utwory", 210)],
  ["Zrealizuj spójny cykl / serię utworów wokół jednego pomysłu"],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Produkuj regularnie przez pełny sezon (6 miesięcy)"],
  ["Produkuj swobodnie w wielu gatunkach na wysokim poziomie", undefined, prog("umiejetnosci", 33)],
  ["Ukończ 260 utworów", undefined, prog("utwory", 260)],
  ["Produkuj łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Twój utwór osiąga zauważalne zasięgi / trafia na playlisty"],
  ["Rozwiń warsztat na tyle, by uczyć produkcji", undefined, prog("umiejetnosci", 34)],
  ["Zbuduj rozpoznawalny katalog o spójnym brzmieniu"],
  ["Regularnie realizujesz płatne produkcje"],
  ["Opanuj każdy etap produkcji na wysokim poziomie", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 320 utworów", undefined, prog("utwory", 320)],
  ["Zdobądź wyróżnienie lub uznanie w społeczności producentów"],
  ["Produkuj łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny album autorski", undefined, prog("umiejetnosci", 36)],
  ["Twoje brzmienie jest dojrzałe i rozpoznawalne", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 390 utworów", undefined, prog("utwory", 390)],
  ["Zbuduj markę o zasięgu ponadlokalnym"],
  ["Poprowadź warsztaty lub mentoring dla producentów"],
  ["Publikuj kursy lub tutoriale produkcji"],
  ["Wydaj kolejny album / rozbuduj dorobek"],
  ["Ukończ 460 utworów", undefined, prog("utwory", 460)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Produkuj łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdym utworze"],
  ["Ukończ 540 utworów", undefined, prog("utwory", 540)],
  ["Zbuduj bogaty, spójny katalog o autorskim charakterze"],
  ["Twoje brzmienie inspiruje innych producentów w Twoim otoczeniu"],
  ["Zrealizuj osobisty „opus” — album lub duży projekt", undefined, prog("umiejetnosci", 38)],
  ["Regularnie wydajesz muzykę lub realizujesz duże produkcje"],
  ["Produkuj łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje produkcje zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 640 utworów", undefined, prog("utwory", 640)],
  ["Uczysz i kształtujesz kolejnych producentów", undefined, prog("umiejetnosci", 39)],
  ["Masz dorobek, z którego można ułożyć retrospektywę"],
  ["Wyprodukujesz niemal każdy utwór, jaki sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski styl", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty.", prog("umiejetnosci", 40)],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (produkcja w DAW: JustinGuitar, Cubase, Produce Like A Pro i in.).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  // — Rozszerzenie zasobów Tier 1 (wszystkie linki zweryfikowane jako aktywne) —
  5: [{ kind: "video", title: "Jak zbudować 8-taktową pętlę", url: yt("wuCGMOQyles") }],
  6: [{ kind: "video", title: "Od pętli do pełnej struktury utworu", url: yt("ltiXacTxmUg") }],
  7: [{ kind: "video", title: "Ustawienia eksportu (bounce): sample rate, bit, dither", url: yt("Bi1sU2Iyer0") }],
  8: [{ kind: "video", title: "Jak wreszcie kończyć swoje utwory", url: yt("UFpZy7X1ZOg") }],
  10: [{ kind: "video", title: "Skróty klawiszowe DAW — przyspiesz pracę", url: yt("u23C1AU_8NU") }],
  11: [{ kind: "video", title: "5 rzeczy, które pomogły mi kończyć więcej utworów", url: yt("t7by48WmueA") }],
  14: [{ kind: "video", title: "Sound design 101: oscylatory, filtry, obwiednie, LFO", url: yt("MVDxvSN0kas") }],
  16: [{ kind: "video", title: "Podstawy miksu dla początkujących", url: yt("NWw9S4pPrtc") }],
  18: [{ kind: "video", title: "Automatyzacja w DAW od podstaw (FL Studio)", url: yt("RoMq8FhYKGk") }],
  22: [{ kind: "video", title: "Sidechain — kompresja pod stopę wyjaśniona", url: yt("QUUCRCVll3k") }],
  24: [{ kind: "video", title: "Mastering dla początkujących — krok po kroku", url: yt("99ABUkzpPH4") }],
  30: [{ kind: "video", title: "Zaawansowany miks od zera (masterclass)", url: yt("mVdgolJWqV4") }],
  1: [{ kind: "video", title: "Czym jest DAW — podstawy", url: yt("rqwfZB9QFPI") }],
  2: [{ kind: "video", title: "Programowanie beatu perkusyjnego", url: yt("dgt8EgI0ECM") }],
  3: [{ kind: "video", title: "Akordy i linia basu", url: yt("iBdzc4GhSgQ") }],
  4: [{ kind: "video", title: "Pisanie melodii", url: yt("OQBYMsi5yBM") }],
  12: [{ kind: "video", title: "Aranżacja i struktura utworu", url: yt("YGkgkL5h8bs") }],
  13: [{ kind: "video", title: "EQ i kompresja — podstawy", url: yt("PM7g_nkJHBw") }],
  15: [{ kind: "video", title: "Sound design syntezatora", url: yt("TXCqlquaIiw") }],
  17: [{ kind: "video", title: "Miks utworu od zera (workflow)", url: yt("aKrF2dra1S0") }],
  19: [{ kind: "video", title: "Automatyzacja parametrów", url: yt("vPUn-kn-bcA") }],
  20: [{ kind: "video", title: "Przestrzeń miksu: pogłos i delay", url: yt("Yd7IoR_Du_8") }],
  21: [{ kind: "video", title: "Nagrywanie wokalu w domu", url: yt("ME15aPMqqEs") }],
  23: [{ kind: "video", title: "Sidechain (kompresja pod stopę)", url: yt("6AvqoFSk2S8") }],
  25: [{ kind: "video", title: "Mastering dla początkujących", url: yt("V_aCU0NXZ68") }],
};
