// Rugby ladder 1-99. Manual — progression tracks: matches played, tries
// scored (total), competition level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "rugby",
  name: "Rugby",
  icon: "🏉",
  description:
    "Od podstaw podania po ligowe boiska i reprezentację. Progresja: rozegrane mecze, przyłożenia i poziom rozgrywek.",
  sortOrder: 33,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Wykonaj poprawne podanie do tyłu (rugby pass)", undefined, prog("technika", 1)],
  ["Złap wysoką piłkę w biegu", undefined, prog("technika", 2)],
  ["Wykonaj poprawny przyklęk z piłką (bezpieczne padnięcie)", undefined, prog("technika", 3)],
  ["Wykonaj bezpieczne wejście w kontakt (technika szarży)", undefined, prog("technika", 4)],
  ["Wykonaj poprawny tackle (obalenie) na tarczy", undefined, prog("technika", 5)],
  ["Zagraj w gniotku/rucku zgodnie z przepisami", undefined, prog("technika", 6)],
  ["Kopnij piłkę zza ręki (punt) na dystans", undefined, prog("technika", 7)],
  ["Zagraj pierwszy mecz treningowy (touch lub kontakt)", undefined, prog("mecze", 1)],
  ["Zdobądź pierwsze przyłożenie (try)", undefined, prog("przylozenia", 1)],
  ["Rozegraj pełny mecz 15-osobowy lub 7-osobowy", undefined, prog("mecze", 2)],
  // 11-25 · Regularny
  ["Trenuj lub graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Wykonaj skuteczny offload (podanie w kontakcie)", undefined, prog("technika", 8)],
  ["Zagraj 5 meczów", undefined, prog("mecze", 5)],
  ["Zdobądź 3 przyłożenia łącznie", undefined, prog("przylozenia", 3)],
  ["Wykonaj skuteczny tackle w meczu na przeciwniku w biegu", undefined, prog("technika", 9)],
  ["Zagraj na wyznaczonej pozycji (młynak lub atak) przez cały mecz"],
  ["Zagraj 10 meczów", undefined, prog("mecze", 10)],
  ["Zdobądź 6 przyłożeń łącznie", undefined, prog("przylozenia", 6)],
  ["Weź udział we wprowadzeniu piłki w młyn (scrum) lub aut (lineout)", undefined, prog("technika", 10)],
  ["Rozegraj mecz w lidze amatorskiej", undefined, prog("liga", 1)],
  ["Zagraj 20 meczów", undefined, prog("mecze", 20)],
  ["Zdobądź 10 przyłożeń łącznie", undefined, prog("przylozenia", 10)],
  ["Wykonaj kopa na bramkę (podwyższenie lub karny)", undefined, prog("technika", 11)],
  ["Zdobądź 2 przyłożenia w jednym meczu", undefined, prog("przylozenia-mecz", 2)],
  ["Zagraj 30 meczów", undefined, prog("mecze", 30)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zdobądź 15 przyłożeń łącznie", undefined, prog("przylozenia", 15)],
  ["Opanuj grę w formacji ataku (linia z przełożeniami)", undefined, prog("technika", 12)],
  ["Zagraj 50 meczów", undefined, prog("mecze", 50)],
  ["Zdobądź 20 przyłożeń łącznie", undefined, prog("przylozenia", 20)],
  ["Rozegraj pełny sezon w regularnej lidze", undefined, prog("liga", 2)],
  ["Wykonaj skuteczny turnover (odbiór piłki w kontakcie)", undefined, prog("technika", 13)],
  ["Zdobądź 3 przyłożenia w jednym meczu (hat-trick)", undefined, prog("przylozenia-mecz", 3)],
  ["Zagraj 75 meczów", undefined, prog("mecze", 75)],
  ["Zdobądź 30 przyłożeń łącznie", undefined, prog("przylozenia", 30)],
  ["Zajmij miejsce w pierwszej połowie tabeli ligowej"],
  ["Kopnij skutecznie z gry (drop goal)", undefined, prog("technika", 14)],
  ["Zagraj 100 meczów", undefined, prog("mecze", 100)],
  ["Zdobądź 45 przyłożeń łącznie", undefined, prog("przylozenia", 45)],
  ["Rozegraj mecz w II lidze lub odpowiedniku", undefined, prog("liga", 3)],
  ["Zostań liderem zespołu w statystykach szarż lub metrów"],
  ["Zdobądź 60 przyłożeń łącznie", undefined, prog("przylozenia", 60)],
  ["Zagraj 150 meczów", undefined, prog("mecze", 150)],
  ["Poprowadź zespół jako kapitan w meczu ligowym"],
  ["Zdobądź 4 przyłożenia w jednym meczu", undefined, prog("przylozenia-mecz", 4)],
  // 46-65 · Zaawansowany
  ["Trenuj 4+ razy w tygodniu przez cały sezon"],
  ["Zdobądź 80 przyłożeń łącznie", undefined, prog("przylozenia", 80)],
  ["Rozegraj mecz w I lidze", undefined, prog("liga", 4)],
  ["Zagraj 200 meczów", undefined, prog("mecze", 200)],
  ["Zdobądź 100 przyłożeń łącznie", undefined, prog("przylozenia", 100)],
  ["Zostań podstawowym zawodnikiem zespołu I-ligowego"],
  ["Zajmij miejsce w czołówce I ligi"],
  ["Zagraj 250 meczów", undefined, prog("mecze", 250)],
  ["Zdobądź 130 przyłożeń łącznie", undefined, prog("przylozenia", 130)],
  ["Zdobądź 5 przyłożeń w jednym meczu", undefined, prog("przylozenia-mecz", 5)],
  ["Awansuj z drużyną do wyższej klasy rozgrywek"],
  ["Zdobądź 160 przyłożeń łącznie", undefined, prog("przylozenia", 160)],
  ["Zagraj 300 meczów", undefined, prog("mecze", 300)],
  ["Zostań najlepszym zdobywcą przyłożeń rundy w lidze"],
  ["Zdobądź 190 przyłożeń łącznie", undefined, prog("przylozenia", 190)],
  ["Zagraj w najwyższej lidze krajowej (Ekstraliga)", undefined, prog("liga", 5)],
  ["Zdobądź przyłożenie w meczu najwyższej ligi"],
  ["Zdobądź 220 przyłożeń łącznie", undefined, prog("przylozenia", 220)],
  ["Zagraj 400 meczów", undefined, prog("mecze", 400)],
  ["Zostań rozpoznawalnym zawodnikiem w swoim regionie"],
  // 66-85 · Wyczynowy
  ["Zdobądź 250 przyłożeń łącznie", undefined, prog("przylozenia", 250)],
  ["Zagraj 500 meczów", undefined, prog("mecze", 500)],
  ["Zostań podstawowym zawodnikiem Ekstraligi"],
  ["Zdobądź 280 przyłożeń łącznie", undefined, prog("przylozenia", 280)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Zagraj 600 meczów", undefined, prog("mecze", 600)],
  ["Zdobądź 310 przyłożeń łącznie", undefined, prog("przylozenia", 310)],
  ["Zostań uznanym zawodnikiem swojej ligi regionalnej"],
  ["Zdobądź 340 przyłożeń łącznie", undefined, prog("przylozenia", 340)],
  ["Zagraj 700 meczów", undefined, prog("mecze", 700)],
  ["Zdobądź przyłożenie w ważnym meczu ligowym"],
  ["Zdobądź 370 przyłożeń łącznie", undefined, prog("przylozenia", 370)],
  ["Zagraj w rozgrywkach międzynarodowych klubowych (np. Challenge Cup)"],
  ["Zdobądź 400 przyłożeń łącznie", undefined, prog("przylozenia", 400)],
  ["Zagraj 800 meczów", undefined, prog("mecze", 800)],
  ["Zdobądź podium mistrzostw regionu z klubem"],
  ["Zagraj w turnieju o zasięgu ogólnokrajowym"],
  ["Zdobądź 430 przyłożeń łącznie", undefined, prog("przylozenia", 430)],
  ["Zagraj 900 meczów", undefined, prog("mecze", 900)],
  ["Zostań kapitanem swojej drużyny klubowej"],
  // 86-99 · Elita
  ["Zdobądź 460 przyłożeń łącznie", undefined, prog("przylozenia", 460)],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zagraj 1000 meczów", undefined, prog("mecze", 1000)],
  ["Zdobądź 500 przyłożeń łącznie", undefined, prog("przylozenia", 500)],
  ["Zdobądź przyłożenie w ważnym meczu ligowym"],
  ["Awansuj z klubem do wyższej klasy rozgrywkowej"],
  ["Zostań czołowym zawodnikiem swojej pozycji w lidze"],
  ["Zagraj w finale rozgrywek ligowych"],
  ["Zdobądź przyłożenie w finale rozgrywek ligowych"],
  ["Zdobądź trofeum swojej ligi klubowej"],
  ["Znajdź się w składzie gwiazd sezonu swojej ligi"],
  ["Poprowadź drużynę jako lider / kapitan przez sezon"],
  ["Wygraj mistrzostwo swojej ligi klubowej"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej drużyny klubowej", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);
