// Drawing ladder 1-99 — REALISTIC personal-progression scale (achievable for a
// dedicated hobbyist; real-world feats like exhibitions stay as future
// certificate anchors, not gated behind fame or 10k+ hours).
// Tracks: umiejetnosci (skill), prace (finished drawings), godziny (practice
// hours, capped ~1200). Grounded in the Love Life Drawing beginner roadmap.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "rysowanie",
  name: "Rysowanie ołówkiem",
  icon: "✏️",
  description:
    "Rysunek od podstaw — kreska, bryła, walor, perspektywa, postać. Poziomy 1–99 to realna droga zaangażowanego amatora: fundamenty → dorobek i godziny → wystawy i uznanie → dojrzały warsztat.",
  sortOrder: 81,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Prowadź pewne, płynne kreski (proste i łuki) bez „kudłacenia”", undefined, prog("umiejetnosci", 1)],
  ["Narysuj podstawowe kształty 2D: koło, kwadrat, elipsa", undefined, prog("umiejetnosci", 2)],
  ["Kontroluj nacisk ołówka — od jasnej do ciemnej kreski", undefined, prog("umiejetnosci", 3)],
  ["Narysuj bryły 3D: sześcian, kula, walec, stożek", undefined, prog("umiejetnosci", 4)],
  ["Zacieniuj kulę z jednym źródłem światła (gradient)", undefined, prog("umiejetnosci", 5)],
  ["Narysuj z obserwacji prosty przedmiot (kubek, jabłko)", undefined, prog("prace", 3)],
  ["Zbuduj skalę walorową (5-8 stopni szarości)", undefined, prog("umiejetnosci", 6)],
  ["Odwzoruj proporcje przedmiotu metodą pomiaru ołówkiem", undefined, prog("umiejetnosci", 7)],
  ["Ukończ 10 rysunków", undefined, prog("prace", 10)],
  ["Przećwicz rysowanie łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Rysuj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Narysuj martwą naturę z kilku obiektów z cieniami", undefined, prog("prace", 15)],
  ["Opanuj perspektywę zbieżną 1-punktową", undefined, prog("umiejetnosci", 8)],
  ["Zacieniuj przedmiot z fakturą (metal, tkanina, szkło)", undefined, prog("umiejetnosci", 9)],
  ["Opanuj perspektywę 2-punktową (pudełka, wnętrza)", undefined, prog("umiejetnosci", 10)],
  ["Przećwicz rysowanie łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Narysuj dłoń z obserwacji", undefined, prog("umiejetnosci", 11)],
  ["Ukończ 30 rysunków", undefined, prog("prace", 30)],
  ["Wykonaj szybkie szkice gestu postaci (30-60 s)", undefined, prog("umiejetnosci", 12)],
  ["Narysuj proporcje głowy metodą Loomisa (konstrukcja)", undefined, prog("umiejetnosci", 13)],
  ["Prowadź szkicownik codziennie przez 2 tygodnie", undefined, prog("prace", 45)],
  ["Opanuj perspektywę 3-punktową (widok z góry/dołu)", undefined, prog("umiejetnosci", 14)],
  ["Przećwicz rysowanie łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Narysuj portret z fotografii z uchwyceniem podobieństwa", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 60 rysunków", undefined, prog("prace", 60)],
  // 26-45 · Średniozaawansowany
  ["Rysuj regularnie przez 8 kolejnych tygodni", undefined, freq(3, 8)],
  ["Opanuj konstrukcję postaci (mankin, proporcje ciała)", undefined, prog("umiejetnosci", 16)],
  ["Narysuj pełną postać z obserwacji (sesja modela/foto)", undefined, prog("umiejetnosci", 17)],
  ["Ukończ 90 rysunków", undefined, prog("prace", 90)],
  ["Opanuj światłocień na twarzy (portret z natury)", undefined, prog("umiejetnosci", 18)],
  ["Przećwicz rysowanie łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Narysuj scenę z perspektywą i figurami w przestrzeni", undefined, prog("umiejetnosci", 19)],
  ["Opanuj fakturę i materiały w rysunku (skóra, włosy, tkanina)", undefined, prog("umiejetnosci", 20)],
  ["Ukończ 130 rysunków", undefined, prog("prace", 130)],
  ["Rysuj z wyobraźni prosty obiekt bez referencji", undefined, prog("umiejetnosci", 21)],
  ["Opanuj kompozycję kadru (rozmieszczenie, prowadzenie wzroku)", undefined, prog("umiejetnosci", 22)],
  ["Przećwicz rysowanie łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Narysuj serię szkiców z życia (kawiarnia, park, ludzie)", undefined, prog("prace", 170)],
  ["Opanuj dynamiczną pozę i ruch postaci (gest + konstrukcja)", undefined, prog("umiejetnosci", 23)],
  ["Zbuduj spójny, dopracowany rysunek portretowy", undefined, prog("umiejetnosci", 24)],
  ["Ukończ 200 rysunków", undefined, prog("prace", 200)],
  ["Opanuj różne media suche (węgiel, sangwina, kredka)", undefined, prog("umiejetnosci", 25)],
  ["Przećwicz rysowanie łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Narysuj złożoną martwą naturę z pełnym światłocieniem", undefined, prog("umiejetnosci", 26)],
  ["Prowadź szkicownik regularnie przez 3 miesiące", undefined, prog("prace", 250)],
  // 46-65 · Zaawansowany (amator)
  ["Rysuj regularnie przez 12 kolejnych tygodni", undefined, freq(3, 12)],
  ["Opanuj anatomię na poziomie użytkowym (mięśnie, ruch)", undefined, prog("umiejetnosci", 27)],
  ["Zbuduj spójną serię tematyczną (5-10 prac)", undefined, prog("umiejetnosci", 28)],
  ["Ukończ 300 rysunków", undefined, prog("prace", 300)],
  ["Przećwicz rysowanie łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Wypracuj rozpoznawalny, osobisty sposób rysowania", undefined, prog("umiejetnosci", 29)],
  ["Pokaż prace publicznie (online / lokalnie) i zbierz opinie"],
  ["Narysuj ambitną, wieloelementową kompozycję figuralną", undefined, prog("umiejetnosci", 30)],
  ["Ukończ 400 rysunków", undefined, prog("prace", 400)],
  ["Opanuj rysunek reportażowy / urban sketching w terenie", undefined, prog("umiejetnosci", 31)],
  ["Przećwicz rysowanie łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj portfolio najlepszych prac (kilkanaście sztuk)"],
  ["Weź udział w wystawie zbiorowej lub konkursie rysunku"],
  ["Opanuj świadomą stylizację (realizm ↔ uproszczenie)", undefined, prog("umiejetnosci", 32)],
  ["Ukończ 500 rysunków", undefined, prog("prace", 500)],
  ["Zrealizuj rysunek na zamówienie / sprzedaj pierwszą pracę"],
  ["Przećwicz rysowanie łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy rysunku (pokaż, wytłumacz)", undefined, prog("umiejetnosci", 33)],
  ["Zbuduj spójny cykl prac wokół jednego pomysłu"],
  ["Narysuj dopracowany, „galeryjny” portret lub scenę", undefined, prog("umiejetnosci", 34)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Rysuj regularnie przez pełny sezon (6 miesięcy)"],
  ["Opanuj rysunek z wyobraźni złożonych scen i postaci", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 650 rysunków", undefined, prog("prace", 650)],
  ["Przećwicz rysowanie łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zorganizuj małą wystawę indywidualną (lokalnie / online)"],
  ["Rozwiń warsztat na tyle, by uczyć innych (warsztat / kurs)", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie realizuj zlecenia / sprzedajesz prace"],
  ["Opanuj wybraną specjalizację (portret / postać / komiks / concept)", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 800 rysunków", undefined, prog("prace", 800)],
  ["Zdobądź wyróżnienie w konkursie lub uznanie w społeczności"],
  ["Prowadź szkicownik nieprzerwanie przez rok"],
  ["Przećwicz rysowanie łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny, wieloczęściowy projekt autorski", undefined, prog("umiejetnosci", 38)],
  ["Twoje prace są dojrzałe i rozpoznawalne bez podpisu"],
  ["Ukończ 1000 rysunków", undefined, prog("prace", 1000)],
  ["Zbuduj społeczność / grono odbiorców swojej twórczości"],
  ["Poprowadź serię zajęć lub mentoring dla początkujących"],
  ["Opanuj rysunek na poziomie łączenia realizmu i ekspresji", undefined, prog("umiejetnosci", 39)],
  ["Zrealizuj wystawę lub publikację prezentującą dorobek"],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Przećwicz rysowanie łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdej pracy"],
  ["Ukończ 1300 rysunków", undefined, prog("prace", 1300)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych rysujących w Twoim otoczeniu"],
  ["Zrealizuj osobisty „opus” — dużą, dopracowaną pracę lub cykl", undefined, prog("umiejetnosci", 40)],
  ["Regularnie wystawiasz lub publikujesz swoje prace"],
  ["Przećwicz rysowanie łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoja praca zdobywa uznanie poza lokalną społecznością"],
  ["Ukończ 1600 rysunków", undefined, prog("prace", 1600)],
  ["Uczysz i kształtujesz kolejnych rysowników"],
  ["Masz dorobek, z którego można ułożyć wystawę retrospektywną"],
  ["Rysujesz swobodnie wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, samodzielny warsztat", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete skill/technique
// milestones (count/hours/exhibition levels intentionally have none). Mix of
// videos (Proko, Circle Line, Sycra…) and free courses (Drawabox, Ctrl+Paint).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  // — Rozszerzenie zasobów Tier 1 (wszystkie linki zweryfikowane jako aktywne) —
  9: [{ kind: "video", title: "Jak zbudować nawyk codziennego rysowania", url: yt("VLg-yfGvVDw") }],
  10: [{ kind: "video", title: "10 ćwiczeń, które szybko poprawią rysunek (Marc Brunet)", url: yt("C87ZXHPQkh0") }],
  11: [{ kind: "video", title: "Jak skutecznie ćwiczyć rysunek — pełny poradnik", url: yt("rVbqw5fMLJY") }],
  14: [{ kind: "video", title: "Jak rysować dynamiczne fałdy tkaniny (Jazza x Proko)", url: yt("5dpD8mDH1Pk") }],
  16: [{ kind: "video", title: "Perspektywa 1-, 2- i 3-punktowa — kompletny kurs", url: yt("1miyDqc0bsg") }],
  18: [{ kind: "video", title: "Jak wypracować własny styl rysowania", url: yt("DHzJMa_pqPY") }],
  21: [{ kind: "video", title: "Jak zacząć szkicownik — materiały, techniki, nawyki", url: yt("r4vCXI0IliQ") }],
  22: [{ kind: "video", title: "Perspektywa 3-punktowa krok po kroku", url: yt("EPBaHkj753I") }],
  25: [{ kind: "video", title: "Rysowanie iteracyjne — najszybsza droga do postępu (Sycra)", url: yt("k0ufz75UvHs") }],
  1: [{ kind: "course", title: "Drawabox — Lekcja 1: kreski i bryły", url: "https://drawabox.com/lesson/1" }],
  4: [{ kind: "video", title: "Bryły 3D — rysunek i cieniowanie", url: yt("cBNc12M2_Yc") }],
  5: [{ kind: "video", title: "Cieniowanie kuli — światło i cień", url: yt("uM-gJrczaRE") }],
  6: [{ kind: "course", title: "Ctrl+Paint — rysunek z obserwacji", url: "https://www.ctrlpaint.com/videos/drawing-shape-simple-still-life" }],
  7: [{ kind: "video", title: "Skala walorowa — ćwiczenie", url: yt("qNju05AR3Kc") }],
  8: [{ kind: "video", title: "Pomiar proporcji (Proko)", url: yt("1J7RQvKnWf4") }],
  13: [{ kind: "video", title: "Perspektywa 1-punktowa", url: yt("qJwaLkDP4xM") }],
  15: [{ kind: "video", title: "Perspektywa 2-punktowa", url: yt("M6MOIP_mLsc") }],
  17: [{ kind: "video", title: "Jak rysować dłonie (Proko)", url: yt("RR19RX3gnH4") }],
  19: [{ kind: "video", title: "Rysunek gestu (Proko)", url: yt("8j39NqwL7s4") }],
  20: [{ kind: "video", title: "Głowa metodą Loomisa (Proko)", url: yt("wAOldLWIDSM") }],
  24: [{ kind: "video", title: "Konstrukcja i cieniowanie twarzy (Proko)", url: yt("PHR7T9N_jAY") }],
  27: [{ kind: "video", title: "Konstrukcja postaci — mankin (Proko)", url: yt("nRHfcqjbPq8") }],
  30: [{ kind: "video", title: "Światło na formie — cieniowanie (Proko)", url: yt("V3WmrWUEIJo") }],
  33: [{ kind: "video", title: "Rysowanie faktur ołówkiem", url: yt("S3DCx0TzNRw") }],
  47: [{ kind: "video", title: "Anatomia dla artystów (Proko)", url: yt("pDgyQjNFVQk") }],
};
