// Volleyball ladder 1-99. Tracks: overhead/forearm passing (consecutive
// touches), serving accuracy (out of 10), match experience. Manual check-offs.
import type { Criterion } from "../../src/lib/milestone-criteria";
import type { MilestoneResource } from "../../src/lib/milestone-resources";
import { ladder, freq, prog } from "./helpers";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "siatkowka",
  name: "Siatkówka",
  icon: "🏐",
  description:
    "Odbicia, zagrywka, atak i blok — od pierwszych odbić po ligowe hale. Serie zagrywek licz z 10 prób.",
  sortOrder: 9,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Wykonaj odbicie górne (overhand pass) 5 razy z rzędu (nad sobą)"],
  ["Odbij piłkę sposobem dolnym 5 razy z rzędu"],
  ["Wykonaj odbicie górne (overhand pass) 10 razy z rzędu"],
  ["Przebij zagrywkę dolną przez siatkę"],
  ["Odbij sposobem dolnym 10 razy z rzędu"],
  ["Traf zagrywką dolną w boisko 5/10"],
  ["Odbij naprzemiennie góra-dół 10 razy"],
  ["Wykonaj odbicie górne (overhand pass) 25 razy z rzędu"],
  ["Zagraj pierwszy mecz (plaża, hala, rekreacja)"],
  ["Przebij zagrywkę tenisową (górną) przez siatkę"],
  // 11-25 · Regularny
  ["Graj lub trenuj raz w tygodniu przez 4 kolejne tygodnie"],
  ["Odbij sposobem dolnym 25 razy z rzędu"],
  ["Traf zagrywką tenisową w boisko 5/10"],
  ["Wystaw piłkę partnerowi do ataku (celna wystawa 5 razy z rzędu)"],
  ["Zagraj 5 meczów"],
  ["Wykonaj odbicie górne (overhand pass) 50 razy z rzędu"],
  ["Przyjmij zagrywkę na wystawę (dokładne dojście do rozgrywającego)"],
  ["Traf zagrywką w boisko 7/10"],
  ["Zagraj 10 meczów"],
  ["Wykonaj atak (kiwnięcie lub zbicie) punktowy w meczu"],
  ["Odbijaj w parze bez upadku piłki 20 wymian"],
  ["Odbij sposobem dolnym 50 razy z rzędu"],
  ["Graj 2 razy w tygodniu przez 8 kolejnych tygodni"],
  ["Zbij piłkę z wystawienia partnera (set) na treningu"],
  ["Zagraj 20 meczów"],
  // 26-45 · Średniozaawansowany
  ["Traf zagrywką w wybraną połowę boiska 6/10", "Zagrywka kierunkowa — początek taktyki."],
  ["Wykonaj odbicie górne (overhand pass) 100 razy z rzędu"],
  ["Zbij skutecznie w meczu 3 razy"],
  ["Wykonaj pojedynczy blok w meczu"],
  ["Zagraj 35 meczów"],
  ["Traf zagrywką w boisko 9/10", "Niemal bezbłędna seria."],
  ["Przyjmij 10 zagrywek z rzędu bez błędu na treningu"],
  ["Opanuj zagrywkę flot (bez rotacji)"],
  ["Zagraj 50 meczów"],
  ["Wystaw piłkę z wyskoku"],
  ["Zdobądź 5 punktów zagrywką w jednym meczu (asy + błędy przyjęcia)"],
  ["Graj regularnie przez pełny sezon (6+ miesięcy)"],
  ["Wykonaj skuteczny atak z drugiej linii (pipe/za trzecim metrem)"],
  ["Zablokuj atak przeciwnika punktowo 3 razy w jednym meczu"],
  ["Zagraj 75 meczów"],
  ["Opanuj zagrywkę z wyskoku (jump serve) — traf 3/10"],
  ["Odbij w parze 50 wymian bez upadku piłki"],
  ["Zagraj turniej siatkówki plażowej 2v2"],
  ["Zdobądź 10 punktów atakiem w jednym meczu"],
  ["Wygraj lokalny turniej amatorski ze swoją drużyną"],
  // 46-65 · Zaawansowany
  ["Zagraj 100 meczów", "Setka spotkań przy siatce."],
  ["Traf zagrywką z wyskoku 5/10"],
  ["Dołącz do drużyny w zorganizowanej lidze amatorskiej"],
  ["Wykonaj obronę w polu (dig) po mocnym ataku 3 razy w meczu"],
  ["Zagraj na wszystkich sześciu pozycjach rotacyjnych świadomie taktycznie"],
  ["Zdobądź 3 asy serwisowe w jednym meczu"],
  ["Zagraj 150 meczów"],
  ["Opanuj atak po bloku (wykorzystanie block-outu) w meczu"],
  ["Rozegraj cały mecz jako rozgrywający lub libero", "Specjalizacja pozycji."],
  ["Traf zagrywką z wyskoku 7/10"],
  ["Zagraj 200 meczów"],
  ["Zostań MVP meczu w swojej drużynie"],
  ["Wygraj sezon ligi amatorskiej ze swoją drużyną"],
  ["Zdobądź 20 punktów w jednym meczu (atak+blok+zagrywka)"],
  ["Zagraj turniej plażowy na poziomie eliminacji regionalnych"],
  ["Zagraj 250 meczów"],
  ["Zablokuj 5 ataków w jednym meczu"],
  ["Rozegraj 5 pełnych sezonów"],
  ["Zagraj mecz w rozgrywkach związkowych (PZPS, dowolna klasa)"],
  ["Zostań kapitanem drużyny na sezon"],
  // 66-85 · Wyczynowy
  ["Zagraj 300 meczów"],
  ["Zdobądź 5 asów serwisowych w jednym meczu"],
  ["Awansuj z drużyną do wyższej klasy rozgrywkowej"],
  ["Zagraj 30 oficjalnych meczów ligowych"],
  ["Zostań najlepiej punktującym zawodnikiem swojej ligi w sezonie"],
  ["Zagraj 400 meczów"],
  ["Wygraj turniej plażowy rangi regionalnej"],
  ["Rozegraj sezon jako podstawowy zawodnik III ligi lub wyżej"],
  ["Zagraj 500 meczów"],
  ["Zdobądź z drużyną medal mistrzostw regionu"],
  ["Zagraj 60 oficjalnych meczów ligowych"],
  ["Wygraj puchar okręgu lub równorzędne trofeum"],
  ["Zagraj na poziomie II ligi"],
  ["Zagraj 600 meczów"],
  ["Rozegraj 100 oficjalnych meczów ligowych"],
  ["Zdobądź 25 punktów w meczu związkowym"],
  ["Zagraj turniej plażowy rangi ogólnopolskiej"],
  ["Rozegraj 3 sezony na poziomie związkowym"],
  ["Zagraj 700 meczów"],
  ["Zostań MVP sezonu swojej ligi"],
  // 86-99 · Elita
  ["Zagraj na poziomie I ligi", "Wysoki poziom ligowy."],
  ["Zagraj 800 meczów"],
  ["Zostań kluczowym zawodnikiem swojej drużyny przez cały sezon"],
  ["Zdobądź podium regionalnych mistrzostw w kategorii wiekowej lub amatorskiej"],
  ["Rozegraj 150 oficjalnych meczów ligowych"],
  ["Wygraj turniej regionalny (hala lub plaża)"],
  ["Zagraj 900 meczów"],
  ["Rozegraj pełny sezon I ligi jako podstawowy zawodnik"],
  ["Wystąp w rozgrywkach pucharu na szczeblu regionalnym"],
  ["Zagraj 1000 meczów", "Tysiąc spotkań przy siatce."],
  ["Poprowadź drużynę jako lider / kapitan przez sezon"],
  ["Zdobądź uznanie w lokalnej społeczności siatkarskiej"],
  ["Zdobądź trofeum na poziomie regionalnym"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, kluczowy zawodnik silnej amatorskiej drużyny", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  1: prog("gorne", 5), 3: prog("gorne", 10), 8: prog("gorne", 25), 16: prog("gorne", 50), 27: prog("gorne", 100),
  2: prog("dolne", 5), 5: prog("dolne", 10), 12: prog("dolne", 25), 22: prog("dolne", 50),
  6: prog("zagrywka", 5), 18: prog("zagrywka", 7), 31: prog("zagrywka", 9),
  41: prog("jump-serve", 3), 47: prog("jump-serve", 5), 55: prog("jump-serve", 7),
  9: prog("mecze", 1), 15: prog("mecze", 5), 19: prog("mecze", 10), 25: prog("mecze", 20),
  30: prog("mecze", 35), 34: prog("mecze", 50),
  40: prog("mecze", 75), 46: prog("mecze", 100), 52: prog("mecze", 150), 56: prog("mecze", 200),
  61: prog("mecze", 250), 66: prog("mecze", 300), 71: prog("mecze", 400), 74: prog("mecze", 500),
  79: prog("mecze", 600), 84: prog("mecze", 700), 87: prog("mecze", 800), 92: prog("mecze", 900),
  95: prog("mecze", 1000),
  21: prog("wymiany", 20), 42: prog("wymiany", 50),
  11: freq(1, 4), 23: freq(2, 8),
  // pozostałe: technika, wydarzenia i poziomy rozgrywkowe — manualne.
};

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Odbicie górne — overhand pass", url: yt("9-Ry8bGI1UQ") }],
  2: [{ kind: "video", title: "Odbicie dolne — forearm pass", url: yt("WXbr6H5YO8s") }],
  4: [{ kind: "video", title: "Zagrywka dolna — krok po kroku", url: yt("IxXl3vwQqzQ") }],
  10: [{ kind: "video", title: "Zagrywka tenisowa — overhand serve", url: yt("LEOPFzMhO8g") }],
  14: [{ kind: "video", title: "Wystawianie piłki — setting basics", url: yt("9ZMuOI1Nyns") }],
  20: [{ kind: "video", title: "Atak — spike technique", url: yt("Gz0BHjmD9K8") }],
  29: [{ kind: "video", title: "Blok — technika i timing", url: yt("R97l-0bnqjI") }],
  33: [{ kind: "video", title: "Zagrywka float — brak rotacji", url: yt("kWdxiIl5XcE") }],
  41: [{ kind: "video", title: "Jump serve — zagrywka z wyskoku", url: yt("gWqS9pxRryw") }],
  49: [{ kind: "video", title: "Obrona w polu — dig technique", url: yt("EKXIAKVFi0M") }],
  54: [{ kind: "article", title: "Pozycje w siatkówce — przewodnik", url: "https://www.wikihow.com/Play-Volleyball" }],
};
