// Jump rope ladder 1-99. Manual — progression tracks: consecutive single jumps,
// double-unders, trick skills, and competition/freestyle level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "skakanka",
  name: "Skakanka",
  icon: "🪢",
  description:
    "Od pierwszych podskoków po double-undery i freestyle. Progresja: powtórzenia pod rząd, double-unders, triki i poziom zawodów.",
  sortOrder: 64,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Wykonaj 10 podskoków pod rząd", undefined, prog("single", 10)],
  ["Opanuj rytm i technikę nadgarstków", undefined, prog("technika", 1)],
  ["Wykonaj 25 podskoków pod rząd", undefined, prog("single", 25)],
  ["Skacz na jednej nodze naprzemiennie (bieg w miejscu)", undefined, prog("technika", 2)],
  ["Wykonaj 50 podskoków pod rząd", undefined, prog("single", 50)],
  ["Wykonaj boxer step (podstawowy krok bokserski)", undefined, prog("technika", 3)],
  ["Wykonaj 75 podskoków pod rząd", undefined, prog("single", 75)],
  ["Skacz przez 1 minutę bez przerwy", undefined, prog("technika", 4)],
  ["Wykonaj 100 podskoków pod rząd", undefined, prog("single", 100)],
  ["Wykonaj pierwszy criss-cross (skrzyżowanie rąk)", undefined, prog("triki", 1)],
  // 11-25 · Regularny
  ["Trenuj 3 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Wykonaj 150 podskoków pod rząd", undefined, prog("single", 150)],
  ["Wykonaj pierwszy double-under (podwójny obrót na skok)", "Kamień milowy.", prog("double", 1)],
  ["Wykonaj 5 criss-crossów pod rząd", undefined, prog("triki", 2)],
  ["Wykonaj 200 podskoków pod rząd", undefined, prog("single", 200)],
  ["Wykonaj 5 double-unders pod rząd", undefined, prog("double", 5)],
  ["Skacz przez 3 minuty bez przerwy", undefined, prog("technika", 5)],
  ["Wykonaj side swing i otwarcie (podstawa freestyle)", undefined, prog("triki", 3)],
  ["Wykonaj 300 podskoków pod rząd", undefined, prog("single", 300)],
  ["Wykonaj 10 double-unders pod rząd", undefined, prog("double", 10)],
  ["Wykonaj EB (skrzyżowanie z tyłu — elephant)", undefined, prog("triki", 4)],
  ["Wykonaj 400 podskoków pod rząd", undefined, prog("single", 400)],
  ["Wykonaj 20 double-unders pod rząd", undefined, prog("double", 20)],
  ["Skacz przez 5 minut bez przerwy", undefined, prog("technika", 6)],
  ["Wykonaj 500 podskoków pod rząd", undefined, prog("single", 500)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 4 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(4, 12)],
  ["Wykonaj 30 double-unders pod rząd", undefined, prog("double", 30)],
  ["Wykonaj pierwszego triple-under (potrójny obrót)", undefined, prog("double", 35)],
  ["Wykonaj kombinację criss-cross + double-under", undefined, prog("triki", 5)],
  ["Wykonaj 700 podskoków pod rząd", undefined, prog("single", 700)],
  ["Wykonaj 50 double-unders pod rząd", undefined, prog("double", 50)],
  ["Osiągnij 150 podskoków w 30 sekund (tempo speed)", undefined, prog("technika", 7)],
  ["Wykonaj mic release (wypuszczenie i chwyt uchwytu)", undefined, prog("triki", 6)],
  ["Wykonaj 1000 podskoków pod rząd", undefined, prog("single", 1000)],
  ["Wykonaj 75 double-unders pod rząd", undefined, prog("double", 75)],
  ["Wykonaj 5 triple-unders pod rząd", undefined, prog("double", 80)],
  ["Zajmij miejsce w pierwszej połowie zawodów amatorskich"],
  ["Wykonaj TJ (toad — skrzyżowanie pod nogą)", undefined, prog("triki", 7)],
  ["Wykonaj 100 double-unders pod rząd", "Setka double-underów.", prog("double", 100)],
  ["Osiągnij 170 podskoków w 30 sekund", undefined, prog("technika", 8)],
  ["Wykonaj krótki układ freestyle (30 s) z 5 różnymi trikami", undefined, prog("triki", 8)],
  ["Wykonaj 1500 podskoków pod rząd", undefined, prog("single", 1500)],
  ["Wykonaj 130 double-unders pod rząd", undefined, prog("double", 130)],
  ["Zajmij miejsce na podium zawodów amatorskich"],
  ["Wykonaj pierwszego quad-under (poczwórny obrót) — próba", undefined, prog("double", 140)],
  // 46-65 · Zaawansowany
  ["Trenuj jak zawodnik freestyle/speed przez sezon"],
  ["Wykonaj 160 double-unders pod rząd", undefined, prog("double", 160)],
  ["Osiągnij 180 podskoków w 30 sekund", undefined, prog("technika", 9)],
  ["Wykonaj układ freestyle z power moves (push-up jump, frog)", undefined, prog("triki", 9)],
  ["Wykonaj 2000 podskoków pod rząd", undefined, prog("single", 2000)],
  ["Wykonaj 200 double-unders pod rząd", undefined, prog("double", 200)],
  ["Wykonaj czystego quad-under", undefined, prog("double", 210)],
  ["Zajmij miejsce w czołówce mistrzostw kraju (kategoria)"],
  ["Wykonaj multiple release i chwyt w locie", undefined, prog("triki", 10)],
  ["Osiągnij 185 podskoków w 30 sekund (speed elitarny)", undefined, prog("technika", 10)],
  ["Wykonaj 250 double-unders pod rząd", undefined, prog("double", 250)],
  ["Wykonaj układ freestyle z gymnastics (przewrót + skok)", undefined, prog("triki", 11)],
  ["Wykonaj 3000 podskoków pod rząd", undefined, prog("single", 3000)],
  ["Wykonaj 300 double-unders pod rząd", undefined, prog("double", 300)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Osiągnij 188 podskoków w 30 sekund", undefined, prog("technika", 11)],
  ["Wykonaj triple-under z criss-crossem (TJ triple)", undefined, prog("triki", 12)],
  ["Wykonaj 400 double-unders pod rząd", undefined, prog("double", 400)],
  ["Wykonaj pełny układ freestyle (75 s) na poziomie zawodniczym", undefined, prog("triki", 13)],
  ["Uzyskaj wynik kwalifikujący do zawodów międzynarodowych"],
  // 66-85 · Wyczynowy
  ["Wykonaj 500 double-unders pod rząd", undefined, prog("double", 500)],
  ["Osiągnij 190 podskoków w 30 sekund", undefined, prog("technika", 12)],
  ["Wystartuj w zawodach międzynarodowych"],
  ["Wykonaj 5 quad-underów pod rząd", undefined, prog("double", 520)],
  ["Zdobądź punkty w zawodach międzynarodowych"],
  ["Wykonaj układ freestyle z multiple releases i power moves", undefined, prog("triki", 14)],
  ["Wykonaj 700 double-unders pod rząd", undefined, prog("double", 700)],
  ["Osiągnij 195 podskoków w 30 sekund", undefined, prog("technika", 13)],
  ["Zajmij miejsce w pierwszej ósemce zawodów międzynarodowych"],
  ["Wykonaj pierwszego quin-under (pięciokrotny obrót) — próba", undefined, prog("double", 720)],
  ["Wykonaj 1000 double-unders pod rząd", "Tysiąc double-underów.", prog("double", 1000)],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Osiągnij 200 podskoków w 30 sekund", "Rekordowe tempo.", prog("technika", 14)],
  ["Wykonaj układ freestyle na poziomie światowej czołówki", undefined, prog("triki", 15)],
  ["Wykonaj czystego quin-under", undefined, prog("double", 1050)],
  ["Wykonaj 1500 double-unders pod rząd", undefined, prog("double", 1500)],
  ["Zajmij miejsce w pierwszej piętnastce zawodów o zasięgu ogólnokrajowym"],
  ["Wykonaj najtrudniejsze kombinacje release + gymnastics", undefined, prog("triki", 16)],
  ["Osiągnij 205 podskoków w 30 sekund", undefined, prog("technika", 15)],
  ["Zdobądź tytuł mistrza regionu"],
  // 86-99 · Elita
  ["Wykonaj 2000 double-unders pod rząd", undefined, prog("double", 2000)],
  ["Weź udział w finale mistrzostw kraju amatorów"],
  ["Osiągnij 210 podskoków w 30 sekund", undefined, prog("technika", 16)],
  ["Wykonaj układ freestyle z własnymi, oryginalnymi elementami", undefined, prog("triki", 17)],
  ["Wykonaj 3000 double-unders pod rząd", undefined, prog("double", 3000)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju amatorów"],
  ["Osiągnij 215 podskoków w 30 sekund", undefined, prog("technika", 17)],
  ["Zdobądź medal mistrzostw kraju amatorów (speed lub freestyle)"],
  ["Ustanów swój rekord życiowy w konkurencji speed", undefined, prog("technika", 18)],
  ["Awansuj do finału mistrzostw kraju amatorów we freestyle"],
  ["Zdobądź złoto mistrzostw kraju amatorów"],
  ["Ustanów swój rekord życiowy w konkurencji (np. double-unders w 30 s)", undefined, prog("technika", 19)],
  ["Zostań wielokrotnym mistrzem kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): wielokrotny mistrz kraju amatorów w skakance", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata) potwierdzają osobne certyfikaty."],
]);
