// Ski jumping ladder 1-99. Manual — progression tracks: jump distance (meters,
// value = meters) and competition level. Benchmarks: małe skocznie ~20-40 m,
// HS100 ~90-105 m, HS140 large hill, mamut (ski flying) 200 m+, WR ~253 m.
import { ladderC, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";
const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "skoki-narciarskie",
  name: "Skoki narciarskie",
  icon: "🎿",
  description:
    "Od pierwszego zjazdu z małej skoczni po loty narciarskie ponad 200 m. Progresja: odległość skoku, technika i poziom zawodów.",
  sortOrder: 45,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Zjedź z najazdu i wyląduj na płaskim (bez dużej skoczni)", undefined, prog("technika", 1)],
  ["Opanuj pozycję dojazdową (aerodynamiczny przysiad)", undefined, prog("technika", 2)],
  ["Wykonaj pierwszy skok na małej skoczni (do 10 m)", undefined, prog("odleglosc", 8)],
  ["Wyląduj poprawnie na telemark", undefined, prog("technika", 3)],
  ["Skocz 15 metrów", undefined, prog("odleglosc", 15)],
  ["Opanuj wybicie z progu (timing odbicia)", undefined, prog("technika", 4)],
  ["Skocz 20 metrów", undefined, prog("odleglosc", 20)],
  ["Ustabilizuj pozycję w locie (narty w V)", undefined, prog("technika", 5)],
  ["Skocz 25 metrów", undefined, prog("odleglosc", 25)],
  ["Skocz 30 metrów", undefined, prog("odleglosc", 30)],
  // 11-25 · Regularny
  ["Trenuj regularnie przez cały sezon skoczni małej"],
  ["Skocz 35 metrów", undefined, prog("odleglosc", 35)],
  ["Wykonaj serię 5 skoków z równym lądowaniem telemark", undefined, prog("technika", 6)],
  ["Skocz 40 metrów", undefined, prog("odleglosc", 40)],
  ["Skocz z skoczni średniej (HS 50-60)", undefined, prog("odleglosc", 50)],
  ["Wystartuj w pierwszych zawodach klubowych"],
  ["Skocz 55 metrów", undefined, prog("odleglosc", 55)],
  ["Opanuj kontrolę lotu przy silniejszym wietrze", undefined, prog("technika", 7)],
  ["Skocz 60 metrów", undefined, prog("odleglosc", 60)],
  ["Skocz z skoczni HS 70", undefined, prog("odleglosc", 65)],
  ["Skocz 70 metrów", undefined, prog("odleglosc", 70)],
  ["Utrzymaj stabilny system telemark w każdym skoku serii", undefined, prog("technika", 8)],
  ["Skocz 75 metrów", undefined, prog("odleglosc", 75)],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  ["Skocz 80 metrów", undefined, prog("odleglosc", 80)],
  // 26-45 · Średniozaawansowany
  ["Trenuj z planem przez cały sezon (skocznie średnie i normalne)"],
  ["Skocz z skoczni normalnej HS 100", undefined, prog("odleglosc", 85)],
  ["Skocz 90 metrów", undefined, prog("odleglosc", 90)],
  ["Opanuj optymalne ustawienie nart w locie (maksymalizacja nośności)", undefined, prog("technika", 9)],
  ["Skocz 95 metrów", undefined, prog("odleglosc", 95)],
  ["Skocz na punkt konstrukcyjny skoczni HS100 (~100 m)", undefined, prog("odleglosc", 100)],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Skocz 105 metrów", undefined, prog("odleglosc", 105)],
  ["Uzyskaj wysokie noty za styl od sędziów", undefined, prog("technika", 10)],
  ["Skocz z skoczni dużej HS 130", undefined, prog("odleglosc", 110)],
  ["Skocz 115 metrów", undefined, prog("odleglosc", 115)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju (kategoria)"],
  ["Skocz 120 metrów", undefined, prog("odleglosc", 120)],
  ["Skocz z skoczni HS 140", undefined, prog("odleglosc", 125)],
  ["Skocz 130 metrów", undefined, prog("odleglosc", 130)],
  ["Opanuj timing wybicia na dużej skoczni", undefined, prog("technika", 11)],
  ["Skocz 135 metrów", undefined, prog("odleglosc", 135)],
  ["Zdobądź minimum na mistrzostwa kraju seniorów"],
  ["Skocz 140 metrów", undefined, prog("odleglosc", 140)],
  ["Skocz na punkt HS140 (~140 m)", undefined, prog("odleglosc", 142)],
  // 46-65 · Zaawansowany
  ["Trenuj na poziomie klubowym/regionalnym"],
  ["Skocz 145 metrów", undefined, prog("odleglosc", 145)],
  ["Zajmij miejsce w czołówce mistrzostw kraju"],
  ["Skocz 150 metrów", undefined, prog("odleglosc", 150)],
  ["Uzyskaj stabilne noty stylu 18+ w zawodach", undefined, prog("technika", 12)],
  ["Skocz 155 metrów", undefined, prog("odleglosc", 155)],
  ["Zdobądź medal mistrzostw kraju juniorów"],
  ["Skocz 160 metrów", undefined, prog("odleglosc", 160)],
  ["Wystartuj w zawodach FIS Cup / Pucharu Kontynentalnego"],
  ["Skocz 165 metrów", undefined, prog("odleglosc", 165)],
  ["Skocz z skoczni mamuciej (ski flying, HS 185+)", undefined, prog("odleglosc", 170)],
  ["Zdobądź punkty w Pucharze Kontynentalnym"],
  ["Skocz 175 metrów", undefined, prog("odleglosc", 175)],
  ["Opanuj lot na skoczni mamuciej (kontrola przy 180+ m)", undefined, prog("technika", 13)],
  ["Skocz 180 metrów", undefined, prog("odleglosc", 180)],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Skocz 185 metrów", undefined, prog("odleglosc", 185)],
  ["Uzyskaj minimum na zawody krajowe"],
  ["Skocz 190 metrów", undefined, prog("odleglosc", 190)],
  ["Skocz 195 metrów", undefined, prog("odleglosc", 195)],
  // 66-85 · Wyczynowy
  ["Weź udział w zawodach krajowych"],
  ["Skocz 200 metrów", "Bariera 200 m — lot narciarski.", prog("odleglosc", 200)],
  ["Ukończ konkurs zawodów krajowych w drugiej serii"],
  ["Skocz 205 metrów", undefined, prog("odleglosc", 205)],
  ["Zdobądź dobry wynik w klasyfikacji zawodów krajowych"],
  ["Skocz 210 metrów", undefined, prog("odleglosc", 210)],
  ["Uzyskaj noty stylu na bardzo wysokim poziomie", undefined, prog("technika", 14)],
  ["Skocz 215 metrów", undefined, prog("odleglosc", 215)],
  ["Zajmij miejsce w pierwszej piętnastce zawodów krajowych"],
  ["Skocz 220 metrów", undefined, prog("odleglosc", 220)],
  ["Wystąp w prestiżowym turnieju krajowym"],
  ["Skocz 225 metrów", undefined, prog("odleglosc", 225)],
  ["Zajmij miejsce w pierwszej dziesiątce zawodów krajowych"],
  ["Skocz 230 metrów", undefined, prog("odleglosc", 230)],
  ["Weź udział w finałowej serii mistrzostw kraju"],
  ["Skocz 235 metrów", undefined, prog("odleglosc", 235)],
  ["Zajmij miejsce w pierwszej szóstce zawodów krajowych"],
  ["Skocz 240 metrów", undefined, prog("odleglosc", 240)],
  ["Stań na podium zawodów krajowych"],
  ["Skocz 245 metrów", undefined, prog("odleglosc", 245)],
  // 86-99 · Elita
  ["Wygraj konkurs zawodów krajowych"],
  ["Skocz 250 metrów", "Bardzo rzadki, elitarny dystans.", prog("odleglosc", 250)],
  ["Zdobądź uznanie w krajowym środowisku skoków narciarskich"],
  ["Zbuduj wieloletni, dojrzały warsztat techniczny"],
  ["Utrzymaj wysoką formę przez cały sezon"],
  ["Ustanów swój rekord życiowy na znanej skoczni"],
  ["Zajmij miejsce w czołowej trójce klasyfikacji krajowej"],
  ["Zdobądź uznanie za konsekwentnie wysoki poziom sezonu"],
  ["Poprowadź kogoś przez zaawansowaną technikę skoków"],
  ["Wygraj klasyfikację generalną sezonu krajowego"],
  ["Osiągnij status uznanego, doświadczonego zawodnika"],
  ["Zbliż się do swojego rekordu życiowego w długości lotu", undefined, prog("odleglosc", 252)],
  ["Ustanów swój rekord życiowy w długości lotu narciarskiego", undefined, prog("odleglosc", 254)],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat skoczka narciarskiego", "Dalsze, zawodowe osiągnięcia (Puchar Świata, mistrzostwa świata, igrzyska) potwierdzają osobne certyfikaty."],
]);

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  2: [
    { kind: "video", title: "Ski Jumping — Inrun Position and Technique", url: yt("qG2Jd0jGtlk") },
  ],
  4: [
    { kind: "video", title: "How to Land Telemark in Ski Jumping", url: yt("A4qqm_5kU9o") },
  ],
  6: [
    { kind: "video", title: "Ski Jumping Takeoff — Timing and Explosion", url: yt("H2u4F1mYBFY") },
  ],
  8: [
    { kind: "video", title: "V-Style Flight Position in Ski Jumping Explained", url: yt("q3dPxPjBFKw") },
  ],
  16: [
    { kind: "article", title: "FIS — Ski Jumping Rules and Scoring System", url: "https://www.fis-ski.com/en/ski-jumping/ski-jumping" },
  ],
  29: [
    { kind: "video", title: "Ski Jumping Wind Conditions — How Wind Affects Jumps", url: yt("DPj0r7rGJHQ") },
  ],
  40: [
    { kind: "video", title: "Large Hill Ski Jumping Technique — Advanced Tips", url: yt("IhXr0eEX6zs") },
  ],
  56: [
    { kind: "reference", title: "FIS Ski Jumping World Cup Standings", url: "https://www.fis-ski.com/en/ski-jumping/cup-standings" },
  ],
  67: [
    { kind: "video", title: "Ski Flying — Over 200 Meters Explained", url: yt("GrM3UMkVxaY") },
  ],
  86: [
    { kind: "video", title: "Greatest Ski Jumps in History — Record Breakers", url: yt("DW-IGHCF7Vw") },
  ],
};
