// Snooker ladder 1-99. Manual — progression tracks: highest break (0-147),
// technique, and competition level. Distinct from pool (bilard).
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "snooker",
  name: "Snooker",
  icon: "🎱",
  description:
    "Angielska sztuka precyzji na dużym stole — od pierwszego wbicia po breaki setki i 147. Progresja: najwyższy break, technika i poziom rozgrywek.",
  sortOrder: 57,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Ustaw poprawny most i uderz białą pewnie", undefined, prog("technika", 1)],
  ["Wbij czerwoną do łuzy", undefined, prog("break", 1)],
  ["Wbij kolorową po czerwonej (sekwencja czerwona-kolor)", undefined, prog("break", 5)],
  ["Kontroluj białą — zatrzymaj ją po uderzeniu (stun)", undefined, prog("technika", 2)],
  ["Zbij break 10 punktów", undefined, prog("break", 10)],
  ["Zagraj z odbiciem od bandy z kontrolą", undefined, prog("technika", 3)],
  ["Zbij break 20 punktów", undefined, prog("break", 20)],
  ["Wyjdź białą na kolejną bilę (pozycjonowanie)", undefined, prog("technika", 4)],
  ["Rozegraj pełnego frejma do końca", undefined, prog("mecze", 1)],
  ["Zbij break 30 punktów", undefined, prog("break", 30)],
  // 11-25 · Regularny
  ["Graj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Zagraj bilę z podkręceniem (screw / side)", undefined, prog("technika", 5)],
  ["Zbij break 40 punktów", undefined, prog("break", 40)],
  ["Zagraj skuteczne zagranie obronne (safety) i snookera", undefined, prog("technika", 6)],
  ["Wygraj pierwszego frejma z realnym przeciwnikiem"],
  ["Zbij break 50 punktów", "Pierwsza „pięćdziesiątka”.", prog("break", 50)],
  ["Wykonaj długiego pota (wbicie przez cały stół)", undefined, prog("technika", 7)],
  ["Weź udział w pierwszym turnieju", undefined, prog("liga", 1)],
  ["Zbij break 60 punktów", undefined, prog("break", 60)],
  ["Zagraj rest (przedłużkę) i most z kontrolą", undefined, prog("technika", 8)],
  ["Zbij break 70 punktów", undefined, prog("break", 70)],
  ["Wygraj mecz (best of 3 frejmy)"],
  ["Zbij break 80 punktów", undefined, prog("break", 80)],
  ["Opanuj rozbicie kupki czerwonych z kontrolą białej", undefined, prog("technika", 9)],
  ["Zbij break 90 punktów", undefined, prog("break", 90)],
  // 26-45 · Średniozaawansowany
  ["Graj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zbij pierwszą setkę — break 100 punktów", "Century break — kamień milowy snookera.", prog("break", 100)],
  ["Opanuj grę pozycyjną wokół czarnej (black ball game)", undefined, prog("technika", 10)],
  ["Zbij break 105 punktów", undefined, prog("break", 105)],
  ["Zajmij miejsce w pierwszej połowie turnieju amatorskiego"],
  ["Zbij break 110 punktów", undefined, prog("break", 110)],
  ["Zagraj skutecznie w wojnie safety (taktyczne frejmy)", undefined, prog("technika", 11)],
  ["Zbij break 115 punktów", undefined, prog("break", 115)],
  ["Wygraj mecz best of 5"],
  ["Zbij break 120 punktów", undefined, prog("break", 120)],
  ["Opanuj zagrania z bandy wielokrotnej (escape z snookera)", undefined, prog("technika", 12)],
  ["Zbij break 125 punktów", undefined, prog("break", 125)],
  ["Zajmij miejsce na podium turnieju amatorskiego"],
  ["Zbij break 130 punktów", undefined, prog("break", 130)],
  ["Zbij dwie setki w jednym meczu", undefined, prog("technika", 13)],
  ["Zbij break 132 punkty", undefined, prog("break", 132)],
  ["Utrzymaj wysoki poziom w meczu wielofrejmowym (best of 7)"],
  ["Zbij break 134 punkty", undefined, prog("break", 134)],
  ["Rozegraj mecz w lidze/rankingu regionalnym", undefined, prog("liga", 2)],
  ["Zbij break 136 punktów", undefined, prog("break", 136)],
  // 46-65 · Zaawansowany
  ["Graj lub trenuj 4+ razy w tygodniu przez sezon"],
  ["Zbij break 138 punktów", undefined, prog("break", 138)],
  ["Zajmij miejsce w czołówce turnieju regionalnego"],
  ["Zbij break 139 punktów", undefined, prog("break", 139)],
  ["Opanuj pełną kontrolę białej w każdej sytuacji", undefined, prog("technika", 14)],
  ["Zbij break 140 punktów", undefined, prog("break", 140)],
  ["Wejdź do rankingu krajowego", undefined, prog("liga", 3)],
  ["Zbij break 141 punktów", undefined, prog("break", 141)],
  ["Zbij trzy setki w jednym meczu", undefined, prog("technika", 15)],
  ["Zbij break 142 punkty", undefined, prog("break", 142)],
  ["Wygraj mecz z zawodnikiem z rankingu krajowego"],
  ["Zbij break 143 punkty", undefined, prog("break", 143)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju"],
  ["Zbij break 144 punkty", undefined, prog("break", 144)],
  ["Utrzymaj średnią 40+ punktów na frejm w meczu", undefined, prog("technika", 16)],
  ["Zbij break 145 punktów", undefined, prog("break", 145)],
  ["Zdobądź medal mistrzostw kraju"],
  ["Zbij break 146 punktów", "O jeden bila od maksimum.", prog("break", 146)],
  ["Wygraj turniej rangi ogólnokrajowej"],
  ["Zbij maksymalnego breaka — 147 punktów", "Perfekcyjny frejm. Legenda snookera.", prog("break", 147)],
  // 66-85 · Wyczynowy
  ["Zbij drugiego breaka 147 w karierze", undefined, prog("technika", 17)],
  ["Uzyskaj status zawodowca (Q School / Main Tour)", undefined, prog("liga", 4)],
  ["Zbij setkę w meczu rangi zawodowej"],
  ["Wygraj mecz w turnieju rankingowym (main tour)"],
  ["Zbij 5 setek w jednym turnieju", undefined, prog("technika", 18)],
  ["Zdobądź punkty w rankingu światowym"],
  ["Awansuj do 1/16 turnieju rankingowego"],
  ["Wygraj mecz z zawodnikiem z Top 32 świata"],
  ["Zbij 10 setek w sezonie", undefined, prog("technika", 19)],
  ["Awansuj do ćwierćfinału turnieju rankingowego"],
  ["Wejdź do Top 64 światowego rankingu"],
  ["Zbij setkę decydującą o wygranej meczu"],
  ["Awansuj do półfinału turnieju o zasięgu ogólnokrajowym"],
  ["Zbij 25 setek w sezonie", undefined, prog("technika", 20)],
  ["Osiągnij czołową 32 rankingu krajowego"],
  ["Awansuj do finału turnieju o zasięgu ogólnokrajowym"],
  ["Wygraj turniej o zasięgu ogólnokrajowym"],
  ["Zbij 147 w meczu turniejowym"],
  ["Osiągnij czołową 16 rankingu krajowego"],
  ["Zbij 50 setek w sezonie", undefined, prog("technika", 21)],
  // 86-99 · Elita
  ["Wygraj drugi turniej o zasięgu ogólnokrajowym"],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Zbij setkę na mistrzostwach kraju amatorów"],
  ["Awansuj do ćwierćfinału mistrzostw kraju amatorów"],
  ["Osiągnij czołową ósemkę rankingu krajowego"],
  ["Wygraj prestiżowy turniej o szerokim zasięgu"],
  ["Awansuj do półfinału mistrzostw kraju amatorów"],
  ["Zbij 100 setek w sezonie", "Bardzo rzadki, wieloletnio wypracowany sezon.", prog("technika", 22)],
  ["Osiągnij czołową czwórkę rankingu krajowego"],
  ["Awansuj do finału mistrzostw kraju amatorów"],
  ["Zostań numerem 1 rankingu krajowego"],
  ["Zdobądź tytuł mistrza kraju amatorów"],
  ["Zdobądź wielokrotne mistrzostwo kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): wielokrotny mistrz kraju amatorów w snookerze", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, Triple Crown) potwierdzają osobne certyfikaty."],
]);
