// Snowboarding ladder 1-99. Manual — progression tracks: terrain difficulty
// (green → blue → red → black → off-piste), trick difficulty (spin degrees),
// days on snow.
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "snowboard",
  name: "Snowboard",
  icon: "🏂",
  description:
    "Od pierwszego zjazdu na miękkim stoku po park, big air i freeride. Progresja: trudność tras, obroty i dni na śniegu.",
  sortOrder: 25,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Wstań na snowboardzie i przesuń się w poślizgu"],
  ["Zjedź na snowboardzie w poślizgu bocznym (na piętach) łagodny stok"],
  ["Zjedź na snowboardzie w poślizgu bocznym na palcach"],
  ["Wykonaj listek (pendulum) na jednej krawędzi"],
  ["Zatrzymaj się kontrolowanie na obu krawędziach"],
  ["Wykonaj pierwszy skręt (przejście krawędzi)"],
  ["Połącz skręty w węża (garlands) w dół stoku"],
  ["Zjedź na snowboardzie całą łatwą trasę (zieloną) skrętami"],
  ["Wjedź i zjedź z orczyka lub wyciągu talerzykowego"],
  ["Zjedź na snowboardzie pewnie niebieską trasę", "Kontrola nad prędkością i kierunkiem."],
  // 11-25 · Regularny
  ["Jeźdź na snowboardzie przez 4 dni w sezonie"],
  ["Wykonaj skręty ślizgane z równym rytmem"],
  ["Zjedź na snowboardzie niebieską trasę bez zatrzymywania"],
  ["Opanuj jazdę w switchu (przeciwną nogą) na łatwym stoku"],
  ["Zjedź na snowboardzie czerwoną trasę", "Stromniej i szybciej."],
  ["Wykonaj ollie (wybicie z deski) w jeździe"],
  ["Jeźdź na snowboardzie przez 10 dni łącznie"],
  ["Zjedź na snowboardzie czerwoną trasę bez zatrzymywania"],
  ["Wykonaj skręty cięte (carving) na spokojnym stoku"],
  ["Przejedź przez łatwą muldę/hopkę w parku"],
  ["Jeźdź na snowboardzie przez 20 dni łącznie"],
  ["Wykonaj 180 na płaskim/łagodnym stoku"],
  ["Zjedź na snowboardzie w lekkim puchu obok trasy"],
  ["Przejedź prosty box lub rail w parku"],
  ["Zjedź na snowboardzie czarną trasę", "Najtrudniejsze oznakowane stoki."],
  // 26-45 · Średniozaawansowany
  ["Jeźdź na snowboardzie przez cały tydzień (7 dni z rzędu)"],
  ["Jeźdź na snowboardzie przez 30 dni łącznie"],
  ["Wykonaj czysty carving na czerwonej trasie"],
  ["Wykonaj 180 z małej hopki w parku"],
  ["Zjedź na snowboardzie czarną trasę bez zatrzymywania"],
  ["Jeźdź na snowboardzie komfortowo w switchu na czerwonej trasie"],
  ["Jeźdź na snowboardzie przez 40 dni łącznie"],
  ["Wykonaj 360 na łagodnym terenie lub hopce"],
  ["Zjedź na snowboardzie w głębokim puchu (freeride) poza trasą"],
  ["Przejedź średni box i rail z pewnością"],
  ["Wykonaj grab (chwyt deski) w powietrzu"],
  ["Jeźdź na snowboardzie przez 50 dni łącznie"],
  ["Zjedź na snowboardzie stromy kuluar lub bardzo stromą czarną trasę"],
  ["Wykonaj 360 z chwytem"],
  ["Skacz z średniej hopki (kicker) w parku"],
  ["Jeźdź na snowboardzie w trudnych warunkach (lód, mgła, kopny śnieg)"],
  ["Jeźdź na snowboardzie przez 60 dni łącznie"],
  ["Wykonaj boardslide na railu"],
  ["Zjedź na snowboardzie trasę FIS/nieprzygotowany teren wysokogórski"],
  ["Wykonaj 540 na hopce"],
  // 46-65 · Zaawansowany
  ["Jeźdź na snowboardzie przez 75 dni łącznie"],
  ["Wykonaj backflip lub inny front-flip (przewrót)"],
  ["Skacz z dużego kickera (10 m+)"],
  ["Zjedź na snowboardzie strome, eksponowane zbocze freeride"],
  ["Jeźdź na snowboardzie przez 100 dni łącznie"],
  ["Wykonaj 720 na dużej hopce"],
  ["Przejedź zaawansowaną linię railów w parku"],
  ["Zjedź na snowboardzie couloir o nachyleniu 40°+"],
  ["Jeźdź na snowboardzie przez 125 dni łącznie"],
  ["Wykonaj serię trików w jednym przejeździe przez park"],
  ["Zjedź na snowboardzie w warunkach lawiniastych z pełnym zabezpieczeniem"],
  ["Wykonaj 900 na hopce"],
  ["Jeźdź na snowboardzie przez 150 dni łącznie"],
  ["Zjedź na snowboardzie kultową trasę freeride (np. Alpy wysokogórskie)"],
  ["Wykonaj cab/switch 540"],
  ["Skacz z bardzo dużego kickera (15 m+)"],
  ["Jeźdź na snowboardzie przez 175 dni łącznie"],
  ["Weź udział w zawodach (slopestyle, boardercross lub freeride)"],
  ["Wykonaj przewrót z obrotem (misty/rodeo)"],
  ["Zjedź na snowboardzie zbocze o nachyleniu 45°+"],
  // 66-85 · Wyczynowy
  ["Jeźdź na snowboardzie przez 200 dni łącznie"],
  ["Wykonaj 1080 na dużej hopce"],
  ["Zjedź na snowboardzie linię freeride z elementami skalnymi (cliff drop)"],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Jeźdź na snowboardzie przez 250 dni łącznie"],
  ["Wykonaj double cork (podwójny korek)"],
  ["Skacz z drop 5 m+ w terenie"],
  ["Zjedź na snowboardzie couloir 50°+"],
  ["Jeźdź na snowboardzie przez 300 dni łącznie"],
  ["Wygraj zawody regionalne"],
  ["Wykonaj serię double corków w slopestyle"],
  ["Zjedź na snowboardzie big-mountain line na wysokogórskiej ścianie"],
  ["Jeźdź na snowboardzie przez 350 dni łącznie"],
  ["Wykonaj 1260 lub triple underflip"],
  ["Zajmij miejsce w czołówce mistrzostw kraju"],
  ["Skacz z drop 8 m+"],
  ["Jeźdź na snowboardzie przez 400 dni łącznie"],
  ["Zdobądź tytuł mistrza kraju"],
  ["Zjedź na snowboardzie wymagającą, znaną ścianę freeride w swoim regionie"],
  ["Wykonaj triple cork"],
  // 86-99 · Elita
  ["Jeźdź na snowboardzie przez 500 dni łącznie"],
  ["Weź udział w zawodach o zasięgu ogólnokrajowym"],
  ["Wykonaj przejazd slopestyle z double/triple corkami oceniony przez sędziów"],
  ["Zjedź na snowboardzie kilka znanych, wymagających ścian freeride"],
  ["Jeźdź na snowboardzie przez 600 dni łącznie"],
  ["Zdobądź dobry wynik w klasyfikacji zawodów krajowych"],
  ["Wykonaj 1440 na big air"],
  ["Zdobądź podium zawodów o zasięgu ogólnokrajowym"],
  ["Jeźdź na snowboardzie przez 750 dni łącznie"],
  ["Wygraj zawody o zasięgu ogólnokrajowym"],
  ["Wykonaj quad cork lub trik na bardzo wysokim poziomie technicznym"],
  ["Poprowadź kogoś przez zaawansowane triki i freeride"],
  ["Jeźdź na snowboardzie przez 1000 dni łącznie"],
  ["Poziom mistrzowski (amatorski szczyt): triple/quad cork i wieloletni, dojrzały warsztat", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  1: prog("technika", 1), 2: prog("technika", 2), 3: prog("technika", 3), 4: prog("technika", 4),
  5: prog("technika", 5), 6: prog("technika", 6), 7: prog("technika", 7),
  8: prog("teren", 1), 10: prog("teren", 2), 15: prog("teren", 3), 25: prog("teren", 4),
  33: prog("teren", 5), 39: prog("teren", 6), 49: prog("teren", 7), 55: prog("teren", 8),
  63: prog("teren", 9), 68: prog("teren", 10), 76: prog("teren", 11), 84: prog("teren", 12),
  22: prog("obrot", 180), 32: prog("obrot", 360), 40: prog("obrot", 540), 51: prog("obrot", 720),
  62: prog("obrot", 900), 66: prog("obrot", 1080), 74: prog("obrot", 1260), 92: prog("obrot", 1440),
  11: prog("dni", 4), 17: prog("dni", 10), 21: prog("dni", 20), 27: prog("dni", 30),
  37: prog("dni", 40), 42: prog("dni", 50), 47: prog("dni", 60), 50: prog("dni", 75),
  54: prog("dni", 100), 58: prog("dni", 125), 61: prog("dni", 150), 65: prog("dni", 175),
  69: prog("dni", 200), 73: prog("dni", 250), 77: prog("dni", 300), 81: prog("dni", 350),
  85: prog("dni", 400), 89: prog("dni", 500), 93: prog("dni", 600), 96: prog("dni", 750),
  98: prog("dni", 1000),
  26: freq(7, 1),
  // pozostałe: triki, zawody, wydarzenia — manualne.
};
