// Indoor cycling / spinning ladder 1-99. Manual — progression tracks: sessions
// attended, FTP (functional threshold power, W/kg ×10 as value), and class/race
// level (indoor cycling racing e.g. Zwift). Distinct from outdoor road cycling.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "spinning",
  name: "Spinning / rower stacjonarny",
  icon: "🚵",
  description:
    "Kolarstwo halowe i trenażer — zajęcia grupowe i wyścigi wirtualne (Zwift). Progresja: liczba sesji, moc progowa (FTP w W/kg) i poziom rywalizacji.",
  sortOrder: 65,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Ukończ pierwszą sesję spinningu / na trenażerze", undefined, prog("sesje", 1)],
  ["Opanuj ustawienie roweru (siodło, kierownica, klipsy)", undefined, prog("technika", 1)],
  ["Utrzymaj kadencję 80-90 rpm przez 10 minut", undefined, prog("technika", 2)],
  ["Ukończ sesję 30 minut bez zsiadania", undefined, prog("technika", 3)],
  ["Zaliczy 5 sesji", undefined, prog("sesje", 5)],
  ["Ukończ interwały (praca/odpoczynek) w rytmie prowadzącego", undefined, prog("technika", 4)],
  ["Ukończ sesję 45 minut", undefined, prog("technika", 5)],
  ["Zmierz swoje FTP (test 20 min) — pierwszy wynik", undefined, prog("ftp", 15)],
  ["Zaliczy 10 sesji", undefined, prog("sesje", 10)],
  ["Ukończ pełną godzinną sesję", undefined, prog("technika", 6)],
  // 11-25 · Regularny
  ["Trenuj 3 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Osiągnij FTP 2,0 W/kg", undefined, prog("ftp", 20)],
  ["Zaliczy 20 sesji", undefined, prog("sesje", 20)],
  ["Utrzymaj pozycję „out of saddle” (na stojąco) w podjazdach", undefined, prog("technika", 7)],
  ["Osiągnij FTP 2,3 W/kg", undefined, prog("ftp", 23)],
  ["Ukończ sesję interwałową HIIT do końca bez opadu mocy", undefined, prog("technika", 8)],
  ["Zaliczy 40 sesji", undefined, prog("sesje", 40)],
  ["Osiągnij FTP 2,5 W/kg", undefined, prog("ftp", 25)],
  ["Weź udział w pierwszym wyścigu wirtualnym (Zwift) lub klasie rankingowej", undefined, prog("liga", 1)],
  ["Ukończ sesję 90 minut", undefined, prog("technika", 9)],
  ["Zaliczy 60 sesji", undefined, prog("sesje", 60)],
  ["Osiągnij FTP 2,7 W/kg", undefined, prog("ftp", 27)],
  ["Utrzymaj równą moc (sweet spot) przez 20 minut", undefined, prog("technika", 10)],
  ["Osiągnij FTP 3,0 W/kg", "Solidny amator.", prog("ftp", 30)],
  ["Zaliczy 80 sesji", undefined, prog("sesje", 80)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 4 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(4, 12)],
  ["Osiągnij FTP 3,2 W/kg", undefined, prog("ftp", 32)],
  ["Zaliczy 100 sesji", undefined, prog("sesje", 100)],
  ["Ukończ sesję 2 godziny na trenażerze", undefined, prog("technika", 11)],
  ["Osiągnij FTP 3,4 W/kg", undefined, prog("ftp", 34)],
  ["Zajmij miejsce w pierwszej połowie wyścigu wirtualnego"],
  ["Osiągnij FTP 3,6 W/kg", undefined, prog("ftp", 36)],
  ["Utrzymaj VO2max effort (5 min na maksa) w treningu", undefined, prog("technika", 12)],
  ["Zaliczy 150 sesji", undefined, prog("sesje", 150)],
  ["Osiągnij FTP 3,8 W/kg", undefined, prog("ftp", 38)],
  ["Awansuj do wyższej kategorii wyścigowej (np. Zwift Cat C→B)", undefined, prog("liga", 2)],
  ["Osiągnij FTP 4,0 W/kg", "Poziom wytrenowanego kolarza.", prog("ftp", 40)],
  ["Zaliczy 200 sesji", undefined, prog("sesje", 200)],
  ["Wygraj podjazd/segment w wyścigu wirtualnym"],
  ["Osiągnij FTP 4,1 W/kg", undefined, prog("ftp", 41)],
  ["Ukończ ultra-sesję 3 godziny na trenażerze", undefined, prog("technika", 13)],
  ["Zaliczy 250 sesji", undefined, prog("sesje", 250)],
  ["Osiągnij FTP 4,2 W/kg", undefined, prog("ftp", 42)],
  ["Zajmij miejsce na podium wyścigu wirtualnego kategorii amatorskiej"],
  ["Osiągnij FTP 4,3 W/kg", undefined, prog("ftp", 43)],
  // 46-65 · Zaawansowany
  ["Trenuj z planem periodyzacji mocy przez cały sezon"],
  ["Osiągnij FTP 4,4 W/kg", undefined, prog("ftp", 44)],
  ["Zaliczy 300 sesji", undefined, prog("sesje", 300)],
  ["Awansuj do kategorii B/A wyścigów wirtualnych", undefined, prog("liga", 3)],
  ["Osiągnij FTP 4,5 W/kg", undefined, prog("ftp", 45)],
  ["Utrzymaj 5 W/kg przez 5 minut (VO2max)", undefined, prog("technika", 14)],
  ["Osiągnij FTP 4,6 W/kg", undefined, prog("ftp", 46)],
  ["Zaliczy 400 sesji", undefined, prog("sesje", 400)],
  ["Zajmij miejsce w czołówce wyścigu wirtualnego kategorii B"],
  ["Osiągnij FTP 4,7 W/kg", undefined, prog("ftp", 47)],
  ["Wygraj wyścig wirtualny kategorii amatorskiej"],
  ["Osiągnij FTP 4,8 W/kg", undefined, prog("ftp", 48)],
  ["Zaliczy 500 sesji", undefined, prog("sesje", 500)],
  ["Utrzymaj sprint 15 W/kg przez 5 sekund", undefined, prog("technika", 15)],
  ["Osiągnij FTP 4,9 W/kg", undefined, prog("ftp", 49)],
  ["Awansuj do kategorii A (elita amatorska)", undefined, prog("liga", 4)],
  ["Osiągnij FTP 5,0 W/kg", "Próg zawodniczy.", prog("ftp", 50)],
  ["Zaliczy 600 sesji", undefined, prog("sesje", 600)],
  ["Zajmij miejsce w czołówce wyścigu kategorii A"],
  ["Osiągnij FTP 5,1 W/kg", undefined, prog("ftp", 51)],
  // 66-85 · Wyczynowy
  ["Osiągnij FTP 5,2 W/kg", undefined, prog("ftp", 52)],
  ["Zaliczy 700 sesji", undefined, prog("sesje", 700)],
  ["Wygraj wyścig wirtualny kategorii A"],
  ["Osiągnij FTP 5,3 W/kg", undefined, prog("ftp", 53)],
  ["Zakwalifikuj się do ligi e-sportu kolarskiego (Zwift Racing League)"],
  ["Osiągnij FTP 5,4 W/kg", undefined, prog("ftp", 54)],
  ["Zaliczy 800 sesji", undefined, prog("sesje", 800)],
  ["Zajmij miejsce w czołówce ligi e-kolarskiej"],
  ["Osiągnij FTP 5,5 W/kg", undefined, prog("ftp", 55)],
  ["Utrzymaj 6 W/kg przez 5 minut", undefined, prog("technika", 16)],
  ["Osiągnij FTP 5,6 W/kg", undefined, prog("ftp", 56)],
  ["Zaliczy 1000 sesji", undefined, prog("sesje", 1000)],
  ["Zajmij miejsce medalowe w rundzie ligi e-sportu kolarskiego"],
  ["Osiągnij FTP 5,7 W/kg", undefined, prog("ftp", 57)],
  ["Zakwalifikuj się do mistrzostw kraju e-kolarstwa"],
  ["Osiągnij FTP 5,8 W/kg", undefined, prog("ftp", 58)],
  ["Zaliczy 1200 sesji", undefined, prog("sesje", 1200)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju e-kolarstwa"],
  ["Osiągnij FTP 5,9 W/kg", undefined, prog("ftp", 59)],
  ["Zdobądź medal mistrzostw kraju e-kolarstwa"],
  // 86-99 · Elita
  ["Osiągnij FTP 6,0 W/kg", "Bardzo wysoki, wieloletnio wypracowany poziom.", prog("ftp", 60)],
  ["Weź udział w zawodach e-kolarstwa o zasięgu ogólnokrajowym"],
  ["Osiągnij FTP 6,1 W/kg", undefined, prog("ftp", 61)],
  ["Zaliczy 1500 sesji", undefined, prog("sesje", 1500)],
  ["Zajmij miejsce w pierwszej dwudziestce zawodów o zasięgu ogólnokrajowym"],
  ["Osiągnij FTP 6,2 W/kg", undefined, prog("ftp", 62)],
  ["Wygraj rundę ligi e-kolarstwa o zasięgu ogólnokrajowym"],
  ["Osiągnij FTP 6,3 W/kg", undefined, prog("ftp", 63)],
  ["Zajmij miejsce w pierwszej dziesiątce zawodów o zasięgu ogólnokrajowym"],
  ["Osiągnij FTP 6,4 W/kg", undefined, prog("ftp", 64)],
  ["Awansuj do finału mistrzostw kraju amatorów w e-kolarstwie"],
  ["Osiągnij FTP 6,5 W/kg", undefined, prog("ftp", 65)],
  ["Zdobądź medal mistrzostw kraju amatorów w e-kolarstwie"],
  ["Poziom mistrzowski (amatorski szczyt): FTP 6,5 W/kg i wieloletni, dojrzały warsztat", "Dalsze, zawodowe osiągnięcia (UCI Esports World Championships) potwierdzają osobne certyfikaty."],
]);
