// Woodworking ladder 1-99 — REALISTIC personal-progression scale (dedicated
// hobbyist; hours capped ~1200, project counts scaled for a slow craft; top
// tiers reframed as attainable mastery, real feats left to future certificates).
// Tracks: umiejetnosci, projekty (finished builds), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "stolarstwo",
  name: "Stolarstwo",
  icon: "🪵",
  description:
    "Obróbka drewna — od pierwszego równego cięcia po meble i precyzyjne złącza. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → własne meble → dojrzały, autorski warsztat.",
  sortOrder: 89,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Odmierz i zaznacz precyzyjnie (miara, kątownik)", undefined, prog("umiejetnosci", 1)],
  ["Wykonaj równe cięcie piłą (ręczną lub elektryczną)", undefined, prog("umiejetnosci", 2)],
  ["Wywierć prostopadłe otwory", undefined, prog("umiejetnosci", 3)],
  ["Zeszlifuj i wygładź powierzchnię", undefined, prog("umiejetnosci", 4)],
  ["Skręć proste połączenie (wkręty, kołki)", undefined, prog("umiejetnosci", 5)],
  ["Zbuduj prosty przedmiot (półka / skrzynka)", undefined, prog("projekty", 2)],
  ["Nałóż wykończenie (olej / lakier)", undefined, prog("umiejetnosci", 6)],
  ["Pracuj bezpiecznie z narzędziami (BHP warsztatu)", undefined, prog("umiejetnosci", 7)],
  ["Ukończ 4 projekty", undefined, prog("projekty", 4)],
  ["Pracuj w warsztacie łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Pracuj w warsztacie kilka razy w tygodniu przez 4 tygodnie", undefined, freq(2, 4)],
  ["Wykonaj proste złącze (na zakładkę / czop luźny)", undefined, prog("umiejetnosci", 8)],
  ["Sklej i ściśnij elementy równo (klamry)", undefined, prog("umiejetnosci", 9)],
  ["Zbuduj taboret lub stolik", undefined, prog("umiejetnosci", 10)],
  ["Ukończ 8 projektów", undefined, prog("projekty", 8)],
  ["Pracuj w warsztacie łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Wykonaj złącze czopowe (mortise & tenon)", undefined, prog("umiejetnosci", 11)],
  ["Zbuduj szafkę z drzwiczkami", undefined, prog("umiejetnosci", 12)],
  ["Ukończ 14 projektów", undefined, prog("projekty", 14)],
  ["Naostrz i ustaw narzędzia ręczne (dłuta, strug)", undefined, prog("umiejetnosci", 13)],
  ["Wykonaj fugowanie i profilowanie (frezarka)", undefined, prog("umiejetnosci", 14)],
  ["Pracuj w warsztacie łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Zbuduj mebel z kilku podzespołów", undefined, prog("projekty", 20)],
  ["Wykonaj szufladę z prowadnicami", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 25 projektów", undefined, prog("projekty", 25)],
  // 26-45 · Średniozaawansowany
  ["Pracuj w warsztacie regularnie przez 8 tygodni", undefined, freq(2, 8)],
  ["Wykonaj złącze na jaskółczy ogon (dovetail)", undefined, prog("umiejetnosci", 16)],
  ["Zbuduj komodę lub biurko z szufladami", undefined, prog("umiejetnosci", 17)],
  ["Ukończ 35 projektów", undefined, prog("projekty", 35)],
  ["Opanuj fornirowanie / okleinowanie", undefined, prog("umiejetnosci", 18)],
  ["Pracuj w warsztacie łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Zrób gięcie drewna (parą lub laminowanie)", undefined, prog("umiejetnosci", 19)],
  ["Zbuduj krzesło z dopasowanymi połączeniami", undefined, prog("umiejetnosci", 20)],
  ["Ukończ 45 projektów", undefined, prog("projekty", 45)],
  ["Wykończ mebel na wysokim poziomie (bejca, olejowosk, politura)", undefined, prog("umiejetnosci", 21)],
  ["Zbuduj stół z solidną konstrukcją", undefined, prog("umiejetnosci", 22)],
  ["Pracuj w warsztacie łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Zbuduj większy mebel (szafa / regał)", undefined, prog("projekty", 55)],
  ["Opanuj precyzyjne dopasowania ręcznymi narzędziami", undefined, prog("umiejetnosci", 23)],
  ["Zaprojektuj drobną modyfikację / własny detal", undefined, prog("umiejetnosci", 24)],
  ["Ukończ 65 projektów", undefined, prog("projekty", 65)],
  ["Opanuj intarsję lub toczenie na tokarce", undefined, prog("umiejetnosci", 25)],
  ["Pracuj w warsztacie łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Zbuduj mebel łączący kilka technik złączy", undefined, prog("umiejetnosci", 26)],
  ["Pracuj w warsztacie regularnie przez 3 miesiące", undefined, prog("projekty", 80)],
  // 46-65 · Zaawansowany (amator)
  ["Pracuj w warsztacie regularnie przez 12 tygodni", undefined, freq(2, 12)],
  ["Zaprojektuj mebel od zera (rysunek + lista materiałów)", undefined, prog("umiejetnosci", 27)],
  ["Zbuduj spójny zestaw mebli", undefined, prog("umiejetnosci", 28)],
  ["Ukończ 95 projektów", undefined, prog("projekty", 95)],
  ["Pracuj w warsztacie łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Pokaż prace publicznie i zbierz opinie odbiorców"],
  ["Zbuduj mebel z precyzyjnymi złączami ręcznymi (bez wkrętów)", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 120 projektów", undefined, prog("projekty", 120)],
  ["Opanuj wybraną specjalizację (meble / toczenie / snycerstwo)", undefined, prog("umiejetnosci", 30)],
  ["Pracuj w warsztacie łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj portfolio najlepszych realizacji"],
  ["Weź udział w wystawie / jarmarku lub sprzedaj mebel"],
  ["Zbuduj skomplikowany mebel (sekretarzyk, komoda z fornirem)", undefined, prog("umiejetnosci", 31)],
  ["Ukończ 145 projektów", undefined, prog("projekty", 145)],
  ["Realizuj mebel na zamówienie / na wymiar", undefined, prog("umiejetnosci", 32)],
  ["Pracuj w warsztacie łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy stolarstwa", undefined, prog("umiejetnosci", 33)],
  ["Zrealizuj spójny cykl / kolekcję mebli"],
  ["Zbuduj mebel na najwyższym własnym poziomie wykonania", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 170 projektów", undefined, prog("projekty", 170)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Pracuj w warsztacie regularnie przez pełny sezon (6 miesięcy)"],
  ["Projektuj i buduj własne meble swobodnie", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 200 projektów", undefined, prog("projekty", 200)],
  ["Pracuj w warsztacie łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zrealizuj kolekcję i pokaż ją (lokalnie / online)"],
  ["Rozwiń warsztat na tyle, by uczyć stolarstwa", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie realizujesz zamówienia / sprzedajesz meble"],
  ["Opanuj każdą podstawową technikę stolarską na wysokim poziomie", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 240 projektów", undefined, prog("projekty", 240)],
  ["Zdobądź wyróżnienie lub uznanie w społeczności rękodzieła"],
  ["Pracuj w warsztacie łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny projekt autorski (duży mebel / zabudowa)", undefined, prog("umiejetnosci", 38)],
  ["Twoje meble są dopracowane w każdym detalu", undefined, prog("umiejetnosci", 39)],
  ["Ukończ 290 projektów", undefined, prog("projekty", 290)],
  ["Zbuduj grono klientów / odbiorców swoich mebli"],
  ["Poprowadź warsztaty lub mentoring dla stolarzy"],
  ["Zaprojektuj spójną kolekcję mebli"],
  ["Zrealizuj wystawę prezentującą Twój dorobek"],
  ["Ukończ 340 projektów", undefined, prog("projekty", 340)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Pracuj w warsztacie łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdej realizacji"],
  ["Ukończ 400 projektów", undefined, prog("projekty", 400)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych stolarzy w Twoim otoczeniu"],
  ["Zbuduj osobisty „opus” — mebel lub kolekcję życia", undefined, prog("umiejetnosci", 40)],
  ["Regularnie wystawiasz lub sprzedajesz swoje meble"],
  ["Pracuj w warsztacie łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje meble zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 470 projektów", undefined, prog("projekty", 470)],
  ["Uczysz i kształtujesz kolejnych stolarzy"],
  ["Masz dorobek, z którego można ułożyć wystawę retrospektywną"],
  ["Zbudujesz z drewna niemal wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski warsztat", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (stolarstwo: Paul Sellers, Steve Ramsey, Crafted Workshop i in.).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Mierzenie i trasowanie precyzyjnie", url: yt("0Gc4VBQ26Yc") }],
  2: [{ kind: "video", title: "Równe cięcie piłą ręczną", url: yt("wlnV4I1-qus") }],
  4: [{ kind: "video", title: "Szlifowanie drewna do gładka", url: yt("DeWnQlozvgU") }],
  5: [{ kind: "video", title: "Złącza na wkręty (pocket hole)", url: yt("mvO6zaIUO18") }],
  7: [{ kind: "video", title: "Wykończenie olejem (rub-on oil)", url: yt("sevALuAtA0g") }],
  12: [{ kind: "video", title: "Złącze na zakładkę (half lap)", url: yt("BlNy56uTQ0k") }],
  17: [{ kind: "video", title: "Złącze czopowe (mortise & tenon)", url: yt("aBodzmUGtdw") }],
  20: [{ kind: "video", title: "Ostrzenie dłut i noża struga", url: yt("NqfAFn5Pdqw") }],
  21: [{ kind: "video", title: "Profilowanie krawędzi frezarką", url: yt("3VPJC3VipO4") }],
  24: [{ kind: "video", title: "Budowa szuflady z prowadnicami", url: yt("Sz-ZOyAlCKM") }],
  27: [{ kind: "video", title: "Złącze na jaskółczy ogon (dovetail)", url: yt("OCYjoj6cfno") }],
};
