// Strongman ladder 1-99. Manual — progression tracks: deadlift (kg), overhead
// press (kg), event skills (atlas stones, yoke, farmers), and competition level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "strongman",
  name: "Strongman",
  icon: "🪨",
  description:
    "Kamienie atlasowe, yoke, farmer's walk i martwy ciąg na maksa. Progresja: martwy ciąg, wyciskanie nad głowę, konkurencje i poziom zawodów.",
  sortOrder: 62,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj bezpieczny martwy ciąg z pełnym zakresem", undefined, prog("technika", 1)],
  ["Opanuj wyciskanie sztangi nad głowę (overhead press)", undefined, prog("technika", 2)],
  ["Wykonaj farmer's walk z lekkim obciążeniem na 20 m", undefined, prog("technika", 3)],
  ["Martwy ciąg 100 kg", undefined, prog("martwy", 100)],
  ["Wyciśnij nad głowę 50 kg", undefined, prog("overhead", 50)],
  ["Podnieś i przenieś worek/kamień ~40 kg", undefined, prog("konkurencje", 1)],
  ["Martwy ciąg 140 kg", undefined, prog("martwy", 140)],
  ["Wyciśnij nad głowę 60 kg", undefined, prog("overhead", 60)],
  ["Wykonaj yoke walk z obciążeniem 100 kg", undefined, prog("konkurencje", 2)],
  ["Martwy ciąg 160 kg", undefined, prog("martwy", 160)],
  // 11-25 · Regularny
  ["Trenuj 3 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Wyciśnij nad głowę 70 kg", undefined, prog("overhead", 70)],
  ["Martwy ciąg 180 kg", undefined, prog("martwy", 180)],
  ["Farmer's walk 80 kg/rękę na 20 m", undefined, prog("konkurencje", 3)],
  ["Wyciśnij nad głowę 80 kg", undefined, prog("overhead", 80)],
  ["Martwy ciąg 200 kg", "Dwieście w martwym.", prog("martwy", 200)],
  ["Załaduj kamień atlasowy 80 kg na platformę", undefined, prog("konkurencje", 4)],
  ["Wystartuj w pierwszych zawodach strongman", undefined, prog("liga", 1)],
  ["Wyciśnij nad głowę 90 kg", undefined, prog("overhead", 90)],
  ["Martwy ciąg 220 kg", undefined, prog("martwy", 220)],
  ["Yoke walk 200 kg na 20 m", undefined, prog("konkurencje", 5)],
  ["Wyciśnij nad głowę 100 kg", "Setka nad głowę.", prog("overhead", 100)],
  ["Martwy ciąg 240 kg", undefined, prog("martwy", 240)],
  ["Opanuj technikę kamieni atlasowych z tłuszczem/pastą", undefined, prog("technika", 4)],
  ["Załaduj kamień atlasowy 100 kg", undefined, prog("konkurencje", 6)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 4 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(4, 12)],
  ["Wyciśnij nad głowę 110 kg", undefined, prog("overhead", 110)],
  ["Martwy ciąg 260 kg", undefined, prog("martwy", 260)],
  ["Farmer's walk 100 kg/rękę na 20 m", undefined, prog("konkurencje", 7)],
  ["Wyciśnij log (kłodę) 100 kg nad głowę", undefined, prog("overhead", 115)],
  ["Martwy ciąg 280 kg", undefined, prog("martwy", 280)],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  ["Załaduj kamień atlasowy 120 kg", undefined, prog("konkurencje", 8)],
  ["Wyciśnij nad głowę 120 kg", undefined, prog("overhead", 120)],
  ["Martwy ciąg 300 kg", "Trzysta w martwym.", prog("martwy", 300)],
  ["Yoke walk 300 kg na 20 m", undefined, prog("konkurencje", 9)],
  ["Opanuj strategię i tempo w konkurencjach na czas", undefined, prog("technika", 5)],
  ["Wyciśnij log 130 kg nad głowę", undefined, prog("overhead", 130)],
  ["Martwy ciąg 320 kg", undefined, prog("martwy", 320)],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Załaduj kamień atlasowy 140 kg", undefined, prog("konkurencje", 10)],
  ["Wyciśnij nad głowę 140 kg", undefined, prog("overhead", 140)],
  ["Martwy ciąg 340 kg", undefined, prog("martwy", 340)],
  ["Farmer's walk 120 kg/rękę na 20 m", undefined, prog("konkurencje", 11)],
  ["Wyciśnij log 150 kg nad głowę", undefined, prog("overhead", 150)],
  // 46-65 · Zaawansowany
  ["Trenuj z pełnym przygotowaniem pod starty przez sezon"],
  ["Martwy ciąg 360 kg", undefined, prog("martwy", 360)],
  ["Zajmij miejsce w czołówce mistrzostw okręgu"],
  ["Załaduj kamień atlasowy 160 kg", undefined, prog("konkurencje", 12)],
  ["Wyciśnij nad głowę 160 kg", undefined, prog("overhead", 160)],
  ["Martwy ciąg 380 kg", undefined, prog("martwy", 380)],
  ["Yoke walk 400 kg na 20 m", undefined, prog("konkurencje", 13)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju (kategoria)"],
  ["Wyciśnij log 160 kg nad głowę", undefined, prog("overhead", 165)],
  ["Martwy ciąg 400 kg", "Czterysta w martwym.", prog("martwy", 400)],
  ["Załaduj kamień atlasowy 180 kg", undefined, prog("konkurencje", 14)],
  ["Zdobądź minimum na mistrzostwa kraju seniorów"],
  ["Wyciśnij nad głowę 170 kg", undefined, prog("overhead", 170)],
  ["Martwy ciąg 420 kg", undefined, prog("martwy", 420)],
  ["Farmer's walk 140 kg/rękę na 20 m", undefined, prog("konkurencje", 15)],
  ["Zdobądź medal mistrzostw kraju juniorów"],
  ["Wyciśnij log 180 kg nad głowę", undefined, prog("overhead", 180)],
  ["Martwy ciąg 440 kg", undefined, prog("martwy", 440)],
  ["Załaduj kamień atlasowy 200 kg", undefined, prog("konkurencje", 16)],
  ["Utrzymaj wysoką formę w kilku konkurencjach jednego dnia", undefined, prog("technika", 6)],
  // 66-85 · Wyczynowy
  ["Zdobądź medal mistrzostw kraju"],
  ["Wyciśnij nad głowę 190 kg", undefined, prog("overhead", 190)],
  ["Martwy ciąg 460 kg", undefined, prog("martwy", 460)],
  ["Yoke walk 450 kg na 20 m", undefined, prog("konkurencje", 17)],
  ["Wystartuj w zawodach międzynarodowych"],
  ["Wyciśnij log 200 kg nad głowę", "Dwieście nad głowę na kłodzie.", prog("overhead", 200)],
  ["Martwy ciąg 480 kg", undefined, prog("martwy", 480)],
  ["Załaduj kamień atlasowy 220 kg", undefined, prog("konkurencje", 18)],
  ["Zdobądź punkty w międzynarodowym cyklu (Strongman Champions League)"],
  ["Martwy ciąg 500 kg", "Pięćset w martwym.", prog("martwy", 500)],
  ["Wyciśnij nad głowę 210 kg", undefined, prog("overhead", 210)],
  ["Farmer's walk 160 kg/rękę na 20 m", undefined, prog("konkurencje", 19)],
  ["Zajmij miejsce w pierwszej ósemce zawodów o zasięgu ogólnokrajowym"],
  ["Załaduj kamień atlasowy 240 kg", undefined, prog("konkurencje", 20)],
  ["Martwy ciąg 520 kg", undefined, prog("martwy", 520)],
  ["Zdobądź tytuł mistrza regionu"],
  ["Wyciśnij log 220 kg nad głowę", undefined, prog("overhead", 220)],
  ["Martwy ciąg 540 kg", undefined, prog("martwy", 540)],
  ["Weź udział w prestiżowych zawodach o zasięgu ogólnokrajowym"],
  ["Załaduj kamień atlasowy 260 kg", undefined, prog("konkurencje", 21)],
  // 86-99 · Elita
  ["Martwy ciąg 560 kg (ze sprzętem/strapami)", undefined, prog("martwy", 560)],
  ["Wyciśnij nad głowę 230 kg", undefined, prog("overhead", 230)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju amatorów"],
  ["Martwy ciąg 580 kg", undefined, prog("martwy", 580)],
  ["Załaduj kamień atlasowy 280 kg", undefined, prog("konkurencje", 22)],
  ["Wyciśnij log 240 kg nad głowę", undefined, prog("overhead", 240)],
  ["Zajmij miejsce na podium dużych zawodów o zasięgu ogólnokrajowym"],
  ["Martwy ciąg 600 kg", "Sześćset w martwym — bardzo rzadki, wieloletnio wypracowany wynik.", prog("martwy", 600)],
  ["Weź udział w prestiżowym turnieju siłaczy o szerokim zasięgu"],
  ["Wyciśnij nad głowę 250 kg", undefined, prog("overhead", 250)],
  ["Ustanów swój rekord życiowy konkurencji na zawodach", undefined, prog("konkurencje", 23)],
  ["Zajmij miejsce w pierwszej szóstce prestiżowego turnieju siłaczy"],
  ["Zdobądź podium prestiżowego turnieju siłaczy"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat siłacza", "Dalsze, zawodowe osiągnięcia (World's Strongest Man) potwierdzają osobne certyfikaty."],
]);
