// Sport shooting ladder 1-99. Manual — progression tracks: score (10 m air
// rifle/pistol, out of ~600-630 for 60 shots) and competition level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "strzelectwo-sportowe",
  name: "Strzelectwo sportowe",
  icon: "🔫",
  description:
    "Precyzja i opanowanie — karabinek lub pistolet pneumatyczny 10 m. Progresja: wynik rundy 60 strzałów (skala ok. 600-630) i poziom zawodów.",
  sortOrder: 59,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj bezpieczne obchodzenie się z bronią i postawę", undefined, prog("technika", 1)],
  ["Trafij w tarczę z 10 m (dowolne pole)", undefined, prog("wynik", 300)],
  ["Opanuj poprawny chwyt/przyłożenie i celowanie", undefined, prog("technika", 2)],
  ["Uzyskaj średnią 6,0 na strzał w serii (60/100)", undefined, prog("wynik", 360)],
  ["Kontroluj oddech i ściąganie języka spustowego", undefined, prog("technika", 3)],
  ["Uzyskaj średnią 7,0 na strzał (420/600 w rundzie)", undefined, prog("wynik", 420)],
  ["Utrzymaj stabilną postawę przez pełną serię", undefined, prog("technika", 4)],
  ["Uzyskaj wynik 450/600 w rundzie 60 strzałów", undefined, prog("wynik", 450)],
  ["Zgraj przyrządy i oddaj skupioną serię 10 strzałów", undefined, prog("technika", 5)],
  ["Uzyskaj wynik 480/600", undefined, prog("wynik", 480)],
  // 11-25 · Regularny
  ["Trenuj raz w tygodniu przez 4 kolejne tygodnie", undefined, freq(1, 4)],
  ["Uzyskaj wynik 500/600", "Poziom pewnego amatora.", prog("wynik", 500)],
  ["Opanuj rytm strzelania (stały timing)", undefined, prog("technika", 6)],
  ["Uzyskaj wynik 520/600", undefined, prog("wynik", 520)],
  ["Trafij pierwszą dziesiątkę (10.0) w zawodach", undefined, prog("technika", 7)],
  ["Weź udział w pierwszych zawodach", undefined, prog("liga", 1)],
  ["Uzyskaj wynik 535/600", undefined, prog("wynik", 535)],
  ["Utrzymaj skupienie mentalne przez całą rundę", undefined, prog("technika", 8)],
  ["Uzyskaj wynik 545/600", undefined, prog("wynik", 545)],
  ["Oddaj serię 10 strzałów bez wyjścia poza „9”", undefined, prog("technika", 9)],
  ["Uzyskaj wynik 555/600", undefined, prog("wynik", 555)],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  ["Uzyskaj wynik 560/600", undefined, prog("wynik", 560)],
  ["Opanuj korektę na warunki (światło, ustawienia)", undefined, prog("technika", 10)],
  ["Uzyskaj wynik 565/600", undefined, prog("wynik", 565)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 2 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Uzyskaj wynik 570/600", undefined, prog("wynik", 570)],
  ["Utrzymaj średnią 9,6+ na strzał w rundzie", undefined, prog("technika", 11)],
  ["Uzyskaj wynik 573/600", undefined, prog("wynik", 573)],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Uzyskaj wynik 576/600", undefined, prog("wynik", 576)],
  ["Oddaj serię 10 strzałów w całości w „10”", undefined, prog("technika", 12)],
  ["Uzyskaj wynik 579/600", undefined, prog("wynik", 579)],
  ["Uzyskaj wynik 582/600", undefined, prog("wynik", 582)],
  ["Utrzymaj wynik 575+ w dwóch różnych zawodach", undefined, prog("technika", 13)],
  ["Uzyskaj wynik 585/600", "Poziom zaawansowany.", prog("wynik", 585)],
  ["Rozegraj zawody z finałem (format olimpijski)", undefined, prog("liga", 2)],
  ["Awansuj do finału zawodów regionalnych"],
  ["Uzyskaj wynik 588/600", undefined, prog("wynik", 588)],
  ["Opanuj strzelanie w finale (pojedyncze strzały dziesiętne)", undefined, prog("technika", 14)],
  ["Uzyskaj wynik 590/600", undefined, prog("wynik", 590)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju (kategoria)"],
  ["Uzyskaj wynik 592/600", undefined, prog("wynik", 592)],
  ["Uzyskaj wynik dziesiętny 10.5+ w seriach finałowych", undefined, prog("technika", 15)],
  ["Uzyskaj wynik 594/600", undefined, prog("wynik", 594)],
  // 46-65 · Zaawansowany
  ["Trenuj z planem periodyzacji przez pełny sezon"],
  ["Uzyskaj wynik 596/600", undefined, prog("wynik", 596)],
  ["Zajmij miejsce w czołówce mistrzostw kraju"],
  ["Uzyskaj wynik 597/600", undefined, prog("wynik", 597)],
  ["Utrzymaj stabilność mentalną w finale mistrzostw", undefined, prog("technika", 16)],
  ["Uzyskaj wynik 598/600", undefined, prog("wynik", 598)],
  ["Zdobądź minimum na mistrzostwa kraju seniorów"],
  ["Uzyskaj wynik 599/600", undefined, prog("wynik", 599)],
  ["Uzyskaj wynik maksymalny 600/600 w rundzie eliminacyjnej", "Perfekcja eliminacji.", prog("wynik", 600)],
  ["Zdobądź medal mistrzostw kraju juniorów"],
  ["Uzyskaj notę finałową (format dziesiętny) na poziomie 620", undefined, prog("wynik", 620)],
  ["Utrzymaj serię strzałów 10.7+ w finale", undefined, prog("technika", 17)],
  ["Uzyskaj notę finałową 625", undefined, prog("wynik", 625)],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Uzyskaj notę finałową 628", undefined, prog("wynik", 628)],
  ["Uzyskaj minimum na mistrzostwa Europy/świata"],
  ["Uzyskaj notę finałową 630", "Poziom światowej czołówki.", prog("wynik", 630)],
  ["Awansuj do finału mistrzostw kraju seniorów"],
  ["Utrzymaj dziesiątki 10.8+ pod presją finału", undefined, prog("technika", 18)],
  ["Uzyskaj notę finałową 632", undefined, prog("wynik", 632)],
  // 66-85 · Wyczynowy
  ["Wystartuj w zawodach międzynarodowych (ISSF)"],
  ["Uzyskaj notę finałową 634", undefined, prog("wynik", 634)],
  ["Zdobądź punkty w Pucharze Świata ISSF"],
  ["Uzyskaj notę finałową 636", undefined, prog("wynik", 636)],
  ["Utrzymaj średnią eliminacji 596+ przez sezon", undefined, prog("technika", 19)],
  ["Uzyskaj notę finałową 638", undefined, prog("wynik", 638)],
  ["Zajmij miejsce w pierwszej ósemce zawodów o zasięgu ogólnokrajowym"],
  ["Uzyskaj notę finałową 640", undefined, prog("wynik", 640)],
  ["Awansuj do finału zawodów o zasięgu ogólnokrajowym"],
  ["Uzyskaj notę finałową 642", undefined, prog("wynik", 642)],
  ["Utrzymaj dziesiątki 10.9 w seriach decydujących", undefined, prog("technika", 20)],
  ["Uzyskaj notę finałową 644", undefined, prog("wynik", 644)],
  ["Zdobądź medal zawodów o zasięgu ogólnokrajowym"],
  ["Uzyskaj notę finałową 646", undefined, prog("wynik", 646)],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Uzyskaj notę finałową 648", undefined, prog("wynik", 648)],
  ["Awansuj do finału mistrzostw kraju amatorów"],
  ["Uzyskaj notę finałową 650", "Bardzo wysoki, wieloletnio wypracowany wynik.", prog("wynik", 650)],
  ["Zdobądź medal mistrzostw regionu"],
  ["Uzyskaj notę finałową 651", undefined, prog("wynik", 651)],
  // 86-99 · Elita
  ["Uzyskaj notę finałową 652", undefined, prog("wynik", 652)],
  ["Zajmij miejsce na podium zawodów o zasięgu ogólnokrajowym"],
  ["Uzyskaj notę finałową 653", undefined, prog("wynik", 653)],
  ["Zdobądź medal mistrzostw kraju amatorów"],
  ["Uzyskaj notę finałową 653,5", undefined, prog("wynik", 654)],
  ["Ustanów swój rekord życiowy w konkurencji", undefined, prog("technika", 21)],
  ["Wygraj zawody o zasięgu ogólnokrajowym"],
  ["Uzyskaj notę finałową 654,5", undefined, prog("wynik", 655)],
  ["Zdobądź złoto mistrzostw kraju amatorów"],
  ["Poprowadź kogoś przez zaawansowaną technikę strzelecką"],
  ["Zdobądź uznanie w krajowym środowisku strzeleckim"],
  ["Zbliż się do swojego osobistego rekordu w konkurencji", undefined, prog("wynik", 656)],
  ["Zdobądź wielokrotne medale mistrzostw kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat strzelecki", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, igrzyska) potwierdzają osobne certyfikaty."],
]);
