// Stand-up paddleboarding (SUP) ladder 1-99. Distance-logged (km/min).
// Benchmarks: recreational ~5-6 km/h; fit ~7-8 km/h; racing 10+ km/h;
// long-distance crossings and multi-day expeditions at the top.
import type { Criterion } from "../../src/lib/milestone-criteria";
import type { MilestoneResource } from "../../src/lib/milestone-resources";
import { ladder, d, t, tfd, weekly, monthly, total, freq, anyOf, prog } from "./helpers";

export const activity = {
  slug: "sup",
  name: "SUP (deska z wiosłem)",
  icon: "🏄",
  description:
    "Stand-up paddleboarding — od pierwszego kilometra po długie przeprawy i wyścigi. Trasy loguj w km.",
  sortOrder: 49,
  logKind: "distance" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Utrzymaj równowagę na desce w klęku i wiosłuj"],
  ["Wstań na desce i przepłyń 100 m na stojąco"],
  ["Wykonaj poprawne wiosłowanie do przodu (technika)"],
  ["Pokonaj 500 m bez schodzenia z desek"],
  ["Wykonaj zwrot (pivot lub step-back turn)"],
  ["Pokonaj 1 km bez przerwy"],
  ["Wiosłuj 20 minut bez przerwy"],
  ["Pokonaj 2 km bez przerwy"],
  ["Wróć do deski po upadku (samodzielnie na głębokiej wodzie)"],
  ["Pokonaj 5 km bez przerwy", "Pierwsza porządna trasa."],
  // 11-25 · Regularny
  ["Pływaj raz w tygodniu przez 4 kolejne tygodnie"],
  ["Pokonaj 6 km bez przerwy"],
  ["Pokonaj 5 km poniżej 50 minut"],
  ["Opanuj wiosłowanie przy wietrze i drobnej fali"],
  ["Pokonaj 8 km bez przerwy"],
  ["Pokonaj 15 km łącznie w jednym tygodniu"],
  ["Pokonaj 10 km bez przerwy", "Dyszka na desce."],
  ["Weź udział w pierwszym spływie lub zawodach SUP"],
  ["Pokonaj łącznie 50 km"],
  ["Pokonaj 5 km poniżej 42 minut"],
  ["Pokonaj 12 km bez przerwy"],
  ["Wiosłuj 90 minut bez przerwy"],
  ["Pokonaj 25 km łącznie w jednym tygodniu"],
  ["Pokonaj 10 km poniżej 80 minut"],
  ["Pokonaj 15 km bez przerwy"],
  // 26-45 · Średniozaawansowany
  ["Pływaj 2 razy w tygodniu przez cały sezon (12 tyg.)"],
  ["Pokonaj 5 km poniżej 38 minut"],
  ["Pokonaj 18 km bez przerwy"],
  ["Pokonaj 10 km poniżej 72 minut"],
  ["Pokonaj 40 km łącznie w jednym miesiącu"],
  ["Pokonaj 20 km bez przerwy", "Pełnodniowa trasa."],
  ["Opanuj wiosłowanie na wodzie płynącej (rzeka)"],
  ["Pokonaj łącznie 200 km"],
  ["Pokonaj 5 km poniżej 35 minut"],
  ["Pokonaj 22 km bez przerwy"],
  ["Pokonaj 30 km łącznie w jednym tygodniu"],
  ["Pokonaj 10 km poniżej 66 minut"],
  ["Ukończ przeprawę z noclegiem (2 dni z rzędu)"],
  ["Pokonaj 25 km bez przerwy"],
  ["Pokonaj 5 km poniżej 32 minut"],
  ["Pokonaj 100 km łącznie w jednym miesiącu"],
  ["Pokonaj 28 km bez przerwy"],
  ["Pokonaj 21,1 km (dystans półmaratonu) bez przerwy"],
  ["Pokonaj 10 km poniżej 62 minut"],
  ["Pokonaj 30 km bez przerwy"],
  // 46-65 · Zaawansowany
  ["Pokonaj 5 km poniżej 30 minut"],
  ["Pokonaj 40 km łącznie w jednym tygodniu"],
  ["Pokonaj 32 km bez przerwy"],
  ["Pokonaj 10 km poniżej 58 minut"],
  ["Pokonaj łącznie 1000 km"],
  ["Pokonaj 35 km bez przerwy"],
  ["Ukończ przeprawę morską/jeziorną 20 km+ na wodzie otwartej"],
  ["Pokonaj 5 km poniżej 28 minut"],
  ["Pokonaj 150 km łącznie w jednym miesiącu"],
  ["Pokonaj 38 km bez przerwy"],
  ["Pokonaj 10 km poniżej 55 minut"],
  ["Pokonaj 50 km łącznie w jednym tygodniu"],
  ["Pokonaj 42,195 km (dystans maratonu) bez przerwy", "Maraton SUP — dowolny czas."],
  ["Pokonaj 5 km poniżej 26 minut"],
  ["Pokonaj łącznie 2000 km"],
  ["Pokonaj 10 km poniżej 52 minut"],
  ["Ukończ wyścig maratoński SUP w zawodach"],
  ["Pokonaj 45 km bez przerwy"],
  ["Pokonaj 200 km łącznie w jednym miesiącu"],
  ["Pokonaj 5 km poniżej 24 minut"],
  // 66-85 · Wyczynowy
  ["Pokonaj 10 km poniżej 50 minut"],
  ["Pokonaj 60 km łącznie w jednym tygodniu"],
  ["Pokonaj 50 km bez przerwy"],
  ["Pokonaj 5 km poniżej 23 minut"],
  ["Ukończ przeprawę open ocean 30 km+ (downwind)"],
  ["Pokonaj łącznie 3000 km"],
  ["Pokonaj 10 km poniżej 48 minut"],
  ["Pokonaj 250 km łącznie w jednym miesiącu"],
  ["Pokonaj 55 km bez przerwy"],
  ["Pokonaj 5 km poniżej 22 minut"],
  ["Pokonaj 42,195 km poniżej 4 godzin"],
  ["Pokonaj 70 km łącznie w jednym tygodniu"],
  ["Pokonaj 60 km bez przerwy"],
  ["Pokonaj 10 km poniżej 46 minut"],
  ["Pokonaj łącznie 5000 km"],
  ["Pokonaj 5 km poniżej 21 minut"],
  ["Ukończ wielodniową ekspedycję 100 km+ (3+ dni)"],
  ["Pokonaj 42,195 km poniżej 3:30"],
  ["Pokonaj 300 km łącznie w jednym miesiącu"],
  ["Pokonaj 70 km bez przerwy"],
  // 86-99 · Elita
  ["Pokonaj 10 km poniżej 44 minut"],
  ["Pokonaj 5 km poniżej 20 minut", "Tempo 15 km/h — poziom wyścigowy."],
  ["Pokonaj 90 km łącznie w jednym tygodniu"],
  ["Ukończ długodystansowy wyścig SUP rangi międzynarodowej"],
  ["Pokonaj 42,195 km poniżej 3:10"],
  ["Pokonaj 80 km bez przerwy"],
  ["Pokonaj 10 km poniżej 42 minut"],
  ["Pokonaj łącznie 10 000 km"],
  ["Pokonaj 100 km bez przerwy", "Setka na desce — ultra SUP."],
  ["Pokonaj 5 km poniżej 19 minut"],
  ["Pokonaj 42,195 km poniżej 3:00"],
  ["Zdobądź podium w wyścigu SUP rangi mistrzowskiej"],
  ["Pokonaj 10 km poniżej 40 minut"],
  ["Poziom mistrzowski: 42,195 km poniżej 2:50 lub start w regionalnych zawodach mistrzowskich", "Wyczynowi zawodnicy SUP pokonują maraton w tempie ponad 15 km/h."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  2: d(0.1), 4: d(0.5), 6: d(1), 7: t(20), 8: d(2), 10: d(5),
  1: prog("technika", 1), 3: prog("technika", 2), 5: prog("technika", 3), 9: prog("technika", 4),
  11: freq(1, 4), 12: d(6), 13: tfd(5, 50), 15: d(8), 16: weekly(15),
  17: d(10), 19: total(50), 20: tfd(5, 42), 21: d(12), 22: t(90),
  23: weekly(25), 24: tfd(10, 80), 25: d(15),
  26: freq(2, 12), 27: tfd(5, 38), 28: d(18), 29: tfd(10, 72), 30: monthly(40),
  31: d(20), 33: total(200), 34: tfd(5, 35), 35: d(22), 36: weekly(30),
  37: tfd(10, 66), 39: d(25), 40: tfd(5, 32), 41: monthly(100), 42: d(28),
  43: d(21.1), 44: tfd(10, 62), 45: d(30),
  46: tfd(5, 30), 47: weekly(40), 48: d(32), 49: tfd(10, 58), 50: total(1000),
  51: d(35), 53: tfd(5, 28), 54: monthly(150), 55: d(38), 56: tfd(10, 55),
  57: weekly(50), 58: d(42.195), 59: tfd(5, 26), 60: total(2000), 61: tfd(10, 52),
  63: d(45), 64: monthly(200), 65: tfd(5, 24),
  66: tfd(10, 50), 67: weekly(60), 68: d(50), 69: tfd(5, 23), 71: total(3000),
  72: tfd(10, 48), 73: monthly(250), 74: d(55), 75: tfd(5, 22), 76: tfd(42.195, 240),
  77: weekly(70), 78: d(60), 79: tfd(10, 46), 80: total(5000), 81: tfd(5, 21),
  83: tfd(42.195, 210), 84: monthly(300), 85: d(70),
  86: tfd(10, 44), 87: tfd(5, 20), 88: weekly(90), 90: tfd(42.195, 190),
  91: d(80), 92: tfd(10, 42), 93: total(10000), 94: d(100), 95: tfd(5, 19),
  96: tfd(42.195, 180), 98: tfd(10, 40),
  99: anyOf(tfd(42.195, 170), prog("mistrzostwa", 1)),
  // 14, 18, 32, 38, 52, 62, 70, 82, 89, 97 — technika/przeprawy/zawody: manualne.
};

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "SUP basics — how to stand up paddle board", url: yt("0MdaBz0EMWM") }],
  3: [{ kind: "video", title: "SUP paddle technique — proper forward stroke", url: yt("9kj4jVCt5Kk") }],
  5: [{ kind: "video", title: "How to turn on a SUP — pivot and sweep", url: yt("YIGJwSBbgJ4") }],
  10: [{ kind: "article", title: "Stand up paddleboarding for beginners — REI guide", url: "https://www.rei.com/learn/expert-advice/stand-up-paddleboarding.html" }],
  14: [{ kind: "video", title: "SUP in wind and chop — tips for rough water", url: yt("7pVgR7hk-qc") }],
  25: [{ kind: "video", title: "SUP long distance paddling tips", url: yt("uSKd3XqYfvo") }],
  32: [{ kind: "video", title: "River SUP — paddling moving water", url: yt("OfXTqf3m3ek") }],
  52: [{ kind: "video", title: "SUP racing technique — go faster", url: yt("2aPPqrN6z6c") }],
  58: [{ kind: "article", title: "SUP marathon training — preparation guide", url: "https://www.supracer.com/category/training/" }],
  70: [{ kind: "video", title: "SUP downwind — ocean paddling skills", url: yt("Bvf5TgR7YtM") }],
};
