// Surfing ladder 1-99. Manual — progression tracks: wave height mastered,
// board volume/size (bigger foamie → shorter shortboard), maneuvers, sessions.
import type { Criterion } from "../../src/lib/milestone-criteria";
import type { MilestoneResource } from "../../src/lib/milestone-resources";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "surfing",
  name: "Surfing",
  icon: "🏄",
  description:
    "Od pianki i białej piany po zawodowe fale. Progresja: rozmiar opanowanych fal, deska (od miękkiej long po short) i manewry.",
  sortOrder: 23,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Połóż się na desce i złap równowagę na wodzie"],
  ["Zrób poprawny take-off (pop-up) na piasku"],
  ["Przepłyń białą pianę leżąc na desce"],
  ["Wstań na desce w białej pianie (softboard)"],
  ["Utrzymaj się na desce przez 3 sekundy jadąc prosto"],
  ["Przejedź całą białą pianę do brzegu na stojąco"],
  ["Samodzielnie złap falę bez popchnięcia"],
  ["Wiosłuj za strefę załamania fal (line-up)"],
  ["Złap nierozbitą, zieloną falę"],
  ["Przejedź zieloną falę w linii prostej", "Pierwszy prawdziwy surf."],
  // 11-25 · Regularny
  ["Surfuj raz w tygodniu przez 4 kolejne tygodnie (lub obóz)"],
  ["Wykonaj skręt (bottom turn) w podstawie fali"],
  ["Jedź wzdłuż fali (trim) w jedną stronę"],
  ["Jedź wzdłuż fali w drugą stronę"],
  ["Opanuj duck dive lub turtle roll pod nadciągającą falą"],
  ["Zaliczy 20 sesji surfingowych"],
  ["Surfuj falę o wysokości do pasa"],
  ["Wykonaj serię 3 skrętów na jednej fali"],
  ["Złap falę na tłocznym line-upie zgodnie z priorytetem"],
  ["Surfuj na desce funboard/mini-malibu"],
  ["Zaliczy 40 sesji surfingowych"],
  ["Surfuj falę o wysokości do klatki piersiowej"],
  ["Wykonaj cutback (powrót do mocy fali)"],
  ["Przejedź sekcję fali, która się zamyka (dokończ przed białą pianą)"],
  ["Surfuj w obu ustawieniach: frontside i backside"],
  // 26-45 · Średniozaawansowany
  ["Surfuj regularnie przez cały wyjazd (2 tyg. codziennie)"],
  ["Zaliczy 75 sesji surfingowych"],
  ["Surfuj na desce shortboard (poniżej 7 stóp)"],
  ["Surfuj falę wysokości głowy"],
  ["Wykonaj płynny cutback frontside i backside"],
  ["Generuj prędkość pompowaniem (pumping) na ścianie fali"],
  ["Zaliczy 100 sesji surfingowych"],
  ["Wykonaj floater na zamykającej się sekcji"],
  ["Surfuj na rafie lub w miejscu z prądem powrotnym (rip)"],
  ["Wykonaj re-entry (uderzenie w grzbiet fali i powrót)"],
  ["Surfuj falę o wysokości głowy i pół"],
  ["Zaliczy 150 sesji surfingowych"],
  ["Wykonaj snap (ostry skręt w górnej części fali)"],
  ["Złap i przejedź 10 fal w jednej sesji"],
  ["Surfuj deskę poniżej 6 stóp"],
  ["Wykonaj serię manewrów: bottom turn → snap → cutback"],
  ["Zaliczy 200 sesji surfingowych"],
  ["Surfuj w warunkach offshore z równymi, czystymi falami"],
  ["Wykonaj mały aerial (odklejenie deski od wody)"],
  ["Surfuj falę wysokości 2x wzrostu"],
  // 46-65 · Zaawansowany
  ["Zaliczy 300 sesji surfingowych"],
  ["Surfuj w tubie (choćby krótkie zakrycie)", "Marzenie każdego surfera."],
  ["Wykonaj czysty aerial z lądowaniem"],
  ["Surfuj falę wysokości 2,5 m"],
  ["Zaliczy 400 sesji surfingowych"],
  ["Utrzymaj się w tubie i wyjedź z niej"],
  ["Wygraj heat w lokalnych zawodach"],
  ["Surfuj point break z długim przejazdem (100+ m)"],
  ["Zaliczy 500 sesji surfingowych"],
  ["Surfuj falę wysokości 3 m"],
  ["Wykonaj serię aerialów w jednej sesji"],
  ["Surfuj o świcie (dawn patrol) przez tydzień z rzędu"],
  ["Zaliczy 600 sesji surfingowych"],
  ["Surfuj rafę koralową (płytkie dno)"],
  ["Wykonaj barrel na backside"],
  ["Surfuj falę wysokości 4 m"],
  ["Zaliczy 750 sesji surfingowych"],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Surfuj znaną, wymagającą falę na świecie", "Np. Uluwatu, Hossegor, Nazaré (mniejszy dzień)."],
  ["Surfuj falę wysokości 5 m"],
  // 66-85 · Wyczynowy
  ["Zaliczy 1000 sesji surfingowych"],
  ["Wykonaj długi, głęboki barrel z wyjazdem"],
  ["Surfuj falę wysokości 6 m"],
  ["Zwyciężaj w zawodach regionalnych"],
  ["Zaliczy 1250 sesji surfingowych"],
  ["Surfuj w ciężkich warunkach (heavy wave) z bezpiecznym wyjściem"],
  ["Wykonaj zaawansowany aerial (rotacja 360°)"],
  ["Surfuj falę wysokości 7 m"],
  ["Zaliczy 1500 sesji surfingowych"],
  ["Zdobądź sponsora lub zostań ambasadorem marki"],
  ["Surfuj falę wysokości 8 m"],
  ["Wystąp w zawodach rangi krajowej"],
  ["Zaliczy 2000 sesji surfingowych"],
  ["Surfuj big wave z holowaniem (tow-in) lub na wiosło 8 m+"],
  ["Zajmij miejsce w czołówce mistrzostw kraju"],
  ["Surfuj falę wysokości 10 m"],
  ["Zaliczy 2500 sesji surfingowych"],
  ["Zdobądź tytuł mistrza kraju"],
  ["Surfuj kultową big-wave (np. Jaws, Mavericks — mniejszy dzień)"],
  ["Surfuj falę wysokości 12 m"],
  // 86-99 · Elita
  ["Zaliczy 3000 sesji surfingowych"],
  ["Weź udział w zawodach o zasięgu ogólnokrajowym"],
  ["Surfuj falę wysokości 15 m"],
  ["Wykonaj przejazd oceniony wysoko przez doświadczonych sędziów lokalnych"],
  ["Zaliczy 4000 sesji surfingowych"],
  ["Surfuj wymagającą, znaną falę w swoim regionie w dużym dniu"],
  ["Zdobądź punkty w rankingu o zasięgu ogólnokrajowym"],
  ["Surfuj falę wysokości 18 m"],
  ["Zaliczy 5000 sesji surfingowych"],
  ["Zdobądź uznanie w krajowym środowisku big-wave"],
  ["Surfuj falę wysokości 20 m"],
  ["Zwycięż w zawodach o zasięgu ogólnokrajowym"],
  ["Poprowadź kogoś przez zaawansowaną technikę surfingu big-wave"],
  ["Poziom mistrzowski (amatorski szczyt): przejazd na fali 20 m+ i wieloletni, dojrzały warsztat", "Dalsze, zawodowe osiągnięcia (Championship Tour, Big Wave Tour) potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  1: prog("technika", 1), 2: prog("technika", 2), 3: prog("technika", 3), 4: prog("technika", 4),
  5: prog("technika", 5), 6: prog("technika", 6), 7: prog("technika", 7), 8: prog("technika", 8),
  9: prog("technika", 9), 10: prog("technika", 10),
  16: prog("sesje", 20), 21: prog("sesje", 40), 27: prog("sesje", 75), 32: prog("sesje", 100),
  37: prog("sesje", 150), 42: prog("sesje", 200), 46: prog("sesje", 300), 50: prog("sesje", 400),
  54: prog("sesje", 500), 58: prog("sesje", 600), 62: prog("sesje", 750), 66: prog("sesje", 1000),
  70: prog("sesje", 1250), 74: prog("sesje", 1500), 78: prog("sesje", 2000), 82: prog("sesje", 2500),
  86: prog("sesje", 3000), 90: prog("sesje", 4000), 94: prog("sesje", 5000),
  17: prog("fala", 1), 22: prog("fala", 2), 29: prog("fala", 3), 35: prog("fala", 4),
  40: prog("fala", 5), 45: prog("fala", 6), 49: prog("fala", 7), 55: prog("fala", 8),
  60: prog("fala", 10), 65: prog("fala", 12), 69: prog("fala", 15), 73: prog("fala", 17),
  77: prog("fala", 20), 81: prog("fala", 25), 85: prog("fala", 30),
  88: prog("fala", 40), 93: prog("fala", 50), 97: prog("fala", 60),
  11: freq(1, 4),
  // pozostałe: manewry, zawody, wydarzenia — manualne.
};

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "How to surf — complete beginner guide", url: yt("QvinPaxS30E") }],
  4: [{ kind: "video", title: "How to stand up on a surfboard — popup technique", url: yt("w5fg_gMx7YY") }],
  9: [{ kind: "video", title: "How to catch unbroken green waves", url: yt("r0dcv6GKNNs") }],
  12: [{ kind: "video", title: "How to bottom turn — surfing fundamentals", url: yt("4xgKYVJHBL4") }],
  15: [{ kind: "video", title: "How to duck dive — get through waves", url: yt("SaxKLBricks") }],
  23: [{ kind: "video", title: "How to do a cutback — surf maneuver", url: yt("zH-KkNdgfdI") }],
  28: [{ kind: "article", title: "Choosing your first shortboard — guide", url: "https://www.surfer.com/features/choosing-your-first-shortboard" }],
  37: [{ kind: "video", title: "How to do a floater — surf trick tutorial", url: yt("rN8aSOB4pR0") }],
  47: [{ kind: "video", title: "How to get barreled — tube riding tips", url: yt("CKoiEmYD9aw") }],
  63: [{ kind: "article", title: "Big wave surfing — safety and preparation", url: "https://www.surfer.com/features/big-wave-essentials" }],
};
