// Chess ladder 1-99 — REALISTIC amateur-progression scale. A dedicated amateur's
// realistic ceiling is ~2200 Elo (national candidate master / strong club master),
// NOT 2850 / GM. Pro titles (FM/IM/GM) and super-GM ratings are certificate
// territory. Tracks: elo (rating, capped 2200), technika (skills), liga
// (tournament/category level), + amateur achievement milestones.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "szachy",
  name: "Szachy",
  icon: "♟️",
  description:
    "Królewska gra strategiczna — od reguł po poziom kandydata na mistrza. Poziomy 1–99 to realna droga amatora: ranking Elo, technika i turnieje. Tytuły zawodowe (FM/IM/GM) potwierdzają osobne certyfikaty.",
  sortOrder: 78,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Naucz się ruchów wszystkich bierek i zasad (roszada, bicie w przelocie)", undefined, prog("technika", 1)],
  ["Daj pierwszego mata (np. mat szewski lub hetmanem)", undefined, prog("technika", 2)],
  ["Opanuj wartość bierek i podstawy wymiany", undefined, prog("technika", 3)],
  ["Zamatuj samotnego króla wieżą i hetmanem", undefined, prog("technika", 4)],
  ["Rozegraj pełną partię z zegarem", undefined, prog("technika", 5)],
  ["Poznaj podstawowe zasady otwarć (rozwój, centrum, król)", undefined, prog("technika", 6)],
  ["Rozwiąż proste zadania na mata w 1-2 ruchach", undefined, prog("technika", 7)],
  ["Zagraj pierwszy turniej (lokalny lub online rated)", undefined, prog("liga", 1)],
  ["Osiągnij ranking 800 Elo (online lub krajowy)", undefined, prog("elo", 800)],
  ["Wygraj pierwszą partię turniejową"],
  // 11-25 · Regularny
  ["Graj i analizuj partie regularnie przez 4 tygodnie", undefined, freq(2, 4)],
  ["Osiągnij ranking 1000 Elo", undefined, prog("elo", 1000)],
  ["Opanuj podstawowe taktyki (widełki, związanie, odsłona)", undefined, prog("technika", 8)],
  ["Osiągnij ranking 1100 Elo", undefined, prog("elo", 1100)],
  ["Rozegraj poprawnie końcówkę pion + król (opozycja)", undefined, prog("technika", 9)],
  ["Osiągnij ranking 1200 Elo", undefined, prog("elo", 1200)],
  ["Zbuduj repertuar jednego otwarcia dla białych i czarnych", undefined, prog("technika", 10)],
  ["Osiągnij ranking 1300 Elo", undefined, prog("elo", 1300)],
  ["Zdobądź kategorię szachową (np. V lub IV kat. PZSzach)", undefined, prog("liga", 2)],
  ["Osiągnij ranking 1400 Elo", undefined, prog("elo", 1400)],
  ["Rozwiązuj zadania taktyczne na mata w 3-4 ruchach", undefined, prog("technika", 11)],
  ["Osiągnij ranking 1500 Elo", undefined, prog("elo", 1500)],
  ["Wygraj partię ofiarą kombinacyjną", undefined, prog("technika", 12)],
  ["Osiągnij ranking 1600 Elo", "Solidny gracz klubowy.", prog("elo", 1600)],
  ["Zdobądź kategorię III/II PZSzach", undefined, prog("liga", 3)],
  // 26-45 · Średniozaawansowany
  ["Studiuj szachy systematycznie przez 12 tygodni", undefined, freq(3, 12)],
  ["Osiągnij ranking 1650 Elo", undefined, prog("elo", 1650)],
  ["Opanuj końcówki wieżowe (podstawowe pozycje teoretyczne)", undefined, prog("technika", 13)],
  ["Osiągnij ranking 1700 Elo", undefined, prog("elo", 1700)],
  ["Zajmij miejsce w pierwszej połowie turnieju z rankingiem FIDE"],
  ["Osiągnij ranking 1750 Elo", undefined, prog("elo", 1750)],
  ["Zbuduj głęboki repertuar debiutowy (kilka systemów)", undefined, prog("technika", 14)],
  ["Osiągnij ranking 1800 Elo", undefined, prog("elo", 1800)],
  ["Zdobądź I kategorię szachową", undefined, prog("liga", 4)],
  ["Osiągnij ranking 1850 Elo", undefined, prog("elo", 1850)],
  ["Wygraj partię przeciwko graczowi 1900+", undefined, prog("technika", 15)],
  ["Osiągnij ranking 1900 Elo", undefined, prog("elo", 1900)],
  ["Zajmij miejsce na podium turnieju amatorskiego"],
  ["Rozwiąż tysiące zadań taktycznych (trening wzorców)"],
  ["Opanuj strategię pozycyjną (słabe pola, struktura pionów)", undefined, prog("technika", 16)],
  ["Osiągnij ranking 1950 Elo", undefined, prog("elo", 1950)],
  ["Wygraj klubowy turniej lub ligę drużynową na swoim poziomie"],
  ["Osiągnij ranking 2000 Elo", "Ekspert — próg zaawansowanego szachisty.", prog("elo", 2000)],
  ["Zagraj setki partii turniejowych z analizą", undefined, prog("technika", 17)],
  ["Zajmij miejsce w czołówce turnieju regionalnego"],
  // 46-65 · Zaawansowany (amator)
  ["Trenuj z coachem/silnikiem i bazą partii przez cały sezon"],
  ["Osiągnij ranking 2050 Elo", undefined, prog("elo", 2050)],
  ["Opanuj głęboką analizę końcówek i przewag strukturalnych", undefined, prog("technika", 18)],
  ["Zdobądź tytuł kandydata na mistrza (CM) lub odpowiednik krajowy", undefined, prog("liga", 5)],
  ["Osiągnij ranking 2100 Elo", undefined, prog("elo", 2100)],
  ["Wygraj partię przeciwko graczowi 2100+", undefined, prog("technika", 19)],
  ["Wygraj turniej rangi regionalnej"],
  ["Osiągnij ranking 2130 Elo", undefined, prog("elo", 2130)],
  ["Prowadź własne przygotowanie debiutowe na poziomie mistrzowskim", undefined, prog("technika", 20)],
  ["Zajmij miejsce w czołówce mistrzostw okręgu/województwa"],
  ["Osiągnij ranking 2160 Elo", undefined, prog("elo", 2160)],
  ["Poprowadź kogoś od podstaw do gry turniejowej"],
  ["Wygraj mecz z zawodnikiem z tytułem kandydata na mistrza"],
  ["Osiągnij ranking 2180 Elo", undefined, prog("elo", 2180)],
  ["Zbuduj bogaty warsztat końcówkowy i taktyczny", undefined, prog("technika", 21)],
  ["Zajmij miejsce na podium silnego turnieju amatorskiego"],
  ["Osiągnij ranking 2200 Elo", "Poziom kandydata na mistrza — realny szczyt amatora.", prog("elo", 2200)],
  ["Weź udział w mistrzostwach kraju amatorów", undefined, prog("liga", 6)],
  ["Utrzymaj ranking 2200+ przez cały sezon"],
  ["Wygraj silny turniej open na poziomie amatorskim"],
  // 66-85 · Ekspert (amatorski szczyt)
  ["Graj wyrównane partie z zawodnikami tytularnymi"],
  ["Zajmij miejsce w pierwszej połowie mistrzostw kraju amatorów"],
  ["Prowadź analizy partii dla innych szachistów", undefined, prog("technika", 22)],
  ["Utrzymuj wysoki, stabilny poziom przez wiele sezonów"],
  ["Wygraj partię przeciwko graczowi z tytułem FIDE"],
  ["Zdobądź podium mistrzostw okręgu/województwa seniorów"],
  ["Reprezentuj swój klub w rozgrywkach drużynowych wysokiej klasy"],
  ["Opanuj przygotowanie przeciwko konkretnym przeciwnikom (scouting)", undefined, prog("technika", 23)],
  ["Wygraj kilka turniejów regionalnych w jednym sezonie"],
  ["Rozwiń warsztat na tyle, by uczyć/trenować szachistów"],
  ["Zbuduj rozpoznawalną pozycję w lokalnym środowisku szachowym"],
  ["Zajmij miejsce w czołówce silnego turnieju o zasięgu krajowym"],
  ["Prowadź własnych podopiecznych do sukcesów turniejowych"],
  ["Osiągnij mistrzowski warsztat we wszystkich fazach gry", undefined, prog("technika", 24)],
  ["Zdobądź podium mistrzostw kraju amatorów"],
  ["Wygraj prestiżowy turniej amatorski o zasięgu krajowym"],
  ["Zdobądź uznanie środowiska szachowego w kraju"],
  ["Zostań mistrzem kraju amatorów w swojej kategorii"],
  ["Utrzymuj poziom kandydata na mistrza przez wiele lat"],
  ["Publikuj analizy lub materiały szkoleniowe dla szachistów"],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Prowadź własną sekcję / szkółkę szachową"],
  ["Twoje partie i analizy inspirują innych graczy"],
  ["Wychowaj zawodnika, który zdobywa własne sukcesy turniejowe"],
  ["Zagraj mecz towarzyski z uznanym arcymistrzem"],
  ["Utrzymaj się w czołówce rankingu amatorów kraju"],
  ["Zbuduj bogaty dorobek turniejowy (dziesiątki wygranych turniejów)"],
  ["Twoja wiedza szachowa jest na poziomie eksperckim, mistrzowskim"],
  ["Zorganizuj turniej lub wydarzenie szachowe dla społeczności"],
  ["Zdobądź wielokrotne mistrzostwo kraju amatorów"],
  ["Bądź mentorem i autorytetem w swoim środowisku szachowym"],
  ["Utrzymuj poziom mistrzowski i dziel się nim z kolejnym pokoleniem"],
  ["Masz dorobek, z którego można ułożyć retrospektywę partii"],
  ["Grasz na poziomie, o którym marzy większość amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): kandydat na mistrza z wieloletnim, dojrzałym warsztatem", "Dalsze, zawodowe tytuły (FM, IM, GM) i mistrzostwo świata potwierdzają osobne certyfikaty."],
]);

import type { MilestoneResource } from "../../src/lib/milestone-resources";
const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  // — Rozszerzenie zasobów Tier 1 (wszystkie linki zweryfikowane jako aktywne) —
  3: [{ kind: "video", title: "Wymiana bierek — kiedy opłaca się bić (wartość figur w praktyce)", url: yt("GOZKmnRkSMU") }],
  4: [{ kind: "video", title: "Mat samotnemu królowi hetmanem — technika krok po kroku", url: yt("CSA9se6t82I") }],
  6: [{ kind: "video", title: "Podstawowe zasady otwarć wyjaśnione", url: yt("8IlJ3v8I4Z8") }],
  8: [{ kind: "article", title: "Jak przygotować się do turnieju szachowego — kompletny poradnik", url: "https://thechessworld.com/articles/training-techniques/tournament-preparation-complete-guide/" }],
  9: [{ kind: "video", title: "7 najczęstszych błędów początkujących w szachach", url: yt("SXrKRA_KZ5k") }],
  10: [{ kind: "video", title: "Jak analizować własne partie — prosty sposób (GM Noel Studer)", url: yt("shma5hsckww") }],
  11: [{ kind: "article", title: "Plan nauki szachów — gotowe programy treningowe wg poziomu", url: "https://www.chess.com/article/view/study-plan-directory" }],
  12: [{ kind: "video", title: "Taktyka dla początkujących: widełki, związanie, szpila", url: yt("MbMslp2WcI0") }],
  14: [{ kind: "article", title: "Lichess czy Chess.com — którą platformę wybrać", url: "https://www.chess.com/blog/avii_ar/lichess-vs-chess-com-which-one-should-you-use" }],
  16: [{ kind: "video", title: "Jak zbudować repertuar debiutowy (Hanging Pawns)", url: yt("nr-_W6Eujzg") }],
  20: [{ kind: "video", title: "Podstawy końcówek pionowych — wprowadzenie (GM Naroditsky)", url: yt("QUqq7wSLE78") }],
  24: [{ kind: "article", title: "Szachy pozycyjne — kompletny przewodnik", url: "https://thechessworld.com/articles/general-information/positional-chess-complete-guide/" }],
  30: [{ kind: "video", title: "Jak skutecznie studiować partie mistrzów", url: yt("Q_IZG57UBCE") }],
  35: [{ kind: "video", title: "Końcówki wieżowe — pozycje Luceny i Philidora", url: yt("rDist9x7szE") }],
  40: [{ kind: "video", title: "Zaawansowana taktyka — trudne zadania z GM Naroditskym", url: yt("1EV8XLSZsho") }],
  1: [{ kind: "video", title: "How to play chess — complete rules", url: yt("OCSbzArwB10") }],
  2: [{ kind: "video", title: "How to checkmate", url: yt("4wRBjlJGMbg") }],
  5: [{ kind: "video", title: "Chess openings basics", url: yt("3qfBIboJjN4") }],
  7: [{ kind: "video", title: "Chess puzzles — mate in 1 and 2", url: yt("52mfuE-YtOs") }],
  13: [{ kind: "video", title: "Chess tactics for beginners (forks, pins, skewers)", url: yt("nFAMHBBwERk") }],
  15: [{ kind: "video", title: "King and pawn endgame", url: yt("wl3eHK4JfbY") }],
  17: [{ kind: "video", title: "Building an opening repertoire", url: yt("F47pMu2Mf-0") }],
  22: [{ kind: "video", title: "Tactical puzzles training", url: yt("e3rSaL6oN1k") }],
  29: [{ kind: "video", title: "Rook endgame fundamentals", url: yt("GJhRZ_0Ykks") }],
  38: [{ kind: "video", title: "Positional chess strategy", url: yt("8V2f39ukN6c") }],
  44: [{ kind: "video", title: "How to reach 2000 Elo", url: yt("fOTLvJmJ1ds") }],
  60: [{ kind: "article", title: "Expert level chess preparation", url: "https://www.chess.com/article/view/how-to-become-a-chess-master" }],
};
