// Sewing / dressmaking ladder 1-99 — REALISTIC personal-progression scale
// (dedicated hobbyist; hours capped ~1200, project counts scaled; top tiers
// reframed as attainable mastery, real feats left to future certificates).
// Tracks: umiejetnosci, projekty (finished pieces), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "szycie",
  name: "Szycie / krawiectwo",
  icon: "🧵",
  description:
    "Od pierwszego równego szwu po szyte na miarę ubrania i konstrukcję wykrojów. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → własne projekty → dojrzały, autorski warsztat.",
  sortOrder: 88,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Nawlecz maszynę i zrób równy szew prosty", undefined, prog("umiejetnosci", 1)],
  ["Utrzymaj stały margines szwu (naddatek)", undefined, prog("umiejetnosci", 2)],
  ["Zrób szew wykończeniowy (obrębienie / zygzak)", undefined, prog("umiejetnosci", 3)],
  ["Wszyj zamek prosty", undefined, prog("umiejetnosci", 4)],
  ["Zrób prosty projekt (poszewka / worek / fartuch)", undefined, prog("projekty", 2)],
  ["Prasuj szwy i pracuj czysto", undefined, prog("umiejetnosci", 5)],
  ["Przyszyj guzik i zrób dziurkę", undefined, prog("umiejetnosci", 6)],
  ["Rozczytaj prosty wykrój z instrukcją", undefined, prog("umiejetnosci", 7)],
  ["Ukończ 4 projekty", undefined, prog("projekty", 4)],
  ["Szyj łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Szyj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(2, 4)],
  ["Uszyj prostą spódnicę lub spodnie z gumą", undefined, prog("umiejetnosci", 8)],
  ["Wykończ brzegi (lamówka, podwinięcie)", undefined, prog("umiejetnosci", 9)],
  ["Uszyj koszulę / bluzkę z kołnierzem", undefined, prog("umiejetnosci", 10)],
  ["Ukończ 8 projektów", undefined, prog("projekty", 8)],
  ["Szyj łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Wszyj rękaw i mankiet", undefined, prog("umiejetnosci", 11)],
  ["Uszyj sukienkę z podszewką", undefined, prog("umiejetnosci", 12)],
  ["Ukończ 14 projektów", undefined, prog("projekty", 14)],
  ["Dopasuj wykrój do własnych wymiarów (pomiary)", undefined, prog("umiejetnosci", 13)],
  ["Zrób próbkę i sprawdź krój przed szyciem", undefined, prog("umiejetnosci", 14)],
  ["Szyj łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Uszyj projekt z kilku elementów (kurtka prosta)", undefined, prog("projekty", 22)],
  ["Wszyj zamek kryty i inne rodzaje zamków", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 30 projektów", undefined, prog("projekty", 30)],
  // 26-45 · Średniozaawansowany
  ["Szyj regularnie przez 8 kolejnych tygodni", undefined, freq(2, 8)],
  ["Uszyj dopasowany żakiet z podszewką", undefined, prog("umiejetnosci", 16)],
  ["Opanuj zaszewki i modelowanie sylwetki", undefined, prog("umiejetnosci", 17)],
  ["Ukończ 40 projektów", undefined, prog("projekty", 40)],
  ["Dopasuj krój do figury (poprawki krawieckie)", undefined, prog("umiejetnosci", 18)],
  ["Szyj łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Pracuj z trudnymi tkaninami (dzianina, jedwab, skóra)", undefined, prog("umiejetnosci", 19)],
  ["Uszyj płaszcz lub marynarkę", undefined, prog("umiejetnosci", 20)],
  ["Ukończ 55 projektów", undefined, prog("projekty", 55)],
  ["Wykończ pracę na poziomie sklepowym (detale, prasowanie)", undefined, prog("umiejetnosci", 21)],
  ["Uszyj strój wieczorowy / złożoną sukienkę", undefined, prog("umiejetnosci", 22)],
  ["Szyj łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Zrób dużą, złożoną realizację (garnitur / suknia)", undefined, prog("projekty", 70)],
  ["Opanuj krawieckie techniki (wewnętrzna konstrukcja marynarki)", undefined, prog("umiejetnosci", 23)],
  ["Zmodyfikuj gotowy wykrój według pomysłu", undefined, prog("umiejetnosci", 24)],
  ["Ukończ 85 projektów", undefined, prog("projekty", 85)],
  ["Opanuj detale couture (ręczne wykończenia, wnętrza)", undefined, prog("umiejetnosci", 25)],
  ["Szyj łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Uszyj projekt na najwyższym własnym poziomie wykończenia", undefined, prog("umiejetnosci", 26)],
  ["Prowadź projekty regularnie przez 3 miesiące", undefined, prog("projekty", 100)],
  // 46-65 · Zaawansowany (amator)
  ["Szyj regularnie przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Skonstruuj własny prosty wykrój od podstaw", undefined, prog("umiejetnosci", 27)],
  ["Uszyj spójną kolekcję (kilka elementów)", undefined, prog("umiejetnosci", 28)],
  ["Ukończ 120 projektów", undefined, prog("projekty", 120)],
  ["Szyj łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Pokaż prace publicznie i zbierz opinie odbiorców"],
  ["Skonstruuj wykrój odzieży dopasowanej do figury", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 150 projektów", undefined, prog("projekty", 150)],
  ["Opanuj wybraną specjalizację (krawiectwo / bielizna / kostiumy)", undefined, prog("umiejetnosci", 30)],
  ["Szyj łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj portfolio najlepszych realizacji"],
  ["Weź udział w pokazie / konkursie lub sprzedaj pracę"],
  ["Skonstruuj skomplikowany wykrój (żakiet z konstrukcją)", undefined, prog("umiejetnosci", 31)],
  ["Ukończ 180 projektów", undefined, prog("projekty", 180)],
  ["Szyj na zamówienie / na miarę dla kogoś", undefined, prog("umiejetnosci", 32)],
  ["Szyj łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy szycia", undefined, prog("umiejetnosci", 33)],
  ["Zrealizuj spójny cykl / mini-kolekcję"],
  ["Uszyj realizację couture na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 220 projektów", undefined, prog("projekty", 220)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Szyj regularnie przez pełny sezon (6 miesięcy)"],
  ["Projektuj i konstruuj własne wykroje swobodnie", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 270 projektów", undefined, prog("projekty", 270)],
  ["Szyj łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Zrealizuj kolekcję i pokaż ją (lokalnie / online)"],
  ["Rozwiń warsztat na tyle, by uczyć szycia", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie szyjesz na zamówienie / sprzedajesz"],
  ["Opanuj krawiectwo miarowe na wysokim poziomie", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 330 projektów", undefined, prog("projekty", 330)],
  ["Zdobądź wyróżnienie lub uznanie w społeczności"],
  ["Szyj łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny projekt autorski (suknia / kolekcja)", undefined, prog("umiejetnosci", 38)],
  ["Twoje realizacje są dopracowane w każdym detalu", undefined, prog("umiejetnosci", 39)],
  ["Ukończ 400 projektów", undefined, prog("projekty", 400)],
  ["Zbuduj grono klientów / odbiorców swoich prac"],
  ["Poprowadź warsztaty lub mentoring dla szyjących"],
  ["Zaprojektuj spójną kolekcję z własnych wykrojów"],
  ["Zrealizuj pokaz lub publikację prezentującą dorobek"],
  ["Ukończ 480 projektów", undefined, prog("projekty", 480)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Szyj łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdej realizacji"],
  ["Ukończ 560 projektów", undefined, prog("projekty", 560)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych szyjących w Twoim otoczeniu"],
  ["Zrealizuj osobisty „opus” — suknię lub kolekcję couture", undefined, prog("umiejetnosci", 40)],
  ["Regularnie pokazujesz kolekcje lub szyjesz couture"],
  ["Szyj łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje prace zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 650 projektów", undefined, prog("projekty", 650)],
  ["Uczysz i kształtujesz kolejnych krawców"],
  ["Masz dorobek, z którego można ułożyć pokaz retrospektywny"],
  ["Uszyjesz niemal wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski warsztat", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (szycie / krawiectwo: Made to Sew, Professor Pincushion i in.).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Równy szew prosty (od nawlekania)", url: yt("tg6_ILHQ_q4") }],
  2: [{ kind: "video", title: "Margines szwu (seam allowance)", url: yt("c0q_U9cPkGA") }],
  3: [{ kind: "video", title: "Wykończenie brzegów zygzakiem", url: yt("Ra49p5_V5Eo") }],
  4: [{ kind: "video", title: "Wszywanie zamka (podstawy)", url: yt("OlpCOp8p6oI") }],
  6: [{ kind: "video", title: "Prasowanie szwów podczas szycia", url: yt("f3spq-JTJ1w") }],
  7: [{ kind: "video", title: "Dziurka na guzik na maszynie", url: yt("FaX8MWwvlmc") }],
  12: [{ kind: "video", title: "Spódnica z gumą w pasie", url: yt("mRwWwff04Ps") }],
  13: [{ kind: "video", title: "Podwinięcie kryte (blind hem)", url: yt("2DXR7qiLVJI") }],
  14: [{ kind: "video", title: "Kołnierz koszuli krok po kroku", url: yt("x0T74oVRWNo") }],
  17: [{ kind: "video", title: "Wszywanie rękawa (set-in sleeve)", url: yt("W4x9uPfp53U") }],
  24: [{ kind: "video", title: "Zamek kryty (invisible zipper)", url: yt("cG8CSr11kjA") }],
};
