// Crochet ladder 1-99 — REALISTIC personal-progression scale (dedicated hobbyist;
// hours capped ~1200, project counts scaled; top tiers reframed as attainable
// mastery, real feats left to future certificates).
// Tracks: umiejetnosci, projekty (finished pieces), godziny.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const activity = {
  slug: "szydelkowanie",
  name: "Szydełkowanie",
  icon: "🪡",
  description:
    "Od łańcuszka po amigurumi, koronki i odzież. Poziomy 1–99 to realna droga amatora: fundamenty → dorobek i godziny → własne projekty → dojrzały, autorski warsztat.",
  sortOrder: 87,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Zrób łańcuszek (chain) równy i luźny", undefined, prog("umiejetnosci", 1)],
  ["Opanuj słupek niski (single crochet)", undefined, prog("umiejetnosci", 2)],
  ["Opanuj półsłupek i słupek (half double, double)", undefined, prog("umiejetnosci", 3)],
  ["Zrób prostokątny fragment o równych brzegach", undefined, prog("umiejetnosci", 4)],
  ["Zakończ pracę i schowaj nitki", undefined, prog("umiejetnosci", 5)],
  ["Utrzymaj równe napięcie nici", undefined, prog("umiejetnosci", 6)],
  ["Zrób prosty projekt (podkładka / szalik)", undefined, prog("projekty", 2)],
  ["Rozczytaj prosty wzór / schemat", undefined, prog("umiejetnosci", 7)],
  ["Ukończ 4 projekty", undefined, prog("projekty", 4)],
  ["Szydełkuj łącznie przez 10 godzin", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Szydełkuj kilka razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(2, 4)],
  ["Szydełkuj w okręgu (magic ring)", undefined, prog("umiejetnosci", 8)],
  ["Przybieraj i ubieraj oczka (kształtowanie)", undefined, prog("umiejetnosci", 9)],
  ["Zrób pierwsze amigurumi (prosta zabawka)", undefined, prog("umiejetnosci", 10)],
  ["Ukończ 8 projektów", undefined, prog("projekty", 8)],
  ["Szydełkuj łącznie przez 25 godzin", undefined, prog("godziny", 25)],
  ["Zrób kwadrat babci (granny square)", undefined, prog("umiejetnosci", 11)],
  ["Zrób czapkę lub torbę", undefined, prog("umiejetnosci", 12)],
  ["Ukończ 14 projektów", undefined, prog("projekty", 14)],
  ["Łącz motywy w większą całość (koc z kwadratów)", undefined, prog("umiejetnosci", 13)],
  ["Dobierz włóczkę i szydełko do próbki (gauge)", undefined, prog("umiejetnosci", 14)],
  ["Szydełkuj łącznie przez 45 godzin", undefined, prog("godziny", 45)],
  ["Zrób projekt z kilku części i połącz go", undefined, prog("projekty", 22)],
  ["Zrób prosty wzór kolorowy (zmiana kolorów)", undefined, prog("umiejetnosci", 15)],
  ["Ukończ 30 projektów", undefined, prog("projekty", 30)],
  // 26-45 · Średniozaawansowany
  ["Szydełkuj regularnie przez 8 kolejnych tygodni", undefined, freq(2, 8)],
  ["Zrób większe amigurumi z detalami", undefined, prog("umiejetnosci", 16)],
  ["Opanuj koronkę szydełkową (lace, przestrzenne wzory)", undefined, prog("umiejetnosci", 17)],
  ["Ukończ 40 projektów", undefined, prog("projekty", 40)],
  ["Opanuj tapestry crochet (obrazkowy żakard)", undefined, prog("umiejetnosci", 18)],
  ["Szydełkuj łącznie przez 70 godzin", undefined, prog("godziny", 70)],
  ["Zrób odzież (sweter / kardigan)", undefined, prog("umiejetnosci", 19)],
  ["Dopasuj rozmiar wzoru do własnych wymiarów", undefined, prog("umiejetnosci", 20)],
  ["Ukończ 55 projektów", undefined, prog("projekty", 55)],
  ["Wykończ pracę profesjonalnie (blokowanie, obszycie)", undefined, prog("umiejetnosci", 21)],
  ["Zrób dużą, złożoną pracę (narzuta / sukienka)", undefined, prog("umiejetnosci", 22)],
  ["Szydełkuj łącznie przez 100 godzin", undefined, prog("godziny", 100)],
  ["Zrób pracę łączącą kilka technik", undefined, prog("projekty", 70)],
  ["Opanuj filet crochet lub broomstick lace", undefined, prog("umiejetnosci", 23)],
  ["Zaprojektuj drobną modyfikację wzoru", undefined, prog("umiejetnosci", 24)],
  ["Ukończ 85 projektów", undefined, prog("projekty", 85)],
  ["Opanuj irlandzką koronkę lub inne wymagające techniki", undefined, prog("umiejetnosci", 25)],
  ["Szydełkuj łącznie przez 150 godzin", undefined, prog("godziny", 150)],
  ["Zrób pracę łączącą motywy, kolor i koronkę", undefined, prog("umiejetnosci", 26)],
  ["Prowadź projekty regularnie przez 3 miesiące", undefined, prog("projekty", 100)],
  // 46-65 · Zaawansowany (amator)
  ["Szydełkuj regularnie przez 12 kolejnych tygodni", undefined, freq(2, 12)],
  ["Zaprojektuj własny prosty wzór od zera", undefined, prog("umiejetnosci", 27)],
  ["Zrób spójny zestaw (np. sweter + akcesoria)", undefined, prog("umiejetnosci", 28)],
  ["Ukończ 120 projektów", undefined, prog("projekty", 120)],
  ["Szydełkuj łącznie przez 220 godzin", undefined, prog("godziny", 220)],
  ["Pokaż prace publicznie i zbierz opinie odbiorców"],
  ["Zaprojektuj odzież z rozpisaniem rozmiarów", undefined, prog("umiejetnosci", 29)],
  ["Ukończ 150 projektów", undefined, prog("projekty", 150)],
  ["Opanuj wybraną specjalizację (amigurumi / koronka / odzież)", undefined, prog("umiejetnosci", 30)],
  ["Szydełkuj łącznie przez 300 godzin", undefined, prog("godziny", 300)],
  ["Zbuduj portfolio najlepszych prac"],
  ["Weź udział w wystawie / konkursie rękodzieła lub sprzedaj pracę"],
  ["Zaprojektuj skomplikowany wzór koronkowy", undefined, prog("umiejetnosci", 31)],
  ["Ukończ 180 projektów", undefined, prog("projekty", 180)],
  ["Sprzedaj pracę / zrealizuj zamówienie", undefined, prog("umiejetnosci", 32)],
  ["Szydełkuj łącznie przez 420 godzin", undefined, prog("godziny", 420)],
  ["Poprowadź kogoś przez podstawy szydełkowania", undefined, prog("umiejetnosci", 33)],
  ["Zrealizuj spójny cykl prac wokół jednego pomysłu"],
  ["Zrób wymagający projekt na najwyższym własnym poziomie", undefined, prog("umiejetnosci", 34)],
  ["Ukończ 220 projektów", undefined, prog("projekty", 220)],
  // 66-85 · Ekspert (poziom amatorski wysoki)
  ["Szydełkuj regularnie przez pełny sezon (6 miesięcy)"],
  ["Projektuj swobodnie własne wzory", undefined, prog("umiejetnosci", 35)],
  ["Ukończ 270 projektów", undefined, prog("projekty", 270)],
  ["Szydełkuj łącznie przez 580 godzin", undefined, prog("godziny", 580)],
  ["Opublikuj własny wzór (za darmo lub na sprzedaż)"],
  ["Rozwiń warsztat na tyle, by uczyć szydełkowania", undefined, prog("umiejetnosci", 36)],
  ["Zbuduj rozpoznawalne portfolio o spójnym stylu"],
  ["Regularnie sprzedajesz prace lub wzory"],
  ["Opanuj każdą technikę szydełkową na wysokim poziomie", undefined, prog("umiejetnosci", 37)],
  ["Ukończ 330 projektów", undefined, prog("projekty", 330)],
  ["Zdobądź wyróżnienie lub uznanie w społeczności rękodzieła"],
  ["Szydełkuj łącznie przez 800 godzin", undefined, prog("godziny", 800)],
  ["Zrealizuj ambitny, wieloczęściowy projekt autorski", undefined, prog("umiejetnosci", 38)],
  ["Twoje prace są dojrzałe i dopracowane w każdym detalu", undefined, prog("umiejetnosci", 39)],
  ["Ukończ 400 projektów", undefined, prog("projekty", 400)],
  ["Zbuduj grono odbiorców swoich prac / wzorów"],
  ["Poprowadź warsztaty lub mentoring dla szydełkujących"],
  ["Zaprojektuj kolekcję spójnych wzorów"],
  ["Zrealizuj wystawę lub publikację prezentującą dorobek"],
  ["Ukończ 480 projektów", undefined, prog("projekty", 480)],
  // 86-99 · Mistrzostwo osobiste (realny szczyt zaangażowanego amatora)
  ["Szydełkuj łącznie przez 1000 godzin", undefined, prog("godziny", 1000)],
  ["Utrzymuj wysoki, powtarzalny poziom w każdej pracy"],
  ["Ukończ 560 projektów", undefined, prog("projekty", 560)],
  ["Zbuduj bogate, spójne portfolio o autorskim charakterze"],
  ["Twój styl inspiruje innych szydełkujących w Twoim otoczeniu"],
  ["Zrealizuj osobisty „opus” — dużą, dopracowaną pracę lub kolekcję", undefined, prog("umiejetnosci", 40)],
  ["Regularnie publikujesz wzory lub wystawiasz prace"],
  ["Szydełkuj łącznie przez 1200 godzin", undefined, prog("godziny", 1200)],
  ["Twoje prace zdobywają uznanie poza lokalną społecznością"],
  ["Ukończ 650 projektów", undefined, prog("projekty", 650)],
  ["Uczysz i kształtujesz kolejnych szydełkujących"],
  ["Masz dorobek, z którego można ułożyć wystawę retrospektywną"],
  ["Wyszydełkujesz niemal wszystko, co sobie zaplanujesz"],
  ["Poziom mistrzowski (amatorski szczyt): dojrzały, autorski warsztat", "Dalsze, „zawodowe” osiągnięcia potwierdzają osobne certyfikaty."],
]);

// Curated, link-verified learning resources for the concrete technique
// milestones (szydełkowanie: Bella Coco, The Woobles, TL Yarn Crafts i in.).
export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Łańcuszek (foundation chain)", url: yt("O8ZQNvY-9FY") }],
  2: [{ kind: "video", title: "Słupek niski (single crochet)", url: yt("-03Z0i4Hjek") }],
  3: [
    { kind: "video", title: "Półsłupek (hdc)", url: yt("f9C1C21MNiM") },
    { kind: "video", title: "Słupek (double crochet)", url: yt("a1whu6Gub1M") },
  ],
  12: [{ kind: "video", title: "Szydełkowanie w okręgu (magic ring)", url: yt("z_CS3TUADYg") }],
  13: [{ kind: "video", title: "Przybieranie i ubieranie oczek", url: yt("tJGkVz8ceIo") }],
  14: [{ kind: "video", title: "Pierwsze amigurumi (podstawy)", url: yt("p581TBewfU0") }],
  17: [{ kind: "video", title: "Kwadrat babci (granny square)", url: yt("GALGQdP_POw") }],
  20: [{ kind: "video", title: "Łączenie motywów (join squares)", url: yt("NUGb9pIcsXE") }],
  24: [{ kind: "video", title: "Zmiana kolorów w szydełkowaniu", url: yt("3wxMQ-_Cz3s") }],
  28: [{ kind: "video", title: "Koronka szydełkowa (lace, muszelki)", url: yt("PVmC7XDgVIo") }],
  30: [{ kind: "video", title: "Tapestry crochet (obrazkowy żakard)", url: yt("GJ31p1WBLvc") }],
  32: [{ kind: "video", title: "Sweter / kardigan dla początkujących", url: yt("nyYmk_CJo_Q") }],
};
