// Table tennis ladder 1-99. Tracks: rally length, serve accuracy, matches.
// Skill milestones (spins, footwork) manual.
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "tenis-stolowy",
  name: "Tenis stołowy",
  icon: "🏓",
  description:
    "Od pierwszej wymiany po turnieje — rotacje, serwisy i refleks przy stole.",
  sortOrder: 11,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Odbij piłeczkę rakietką 20 razy w górę"],
  ["Wymień z partnerem 5 uderzeń bez błędu"],
  ["Wprowadź prawidłowy serwis (podrzut + odbicie od własnej połowy)"],
  ["Wymień 10 uderzeń forhendem"],
  ["Wymień 10 uderzeń bekhendem"],
  ["Traf serwisem w wybraną połowę stołu 5/10"],
  ["Wymień 20 uderzeń bez błędu"],
  ["Rozegraj pierwszego seta do 11"],
  ["Wymień naprzemiennie forhend-bekhend 10 razy"],
  ["Rozegraj pierwszy mecz (najlepszy z 5 setów)"],
  // 11-25 · Regularny
  ["Graj raz w tygodniu przez 4 kolejne tygodnie"],
  ["Wymień 30 uderzeń bez błędu"],
  ["Zagraj półwolej (blok) po ataku przeciwnika"],
  ["Traf serwisem 7/10 w wybraną połowę"],
  ["Rozegraj 5 meczów"],
  ["Zagraj pierwszy topspin forhendowy", "Rotacja górna — fundament ofensywy."],
  ["Wymień 50 uderzeń bez błędu"],
  ["Wygraj pierwszego seta"],
  ["Zagraj serwis z rotacją boczną"],
  ["Rozegraj 10 meczów"],
  ["Odbierz serwis z rotacją bez wyrzucenia piłki 5 razy z rzędu"],
  ["Wygraj pierwszy mecz"],
  ["Graj 2 razy w tygodniu przez 8 kolejnych tygodni"],
  ["Zagraj topspin bekhendowy"],
  ["Wymień 100 uderzeń bez błędu", "Setka — kontrola jest już odruchem."],
  // 26-45 · Średniozaawansowany
  ["Traf serwisem 9/10 w wybraną połowę"],
  ["Rozegraj 20 meczów"],
  ["Zagraj skuteczny smecz po wysokiej piłce"],
  ["Wygraj 5 meczów"],
  ["Zagraj serwis z rotacją dolną, po którym rywal wyrzuca piłkę w siatkę"],
  ["Wymień topspin-blok 10 razy z rzędu w parze"],
  ["Rozegraj 35 meczów"],
  ["Zagraj kontratak topspinem na topspin"],
  ["Wygraj 10 meczów"],
  ["Zagraj flip (bananę) po krótkim serwisie", "Atak nad stołem — technika nowoczesnej gry."],
  ["Wygraj seta do 3 lub niżej"],
  ["Rozegraj 50 meczów"],
  ["Wygraj 20 meczów"],
  ["Zagraj mecz taktyczny na słabszą stronę rywala (świadomie)"],
  ["Weź udział w turnieju amatorskim"],
  ["Zagraj skuteczny lob obronny 3 razy w jednej wymianie"],
  ["Wygraj mecz w turnieju amatorskim"],
  ["Rozegraj 75 meczów"],
  ["Wygraj 30 meczów"],
  ["Wymień 200 uderzeń bez błędu"],
  // 46-65 · Zaawansowany
  ["Zagraj serwis, po którym otrzymujesz łatwą piłkę 5 razy z rzędu (serw + atak)"],
  ["Rozegraj 100 meczów", "Setka przy stole."],
  ["Wygraj 50 meczów"],
  ["Osiągnij ćwierćfinał turnieju amatorskiego"],
  ["Zagraj pełny mecz w obronie ciętej (chop) lub przeciwko niej z wygraną"],
  ["Wygraj 3 mecze w jednym turnieju"],
  ["Rozegraj 150 meczów"],
  ["Wygraj 75 meczów"],
  ["Osiągnij półfinał turnieju amatorskiego"],
  ["Zagraj mecz z zawodnikiem ligowym i urwij mu seta"],
  ["Wygraj 100 meczów"],
  ["Wygraj turniej amatorski", "Pierwsze trofeum."],
  ["Rozegraj 200 meczów"],
  ["Dołącz do klubu z sekcją tenisa stołowego"],
  ["Wygraj 150 meczów"],
  ["Zagraj sezon w lidze amatorskiej lub klubowej"],
  ["Rozegraj 300 meczów"],
  ["Pokonaj zawodnika z licencją PZTS"],
  ["Wygraj drugi turniej amatorski"],
  ["Wygraj 200 meczów"],
  // 66-85 · Wyczynowy
  ["Rozegraj 400 meczów"],
  ["Zdobądź licencję zawodniczą PZTS"],
  ["Zagraj mecz ligowy (najniższa klasa rozgrywkowa)"],
  ["Wygraj 250 meczów"],
  ["Wygraj mecz ligowy"],
  ["Rozegraj 500 meczów"],
  ["Wygraj 5 turniejów amatorskich łącznie"],
  ["Rozegraj pełny sezon ligowy jako podstawowy zawodnik"],
  ["Wygraj 300 meczów"],
  ["Osiągnij bilans dodatni sezonu ligowego (więcej wygranych niż porażek)"],
  ["Awansuj z drużyną do wyższej klasy rozgrywkowej"],
  ["Rozegraj 600 meczów"],
  ["Wygraj 400 meczów"],
  ["Zostań najlepszym zawodnikiem swojej drużyny w sezonie"],
  ["Zagraj na poziomie ligi okręgowej"],
  ["Wygraj turniej rangi wojewódzkiej"],
  ["Rozegraj 750 meczów"],
  ["Wygraj 500 meczów"],
  ["Zagraj 50 meczów ligowych"],
  ["Zagraj na poziomie III ligi"],
  // 86-99 · Elita
  ["Rozegraj 900 meczów"],
  ["Zdobądź medal mistrzostw województwa"],
  ["Wygraj 600 meczów"],
  ["Rozegraj pełny sezon III ligi z bilansem dodatnim"],
  ["Zagraj na poziomie II ligi"],
  ["Rozegraj 1000 meczów", "Tysiąc pojedynków przy stole."],
  ["Zagraj 100 meczów ligowych"],
  ["Wygraj mistrzostwa województwa"],
  ["Wygraj 750 meczów"],
  ["Zagraj na poziomie I ligi"],
  ["Zagraj w turnieju z cyklu Grand Prix Polski"],
  ["Zdobądź punkty w rankingu ogólnopolskim PZTS"],
  ["Zagraj na wysokim poziomie ligowym lub zdobądź podium mistrzostw regionu", "Bardzo mocny poziom amatorski."],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, czołowy zawodnik regionu", "Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  2: prog("wymiana", 5), 4: prog("wymiana", 10), 7: prog("wymiana", 20), 12: prog("wymiana", 30),
  17: prog("wymiana", 50), 25: prog("wymiana", 100), 45: prog("wymiana", 200),
  6: prog("serwis", 5), 14: prog("serwis", 7), 26: prog("serwis", 9),
  10: prog("mecze", 1), 15: prog("mecze", 5), 20: prog("mecze", 10), 27: prog("mecze", 20),
  32: prog("mecze", 35), 37: prog("mecze", 50), 43: prog("mecze", 75), 47: prog("mecze", 100),
  52: prog("mecze", 150), 58: prog("mecze", 200), 62: prog("mecze", 300), 66: prog("mecze", 400),
  71: prog("mecze", 500), 77: prog("mecze", 600), 82: prog("mecze", 750), 86: prog("mecze", 900),
  91: prog("mecze", 1000),
  22: prog("wygrane", 1), 29: prog("wygrane", 5), 34: prog("wygrane", 10), 38: prog("wygrane", 20),
  44: prog("wygrane", 30), 48: prog("wygrane", 50), 53: prog("wygrane", 75), 56: prog("wygrane", 100),
  60: prog("wygrane", 150), 65: prog("wygrane", 200), 69: prog("wygrane", 250), 74: prog("wygrane", 300),
  78: prog("wygrane", 400), 83: prog("wygrane", 500), 88: prog("wygrane", 600), 94: prog("wygrane", 750),
  11: freq(1, 4), 23: freq(2, 8),
  // pozostałe: technika, liga, osiągnięcia — manualne.
};
