// Tennis ladder 1-99. Tracks: rally length, first-serve accuracy (out of 10),
// match experience; skill and competition milestones manual. Anchored loosely
// to the NTRP self-rating scale (1.5 beginner → 5.0+ tournament player).
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "tenis",
  name: "Tenis",
  icon: "🎾",
  description:
    "Od pierwszego odbicia o ścianę po turnieje. Drabinka zgodna z duchem skali NTRP (1.5 → 5.0+).",
  sortOrder: 10,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Odbij piłkę rakietą 10 razy w górę", "Czucie naciągu — start absolutny."],
  ["Odbij piłkę o ścianę 5 razy z rzędu"],
  ["Przebij piłkę forhendem przez siatkę"],
  ["Odbij o ścianę 10 razy z rzędu"],
  ["Przebij piłkę bekhendem przez siatkę"],
  ["Wymień z partnerem 5 uderzeń bez błędu (mini-tenis)"],
  ["Wprowadź serwis od dołu w pole serwisowe"],
  ["Odbij o ścianę 25 razy z rzędu"],
  ["Wymień z partnerem 10 uderzeń z linii serwisowej"],
  ["Rozegraj pierwszego gema na punkty", "NTRP ~1.5."],
  // 11-25 · Regularny
  ["Graj lub trenuj raz w tygodniu przez 4 kolejne tygodnie"],
  ["Wprowadź serwis od góry w pole serwisowe"],
  ["Wymień 10 uderzeń z linii końcowej"],
  ["Traf serwisem od góry 3/10 pierwszych podań"],
  ["Rozegraj pierwszego pełnego seta"],
  ["Rozegraj wymianę 20 uderzeń z linii końcowej"],
  ["Zagraj wolej forhendowy i bekhendowy przy siatce"],
  ["Traf serwisem 5/10 pierwszych podań", "Połowa pierwszych podań w korcie — NTRP ~2.5."],
  ["Rozegraj 5 meczów"],
  ["Zagraj skuteczny lob obronny w wymianie"],
  ["Wymień 30 uderzeń z linii końcowej"],
  ["Graj 2 razy w tygodniu przez 8 kolejnych tygodni"],
  ["Wygraj pierwszego seta w meczu"],
  ["Zagraj smecz po odbiciu piłki od kortu"],
  ["Rozegraj 10 meczów"],
  // 26-45 · Średniozaawansowany
  ["Traf serwisem 6/10 pierwszych podań"],
  ["Zagraj slajs bekhendowy utrzymujący piłkę nisko"],
  ["Wymień 50 uderzeń z linii końcowej", "Regularność — fundament NTRP 3.0."],
  ["Wygraj pierwszego mecza"],
  ["Zagraj kick lub slice serwis (rotacyjny)"],
  ["Rozegraj 20 meczów"],
  ["Zagraj drop shot wygrywający punkt"],
  ["Traf 5/10 returnów w kort po mocnym serwisie"],
  ["Wygraj 5 meczów"],
  ["Traf serwisem 7/10 pierwszych podań"],
  ["Zagraj pełny mecz deblowy z taktyką (kto przy siatce, kto z tyłu)"],
  ["Rozegraj 35 meczów"],
  ["Zagraj as serwisowy"],
  ["Wygraj gema do zera przy własnym podaniu"],
  ["Wymień 75 uderzeń bez błędu"],
  ["Wygraj 10 meczów", "Poziom NTRP ~3.5 — regularna gra z kontrolą kierunku."],
  ["Zagraj passing shot mijający wolejującego"],
  ["Rozegraj 50 meczów"],
  ["Weź udział w turnieju amatorskim", "Liga miejska, challenger klubowy."],
  ["Wygraj mecz w turnieju amatorskim"],
  // 46-65 · Zaawansowany
  ["Traf serwisem 8/10 pierwszych podań"],
  ["Wygraj 20 meczów"],
  ["Zagraj cały mecz z konsekwentną taktyką na słabszą stronę rywala"],
  ["Rozegraj 75 meczów"],
  ["Zagraj winnera z bekhendu po linii", "Uderzenie wysokiego ryzyka."],
  ["Wygraj 2 mecze w jednym turnieju"],
  ["Wygraj 30 meczów"],
  ["Rozegraj 100 meczów", "Setka spotkań na korcie."],
  ["Zagraj tie-breaka wygranego pod presją (od stanu 4:6)"],
  ["Osiągnij półfinał turnieju amatorskiego"],
  ["Wygraj 3 asy w jednym meczu"],
  ["Wygraj 50 meczów"],
  ["Zagraj serwis z prędkością 150+ km/h lub odpowiednik (mierzony)", "Radar lub aplikacja."],
  ["Wygraj turniej amatorski", "Pierwsze trofeum."],
  ["Rozegraj 150 meczów"],
  ["Wygraj mecz z zawodnikiem z rankingu klubowego wyżej o 2 miejsca"],
  ["Rozegraj 5 pełnych sezonów gry"],
  ["Wygraj 75 meczów"],
  ["Zdobądź punkty w lidze regionalnej amatorów"],
  ["Wygraj drugi turniej amatorski", "Potwierdzenie — NTRP ~4.0."],
  // 66-85 · Wyczynowy
  ["Rozegraj 200 meczów"],
  ["Wygraj 100 meczów"],
  ["Traf serwisem 9/10 pierwszych podań w serii treningowej"],
  ["Osiągnij finał turnieju rangi wojewódzkiej"],
  ["Wygraj mecz 6:0, 6:0"],
  ["Rozegraj 250 meczów"],
  ["Zostań mistrzem klubu"],
  ["Wygraj 3 turnieje amatorskie łącznie"],
  ["Wygraj 150 meczów"],
  ["Zagraj sezon w drużynowej lidze klubowej"],
  ["Rozegraj 300 meczów"],
  ["Wygraj turniej rangi wojewódzkiej"],
  ["Pokonaj zawodnika z licencją związkową (PZT)"],
  ["Wygraj 200 meczów"],
  ["Zdobądź licencję zawodniczą i punkt w rankingu PZT/ITF amatorów"],
  ["Rozegraj 400 meczów"],
  ["Osiągnij poziom NTRP 4.5 potwierdzony wynikami", "Silne, planowane uderzenia i taktyka."],
  ["Wygraj 5 turniejów łącznie"],
  ["Wygraj 250 meczów"],
  ["Wygraj turniej ogólnopolski amatorów (np. cykl Tenis Pro-Am)"],
  // 86-99 · Elita
  ["Rozegraj 500 meczów"],
  ["Osiągnij czołową dziesiątkę rankingu regionalnego"],
  ["Wygraj 300 meczów"],
  ["Wygraj 10 turniejów łącznie"],
  ["Zagraj w mistrzostwach Polski amatorów"],
  ["Rozegraj 600 meczów"],
  ["Zdobądź medal mistrzostw Polski amatorów lub kategorii wiekowej"],
  ["Osiągnij poziom NTRP 5.0", "Broń słabości, buduje punkty od serwisu — poziom turniejowy."],
  ["Wygraj 400 meczów"],
  ["Wygraj mistrzostwa regionu"],
  ["Zagraj turniej z pulą rankingową ITF/UTR 10+"],
  ["Wygraj 15 turniejów łącznie"],
  ["Wygraj mistrzostwa regionalne amatorów lub masters kategorii wiekowej"],
  ["Poziom mistrzowski (amatorski szczyt): NTRP 5.5 lub UTR 9+", "Dojrzały, wieloletni warsztat tenisowy zaangażowanego amatora. Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  1: prog("scianka", 5), 2: prog("scianka", 5), 4: prog("scianka", 10), 8: prog("scianka", 25),
  6: prog("wymiana", 5), 9: prog("wymiana", 10), 13: prog("wymiana", 10), 16: prog("wymiana", 20),
  21: prog("wymiana", 30), 28: prog("wymiana", 50), 40: prog("wymiana", 75),
  14: prog("serwis", 3), 18: prog("serwis", 5), 26: prog("serwis", 6), 35: prog("serwis", 7),
  46: prog("serwis", 8), 68: prog("serwis", 9),
  19: prog("mecze", 5), 25: prog("mecze", 10), 31: prog("mecze", 20), 37: prog("mecze", 35),
  43: prog("mecze", 50), 49: prog("mecze", 75), 53: prog("mecze", 100), 60: prog("mecze", 150),
  66: prog("mecze", 200), 71: prog("mecze", 250), 76: prog("mecze", 300), 81: prog("mecze", 400),
  86: prog("mecze", 500), 91: prog("mecze", 600),
  29: prog("wygrane", 1), 34: prog("wygrane", 5), 41: prog("wygrane", 10), 47: prog("wygrane", 20),
  52: prog("wygrane", 30), 57: prog("wygrane", 50), 63: prog("wygrane", 75), 67: prog("wygrane", 100),
  74: prog("wygrane", 150), 79: prog("wygrane", 200), 84: prog("wygrane", 250), 88: prog("wygrane", 300),
  94: prog("wygrane", 400),
  59: prog("turnieje", 1), 65: prog("turnieje", 2), 73: prog("turnieje", 3), 83: prog("turnieje", 5),
  89: prog("turnieje", 10), 97: prog("turnieje", 15),
  11: freq(1, 4), 22: freq(2, 8),
  // pozostałe: technika i osiągnięcia turniejowe — manualne.
};
