// Triathlon ladder 1-99. Manual — progression tracks: race distance completed
// (super-sprint → sprint → olympic → 70.3 → Ironman → ultra) and finish level.
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "triathlon",
  name: "Triathlon",
  icon: "🏊",
  description:
    "Pływanie, rower i bieg w jednym. Od super-sprintu po Ironmana i ultra. Progresja: ukończony dystans, czasy i poziom zawodów.",
  sortOrder: 41,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Przepłyń 200 m, przejedź 5 km i przebiegnij 1 km (osobno)", undefined, prog("dystans", 1)],
  ["Opanuj pływanie w otwartej wodzie (bez ścian) na 200 m", undefined, prog("technika", 1)],
  ["Wykonaj płynną zmianę rower→bieg (trening brick)", undefined, prog("technika", 2)],
  ["Przepłyń 400 m bez zatrzymania", undefined, prog("plywanie", 400)],
  ["Przejedź 20 km rowerem bez przerwy", undefined, prog("rower", 20)],
  ["Przebiegnij 5 km bez zatrzymania", undefined, prog("bieg", 5)],
  ["Opanuj zmianę pływanie→rower (T1) sprawnie", undefined, prog("technika", 3)],
  ["Ukończ super-sprint (0,4 km / 10 km / 2,5 km)", "Pierwszy triathlon!", prog("dystans", 2)],
  ["Przepłyń 750 m w otwartej wodzie", undefined, prog("plywanie", 750)],
  ["Przebiegnij 5 km po jeździe rowerem (brick) bez marszu", undefined, prog("technika", 4)],
  // 11-25 · Regularny
  ["Trenuj wszystkie trzy dyscypliny w jednym tygodniu przez 4 tygodnie", undefined, freq(3, 4)],
  ["Przejedź 40 km rowerem bez przerwy", undefined, prog("rower", 40)],
  ["Przebiegnij 8 km bez zatrzymania", undefined, prog("bieg", 8)],
  ["Ukończ dystans sprint (0,75 km / 20 km / 5 km)", undefined, prog("dystans", 3)],
  ["Przepłyń 1000 m bez zatrzymania", undefined, prog("plywanie", 1000)],
  ["Opanuj draft-legal lub jazdę w grupie", undefined, prog("technika", 5)],
  ["Przebiegnij 10 km bez zatrzymania", undefined, prog("bieg", 10)],
  ["Przejedź 50 km rowerem bez przerwy", undefined, prog("rower", 50)],
  ["Ukończ sprint poniżej 1:30", undefined, prog("czas-sprint", 90)],
  ["Przepłyń 1500 m w otwartej wodzie", undefined, prog("plywanie", 1500)],
  ["Przejedź 60 km rowerem", undefined, prog("rower", 60)],
  ["Ukończ dystans olimpijski (1,5 km / 40 km / 10 km)", "Klasyczny dystans triathlonu.", prog("dystans", 4)],
  ["Ukończ sprint poniżej 1:20", undefined, prog("czas-sprint", 80)],
  ["Przebiegnij 12 km po jeździe (brick)", undefined, prog("bieg", 12)],
  ["Ukończ olimpijski poniżej 3:00", undefined, prog("czas-olimp", 180)],
  // 26-45 · Średniozaawansowany
  ["Trenuj konsekwentnie 6-8 h tygodniowo przez 12 tygodni", undefined, freq(4, 12)],
  ["Przejedź 80 km rowerem bez przerwy", undefined, prog("rower", 80)],
  ["Przebiegnij 15 km bez zatrzymania", undefined, prog("bieg", 15)],
  ["Ukończ olimpijski poniżej 2:45", undefined, prog("czas-olimp", 165)],
  ["Przepłyń 1900 m w otwartej wodzie", undefined, prog("plywanie", 1900)],
  ["Przejedź 90 km rowerem", undefined, prog("rower", 90)],
  ["Przebiegnij półmaraton (21 km)", undefined, prog("bieg", 21)],
  ["Ukończ dystans połówka Ironman / 70.3 (1,9 / 90 / 21,1)", "Middle distance — poważny próg.", prog("dystans", 5)],
  ["Ukończ olimpijski poniżej 2:30", undefined, prog("czas-olimp", 150)],
  ["Przejedź 120 km rowerem bez przerwy", undefined, prog("rower", 120)],
  ["Ukończ 70.3 poniżej 6:00", undefined, prog("czas-703", 360)],
  ["Przepłyń 2500 m bez zatrzymania", undefined, prog("plywanie", 2500)],
  ["Przebiegnij 25 km po długiej jeździe", undefined, prog("bieg", 25)],
  ["Ukończ 70.3 poniżej 5:30", undefined, prog("czas-703", 330)],
  ["Przejedź 150 km rowerem", undefined, prog("rower", 150)],
  ["Ukończ olimpijski poniżej 2:20", undefined, prog("czas-olimp", 140)],
  ["Przepłyń 3000 m w otwartej wodzie", undefined, prog("plywanie", 3000)],
  ["Ukończ 70.3 poniżej 5:00", "Sub-5 na połówce.", prog("czas-703", 300)],
  ["Przejedź 160 km rowerem bez przerwy", undefined, prog("rower", 160)],
  // 46-65 · Zaawansowany
  ["Trenuj 10-12 h tygodniowo przez cały sezon"],
  ["Przebiegnij maraton (42 km)", undefined, prog("bieg", 42)],
  ["Przepłyń 3800 m bez zatrzymania", undefined, prog("plywanie", 3800)],
  ["Przejedź 180 km rowerem bez przerwy", undefined, prog("rower", 180)],
  ["Ukończ pełny dystans Ironman (3,8 / 180 / 42,2)", "Królewski dystans — mniej niż ułamek procenta ludzi go kończy.", prog("dystans", 6)],
  ["Ukończ 70.3 poniżej 4:40", undefined, prog("czas-703", 280)],
  ["Ukończ Ironmana poniżej 13:00", undefined, prog("czas-im", 780)],
  ["Przejedź 200 km rowerem", undefined, prog("rower", 200)],
  ["Ukończ olimpijski poniżej 2:10", undefined, prog("czas-olimp", 130)],
  ["Ukończ Ironmana poniżej 12:00", undefined, prog("czas-im", 720)],
  ["Ukończ 70.3 poniżej 4:30", undefined, prog("czas-703", 270)],
  ["Zajmij miejsce w pierwszej połowie kategorii wiekowej na zawodach"],
  ["Ukończ Ironmana poniżej 11:00", undefined, prog("czas-im", 660)],
  ["Ukończ olimpijski poniżej 2:05", undefined, prog("czas-olimp", 125)],
  ["Ukończ 70.3 poniżej 4:20", undefined, prog("czas-703", 260)],
  ["Ukończ Ironmana poniżej 10:30", undefined, prog("czas-im", 630)],
  ["Zajmij miejsce na podium kategorii wiekowej"],
  ["Ukończ 70.3 poniżej 4:10", undefined, prog("czas-703", 250)],
  ["Ukończ Ironmana poniżej 10:00", "Sub-10 na Ironmanie — poziom elity amatorów.", prog("czas-im", 600)],
  ["Uzyskaj wynik kwalifikujący do mistrzostw (slot 70.3 lub IM Worlds)"],
  ["Opanuj strefy zmian (T1/T2) tak, by nie tracić na nich czasu"],
  // 66-85 · Wyczynowy
  ["Trenuj 15+ h tygodniowo przez sezon"],
  ["Ukończ olimpijski poniżej 2:00", undefined, prog("czas-olimp", 120)],
  ["Ukończ 70.3 poniżej 4:00", "Sub-4 na połówce.", prog("czas-703", 240)],
  ["Ukończ Ironmana poniżej 9:40", undefined, prog("czas-im", 580)],
  ["Wystartuj w mistrzostwach świata 70.3 lub Ironman"],
  ["Ukończ olimpijski poniżej 1:55", undefined, prog("czas-olimp", 115)],
  ["Ukończ 70.3 poniżej 3:50", undefined, prog("czas-703", 230)],
  ["Ukończ Ironmana poniżej 9:20", undefined, prog("czas-im", 560)],
  ["Ukończ podwójny Ironman lub dystans ultra (np. 226 km × 2)", undefined, prog("dystans", 7)],
  ["Ukończ 70.3 poniżej 3:45", undefined, prog("czas-703", 225)],
  ["Ukończ Ironmana poniżej 9:00", "Sub-9 — bardzo blisko poziomu zawodowego.", prog("czas-im", 540)],
  ["Zajmij miejsce w pierwszej dziesiątce kategorii na mistrzostwach"],
  ["Ukończ olimpijski poniżej 1:52", undefined, prog("czas-olimp", 112)],
  ["Ukończ 70.3 poniżej 3:40", undefined, prog("czas-703", 220)],
  ["Ukończ Ironmana poniżej 8:45", undefined, prog("czas-im", 525)],
  ["Zostań uznanym zawodnikiem w swojej kategorii wiekowej"],
  ["Ukończ 70.3 poniżej 3:35", undefined, prog("czas-703", 215)],
  ["Ukończ Ironmana poniżej 8:30", undefined, prog("czas-im", 510)],
  ["Ukończ ultra-triathlon (np. Deca lub Ultraman)", undefined, prog("dystans", 8)],
  ["Zajmij miejsce na podium kategorii na mistrzostwach świata amatorów"],
  // 86-99 · Elita
  ["Weź udział w zawodach o zasięgu ogólnokrajowym"],
  ["Ukończ 70.3 poniżej 3:30", undefined, prog("czas-703", 210)],
  ["Ukończ Ironmana poniżej 8:15", undefined, prog("czas-im", 495)],
  ["Ukończ olimpijski poniżej 1:50", "Bardzo wysoki, wieloletnio wypracowany poziom.", prog("czas-olimp", 110)],
  ["Zdobądź punkty w rankingu krajowym amatorów"],
  ["Ukończ 70.3 poniżej 3:25", undefined, prog("czas-703", 205)],
  ["Ukończ Ironmana poniżej 8:05", undefined, prog("czas-im", 485)],
  ["Zajmij miejsce w pierwszej dziesiątce zawodów o zasięgu ogólnokrajowym"],
  ["Ukończ Ironmana poniżej 8:00", "Sub-8 — bardzo rzadki wynik amatorski.", prog("czas-im", 480)],
  ["Weź udział w finale mistrzostw świata amatorów (age-group)"],
  ["Stań na podium zawodów rangi mistrzowskiej amatorów"],
  ["Ukończ Ironmana poniżej 7:50", undefined, prog("czas-im", 470)],
  ["Zdobądź medal mistrzostw świata amatorów w swojej kategorii wiekowej"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat triatlonowy", "Dalsze, zawodowe osiągnięcia (elita PTO/World Triathlon, igrzyska) potwierdzają osobne certyfikaty."],
]);
