// Powerlifting ladder 1-99. Manual — progression tracks: squat, bench, deadlift
// (kg), total (kg), and competition level. Values = kg (male open reference).
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "trojboj-silowy",
  name: "Trójbój siłowy",
  icon: "🏋️‍♂️",
  description:
    "Powerlifting — przysiad, wyciskanie leżąc i martwy ciąg. Progresja: ciężary w trzech bojach, total i poziom zawodów (odniesienie open).",
  sortOrder: 61,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj technikę przysiadu z gryfem olimpijskim", undefined, prog("technika", 1)],
  ["Opanuj technikę wyciskania leżąc z klatką i łopatkami", undefined, prog("technika", 2)],
  ["Opanuj technikę martwego ciągu z neutralnym kręgosłupem", undefined, prog("technika", 3)],
  ["Przysiad 40 kg", undefined, prog("przysiad", 40)],
  ["Wyciśnij 30 kg", undefined, prog("wyciskanie", 30)],
  ["Martwy ciąg 60 kg", undefined, prog("martwy", 60)],
  ["Przysiad 60 kg", undefined, prog("przysiad", 60)],
  ["Wyciśnij 40 kg", undefined, prog("wyciskanie", 40)],
  ["Martwy ciąg 80 kg", undefined, prog("martwy", 80)],
  ["Zaliczy total 150 kg (suma trzech bojów)", undefined, prog("total", 150)],
  // 11-25 · Regularny
  ["Trenuj 3 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Przysiad 80 kg", undefined, prog("przysiad", 80)],
  ["Wyciśnij 50 kg", undefined, prog("wyciskanie", 50)],
  ["Martwy ciąg 100 kg", "Setka w martwym.", prog("martwy", 100)],
  ["Zaliczy total 220 kg", undefined, prog("total", 220)],
  ["Przysiad 100 kg", "Setka w przysiadzie.", prog("przysiad", 100)],
  ["Wyciśnij 60 kg", undefined, prog("wyciskanie", 60)],
  ["Martwy ciąg 120 kg", undefined, prog("martwy", 120)],
  ["Wystartuj w pierwszych zawodach", undefined, prog("liga", 1)],
  ["Zaliczy total 280 kg", undefined, prog("total", 280)],
  ["Przysiad 120 kg", undefined, prog("przysiad", 120)],
  ["Wyciśnij 70 kg", undefined, prog("wyciskanie", 70)],
  ["Martwy ciąg 140 kg", undefined, prog("martwy", 140)],
  ["Zaliczy total 320 kg", undefined, prog("total", 320)],
  ["Opanuj wzorce ruchowe pod submaksymalnym ciężarem", undefined, prog("technika", 4)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 4 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(4, 12)],
  ["Przysiad 140 kg", undefined, prog("przysiad", 140)],
  ["Wyciśnij 80 kg", undefined, prog("wyciskanie", 80)],
  ["Martwy ciąg 160 kg", undefined, prog("martwy", 160)],
  ["Zaliczy total 380 kg", undefined, prog("total", 380)],
  ["Przysiad 150 kg", undefined, prog("przysiad", 150)],
  ["Wyciśnij 90 kg", undefined, prog("wyciskanie", 90)],
  ["Martwy ciąg 180 kg", undefined, prog("martwy", 180)],
  ["Zaliczy total 420 kg", undefined, prog("total", 420)],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  ["Przysiad 160 kg", undefined, prog("przysiad", 160)],
  ["Wyciśnij 100 kg", "Setka w wyciskaniu.", prog("wyciskanie", 100)],
  ["Martwy ciąg 200 kg", "Dwieście w martwym.", prog("martwy", 200)],
  ["Zaliczy total 460 kg", undefined, prog("total", 460)],
  ["Opanuj peaking i podejścia zawodnicze (attempt selection)", undefined, prog("technika", 5)],
  ["Przysiad 180 kg", undefined, prog("przysiad", 180)],
  ["Wyciśnij 110 kg", undefined, prog("wyciskanie", 110)],
  ["Martwy ciąg 220 kg", undefined, prog("martwy", 220)],
  ["Zaliczy total 500 kg", "Klub 500 kg.", prog("total", 500)],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  // 46-65 · Zaawansowany
  ["Trenuj z pełną periodyzacją pod starty przez sezon"],
  ["Przysiad 200 kg", "Dwieście w przysiadzie.", prog("przysiad", 200)],
  ["Wyciśnij 120 kg", undefined, prog("wyciskanie", 120)],
  ["Martwy ciąg 240 kg", undefined, prog("martwy", 240)],
  ["Zaliczy total 540 kg", undefined, prog("total", 540)],
  ["Zajmij miejsce w czołówce mistrzostw okręgu"],
  ["Przysiad 210 kg", undefined, prog("przysiad", 210)],
  ["Wyciśnij 130 kg", undefined, prog("wyciskanie", 130)],
  ["Martwy ciąg 250 kg", undefined, prog("martwy", 250)],
  ["Zaliczy total 580 kg", undefined, prog("total", 580)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju (kategoria)"],
  ["Przysiad 220 kg", undefined, prog("przysiad", 220)],
  ["Wyciśnij 140 kg", undefined, prog("wyciskanie", 140)],
  ["Martwy ciąg 270 kg", undefined, prog("martwy", 270)],
  ["Zaliczy total 620 kg", undefined, prog("total", 620)],
  ["Zdobądź minimum na mistrzostwa kraju seniorów"],
  ["Przysiad 240 kg", undefined, prog("przysiad", 240)],
  ["Wyciśnij 150 kg", undefined, prog("wyciskanie", 150)],
  ["Martwy ciąg 290 kg", undefined, prog("martwy", 290)],
  ["Zaliczy total 660 kg", undefined, prog("total", 660)],
  // 66-85 · Wyczynowy
  ["Zdobądź medal mistrzostw kraju"],
  ["Przysiad 260 kg", undefined, prog("przysiad", 260)],
  ["Wyciśnij 160 kg", undefined, prog("wyciskanie", 160)],
  ["Martwy ciąg 300 kg", "Trzysta w martwym.", prog("martwy", 300)],
  ["Zaliczy total 700 kg", "Klub 700 kg — poziom krajowej czołówki.", prog("total", 700)],
  ["Wystartuj w zawodach międzynarodowych"],
  ["Przysiad 280 kg", undefined, prog("przysiad", 280)],
  ["Wyciśnij 170 kg", undefined, prog("wyciskanie", 170)],
  ["Martwy ciąg 320 kg", undefined, prog("martwy", 320)],
  ["Zaliczy total 740 kg", undefined, prog("total", 740)],
  ["Zdobądź minimum na mistrzostwa Europy/świata"],
  ["Przysiad 300 kg", "Trzysta w przysiadzie.", prog("przysiad", 300)],
  ["Wyciśnij 180 kg", undefined, prog("wyciskanie", 180)],
  ["Martwy ciąg 340 kg", undefined, prog("martwy", 340)],
  ["Zaliczy total 780 kg", undefined, prog("total", 780)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw regionu"],
  ["Przysiad 320 kg", undefined, prog("przysiad", 320)],
  ["Wyciśnij 200 kg", "Dwieście w wyciskaniu.", prog("wyciskanie", 200)],
  ["Martwy ciąg 360 kg", undefined, prog("martwy", 360)],
  ["Zaliczy total 820 kg", undefined, prog("total", 820)],
  // 86-99 · Elita
  ["Zdobądź medal mistrzostw regionu"],
  ["Przysiad 350 kg", undefined, prog("przysiad", 350)],
  ["Wyciśnij 220 kg", undefined, prog("wyciskanie", 220)],
  ["Martwy ciąg 380 kg", undefined, prog("martwy", 380)],
  ["Zaliczy total 880 kg", undefined, prog("total", 880)],
  ["Zdobądź medal mistrzostw kraju amatorów"],
  ["Przysiad 380 kg", undefined, prog("przysiad", 380)],
  ["Wyciśnij 240 kg", undefined, prog("wyciskanie", 240)],
  ["Martwy ciąg 400 kg", "Czterysta w martwym.", prog("martwy", 400)],
  ["Zaliczy total 950 kg", "Bardzo wysoki total (klasa ciężka).", prog("total", 950)],
  ["Ustanów swój rekord życiowy w boju lub totalu", undefined, prog("technika", 6)],
  ["Zaliczy total 1000 kg (klub tony)", "Tona w trójboju.", prog("total", 1000)],
  ["Zdobądź złoto mistrzostw kraju amatorów"],
  ["Poziom mistrzowski (amatorski szczyt): tona w trójboju i wieloletni, dojrzały warsztat", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata IPF) potwierdzają osobne certyfikaty."],
]);
