// Mountain hiking ladder 1-99. Mixes auto-evaluable trail distances (log km
// and time of hikes) with manual summit milestones (progression tracks by
// altitude, Korona Gór Polski count, and skill milestones without criteria).
import type { Criterion } from "../../src/lib/milestone-criteria";
import type { MilestoneResource } from "../../src/lib/milestone-resources";
import { ladder, d, t, weekly, monthly, total, freq, prog } from "./helpers";

export const activity = {
  slug: "turystyka-gorska",
  name: "Turystyka górska",
  icon: "🥾",
  description:
    "Szlaki, szczyty i długie dni w górach — od pierwszego spaceru po Koronę Gór Polski i czterotysięczniki. Wycieczki loguj w km.",
  sortOrder: 20,
  logKind: "distance" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Przejdź 3 km w terenie", "Dowolna ścieżka poza asfaltem."],
  ["Przejdź 5 km w terenie"],
  ["Spędź 2 godziny w drodze na szlaku"],
  ["Zdobądź pierwszy szczyt z oznakowanym szlakiem", "Dowolny — liczy się wierzchołek."],
  ["Przejdź 8 km w terenie"],
  ["Przejdź 10 km w terenie"],
  ["Spędź 3 godziny w drodze na szlaku"],
  ["Zdobądź szczyt powyżej 500 m n.p.m."],
  ["Przejdź 12 km w terenie"],
  ["Zdobądź szczyt powyżej 1000 m n.p.m.", "Beskidy, Sudety — pierwsze prawdziwe góry."],
  // 11-25 · Regularny
  ["Wychodź na szlak raz w tygodniu przez 4 kolejne tygodnie"],
  ["Przejdź 14 km w terenie"],
  ["Spędź 4 godziny w drodze na szlaku"],
  ["Przejdź 40 km łącznie w jednym miesiącu"],
  ["Przejdź 16 km w terenie"],
  ["Zdobądź 3 szczyty Korony Gór Polski", "28 najwyższych szczytów pasm Polski."],
  ["Przejdź 18 km w terenie"],
  ["Spędź 5 godzin w drodze na szlaku"],
  ["Przejdź łącznie 100 km po szlakach"],
  ["Zdobądź szczyt powyżej 1500 m n.p.m.", "Babia Góra, Śnieżka, tatrzańskie doliny wyżej."],
  ["Przejdź 20 km w terenie", "Pełnodniowa wycieczka."],
  ["Przejdź 60 km łącznie w jednym miesiącu"],
  ["Ukończ wycieczkę z przewyższeniem 800 m+", "Suma podejść z aplikacji/zegarka."],
  ["Przejdź 22 km w terenie"],
  ["Zdobądź 5 szczytów Korony Gór Polski"],
  // 26-45 · Średniozaawansowany
  ["Spędź 6 godzin w drodze na szlaku"],
  ["Przejdź 25 km w terenie"],
  ["Zdobądź szczyt powyżej 2000 m n.p.m.", "Tatry — np. Kasprowy Wierch, Giewont."],
  ["Przejdź łącznie 300 km po szlakach"],
  ["Ukończ wycieczkę z przewyższeniem 1200 m+"],
  ["Przejdź 28 km w terenie"],
  ["Przejdź 80 km łącznie w jednym miesiącu"],
  ["Przejdź szlak grzbietowy łączący 3 szczyty w jeden dzień"],
  ["Zdobądź 10 szczytów Korony Gór Polski"],
  ["Spędź 8 godzin w drodze na szlaku"],
  ["Przejdź 30 km w terenie"],
  ["Zdobądź Rysy lub inny szczyt powyżej 2400 m n.p.m.", "Dach Polski: 2499 m."],
  ["Ukończ dwudniową wędrówkę z noclegiem w schronisku lub pod namiotem"],
  ["Przejdź 32 km w terenie"],
  ["Przejdź łącznie 500 km po szlakach"],
  ["Ukończ wycieczkę z przewyższeniem 1500 m+"],
  ["Przejdź 100 km łącznie w jednym miesiącu"],
  ["Przejdź 35 km w terenie"],
  ["Przejdź szlak eksponowany, z łańcuchami (np. Orla Perć — fragment)", "Wymaga pewności kroku i braku lęku wysokości."],
  ["Zdobądź 15 szczytów Korony Gór Polski"],
  // 46-65 · Zaawansowany
  ["Spędź 10 godzin w drodze na szlaku"],
  ["Przejdź 38 km w terenie"],
  ["Ukończ trzydniową wędrówkę z plecakiem"],
  ["Przejdź 40 km w terenie"],
  ["Zdobądź szczyt powyżej 2600 m n.p.m.", "Alpy, Pireneje, Kaukaz niski — wyżej niż Tatry."],
  ["Przejdź łącznie 1000 km po szlakach"],
  ["Ukończ wycieczkę z przewyższeniem 2000 m+"],
  ["Przejdź 120 km łącznie w jednym miesiącu"],
  ["Przejdź 42 km w terenie"],
  ["Zdobądź 20 szczytów Korony Gór Polski"],
  ["Przejdź całą Orlą Perć lub via ferratę o trudności B/C"],
  ["Przejdź 45 km w terenie"],
  ["Zdobądź szczyt powyżej 3000 m n.p.m.", "Pierwszy trzytysięcznik — wysokość zaczyna być odczuwalna."],
  ["Ukończ tygodniową wędrówkę (5+ dni z rzędu na szlaku)"],
  ["Przejdź 48 km w terenie"],
  ["Przejdź łącznie 2000 km po szlakach"],
  ["Spędź 12 godzin w drodze na szlaku"],
  ["Przejdź 50 km w terenie", "Pół setki w górach jednym ciągiem."],
  ["Ukończ wycieczkę z przewyższeniem 2500 m+"],
  ["Zdobądź pełną Koronę Gór Polski (28 szczytów)", "Odznaka zdobywcy KGP."],
  // 66-85 · Wyczynowy
  ["Przejdź 150 km łącznie w jednym miesiącu"],
  ["Zdobądź szczyt powyżej 3500 m n.p.m."],
  ["Przejdź 55 km w terenie"],
  ["Przejdź główny szlak beskidzki lub sudecki w całości (etapami)", "Ok. 500 km kultowego szlaku."],
  ["Ukończ wycieczkę z przewyższeniem 3000 m+"],
  ["Przejdź 60 km w terenie"],
  ["Przejdź łącznie 3000 km po szlakach"],
  ["Zdobądź szczyt powyżej 4000 m n.p.m.", "Czterotysięcznik alpejski — np. Breithorn, Gran Paradiso."],
  ["Spędź 16 godzin w drodze na szlaku"],
  ["Przejdź 65 km w terenie"],
  ["Przejdź 200 km łącznie w jednym miesiącu"],
  ["Ukończ górski rajd/bieg długodystansowy jako uczestnik", "Np. rajd 50 km+ w formule non-stop."],
  ["Przejdź 70 km w terenie"],
  ["Zdobądź 3 różne czterotysięczniki"],
  ["Przejdź łącznie 5000 km po szlakach"],
  ["Przejdź 75 km w terenie"],
  ["Ukończ wędrówkę z przewyższeniem 4000 m+ w jeden dzień"],
  ["Przejdź 80 km w terenie"],
  ["Zdobądź szczyt powyżej 4500 m n.p.m.", "Np. Matterhorn, Mont Blanc — wspinaczka wysokogórska."],
  ["Przejdź 90 km w terenie"],
  // 86-99 · Elita
  ["Przejdź 250 km łącznie w jednym miesiącu"],
  ["Przejdź 100 km w terenie bez snu", "Format setek górskich (np. Łemkowyna, Beskidy Ultra)."],
  ["Zdobądź 10 różnych szczytów powyżej 3000 m"],
  ["Przejdź łącznie 10 000 km po szlakach"],
  ["Spędź 24 godziny w ciągłym marszu górskim"],
  ["Zdobądź szczyt powyżej 5000 m n.p.m.", "Np. Elbrus, Kilimandżaro — strefa wysokościowa."],
  ["Przejdź 110 km w terenie"],
  ["Przejdź długodystansowy szlak 700 km+ w jednej wyprawie", "GR20+, Camino frances, TMB wielokrotnie…"],
  ["Przejdź 120 km w terenie"],
  ["Zdobądź szczyt powyżej 6000 m n.p.m.", "Andy, Himalaje trekkingowe — np. Aconcagua, Island Peak."],
  ["Przejdź 300 km łącznie w jednym miesiącu"],
  ["Przejdź 140 km w terenie"],
  ["Zdobądź szczyt powyżej 7000 m n.p.m."],
  ["Poziom himalajski: szczyt powyżej 8000 m lub 160 km górskiego ultra non-stop", "Korona Himalajów zaczyna się tutaj."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  1: d(3), 2: d(5), 3: t(120), 5: d(8), 6: d(10), 7: t(180), 9: d(12),
  4: prog("szczyt", 200), 8: prog("szczyt", 500), 10: prog("szczyt", 1000),
  11: freq(1, 4), 12: d(14), 13: t(240), 14: monthly(40), 15: d(16),
  16: prog("kgp", 3), 17: d(18), 18: t(300), 19: total(100), 20: prog("szczyt", 1500),
  21: d(20), 22: monthly(60), 23: prog("przewyzszenie", 800), 24: d(22), 25: prog("kgp", 5),
  26: t(360), 27: d(25), 28: prog("szczyt", 2000), 29: total(300), 30: prog("przewyzszenie", 1200),
  31: d(28), 32: monthly(80), 34: prog("kgp", 10), 35: t(480),
  36: d(30), 37: prog("szczyt", 2400), 39: d(32), 40: total(500),
  41: prog("przewyzszenie", 1500), 42: monthly(100), 43: d(35), 45: prog("kgp", 15),
  46: t(600), 47: d(38), 49: d(40), 50: prog("szczyt", 2600),
  51: total(1000), 52: prog("przewyzszenie", 2000), 53: monthly(120), 54: d(42), 55: prog("kgp", 20),
  57: d(45), 58: prog("szczyt", 3000), 60: d(48),
  61: total(2000), 62: t(720), 63: d(50), 64: prog("przewyzszenie", 2500), 65: prog("kgp", 28),
  66: monthly(150), 67: prog("szczyt", 3500), 68: d(55), 70: prog("przewyzszenie", 3000),
  71: d(60), 72: total(3000), 73: prog("szczyt", 4000), 74: t(960), 75: d(65),
  76: monthly(200), 78: d(70), 80: total(5000),
  81: d(75), 82: prog("przewyzszenie", 4000), 83: d(80), 84: prog("szczyt", 4500), 85: d(90),
  86: monthly(250), 87: d(100), 89: total(10000), 90: t(1440),
  91: prog("szczyt", 5000), 92: d(110), 94: d(120), 95: prog("szczyt", 6000),
  96: monthly(300), 97: d(140), 98: prog("szczyt", 7000),
  // 33, 38, 44, 48, 56, 59, 69, 77, 79, 88, 93, 99 — manual (skill/expedition), no criteria.
};

void weekly;

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "article", title: "Hiking for beginners — getting started", url: "https://www.rei.com/learn/expert-advice/hiking-for-beginners.html" }],
  5: [{ kind: "video", title: "10 essential hiking tips for beginners", url: yt("wGzCNjSJJHE") }],
  10: [{ kind: "article", title: "What to pack for a day hike — checklist", url: "https://www.rei.com/learn/expert-advice/day-hiking-checklist.html" }],
  16: [{ kind: "article", title: "Korona Gór Polski — lista szczytów", url: "https://www.koronagorspolski.pl/" }],
  28: [{ kind: "video", title: "High altitude hiking — acclimatization tips", url: yt("jYiOA4Rmh-I") }],
  38: [{ kind: "article", title: "Overnight backpacking essentials — REI guide", url: "https://www.rei.com/learn/expert-advice/backpacking-beginners.html" }],
  44: [{ kind: "video", title: "Via ferrata — what to know before you go", url: yt("5jXVOKUNV3k") }],
  58: [{ kind: "article", title: "Trekking at altitude — 3000m+ preparation", url: "https://www.rei.com/learn/expert-advice/altitude-sickness.html" }],
  73: [{ kind: "video", title: "Climbing a 4000m peak — what to expect", url: yt("CXVoS4iQ3Hg") }],
  91: [{ kind: "article", title: "High altitude mountaineering — 5000m+ guide", url: "https://www.rei.com/learn/expert-advice/mountaineering-basics.html" }],
};
