// Windsurfing ladder 1-99. Manual — progression tracks: skill line (uphaul →
// planing → harness → waterstart → jibe → loops), top speed (knots), and
// competition level.
import { ladderC, freq, prog } from "./helpers";
import type { MilestoneResource } from "../../src/lib/milestone-resources";

export const activity = {
  slug: "windsurfing",
  name: "Windsurfing",
  icon: "🏄",
  description:
    "Deska z żaglem — od wyciągania żagla po ślizg, harness i skoki. Progresja: umiejętności, prędkość (węzły) i poziom zawodów.",
  sortOrder: 47,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Utrzymaj równowagę na desce w miejscu", undefined, prog("technika", 1)],
  ["Wyciągnij żagiel z wody (uphaul)", undefined, prog("technika", 2)],
  ["Popłyń w linii prostej na desce z żaglem", undefined, prog("technika", 3)],
  ["Wykonaj zwrot przez sztag (hals) na desce", undefined, prog("technika", 4)],
  ["Wykonaj zwrot przez rufę", undefined, prog("technika", 5)],
  ["Płyń pod wiatr (ostro na wiatr)", undefined, prog("technika", 6)],
  ["Kontroluj kurs w obie strony i wracaj do punktu startu", undefined, prog("technika", 7)],
  ["Popłyń przy wietrze 3-4°B bez wywrócenia się", undefined, prog("technika", 8)],
  ["Opanuj pozycję z wypięciem bioder (rozpoczęcie trapezu)", undefined, prog("technika", 9)],
  ["Popływaj łącznie 10 godzin na wodzie", undefined, prog("godziny", 10)],
  // 11-25 · Regularny
  ["Pływaj raz w tygodniu przez 4 tygodnie w sezonie", undefined, freq(1, 4)],
  ["Zaczep się w trapez (harness) i płyń odciążając ręce", undefined, prog("technika", 10)],
  ["Osiągnij pierwszy ślizg (planing)", "Deska wychodzi na wodę — nowy świat.", prog("technika", 11)],
  ["Wepnij stopy w pętle (footstraps) w ślizgu", undefined, prog("technika", 12)],
  ["Osiągnij prędkość 15 węzłów", undefined, prog("predkosc", 15)],
  ["Popłyń przy wietrze 5°B", undefined, prog("technika", 13)],
  ["Popływaj łącznie 30 godzin", undefined, prog("godziny", 30)],
  ["Wykonaj power jibe (zwrot w ślizgu) — próba", undefined, prog("technika", 14)],
  ["Osiągnij prędkość 18 węzłów", undefined, prog("predkosc", 18)],
  ["Płyń w ślizgu przez dłuższy odcinek bez wypadania", undefined, prog("technika", 15)],
  ["Wykonaj waterstart (start z wody bez uphaul)", "Kluczowa umiejętność.", prog("technika", 16)],
  ["Osiągnij prędkość 20 węzłów", undefined, prog("predkosc", 20)],
  ["Popływaj łącznie 60 godzin", undefined, prog("godziny", 60)],
  ["Wykonaj czysty power jibe z zachowaniem ślizgu", undefined, prog("technika", 17)],
  ["Wystartuj w pierwszych zawodach lub regatach klubowych"],
  // 26-45 · Średniozaawansowany
  ["Pływaj regularnie przez cały sezon (2×/tydz.)", undefined, freq(2, 12)],
  ["Osiągnij prędkość 22 węzły", undefined, prog("predkosc", 22)],
  ["Wykonaj carve jibe na dużej prędkości", undefined, prog("technika", 18)],
  ["Popływaj łącznie 100 godzin", undefined, prog("godziny", 100)],
  ["Osiągnij prędkość 25 węzłów", undefined, prog("predkosc", 25)],
  ["Pływaj przy silnym wietrze 6°B", undefined, prog("technika", 19)],
  ["Wykonaj chop hop (mały skok z fali/zmarszczki)", undefined, prog("technika", 20)],
  ["Osiągnij prędkość 27 węzłów", undefined, prog("predkosc", 27)],
  ["Popływaj łącznie 150 godzin", undefined, prog("godziny", 150)],
  ["Wykonaj skok z fali (jump) z kontrolowanym lądowaniem", undefined, prog("technika", 21)],
  ["Osiągnij prędkość 30 węzłów", undefined, prog("predkosc", 30)],
  ["Pływaj w falach (bump and jump)", undefined, prog("technika", 22)],
  ["Zajmij miejsce w pierwszej połowie zawodów regionalnych"],
  ["Wykonaj duck jibe (zwrot z przełożeniem żagla)", undefined, prog("technika", 23)],
  ["Osiągnij prędkość 32 węzły", undefined, prog("predkosc", 32)],
  ["Popływaj łącznie 250 godzin", undefined, prog("godziny", 250)],
  ["Wykonaj forward loop (pierwsza rotacja) — próba", undefined, prog("technika", 24)],
  ["Osiągnij prędkość 35 węzłów", undefined, prog("predkosc", 35)],
  ["Zajmij miejsce na podium zawodów regionalnych"],
  ["Wykonaj czysty forward loop z lądowaniem", "Pierwsza pętla — kamień milowy freestyle.", prog("technika", 25)],
  // 46-65 · Zaawansowany
  ["Pływaj intensywnie przez cały sezon"],
  ["Osiągnij prędkość 37 węzłów", undefined, prog("predkosc", 37)],
  ["Wykonaj back loop — próba", undefined, prog("technika", 26)],
  ["Popływaj łącznie 400 godzin", undefined, prog("godziny", 400)],
  ["Osiągnij prędkość 39 węzłów", undefined, prog("predkosc", 39)],
  ["Surfuj falę w stylu wave riding (bottom turn + cutback)", undefined, prog("technika", 27)],
  ["Wykonaj czysty back loop", undefined, prog("technika", 28)],
  ["Osiągnij prędkość 40 węzłów", "Bariera 40 węzłów.", prog("predkosc", 40)],
  ["Popływaj łącznie 600 godzin", undefined, prog("godziny", 600)],
  ["Wykonaj element freestyle (vulcan lub spock) — próba", undefined, prog("technika", 29)],
  ["Zajmij miejsce w czołówce zawodów krajowych"],
  ["Osiągnij prędkość 42 węzły", undefined, prog("predkosc", 42)],
  ["Wykonaj czysty vulcan/spock", undefined, prog("technika", 30)],
  ["Popływaj łącznie 800 godzin", undefined, prog("godziny", 800)],
  ["Osiągnij prędkość 44 węzły", undefined, prog("predkosc", 44)],
  ["Zdobądź medal mistrzostw kraju (klasa slalom/wave/freestyle)"],
  ["Wykonaj kombinację trików freestyle w jednym przejeździe", undefined, prog("technika", 31)],
  ["Osiągnij prędkość 45 węzłów", undefined, prog("predkosc", 45)],
  ["Popływaj łącznie 1000 godzin", undefined, prog("godziny", 1000)],
  ["Uzyskaj wynik kwalifikujący do zawodów międzynarodowych"],
  // 66-85 · Wyczynowy
  ["Osiągnij prędkość 46 węzłów", undefined, prog("predkosc", 46)],
  ["Wystartuj w cyklu regat krajowych wysokiej rangi"],
  ["Wykonaj double forward loop — próba", undefined, prog("technika", 32)],
  ["Osiągnij prędkość 47 węzłów", undefined, prog("predkosc", 47)],
  ["Zdobądź punkty w rankingu międzynarodowym"],
  ["Wykonaj czysty double forward", undefined, prog("technika", 33)],
  ["Osiągnij prędkość 48 węzłów", undefined, prog("predkosc", 48)],
  ["Zajmij miejsce w pierwszej ósemce zawodów międzynarodowych"],
  ["Wykonaj push loop lub table top na fali", undefined, prog("technika", 34)],
  ["Osiągnij prędkość 49 węzłów", undefined, prog("predkosc", 49)],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Osiągnij prędkość 50 węzłów", "Elita speedu — poziom rekordów akwenu.", prog("predkosc", 50)],
  ["Wystartuj w prestiżowych regatach krajowych"],
  ["Wykonaj zaawansowany trik freestyle (culo, shaka)", undefined, prog("technika", 35)],
  ["Osiągnij prędkość 52 węzły", undefined, prog("predkosc", 52)],
  ["Zajmij miejsce w pierwszej piętnastce zawodów o zasięgu ogólnokrajowym"],
  ["Osiągnij prędkość 54 węzły", undefined, prog("predkosc", 54)],
  ["Wykonaj kombinację najtrudniejszych znanych sobie trików na fali/freestyle", undefined, prog("technika", 36)],
  ["Zdobądź tytuł mistrza regionu"],
  ["Osiągnij prędkość 56 węzłów", undefined, prog("predkosc", 56)],
  // 86-99 · Elita
  ["Zajmij miejsce w pierwszej dziesiątce zawodów o zasięgu ogólnokrajowym"],
  ["Osiągnij prędkość 58 węzłów", undefined, prog("predkosc", 58)],
  ["Wygraj heat na zawodach o zasięgu ogólnokrajowym"],
  ["Osiągnij prędkość 60 węzłów", undefined, prog("predkosc", 60)],
  ["Zajmij miejsce w pierwszej szóstce zawodów o zasięgu ogólnokrajowym"],
  ["Osiągnij prędkość 62 węzły", undefined, prog("predkosc", 62)],
  ["Zdobądź podium etapu zawodów o zasięgu ogólnokrajowym"],
  ["Osiągnij prędkość 64 węzły", undefined, prog("predkosc", 64)],
  ["Zajmij miejsce w pierwszej trójce klasyfikacji kraju amatorów"],
  ["Wygraj etap zawodów o zasięgu ogólnokrajowym"],
  ["Osiągnij prędkość 66 węzłów", "Bardzo rzadki, wieloletnio wypracowany wynik.", prog("predkosc", 66)],
  ["Zdobądź tytuł mistrza kraju amatorów"],
  ["Poprowadź kogoś przez zaawansowaną technikę windsurfingu"],
  ["Poziom mistrzowski (amatorski szczyt): wieloletni, dojrzały warsztat windsurfingowy", "Dalsze, zawodowe osiągnięcia (PWA World Tour, rekordy prędkości) potwierdzają osobne certyfikaty."],
]);

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const resourcesByLevel: Record<number, MilestoneResource[]> = {
  1: [{ kind: "video", title: "Windsurfing basics — getting started", url: yt("v_6CLaCJtYc") }],
  3: [{ kind: "video", title: "How to sail in a straight line — windsurfing", url: yt("KA8VBn4cNgg") }],
  12: [{ kind: "video", title: "How to use a harness — windsurfing technique", url: yt("IbJfLGa8sxY") }],
  13: [{ kind: "video", title: "How to plane — windsurfing breakthrough", url: yt("k6WT5PLSLX4") }],
  21: [{ kind: "video", title: "How to waterstart — essential windsurfing skill", url: yt("0WZfeAPHebM") }],
  24: [{ kind: "video", title: "How to power jibe — windsurfing turn", url: yt("ZVEZg_fOQ2I") }],
  35: [{ kind: "video", title: "How to jump — windsurfing high wind", url: yt("M6j5i8MdFDw") }],
  42: [{ kind: "video", title: "Forward loop tutorial — windsurfing freestyle", url: yt("b7gVPE95yRk") }],
  51: [{ kind: "video", title: "Wave riding — bottom turn and cutback", url: yt("GlGPbXGqnqs") }],
  67: [{ kind: "article", title: "PWA World Tour — competitive windsurfing", url: "https://www.pwaworldtour.com/" }],
};
