// Climbing ladder 1-99. Tracks: bouldering grade (V-scale), rope grade
// (French scale, encoded ×10: 6a=60, 6b=62, 6c=64, 7a=70…), sessions.
// Grade benchmarks: V0-V2 beginner year one; V4-V5 solid intermediate;
// V7+ advanced; V10+ elite amateur. Rope: 6a first year, 7a dedicated
// amateur ("magic line"), 8a elite amateur.
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "wspinaczka",
  name: "Wspinaczka",
  icon: "🧗",
  description:
    "Bouldering i wspinaczka linowa — od pierwszej ścianki po skały. Progi wg skal V (boulder) i francuskiej (lina).",
  sortOrder: 15,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Wejdź na szczyt dowolnej drogi na ściance", "Kolor nieważny — liczy się góra."],
  ["Ukończ pierwszy boulder V0/4 (najłatwiejszy kolor)"],
  ["Zejdź kontrolowanie (zeskocz na matę z przysiadem)"],
  ["Ukończ 3 różne bouldery V0"],
  ["Ukończ pierwszą sesję 1,5 h na ściance"],
  ["Ukończ boulder V1"],
  ["Wykonaj poprawne ułożenie ciała „żabka” (biodra przy ścianie)"],
  ["Ukończ 5 sesji wspinaczkowych"],
  ["Ukończ 3 różne bouldery V1"],
  ["Ukończ boulder V2"],
  // 11-25 · Regularny
  ["Wspinaj się raz w tygodniu przez 4 kolejne tygodnie"],
  ["Zdaj kurs asekuracji na wędkę (top rope)"],
  ["Przejdź pierwszą drogę na wędkę (dowolna trudność)"],
  ["Ukończ 10 sesji"],
  ["Przejdź drogę 4+ na wędkę"],
  ["Ukończ 3 różne bouldery V2"],
  ["Przejdź drogę 5a na wędkę"],
  ["Ukończ boulder V3", "Wejście w poziom „regularnego” boulderowca."],
  ["Ukończ 20 sesji"],
  ["Przejdź drogę 5b na wędkę"],
  ["Opanuj chwyt zamknięty/otwarty i rozpoznawanie chwytów"],
  ["Wspinaj się 2 razy w tygodniu przez 8 kolejnych tygodni"],
  ["Przejdź drogę 5c na wędkę"],
  ["Ukończ 3 różne bouldery V3"],
  ["Ukończ 35 sesji"],
  // 26-45 · Średniozaawansowany
  ["Zdaj kurs prowadzenia (lead) na ściance"],
  ["Przejdź pierwszą drogę z dolną asekuracją"],
  ["Ukończ boulder V4", "Pierwszy poziom wymagający realnej siły palców."],
  ["Przejdź drogę 6a na wędkę", "6a to klasyczny próg „umiem się wspinać”."],
  ["Ukończ 50 sesji"],
  ["Zalicz pierwszy odpad na prowadzeniu (kontrolowany)", "Strach przed lotem blokuje bardziej niż siła."],
  ["Przejdź drogę 6a na prowadzeniu"],
  ["Ukończ 3 różne bouldery V4"],
  ["Przejdź drogę 6a+ na prowadzeniu"],
  ["Ukończ 75 sesji"],
  ["Ukończ boulder V5"],
  ["Wspinaj się na skałach (outdoor) po raz pierwszy", "Prawdziwa skała to inna bajka niż plastik."],
  ["Przejdź drogę 6b na prowadzeniu"],
  ["Zwis na krawądce 20 mm przez 10 sekund", "Mierzalna siła palców."],
  ["Ukończ 100 sesji", "Setka sesji na ścianie."],
  ["Przejdź skalną drogę 6a"],
  ["Ukończ 3 różne bouldery V5"],
  ["Przejdź drogę 6b+ na prowadzeniu"],
  ["Ukończ boulder V6"],
  ["Przejdź 10 różnych dróg 6a+ lub trudniejszych"],
  // 46-65 · Zaawansowany
  ["Przejdź drogę 6c na prowadzeniu"],
  ["Ukończ 150 sesji"],
  ["Zrób trawers całej ścianki bez dotknięcia ziemi"],
  ["Przejdź skalną drogę 6b"],
  ["Ukończ 3 różne bouldery V6"],
  ["Przejdź drogę 6c+ na prowadzeniu"],
  ["Zwis na krawądce 20 mm przez 20 sekund"],
  ["Ukończ boulder V7", "Poziom zaawansowany — regularny trening siłowy jest konieczny."],
  ["Ukończ 200 sesji"],
  ["Przejdź drogę 7a na prowadzeniu", "Magiczna liczba wspinaczy amatorów."],
  ["Wspinaj się na skałach w 3 różnych rejonach"],
  ["Przejdź drogę wielowyciągową (multipitch) z przewodnikiem/partnerem"],
  ["Ukończ 3 różne bouldery V7"],
  ["Przejdź skalną drogę 6c"],
  ["Ukończ 250 sesji"],
  ["Przejdź drogę 7a+ na prowadzeniu"],
  ["Ukończ boulder V8"],
  ["Zrób flash drogi 6b+ (przejście za pierwszym razem z obserwacji)"],
  ["Przejdź skalną drogę 7a"],
  ["Ukończ 300 sesji"],
  // 66-85 · Wyczynowy
  ["Przejdź drogę 7b na prowadzeniu"],
  ["Zwis na krawądce 20 mm z dodatkowym obciążeniem 10 kg"],
  ["Ukończ 3 różne bouldery V8"],
  ["Weź udział w zawodach wspinaczkowych (dowolna ranga)"],
  ["Przejdź drogę 7b+ na prowadzeniu"],
  ["Ukończ 400 sesji"],
  ["Ukończ boulder V9"],
  ["Zrób onsight drogi 6c (bez wcześniejszej wiedzy o drodze)"],
  ["Przejdź skalną drogę 7b"],
  ["Przejdź drogę 7c na prowadzeniu"],
  ["Ukończ 500 sesji", "Pół tysiąca sesji."],
  ["Przejdź multipitch 6b lub trudniejszy jako prowadzący"],
  ["Ukończ 3 różne bouldery V9"],
  ["Zdobądź finał zawodów lokalnych"],
  ["Przejdź drogę 7c+ na prowadzeniu"],
  ["Ukończ boulder V10", "Dwucyfrowe V — elita amatorskiego boulderingu."],
  ["Zrób onsight drogi 7a"],
  ["Ukończ 600 sesji"],
  ["Przejdź skalną drogę 7c"],
  ["Przejdź drogę 8a na prowadzeniu", "8a — mityczna granica, poziom elity amatorskiej."],
  // 86-99 · Elita
  ["Ukończ 3 różne bouldery V10"],
  ["Zdobądź podium zawodów regionalnych"],
  ["Ukończ 750 sesji"],
  ["Ukończ boulder V11"],
  ["Zrób onsight drogi 7b"],
  ["Przejdź drogę 8a+ na prowadzeniu"],
  ["Przejdź skalną drogę 8a"],
  ["Ukończ 900 sesji"],
  ["Ukończ boulder V12"],
  ["Weź udział w zawodach amatorskich rangi regionalnej"],
  ["Przejdź drogę 8a+ na prowadzeniu z redpointem"],
  ["Zrób onsight drogi 7c"],
  ["Ukończ 1000 sesji", "Cztery cyfry sesji wspinaczkowych."],
  ["Poziom mistrzowski (amatorski szczyt): 8b/V13 lub wieloletnia regularna praktyka", "Dojrzały, wieloletni warsztat wspinaczkowy zaangażowanego amatora. Dalsze, zawodowe osiągnięcia potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  2: prog("boulder", 0), 6: prog("boulder", 1), 10: prog("boulder", 2), 18: prog("boulder", 3),
  28: prog("boulder", 4), 36: prog("boulder", 5), 44: prog("boulder", 6), 53: prog("boulder", 7),
  62: prog("boulder", 8), 72: prog("boulder", 9), 81: prog("boulder", 10), 89: prog("boulder", 11),
  94: prog("boulder", 12),
  15: prog("wedka", 44), 17: prog("wedka", 50), 20: prog("wedka", 52), 23: prog("wedka", 54),
  29: prog("wedka", 60),
  32: prog("lead", 60), 34: prog("lead", 61), 38: prog("lead", 62), 43: prog("lead", 63),
  46: prog("lead", 64), 51: prog("lead", 65), 55: prog("lead", 70), 61: prog("lead", 71),
  66: prog("lead", 72), 70: prog("lead", 73), 75: prog("lead", 74), 80: prog("lead", 75),
  85: prog("lead", 80), 91: prog("lead", 81), 96: prog("lead", 82),
  41: prog("skala", 60), 49: prog("skala", 62), 59: prog("skala", 64), 64: prog("skala", 70),
  74: prog("skala", 72), 84: prog("skala", 73), 92: prog("skala", 80),
  5: prog("sesje", 1), 8: prog("sesje", 5), 14: prog("sesje", 10), 19: prog("sesje", 20),
  25: prog("sesje", 35), 30: prog("sesje", 50), 35: prog("sesje", 75), 40: prog("sesje", 100),
  47: prog("sesje", 150), 54: prog("sesje", 200), 60: prog("sesje", 250), 65: prog("sesje", 300),
  71: prog("sesje", 400), 76: prog("sesje", 500), 83: prog("sesje", 600), 88: prog("sesje", 750),
  93: prog("sesje", 900), 98: prog("sesje", 1000),
  39: prog("krawadka", 10), 52: prog("krawadka", 20), 67: prog("krawadka", 40),
  11: freq(1, 4), 22: freq(2, 8),
  // pozostałe: kursy, onsighty, zawody, multipitche — manualne.
};
