// Wrestling ladder 1-99. Manual — progression tracks: technique, matches, and
// competition level (freestyle/greco-roman, amateur → Olympic).
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "zapasy",
  name: "Zapasy",
  icon: "🤼",
  description:
    "Jeden z najstarszych sportów świata — sprowadzenia, rzuty i kontrola. Progresja: technika, walki i poziom rywalizacji (styl wolny/klasyczny).",
  sortOrder: 69,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj postawę zapaśniczą i poruszanie", undefined, prog("technika", 1)],
  ["Wykonaj poprawny pad i przewrót ochronny", undefined, prog("technika", 2)],
  ["Wykonaj sprowadzenie za nogi (double leg takedown)", undefined, prog("technika", 3)],
  ["Wykonaj sprowadzenie single leg", undefined, prog("technika", 4)],
  ["Opanuj sprawl (obronę przed sprowadzeniem)", undefined, prog("technika", 5)],
  ["Wykonaj przewrót przeciwnika w parterze (turn)", undefined, prog("technika", 6)],
  ["Utrzymaj kontrolę i punktuj w parterze", undefined, prog("technika", 7)],
  ["Odbądź pierwszą walkę treningową", undefined, prog("walki", 1)],
  ["Wykonaj rzut biodrowy lub przez plecy", undefined, prog("technika", 8)],
  ["Odbądź 5 walk treningowych", undefined, prog("walki", 5)],
  // 11-25 · Regularny
  ["Trenuj 3 razy w tygodniu przez 4 kolejne tygodnie", undefined, freq(3, 4)],
  ["Wykonaj kombinację sprowadzeń (setup + takedown)", undefined, prog("technika", 9)],
  ["Odbądź 10 walk", undefined, prog("walki", 10)],
  ["Wykonaj rzut suplesowy (styl klasyczny) z asekuracją", undefined, prog("technika", 10)],
  ["Wystartuj w pierwszych zawodach", undefined, prog("liga", 1)],
  ["Odbądź 20 walk", undefined, prog("walki", 20)],
  ["Wygraj pierwszą walkę na zawodach"],
  ["Zdobądź touché (położenie na łopatki) w walce", undefined, prog("technika", 11)],
  ["Odbądź 35 walk", undefined, prog("walki", 35)],
  ["Opanuj obronę w parterze i ucieczkę spod kontroli", undefined, prog("technika", 12)],
  ["Zajmij miejsce w pierwszej połowie turnieju"],
  ["Odbądź 50 walk", undefined, prog("walki", 50)],
  ["Wykonaj gut wrench (obrót w parterze) z punktami", undefined, prog("technika", 13)],
  ["Zdobądź minimum na mistrzostwa okręgu", undefined, prog("liga", 2)],
  ["Odbądź 70 walk", undefined, prog("walki", 70)],
  // 26-45 · Średniozaawansowany
  ["Trenuj 4-5 razy w tygodniu przez 12 kolejnych tygodni", undefined, freq(4, 12)],
  ["Opanuj tokui-waza (swoją technikę wiodącą)", undefined, prog("technika", 14)],
  ["Zajmij miejsce na podium turnieju regionalnego"],
  ["Odbądź 90 walk", undefined, prog("walki", 90)],
  ["Wykonaj rzut o wysokiej amplitudzie (5 punktów) w walce", undefined, prog("technika", 15)],
  ["Zajmij miejsce w czołówce mistrzostw okręgu"],
  ["Odbądź 120 walk", undefined, prog("walki", 120)],
  ["Wygraj walkę przez przewagę techniczną (10+ punktów)", undefined, prog("technika", 16)],
  ["Zdobądź minimum na mistrzostwa kraju", undefined, prog("liga", 3)],
  ["Odbądź 150 walk", undefined, prog("walki", 150)],
  ["Wygraj walkę z zawodnikiem z rankingu okręgowego"],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju"],
  ["Odbądź 180 walk", undefined, prog("walki", 180)],
  ["Opanuj chain wrestling (łączenie kilku ataków płynnie)", undefined, prog("technika", 17)],
  ["Zdobądź medal mistrzostw kraju juniorów"],
  ["Odbądź 220 walk", undefined, prog("walki", 220)],
  ["Wykonaj skuteczny kontratak na atak rywala", undefined, prog("technika", 18)],
  ["Zajmij miejsce w pierwszej czwórce mistrzostw kraju"],
  ["Odbądź 260 walk", undefined, prog("walki", 260)],
  ["Wygraj walkę touché z zawodnikiem czołowym", undefined, prog("technika", 19)],
  // 46-65 · Zaawansowany
  ["Trenuj na wysokim poziomie klubowym przez cały sezon"],
  ["Zdobądź medal mistrzostw kraju seniorów"],
  ["Odbądź 300 walk", undefined, prog("walki", 300)],
  ["Opanuj pełen arsenał techniczny na mistrzowskim poziomie", undefined, prog("technika", 20)],
  ["Wygraj walkę z czołowym zawodnikiem regionu"],
  ["Zdobądź czołową pozycję w rankingu regionalnym", undefined, prog("liga", 4)],
  ["Odbądź 350 walk", undefined, prog("walki", 350)],
  ["Wystartuj w turnieju międzynarodowym"],
  ["Zdobądź medal na turnieju międzynarodowym"],
  ["Odbądź 400 walk", undefined, prog("walki", 400)],
  ["Zostań mistrzem kraju seniorów"],
  ["Wygraj walkę z zawodnikiem z rankingu światowego"],
  ["Utrzymaj wysoką skuteczność w zawodach rangi światowej", undefined, prog("technika", 21)],
  ["Odbądź 450 walk", undefined, prog("walki", 450)],
  ["Zdobądź punkty w rankingu UWW", undefined, prog("liga", 5)],
  ["Zajmij miejsce w pierwszej ósemce turnieju o zasięgu ogólnokrajowym"],
  ["Odbądź 500 walk", undefined, prog("walki", 500)],
  ["Weź udział w mistrzostwach regionu"],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw regionu"],
  ["Odbądź 550 walk", undefined, prog("walki", 550)],
  // 66-85 · Wyczynowy
  ["Zdobądź medal na turnieju o zasięgu ogólnokrajowym"],
  ["Odbądź 600 walk", undefined, prog("walki", 600)],
  ["Wygraj walkę z uznanym zawodnikiem krajowym"],
  ["Zdobądź medal mistrzostw regionu"],
  ["Odbądź 650 walk", undefined, prog("walki", 650)],
  ["Osiągnij czołową 20 rankingu krajowego"],
  ["Weź udział w mistrzostwach kraju amatorów"],
  ["Odbądź 700 walk", undefined, prog("walki", 700)],
  ["Zajmij miejsce w pierwszej dziesiątce mistrzostw kraju amatorów"],
  ["Utrzymaj wysoki poziom techniczny w swojej kategorii", undefined, prog("technika", 22)],
  ["Odbądź 750 walk", undefined, prog("walki", 750)],
  ["Osiągnij czołową dziesiątkę rankingu krajowego"],
  ["Zdobądź złoto mistrzostw regionu"],
  ["Odbądź 800 walk", undefined, prog("walki", 800)],
  ["Zajmij miejsce w pierwszej ósemce mistrzostw kraju amatorów"],
  ["Wygraj prestiżowy turniej o zasięgu ogólnokrajowym"],
  ["Zdobądź podium mistrzostw kraju amatorów"],
  ["Odbądź 850 walk", undefined, prog("walki", 850)],
  ["Osiągnij czołową piątkę rankingu krajowego"],
  ["Weź udział w mistrzostwach kraju amatorów seniorów"],
  // 86-99 · Elita
  ["Zdobądź srebro lub brąz mistrzostw kraju amatorów"],
  ["Zostań numerem 1 rankingu krajowego w swojej kategorii"],
  ["Awansuj do finału mistrzostw kraju amatorów"],
  ["Odbądź 950 walk", undefined, prog("walki", 950)],
  ["Zdobądź złoto mistrzostw kraju amatorów"],
  ["Poprowadź kogoś przez zaawansowaną technikę zapaśniczą"],
  ["Zdobądź uznanie w krajowym środowisku zapaśniczym"],
  ["Obroń tytuł mistrza kraju amatorów"],
  ["Odbądź 1100 walk", undefined, prog("walki", 1100)],
  ["Zdobądź wielokrotne medale mistrzostw kraju amatorów"],
  ["Poprowadź własną grupę treningową przez dłuższy czas"],
  ["Zdobądź wielokrotne złoto mistrzostw kraju amatorów"],
  ["Osiągnij status uznanego zawodnika swojej kategorii wagowej", undefined, prog("technika", 23)],
  ["Poziom mistrzowski (amatorski szczyt): wielokrotny mistrz kraju amatorów w zapasach", "Dalsze, zawodowe osiągnięcia (mistrzostwa świata, igrzyska) potwierdzają osobne certyfikaty."],
]);
