// Sailing ladder 1-99. Manual — progression tracks: sailing licences/patents
// (PL: żeglarz jachtowy → jachtowy sternik morski → kapitan), miles logged,
// boat handling skills, regatta results.
import type { Criterion } from "../../src/lib/milestone-criteria";
import { ladder, freq, prog } from "./helpers";

export const activity = {
  slug: "zeglarstwo",
  name: "Żeglarstwo",
  icon: "⛵",
  description:
    "Od pierwszego halsu po morskie patenty i regaty. Progresja oparta na polskich stopniach żeglarskich i przepłyniętych milach.",
  sortOrder: 22,
  logKind: "manual" as const,
};

export const milestones = ladder([
  // 1-10 · Pierwsze kroki
  ["Rozpłyń się na jachcie pod okiem instruktora"],
  ["Nazwij części jachtu i takielunku (dziób, rufa, grot, fok, ster)"],
  ["Wykonaj poprawny zwrot przez sztag"],
  ["Wykonaj poprawny zwrot przez rufę"],
  ["Utrzymaj kurs względem wiatru przez 10 minut"],
  ["Postaw i zrzuć żagle samodzielnie"],
  ["Wykonaj manewr „człowiek za burtą” na spokojnej wodzie"],
  ["Zacumuj i odbij od kei bez uderzenia"],
  ["Przepłyń samodzielnie krótką trasę na jeziorze"],
  ["Zdaj egzamin na patent żeglarza jachtowego", "Podstawowy stopień w Polsce."],
  // 11-25 · Regularny
  ["Pływaj lub trenuj raz w tygodniu przez 4 kolejne tygodnie w sezonie"],
  ["Prowadź jacht przy wietrze 3-4°B"],
  ["Zarefuj żagle w silniejszym wietrze"],
  ["Przepłyń łącznie 50 mil morskich"],
  ["Poprowadź jacht kabinowy na jeziorze jako sternik"],
  ["Wykonaj cumowanie rufą do pomostu"],
  ["Zaplanuj i przepłyń dzienny rejs jeziorny (20+ Mm)"],
  ["Rozpoznaj i zareaguj na zmianę pogody"],
  ["Przepłyń łącznie 100 mil morskich"],
  ["Weź udział w pierwszych regatach"],
  ["Prowadź jacht przy wietrze 5°B"],
  ["Odbądź pierwszy rejs morski jako załoga"],
  ["Opanuj obsługę silnika zaburtowego/stacjonarnego"],
  ["Przepłyń łącznie 200 mil morskich"],
  ["Odbądź nocną wachtę na morzu"],
  // 26-45 · Średniozaawansowany
  ["Trenuj lub pływaj 2 razy w tygodniu przez sezon (12 tyg.)"],
  ["Przepłyń łącznie 300 mil morskich"],
  ["Poprowadź jacht w rejsie przybrzeżnym jako sternik"],
  ["Wykonaj nawigację zliczeniową bez GPS na krótkim odcinku"],
  ["Zdaj egzamin na jachtowego sternika morskiego", "Kluczowy morski patent w Polsce."],
  ["Przepłyń łącznie 500 mil morskich"],
  ["Odbądź rejs pełnomorski 100+ Mm bez zawijania"],
  ["Poprowadź manewr MOB pod żaglami na morzu"],
  ["Zaplanuj trasę z uwzględnieniem pływów i prądów"],
  ["Przepłyń przez cieśninę lub kanał morski"],
  ["Odbądź rejs w warunkach 6°B"],
  ["Przepłyń łącznie 750 mil morskich"],
  ["Zajmij miejsce w pierwszej połowie stawki regat"],
  ["Poprowadź jacht nocą z wykorzystaniem świateł nawigacyjnych"],
  ["Przepłyń łącznie 1000 mil morskich"],
  ["Odbądź rejs z co najmniej jednym postojem w obcym porcie"],
  ["Zarządzaj załogą jako skiper na tygodniowym rejsie"],
  ["Opanuj stawianie i obsługę spinakera/gennakera"],
  ["Przepłyń łącznie 1500 mil morskich"],
  ["Odbądź rejs w warunkach 7°B"],
  // 46-65 · Zaawansowany
  ["Przepłyń łącznie 2000 mil morskich"],
  ["Poprowadź rejs morski jako kapitan (skiper) tydzień+"],
  ["Wykonaj bezpieczne wejście do portu przy silnym bocznym wietrze"],
  ["Odbądź rejs nocny 100+ Mm w pojedynkę na wachcie"],
  ["Przepłyń łącznie 3000 mil morskich"],
  ["Stań na podium regat klubowych"],
  ["Odbądź rejs przez otwarte morze (200+ Mm bez lądu)"],
  ["Zdaj egzamin na jachtowego kapitana morskiego", "Najwyższy patent żeglarski w Polsce."],
  ["Przepłyń łącznie 5000 mil morskich"],
  ["Poprowadź jacht w sztormie (8°B)"],
  ["Wykonaj naprawę awaryjną takielunku na morzu"],
  ["Odbądź rejs międzynarodowy z przekroczeniem granicy morskiej"],
  ["Przepłyń łącznie 7500 mil morskich"],
  ["Poprowadź szkolenie mniej doświadczonej załogi"],
  ["Odbądź rejs trwający 14+ dni bez powrotu do bazy"],
  ["Przepłyń łącznie 10 000 mil morskich"],
  ["Zwycięż w regatach klubowych"],
  ["Odbądź rejs po wodach pływowych (np. kanał La Manche)"],
  ["Poprowadź jacht w warunkach 9°B"],
  ["Przepłyń łącznie 15 000 mil morskich"],
  // 66-85 · Wyczynowy
  ["Odbądź samotny rejs morski (100+ Mm solo)"],
  ["Przepłyń łącznie 20 000 mil morskich"],
  ["Poprowadź rejs przez Bałtyk z brzegu na brzeg"],
  ["Stań na podium regat rangi ogólnokrajowej"],
  ["Odbądź rejs oceaniczny jako załoga (przelot 500+ Mm)"],
  ["Przepłyń łącznie 30 000 mil morskich"],
  ["Poprowadź jacht przez cieśninę o silnych prądach (np. Sund, Bełt)"],
  ["Odbądź rejs w wysokich szerokościach (np. Norwegia, Szkocja)"],
  ["Przepłyń łącznie 40 000 mil morskich"],
  ["Zdobądź licencję instruktora żeglarstwa"],
  ["Poprowadź samotny rejs 300+ Mm bez zawinięcia"],
  ["Odbądź przelot przez otwarty ocean jako sternik wachty"],
  ["Przepłyń łącznie 50 000 mil morskich"],
  ["Zwycięż w regatach ogólnokrajowych"],
  ["Poprowadź jacht w sztormie 10°B i bezpiecznie sprowadź załogę"],
  ["Odbądź rejs transoceaniczny (przekrocz ocean)", "Atlantyk, Pacyfik — inny wymiar żeglarstwa."],
  ["Przepłyń łącznie 75 000 mil morskich"],
  ["Poprowadź jako kapitan rejs transoceaniczny"],
  ["Odbądź rejs dookoła morza (np. okrążenie Bałtyku)"],
  ["Przepłyń łącznie 100 000 mil morskich", "Sto tysięcy mil w kilu — dorobek życia żeglarza."],
  // 86-99 · Elita
  ["Odbądź samotny rejs oceaniczny (transatlantyk solo)"],
  ["Weź udział w regatach o zasięgu ogólnokrajowym"],
  ["Poprowadź ekspedycję żeglarską w wymagający, odległy rejon"],
  ["Zdobądź tytuł w mistrzostwach regionu w klasie regatowej"],
  ["Okrąż przylądek (Horn, Dobrej Nadziei lub Leeuwin)"],
  ["Przepłyń łącznie 150 000 mil morskich"],
  ["Poprowadź rejs dookoła kontynentu"],
  ["Ustanów swój rekord życiowy na akwenie regatowym"],
  ["Odbądź rejs dookoła świata jako załoga"],
  ["Zdobądź podium mistrzostw kraju amatorów w klasie regatowej"],
  ["Poprowadź rejs dookoła świata jako kapitan"],
  ["Okrąż samotnie przylądek Horn"],
  ["Przepłyń łącznie 250 000 mil morskich"],
  ["Poziom mistrzowski (amatorski szczyt): samotny rejs dookoła świata bez zawinięcia", "Dalsze, zawodowe osiągnięcia (Vendée Globe i podobne regaty) potwierdzają osobne certyfikaty."],
]);

export const criteriaByLevel: Record<number, Criterion> = {
  1: prog("technika", 1), 2: prog("technika", 2), 3: prog("technika", 3), 4: prog("technika", 4),
  6: prog("technika", 5), 7: prog("technika", 6), 8: prog("technika", 7),
  10: prog("patent", 1), 30: prog("patent", 2), 53: prog("patent", 3),
  14: prog("mile", 50), 19: prog("mile", 100), 24: prog("mile", 200),
  27: prog("mile", 300), 31: prog("mile", 500), 36: prog("mile", 750), 40: prog("mile", 1000),
  44: prog("mile", 1500), 46: prog("mile", 2000), 50: prog("mile", 3000), 54: prog("mile", 5000),
  58: prog("mile", 7500), 61: prog("mile", 10000), 65: prog("mile", 15000),
  67: prog("mile", 20000), 71: prog("mile", 30000), 74: prog("mile", 40000), 78: prog("mile", 50000),
  82: prog("mile", 75000), 85: prog("mile", 100000), 91: prog("mile", 150000), 98: prog("mile", 250000),
  11: freq(1, 4), 26: freq(2, 12),
  // pozostałe: manewry, rejsy, regaty, wydarzenia — manualne.
};
