// Speedway ladder 1-99. Manual — progression tracks: technique, matches, and
// competition level (amateur → Ekstraliga → Speedway GP world championship).
import { ladderC, freq, prog } from "./helpers";

export const activity = {
  slug: "zuzel",
  name: "Żużel",
  icon: "🏁",
  description:
    "Motocykle bez hamulców na owalnym torze żużlowym — cztery okrążenia, cztery zakręty, ślizg. Progresja: technika, mecze i poziom rozgrywek.",
  sortOrder: 77,
  logKind: "manual" as const,
};

export const { milestones, criteriaByLevel } = ladderC([
  // 1-10 · Pierwsze kroki
  ["Opanuj kontrolę motocykla żużlowego (bez hamulca) na prostej", undefined, prog("technika", 1)],
  ["Wejdź w kontrolowany ślizg (broadside) w zakręcie", undefined, prog("technika", 2)],
  ["Pokonaj pełne okrążenie toru żużlowego", undefined, prog("technika", 3)],
  ["Utrzymaj równą linię przez wszystkie 4 zakręty", undefined, prog("technika", 4)],
  ["Wykonaj poprawny start spod taśmy", undefined, prog("technika", 5)],
  ["Przejedź 4 okrążenia (pełny dystans wyścigu) w tempie", undefined, prog("technika", 6)],
  ["Opanuj jazdę przy bandzie i przy krawężniku", undefined, prog("technika", 7)],
  ["Weź udział w pierwszym treningu z innymi zawodnikami", undefined, prog("mecze", 1)],
  ["Zdobądź licencję żużlową (próba toru / egzamin)", undefined, prog("liga", 1)],
  ["Ukończ 3 wyścigi treningowe", undefined, prog("mecze", 3)],
  // 11-25 · Regularny
  ["Trenuj raz w tygodniu przez 4 kolejne tygodnie w sezonie", undefined, freq(1, 4)],
  ["Opanuj wyprzedzanie górą (po zewnętrznej)", undefined, prog("technika", 8)],
  ["Ukończ 6 wyścigów", undefined, prog("mecze", 6)],
  ["Zdobądź pierwsze punkty w zawodach młodzieżowych", undefined, prog("punkty", 1)],
  ["Utrzymaj czoło wyścigu przez 4 okrążenia", undefined, prog("technika", 9)],
  ["Ukończ 10 wyścigów", undefined, prog("mecze", 10)],
  ["Wygraj pierwszy wyścig w zawodach"],
  ["Opanuj wyprzedzanie dołem (spod przeciwnika)", undefined, prog("technika", 10)],
  ["Zdobądź 15 punktów łącznie", undefined, prog("punkty", 15)],
  ["Ukończ 20 wyścigów", undefined, prog("mecze", 20)],
  ["Wystartuj w rozgrywkach ligowych (2. liga / U24)", undefined, prog("liga", 2)],
  ["Zdobądź 40 punktów łącznie", undefined, prog("punkty", 40)],
  ["Ukończ 40 wyścigów", undefined, prog("mecze", 40)],
  ["Zdobądź komplet punktów w wyścigu (wygrana z prowadzenia)", undefined, prog("technika", 11)],
  ["Zdobądź 75 punktów łącznie", undefined, prog("punkty", 75)],
  // 26-45 · Średniozaawansowany
  ["Trenuj i ścigaj się systematycznie przez sezon", undefined, freq(2, 12)],
  ["Zdobądź 120 punktów łącznie", undefined, prog("punkty", 120)],
  ["Opanuj ustawienie motocykla pod tor (setup)", undefined, prog("technika", 12)],
  ["Zostań czołowym punktującym swojej drużyny w meczu"],
  ["Ukończ 80 wyścigów", undefined, prog("mecze", 80)],
  ["Zdobądź 180 punktów łącznie", undefined, prog("punkty", 180)],
  ["Wygraj wyścig z ostatniej pozycji (mijając rywali)", undefined, prog("technika", 13)],
  ["Awansuj do 1. ligi", undefined, prog("liga", 3)],
  ["Zdobądź 250 punktów łącznie", undefined, prog("punkty", 250)],
  ["Ukończ 120 wyścigów", undefined, prog("mecze", 120)],
  ["Utrzymaj średnią punktową 1,5+ w sezonie", undefined, prog("technika", 14)],
  ["Zdobądź 350 punktów łącznie", undefined, prog("punkty", 350)],
  ["Zajmij miejsce w czołówce 1. ligi"],
  ["Ukończ 160 wyścigów", undefined, prog("mecze", 160)],
  ["Zdobądź 450 punktów łącznie", undefined, prog("punkty", 450)],
  ["Zdobądź podium indywidualnych mistrzostw okręgu/kraju juniorów"],
  ["Utrzymaj średnią punktową 1,8+", undefined, prog("technika", 15)],
  ["Zdobądź 600 punktów łącznie", undefined, prog("punkty", 600)],
  ["Awansuj do najwyższej ligi (Ekstraliga)", undefined, prog("liga", 4)],
  ["Ukończ 200 wyścigów", undefined, prog("mecze", 200)],
  // 46-65 · Zaawansowany
  ["Trenuj z profesjonalnym zapleczem przez cały sezon"],
  ["Zdobądź punkt w meczu Ekstraligi"],
  ["Zdobądź 800 punktów łącznie", undefined, prog("punkty", 800)],
  ["Utrzymaj średnią punktową 2,0+ (solidny senior)", undefined, prog("technika", 16)],
  ["Zostań kluczowym zawodnikiem zespołu Ekstraligi"],
  ["Ukończ 300 wyścigów", undefined, prog("mecze", 300)],
  ["Zdobądź 1000 punktów łącznie", undefined, prog("punkty", 1000)],
  ["Zdobądź komplet punktów (wyścig wygrany) w Ekstralidze"],
  ["Zajmij miejsce w pierwszej ósemce indywidualnych mistrzostw kraju"],
  ["Zdobądź 1250 punktów łącznie", undefined, prog("punkty", 1250)],
  ["Utrzymaj średnią punktową 2,2+", undefined, prog("technika", 17)],
  ["Ukończ 400 wyścigów", undefined, prog("mecze", 400)],
  ["Zdobądź medal drużynowych mistrzostw kraju (DMP)"],
  ["Zdobądź 1500 punktów łącznie", undefined, prog("punkty", 1500)],
  ["Zajmij miejsce na podium indywidualnych mistrzostw kraju"],
  ["Zostań uznanym zawodnikiem swojej ligi regionalnej", undefined, prog("liga", 5)],
  ["Zdobądź 1800 punktów łącznie", undefined, prog("punkty", 1800)],
  ["Utrzymaj średnią punktową 2,4+ (czołówka krajowa)", undefined, prog("technika", 18)],
  ["Ukończ 500 wyścigów", undefined, prog("mecze", 500)],
  ["Zostań indywidualnym mistrzem kraju amatorów"],
  // 66-85 · Wyczynowy
  ["Zdobądź 2100 punktów łącznie", undefined, prog("punkty", 2100)],
  ["Wygraj mecz ligowy jako czołowy zawodnik"],
  ["Weź udział w eliminacjach zawodów o zasięgu ogólnokrajowym", undefined, prog("liga", 6)],
  ["Zdobądź 2400 punktów łącznie", undefined, prog("punkty", 2400)],
  ["Utrzymaj średnią punktową 2,5+", "Bardzo wysoki, wieloletnio wypracowany poziom.", prog("technika", 19)],
  ["Ukończ 600 wyścigów", undefined, prog("mecze", 600)],
  ["Zdobądź stałą kwalifikację do zawodów o zasięgu ogólnokrajowym", undefined, prog("liga", 7)],
  ["Zdobądź pierwsze punkty w rundzie zawodów o zasięgu ogólnokrajowym"],
  ["Zdobądź 2800 punktów łącznie", undefined, prog("punkty", 2800)],
  ["Awansuj do półfinału rundy zawodów o zasięgu ogólnokrajowym"],
  ["Zdobądź medal drużynowych zawodów o zasięgu ogólnokrajowym"],
  ["Zdobądź 3200 punktów łącznie", undefined, prog("punkty", 3200)],
  ["Utrzymaj średnią punktową 2,6+ w silnej lidze regionalnej", undefined, prog("technika", 20)],
  ["Ukończ 700 wyścigów", undefined, prog("mecze", 700)],
  ["Awansuj do finału zawodów o zasięgu ogólnokrajowym"],
  ["Zdobądź 3600 punktów łącznie", undefined, prog("punkty", 3600)],
  ["Wygraj wyścig finałowy zawodów o zasięgu ogólnokrajowym"],
  ["Zajmij miejsce w pierwszej ósemce klasyfikacji generalnej kraju amatorów"],
  ["Zdobądź 4000 punktów łącznie", undefined, prog("punkty", 4000)],
  ["Zdobądź podium rundy mistrzostw kraju amatorów"],
  // 86-99 · Elita
  ["Wygraj rundę mistrzostw kraju amatorów"],
  ["Zajmij miejsce w pierwszej piątce klasyfikacji generalnej kraju amatorów"],
  ["Utrzymaj średnią punktową 2,7+ przez cały sezon", undefined, prog("technika", 21)],
  ["Zdobądź medal drużynowych zawodów o zasięgu ogólnokrajowym"],
  ["Ukończ 900 wyścigów", undefined, prog("mecze", 900)],
  ["Zajmij miejsce na podium klasyfikacji generalnej kraju amatorów"],
  ["Wygraj kilka rund mistrzostw kraju amatorów w jednym sezonie"],
  ["Zostań wicemistrzem kraju amatorów"],
  ["Zdobądź 5000 punktów łącznie", undefined, prog("punkty", 5000)],
  ["Zdobądź indywidualne mistrzostwo kraju amatorów", "Krajowa korona żużla amatorskiego."],
  ["Obroń tytuł indywidualnego mistrza kraju amatorów"],
  ["Zdobądź wielokrotne mistrzostwo kraju amatorów"],
  ["Poprowadź kogoś przez zaawansowaną technikę jazdy żużlowej", undefined, prog("technika", 22)],
  ["Poziom mistrzowski (amatorski szczyt): wielokrotny mistrz kraju amatorów na żużlu", "Dalsze, zawodowe osiągnięcia (Grand Prix, mistrzostwa świata) potwierdzają osobne certyfikaty."],
]);
